### ISSUE TITLE
Vorta using internal Borg and not the homebrew installed version

### ISSUE THREAD

**Issue by ankit255** [borgbase/vorta#1001]
**Describe the bug**

**To Reproduce**
1. As per instructions type: brew install --cask macfuse
2. brew install borgbackup/tap/borgbackup-fuse
3. brew install --cask vorta
4. Open Vorta
5. Go to "Misc" page which shows that vorta is using borg from within its Applications/Contents/Resources/borg-dir/ directory (screenshot attached)

Expected Result: The homebrew borg is installed (default) in /opt/homebrew/bin/borg which should be used

KIND REQUEST: DO NOT MARK THIS AS SUPPORT AS THIS IS A BUG NOT JUST A ONE OFF UNLESS YOU CAN PROVE OTHERWISE.

**Environment (please complete the following information):**
- OS: Mac OS Big Sur 11.4
- Vorta version: 0.7.5
- Installed from: brew install --cask vorta
<img width="800" alt="Screen Shot 2021-05-30 at 4 04 51 PM" src="https://user-images.githubusercontent.com/5544554/120101521-0f267100-c164-11eb-86b9-a423abbebc6e.png">

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by ankit255** [comment]
As a potential hotfix: creating a symlink from homebrew's cellar to /usr/local/bin (basically copying /opt/homebrew/bin/borg to /usr/local/bin/borg) worked.
But, this needs to be addressed in the code for Vorta to look at directory /opt/hombrew/bin/borg too

**Comment by m3nu** [comment]
You're right. `/opt/homebrew/bin` isn't in our `PATH` variable for macOS yet. Added a new PR #1002 to address this.
