### ISSUE TITLE
Unable to disable "Verify repository data every X"

### ISSUE THREAD

**Issue by sandrotosi** [borgbase/vorta#1009]
**Describe the bug**
Unable to disable "Verify repository data every X", every time i click on the tick next to it, after "some time" it gets enabled again.

**To Reproduce**
1. Go to Schedule tab
2. Click on "Verify repository data every X" to remove the enabled tick
3. wait some time (this is unclear how long to wait, but it's gonna come back)
4. "Verify repository data every X" is enabled again without any further user interaction

**Environment (please complete the following information):**
- OS: Debian unstable
- Vorta version: 0.7.5
- Installed from: debian package

**Comment by m3nu** [comment]
Interesting. Thanks for reporting! Will look into it.

**Comment by m3nu** [comment]
The settings won't be saved, unless you click *Apply* below that. Maybe this is what happened?

I'm working to remove this over time and apply all setting changes right away in #908.

**Comment by sandrotosi** [comment]
OMG that's it, i was not clicking on "Apply", once i did that, the option remains unselected

**Comment by real-yfprojects** [comment]
> OMG that's it, i was not clicking on "Apply", once i did that, the option remains unselected

If this issue is resolved, please close it.
