### ISSUE TITLE
Add available .ts translation files to repo

### ISSUE THREAD

**Issue by jose1711** [borgbase/vorta#1013]
Slovak translation is available for quite a long time with a decent coverage (currently 90 % translated), yet it did not make it to the latest release.

Edit: Sorry for inaccuracy. Actually only `.ts` file is missing in source (compiled `.qm` file is present)

**Comment by m3nu** [comment]
Yes, only the `.qm` is needed for translations. Works fine here. Any issues on your side with the latest release?

![Screen Shot 2021-06-12 at 07 55 29](https://user-images.githubusercontent.com/3916435/121764251-a2dc4200-cb53-11eb-85d4-c5aa73322256.jpg)

**Comment by jose1711** [comment]
Thank you, the in-app translation is OK. Somehow I thought that `.ts` &rarr; `.qm` translation is part of the build process. For consistency it would probably be still nice if `vorta.sk.ts` is included too.

**Comment by m3nu** [comment]
True. I'll add it for the next update. It's also a good backup. I have it locally, but didn't commit it.
