### ISSUE TITLE
Changed from flatpack to backport version: newest "incremetal" backup lasted much longer than with flatpack

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#1014]
Until now I have always used the flatpack version of Vorta.

But as we have it now as backport version (vorta and Borg), I am glad that I am able to get rid of the flatpack version and can change to the backport version.

So I made this steps:
1. I opened the flatpack version.
2. I have verified the archive. (My archive has about 180 updates. No error.)
3. I have closed the flatpack version
4. I have installed the backport version of Vorta and Borg (same versions like flatpack was)
5. I have started the backport version.
6. I have added a new profile and the existing Vorta repository (from flatpack).
7. I have added the same source like in flatpack and the same exclusions
8.  I have verified the archive in the backport version. (There was no error)
9. I have made a new "incremental" backup / update.

The latest update has about the size I have expected for a daily backup. It is 208 MB. With the flatpack version I also have about 80-200 MB for the daily update.

But my daily update with flatpack lasted for about 2 minutes.So my expectation was, that with the backport version I will also take about 2 minutes for a new update.
But this first update with the backport version took now 41 minutes!

Is this normal? Why?

![Vorta Backports](https://user-images.githubusercontent.com/13977359/121713789-81d90a00-cadd-11eb-9439-fa33abba7eeb.jpg)

Thank you.

**Comment by m3nu** [comment]
> But my daily update with flatpack lasted for about 2 minutes.So my expectation was, that with the backport version I will also take about 2 minutes for a new update.
> But this first update with the backport version took now 41 minutes!

Maybe the sandboxed Flatpak version used a different cache and had to rebuild it during the first run? As long as it's fast after the first run.

**Comment by Golddouble** [comment]
Thank you. Yes, the second update is as fast as usual.

Question:
Why has the name changed in the column "name"? (See picture above).
Example: mx-2021-06-11-165655

I also like more the time format T16:56:55 than   -165655.

**Comment by m3nu** [comment]
> Why has the name changed in the column "name"? (See picture above).

The default archive name changed a few months ago to be simpler. Useful in the CLI. You already have the datetime in another column, so it's not too useful to have the datetime again in the name. If you prefer, just change it back in the horizontal tab below. Can be anything really. There are also placeholders for hostname, profile name, etc available.

**Comment by Golddouble** [comment]
Thank you for this tip.

I was not aware, that it is now possible to change the name. Is this new?

And is this the implementation of the feature I suggested here:
https://github.com/borgbase/vorta/discussions/818
?

**Comment by m3nu** [comment]
Not really, since the archive name template applies to all future archives. Notes would probably just apply to **one** archive.

As workaround, you could add a "note" to the archive name template and remove it after. That would kinda do what you ask for.

**Comment by Golddouble** [comment]
Where can I find and manipulate the template you are talking about?

**Comment by m3nu** [comment]
Under *Archives > Prune Options and Archive Naming*. Delete the field to see all possible placeholders.

![Screen Shot 2021-06-14 at 11 11 02](https://user-images.githubusercontent.com/3916435/121852966-4f0f5b80-cd01-11eb-9a6a-49246db03085.jpg)

**Comment by Golddouble** [comment]
Thank you. This is a very good workaround for the feature suggestion I made here:
https://github.com/borgbase/vorta/discussions/818

**Comment by Golddouble** [comment]
> > But my daily update with flatpack lasted for about 2 minutes.So my expectation was, that with the backport version I will also take about 2 minutes for a new update.
> > But this first update with the backport version took now 41 minutes!
> 
> Maybe the sandboxed Flatpak version used a different cache and had to rebuild it during the first run? As long as it's fast after the first run.

Does this mean, when I delete Vorta flatpack, I have also to delete any cache?
If yes: Where can I find this cache for the flatpack version?

Thank you.

**Comment by m3nu** [comment]
Usually it's `~/.cache/borg`, but for Flatpak it may be in a sandbox.

**Comment by Golddouble** [comment]
Thank you.

As I have in the meantime changed to the backport version, I assume, that I now have two caches. One for backports and one for flatpak.

> Usually it's ~/.cache/borg, but for Flatpak it may be in a sandbox.

Thank you. I have found "~/.cache/borg". It is 2.0 GiB. I assume, that this is from the backport version.

In addition I have now found ...
`~/.var/app/com.borgbase.Vorta/cache/borg/`

..., which is 1.2 GiB.

In both "caches" I have found the file "cache/CACHEDIR.TAG"

And both files have exactly the same content:
```
Signature: 8a477f597d28d172789f06886806bc55
# This file is a cache directory tag created by Borg.
# For information about cache directory tags, see:
#       http://www.bford.info/cachedir/spec.html
```

Question:
Can it be, that 
`~/.var/app/com.borgbase.Vorta/cache/borg/`
is the cache from flatpak?

My goal is just to delete the flatpak vorta/borg cache I no longer need, because I want to delete flatpak. (And I guess, only deleting flatpak does not automatically delete the flatpak cache.)

**Comment by m3nu** [comment]
> Question:
> Can it be, that
> ~/.var/app/com.borgbase.Vorta/cache/borg/
> is the cache from flatpak?

Not a Flatpak expert, but I think so. If so, you could just copy that folder to the new place if you change from Flatpak to Backports. (untested)

**Comment by Golddouble** [comment]
> Not a Flatpak expert, but I think so. If so, you could just copy that folder to the new place if you change from Flatpak to Backports. (untested)

Good idea. But it's too late, because Backports version is already in use.
I have now deleted the whole older ~/.var/app/com.borgbase.Vorta/
Pakport version seems to work nevertheless.
