### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by lawzeus** [borgbase/vorta#1017]
this is the error 

**Describe the bug**
**To Reproduce**

**Environment (please complete the following information):**
- OS:
- Vorta version:
- Installed from:

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

Platform: Darwin Amits-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64
Borg: 1.1.16  Python: CPython 3.9.5 msgpack: 0.5.6.+borg1
PID: 60193  CWD: /
sys.argv: ['/usr/local/bin/borg', 'create', '--list', '--progress', '--info', '--log-json', '--json', '--filter=AM', '-C', 'lz4', '--exclude-from', '/var/folders/41/q1hx0rjd5xzck1vl121t6b2m0000gn/T/tmp7cicg0i8', '/Users/aks/borgbackup/macbook/aks::Amits-MacBook-Pro.local-local-2021-06-16T00:56:08', '/Users/aks']
SSH_ORIGINAL_COMMAND: None

2021-06-16 01:10:56,625 - vorta.scheduler - DEBUG - Job for profile local was rescheduled.

**Comment by m3nu** [comment]
I'll close this issue, since there are literally no details attached.

If the bug happens again and you find time to fill in our bug template, feel free to open a new issue. Thanks!
