### ISSUE TITLE
Vorta does not recognize when mount is unmounted externally.

### ISSUE THREAD

**Issue by SebastianJL** [borgbase/vorta#1025]
**Describe the bug**
The software thinks that a borg archive is mounted to a mount point but it isn't. Now I cannot mount it again, because vorta want's to unmount it first. Upon clicking unmount you get the error message: "No active Borg mounts found." (See image below). Normally a restart of vorta fixes the problem but this time it doesn't. I tried doing it on purpose with the steps below for a second archive and then a restart fixes the problem, but not for the first archive.

**To Reproduce**
1. Go to Archives.
2. Select an archive.
2. Click on 'Selected Archive'
3. Click 'Mount'.
4. Select mountpoint in explorer. I selected '~/mnt/'.
4. Remove mount externally. For example via umount command.
5. Click on 'Selected Archive'
6. Click on 'Unmount'
4. See error 'No active Borg mounts found.'

**Environment (please complete the following information):**
- OS: Debian GNU/Linux 11 (bullseye)
- Vorta version: Vorta 0.7.7
- Borg version: 1.1.16
- Installed from: pip3

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

![image](https://user-images.githubusercontent.com/11479035/123092134-72858500-d42a-11eb-8669-daabcc85601e.png)

**Comment by m3nu** [comment]
Mounting is very OS-specific and we don't cover all possible cases.

To unmount, you can simply unmount the FUSE share directly. Borg only offers a convenience [wrapper](https://borgbackup.readthedocs.io/en/stable/usage/mount.html#borg-umount):

> This is a convenience wrapper that just calls the platform-specific shell command - usually this is either umount or fusermount -u.

**Comment by m3nu** [comment]
If Vorta tells you something is mounted, there may be a `borg mount` process running in the background. This is what Vorta displays here.

To resolve this, look for dead `python` or `borg` processes.

**Comment by SebastianJL** [comment]
@m3nu I couldn't find out what the problem was, but a computer restart fixed it.
