### ISSUE TITLE
Feature: Ability to sort by size when diffing

### ISSUE THREAD

**Issue by Victor239** [borgbase/vorta#1026]
Current when using Diff you can only see the file changes sorted by directories, it would be helpful to also be able to instead sort by size so that the user can easily see which particular directories or files contributed the most megabytes in a particular diff. 

It'd be helpful especially when I for example see an unexpected large diff of multiple gigabytes, but I can't easily tell which directories are contributing all of that data because many directories each contribute hundreds of little small changed files.

**Comment by Golddouble** [comment]
I have already suggested this feature here:
https://github.com/borgbase/vorta/discussions/973

> a) you could add the possibility to sort the list according to file-size

Maybe you want to vote for this there.

**Comment by m3nu** [comment]
Probably easy to add. Others have added sorting to Qt tables before. Just needs some settings added when setting up the Qt table. Most likely here: https://github.com/borgbase/vorta/blob/master/src/vorta/views/diff_result.py#L40

**Comment by real-yfprojects** [comment]
This could be done similiar to the KDE Taskmanager *KSysGuard*:

![Screenshot_20220106_194910](https://user-images.githubusercontent.com/62463991/148435254-c32fd5df-706d-40b8-9668-29fe017933bf.png)

It supports a tree view and a list/table view in which the items can be sorted by every single column.

**Comment by m3nu** [comment]
Sorting would happen by clicking the column title. Same as in the "CPU" column in your screenshot.

Your dropdown does filtering, which is a different operation.

**Comment by real-yfprojects** [comment]
The important to "filters" are `All Processes` and `All Process, Tree`. The first one is a simple list of process (in our case changes) and the second one displays the processes in a tree (like a directory tree in the diff view) and only sorts within an hierarchy.
Also a search bar might be useful in the diff view.

**Comment by Victor239** [comment]
Feature is added now https://github.com/borgbase/vorta/pull/1156

**Comment by real-yfprojects** [comment]
I don't think that one is able to sort by size at the moment.

**Comment by Victor239** [comment]
An additional UX issue is that folders aren't always colour-coded, and are usually missing a value in the `Modified` column. In this example below I had to open two subfolders in order to find out if the given size for `.code42` had been removed or added:

![](https://i.imgur.com/b4cpRRY.png)

**Comment by real-yfprojects** [comment]
I would suggest to show a signed size for indicating that and leave the modified column for the folders as is since they are not modified in this example.
