### ISSUE TITLE
[BUG] Wrong text in the tray menu 

### ISSUE THREAD

**Issue by teemue** [borgbase/vorta#1033]
**Describe the bug**
When Vorta is either getting archive contents after clicking Extract on the archive tab or restoring files from an archive, the status text in the tray menu says 'Backup in progress"

**Environment (please complete the following information):**
- OS: macOS 10.15.7.
- Vorta version: 0.7.7
- Installed from: dmg from github

**Comment by bastiencyr** [comment]
Hello, 
It seems it's a normal behaviour : 
https://github.com/borgbase/vorta/blob/ea40d7b359f3d65151503d498730fd3c3b370c49/src/vorta/tray_menu.py#L53

But I do agree that this message is not the right one. Maybe we can change this to "Task in progress".

**Comment by m3nu** [comment]
Yeah, "Task in progress" is more accurate.

**Comment by m3nu** [comment]
Fixed in #1111
