### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Bbbass6strings** [borgbase/vorta#1048]
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/peewee.py", line 6665, in get
    return clone.execute(database)[0]
  File "/app/lib/python3.8/site-packages/peewee.py", line 4121, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/vorta/views/main_window.py", line 124, in profile_select_action
    self.current_profile = BackupProfileModel.get(id=self.profileSelector.currentData())
  File "/app/lib/python3.8/site-packages/peewee.py", line 6242, in get
    return sq.get()
  File "/app/lib/python3.8/site-packages/peewee.py", line 6668, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [1, 1, 0]

**Comment by m3nu** [comment]
Please fill the bug report template in full to help reproduce errors faster.

For this case it reminds me of something that was fixed months ago. So I'd also update.
