### ISSUE TITLE
ValueError: Timezone offset does not match system offset: 10800 != 0. Please, check your config files.

### ISSUE THREAD

**Issue by RampantPanda** [borgbase/vorta#1049]
Hi,
I really don't know what I'm doing, but I tried to launch vorta and it gave me this error (and told me to file a bug report):

> ╰─λ vorta
> 2021-07-29 20:05:07,996 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
> 2021-07-29 20:05:08,002 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
> Traceback (most recent call last):
> File "/usr/bin/vorta", line 33, in <module>
> sys.exit(load_entry_point('vorta==0.7.7', 'gui_scripts', 'vorta')())
> File "/usr/lib/python3.9/site-packages/vorta/__main__.py", line 58, in main
> app = VortaApp(sys.argv, single_app=args.profile is None)
> File "/usr/lib/python3.9/site-packages/vorta/application.py", line 61, in __init__
> self.scheduler = VortaScheduler(self)
> File "/usr/lib/python3.9/site-packages/vorta/scheduler.py", line 22, in __init__
> super().__init__()
> File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
> self.configure(gconfig, **options)
> File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 131, in configure
> self._configure(config)
> File "/usr/lib/python3.9/site-packages/apscheduler/schedulers/base.py", line 702, in _configure
> self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
> File "/usr/lib/python3.9/site-packages/tzlocal/unix.py", line 165, in get_localzone
> _cache_tz = _get_localzone()
> File "/usr/lib/python3.9/site-packages/tzlocal/unix.py", line 90, in _get_localzone
> utils.assert_tz_offset(tz)
> File "/usr/lib/python3.9/site-packages/tzlocal/utils.py", line 46, in assert_tz_offset
> raise ValueError(msg)
> ValueError: Timezone offset does not match system offset: 10800 != 0. Please, check your config files.

I'm using Garuda Linux, KDE and vorta has previously worked for me.
[Here ](https://linux-hardware.org/?probe=e134bae415)is my hw-probe.

**Comment by Hofer-Julian** [comment]
Looks like a duplicate of https://github.com/borgbase/vorta/issues/1040
