### ISSUE TITLE
Implement auto option for compression

### ISSUE THREAD

**Issue by Aledosim** [borgbase/vorta#1052]
Hello!
borg have the auto option for compression when creating a new archive. It decides whether to use compression or not, which avoids compressing an already compressed file.
I'm opening this issue to track this, I pretend to contribute with code soon.
Thanks.

**Comment by bastiencyr** [comment]
Hello, 
I guess you talk about https://manpages.debian.org/testing/borgbackup/borg-compression.1.en.html
Maybe it can be the default behaviour @m3nu . I dont know how it impacts the speed of the backup and the final size.
If it is not the default behaviour, what is your idea about the UI integration ?

**Comment by Aledosim** [comment]
@bastiencyr you got it. I think a checkbox on Misc section or next to the compression options would do the job.

**Comment by bastiencyr** [comment]
Can you give some motivations about this option (backup speed ? Size backup ?) ?
Misc section is for global settings (for every profile).

**Comment by m3nu** [comment]
We won't change those options because `auto` doesn't have much benefit when using it with `zstd`. For details you can read older issues or the source code. All decisions are explained there in detail. 🤓

**Comment by RubenKelevra** [comment]
@m3nu wrote:
> We won't change those options because `auto` doesn't have much benefit when using it with `zstd`. For details you can read older issues or the source code. All decisions are explained there in detail. nerd_face

That's wrong. Using auto will try to compress with lz4 and not do a compression with zstd if it's not compacting. Meaning you won't spend (cpu) time on higher compression levels of zstd - as lz4 is much quicker than those.

In addition to saving cpu time on compression, it will also not save blocks compressed if there's no benefit - speeding up the recovery time.

*NOT* using auto with zstd makes no sense.

**Comment by m3nu** [comment]
> NOT using auto with zstd makes no sense.

Already discussed here: https://github.com/borgbase/vorta/issues/924#issuecomment-809159687
