### ISSUE TITLE
Malformed .vorta-init.json causes Vorta to crash on startup without error

### ISSUE THREAD

**Issue by phihos** [borgbase/vorta#1053]
Hi,

in my company we started to adopt Vorta with the bootstrapping feature I implemented some time ago.
I made a mistake when implementing the bootstrapping by not handling malformed JSON very well.

Steps to reproduce:
1. Close Vorta if opened.
2. Plase a file containing garbled JSON like `}` in ~/.vorta-init.json
3. Start Vorta.

What should happen is that the user is at least notified of the failed import attempt. Also the program should still be usable by simply skipping the profile import on error.
What actually happens is nothing visible. There is a stacktrace logged to console, but this does not help the average user. And then Vorta terminates.

I have already something ready and will make a PR shortly.

**Comment by m3nu** [comment]
Thanks for fixing! We always learn more, once the rubber hits the road. 😄
