### ISSUE TITLE
Vorta defaults to Russian language

### ISSUE THREAD

**Issue by johngb** [borgbase/vorta#1059]
**Describe the bug**
After following the instructions on https://vorta.borgbase.com/install/macos/ to install Vorta, and opening it for the first time, the language shown is only Russian.  I don't speak Russian, and I don't have any Russian content on my computer.  My wife does, hence me knowing that it's Russian and not just some strange character set.

**To Reproduce**
1. Go to https://vorta.borgbase.com/install/macos/
2. $ brew install --cask macfuse
3. $ brew install borgbackup/tap/borgbackup-fuse
4. $ brew install --cask vorta
5. Open vorta.app
6. Language is Russian

**Environment (please complete the following information):**
- OS: Mac OS Catalina 10.15.7 (19H524)
- Vorta version: 0.78
- Borg version: 1.1.17
- Installed from: Homebrew following the instructions linked above

[vorta.log](https://github.com/borgbase/vorta/files/7079940/vorta.log)

**Comment by m3nu** [comment]
Your computer has Russian as secondary language after British English.

`2021-08-30 23:17:54,965 - vorta.i18n - DEBUG - Loading translation succeeded for ['en-GB', 'ru'].`

This is a known issue with Qt. We can't do much about it here. If you dont' use Russian, I'd suggest removing it as secondary language in your settings.

**Comment by johngb** [comment]
Indeed, that fixed the problem.  I must have had it set from a while back when my wife used my computer for something.

Does this mean that if I ever have any other language set (when I'm learning a new language for example), that Qt will default to that instead of to English, or is it specific to Russian?

**Comment by m3nu** [comment]
Not sure about that, since I couldn't reproduce the issue here after adding Russian as secondary language.

My theory is that pure language without country (like `ru`) are matched before languages with country preference (e.g. `en_US`). Your English was `en_GB`, which might get matched AFTER `ru` for some reason. `en_US` is our app default, so maybe that's why it's used anyway.

In the end we use pure Qt to match the language and I don't think we should reimplement it. Hope it gets fixed at some point.

**Comment by johngb** [comment]
@m3nu That's a good suggestion.  I tested it out, and if I add Portuguese (Portugal) as a secondary language, Vorta doesn't switch to Portuguese.  Unfortunately on Mac OS there's no option for "Russian (Russia)" as a language, so I'll take it up with the Qt guys to see if they have a solution.

> In the end we use pure Qt to match the language and I don't think we should reimplement it.

Absolutely.  At least I know where the problem is coming from now, and can do something about it.  Thanks a ton for your help.
