### ISSUE TITLE
Fata Error - uncought exception for "Update data for each entry"

### ISSUE THREAD

**Issue by VosaXalo** [borgbase/vorta#1060]
```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/views/source_tab.py", line 154, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/app/lib/python3.7/site-packages/vorta/views/source_tab.py", line 100, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.Type).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'
```

Note: if I exit from Vorta and run it again, the error doesn't happen.

I'm using Vorta on a Linux PC with KDE Neon 20.04, installed via flatpak.

**Comment by bastiencyr** [comment]
Hello @VosaXalo ,
Seems to be a duplicate of #1034, can you reproduce this error ?

**Comment by VosaXalo** [comment]
Hello @bastiencyr ,
the problem is quite similar as the one described in #1034. 
I'm not 100% sure, but it seems that this happens after I reactivate my PC from the suspension. To resolve is sufficient to close Vorta and run it again.

**Comment by m3nu** [comment]
If it's a duplicate or similar, let's discuss it there. Even better if you found a way to reproduce #1034.

**Comment by VosaXalo** [comment]
Ok @m3nu thank you.
