### ISSUE TITLE
Mac M1 : Vorta does not automatically start at login

### ISSUE THREAD

**Issue by uselpa** [borgbase/vorta#1064]
**Describe the bug**
Vorta does not start at login, even if the corresponding checkmark is set.

**To Reproduce**
Manually adding Vorta to "Preferences / Users & Groups / Login Items" appears to work for a second or two, but the Vorta disappears again from the list.

**Environment (please complete the following information):**
- Macbook Air (M1, 2020)
- OS: Big Sur 11.5.2
- Vorta version: 0.7.8 / borg 1.1.7
- Installed from: homebrew

**Comment by bastiencyr** [comment]
Hello @uselpa , 
Im not familiar with Mac, In Misc Vorta did you check "Automatically start Vorta at login" ?

**Comment by uselpa** [comment]
Yes indeed (see attached).

**Comment by m3nu** [comment]
Logs would be useful. I suspect there is something in the system logs.

We use PyObjC to edit login items. Maybe something changed here. It's in `autostart.py`

**Comment by m3nu** [comment]
Also, still works on my 2017 Intel Mac. So someone else would need to debug this.

**Comment by uselpa** [comment]
Hi,
attached the log I suppose you expect. At 10:00 am I deactivated/reactivated the startup bot it does not show in the logs, nor anywhere else I looked.
I suppose that manually creating a launchd User Agent starting /Applications/Vorta.app/Contents/MacOS/vorta-darwin should do?
Regards,
-Patrick

**Comment by uselpa** [comment]
Regarding `autostart.py`, it says: "On macOS, this function adds/removes the current app bundle from Login items".
Manually adding Vorta to Login Items does not work (I tried that at first, see my first message).

I now manually created a plist in ~/Library/LaunchAgents, loaded it vie `launchctl`, and this appears to work (and should work on any macOS and both Intel and M1 Macs).

**Comment by m3nu** [comment]
I believe `launchctl` is different from user login items?

**Comment by uselpa** [comment]
Yes indeed. I just came across this explanation: https://eclecticlight.co/2021/09/16/how-to-run-an-app-or-tool-at-startup/

FWIW, here's my config file for launchctl. For a normal deployment, KeepAlive should probably be false, and the Label should be different of course. (Disclaimer: I am not an expert on the subject).

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>    <true/>
	<key>Label</key>        <string>lu.usel.Vorta.plist</string>
	<key>ProcessType</key> 	<string>Interactive</string>
	<key>ProgramArguments</key>
	<array>
		<string>/Applications/Vorta.app/Contents/MacOS/vorta-darwin</string>
	</array>
	<key>RunAtLoad</key>    <true/>
</dict>
</plist>
```

**Comment by jetchirag** [comment]
I tested this on M1 Air, Monterey 12.2.1 with vorta version 0.8.11, also installed with homebrew and this feature is working fine for me.

**Comment by m3nu** [comment]
Thanks for testing, @jetchirag . The code for this feature was also adjusted to avoid alerts every time. So there shouldn't be an issue any more.

Closing this, since it's also 2 years old.
