### ISSUE TITLE
Change keys label name in password manager

### ISSUE THREAD

**Issue by bastiencyr** [borgbase/vorta#1065]
**Environment (please complete the following information):**
- Vorta version: Latest

Hello, 
The name format of keys in the key manager is '/home/user/repo_path'. Other applications give a more appropriate name like "Nextcloud", "Pika Backup Password"... At least, "Vorta' should appear in the name. Maybe "Vorta Backup Password" or "vorta.backup.path_to_repo" for description field. It should be easy since we just need to add a label to the keys and label is not needed to retrieve keys. 

Only for dev, I just noticed that there are a lot of  keys added in my repo manager which start by "vorta-test-repo...". I don't know if it is a bug but it would be nice for dev to provide a way to remove this tests repo. I have something like 650 entries 'vorta-test-repo...' in my default  password manager (gnome-keyring) :(

**Comment by m3nu** [comment]
Good observation. I also have a good deal of entries in my Keychain. Would make sense to remove those after a test.

**Comment by real-yfprojects** [comment]
> The name format of keys in the key manager is '/home/user/repo_path'. Other applications give a more appropriate name like "Nextcloud", "Pika Backup Password"... At least, "Vorta' should appear in the name. Maybe "Vorta Backup Password" or "vorta.backup.path_to_repo" for description field. It should be easy since we just need to add a label to the keys and label is not needed to retrieve keys.

Is this still/really a problem? 

In KWallet the entries are stored in a folder called `Vorta`. Like that it is easy to recognise the keys are from vorta while the name of the keys being the repo path allows finding them fast. Adding Vorta in front of all these paths won't add any use in KWallet from my point of view.

I can see in the code that vorta adds `application` data to the key when using secretstorage. This might lead to similiar behavior of the keyring used.

**Comment by bastiencyr** [comment]
> In KWallet the entries are stored in a folder called Vorta. Like that it is easy to recognise the keys are from vorta while the name of the keys being the repo path allows finding them fast. Adding Vorta in front of all these paths won't add any use in KWallet from my point of view.

Its true. I just realized that this issue only concerns gnome (secretstorage) and maybe Mac. The implementation is different from Gnome to Kde, you can see in the source code a folder named "keyring". What you call folder is "collection" in gnome secretstorage and the current implementation use the default collection. Thats why there is not folder on my computer but there is one on your computer.

application key is just a label that doesnt appear directly on the gui and doesnt imply creating folder. This a a screenchot :

![image](https://user-images.githubusercontent.com/63359575/148538258-3c74e2d9-f489-4374-b993-ac312a3eeb65.png)

The application label only appear if I click on the password.
The entries with the format vorta-test-repo.aaaa:repo are created by pytest and, as it is said above, there are many of them. "/tmp/asdf" is created by vorta

**Comment by real-yfprojects** [comment]
> I also have a good deal of entries in my Keychain. Would make sense to remove those after a test.

For that the keyring API should support deleting keys from the key chain.
