### ISSUE TITLE
Wrong folder removed when the same folder is in 2 different profiles

### ISSUE THREAD

**Issue by bastiencyr** [borgbase/vorta#1073]
Hello,

1. Create 2 profiles : profile 1 and profile 2
2. Add the same  backup folder for the 2 profiles. For example /home/bastien/doc 
3. Go to profile 1 and remove the folder /home/bastien/doc from source folders and then recalculate size
4. Go to profile 2. /home/bastien/doc is not there anymore.
5. Go back to profile 1 : /home/bastien/doc is back !

If you just add /home/bastien/doc to profile 1 and profile 2, notice that the size is not there for one of the profile.

- Vorta version: latest stable. 0.7.8

**Comment by bastiencyr** [comment]
The second part of the issue doesnt seem to be solved. If I add the same folder in two different profiles, so one of the profile doesnt show the size of the folder

**Comment by m3nu** [comment]
Uh, must have overread the second part. Will revisit it.
