### ISSUE TITLE
Remove type column in source folders and add icon.

### ISSUE THREAD

**Issue by bastiencyr** [borgbase/vorta#1074]
Hello, 

Suggestion of UI :

![image](https://user-images.githubusercontent.com/63359575/136474258-2c14a6fe-0592-4053-8a2f-a583584a6ea0.png)

Add a different icon for files
And so remove type column

And  is it really useful to keep the number of files? What is the use case ?

**Comment by real-yfprojects** [comment]
> And is it really useful to keep the number of files? What is the use case ?

I know a stupid use case: Testing exclude patterns I used the file count to see how many files are matched.

**Comment by real-yfprojects** [comment]
The Type column was removed by #1176. I think this can be closed.

**Comment by m3nu** [comment]
Can’t you close issues with your current permissions? If not we should change that.

**Comment by real-yfprojects** [comment]
> Can’t you close issues with your current permissions?

No, I don't have any (special) permissions on this repository.

**Comment by m3nu** [comment]
Oh. Lets change that.

**Comment by real-yfprojects** [comment]
> Oh. Lets change that.

Thanks. This means a lot to me.
