### ISSUE TITLE
Show archive action menu

### ISSUE THREAD

**Issue by xFr3d** [borgbase/vorta#1075]
Error message:

```
File "/usr/lib/python3.9/site-packages/vorta/views/archive_tab.py", line 122, in showArchiveActionMenu
unmountAction = menu.addAction("Unmount".self.job_umount_action)
AttributeError: 'ArchiveTab' object has no attribute 'job_umount_action'
```

- OS: Archlinux
- Vorta version: 0.7.8
- Installed from: AUR

**Comment by bastiencyr** [comment]
Hello @xFr3d , 
Thanks for reporting that but how did you install vorta. The error you have is clearly related to #1045 which is not in 0.7.8 yet.

**Comment by bastiencyr** [comment]
Perfect !
Thanks for the bug, it would be in 0.8.0 without your reporting.
