### ISSUE TITLE
Pass through borg error message for all commands

### ISSUE THREAD

**Issue by derphilipp** [borgbase/vorta#108]
**How to reproduce:**
* Remove your rights on your borg cache files (this stems from running borg with sudo)
* Try to add existing repo with vorta

**Result:**
An error message is displayed extremely short but is immediately replaced with a generic error message. Here a popup of the original log would be helpful. (Example: "Borg cli failed and output the following: ...")

**Workaround:**
Look inside the log-file, here you can clearly see the error

**Comment by m3nu** [comment]
Agree. This could be solved better. For errors, the last message should stick. This is the case for some commands, but not all.

**Comment by m3nu** [comment]
Closing this in favor of #375 , which has more details on the same topic.
