### ISSUE TITLE
Can't set prune keep to values over 99.

### ISSUE THREAD

**Issue by lstrz** [borgbase/vorta#1082]
**Describe the bug**
The input field for prune keep values has a two digit limit. Borg on the command line has no such limit. 

**To Reproduce**
1. Go to the "Archives" tab.
2. Click on the "Prune Options and Archive Naming" subtab.
3. Click the first "Keep" field.
4. Try typing a value over 99 (this fails due to the bug).
5. Type in 99. The up arrow greys out (this shouldn't be so), making you unable to increase the value beyond 99. 

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Vorta version: 0.7.8
- Installed from: pip3

**Comment by bastiencyr** [comment]
Hello @lstrz , 
What is your use case ? 
99 is already a big number and maybe it does not make sense to do more (for example 100 yearly is more than a human can live...). 

But if you want more than 99, you can set -1 that means infinite. Between 99 and infinite, yes you can't set a number.
