### ISSUE TITLE
Vorta won't launch with latest python-tzlocal (version 4.0.1-1)

### ISSUE THREAD

**Issue by Pierrep56** [borgbase/vorta#1083]
Latest Vorta version (0.7.8.) does not launch on Arch based distro with actual python-tzlocal version updated to 4.0.1.

To reproduce:
1) Install vorta from AUR (vorta-git has the same issue at the moment)
2) open a terminal and run "vorta"
3) you'll get an output ending with wrong required version of python-tzlocal 

Workaround:
The actual version of python-tzlocal is 4.0.1-1.
Downgrade to 2.1 and vorta can be launched again.

**Comment by nrbeaton** [comment]
Same issue!

`python-apscheduler` (https://archlinux.org/packages/community/any/python-apscheduler/) has been flagged out of date, is that causing the issue?

**Comment by stephensrmmartin** [comment]
I re-installed my updated apscheduler package and launched vorta:

```
2021-10-21 09:55:32,327 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.7.8', 'gui_scripts', 'vorta')())
  File "/usr/lib/python3.9/site-packages/vorta/__main__.py", line 57, in main
    from vorta.application import VortaApp
  File "/usr/lib/python3.9/site-packages/vorta/application.py", line 17, in <module>
    from vorta.scheduler import VortaScheduler
  File "/usr/lib/python3.9/site-packages/vorta/scheduler.py", line 5, in <module>
    from apscheduler.schedulers.qt import QtScheduler
ModuleNotFoundError: No module named 'apscheduler.schedulers.qt'

```

**Comment by m3nu** [comment]
I'm aware that we can't use apscheduler in the future and already started adding our own scheduler, since our use case is fairly simple. But not finished yet.

Currently we pin the apscheduler version to below 4 [here](https://github.com/borgbase/vorta/blob/master/setup.cfg#L45).
