### ISSUE TITLE
Doesn't run commands

### ISSUE THREAD

**Issue by Liemaeu** [borgbase/vorta#1103]
I added pre- and post-commands, but Vorta doesn't run them.

My pre-command (shell script) opens something in xterm (xterm -e "sh -c 'command' "). First I got the error "pre-backup command return non-zero exit code" what I could fix by adding a "exit 0" at the end of my script. Now the backup starts, but my commands in the script weren't executed (xterm window didn't show up), the backup started just immediately.

I use the same scripts in grsync, they work fine there.

I'm using Vorta (Flatpak) on Ubuntu 20.04.

**Comment by Liemaeu** [comment]
Same at the post-command. E.g. I save the installed packages with the command `dpkg --get-selections > /media/richard/BackupFestplatte/Pakete/Package.list`. The file was actually created, but it's empty.

**Comment by m3nu** [comment]
Since your script did run at first (but with an error), the issue could be with the combination of Flatpak and a window manager. Maybe this is just not allowed from the sandbox?

Have you tried using e.g. the Python package directly without Flatpak?

**Comment by Liemaeu** [comment]
The Python package works! Thank you very much!
