### ISSUE TITLE
Improvement request: Prune based on profile instead of --prefix

### ISSUE THREAD

**Issue by geckolinux** [borgbase/vorta#1106]
Hi there, I recently switched to a different computer with a different hostname, but I transferred my entire `/home` directory to it and it has the same username and UID and the same SSH key. So Borg still works with my existing Vorta profile but with different prefix names:

![Screenshot from 2021-11-12 10-32-23](https://user-images.githubusercontent.com/2692138/141492433-ef426ac9-7c47-481b-a922-40d1ecd25d73.png)

I just ran a prune job with Vorta, but it obviously didn't prune the archives with the older prefix:
`/usr/bin/borg prune --list --info --log-json --keep-hourly 2 --keep-daily 7 --keep-weekly 4 --keep-monthly 6 --keep-yearly 2 --prefix IntelNUC9-intelnuc9-nas-`
Would it be possible to make Vorta run the prune on all the archives visible in a given profile regardless of their prefix name?

Thanks!

**Comment by m3nu** [comment]
Have you tried keeping the *Prune Prefix* empty under *Archives > Prune Options*? If this doesn't work, we could update the behavior?

OTOH having an empty prefix could be dangerous and prune too much. So it may not work as of now and there could be reasons against it.

**Comment by geckolinux** [comment]
> Have you tried keeping the _Prune Prefix_ empty under _Archives > Prune Options_? If this doesn't work, we could update the behavior?

Ah, thanks! I hadn't even seen that. Seems to work great by removing the prune prefix.
