### ISSUE TITLE
Vorta backup scheduling error: archive already exists

### ISSUE THREAD

**Issue by ruffson** [borgbase/vorta#1115]
**Describe the bug**
Since a few days I am getting notifications that backups with Vorta failed: "Error during backup creation".

When I open Vorta, it says that the archive "already exists" (see screenshots below).
It seems that the scheduler starts the backup twice when it should start it only once.
I have set it to "every 3 hours" and as you can see in the screenshot showing the log, it is started twice per the 3 hour time slot with only a few minutes delay.

I initially thought that there were maybe two Vorta instances running but this error has persistent through several reboots and restarts of Vorta.

When I do a manual backup (as can be seen in the screenshot at 12:11) it works as expected.

**To Reproduce**
1. Set schedule to 'every 3 hours'
2. Wait
3. Observe error
4. Bath in misery

**Environment (please complete the following information):**
- OS: Fedora 35 (also observed in Fedora 34).
- Vorta version: v0.8.0, Borg version: 1.1.15
- Installed from: flathub

**Additional context**

Schedule Log
![vorta1](https://user-images.githubusercontent.com/1185812/142300857-1c67a2a5-67e8-4dbe-84d7-8ca9f5ce628b.png)

Actual Schedule
![vorta2](https://user-images.githubusercontent.com/1185812/142300864-8cc81c58-ba74-4219-b062-86c37e3bc2d1.png)

Added a log with the time around when it happened last.

[vorta.log](https://github.com/borgbase/vorta/files/7558726/vorta.log)

**Comment by m3nu** [comment]
Yes, this happened in an early version of the scheduler. Already fixed in v0.8.1 and the current Github master branch.

**Comment by m3nu** [comment]
If the problem still happens with the latest version, please comment here. Else I'll close this issue for now.

**Comment by ruffson** [comment]
Thank you! I will patiently wait for the release on flathub.

**Comment by m3nu** [comment]
Flathub should be updated automatically from Github. Not sure. @Hofer-Julian is in command there.

**Comment by m3nu** [comment]
Already updated, I think. Says version 0.8.1 [here](https://flathub.org/apps/details/com.borgbase.Vorta)

**Comment by ruffson** [comment]
> Already updated, I think. Says version 0.8.1 [here](https://flathub.org/apps/details/com.borgbase.Vorta)

It is indeed! Sorry I swear I tried updating before posting the issue. Thanks for your help!
