### ISSUE TITLE
Next Backup time under the schedule tab is never updated

### ISSUE THREAD

**Issue by DanHam** [borgbase/vorta#1116]
**Describe the bug**

When using scheduled backups the value for 'Next Backup' is never updated after the first run.

![70vorta](https://user-images.githubusercontent.com/4364798/142396971-5a26fe9d-5ffb-4336-83de-5c8ab66ec548.png)

The current date/time is `2021-11-18 10:17`

The next backup is **actually** scheduled to run: `2021-11-18 11:00`. This runs as expected.

The `Next Backup` field under the `Schedule` tab is displaying: `2021-11-17 14:00` which is clearly incorrect.

The value is never updated after the first time a scheduled backup is set.

The next scheduled backup **is** shown correctly when right clicking the Vorta icon in the panel - I believe this was fixed by #1099 

**To Reproduce**

1. Set up a scheduled backup
2. Let the scheduled backup run
3. Check the value of the `Next Backup` field under the `Schedule` tab - this will be incorrect and will continue to display the first scheduled backup time indefinitely.

**Environment:**

- OS: Arch Linux
- Vorta version: 0.8.1
- Installed from: Arch AUR. `pacman -Q vorta-git` outputs: `vorta-git r578.0dafa9d-1` (Built from 0dafa9d)
- Borg version: 1.1.17

**Comment by m3nu** [comment]
Thanks for the great report. This was already pointed out, but it didn't seem like very high priority. Will try again to fix it anyways.

**Comment by DanHam** [comment]
@m3nu @real-yfprojects Thank you!
