### ISSUE TITLE
New scheduling option - on boot

### ISSUE THREAD

**Issue by voltaicforge** [borgbase/vorta#112]
For a general desktop PC, I think a option to have a 'backup at boot' option in Vorta avaliable.

For now, a desktop user is best to either backup every few hours or leave the PC on at night to backup at night.

Having an option to backup at boot would be nice as well, to ensure that every time the PC is booted a backup sync will occur.

This would be achievable using borg via a system init script - but a option it Vorta would improve ease of use.

**Comment by ThomasWaldmann** [comment]
I once had a commercial windows backup tool that offered backups at boot/shutdown.
It was a pain, both ways, esp. if there is no way to interact with the process.

So the only thing that might make sense is to do it a bit after boot (or log in) and after displaying a notification with the option to abort/delay it (delay e.g. to have enough time to plug in your usb backup disk).

**Comment by m3nu** [comment]
I'm skeptical too. Vorta will only know about its own *startup*, not the system *startup*. There could be an option to run a backup at startup.

Other integration, like init-scripts is system-specific and up to the distributions.

**Comment by m3nu** [comment]
In addition, who restarts their machine? Isn't hibernation more common now? Then you'd need another "Backup after Wakup".

**Comment by bpereto** [comment]
hm in my usecase my laptop needs a regular backup, so I would look for a option to start a backup after the "next backup" schedule passed (ex. after resume from hibernation) and/or schedule criteria is met.
At the moment I have configured a daily backup and my laptop is missing the schedule all the time :)

**Comment by ThomasWaldmann** [comment]
an easy workaround could be to try backups much more often and set the prune policy to keep what you really want to keep.

as the changes between more frequent backups are expected to be even smaller than with daily backups, it should be rather quick.

**Comment by m3nu** [comment]
Knowing about hibernation and reboot would be very system-specific. Since there is an easy workaround (short backup interval), I'll close this for now. If someone has very strong feelings about this feature, feel free to comment here and I'll reopen.

**Comment by mxmehl** [comment]
Can we still do it like anacron? Have a preferred time, e.g. 10:00 in the morning, but catch up if the computer is first started at 11:00? 

This way, one can still have daily backups even if the computer isn't running at the scheduled time.

**Comment by m3nu** [comment]
Vorta doesn't know about the computer sleeping and letting it know about it would be different for each platform. For your case, I'd suggest to just set the backup to every 3 hours or so.

**Comment by mxmehl** [comment]
> Vorta doesn't know about the computer sleeping and letting it know about it would be different for each platform. For your case, I'd suggest to just set the backup to every 3 hours or so.

Well, how does anacron manage to get a task done once a day? AFAIK it saves the last time it ran to a file. Wouldn't the same be possible for vorta?

Many users will want a backup to run daily, not up to 8 times a day like you suggested. I feel like this isn't some crazy wish but a common requirement for a backup tool...

**Comment by ThomasWaldmann** [comment]
@mxmehl you know that a backup with borg is rather quick if you don't have many / big changes? So doing multiple backups a day is not as bad / as big effort as it sounds. A few days later, you can already prune away again most of these backups, so you won't end up with a huge total amount of backups.

Just wanted to say, if you are coming from other tools you might have a wrong impression / non-matching experience here.

**Comment by mxmehl** [comment]
Thanks for the info. I personally might find a way to get the expected experience. 

But less tech-savvy users who switched from other backup tools (because we tell them how great borg/vorta is!) will expect a tool which enables them to backup once a day, not multiple times, and not once every 2 days because of differing switch-on times.

That's why I propose to make this possible in the sake of user experience.

**Comment by m3nu** [comment]
Currently the scheduling is done in an external package - `apscheduler`. It actually allows to set the maximum allowable delay for a job. This is needed for when the thread sleeps and doesn't precisely wake up at the right time. Currently this is set to 2min or so.

Setting this to a very high value would achieve the behavior you describe. It would still need some tweaks to avoid running hourly jobs multiple times.
