### ISSUE TITLE
Changelog for v0.8.1?

### ISSUE THREAD

**Issue by daPhipz** [borgbase/vorta#1121]
Hello!
I have installed Vorta as a Flatpak from Flathub. The current version there is `0.8.1`, which I have got installed.
However, I can see that the latest release here on GitHub is `0.7.8`, released on Aug 26. Is there a specific reason behind this?
Where can I see the changelog for my current version?

**Comment by m3nu** [comment]
https://github.com/borgbase/vorta/releases

**Comment by daPhipz** [comment]
Thwnks - but why is a pre-release being pushed out to the main flatpak branch? I would rather use a stable version...

**Comment by m3nu** [comment]
Not many people will try the Github master branch. So we need to publish everything to Flatpak an PyPi to get enough feedback. There were also urgent issues with Python 3.10 and an external dependency, which won't be resolved in the 0.7 branch.

**Comment by daPhipz** [comment]
Ah I see. Thanks for the info!
