### ISSUE TITLE
Can't mount backup archives anymore

### ISSUE THREAD

**Issue by pentago** [borgbase/vorta#1122]
I'm using latest MacOS and Macbook Pro M1 and it seems that we're not able to mount backup archives anymore due to missing dependencies.

I'm getting the following error:
`ERROR: borg mount not available: loading FUSE support failed [ImportError: No module named 'llfuse']`

Is there any officially recommended way of solving this so we're able to backup archives again?

thanks!

**Comment by m3nu** [comment]
I assume you already installed Borg with FUSE support and also installed MacFUSE?

More: https://github.com/borgbackup/homebrew-tap

**Comment by pentago** [comment]
I do have MacFUSE but I just checked the borg installation docs and found that I don't use FUSE-patched version of borg.
Doing `brew install borgbackup/tap/borgbackup-fuse` solved the issue 👍🏼

**Comment by m3nu** [comment]
Glad this solved it. Closing this issue.
