### ISSUE TITLE
Vorta crashes on 'permission' denied while calculating directory size

### ISSUE THREAD

**Issue by commandline-be** [borgbase/vorta#1126]
**Describe the bug**

Vorta crashes on 'permission' denied while calculating directory size

**To Reproduce**
1. Add sources
2. Add a folder where a sub folder is not owned by the user running vorta

**Environment (please complete the following information):**
- OS: Ubuntu 21.10
- Vorta version: 0.78
- Borg version 1.1.17
- Installed from: Ubunt repo

Vorta and Borg versions can be found in Main Window > Misc Tab.
[exported-vorta.log](https://github.com/borgbase/vorta/files/7653915/exported-vorta.log)
[exported-vorta.log](https://github.com/borgbase/vorta/files/7653916/exported-vorta.log)

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by m3nu** [comment]
Please update to the latest version 0.8.2 and let us know if the issue still occurs.

**Comment by commandline-be** [comment]
thanks, that worked, should have though of that myself

**Comment by m3nu** [comment]
No worries. Still thanks for reporting.👍
