### ISSUE TITLE
Untranslatable Miscellaneous tab - source strings missing in lang files

### ISSUE THREAD

**Issue by p-bo** [borgbase/vorta#1129]
**Describe the bug**
See title of this report

**To Reproduce**
1. Start Vorta in non-English lang (some, which is translated completely, eg. Czech)
2. See texts in app translated (and few not, because they are coming from backend components/libraries probably?)
3. Go to Miscellaneous tab (last tab, in mentioned Czech it is "Různé")
4. See, that sentences here are still in English
5. Go to source code of app and try to find these English strings in some .ts file
(for instance in https://github.com/borgbase/vorta/blob/master/src/vorta/i18n/ts/vorta.cs.ts )
6. Conclude, they aren't here (something is wrong regarding strings extraction from source code)

Wish: Would it be possible to look for other strings, which are part of Vorta and not appearing as source strings in lang files too please?

**Environment (please complete the following information):**
- OS: Ubuntu 20.04
- Vorta version: 0.8.2 (see attached screenshot)
- Installed from: Flatpak

![untranslatable_miscellaneous](https://user-images.githubusercontent.com/12208593/144765673-1e0853f0-d251-4865-aec9-97e442093209.png)

**Comment by m3nu** [comment]
Thanks for pointing this out! Indeed, this source code file was missing from the path we search for translations. I've now added it and uploaded to Transifex. After it's translated there, it will be included in the next release.

No change to our source code is needed. This was an issue in the Makefile I use for admin tasks.

**Comment by p-bo** [comment]
Thanks for solving this! :-)
(did my part for Czech on Transifex already - strings were translated in past, thus present in translation memory)
Closing

**Comment by m3nu** [comment]
Thanks a lot for adding the translations. Currently we don't have many PRs planned, but I'll do a translation update, if it takes too long.
