### ISSUE TITLE
Can't add existing repo with repokey encryption enabled, but empty password

### ISSUE THREAD

**Issue by derphilipp** [borgbase/vorta#113]
**Describe the bug**
Using encryption, but with an empty password is a bad idea, but possible with borg. ~Borgmatic~ Vorta fails to work with it and reports wrong password

**To Reproduce**
1. Create repo, with encryption
2. When asked for password just hit return ("")
3. Try to use sorta

**Desktop (please complete the following information):**
 - OS: macOS

**Workaround**
- Change password to anything else. Probably a good idea anyway.

**Comment by ThomasWaldmann** [comment]
You meant "vorta", but wrote "borgmatic"?

**Comment by derphilipp** [comment]
Valid security decision. Good point!
