### ISSUE TITLE
Use StrictHostKeyChecking=accept-new for all connections

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1134]
We use `StrictHostKeyChecking=no` currently for adding new repos only. For all other connections, we have strict checking.

Maybe this one is even better.

**Comment by m3nu** [comment]
The openssh version required was released in Oct 2017, so should be widely supported by now.

**Comment by delfino-nunez** [comment]
So what you are trying to do here is to prevent adding a key if it was changed?
Only add the key for new hosts and not existing ones right?

> We use StrictHostKeyChecking=no currently for adding new repos only

I see that `StrictHostKeyChecking=no` is used on initJob and InfoRepoJob, you mean it should only be changed when doing the init of a new job or also in the info?

**Comment by m3nu** [comment]
It should work if the key was never seen, but fail if a known key changed.

The suggestion here is to use `StrictHostKeyChecking=accept-new` instead of `StrictHostKeyChecking=no`. All other calls already reject a changed key.
