### ISSUE TITLE
Feature: when diffing 2 archives, show size at the directory level too

### ISSUE THREAD

**Issue by sandrotosi** [borgbase/vorta#1140]
Hello,
when i diff 2 archive, the size difference is only shown at the file level; that makes it hard to know which directories contain the most changed files/size, which is a valuable information.

Can you extend the diff tree to show the diff size also at the directory level, and not only at the file level?

thanks!

**Comment by m3nu** [comment]
We don't get this data from Borg, so it would need summing up the files while building the tree. Could work because the current data model is relatively well suited to do this. Would just be one more step when adding more items to the parent tree object.

**Comment by m3nu** [comment]
Fixed via #1156
