### ISSUE TITLE
Bug when pressing the extract button

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#1141]
**Describe the bug**
After pressing the export button, I got the following message:
```
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/archive_tab.py", line 416, in list_archive_result
    window = ExtractDialog(result['data'], archive)
  File "/usr/lib/python3/dist-packages/vorta/views/extract_dialog.py", line 42, in __init__
    for line in fs_data.split("\n"):
AttributeError: 'dict' object has no attribute 'split'
```

**To Reproduce**
1. open Vorta
2. make a new profile
3. make a new repository without encryption and password. Source is an external HDD
4. create the line "/home/Golddouble/losch.txt" in source tab (So I only make a backup of one file. It is 19 Bytes.)
5. start the backup -> Works as expected
6. tab Archive->sanpshot->extract
7. Now this error appears:

**Environment (please complete the following information):**
- OS: MX Linux 19.4 (Xfce) Debian 10 based
- Vorta version: 0.7.5 (Debian Backports)
- Installed from: MX Linux package installer (Debian Backports)

Thank you for reproducing this and your feedback.

Hint:
I use the same Vorta version with another profile and repository for my daily backup of my home without an issue. And I also were able to extract in this other profile. I just wanted to try out anything and to make an experiment in an new profile and run into this issue. Very strange.

Edit:
Vorta mounting button works.

**Comment by Golddouble** [comment]
I have not this issue with Vorta 8.2 (flatpack)

**Comment by Golddouble** [comment]
There is a workaround for Vorta 0.7.5:
In Step 4) (see first post) we have to add first a folder. Afterwards we can add a single file like "/home/Golddouble/losch.txt". So no issue more, when trying to extract.

**Comment by m3nu** [comment]
Yeah, probably an issue with parsing the file list, if it's empty. Good to know it's fixed already in the current version.
