### ISSUE TITLE
How to find out why Vorta backups of a few weeks went missing

### ISSUE THREAD

**Issue by mYnDstrEAm** [borgbase/vorta#1151]
**Describe the bug**
Vorta backups of a few weeks went missing. I'd like to find out why. I may not notice if Vorta doesn't carry out its backups for a day or so but not for weeks - I'm pretty sure it did backups during this time so they must have been deleted or something similar.

I have configured the pruning options so that they shouldn't be deleted, have many backups from earlier times (just none during these few weeks) and there are no log entries for the time during these weeks either. Maybe somebody here has experienced something similar or has a recommendation of what one could check.

The last few backups that went through had returncode '2' - what does that mean? All backups since a recent restart after kernel upgrade (Debian 11 upgrade) are displayed again. It looks like [bash history entries went missing after the restart](https://unix.stackexchange.com/questions/582401/how-to-prevent-missing-entries-in-bash-history-possibly-due-to-lack-of-disk-s) too (at least that's when I noticed it) but I could restore them using even older Vorta backups. I searched the syslog but couldn't find anything so far (any ideas what to look for?).

**To Reproduce**
unknown

**Environment (please complete the following information):**
- OS: Debian11/KDE
- Vorta version: 0.7.7
- Installed from: via pip3

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
So far the only thing in the syslogs that may be relevant I could find is:

```
systemd-xdg-autostart-generator[2465]	Configuration file /home/username/.config/autostart/com.borgbase.vorta.desktop is marked executable. Please remove executable permission bits. Proceeding anyway.
systemd-xdg-autostart-generator[2465]	/home/username/.config/autostart/com.borgbase.vorta.desktop:17: Unknown key name 'TerminalOptions' in section 'Desktop Entry', ignoring.
```
which were logged right after the restart (backups after which are displayed again in the Vorta Archive).

**Comment by m3nu** [comment]
Return code 2 is a failed Borg command. You can view the logs to see the precise message. Can be found under *Misc > Log*.

**Comment by mYnDstrEAm** [comment]
Thanks, that's helpful. The logs of the last backup a few weeks ago has `OSError: [Errno 28] No space left on device` (as well as many permission denied errors which would need Vorta to support root backups). However, that shouldn't be the cause of it as I'm fairly sure that there was enough disk space many times during these weeks, that the backups ran at least several times and that I haven't freed up disk space after rebooting after the kernel upgrade.

**Comment by mYnDstrEAm** [comment]
Maybe it was a problem with the cache. In any case there should have been notifications about backups failing and I do think that errors went through. Maybe it was a problem of SSD of a SSHD failing(?)  
Beyond potential improvements to logging, it probably isn't easy (if possible at all) or important for Vorta to close this issue...nevertheless more and better logs and making sure those logs aren't deleted or changed could be important.
