### ISSUE TITLE
Linux | KDE | Vorta fails to autostart

### ISSUE THREAD

**Issue by fredcwells** [borgbase/vorta#1152]
**Describe the bug**
Vorta fails to automatically start on login when enabled. 

**To Reproduce**
1. Start Vorta
2. Select '_Automatically start Vorta at login_' from Misc tab
3. Logout then login
4. Observe Vorta didn't start
5. Manually start Vorta from Start Menu or directly from vorta.destkop file 
6. Observe Vorta does start and run properly

**Environment (please complete the following information):**
- OS:  Linux / Fedora 34
- Vorta version: 0.82
- Installed from: COPR repo (copr:copr.fedorainfracloud.org:luminoso:vorta)

**Additional context**

If I run the _vorta.desktop_ file directly (i.e. from Dolphin), it starts and behaves as expected.

IMPORTANT -  if I remove _--daemonize_ argument from _~/.config/autostart/vorta.desktop_ it autostarts fine on login.   However, this is short lived because Vorta immediately and automatically updates _vorta.desktop_ per Misc settings, overwriting the manual  change.   Any method I use with _--daemonize_ arg fails (e.g. startup script, etc).  Feels like a possible _background_ job conflict with KDE startup. 

Here is auto generated/updated _~/.config/autostart/vorta.desktop_ file created by the vorta app...

[Desktop Entry]
Name=Vorta
GenericName=Backup Software
Exec=vorta --daemonize
Type=Application
Icon=com.borgbase.Vorta
Categories=Utility;Archiving;Qt;
Keywords=borg;
StartupWMClass=vorta
StartupNotify=false
X-GNOME-Autostart-enabled=true

**Comment by mYnDstrEAm** [comment]
Autostart worked for me under Debian11/KDE. I have to test it again because I reinstalled Vorta from the official repos (it's been added for Debian11) and it doesn't show anymore under KDE's autostart entries (System Settings -> Startup and Shutdown -> Autostart).

`/home/username/.config/autostart/com.borgbase.vorta.desktop` has this content (and I have unchecked the setting under Misc and rechecked it which didn't change the file):
```
[Desktop Entry]
Categories=Utility;Archiving;Qt;
Comment[en_US]=
Comment=
Exec=/home/username/.local/bin/vorta
GenericName[en_US]=Backup Software
GenericName=Backup Software
Icon=/home/username/Software/Icons/com.borgbase.Vorta.svg
Keywords=borg;
MimeType=
Name[en_US]=Vorta
Name=Vorta
Path=
StartupNotify=true
StartupWMClass=vorta
Terminal=false
TerminalOptions=
Type=Application
X-DBUS-ServiceName=
X-DBUS-StartupType=
X-KDE-SubstituteUID=false
X-KDE-Username=
```

**Comment by m3nu** [comment]
Autostart is probably very distro-specific and better dealt with during packaging than here in Vorta.

**Comment by real-yfprojects** [comment]
> IMPORTANT - if I remove _--daemonize_ argument from _~/.config/autostart/vorta.desktop_ it autostarts fine on login. However, this is short lived because Vorta immediately and automatically updates _vorta.desktop_ per Misc settings, overwriting the manual change. Any method I use with _--daemonize_ arg fails (e.g. startup script, etc). Feels like a possible _background_ job conflict with KDE startup.

Running `vorta --daemonize` in the terminal works just fine?
You could also try to change the autostart entry to `vorta --daemonize >> /home/.../vorta_output.log` and look at the logs in this file as well as the ones in vorta's own log file which you can access through the GUI.

**Comment by pommetjehorlepiep** [comment]
Having exactly the same issue with running Vorta (installed using the AUR package) on ArchLinux KDE.
Vorta version 0.8.2

`vorta --daemonize` in the terminal works as expected
