### ISSUE TITLE
Vorta unable to start due to an encoding problem

### ISSUE THREAD

**Issue by rmattes** [borgbase/vorta#1157]
**Describe the bug**
A freshly installed Vorta fails to start with the following error in the stack trace:
```
File "/Users/sample/TMP/vorta/venv/lib/python3.9/site-packages/vorta/network_status/darwin.py", line 34, in get_known_wifis
    current_wifi = self.get_current_wifi()
  File "/Users/sample/TMP/vorta/venv/lib/python3.9/site-packages/vorta/network_status/darwin.py", line 23, in get_current_wifi
    for line in out.decode("utf-8").split('\n'):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 294: invalid start byte
```
**Environment (please complete the following information):**
- OS: MacOS 10.15.7
- Vorta version: 0.8.2
- Installed from: pip install vorta

**Comment by rmattes** [comment]
Seems as if Vorta is grocking on an WiFi SSID containing a german umlaut.

**Comment by m3nu** [comment]
It fails because your ö is latin1 encoded and not utf-8. You may want to change to utf-8 for better compatiblity.

I've added a small patch to ignore such errors. We can't start to do encoding detection, etc here. Especially since macOS already restricts this feature quite heavily.
