### ISSUE TITLE
Cant start vorta, python error 

### ISSUE THREAD

**Issue by JackDinn** [borgbase/vorta#1160]
Im sure it was fine until the last update, anyhow:-

Kernel: 5.10.89-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0
    parameters: BOOT_IMAGE=/boot/vmlinuz-5.10-x86_64
    root=UUID=bfe48f69-800c-4332-b8ea-0df162b1710d rw quiet apparmor=1
    security=apparmor udev.log_priority=3
  Desktop: KDE Plasma 5.23.4 tk: Qt 5.15.2 wm: kwin_x11 vt: 1 dm: SDDM
    Distro: Manjaro Linux base: Arch Linux

```
❰greg❙~❱✔≻ vorta
Traceback (most recent call last):
  File "/usr/bin/vorta", line 33, in <module>
    sys.exit(load_entry_point('vorta==0.8.1', 'gui_scripts', 'vorta')())
  File "/usr/bin/vorta", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for vorta

```

**Comment by JackDinn** [comment]
Ok i found something.

yay -S $(pacman -Qoq /usr/lib/python3.9) --answerclean All

**Comment by antun3s** [comment]
@JackDinn , it worked.
Thanks!

**Comment by amishtechie** [comment]
Thanks @JackDinn. This worked.
