### ISSUE TITLE
Feature request: backups of plain files without compression and encryption (to sync media center libraries and for full drive backups)

### ISSUE THREAD

**Issue by mYnDstrEAm** [borgbase/vorta#1161]
It seems like it's currently not possible to backup data as plain files with Vorta. Even if "no compression" is selected the files aren't readable until mounted via Vorta. A mode for plain file backups would be very useful to many and is a core missing feature when compared to alternative software.

Examples of major use cases:

* Keeping libraries of media centers in sync.  
For example, I'd like to have my Kodi media center library on multiple devices, not just as a backup but also for using the library. Vorta should detect if files have been moved or renamed using checksums (only new files are added and deleted files removed - duplicate files, files with missing metadata-changes like ratings or misnamed files are prevented).  
This is also useful for music libraries, including if you'd like to keep metadata of tracks (like ratings, bookmarks and [cue points](https://en.wikipedia.org/wiki/Cue_(audio))) in sync across devices. This includes music libraries for DJ mixing software (like the open source mixxx). It would be best if changes can be done on each of the devices but that would be an advanced improvement once plain file backups are possible.

* Restoring (full-drive) backups of hard drives and migrating hard drives.  
For example, if a drive is expected to fail soon and you'd like to migrate files to a new primary (not backup) drive.

I may not be aware of all the ways Vorta can be used (especially relating to the second use-case example) and may edit this over time. 

I think, right next to the lack of support for (root) system backups, this may be one of the most useful features missing in Vorta and when compared to competitors (see [here](https://github.com/borgbase/vorta/discussions/825#discussioncomment-858952)). I think to increase user-friendliness and become more popular Vorta needs to include missing features so that instead of using various different scripts and software for different purposes, only one backup/sync-software needs to be known and used (beyond Vorta features like deduplication that would make it far more useful when built into Vorta).

**Comment by real-yfprojects** [comment]
Vorta is just a GUI for the command-line program [borg](https://github.com/borgbackup/borg). **I** think FRs should only request features that relate to the GUI supporting *borg* features and making them easily usable through the GUI.

**Comment by real-yfprojects** [comment]
> Moreover, a user also linked to [here](https://borgbackup.readthedocs.io/en/stable/usage/create.html#examples) so some functionality for plain file backups seems to be already built into borg and could be made available here:
> 
> ```
> # No compression (none)
> $ borg create --compression none /path/to/repo::arch ~
> ```
>

If I am not mistaken, vorta already supports the compression type `none`.
