### ISSUE TITLE
[feature request] thinning out: keep/lock important "incremental backups"

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#1165]
I make every day my daily backup. Sometimes such a backup contains an "important state" of my data. And therefore I want absolutely keep exactly this backup and not the backup one day after this or before.

What do you think?

When I have created 50 incremental backups, then I can start "thinning out". So some incremental backups are deleted according to the "thinning out rules".

So this way, it can be, that also my backup with this "important state" (see above) will be deleted.

With my feature request this could be prevented.

So here is my suggestion: 
Please add in "archive tab" in the list with the incremental backups a new column. The name of this column should be "keep". It should have a checkbox behind each backup. 
When we now check such a checkbox behind a particular backup, then this means, that this backup should never be automated deleted through "thinning out" function.

So when we start "thinning out" it should delete all backups according to the "thinning out" rules, but in addition keep all backups, that have a checked keep-checkbox behind them.

What do you think?

**Comment by m3nu** [comment]
You can already achieve something similar with pruning prefixes. You would need to change the prefix to e.g. `important-{host}` BEFORE creating the archive to exclude it from all pruning.

**Comment by Golddouble** [comment]
Thank you for the hint. 

![ksnip_20220108-141405](https://user-images.githubusercontent.com/13977359/148645537-e365c2f5-e220-4ffd-a329-6aae9da23c42.jpg)
A) Do I understand right, that in this example only backups whose names start with `11e-default-` are considered to delete by prun? And all other are ignored?

B) Am I right, that I can exclude older backups, that I created a long time ago, from the prune process by changing the name with the "rename" function before I start "prune", in a way, that this name does no longer start with `11e-default-`?

Thank you.

**Comment by m3nu** [comment]
Yes to both. Renaming is a good way actually. So you don't need to change the prefix at all.
