### ISSUE TITLE
Folder failed to be added

### ISSUE THREAD

**Issue by stepelu** [borgbase/vorta#1170]
**Describe the bug**

I added an additional folder via Sources -> Add Folder (extra data I wanted to backup).
Differently from the usual behavior the 3 columns Type, Size, File Count remained empty for this folder.
Clicking on Recalculate sizes (OT: casing is inconsistent ;)) resulted in an error message being shown, I paste below the corresponding log:
```
2022-01-22 15:14:33,145 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "views/source_tab.py", line 156, in sources_update
  File "views/source_tab.py", line 100, in update_path_info
AttributeError: 'NoneType' object has no attribute 'setText'
```

I cannot help to reproduce, as I removed the problematic folder (from Vorta), restated Vorta, added the folder again, and the problem went away.
Removing and adding without restart did not solve the issue.
The folder did not show anything strange, but I moved and deleted various files in it before adding it Vorta.

**Environment (please complete the following information):**
- OS: OSX latest
- Vorta version: 0.8.2
- Installed from: brew

**Comment by real-yfprojects** [comment]
Could you enclose the full log, please?

**Comment by stepelu** [comment]
Sorry for the late reply. 
At the time you replied the logs in questions were already gone: vorta keeps 5 days of (daily rotating) logs.
If the issue pops up again I will update this ticket with full logs.

**Comment by real-yfprojects** [comment]
Possible duplicate of #1080
