### ISSUE TITLE
Impossible to add a hidden file to backup on MacOS

### ISSUE THREAD

**Issue by pierreduchemin** [borgbase/vorta#1173]
**Describe the bug**

**To Reproduce**
1. Go to  'Sources' tab
2. Click on 'Add files'
3. Finder is displayed
4. Display hidden files in finder using cmd + shift + .
5. Hidden files are now visible but not clickable, because of this it is impossible to add hidden files to sources using GUI

**Environment:**
- OS: MacOS Monterey 12.1
- Vorta version: 0.7.8
- Installed from: brew
- Borg version: 1.1.17

**Additional context**
I was able to successfully add hidden files to sources by exporting my configuration, editing generated json file and re-importing it.

**Comment by pierreduchemin** [comment]
I also tried with version 0.8.2 using dmg file and it had the same behavior.

**Comment by m3nu** [comment]
Qt has some limitations in their file picker. I'd also like to combine picking files and folders. This is in the same category.

**Comment by jchhenderson** [comment]
One workaround it to type the what you want into a text file, copy it and then use the `Paste folders/Files` button.

**Comment by pierreduchemin** [comment]
Fixed in version 0.8.6.
Thanks!

**Comment by andreagrandi** [comment]
Hello folks, sorry to resurface this but I'm using 0.8.11 and this isn't fixed at all. I still can't select hidden files from the UI and even if I try the workaround of copy-pasting, I get this:
<img width="289" alt="Screenshot 2023-12-27 at 17 25 28" src="https://github.com/borgbase/vorta/assets/636391/4539f167-74d1-4d63-88db-50281d76bcd2">
