### ISSUE TITLE
Missed backups aren't catched up if no previously scheduled backup ran.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1182]
# Issue
When vorta checks for a missed backup to catch up it queries for the last scheduled backup and will calculate whether this is too long in the past. But if there aren't any scheduled backups it will schedule a new one anyway e.g. in an hour from the current time. But if vorta is closed and this scheduled backup is missed in conclusion it won't be run on startup.

Related to #1130.

# Proposal

Vorta always calculates the next backup time from the last backup made whether it is scheduled or not. I think this is the wanted/expected behaviour. When choosing *run every hour* the result should be backups that are an hour apart from each other.

This will fix the issue.

**Comment by m3nu** [comment]
So this will just use the time of the last user-initiated backup as starting point if no scheduled backup is available at all instead of midnight as is the case now?

Works for me and seems more reasonable than using midnight as random starting point.

Are you doing a PR for this?

**Comment by real-yfprojects** [comment]
> So this will just use the time of the last user-initiated backup as starting point if no scheduled backup is available at all instead of midnight as is the case now?

Yes.

> Are you doing a PR for this?

And yes.
