### ISSUE TITLE
Vorta doesn't work on macOS Mojave (10.14.6) after upgrade to 0.8.3

### ISSUE THREAD

**Issue by rupertpaulson** [borgbase/vorta#1187]
Vorta stopped working after upgrading from version 0.8.2 to 0.8.3 on macOS Mojave (10.14.6):
"The application Vorta can't be opened."

Reinstalling 0.8.2 via Homebrew works just fine again. And a manual installation of the newest version (0.8.3) with the DMG file from GitHub results in the same problem: "The application Vorta can't be opened."

I know, I should upgrade to Big Sur or Monterey. But maybe still worth mentioning...

**Comment by m3nu** [comment]
Yeah, Mojave is old old stable. We build all releases on Github actions and use their default version, which is probably old stable by now.

**Comment by rupertpaulson** [comment]
Thx @m3nu, good to know. So it's just time to upgrade my OS.

**Comment by WillyCroco** [comment]
I do have the same issue on Mojave. Launching the binary from terminal will end in "Segmentation fault : 11".
