### ISSUE TITLE
Backing up entire disk

### ISSUE THREAD

**Issue by git70** [borgbase/vorta#1189]
Hi all!

Can Vorta back up a second drive in RAW mode?
Of course, I mean the inactive (unmounted) disk.

Using this functionality:

borg create --read-special repo::hostname-disk $DISK
https://borgbackup.readthedocs.io/en/stable/deployment/image-backup.html

or

dd if=/dev/sdx bs=10M | borg create /path/to/repo::my-sdx -
https://borgbackup.readthedocs.io/en/stable/usage/create.html

I would like to take a full disk image (with bootsector, partition table etc - similar to Clonezilla or .img via dd) and then take advantage of deduplication for subsequent backups.
This way, you can back up a disk image (for example, completely encrypted with FDE) and in case of an explosion of your computer's system disk, you can easily restore that image to a new disk.

Best Regards!

**Comment by m3nu** [comment]
Interesting use case. If your user has sufficient [permissions,](https://unix.stackexchange.com/questions/141255/give-a-specific-user-permissions-to-a-device-without-giving-access-to-other-user) it should be possible. You can pass the additional argument somewhere in the _Schedule_ tab.

**Comment by git70** [comment]
In the case of problems with permissions, I intend to restart a computer from LiveUSB (for example with the set data persistent).
I hope that then it will work and instead of doing a huge disk image every time, I will be able to do a beautiful deduplication :) 
Thank you for a good job!
