### ISSUE TITLE
delete specific archive(s)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#119]
**Is your feature request related to a problem? Please describe.**
It would be good to have a UI to delete a specific archive.

Prune is there, but does not / not always handle the use case, e.g. if you accidentally backed up some crap, improve your exclude list excluding the crap and back up again afterwards. Then you would like to delete the first backup and maybe not want to wait for / rely on prune doing that.

There might be also the case where you just want to manually get rid of something for other reasons, without killing the whole repo.

**Describe the solution you'd like**
Select 1 (or multiple) archives from the list, click "delete" button.

**Comment by m3nu** [comment]
We may get some per-archive action icons in #131. Those could be easily extended to run a new `borg.delete` command.

**Comment by m3nu** [comment]
Closing, since this was already implemented and merged in #164.
