### ISSUE TITLE
Notification when AES-CTR will be interrupted

### ISSUE THREAD

**Issue by git70** [borgbase/vorta#1190]
Does Vorta notify me somehow about the problem with the counter?
Does only see the log show anything?
https://borgbackup.readthedocs.io/en/stable/faq.html#isn-t-borgbackup-s-aes-ctr-crypto-broken

**Comment by m3nu** [comment]
We can catch specific Borg logs and pass them through as alerts. So yes, if we get an example of the log message, we can react to it. Personally I never had such a case and wouldn't know how to trigger it.

**Comment by git70** [comment]
Is Vorta currently reporting any alerts to paying the user's attention? (for example, a popup window or system notification)
I mean, or even a weak computer user in the company will notice irregularities and report to the administrator.

If this does not work, it would be possible to make selected journal events have become "red alerts" (to choose from).

**Comment by real-yfprojects** [comment]
Vorta shows error messages or notifies the user about them. How does *borg* react to an AES-CTR interruption?

**Comment by git70** [comment]
> Vorta shows error messages or notifies the user about them.

Is there a list of events that Vorta notifies?
Can you add your own events and mistakes to this list?
Alternatively, can we treat it as a Feature Request?
(In my opinion, this is an aspect to increase security)

> How does _borg_ react to an AES-CTR interruption?

@ThomasWaldmann Can you help explain?

**Comment by ThomasWaldmann** [comment]
You can raise the clientside counter to produce the same situation as a serverside attack.
See `.config/security/...`

**Comment by real-yfprojects** [comment]
> You can raise the clientside counter to produce the same situation (clientside counter > serverside counter) as a serverside attack. See `.config/borg/security/...`

If I get it right this only applies when using a remote repository. -> I cannot reproduce it locally.

**Comment by ThomasWaldmann** [comment]
Just try it.

**Comment by real-yfprojects** [comment]
> Just try it.

It will tell me that the encryption method has changed, refuse to continue and exit with return code `0`.

**Comment by ThomasWaldmann** [comment]
Interesting, I expected a somewhat different msg. Did you edit the `nonce` file?

**Comment by real-yfprojects** [comment]
> Did you edit the `nonce` file?

I used a unencrypted repo :roll_eyes:. But still I am not able to edit any of the two nonce files (in the repo or the borg config) in a way leading to a fail. I think I need more specific instructions.

**Comment by git70** [comment]
Was it possible to explain the matter?

**Comment by real-yfprojects** [comment]
I understood your point and I think this will turn out to be a feature request.
But I didn't understand how borg outputs such a problem with the counter (since I was incapable of reproducing it). Maybe @m3nu did understand it.

**Comment by m3nu** [comment]
Will try after the 1.2 release.

**Comment by git70** [comment]
Thank you Manu!
So I am waiting patiently :)

**Comment by git70** [comment]
We already have a version 1.2
Any update? ;)

**Comment by ThomasWaldmann** [comment]
BTW, the new crypto in 1.3 will solve the potential counter issues (not yet released).

**Comment by git70** [comment]
Thx Thomas for information!
This means that there is no point in dealing with this matter and just wait for 1.3 :)
Is there a well-known date of release 1.3?

**Comment by ThomasWaldmann** [comment]
If you can wait, yes, that will solve automatically for new repos.

Work on 1.3 (see master branch) is still ongoing, but I will try to limit the scope to pressing crypto and repo format issues, so the whole development, testing and release process will not take as long as it did for 1.2.

My current idea is that alpha/beta testing of 1.3 could start after 1.2.1 release, no promises though.
