### ISSUE TITLE
Vorta App Fatal Error

### ISSUE THREAD

**Issue by 8ICE8** [borgbase/vorta#1203]
```pytb
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/peewee.py", line 6665, in get
    return clone.execute(database)[0]
  File "/app/lib/python3.7/site-packages/peewee.py", line 4121, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/application.py", line 227, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/app/lib/python3.7/site-packages/peewee.py", line 6242, in get
    return sq.get()
  File "/app/lib/python3.7/site-packages/peewee.py", line 6670, in get
    (clone.model, sql, params))
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```

**Comment by m3nu** [comment]
Please fill the full bug template including version and steps to reproduce.

**Comment by FlorianLudwig** [comment]
Hi @m3nu 

i can reproduce this.

**To Reproduce**
Steps to reproduce the behavior:
1. `rm -rf .local/share/Vorta` # delete local config 
2. start vorta
3. add existing repository (i used one from borgbase)
4. wait
5. Exception

**Environment (please complete the following information):**
- OS: Linux
- Vorta version: `v0.8.3` and master as of `94fd8a0edfa5e6f3ba6114d447a5f731858cdab0` 
- Installed from: git

**Comment by real-yfprojects** [comment]
How long does one have to wait? I cannot reproduce any issue with the instructions given.

**Comment by FlorianLudwig** [comment]
@real-yfprojects for me i was a a ~ 10 seconds

**Comment by real-yfprojects** [comment]
Can you reproduce it with a local repo as well? @FlorianLudwig

**Comment by 8ICE8** [comment]
I have never run into this issue with local repos

**Comment by real-yfprojects** [comment]
@8ICE8 Can you provide logs from startup until closing the app after the exception?

**Comment by 8ICE8** [comment]
I deleted my old archives and repo, initialized a new repo and v0.8.4 seems to be working flawlessly.  Is it possible that there had been some kind of version mismatch between the version of borg originally used to initialize the now deleted repo and volta?.  Sorry, I'm not super technical.  I'm good about updating, but not tracking the details of every single one.

**Comment by real-yfprojects** [comment]
> Is it possible that there had been some kind of version mismatch between the version of borg originally used to initialize the now deleted repo and volta?. 

The error you reported originates from the vorta internal database. This shouldn't relate to borg and its version. Also vorta checks the borg version on startup.

> Sorry, I'm not super technical. 

The logs can be accessed through the `Misc` tab.
