### ISSUE TITLE
logging ideas

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#121]
**Is your feature request related to a problem? Please describe.**

There is currently a log in `~/.cache/Vorta/log/vorta.log`, but one needs to view it outside of vorta.

Also, it is just one file for everything. Not sure if vorta has some management for it or one would need logrotate to keep it from growing to infinity.

**Describe the solution you'd like**

I'ld like if logs were coupled to borg invocations, like writing them to separate files and linking them on the GUI to the entries in `Schedule -> Log`.

After clicking on some button, the specific log would be opened in a scrollable window in a way so it is possible to control the rendering of each line (e.g. colour or style).

Having a logical link between archives and corresponding log file would also enable vorta to get rid of log files after the corresponding archive is deleted or pruned away.

borg and vorta log output could just end up in the logfile intermixed, usually it should be clear where a msg comes from. also we could log the logger name.

**Describe alternatives you've considered**

completely manual log view: most users likely would not even know where the logfile is.

external viewer invoked from vorta: not enough control, too platform specific

**Comment by ThomasWaldmann** [comment]
about controlling each line of log output in the log view: i implemented some code for `borgweb` colouring log lines in a nice way (like errors, warnings, success in different colours).

**Comment by luckyrat** [comment]
> completely manual log view: most users likely would not even know where the logfile is.

^^ this was me, in #230.

I therefore very much approve of the suggestions here. I'm not quite following this bit though:

> borg and vorta log output could just end up in the logfile intermixed, usually it should be clear where a msg comes from. also we could log the logger name.

Am I right in thinking this is an alternative suggestion to having separate log files for each command invocation?

If so then I suppose I don't have a strong preference either way - whatever the easiest way to allow a user to quickly see all output relating to a borg command would be fine by me. I'm sure there are some technical challenges with either approach but you'll know better how significant they are.

> about controlling each line of log output in the log view: i implemented some code for borgweb colouring log lines in a nice way (like errors, warnings, success in different colours).

This sounds good too, although perhaps for a 2nd round of improvements? With my new user hat on, I would be pleased by the colours but just being able to find the information I needed is more important.

**Comment by m3nu** [comment]
Most of this is now implemented:

- we log the module name in the log file.
- there is a button to open the log folder (#247)

Do you still think the log file should be split? Personally I like to have it in one place to correlate things that happened at the same time.

**Comment by ThomasWaldmann** [comment]
vorta and borg can log to same file.

but i still think that there could be a new file per action. e.g. if you backup twice a day, it would create 2 log files per day. this also makes it easier to remove logs (delete old files instead of having to shorten one file). is this already implemented?

**Comment by m3nu** [comment]
One action = one Borg invocation? This could be considerably more than 2. E.g. working in the Archive tab: prune, mount, delete, refresh. But then some Borg commands have lots of output. E.g. prune. An argument for separate files.

When I look at existing software, it seems more common to have it all in one (mostly) and rotate that over time. For debugging I strongly prefer everything in one place to quickly see what's going on or what happened before or after.

Log rotation isn't implemented yet, but should be. Some macOS tools seem to clear it, but on Ubuntu I have months of logs. There seems to be a choice of [size-based vs. time-based](https://docs.python.org/3.7/library/logging.handlers.html#rotatingfilehandler). Time-based is probably easier to use. Daily logs for a week or so should be sufficient, since it's just for debugging, not analytics.

**Comment by ThomasWaldmann** [comment]
Side note:

I recently had to deal with re-configuring linux' `logrotate` and ended up with just having 1 log per day (the config change was easy, but a lot of effort went into logrotate behaving strange). The default way it is used (logname, logname.1, logname.2.gz, ...) is bad for syncing. I configured it now to use iso8601-like timestamps and no compression. The .1 ending is also easily confused by tools thinking it is a man page.

For vorta I could also imagine time-based, daily, with iso datetime in the filename. And maybe some extension that makes sure the desktop env really opens a text viewer (and not man page or nothing).

**Comment by ThomasWaldmann** [comment]
(still, coupling a log to an archive name would be also nice, and kill it together with the archive)

**Comment by m3nu** [comment]
Logging by profile could make sense, but will need some more changes to logging.

For now I just added simple daily rotation to at least avoid a build-up of old logs. Default format is this:

```
vorta.log
vorta.log.2019-04-07_22-16
vorta.log.2019-04-07_22-19
```

**Comment by ThomasWaldmann** [comment]
guess this might confuse extension-based mimetype determination.

maybe rather vorta-<datetime>.log or even .txt?

**Comment by m3nu** [comment]
> maybe rather `vorta-<datetime>.log` or even `.txt`?

I'll see if this pattern is possible by overriding some attributes in the [TimedRotatingFileHandler class](https://github.com/python/cpython/blob/master/Lib/logging/handlers.py#L191). But not looking to reimplement logrotation for this feature. :-)

**Comment by ThomasWaldmann** [comment]
Doesn't look like that logging handler code is capable of this.

Guess we rather don't use it or users will not be able to easily view log files.

**Comment by ThomasWaldmann** [comment]
btw, maybe we do not even need a rotating handler if we just decide on daily logs and compute the log file name by this pattern: `vorta-%s.txt` with the current day's string representation and just append to it.

only difficulty here is that this needs to reinit the logging system with that filename at the day boundary.

**Comment by m3nu** [comment]
Log rotation and the button to open logs is already implemented and I'm revisiting better logging flow in #375. So closing this issue now. If something else is missing, do let me know.

![Screen Shot 2020-06-02 at 09 01 08](https://user-images.githubusercontent.com/3916435/83468583-c20bb280-a4af-11ea-9719-ac90b2e54b80.jpg)
