### ISSUE TITLE
[FEATURE REQUEST] Skip File

### ISSUE THREAD

**Issue by philzeo** [borgbase/vorta#1210]
Is it possible to get a feature where, if there's a file causing issues with the backup, we can skip it and continue the sync?

For example: I have a massive first backup in most instances when I use vorta on a system for the first time. Sometimes, it hangs on just one file, and that can cause a lot of issues. The ability to skip a single file that's causing it to hang, and either flag it for skipping every time (an option to add it or its folder to the exclusions list) or just to skip it this time might save a lot of heartache. 

This would be awesome, if possible. If not, I'd still love to learn why it's not possible because it's a great program.

**Comment by philzeo** [comment]
I think the thing im looking for is a "skip this file" option DURING the scan. If I add an exclusion while the scan is currently going, it won't do anything to the currently running scan. And if it hangs during a large file, then I have to shut it down to restart the scan from the beginning which is really rough.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by real-yfprojects** [comment]
> Get Outlook for Android<https://aka.ms/AAb9ysg>
> ________________________________
> From: Manu ***@***.***>
> Sent: Wednesday, March 2, 2022 1:58:09 AM
> To: borgbase/vorta ***@***.***>
> Cc: philzeo ***@***.***>; Author ***@***.***>
> Subject: Re: [borgbase/vorta] [FEATURE REQUEST] Skip File (Issue #1210)

The advertisement in your email signature is a little odd.

**Comment by real-yfprojects** [comment]
> I think the thing im looking for is a "skip this file" option DURING the scan. If I add an exclusion while the scan is currently going, it won't do anything to the currently running scan. And if it hangs during a large file, then I have to shut it down to restart the scan from the beginning which is really rough.

AFAIK [borg](https://borgbackup.readthedocs.io/en/stable/) which is the backup tool vorta provides a GUI for doesn't support such a feature. Consider opening an issue at their repository.
