### ISSUE TITLE
Switch away from fontawesome.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1218]
Currently vorta uses icons from [fontawesome.com](https://fontawesome.com/icons) for the GUI. Though the icons currently used are from an old version of fontawesome and have a different style than new ones. They therefore should be updated when a new icon from fontawesome is introduced to vorta.

While we're at it, replacing all the icons currently used by vorta we could also overcome the drawbacks of fontawesome. The major disadvantage is that most icons on fontawesome are only accessible through a premium plan. This wasn't a problem yet, but I was already looking for new icons to improve the GUI previously and couldn't use the best fitting icon, because it was locked. This is the case for `file-plus`, `folder-plus` and `list-tree`. Closely linked to there payment model is the dubious licensing of their icons. Nowhere on their website a real license text can be found. The icons are definitely not open-source, while there are many great open-source icon themes out there. These are the ones I found:

- [Breeze icons](https://develop.kde.org/frameworks/breeze-icons/) | [List of icons](https://cdn.kde.org/breeze-icons/icons.html)
- [Bootstrap icons](https://icons.getbootstrap.com/)
- [Feather](https://feathericons.com/)
- [ForkAwesome](https://github.com/ForkAwesome/Fork-Awesome)
- [Material](https://fonts.google.com/icons?icon.query=folder) (Google)

Personally I prefer the breeze icon theme. All three of them look great but breeze has a larger collection of useful icons.
Everyone is welcome to leave their icon theme suggestions down below, I will add them to the list.

**Comment by m3nu** [comment]
No problem to use other sources for SVG icons than FA. Changing existing icons isn’t necessary though. License is pretty clear and we voluntary attribute in the Credits section. More: https://fontawesome.com/v4/license/

**Comment by real-yfprojects** [comment]
> No problem to use other sources for SVG icons than FA. Changing existing icons isn’t necessary though. 

Shouldn't the icons of the GUI be of a unified style?

> License is pretty clear and we voluntary attribute in the Credits section. 
More: https://fontawesome.com/v4/license/

Through their github repository I was no able to find the licensing for the free icons. They are licensed under CC-BY - the attribution is already embedded in the svg files.

**Comment by sten0** [comment]
I'm not sure there's any urgency to change at this time, but from what I could gather, Fork Awesome is a friendlier upstream (eg: https://fedidat.com/140-migrate-font-fork/ ), and seem to be OFL-1.1 and Expat.  Eventually I think that it'd be nice if Vorta could do a runtime check for KDE Plasma, and if found then inherit the active KDE Plasma icon theme, else use a fallback.  That's just a long-term maybe wishlist thing though--maybe 2023-24ish? ;-)  My personal preference would be for Breeze as a fallback, for the reasons @real-yfprojects noted, and also because it's focused on desktop things rather than web things.

**Comment by m3nu** [comment]
#1729 resolves the licensing issue, but not the consistency issue also mentioned here. I'm not sure this can be resolved in Vorta, since one icon set doesn't have so many options usually.
