### ISSUE TITLE
UI does not recognize borg being finished

### ISSUE THREAD

**Issue by leahdrenalin** [borgbase/vorta#1222]
**Describe the bug**
It seems like in Vorta 0.8.3 with borg 1.1.17 on OpenSuse Leap 15.4 Beta, Vorta does not register when borg is done backing up. The spinner continues to spin and nothing happens, even though there is no running borg process on the machine anymore. On the target host (borg 1.1.15), the data seems to be complete and the SSH session has been closed. The logs show nothing except starting the borg create command and creating the archive. 

The same target host works perfectly fine with Vorta 0.7.5, borg 1.1.15 and OpenSuse Leap 15.3.

**To Reproduce**
1. start Backup
2. wait

**Environment (please complete the following information):**
- OS: OpenSuse Leap 15.4 Beta
- Vorta version: 0.8.3
- Installed from: zypper in vorta

**Comment by leahdrenalin** [comment]
I don't know and I don't have the means or time to test in the foreseeable future.

**Comment by GerritHeim** [comment]
Same problem here. I reported it in openSUSE Bugzilla

https://bugzilla.opensuse.org/show_bug.cgi?id=1199080

**Comment by real-yfprojects** [comment]
> Vorta can be connected to Borg Repo and the backup runs through seemingly normally, but is not completed.
>
>The list of archives is not displayed. Refresh runs dead.
>
>On the command line with borg there are no problems. So the problem is with vorta.

Quoting this from the openSUSE bugzilla to have everything in one place.

**Comment by real-yfprojects** [comment]
For debugging you could start an interactive terminal and try the following:
```pycon
>>> from subprocess import Popen
>>> p = Popen(cmd, universal_newlines=True, start_new_session=True)
output of borg command
>>> p.poll()
0
```
Here `cmd` must be replaced with a list of the executable to call (borg) and the arguments to pass to it. E.g. 

```python3
['borg', 'create', 'myrepo::myarchive', 'source']
```
This should contain exactly the command that leads to vorta hanging. You can find it in the logs.
