### ISSUE TITLE
Translation: Missing translations on Tab Archives, shows only English.

### ISSUE THREAD

**Issue by delfino-nunez** [borgbase/vorta#1223]
**Describe the bug**
On tab "Archives" the following translations are missing, the translation doesn't exists in Transifex or ts file, they aren't translating when language is changed.
Missing translation:
"Selected Archive" drop down options are not translated, still display in English.
"Compact" button not translated, still display in English.
INFO message in English.

![Archives-es](https://user-images.githubusercontent.com/770967/159110391-a6041e65-6f14-41eb-8792-95a6d0a2664a.png)
![Archives-fr](https://user-images.githubusercontent.com/770967/159110393-98552b01-5f78-40d4-bf87-0c00409363cd.png)

**To Reproduce**
1. Set language
2. Click on 'Archives'
3. Click on 'Selected Archive'
4. See untranslated options.
5. Click 'Check'
6. View "INFO" messages in English instead of the set language.

**Environment (please complete the following information):**
- OS: Linux 5.13.0-35-generic # 40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Vorta version: 0.8.3
- Installed from: GitHub

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
The text is not available for translation on Transifex or the ts file.

**Comment by m3nu** [comment]
Hi, you can add missing translations on Transifex. See here for details: https://vorta.borgbase.com/contributing/translations/

**Comment by real-yfprojects** [comment]
One will have to go over all GUI strings and fix the use of `trans_late` and `translate`, because this is the problem of #1223 and #1224 as well as the missing use of either of them.

**Comment by delfino-nunez** [comment]
> Hi, you can add missing translations on Transifex. See here for details: https://vorta.borgbase.com/contributing/translations/

I'll take a look, thank you.

**Comment by delfino-nunez** [comment]
> Hi, you can add missing translations on Transifex. See here for details: https://vorta.borgbase.com/contributing/translations/

If I try to add/push missing translations I get the following error, is there a process to add the missing ones? 
or do I need to make a code change and PR?

```
vorta$ make translations-push
pylupdate5 -verbose -translate-function trans_late \
                   src/vorta/*.py src/vorta/views/*.py src/vorta/borg/*.py \
                   src/vorta/store/*.py src/vorta/assets/UI/*.ui \
                   -ts src/vorta/i18n/ts/vorta.en.ts
Updating 'src/vorta/i18n/ts/vorta.en.ts'...
    Found 368 source texts (0 new and 368 already existing)
tx push -s
tx INFO: Pushing resource vorta.vorta
tx INFO: Pushing source file (src/vorta/i18n/ts/vorta.en.ts)
tx ERROR: Error received from server: Only maintainers are allowed to update the source file.
tx ERROR: Could not upload source file. You can use --skip to ignore this error and continue the execution.
tx ERROR: Error received from server: Only maintainers are allowed to update the source file.
make: *** [Makefile:45: translations-push] Error 1

``
![Missing-translations](https://user-images.githubusercontent.com/770967/159215667-28830a2f-e8a2-4757-9cf3-94ca9ed329b4.png)
`

**Comment by m3nu** [comment]
`make translations-push` adds compiled translations to the repo. This is only done for releases.

If you need to edit the source code because a string is not marked for translation, you should open a pull request.

**Comment by delfino-nunez** [comment]
> One will have to go over all GUI strings and fix the use of trans_late and translate, because this is the problem of https://github.com/borgbase/vorta/issues/1223 and https://github.com/borgbase/vorta/issues/1224 as well as the missing use of either of them.

@real-yfprojects  what you mean? 
do you mean that trans_late calls should be replaced with translate?

I'm looking at the trans_late method but I don't get it what it's use for.

I see many places where is used so I don't want to replace it unless I understand the use.

**Comment by real-yfprojects** [comment]
> @real-yfprojects what you mean? do you mean that trans_late calls should be replaced with translate?

In some cases.

> I'm looking at the trans_late method but I don't get it what it's use for.

The translation framework will extract hard coded strings (in quotes) that are surrounded by a call to `self.tr`, `translate` or `trans_late`. On runtime the method `self.tr` of Qt classes and subclasses as well as the function `translate` will return the translation for the string passed to them. The function `trans_late` will always return exactly the string passed to it. Therefore `trans_late` allows for marking a string for extraction to the translation files without actually translating it (yet). The string therefore has to be translated using `translate` or `self.tr` later before it is presented to the user. This behaviour is rarely useful but it makes sense for enums and the like whose string values are used by the program and therefore shouldn't be translated but are also displayed and should be translated for that. Usually you don't want to use `trans_late` since it should be the exception.

**Comment by delfino-nunez** [comment]
So any string inside trans_late could eventually become translated ( with some exceptions I imagine) ?

**Comment by real-yfprojects** [comment]
> So any string inside trans_late could eventually become translated ( with some exceptions I imagine) ?

Yes, but without exceptions. If a string shouldn't be translated it shouldn't be wrapped in `self.tr`, `translate` or `trans_late`.

**Comment by delfino-nunez** [comment]
Got it, I'll will be wrapping in self.tr some missing strings I've seen not translated.

Thank you for explaining.

**Comment by delfino-nunez** [comment]
Closing this issue since some of the missing strings are set to translate and any new one should be added as new issues.
