### ISSUE TITLE
Uncaught Exception when scheduling for 4 weeks

### ISSUE THREAD

**Issue by vis2k** [borgbase/vorta#1227]
**Describe the bug**
Trying to enter '30 days' or '4 weeks' for scheduled backup causes the following exception:

<img width="795" alt="2022-03-22_00-29-19@2x" src="https://user-images.githubusercontent.com/16416509/159307417-7f8e0071-22e6-4d0d-80e2-5f25b688ee94.png">

**To Reproduce**
- open vorta
- schedule
- enter '4' and select 'weeks'
- click the radio button to select it

**Environment (please complete the following information):**
- OS: mac montery
- Vorta version: latest
- Installed from: brew

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by real-yfprojects** [comment]
This due to c++ int having only 31?? bits to represent an integer while python actually has no real size limit for the int type.

**Comment by vis2k** [comment]
thanks for fix :)
