### ISSUE TITLE
Uncaught exception while getting diff

### ISSUE THREAD

**Issue by herrwusel** [borgbase/vorta#1228]
**Describe the bug**
When getting the diff of two snapshots I get an uncaught exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/vorta/views/archive_tab.py", line 521, in list_diff_result
    window = DiffResult(result['data'], archive_newer, archive_older, result['params']['json_lines'])
  File "/usr/lib/python3.10/site-packages/vorta/views/diff_result.py", line 32, in __init__
    files_with_attributes, nested_file_list = parse_diff_json_lines(lines) \
  File "/usr/lib/python3.10/site-packages/vorta/views/diff_result.py", line 113, in parse_diff_json_lines
    assert change_type  # either no changes, or unrecognized change(s)
AssertionError
```

**To Reproduce**
1. Open vorta
2. get diff of two snapshots

**Environment (please complete the following information):**
- OS: Arch
- Vorta version: 0.8.3
- Installed from: aur

Edit: It seems that there is one "faulty" snapshot. Diffs are working for the other backups.
Edit 2: The newest archives are comparable but not with older ones.

**Comment by real-yfprojects** [comment]
It seems like there is an item without changes in the `borg diff` output.
You could try the following to debug this:
```bash
> git clone https://github.com/real-yfprojects/vorta.git
> cd vorta
> python -m venv env
> source env/bin/activate
> pip install -e . # look for error messages or warnings which indicate a problem that has to be fixed before the next step
> vorta
```
Now try to reproduce the error. Then search a section starting with `---- DEBUG` in the logs and paste it here.

**Comment by herrwusel** [comment]
Thanks for your help! 
Unfortunately there is nothing with `---- DEBUG` in the logs when reproducing the error.

**Comment by real-yfprojects** [comment]
> Thanks for your help! Unfortunately there is nothing with `---- DEBUG` in the logs when reproducing the error.

If you are running the forked branch of vorta, this is not possible.

**Comment by real-yfprojects** [comment]
> You are correct. I forgot to checkout the correct branch.

Mainly my fault since I forgot to include it in the instructions.

Nothing unexpected in the logs. This seems to be a problem with borg. Still I am interested in the output of
```
borg diff <repo>::<archive1> <archive2>
```
for the archives in question - more specifically in the line for `home/jakob/Zotero/pipes/1647851804595`.

**Comment by herrwusel** [comment]
This is the line from the json respone:
```
{"path": "home/jakob/Zotero/pipes/1647851804595", "changes": []}
```
There are only two empty `changes` values both coming from the Zotero directory.

**Comment by m3nu** [comment]
Probably we don't take such empty lines into account when parsing the output from Borg.

**Comment by real-yfprojects** [comment]
> This is the line from the json respone:
> 
> ```
> {"path": "home/jakob/Zotero/pipes/1647851804595", "changes": []}
> ```

And what is the plain output (when running borg without the `--json` or `--json-lines` flag)?

> Probably we don't take such empty lines into account when parsing the output from Borg.

But can there be a changed file without any changes? Something like that is not mentioned in the borg docs.

**Comment by herrwusel** [comment]
It just a plain line missing the change type and size: 
```
                    home/jakob/Zotero/pipes/1647851804595
```

**Comment by real-yfprojects** [comment]
I suggest that you open an issue report at the [borg repo](https://github.com/borgbackup/borg) for this case. I don't think this is intended behaviour.
