### ISSUE TITLE
Unhandled exception windows when password manager is locked

### ISSUE THREAD

**Issue by supermihi** [borgbase/vorta#1233]
**Describe the bug**
I have a scheduled backup with Vorta. Today it failed because apparently the password manager was locked, leading to the screenshot below that asks me to report this issue on GitHub. Imho there should be a helpful error message instead of this exception; also Vorta was completely unresponsive after that, i.e., I could neither click the "ok" button to close the exception window nor do anything else. 

**Environment:**
- OS: Arch Linux
- Vorta version: 0.8.3
- Installed from: Arch Linux AUR

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
![screenshot](https://user-images.githubusercontent.com/102419/159922730-d70aa9ac-488c-4436-ae22-00e73f379add.png)

**Comment by m3nu** [comment]
This happens in the `secretstorage` package, but we should probably deal with it somehow.

**Comment by supermihi** [comment]
I investigated a little more, and the problems seems to be related with me upgrading to KeePassXC 2.7.0, which implements a  [dialog for unlocking secrets](https://github.com/keepassxreboot/keepassxc/pull/6943). For some reason, this doesn't seem to work well with `secretstorage`, because I never see that dialog (works well with other clients).

**Comment by supermihi** [comment]
As there's a call to `ensure_not_locked()` in the stack: perhaps Vorta should call something like `unlock_if_required()` or the like (just guessing)?

**Comment by supermihi** [comment]
`collection.unlock()` seems to be the correct method (https://secretstorage.readthedocs.io/en/latest/#locking-and-unlocking-collections)

**Comment by Aeysol** [comment]
It seems that KeePassXC with v2.7.0 has changed the initial status of an item when fetched using the SecretStorage API. The new dialog that is presented to users now sets the state of the item initially to _locked_ and after manual confirmation by the user to _unlocked_.

I've patched the `get_password()` method in the file [secretstorage.py](https://github.com/borgbase/vorta/blob/master/src/vorta/keyring/secretstorage.py#L43):
```py
def get_password(self, service, repo_url):
    if self.is_unlocked:
        asyncio.set_event_loop(asyncio.new_event_loop())
        collection = secretstorage.get_default_collection(self.connection)
        attributes = {'application': 'Vorta', 'service': service, 'repo_url': repo_url}
        items = list(collection.search_items(attributes))
        logger.debug('Found %i passwords matching repo URL.', len(items))
        if len(items) > 0:
            item = items[0]
            if item.is_locked() == True: item.unlock() # Unlock the item first if needed
            return item.get_secret().decode("utf-8")
    return None
```

This works as intended.

**Comment by m3nu** [comment]
Cool! We should make this a PR right away, once it’s known to work everywhere.

**Comment by supermihi** [comment]
@Aeysol thanks a lot, I can confirm that this fix works.

**Comment by real-yfprojects** [comment]
@Aeysol Do you want to create a PR for your fix? Otherwise someone else could do it.

**Comment by Aeysol** [comment]
@real-yfprojects PR #1255 created.

**Comment by real-yfprojects** [comment]
> @real-yfprojects PR #1255 created.

Great!
