### ISSUE TITLE
Translation string missing on "Diff" result dialog grid

### ISSUE THREAD

**Issue by delfino-nunez** [borgbase/vorta#1241]
**Describe the bug**
On the result "Diff" dialog the grid result columns titles are not translated, display in English.

**To Reproduce**
1. Go to 'Archives'
2. Click on 'Diff'
3. Select 2 archives to compare
4. Click on 'Diff'
5. See result grid with column titles in English

![Selection_002](https://user-images.githubusercontent.com/770967/160531029-0751b0a8-ad57-4840-af8a-4666935fbd5d.png)

**Environment (please complete the following information):**
- OS: Linux 5.13.0-37-generic # 42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Vorta version: 0.8.3
- Installed from: GitHub repo

**Comment by delfino-nunez** [comment]
I'll wait for PR #1244 to be reviewed since this one would be the same solution.

**Comment by real-yfprojects** [comment]
Fixed in d8e4a93cdd527b692869da0969c0fbf43f08305d.
