### ISSUE TITLE
v0.8.4 Release

### ISSUE THREAD

**Issue by vis2k** [borgbase/vorta#1250]
Hi guys, you recently fixed a few issues that are very useful.
Any way to push the next release? Last one was from january.

Thanks :))

**Comment by m3nu** [comment]
Agreed. Will do a release soon. Just giving translators some time to catch up with the latest changes and to allow for testing the larger UI changes.

You can use the latest version right away with `pip` only. No git, etc needed

https://vorta.borgbase.com/contributing/#testing-the-current-development-version

**Comment by m3nu** [comment]
Still a few milestones open: https://github.com/borgbase/vorta/milestone/9

**Comment by vis2k** [comment]
thank you for your work.
best backup tool I've found in a long time :)
