### ISSUE TITLE
Support includes for patterns / pattern file

### ISSUE THREAD

**Issue by jose1711** [borgbase/vorta#1252]
I think it would be great if vorta supports including files containing exclude patterns. I am having multiple backup profiles (to different locations) and keeping the exclude lists in sync manually is kinda messy.
So if it would be possible to do
```
@dot_local
@dot_config
```
instead of
```
**/.local/share/foo
**/.local/tmp/bar
**/.local/baz
**/.config/fooapp
**/.config/barapp
..
..
```
in each profile would make things considerably tidier I believe.

**Comment by real-yfprojects** [comment]
> ```
> @dot_local
> @dot_config
> ```

How are these lines supposed to behave?
If you want to exclude all children of `.local` you could use `~/.local/*`.

**Comment by jose1711** [comment]
> > ```
> > @dot_local
> > @dot_config
> > ```
> 
> How are these lines supposed to behave? If you want to exclude all children of `.local` you could use `~/.local/*`.

This would read the lines from ´dot_local´ and ´dot_config´ files residing somewhere near vorta config files and concatenate the results forming the final list of patterns.

**Comment by real-yfprojects** [comment]
> This would read the lines from ´dot_local´ and ´dot_config´ files residing somewhere near vorta config files and concatenate the results forming the final list of patterns.

Maybe one could also be able to specify any absolute path to such a pattern file.
The key term `pattern file` should also be included in the title of this issue btw.

**Comment by jose1711** [comment]
> > This would read the lines from ´dot_local´ and ´dot_config´ files residing somewhere near vorta config files and concatenate the results forming the final list of patterns.
> 
> Maybe this feature could also allow specifying any absolute path to such a pattern file.

Sure, that would work too. The whole idea is just to make the pattern list more readable and easier to manage if they are shared by multiple backup profiles.

> The key term `pattern file` should also be included in the title of this issue btw.

Will do.

**Comment by m3nu** [comment]
See #907 for planned changes and lets discuss there.

**Comment by hoopahmadness** [comment]
Why was this marked as completed? As far as I can tell there's still no support for using a pattern file.

**Comment by m3nu** [comment]
The new exclude dialog supports a lot of different ways like keeping exclusions as JSON files. Have you tried it recently?

**Comment by hoopahmadness** [comment]
I'll just take this as "Closed Won't Do" I guess.
