### ISSUE TITLE
Feature request: mount repository

### ISSUE THREAD

**Issue by jose1711** [borgbase/vorta#1256]
Borg allows mounting of the whole repository as a FUSE filesystem, in which all archives are shown as directories. This may be useful if you're looking for something specific, want to do diff between different versions of the same file etc. Vorta seems to currently only support mounting of the individual archives and repo mount can be achieved only via command-line.

**Comment by m3nu** [comment]
Already possible by pressing "Mount" without selecting any archive.

Not very intuitive though. Maybe the recent UI changes to be released in the next version made this more explicit.

**Comment by real-yfprojects** [comment]
> Not very intuitive though. Maybe the recent UI changes to be released in the next version made this more explicit.

No, the recent changes removed this feature completely.

**Comment by real-yfprojects** [comment]
Actually the recent changes didn't remove this feature but #864 about a year ago.
