### ISSUE TITLE
Vorta hangs on repository creation & can't backup due to passhprase error

### ISSUE THREAD

**Issue by carobinario** [borgbase/vorta#1260]
Hi,
I'm using Vorta. I always back up without problem to an usb hard disk and to Borgbase (two different profiles).

Yesterday I created a third profile to backup to the usb hard disk. Unfortunately Vorta hanged when I created the repo. 

_2022-04-11 18:18:51,027 - vorta.borg.borg_job - WARNING -
IMPORTANT: you will need both KEY AND PASSPHRASE to access this repo!
If you used a repokey mode, the key is stored in the repo, but you should back it up separately.
Use "borg key export" to export the key, optionally in printable format.
Write down the passphrase. Store both at safe place(s)._

After restarting Vorta I tried to backup but I had this error:

_2022-04-11 18:29:15,829 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2022-04-11 18:29:15,830 - vorta.notifications - DEBUG - notification not suppressed_

What's wrong? Why can I backup to the other two repositories but not to the third one? 

**Environment:**
- OS: Opensuse Tumbleweed (20220409), KDE Plasma Version: 5.24.4, KDE Frameworks Version: 5.92.0, Qt Version, 5.15.2.
- Vorta version: Vorta 0.8.3 (Borg 1.2.0) 
- Installed from: Opensuse repository
- Additional software: Keepass XC 2.7.0 as secret service manager (I'm not using Kwallet)

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
Here is the log: [vorta.log](https://github.com/borgbase/vorta/files/8466192/vorta.log)

Thanks.

**Comment by real-yfprojects** [comment]
Do you have KWallet installed?

The warning from borg is normal. Though the behaviour of vorta isn't. In your logs I could find the following two lines indicating that you cancelled on of the jobs linked to the creation of the borg repository:

```
2022-04-11 18:22:49,854 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2022-04-11 18:22:49,855 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
```

Can you reproduce the issue after unlinking the repository and deleting it from the drive?

**Comment by carobinario** [comment]
> Can you reproduce the issue after unlinking the repository and deleting it from the drive?

Hi, I can reproduce it after: a) unlink repository 2) delete repository from the drive 3) create new directory on the drive (vorta-test2) 4) add new repo in previous directory.

Also I updated KeepassXC to 2.7.1 and Tumbleweed to 20220413 and Kde Frameworks to 5.93.0, Kernel to 5.17.2-1-default (64-bit). 

Kdewallet is installed but not active.

Here is updated log and two screenshot:


[vorta-log-new.txt](https://github.com/borgbase/vorta/files/8499879/vorta-log-new.txt)

![vorta UI](https://user-images.githubusercontent.com/16922051/163674589-951d2b74-e6f5-438c-a7aa-8b940a6904b0.png)

![vorta UI2](https://user-images.githubusercontent.com/16922051/163674596-806b29a1-c138-4b61-b7e9-37449525e30f.png)

**Comment by real-yfprojects** [comment]
Which keys from vorta are stored in the secretstorage keyring? (should be the one from KeepassXC) Is there a key for the repository in question?

**Comment by carobinario** [comment]
Hi,
I have two keyring stored in Keepassxc:

![keepass1](https://user-images.githubusercontent.com/16922051/163683147-cb9f86ae-7a9c-4dca-b708-ab63c0b8a171.png)

![keepass2](https://user-images.githubusercontent.com/16922051/163683149-f2c2851e-a4a7-427f-bed2-80b3d6eb070b.png)

![keepass3](https://user-images.githubusercontent.com/16922051/163683153-38552991-7d9a-4cf1-b753-021e69e81348.png)

**Comment by real-yfprojects** [comment]
Since you censored the `repo_url`s you must tell me whether one of them matches the path to the repository on the USB drive.

**Comment by carobinario** [comment]
Hi,
sorry, non problem. Here is new screenshot and log without censorship in usb drive url:

![vorta screenshot 23 04 22](https://user-images.githubusercontent.com/16922051/164892888-21d29bbe-1618-413b-bb89-4a3491e7bc1d.png)
![keepassxc](https://user-images.githubusercontent.com/16922051/164892892-39d2f135-e321-4ace-91e0-12d56718275e.png)

[vorta log 230422.txt](https://github.com/borgbase/vorta/files/8546840/vorta.log.230422.txt)

Operating System: openSUSE Tumbleweed 20220420
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.2
Kernel Version: 5.17.3-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600 CPU @ 3.30GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530

**Comment by real-yfprojects** [comment]
Your screenshot shows that the passphrase for the repository isn't stored in KeepassXC. So the storing doesn't work with repository on the USB drive. But I have no idea what could be a reason for that. Can you provide the logs of the current master branch?

**Comment by carobinario** [comment]
Hi,
I downloaded Vorta current master branch but I don't know how to install it; I don't want to overwrite latest stable version or break the system. Thanks.

**Comment by carobinario** [comment]
> 



> Install vorta in development mode using `pip install -e .`

Hi, what's wrong?

```

(env-dir) riccardo@icpo:~/Scaricati/vorta-master> pip install -e

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

-e option requires 1 argument

```
Thanks

**Comment by carobinario** [comment]
Hi,
thanks for your instructions: unfortunately it's the same!

(env-dir) riccardo@icpo:~/Scaricati/vorta-master> vorta

![vortatest5](https://user-images.githubusercontent.com/16922051/165614964-2e913656-e446-4518-99c4-06490043e186.png)


[vorta log 27 04 22.txt](https://github.com/borgbase/vorta/files/8576992/vorta.log.27.04.22.txt)

**Comment by carobinario** [comment]
Hi, on Opensuse Tubleweed, Borg was updated to 1.2 version on Wed Mar 30.

With vorta-master I tried to create a new repository on an internal sata hard disk: same issue + fatal error (see below):

![vorta fatal error](https://user-images.githubusercontent.com/16922051/166141558-bc4e46b6-605c-41dd-86ef-f54d6a321641.png)

[vorta fatal error message.txt](https://github.com/borgbase/vorta/files/8598681/vorta.fatal.error.message.txt)

[vorta log full.txt](https://github.com/borgbase/vorta/files/8598682/vorta.log.full.txt)

**Comment by m3nu** [comment]
Looks like an issue with Dbus and Secretstorage. Usually the lack of either would just mean it falls back to the storing the password in the database. Do you currently use Secretstorage?

(This is unrelated to the Borg version, it's just where Vorta stores repo passwords)

**Comment by carobinario** [comment]
I'm using KeePassXC 2.7.1 as Secretstorage on Opensuse Tumbleweed / KDE Plasma Version: 5.24.4. KWalletManager is disabled. 

Other two repos (created months ago) work ok (https://github.com/borgbase/vorta/issues/1260#issuecomment-1100700745).

**Comment by real-yfprojects** [comment]
Please initialize a repo using borg with blake2-repokey encryption:
```bash
>  borg init --info --log-json  --encryption=repokey-blake2 testrepo
```
The borg command should show the warning you were seeing previously: `you will need both KEY AND PASSPHRASE to access this repo! [...]`
Please run the following immediately after the borg init command:
```bash
> echo $?
```
This will output borg's return code. I expect it to be larger than 0 while it is 0 on my machine with borg 1.1.15.

**Comment by carobinario** [comment]
Hi,
riccardo@icpo:~> echo $?
0

Full log here: [shell log.txt](https://github.com/borgbase/vorta/files/8599032/shell.log.txt)

**Comment by real-yfprojects** [comment]
> With vorta-master I tried to create a new repository on an internal sata hard disk: same issue + fatal error (see below):
> 
> ![vorta fatal error](https://user-images.githubusercontent.com/16922051/166141558-bc4e46b6-605c-41dd-86ef-f54d6a321641.png)
> 

I overlooked this one before. This seems to be a different error that didn't occur previously. As _m3nu_ this indicates a problem with your DBus or secretstorage.
Note: Your are using the window for adding an existing repo not the one for initializing a new one.

> [vorta log full.txt](https://github.com/borgbase/vorta/files/8598682/vorta.log.full.txt)

This one is empty.

**Comment by real-yfprojects** [comment]
> Usually the lack of either would just mean it falls back to the storing the password in the database.

Afaik when storing passwords this does not happen.

**Comment by carobinario** [comment]
I don't understand: is this a bug of my whole system (Vorta + Borg 1.2 + KeepassXC 2.7.1 + Kde Plasma + Opensuse Tumbleweed), a bug of Vorta + KeepassXc 2.7.1 or a bug of Vorta only?

Thanks

**Comment by real-yfprojects** [comment]
Maybe it is the communication with the keyring when storing a password that is freezing the GUI.  This would be my last guess on this issue.
I crafted a branch to debug this:
https://github.com/real-yfprojects/vorta/tree/debug%231260

**Comment by carobinario** [comment]
Thanks, but unfortunately I have the same error.

**Comment by real-yfprojects** [comment]
> Thanks, but unfortunately I have the same error.

Well that's for sure since the branch doesn't fix the issue it only modifies (console) output to allow debugging.

**Comment by carobinario** [comment]
Hi, here is two new logs, from terminal and from vorta.log:

[cli.txt](https://github.com/borgbase/vorta/files/8700891/cli.txt)
[vorta log.txt](https://github.com/borgbase/vorta/files/8700893/vorta.log.txt)

**Comment by real-yfprojects** [comment]
It is the same fatal error as the one you posted earlier. Did the window pop up too?

> ![vorta fatal error](https://user-images.githubusercontent.com/16922051/166141558-bc4e46b6-605c-41dd-86ef-f54d6a321641.png)

**Comment by carobinario** [comment]
> Did the window pop up too?

Yes.

Of course, if I disable KeepassXC Secret Service integration, Vorta works correctly.

**Comment by real-yfprojects** [comment]
> > Did the window pop up too?
> 
> Yes.

This error is either an issue of KeePassXC or `secretstorage` but not a bug of vorta. But if I understood you correctly this error did not occur when first opening this issue which would indicate that there is an additional problem.
