### ISSUE TITLE
Drop support of Python 3.6

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1266]
[Python 3.6](https://www.python.org/downloads/release/python-3615/) has reached end-of-life and is no longer supported. I therefore ask to drop support for it and limit support to the versions `>=3.7`. This will allow for using of the new stuff introduced with `3.7` in the vorta source code.

#### Tasks
- [ ] Update docs

**Comment by m3nu** [comment]
Sounds good. Borg will be >=3.9 from version 1.3

**Comment by Saiesh-Agre** [comment]
is this issue still open?
I may be able to help with this, can you provide more information and how to get started?

**Comment by real-yfprojects** [comment]
> I may be able to help with this, can you provide more information and how to get started?

This issue only needs updating the py version in [this doc file](https://github.com/borgbase/vorta.borgbase.com/blob/f518a1e9f7292e5beb196cbc65c87db8c446b906/install/linux.md).
