### ISSUE TITLE
Select multiple archives

### ISSUE THREAD

**Issue by tio-trom** [borgbase/vorta#1269]
Would be so handy if we could select multiple achieves for deleting. I have so many and deleting them one by one takes a long time. Thanks!

**Comment by m3nu** [comment]
True. Good idea!

**Comment by tio-trom** [comment]
I was wondering when is the major release because I have exceeded the borg disk space because it is almost impossible for me to select individual backups and delete them. So I can't clear more space very quickly...

**Comment by tio-trom** [comment]
I sure do, but it does not seem to prune old archives (the ones created before I tweaked the prune to do so)...

**Comment by m3nu** [comment]
Prune prefix is set to include those?

**Comment by tio-trom** [comment]
Hm it is a weird situation because I am doing the borg backups from my server, and it backs up using the name of the apps it is backing up. But in my Vorta I am not sure how this can be changed.

Here's how my backups look like:
![2022-05-14_13-36](https://user-images.githubusercontent.com/38043315/168423958-e5d19cf4-7faa-4bfd-a699-2b079266698a.png)

And here's how prune looks like:
![2022-05-14_13-36_1](https://user-images.githubusercontent.com/38043315/168423973-336890d0-c6e7-4c7f-9a2e-ea0da63acfbe.png)

**Comment by Hofer-Julian** [comment]
If you want to prune everything, remove the prune prefix

**Comment by tio-trom** [comment]
Ah ok! I did that. Now I will have to basically wait for it to trigger the prune on schedule or? Thanks a lot!

**Comment by m3nu** [comment]
There should be a Prune button. The Borg cli also has a dry run option and will explain why a particular archive is kept or not. (Now in version 1.2)

**Comment by tio-trom** [comment]
Ah ok thanks. Works. I see still a lot of archives but perhaps they only have the files that are needed there. It did delete overall hundreds of GB. 

For example:
![2022-05-14_17-14](https://user-images.githubusercontent.com/38043315/168434363-4a470179-3f73-49fb-8867-b8f59d813bcf.png)

That's the prune config. But here are my archives:
![2022-05-14_17-15](https://user-images.githubusercontent.com/38043315/168434494-2b3fc8ea-56b9-4db0-86fb-bef7bcc03a2a.png)

Still lots of them. Is that normal?

**Comment by real-yfprojects** [comment]
You should have all the backups run in the last 14 days as well as about 13 additional backups.

**Comment by tio-trom** [comment]
Ah yes I think that's right! Was a bit confused since it creates backups for multiple apps that I have. Thanks!
