### ISSUE TITLE
sentry stuff still there in settings

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#127]
although sentry-related code is gone, the settings are still there:

settings -> misc -> send errors to sentry.

**Comment by m3nu** [comment]
Users who used the old version still have the setting in their database. Would have to be actively deleted in `vorta.models`.

For the future it's probably best to only show settings from a white-listed list.

I'm not fully sure on how to handle settings anyways. Maybe hardcoding them a bit more is better. Currently it's just some dicts that get saved to a DB table.

**Comment by ThomasWaldmann** [comment]
There is also sentry stuff in the README.
