### ISSUE TITLE
Backup repository sizes are growing faster than expected, displayed sizes don't match

### ISSUE THREAD

**Issue by keywordnew** [borgbase/vorta#1271]
**Describe the bug**

- backup repository sizes are growing much faster than expected
- displayed sizes from Vorta, BorgBase, and borgbackup no longer match

**To Reproduce**
Steps to reproduce the behavior/findings:
1. run `borg info` in terminal against a local repo A.
<img width="723" alt="Screen Shot 2022-04-23 at 10 49 52" src="https://user-images.githubusercontent.com/10335475/164886349-dcb380d9-4714-493e-bc03-97df008480b3.png">
2. Check same repo in Vorta -> Repository.
<img width="212" alt="Screen Shot 2022-04-23 at 10 55 39" src="https://user-images.githubusercontent.com/10335475/164886357-15402207-5815-45c1-ad48-2cd58fd6e2ea.png">
3. Check parent dir in Finder.
<img width="112" alt="Screen Shot 2022-04-23 at 10 56 47" src="https://user-images.githubusercontent.com/10335475/164886401-548c4370-5707-4091-a4fd-42dc91a3150e.png">
4. Compare.

- Original size (`borg check`) matches Original size (Vorta), accepting rounding
- Compressed size (`borg check`) _does not match_ Compressed size (Vorta)
- Deduplicated size (`borg check`) _does not match_ Deduplicated size (Vorta)
- Deduplicated size (`borg check`) does match Compressed size (Vorta), accepting rounding
- directory size (Finder) matches nothing, and continues to trend upward faster than expected

**Environment (please complete the following information):**

- OS: MacOS 11.6.5
- Vorta version: 0.8.3
- Installed from: `brew`
- borgbackup version: 1.2.0
- Installed from: `brew`

**Additional context**

- I'm finding the issue in local repos, and remote repos on Borgbase.
  - borg check: <img width="723" alt="Screen Shot 2022-04-23 at 11 02 18" src="https://user-images.githubusercontent.com/10335475/164886774-4d9e58fb-809b-4361-b3e7-c11ef1701b6c.png">
  - BorgBase web app: <img width="72" alt="Screen Shot 2022-04-23 at 11 02 45" src="https://user-images.githubusercontent.com/10335475/164886757-cc74c872-810a-482d-89a3-e88a4efdd08d.png">
  - Vorta: <img width="198" alt="Screen Shot 2022-04-23 at 11 03 04" src="https://user-images.githubusercontent.com/10335475/164886761-49389042-c707-4369-bce0-955e72111df3.png">

- no errors in Vorta logs seem to be related to this issue
- this issue like wasn't happening before the last 30 days or so, I'm relatively confident I'd have noticed
- possibly related reported issue from `borgbackup` is https://github.com/borgbackup/borg/issues/5909, but I don't think it's the same cause, as I haven't experienced crashes nor unexpected termination of `borg` processes

**Comment by m3nu** [comment]
Since you are using Borg 1.2, have you already looked into `borg compact` and delayed deletion?

For Vorta the value is from `borg create` to limit the number of Borg calls.

**Comment by keywordnew** [comment]
Thanks for cluing me into `borg compact`.

I did two things. First, I looked for more information about `borg compact`. I see that #1205 is merged and from the comments, there may in future be a checkbox for `compact` in the validation tab. Cool. Second, I ran the command and compared the reported repo sizes. The results are below, in this post.

After running `borg compact` on the same repo as in the origin post, these are the differences compared to the original post:
- directory size (Finder) has fallen and matches Deduplicated size (borg check), with marginal difference

Looks like delayed deletion/[separate compaction](https://borgbackup.readthedocs.io/en/stable/usage/notes.html#separate-compaction) as you mentioned was behind this. And resolved by [`borg compact`](https://borgbackup.readthedocs.io/en/stable/usage/compact.html).

Solved, thank you! 🎉
 
> For Vorta the value is from borg create to limit the number of Borg calls.

I understand this to mean that the values for Deduplicated and Compressed sizes displayed in Vorta actually apply to the most recent _archive_ `create`d for that repo using the [--stats flag](https://borgbackup.readthedocs.io/en/stable/usage/create.html), and not the repo itself.

- borg check: <img width="714" alt="Screen Shot 2022-04-23 at 14 44 52" src="https://user-images.githubusercontent.com/10335475/164908909-05196c5b-62dd-4dcb-9ce0-04a316dc92ba.png">
- Vorta: <img width="204" alt="Screen Shot 2022-04-23 at 14 47 12" src="https://user-images.githubusercontent.com/10335475/164908925-2efbb799-c144-41e3-a2ec-8c444724d680.png">
- MacOS Finder: <img width="65" alt="Screen Shot 2022-04-23 at 14 45 06" src="https://user-images.githubusercontent.com/10335475/164908931-481f2b28-67a5-4ae4-bbe7-3a7771877749.png">

UX-wise, displaying this information in the "Repository" tab of Vorta gives the incorrect impression that all the displayed info is about the repository, not the archive.

**Comment by real-yfprojects** [comment]
Borg is displaying the wrong sizes while vorta displays the correct size of _the whole repository_.
Borg shows the size original size, the size of the original data in compressed form and
the deduplicated and compressed size.
Vorta displays the original size, the deduplicated size and the deduplicated and compressed size which I find more intuitive.

> For Vorta the value is from borg create to limit the number of Borg calls.

This was mentioned because it means that vorta size might not be up-to-date if the repository was modified.

**Comment by keywordnew** [comment]
> This was mentioned because it means that vorta size might not be up-to-date if the repository was modified.

Thanks for clarifying the intent of this point.

> Borg is displaying the wrong sizes while vorta displays the correct size of the whole repository...
> ...which I find more intuitive

I'm inclined to agree with you. While I think there could be improvements to labelling, I have no specific suggestions.

I'll close this issue for now as the main problem of unexpected repository sizes has been resolved. The issue with mismatched displayed sizes across the clients should imo be spun off, if at all requiring follow-up.

Thanks to everyone here who participated!
