### ISSUE TITLE
Cannot add dot files

### ISSUE THREAD

**Issue by casperghst42** [borgbase/vorta#1278]
**Describe the bug**
I am not able to add . (dot) files.

**To Reproduce**
1. Click on 'Add file(s)'
2. Press shift+cmd+. to have finder show . (dot) files and directories
3. Try to select a dot file (not possible)

**Environment (please complete the following information):**
- OS: Catalina (10.15.7)
- Vorta version: 0.8.3
- Installed from: brew

**Comment by real-yfprojects** [comment]
#1173
