### ISSUE TITLE
AttributeError in scheduler on startup.

### ISSUE THREAD

**Issue by fdfytr** [borgbase/vorta#1286]
**Describe the bug**
Pop up alert

**To Reproduce**
After automatic update from previous version
1. Start application

**Environment (please complete the following information):**
- OS: Big Sur 11.6.5
- Vorta version: 0.8.4
- Borg ver 1.2.0
- Installed from: vorta.borgbase.com

```

CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "application.py", line 186, in set_borg_details_result
  File "scheduler.py", line 177, in reload_all_timers
  File "scheduler.py", line 127, in set_timer_for_profile
  File "scheduler.py", line 212, in create_backup
AttributeError: 'NoneType' object has no attribute 'id'
```
[vorta.log](https://github.com/borgbase/vorta/files/8646754/vorta.log)

**Comment by real-yfprojects** [comment]
Next time including the logs would be great since their are the basis of every debugging process.

Also it seems like you do not have repo selected in your profile.
