### ISSUE TITLE
Allow disabling macOS Full Access prompt

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1287]
**Describe the bug**
In some cases it's not desirable to give full disk access to Vorta. We still show the below prompt every time and users have to close it.

Could make sense to add a "Don't show again" checkbox there. Same as we already have with the "Close or Minimize" prompt.

<img width="610" alt="Screen Shot 2022-05-07 at 8 34 39 PM" src="https://user-images.githubusercontent.com/3916435/167279254-8eb615ee-7196-4f50-9edc-9cb2c3b14e68.png">

**To Reproduce**
Remove full access permission in macOS and start Vorta.

**Environment (please complete the following information):**
- OS: macOS
- Vorta version: any
- Installed from: any

**Comment by bigtedde** [comment]
I will take a look into this.

**Comment by real-yfprojects** [comment]
We already have such a checkbox in place in a dialog that is shown when running vorta on a DE without a system tray. Its behaviour is changed in #1620, so you can find a possible implementation via that PR.
