### ISSUE TITLE
"Repository in use message" ignores abort option & reappears continuously

### ISSUE THREAD

**Issue by philipkozeny** [borgbase/vorta#1289]
**Describe the bug**
With the latest 0.8.4 release, you are not able to abort a scheduled backup when the "repository lock" message is shown. Even after pressing abort, the backup seems to rerun after a few moments and the message appears again indefinitely. Only breaking the lock (with the continue option in that case) solves the issue.

<img width="532" alt="Screenshot 2022-05-09 at 14 26 13" src="https://user-images.githubusercontent.com/16721635/167410344-3bb14406-551c-4b55-a53a-961eb3923b65.png">

**To Reproduce**
1. Create a lock on the repository (eg run a long check, or manually create on)
2. Wait for the scheduler to start a backup
3. Press "abort" on the lock message
4. See dialog reappears all the time

**Environment (please complete the following information):**
- OS: macOS 12.3.1
- Vorta version: 0.8.4
- Installed from: Homebrew

**Comment by real-yfprojects** [comment]
So you would want a longer timeout before the scheduler tries running the scheduled backup again?

**Comment by philipkozeny** [comment]
Yes, now it feels like the message reappears every second and you can't really interact with the rest of your system. Maybe doing it in the minute range instead of seconds would be good.

**Comment by sudwhiwdh** [comment]
I get the same warning on Linux. However, only since a few days with Vorta 0.8.4 and it is always about automatic missed backups. What do I have to do so that the warning no longer occurs? And what does it mean at all?

**Comment by real-yfprojects** [comment]
> I get the same warning on Linux. However, only since a few days with Vorta 0.8.4 and it is always about automatic missed backups. What do I have to do so that the warning no longer occurs? And what does it mean at all?

The warning should appear when the repository is currently accessed through borg when vorta tries to do the same. For example if a backup to this repo is running _(in vorta which would be a bug or)_ in a different process.

**Comment by sudwhiwdh** [comment]
> For example if a backup to this repo is running (in vorta which would be a bug or) in a different process.

I only use Vorta with a single repository for which I have set up an automatic daily backup. So how would a second process come into play that also wants to use Borg at the same time?

**Comment by real-yfprojects** [comment]
> I only use Vorta with a single repository for which I have set up an automatic daily backup. So how would a second process come into play that also wants to use Borg at the same time?

I have no idea. I think it would make sense to open a new issue for this.
