### ISSUE TITLE
Repository size shown as N/A

### ISSUE THREAD

**Issue by philipkozeny** [borgbase/vorta#1290]
**Describe the bug**
With my repo the repository information (Original Size etc.) is no longer shown. With ```borg info``` I still get the information, see:

```
------------------------------------------------------------------------------
                       Original size      Compressed size    Deduplicated size
All archives:               64.50 TB             54.62 TB            980.82 GB

                       Unique chunks         Total chunks
Chunk index:                 1282063             62162315
```

Vorta shows:

<img width="305" alt="Screenshot 2022-05-09 at 19 33 49" src="https://user-images.githubusercontent.com/16721635/167465654-1b860b51-0f38-4b2c-926b-68a630728fec.png">

Are there any specific logs I can provide? Was not able to find anything suspicious in `vorta.log`, but here they are:  
[vorta.log](https://github.com/borgbase/vorta/files/8653946/vorta.log)

**Environment (please complete the following information):**
- OS: macOS 12.3.1
- Vorta version: 0.8.4
- Installed from: Home-brew

**Comment by real-yfprojects** [comment]
This behavior was introduced with #1251 and is probably intended. What does the tooltip of the stats labels say?

**Comment by philipkozeny** [comment]
Thanks, seems like after some operations the data is now shown.

**Comment by philipkozeny** [comment]
I need to add, that the info is now set to N/A again (probably after an automatic prune). Just FYI: from a users perspective this is kinda confusing when you use the automatic prune option and this happens regularly.

**Comment by real-yfprojects** [comment]
Maybe we could schedule a `borg info` job after pruning or deleting an archive to refresh the data.

**Comment by rmeissn** [comment]
This is still a problem on Vorta 0.9.1 and borg 1.2.4 via flathub
