### ISSUE TITLE
Recommended borg version

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#1297]
There's a recent issue at the flatpak repo of Vorta https://github.com/flathub/com.borgbase.Vorta/issues/59 asking whether it could be updated to borg 1.2.

Should I?
I see work being done to support 1.2, but which borg version do we recommend at the moment?

**Comment by m3nu** [comment]
1.2 is recommended. Should work well. I'm not aware of any issues.

**Comment by Hofer-Julian** [comment]
Thanks, I will update the borg version then.
