### ISSUE TITLE
Snapshot Information is not updated

### ISSUE THREAD

**Issue by bpereto** [borgbase/vorta#13]
Snapshotinformation shows no information about size and duration. Also the Repository Information is not updated.

This happens when returncode from borg is 1:
https://github.com/borgbase/vorta/blob/b13b6f91c1bee1114962e64e4c67efb9d5676619/src/vorta/borg/create.py#L14

But Borg specifies the exit codes as following:
https://github.com/borgbackup/borg/commit/72c984891c964aecaf05c4f3432608b1cae95c6d
> 0 = success (logged as INFO)
1 = warning (logged as WARNING)
2 = (fatal and abrupt) error (logged as ERROR)
please use the EXIT_(SUCCESS,WARNING,ERROR) constants from helpers module.

**Comment by m3nu** [comment]
The snapshot info loaded via the `list` subcommand doesn't have that information. Future snapshots you do from the tool will have it.

From what I saw, exit code 1 is generally a failure. Like no network.

**Comment by bpereto** [comment]
alright,

I runned the same command manually with output. In my cas it was insufficient permission/protection of an application.
Backup worked, but with errors:
```
/home/beni/.config/Bitwarden: scandir: [Errno 13] Permission denied: '/home/beni/.config/Bitwarden'
```

**Comment by m3nu** [comment]
This indicates that your user can't access the Bitwarden directory. Probably for security, since it's some kind of keychain.

You can either exclude this dir from backups or fix the permissions.

**Comment by m3nu** [comment]
Closing this, as the change needs to be made in Borg itself. (showing size of each snapshot). Not sure whether they have this data.
