### ISSUE TITLE
Vorta should launch with a single instead of a double click from the dock

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1300]
Hello, I have installed the current Flatpak version 0.8.4 under Linux.
Apps like LibreOffice, Firefox, Tor Browser, KeePassXC etc. all need only a single click to launch the app from the dock.
How come this is different for Vorta?

**Comment by sudwhiwdh** [comment]
Thank you. I am looking. What can I say.
The LINUX OS is called elementary OS 6.1.
The desktop environment is called PANTHEON.
The dock is called PLANK.

**Comment by sudwhiwdh** [comment]
Made another exciting observation that may be related to launching from the dock. When I start the Flatpak from the terminal, I often see the following screen even after closing and retrying several times. 
![Screenshot](https://user-images.githubusercontent.com/58292468/171437913-44e2e8bf-55a1-4879-95a4-8177c8aeb311.png)
The result is every time that the process remains at this point and also the Vorta application window does not open.

**Comment by real-yfprojects** [comment]
I couldn't install Elementary OS in my VM. I am therefore not able to have a look at this issue.
Your screenshot looks like a problem with the flatpack and its interacting with the DE.
What do you think @Hofer-Julian?

**Comment by sudwhiwdh** [comment]
If I click once on the Vorta Dock icon and then additionally start the Vorta Flatpak in the terminal, the result changes as follows:
![Screenshot](https://user-images.githubusercontent.com/58292468/171847357-bf40eac5-7170-4d05-a9d5-962c739323e0.png)
The application window finally opens and it seems that there are now two instances of Vorta running in parallel.

**Comment by sudwhiwdh** [comment]
> Can you show a screenshot of the settings tab?

Which tab is the setting tab supposed to be? There is none that has such a title.

> I don't think so because the one in the terminal exited.

Why does the terminal output the following: "An instance of Vorta is already running."?

**Comment by real-yfprojects** [comment]
> Which tab is the setting tab supposed to be? There is none that has such a title.

Its called `Misc`.

> Why does the terminal output the following: "An instance of Vorta is already running."?

Vorta has a feature that prevents opening vorta multiple times. This ensures that there is always only a single process running. When clicking on the dock vorta starts but it doesn't open the window and remains in the background. The second click then tells the running instance to become visible.

**Comment by m3nu** [comment]
There could be some explanatory text below the normal checkbox label. That’s how I do it on websites.

**Comment by real-yfprojects** [comment]
Your screenshot shows that you have deselected `Open main window on startup`. Therefore when starting vorta the main window remains hidden.

**Comment by sudwhiwdh** [comment]
After selecting the option "Open main window on startup", the issue I outlined at the beginning is solved. Vorta now also starts with a single click from the dock.
At the same time, another error message seems to have disappeared, which occurred when the option "Open main window on startup" was deactivated and the option "Run missed backups on startup or wakeup" was activated.
I am unsure right now: Was the option "Open main window on startup" originally enabled by default in Vorta?
If so, I probably turned it off because I thought it meant something similar to "Automatically start Vorta at login". And I don't like programs that need resources already at system startup.

**Comment by real-yfprojects** [comment]
> At the same time, another error message seems to have disappeared, which occurred when the option "Open main window on startup" was deactivated and the option "Run missed backups on startup or wakeup" was activated.

What other error message?

> Was the option "Open main window on startup" originally enabled by default in Vorta?

It should have been.

> If so, I probably turned it off because I thought it meant something similar to "Automatically start Vorta at login". And I don't like programs that need resources already at system startup.

Yeah, the difference between the two is not clear.
