### ISSUE TITLE
error on right clicking the archive

### ISSUE THREAD

**Issue by arun54321** [borgbase/vorta#1303]
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/views/archive_tab.py", line 163, in archiveitem_contextmenu
    menu.addAction(self.bMount.icon(), self.bMount.text(),
AttributeError: 'ArchiveTab' object has no attribute 'bMount'

![image](https://user-images.githubusercontent.com/42943340/169274794-6b53113f-e153-470e-954a-6e4c090cf5d5.png)

OS: fedora 36
with the latest vorta available on flathub.

**Comment by m3nu** [comment]
Already fixed in `master`.
