### ISSUE TITLE
0.8.5 Release

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1312]
This will be a bugfix release to improve larger changes shipped in the previous release.

- macOS builds can be found/triggered here: https://github.com/borgbase/vorta/actions/workflows/build-macos.yml
- Or use Pip to test the current master branch: https://vorta.borgbase.com/contributing/#testing-the-current-development-version

Any pressing issues we need to address before releasing this? @real-yfprojects ?

[Open milestones](https://github.com/borgbase/vorta/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22v0.8.x+%28Next+minor+release%29%22) for next minor version.

**Comment by real-yfprojects** [comment]
> Any pressing issues we need to address before releasing this? @real-yfprojects ?

#1311 and #1313 should probably be merged before the release.

**Comment by real-yfprojects** [comment]
When do you plan the release for? @m3nu

**Comment by m3nu** [comment]
If all is clear, tomorrow morning maybe?

**Comment by m3nu** [comment]
Here a final macOS build: https://github.com/borgbase/vorta/actions/runs/2372294620

**Comment by m3nu** [comment]
Done. https://github.com/borgbase/vorta/releases/tag/v0.8.5
