### ISSUE TITLE
Systemtray context menu shows only time of next backup but ignores the date.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1315]
The label displaying the next backup time shows only the time of the backup. The user will not know on which day the backup will be run or rather think it was scheduled for today.

https://github.com/borgbase/vorta/blob/f76aa5a5f483b776084dccb5199098154f4b7279/src/vorta/scheduler.py#L193

Instead the label could show the time only if the backup is scheduled for today and show the date only if the backup is scheduled in more than two day's time.

**Comment by tal66** [comment]
Hi, I'd like to do this

**Comment by m3nu** [comment]
So best to think about the options and requirements you guys want to achieve first. Before writing any code.
