### ISSUE TITLE
QTranslator has no attribute 'language'

### ISSUE THREAD

**Issue by maximus555** [borgbase/vorta#1317]
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/app/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language'

**Comment by internetman420** [comment]
I guess this is not a Vorta specific question, but does one know when this fix will reach flathub - and in turn our distros?

**Comment by real-yfprojects** [comment]
> I guess this is not a Vorta specific question, but does one know when this fix will reach flathub - and in turn our distros?

I think the flatpack is always updated to the latest github release. The fix is not merged yet and will have to be released afterwards. I expect both to happen in the next couple of days.

**Comment by real-yfprojects** [comment]
In the meantime you should be save to reinstall version `0.8.4`.
