### ISSUE TITLE
Open main window when started for the first time

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#132]
Not everyone is happy with the current behavior of going straight to the tray icon after starting. We actively decided NOT to show a window on startup, so that Vorta can just silently do it's job without wasting time for users who know what they are doing. For development purposes there is the `--foreground` option which will open a window on startup.

I still prefer to just minimize the window on startup, but would suggest the following changes:

- [ ] When no settings exist (i.e. the first time Vorta is started), show the settings window.
- [x] When Vorta is started a second time, also open the settings window. (Currently we just display an error message.

**Comment by ThomasWaldmann** [comment]
Can there be conflicts if 2 vorta access the settings DB?

**Comment by m3nu** [comment]
Technically it's [not an issue](https://www.sqlite.org/faq.html#q5) as long as they don't write at the same time. But logically it would be confusing if they both change different settings.

**Comment by Hofer-Julian** [comment]
Actually I also think, that on startup, it would be preferable to have it hidden.

But if I would start it manually, regardless if it is already running or not, I would expect to see a GUI in the foreground.

**Comment by ansemjo** [comment]
Current [Gnome Desktops](https://www.gnome.org/) simply do not have a tray area anymore - which left me quite confused after I first started Vorta because nothing visibly happened. Running `vorta` in a terminal then said it was running already. Killing the running instance and starting it again with `-f` pops up the main window.

I think showing the main window would be desirable. Just don't make it kill the background process when you exit the window and reopen said window when you start Vorta from the applications list again?

**Comment by Hofer-Julian** [comment]
> Not everyone is happy with the current behavior of going straight to the tray icon after starting. We actively decided NOT to show a window on startup, so that Vorta can just silently do it's job without wasting time for users who know what they are doing. For development purposes there is the `--foreground` option which will open a window on startup.
> 
> I still prefer to just minimize the window on startup, but would suggest the following changes:
> 
>     * When no settings exist (i.e. the first time Vorta is started), show the settings window.
> 
>     * When Vorta is started a second time, also open the settings window. (Currently we just display an error message.

To solve the first, it would be good to have a "--background" instead of a "--foreground" option, right? We'd only need to change the behaviour of the autostart method for macOS if I'm not mistaken.



> While doing the translation work, I restarted vorta quite often. I noticed that some commandline option would be useful that starts it in foreground, GUI window visible and terminates when window is closed.

The next step would probably be to implement this. I would also find this function convenient.

**Comment by m3nu** [comment]
No new option, like `--background `. Nobody can find it. I'd just open the main window IF a new database is created on startup. If a settings database already exists, then we can assume the user already started Vorta before and roughly knows how it works.

**Comment by Hofer-Julian** [comment]
But with that, Gnome users without an extension would have to start vorta one time to start it and another time to bring it to the foreground (when the second point is implemented).

Also I wonder about the design choice to start it in background on default. I can think of no other program which behaves that way, unless during autostart and there one could use e.g. a background option.

**Comment by m3nu** [comment]
> But with that, Gnome users without an extension would have to start vorta one time to start it and another time to bring it to the foreground (when the second point is implemented).

Not sure I'm understanding this. Is it still about opening the settings window? Why would they start it multiple times?

**Comment by m3nu** [comment]
There could be a setting to disable showing the window.

Most of my programs behave this way (no window on startup). Their job is just to be there in the background and do their job.

- password manager (1Password)
- application firewall (Little Snitch)
- VPN manager (Shimo)
- Bandwidth monitor (Bandwidth+)

Why would any of those open a window on startup?

**Comment by Hofer-Julian** [comment]
Oh, maybe I didn't made my point clear, sorry for that.

> I still prefer to just minimize the window on startup, but would suggest the following changes:
> 
>     * When no settings exist (i.e. the first time Vorta is started), show the settings window.
> 
>     * When Vorta is started a second time, also open the settings window. (Currently we just display an error message.

Assume this is implemented, I use pure Gnome and I already started vorta at least one time.
Now I want to open Vorta, so I go for example to the terminal and write vorta. And nothing visible happens. Now I have to write vorta again to bring it to the foreground.




> There could be a setting to disable showing the window.
> 
> Most of my programs behave this way (no window on startup). Their job is just to be there in the background and do their job.
> 
>     * password manager (1Password)
> 
>     * application firewall (Little Snitch)
> 
>     * VPN manager (Shimo)
> 
>     * Bandwidth monitor (Bandwidth+)
> 
> 
> Why would any of those open a window on startup? Vorta is the same category. Why would it need to open a settings window all the time? I don't really care, as long as the backups get done.

That's actually what I wanted to say. It makes sense to start it in the background on startup. But if I open Vorta manually, I would expect to see a window popup.

If it would be foreground on default, the user would simply have to start vorta to see a window. And the background option could be used for the process responsible for starting Vorta during startup. No one  would have to play with command line parameters that way.

**Comment by ansemjo** [comment]
> Assume this is implemented, I use pure Gnome and I already started vorta at least one time.
> Now I want to open Vorta, so I go for example to the terminal and write vorta. And nothing visible happens. Now I have to write vorta again to bring it to the foreground.

Only that this currently does not work. Launching it a second time via the Applicatuons menu does absolutely nothing right now. Trying to launch it from a Terminal at least gives you the error message. So regardless of the background behaviour on startup: can we agree that launching Vorta a second time should at least open the settings window?

Another nit-pick: even if I start vorta with `--foreground` .. if I close this window which is shown I currently have no way to exit the process naturally? Vorta does not react to pressing <kbd>ctrl</kbd>-<kbd>C</kbd>. So at this point I need to `kill` Vorta from a second terminal in order to start it again.

Let me just say that I really appreciate this effort though! Looking forward to replacing Deja-Dup with Vorta. :)

**Comment by m3nu** [comment]
The normal way to quit it would be "Quit" from the tray menu. Ctrl-C would be nice to have. Probably easy to add.

Opening the window when it's already running would be nice too. But I don't know how to find the process and trigger an action (open window) yet.

**Comment by m3nu** [comment]
D-Bus only works on selected Linux desktops.

**Comment by m3nu** [comment]
There is now a setting and the startup behavior changed as well. So closing this issue.
