### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by internetman420** [borgbase/vorta#1321]
I have been using Vorta for quite some time now with no problems. Suddenly today an "Fatal Error" dialog window started to appear. It said that I should file a report here, so I shall!

This dialog window has popped up a couple of times within the last 30 minutes, so it looks like the "steps to reproduce" is to just have vorta running in the background.

I am running Vorta 0.8.5  on Elementary OS 6.1 with Linux z 5.14.0-1029-oem. Borg version 1.2.0.
Vorta is installed through EOS AppCenter.

![Screenshot from 2022-05-25 11 35 31](https://user-images.githubusercontent.com/63474498/170236087-d422ddc9-ee33-4527-a20f-bc9d3f10566c.png)

**Comment by internetman420** [comment]
Oops, I see that this is a duplicate of https://github.com/borgbase/vorta/issues/1317 .

Sorry, please do the admin thing.

**Comment by real-yfprojects** [comment]
There you go. I did the admin thing.
