### ISSUE TITLE
Erreur suite mise à jour VORTA vers 0.8.5

### ISSUE THREAD

**Issue by DominiqueFrt** [borgbase/vorta#1326]
Erreur non prise en charge, veuillez remplir un rapport de bug avec ce texte à l'adresse suivante
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 97, in <lambda>
    self.app.scheduler.schedule_changed.connect(lambda pid: self.draw_next_scheduled_backup())
  File "/app/lib/python3.9/site-packages/vorta/views/schedule_tab.py", line 164, in draw_next_scheduled_backup
    text = get_locale().toString(time, QLocale.FormatType.LongFormat)
  File "/app/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 75, in get_locale
    return QLocale(translator.language())
AttributeError: 'QTranslator' object has no attribute 'language'

Message à la fin de la sauvegarde.
Dépôt dissocié et reconfigurer sans effet.

Operating System: Kubuntu 21.10
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-44-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-2700K CPU @ 3.50GHz
Memory: 15.6 Gio of RAM
Graphics Processor: NVIDIA GeForce GT 710/PCIe/SSE2

**Comment by real-yfprojects** [comment]
#1317
