### ISSUE TITLE
Should Flatpak use a newer PyQt version than 5.11.3?

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1327]
Maybe an update to the newest version of pyqt would be useful. And why not use pypi.org as a source?

**Comment by m3nu** [comment]
@Hofer-Julian, any objections? From what I know Flatpak dependencies are just Json files in our repo?

**Comment by Hofer-Julian** [comment]
They are here: https://github.com/flathub/com.borgbase.Vorta

PRs to update PyQt are very welcome. I will not have time to do it myself any time soon though.
