### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'setText'

### ISSUE THREAD

**Issue by HerroBert** [borgbase/vorta#1334]
Describe the bug
root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 154, in sources_update
    self.update_path_info(row)  # Update data for each entry
  File "/usr/lib/python3/dist-packages/vorta/views/source_tab.py", line 101, in update_path_info
    self.sourceFilesWidget.item(index_row, SourceColumn.Size).setText(self.tr("Calculating..."))
AttributeError: 'NoneType' object has no attribute 'setText'

To Reproduce

random in GUI

Environment (please complete the following information):

    OS:  Xubuntu
    Vorta version: 0.7.5
    Installed from: apt

Additional context
nope

**Comment by real-yfprojects** [comment]
Your logs please!

**Comment by real-yfprojects** [comment]
(Possible) duplicate of #1080.

**Comment by HerroBert** [comment]
Yes, maybe.

But I found a cause. Folders are (sometimes) addes as files. I checked db and found _path_isdir_ = 0 for my last added folder.
So I corrected that and set _dir_files_count_ from -1 to 1 too.
Problem seems to be solved.

**Comment by m3nu** [comment]
> Vorta version: 0.7.5

A pretty old version. Would be interesting if the issue still exists.

**Comment by HerroBert** [comment]
So I have 0.8.3 now and I think problem is gone.
