### ISSUE TITLE
help exclude directory but not specific subdirectory

### ISSUE THREAD

**Issue by Condorello** [borgbase/vorta#1338]
Hello, i'm trying to make an excluding patterns which exclude the /run/* folder but keep including a specific subfolder /run/media/user/Archive.
Archivio is where my linux box mount for default the second hard drive where i store files i want backupped.

I already tried to put in origins directory /run/media/user/Archive but it doesn't work because later excluding patterns exclude it.

Someone can help me with a valid regex?

Or maybe is better to add a section in Vorta called [inclusions ovverride] which could be run at the end of the queue backup after the exclusions?

**Comment by real-yfprojects** [comment]
A similar  question was posted in #1261. Adapted to your problem the solution probably is the exclude pattern `re:/run/(?!media/user/Archive).*`.
