### ISSUE TITLE
Multiple fatal errors in latest Flatpak version

### ISSUE THREAD

**Issue by Victor239** [borgbase/vorta#1339]
**Describe the bug**
![](https://i.imgur.com/L00cgY1.png)

I received three of these error pop-ups at once.

**To Reproduce**
1. Wait for automatic scheduled backup to start
2. Midway through backup receive multiple fatal errors

**Environment (please complete the following information):**
- OS: Kubuntu 22.04
- Vorta version: 0.8.5 (Borg 1.2.0)
- Installed from: Flatpak

**Additional context**

**Comment by real-yfprojects** [comment]
#1317 Please have a look into the list of closed and open issues before opening a new one.
