### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by amfp** [borgbase/vorta#1344]
Is it possible to translate the application?

**Comment by real-yfprojects** [comment]
The application should automatically choose the language best fitting to the desktop settings. Translation progress can be viewed on [transifex](https://www.transifex.com/borgbase/vorta/). 
If you want to help translating, refer to [the translation docs](https://vorta.borgbase.com/contributing/translations/), create an account on transifex and request joining the vorta translation team on transifex as well.

**Comment by delfino-nunez** [comment]
I added a recommendation for Spanish you requested.
