### ISSUE TITLE
Flatpak version requires ~/.ssh/config to have 600 permissions.

### ISSUE THREAD

**Issue by myfirstnameispaul** [borgbase/vorta#1345]
**Describe the bug**
Flatpak version requires `~/.ssh/config` to have `600` permissions.

**To Reproduce**
1. Install from flatpak using Software Manager
2. Attempt to connect to remote repository using ssh
3. Doesn't connect and reports "ERROR: Connection closed by remote host."
4. Remote host reports no login attempts in `/var/log/auth.log`
5. Change permissions on `~/.ssh/config` from `644` to `600`.
6. Vorta now connects to remote repository using ssh

**Environment (please complete the following information):**
- OS: Linux Mint 20.3
- Vorta version: 0.8.6
- Installed from: Flatpak using Software Manager

**Additional context**
I also installed using `pip`, and it worked immediately without changing permissions on `config`.

**Comment by m3nu** [comment]
Could be added to the docs, but may be more related to SSH or Flatpak than Vorta.
