### ISSUE TITLE
Shift of a few seconds with fixed schedule.

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1363]
I am currently using the flatpak of Vorta 0.8.7 and have observed that the displayed time of my next scheduled backup varies from day to day at the seconds position. I would expect if I set a daily backup via the GUI to 12 o'clock, that the backup would then show 12:00:00 for the next day. Whereby the seconds could also be hidden.

**Comment by m3nu** [comment]
QTimer isn’t fully deterministic due to battery optimization at the OS level.

https://doc.qt.io/qt-5/qt.html#TimerType-enum

**Comment by sudwhiwdh** [comment]
Thank you for the explanation. Then this issue can probably be closed, right? Would you say it makes sense to display the seconds graphically at this point?

**Comment by real-yfprojects** [comment]
This is indeed a minor bug. The scheduler only manipulates hour and minute of the day when calculating the next backup time.
