### ISSUE TITLE
i18n infrastructure / integration

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#137]
https://www.transifex.com/ is a nice infrastructure service for translators and free for FOSS projects.

there need to be some scripts pushing / pulling stuff from/to transifex and this needs to be integrated into release process.

**Comment by m3nu** [comment]
I can set that up. There is also https://poeditor.com as an alternative (free for < 1000 strings). They integrate with Github, but are probably less sophisticated than Transifex.

**Comment by ThomasWaldmann** [comment]
I personally used / would use vim anyway. :)

**Comment by m3nu** [comment]
Then let's skip the web interface for now. I'm looking into Qt Linguist to edit the translations nicely.

**Comment by ThomasWaldmann** [comment]
We can skip it for right now, but after getting the groundwork done, transifex (or similar popular service) would be quite useful for visibility to translators / easy of use by non-programmer translators.

**Comment by m3nu** [comment]
Looked into it further. Qt Linguist is very hard to install because it comes in a package with an online installer. And Poeditor or Poedit (a desktop GUI) both don't support Qt .ts files. 

So I'd suggest to use Transifex with their Github workflow. They allow to "pull" new translations and make a PR from them. https://docs.transifex.com/integrations/github

**Comment by m3nu** [comment]
Set it up with Transifex and added your existing translations. Seems workable.

![screenshot 2019-01-19 at 09 43 13](https://user-images.githubusercontent.com/3916435/51420631-becf9980-1bce-11e9-850c-d2ce4fb62246.png)

**Comment by ThomasWaldmann** [comment]
Hmm, maybe we want to have all source files in the repo that are needed to build the package - that would include .ts files. So, I'ld suggest that when a release is made, stuff from transifex is pulled and committed to the repo. Not the binary .qm files, of course.

**Comment by m3nu** [comment]
Thought so. Good to have some redundancy anyways. Will make that change.

**Comment by ThomasWaldmann** [comment]
I've noticed you've taken "borg" as organisation name on transifex.
How about "borgbase" (like on github) or "vorta"?

**Comment by m3nu** [comment]
I had "borgbase" at first, but changed it because it wasn't directly related.

Changed it back to borgbase now for consistency. Maybe I will translate the website in the future. Who knows..

**Comment by ThomasWaldmann** [comment]
Thanks. Another thing I noticed is that the files in all languages there have "en" in their name. Likely that shall mean the language of the original strings, but it is a bit unusual.

Also it has "ts" in the basename (additionally to the ".ts" extension) if you download such a file.

**Comment by m3nu** [comment]
I'm not getting the second .ts extension. Is that via the web interface?

I would use their cli-tool to update translations. Better than moving files around. There is [a config file](https://github.com/borgbase/vorta/pull/134/files#diff-cb86fa52440c3b29e9ad70ce1a82fe14) for that in the PR.

The resource file is called `vorta-en-ts` (can be renamed quickly). It's like a slug and not related to the actual filename.

**Comment by ThomasWaldmann** [comment]
I clicked on the download links.

**Comment by m3nu** [comment]
I added their `$ tx pull` command in the Makefile to update translations. For many languages this will be faster than downloading the files each time. The config in `.tx/config` tells it where the destination files and source files are located.

**Comment by ThomasWaldmann** [comment]
I know about the transifex tools, still would prefer to have non-confusing names on transifex.
Like not having "en" show up in the name of the french translation.
And neither "ts" (it looks like we won't need some other translation system, like gnu gettext).

**Comment by m3nu** [comment]
What's a better name? `all` until some distinction comes along?

**Comment by ThomasWaldmann** [comment]
I'ld just use "vorta" until there is some need for sth. else.

**Comment by m3nu** [comment]
Fixed in #134
