### ISSUE TITLE
Vorta system tray icon on menu bar distorted when monitor not in focus

### ISSUE THREAD

**Issue by pm-melo** [borgbase/vorta#1374]
**Describe the bug**
When using multiple monitors on macOS (Intel chip, at least), whenever you change the monitor in focus, the icons of the ones with no focus become stretched. Happens on laptop monitor as well. 

**To Reproduce**
1. Install and run Vorta
2. Connect at least one extra monitor
3. Select a window or the desktop of the other monitor and watch the icon on the menu bar change

**Environment (please complete the following information):**
- OS: macOS 12.4
- Vorta version: 0.8.7 (Borg version: 1.2.0)
- Installed from: GitHub

<img width="135" alt="Captura de ecrã 2022-07-09, às 19 08 38" src="https://user-images.githubusercontent.com/71525994/178117879-540b0494-7c86-4eb4-a542-f7ff128a0347.png">

**Comment by real-yfprojects** [comment]
@m3nu Can you reproduce this?

**Comment by m3nu** [comment]
No. Never seen this.

**Comment by lukecyca** [comment]
This is occurring for me too.

MacBook Pro 2021 (M1 Pro) running macOS 12.5.1 and Vorta 0.8.7

It happens on both my monitors. Whichever monitor currently has focus shows the icon correctly. Whichever monitor does not have focus (and has a dimmed menubar) shows the icon vertically squished.

<img width="479" alt="Screen Shot 2022-10-15 at 15 07 23" src="https://user-images.githubusercontent.com/366484/196009401-daa56bc4-d427-43b9-beaf-0669f28a9967.png">

<img width="471" alt="Screen Shot 2022-10-15 at 15 07 26" src="https://user-images.githubusercontent.com/366484/196009403-827ee269-4447-4c18-ab1c-9a693b08fefc.png">

**Comment by real-yfprojects** [comment]
This behaviour is a known [Qt bug](https://bugreports.qt.io/browse/QTBUG-88600) which is supposedly fixed in Qt `5.12.11`. AFAIK the MacOS bundle uses a PyQt version `5.15` so this issue shouldn't occur.
