### ISSUE TITLE
Append profile information in the status messages

### ISSUE THREAD

**Issue by herrwusel** [borgbase/vorta#1379]
This is a feature request not a bug :)

I use multiple profiles with vorta and often the backups run at the same time. So it would be a nice addition to have the status in the bottom of the gui with more information. In the picture below it is not clear from which profile the message originates:
![image](https://user-images.githubusercontent.com/8242787/182555982-c9e021cd-4fb1-49a8-807c-6b2078e7bbd0.png)

**Comment by diivi** [comment]
Any decision on how this should be done?
How about `ERROR (Profile Name): Connection closed by remote host. Is borg working on the server?`

**Comment by real-yfprojects** [comment]
What about other messages? They can't be associated to a profile either.

**Comment by diivi** [comment]
Yeah, I meant adding the profile in parenthesis to the beginning of all messages in general, my bad.

**Comment by herrwusel** [comment]
First of all, thanks for having a look a this. I would prefer the following pattern: ` (Profile Name) Log level: log message`

**Comment by diivi** [comment]
Thinking of editing these lines in `main_window.py` then:
```python
def set_log(self, text=''):
  self.logText.setText(text)
  self.logText.repaint()
```
to concatenate the `text` after the profile name.
What do you think @real-yfprojects ?

**Comment by real-yfprojects** [comment]
> I would prefer the following pattern: ` (Profile Name) Log level: log message`

Square or round brackets?



> Thinking of editing these lines in `main_window.py` then:
> 
> ```python
> def set_log(self, text=''):
>   self.logText.setText(text)
>   self.logText.repaint()
> ```
> 
> to concatenate the `text` after the profile name.

How do you know from which profile a log was sent?

**Comment by diivi** [comment]
> How do you know from which profile a log was sent?

Oh, yeah, then this should probably be done in the places where we use `self.app.backup_log_event.emit`. 
Just checked `borg_job.py` and I think the profile info is available there right?

**Comment by real-yfprojects** [comment]
> Just checked `borg_job.py` and I think the profile info is available there right?

I think so.

**Comment by herrwusel** [comment]
> Square or round brackets?

Definitely square brackets

**Comment by diivi** [comment]
@Hofer-Julian this can be closed now :)

**Comment by herrwusel** [comment]
Thanks!
