### ISSUE TITLE
Remove phrase "For simple and secure backup hosting, try BorgBase"

### ISSUE THREAD

**Issue by ispmarin** [borgbase/vorta#1382]
**Describe the bug**
The description "For simple and secure backup hosting, try BorgBase" is present on all times, and this is at least an advertisement.

**To Reproduce**
1. Start Vorta 
2. See message

**Environment (please complete the following information):**
- OS: MacOS
- Vorta version: latest
- Installed from: brew

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
Maybe an option to remove the message? Or if Vorta detects that no borgbase repository was added, and remove it automatically? Or remove it after the first close and open cycle?

**Comment by m3nu** [comment]
Unfortunately maintaining software takes time and effort. Much of it is behind the scenes and not glamorous. The commercial BorgBase service helps pay for it, though much of the time I put in is still unpaid.

So I hope you can understand that I'd rather keep this message. Thanks for understanding! 🙏

**Comment by real-yfprojects** [comment]
Since this is free software you can always fork the repository and remove the product placement.

**Comment by ispmarin** [comment]
Of course! Understood. It is a minor inconvenience for such great software.
Thanks for listening and explaining the reason!

Cheers
Ivan

Em seg., 8 de ago. de 2022 15:27, Manu ***@***.***> escreveu:
