### ISSUE TITLE
exclude pattern tmpfile is not cleaned up after the backup

### ISSUE THREAD

**Issue by marco44** [borgbase/vorta#1383]
I suppose it's the same for include pattern files. The file is created, written into, we do the backup, but it's never cleaned. So I end up with hundreds of tmp* files in my /tmp. It's not that big of an issue, but it's still a bit of a mess :)

Is a patch worth it ? I can write one for this if it's deemed useful (it would be for me). This happens with 0.8.7 on current archlinux.

**Comment by m3nu** [comment]
Definitely useful and a patch would be appreciated. 🙏

Just make sure it's still an issue with the current master branch. My guess is yes, since I don't recall any change there.

**Comment by marco44** [comment]
Yeah it still occurs with the git head version
