### ISSUE TITLE
Unify code formatting and setup some kind of automation.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1386]
- Choose a preferred code formatter (black or yapf)
- Run it on the whole code base.
- Think of and setup some system for PRs so that the code formatter is run on all commits/all code. Possible Solutions:
	- Linter only and committer has to run himself
   - formatter bot
   - github action
   - pre-commit script

**Comment by m3nu** [comment]
Yes, please! I mostly use Black and [HN](https://news.ycombinator.com/item?id=17155048) also prefers it.

We can start using it in the v2 branch. Wanna add the config?

To keep it simple, I'd just raise a GH Actions linting error, if Black would detect a change (`black --check`).

**Comment by real-yfprojects** [comment]
> We can start using it in the v2 branch. Wanna add the config?

I would merge #1384 first and then add a commit formatting the whole repository and another one adding the additional linting action. The `borg-v2-branch` as well as pending PRs can be rebased after that.

**Comment by m3nu** [comment]
Fine with me. I don't mind redoing my v2 changes. Not much yet.

**Comment by real-yfprojects** [comment]
> Fine with me. I don't mind redoing my v2 changes. Not much yet.

There shouldn't be much redoing. You rebase onto master interactively while editing the commit. You run black and isort on the modified files when editing. Or you rebase and then amend after running black 
and isort. Something along those lines should work (you can always reflog if it doesn't).
