### ISSUE TITLE
Assign names to repos

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1388]
Repo URLs can be hard to read. Even the ones BorgBase uses. So would suggest to ask for a name when adding a repo and show that in the dropdown and other places.

**Comment by real-yfprojects** [comment]
The tooltip should show the full repo url then.

**Comment by diivi** [comment]
I'd like to work on this next, I was looking for a feature in Vorta like the tags for a repo on BorgBase.

**Comment by diivi** [comment]
> Regarding terminology: Do we want to call it repo name, repo alias or something else?

Borgbase calls it repo name, so I went ahead with that, open to recommendations though.
