### ISSUE TITLE
Clear contents of `logText` after successfull backup.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1389]
Currently the label `logText` is not cleared after a borg command finished. When creating a backup the label will show the path of the last backuped file even after backup completion.

Instead the `progressText` and `logText` labels should be cleared if they show information only relevant during the command execution.

**Comment by real-yfprojects** [comment]
This was already reported here: https://github.com/borgbase/vorta/issues/1356#issuecomment-1157515164

**Comment by aadityasinha-dotcom** [comment]
Hey @real-yfprojects can I work on this issue?

**Comment by real-yfprojects** [comment]
Sure, you'll need to be familiar with (py)qt signals for this one.

**Comment by real-yfprojects** [comment]
> Hey, @real-yfprojects can you explain me about this issue?

What is your question?

**Comment by DaffyTheDuck** [comment]
Hey! @aadityasinha-dotcom are you still working on this ?

**Comment by aadityasinha-dotcom** [comment]
Yes

**Comment by DaffyTheDuck** [comment]
> Hey, @real-yfprojects can you explain me about this issue?

I guess @real-yfprojects means something like this

![log_text](https://user-images.githubusercontent.com/34976093/222709066-d85999b7-0a66-48a4-bdf9-20995b1dc1bd.gif)

See the bottom text disappears after the job is finished 😄

**Comment by real-yfprojects** [comment]
> See the bottom text disappears after the job is finished

That is the goal. Vorta doesn't do this yet afaik.

**Comment by aadityasinha-dotcom** [comment]
okay got it, thank you @DaffyTheDuck

**Comment by aadityasinha-dotcom** [comment]
https://user-images.githubusercontent.com/75474786/222726002-8366c311-a68f-4844-928a-7bd66faeae6d.mp4

But in my system it does not disappears

**Comment by DaffyTheDuck** [comment]
> But in my system it does not disappears

That's what you have to figure out 😄

**Comment by aadityasinha-dotcom** [comment]
@real-yfprojects  can oyu explain this?

**Comment by real-yfprojects** [comment]
> can you explain this?

*this* is an ambiguous pronoun. Be more specific with your question. State what you have already figured out. What problems you are facing and what kind of advice you are expecting.

If I tell you in detail what lines of code have to be written. I can just write the code instead.

**Comment by DaffyTheDuck** [comment]
> @real-yfprojects can you explain this?

In simple, he means that you've to modify the code in such a way that it should remove the labels after the backup is complete 😄 (you can also tweak the code in a way that as shown in my gif it wont remove it instantly)

**Comment by aadityasinha-dotcom** [comment]
okay

**Comment by aadityasinha-dotcom** [comment]
But my question is why it is not disappearing in my system? @DaffyTheDuck

**Comment by DaffyTheDuck** [comment]
> But my question is, why it is not disappearing in my system? @DaffyTheDuck

Because I've modified the code in my system which doesn't exists in main repository, your system contains the code from main repository, so to close this issue you've to modify the code in your system and push the changes so @real-yfprojects and @m3nu and review it 😄

**Comment by aadityasinha-dotcom** [comment]
My bad, sorry I got confused what was the goal of this issue. I thought we need not to disappear the text sorry. And thank you for the clarification @DaffyTheDuck

**Comment by DaffyTheDuck** [comment]
> My bad, sorry I got confused what was the goal of this issue. I thought we need not to disappear the text sorry. And thank you for the clarification @DaffyTheDuck

Never Mind 😄 and All The Best 👍🏼
