### ISSUE TITLE
i18n: potential layout issues

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#139]
UI layout needs to cope with shorter / longer texts flexibly, so nothing gets truncated and layout still looks reasonable somehow.

there might be even more fun if we want to support RTL languages (like hebrew or arabic).

**Comment by ThomasWaldmann** [comment]
if we want to avoid any in-production / in-translation issues with this, we could:

- add some `en_XL` fake translation that just returns the original text twice to produce longer strings.
- not sure, but maybe could work: add some `en_RTL` fake translation that returns reversed strings, so when rendering them RTL it looks correct again.

**Comment by m3nu** [comment]
I think this can be closed. No complaints from IT or FR so far. And not planning to support RTL for now.
