### ISSUE TITLE
Archives action buttons confusing

### ISSUE THREAD

**Issue by drws** [borgbase/vorta#1398]
**Describe the bug**
In the _Archives_ tab there are several action buttons underneath the archive list and several in the sidebar in the right side. To recap:

* _Below_: Refresh, Check, Prune, Compact, Mount
* _Right top_: Refresh, Mount, Extract, Rename (single-archive operations)
* _Right bottom_: Diff, Delete (two-archive operations)

There are several smaller issues with current implementation:

1. The Mount action mounts all archives in the selected folder if none, two or more archives are selected. This is a practical functionality which should be prevented if there are issues with it, otherwise please correct the button description to indicate the possibility. Is there a similar functionality for Extract?

2. It seems logical that Diff button is a two-archive operation, but the same emphasis is also in the Delete button's description implying that only two archives can be deleted at once. I can delete a single archive in the test repository, so what is missing here?

3. The Compact button has no description at all and the same goes for the right-side Mount.

4. There are two typos in buttons' description: a consist**a**ncy in Check and an unneeded final dot in bottom Mount.

5. There are 9 unique actions, two of which are duplicated in both places (Refresh and Mount). 6 of these are already in the right sidebar, which looks like the more practical choice in my opinion. So if 3 more are added to the right side (Check, Prune and Compact), the bottom bar space could be reclaimed.

**Environment (please complete the following information):**
- OS: Arch Linux
- Vorta version: 0.8.7
- Installed from: OS repository

**Comment by real-yfprojects** [comment]
Thank you for submitting this issue report. 
On the right side you can find archive actions while you can find repository actions below.

We will check the descriptions of the GUI elements you mention. Here some notes to your other questions.
 
> 1. The Mount action mounts all archives in the selected folder if none, two or more archives are selected. 
> otherwise please correct the button description to indicate the possibility. 
> Is there a similar functionality for Extract?

This is intended since borg allows mounting a single archive or a whole repository. There is no way of extracting a full repository. This wouldn't make much sense in my opinion but if you still want to you can mount the repository and use copy and paste to "extract".

> 2. It seems logical that Diff button is a two-archive operation, but the same emphasis is also in the Delete button's description implying that only two archives can be deleted at once. I can delete a single archive in the test repository, so what is missing here?

I think you can delete one or multiple archives at once. 

> 5. There are 9 unique actions, two of which are duplicated in both places (Refresh and Mount). 6 of these are already in the right sidebar, which looks like the more practical choice in my opinion. So if 3 more are added to the right side (Check, Prune and Compact), the bottom bar space could be reclaimed.

From my point of view repository actions including check, prune and compact should always be separate from the archive actions.

**Comment by drws** [comment]
Thank you for looking into it. Sending back a few notes as well :)

> On the right side you can find archive actions while you can find repository actions below.
> From my point of view repository actions including check, prune and compact should always be separate from the archive actions.

Thank you for clarifying the grouping and I agree that repository actions should be separated. However, I think that visual separation (vertical spacing) in the right sidebar would suffice, reclaiming some vertical space for the archive list itself. The groups in the right sidebar could also be titled (Repository actions, Single-archive actions, Multiple-archive actions) so the GUI is even clearer.

> I think you can delete one or multiple archives at once.

That was expected, however during GUI cleanup please don't forget to check the two-archive requirement listed in the Delete button GUI hint.
