### ISSUE TITLE
i18n: blacklist/whitelist for translations

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#140]
for translations, there is often some initial enthusiasm and lots of people helping, but sometimes that cools down a bit after a while and some translations get worse and worse.

this is the reason why I suggested some minimum quality in the policy draft (see #138) to avoid vorta giving a bad impression (half translated is worse than not translated IMHO).

we need some code to blacklist below-threshold translations (or whitelist good above-threshold).

also, there could be some means to override that, useful for translators working on improving such translations.

**Comment by m3nu** [comment]
This is probably where using a web service, like Transifex is most useful. They have different roles and a review workflow. People can also sign up on the public project page and add translations there: https://www.transifex.com/borgbase/vorta/

**Comment by m3nu** [comment]
I [set the minimum to 90%](https://github.com/borgbase/vorta/pull/146/files#diff-cb86fa52440c3b29e9ad70ce1a82fe14). Languages lower than that aren't downloaded.

**Comment by ThomasWaldmann** [comment]
Guess that doesn't make the current *.ts file in git go away, they are just not updated.

**Comment by m3nu** [comment]
Currently there is only the German .ts. The rest will be added when they're ready. I'll have an eye on the percentages and remove the .ts files when they go too low. Since I need to pull and commit those files anyways. 

A blacklist of allowed languages would need to be updated manually as well. So the outcome will be the same.

**Comment by brokenpip3** [comment]
I start the italian translation today

**Comment by ThomasWaldmann** [comment]
@m3nu ok, if you intend to manually not pull / remove from git the below-quality-standard .ts files, I guess this ticket can be closed, no python code needed then.

**Comment by m3nu** [comment]
> I start the italian translation today
> EDIT: please accept my join request

I'll do one last check of the English strings today @brokenpip3 . Then update them and then confirm you on Transifex. Just to make sure we don't do translations multiple times.

Someone else on Reddit offered to do French translations. So I'll be adding him too.
