### ISSUE TITLE
No option to *not* use an SSH Key

### ISSUE THREAD

**Issue by Hammit** [borgbase/vorta#1400]
**Describe the bug**
I want to create a backup to external storage mounted locally. No network involved. No need for encryption, however I'm forced to select an SSH Key.

**To Reproduce**
1. Go to Vorta main screen
2. Select a repository
3. Now you are forced to use an SSH Key

**Environment (please complete the following information):**
- OS: Ubuntu MATE 22.04 LTS
- Vorta version: 0.8.3
- Borg version: 1.2.0
- Installed from: apt using Ubuntu repos

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by real-yfprojects** [comment]
You don't need to select an SSH key. It is only needed for remote repositories, but you can select one for local ones anyway - without any effect afaik. 
It might therefore be reasonable to hide the widget from the GUI for local repositories.

**Comment by Hammit** [comment]
My understanding is that without selecting an SSH key the default option is
to use all SSH keys. I read that somewhere I think... Docs maybe

I believe this affects the encryption mode of the backup. I specifically
want to avoid encryption.

from my mobile

**Comment by real-yfprojects** [comment]
> My understanding is that without selecting an SSH key the default option is to use all SSH keys. I read that somewhere I think... Docs maybe I believe this affects the encryption mode of the backup. I specifically want to avoid encryption. 

I don't think so.
Only when connecting to a remote repository *borg* will connect to the server through *ssh*. By default *ssh* will select the correct ssh key for the server. However you can force *ssh* to use a specific key through a command line option. SSH uses TLS encryption to communicate with the server. Only the packages sent through the internet are encrypted. The server can read the plain text. This is where *borg*'s repository encryption comes into play. It encrypts the data stored in the repository on the remote server (or in the local repository) before sending it to the server. When creating a new repository in vorta, you can set the repository encryption which is independent from ssh and doesn't need an ssh key. So in your case you only have to set the encryption method to `None` in vorta when creating the repository while you don't have to bother about ssh keys.

**Comment by Hammit** [comment]
Thank you for clearing this up. It is confusing though and I think your suggestion of hiding it for local repos sounds reasonable.
