### ISSUE TITLE
i18n: localisation l10n

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#141]
opening this to discuss about the l10n part of i18n.

**Comment by ThomasWaldmann** [comment]
date / time formats:

I suggest **not** to support any non-iso-8601 for reasons: https://xkcd.com/1179/

**Comment by m3nu** [comment]
So the task here is to make sure the date is always formatted as `2018-12-31 23:59:59` when displayed?

**Comment by ThomasWaldmann** [comment]
Yes, and I guess the only thing to be "localized" (or rather: "translated") here is the day name or abbreviation (if given).

Like `Fri, 2018-09-13 23:59:59` (en) --> `Fr, 2018-09-13 23:59:59` (de).

**Comment by ThomasWaldmann** [comment]
I had a look into the source and it seems there is nothing to do here, no localized date/time formats are used.

It only uses hardcoded `%Y-%m%d[T ]%H:%M[:%S]` and i did not find weekday names in formatting.

**Comment by m3nu** [comment]
I don't recall ever using a weekday. So close this?
