### ISSUE TITLE
Cannot extract or mount archive on Linux (Xfce 4.16.1): folder selection acts as file picker

### ISSUE THREAD

**Issue by MurdoMaclachlan** [borgbase/vorta#1411]
**Describe the bug:**
I'm trying to extract part of an archive and can't because I can't choose a folder as the extract point, as it acts as a file picker; selecting a folder just opens it. I can't do any sort of workaround such as entering the folder path manually because there's no place either in Vorta or the file picker to do so.

I tried installed Vorta via pip, but that version crashes, which I assume is a separate bug and should have a separate report filed.

**To reproduce:**
1. Go to 'Archives'
2. Click on 'Extract' or 'Mount'
3. After being prompted to choose a folder for extraction or mounting, attempt to choose one.
4. Folder selection acts as file picker, thus you cannot choose a point.

**Environment:**
- OS: Linux (Slackware Current, Xfce 4.16.1)
- Vorta version: 0.8.7
- Installed from: Flatpak

**Additional context:**
I do not believe this issue is the same as #693, which is to do with adding new repos, and has a workaround available that does not work here, and is marked as fixed. I also do not believe it is the same as #372, which was determined to only occur with Flatpak + Wayland; I am using Flatpak, but on X11.

Vorta has all adequate permissions, and in fact has permissions beyond what it should need, as I enabled them in Flatseal whilst trying to fix this.

**Comment by real-yfprojects** [comment]
> I tried installed Vorta via pip, but that version crashes, which I assume is a separate bug and should have a separate report filed.

Feel free to open an issue since this might help pinning the issue down on the flatpak distribution.

**Comment by MurdoMaclachlan** [comment]
> Feel free to open an issue since this might help pinning the issue down on the flatpak distribution.

Done!

**Comment by MurdoMaclachlan** [comment]
I never managed to find a fix for the pip version to test if behaviour is different, but this seems to have been fixed in one of the updates to the flatpak version at least.

**Comment by real-yfprojects** [comment]
> I never managed to find a fix for the pip version to test if behaviour is different, but this seems to have been fixed in one of the updates to the flatpak version at least.

Nice to hear! This was probably fixed upstream.
