### ISSUE TITLE
Vorta 0.8.7 crashes on Linux (Slackware Current) when installed via pip

### ISSUE THREAD

**Issue by MurdoMaclachlan** [borgbase/vorta#1412]
**Describe the bug**
The most recent stable version of Vorta installed via pip crashes for me with the following error:

```
bash-5.1$ vorta
Traceback (most recent call last):
  File "/home/murdo/.local/bin/vorta", line 5, in <module>
    from vorta.__main__ import main
  File "/home/murdo/.local/lib/python3.9/site-packages/vorta/__main__.py", line 7, in <module>
    from vorta.i18n import trans_late, translate
  File "/home/murdo/.local/lib/python3.9/site-packages/vorta/i18n/__init__.py", line 7, in <module>
    from PyQt5.QtCore import QLocale, QTranslator
ImportError: /home/murdo/.local/lib/python3.9/site-packages/PyQt5/QtCore.abi3.so: undefined symbol: _ZdaPvm, version Qt_5
```

The crash is instant, with nothing happening before it. The Flatpak version does not have this crash.

**To Reproduce**
1. Install Vorta via pip
2. Run 'vorta' in shell
3. Observe crash

**Environment (please complete the following information):**
- OS: Linux (Slackware Current, on Xfce 4.16.1, Python 3.9.13, Pip 22.2.2)
- Vorta version: 0.8.7
- Installed from: Pip

**Additional context**
Discovered by installing the pip version to test if it also suffers from the issue observed in #1411.

**Comment by real-yfprojects** [comment]
Into your commandline start `python3`. A python interactive shell will start. Enter

```python3
import PyQt5.QtCore
```
Does the same error show up?

**Comment by MurdoMaclachlan** [comment]
It does

**Comment by real-yfprojects** [comment]
Consequently this is a PyQt issue which you might find help on on the internet or [the official mailing list](https://www.riverbankcomputing.com/support/lists).
