### ISSUE TITLE
Official Fedora Package

### ISSUE THREAD

**Issue by jonathanspw** [borgbase/vorta#1413]
Hi,

I'm a Fedora packager and I've created and will maintain an official vorta package for Fedora versions 35 and later.

This is in main repos and no extra Copr repositories are required, just `dnf install vorta` (or via the GUI software managers in Gnome, KDE, etc.).

It's currently in Rawhide/dev and in the testing repositories for 35, 36, and 37.  It will be in the stable repos in about a week.  I'm working to get it in EPEL9 (and maybe 8) once I work out a few dependency issues.

https://bodhi.fedoraproject.org/updates/?packages=vorta

https://src.fedoraproject.org/rpms/vorta

**Comment by Justinzobel** [comment]
Great work @jonathanspw I just submitted yesterday vorta for review and they mentioned you'd already packaged it a few days before.

I'd be happy to co-maintain the package if you'd like extra hands to make maintenance easier.

**Comment by jonathanspw** [comment]
> Great work @jonathanspw I just submitted yesterday vorta for review and they mentioned you'd already packaged it a few days before.
> 
> I'd be happy to co-maintain the package if you'd like extra hands to make maintenance easier.

Sure.  I added you with commit access.

**Comment by Justinzobel** [comment]
> > Great work @jonathanspw I just submitted yesterday vorta for review and they mentioned you'd already packaged it a few days before.
> > I'd be happy to co-maintain the package if you'd like extra hands to make maintenance easier.
> 
> Sure. I added you with commit access.

Thanks!

**Comment by m3nu** [comment]
Good stuff, guys. 👏 Good to add a link to this here: https://vorta.borgbase.com/install/linux/#distribution-packages ?

**Comment by jonathanspw** [comment]
Yep.  No link is really necessary but use https://src.fedoraproject.org/rpms/vorta if you must.

A simple `dnf install vorta` will suffice :)

**Comment by Justinzobel** [comment]
Added this https://github.com/borgbase/vorta.borgbase.com/pull/30 to update the docs. Once there are EPEL builds it can be updated again.

**Comment by jonathanspw** [comment]
Do you know if there's demand for this on EL8?  I was only going to build official packages for EPEL9 but I will do EPEL8 if you think there is demand/users.

**Comment by Justinzobel** [comment]
> Do you know if there's demand for this on EL8? I was only going to build official packages for EPEL9 but I will do EPEL8 if you think there is demand/users.

I'm not sure. The copr that it's in doesn't have builds for EL8/9 so maybe it hasn't been requested of luminoso.

I'd say most Enterprise Linux desktops are backed up (if at all) using borg directly from the cron or systemd by their system admins instead of a GUI.

**Comment by m3nu** [comment]
Merged the docs PR. So closing this. Thanks everyone for making this happen! 🙏

https://vorta.borgbase.com/install/linux/#fedora
