### ISSUE TITLE
User-defined exclusion patterns have no effect

### ISSUE THREAD

**Issue by unfa** [borgbase/vorta#1415]
**Describe the bug**
I have specified exclusion patterns to avoid backing up unnecessary data, but borg seems to completely ignore them. I have consulted borg manual to make sure the format is correct.

Am I doing something wrong or is this a bug?

My exclusion patterns:

```
/data/Temp/**
/data/Disposable/**
/home/unfa/mountpoint/**
**/.cache/**
**/Olive/mediacache/**
**/hiberfil.sys
**/swapfile.sys
**/pagefile.sys
/mnt/windows/Users/unfa/[...]
**/SteamLibrary/**
```

**To Reproduce**

1. Define an exclusion pattern
2. Run backup
3. Watch as the excluded files are still backed up

**Environment (please complete the following information):**
- OS: Arch Linux
- Vorta version: 0.8.7
- Borg version: 1.2.2
- Installed from: AUR `vorta-git` PKGBUILD

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Comment by real-yfprojects** [comment]
I think you have to replace `/**` in your patterns by `/**/*`.

**Comment by m3nu** [comment]
You're passing sh-style patterns, when the default is fn-style. So you need to either prefix with `sh:` or change to fn-style.

Borg docs have more (also linked in Vorta): https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns.

**Comment by unfa** [comment]
So should I prefix every line in my exclusions with `sh:` ?
Like `sh:/data/Temp/**` ?

**Comment by real-yfprojects** [comment]
> So should I prefix every line in my exclusions with `sh:` ?
> Like `sh:/data/Temp/**` ?

Yes, though I am pretty sure my point applies too.

**Comment by unfa** [comment]
> > So should I prefix every line in my exclusions with `sh:` ?
> > Like `sh:/data/Temp/**` ?
> 
> Yes, though I am pretty sure my point applies too.

Thanks, I will test this.

I wonder if Vorta could help users verify if these things are properly formatted, do some basic syntax checks or stuff?
I tried to follow the examples but ended up with something that wasn't valid.

**Comment by m3nu** [comment]
> I wonder if Vorta could help users verify if these things are properly formatted, do some basic syntax checks or stuff? I tried to follow the examples but ended up with something that wasn't valid.

Already planned for a while. See #907
