### ISSUE TITLE
can't mount any archives later than a particular one

### ISSUE THREAD

**Issue by chewywater** [borgbase/vorta#1424]
### Description

I have an archive that won't mount. All archives later than this one won't mount either. I can still restore from them using 'extract' though. 

REPRODUCE:
Boot computer
vorta>archives> select archive Rigel-2022-09-28-151826 > hit 'mount' button on right side of archive list. 

DETAILS and DATA (note that vorta-log was taken during this activity)
vorta>archives>mount Rigel-2022-09-28-111802, mounts
vorta>archives>mount Rigel-2022-09-28-131814 mounts
vorta>archives>mount Rigel-2022-09-28-151826 FAILS

- never gets past “mounting archive into folder”, never shows mount point in ‘mount point’ column in vorta ui. 
- linux shows that something is mounted.
- when i try to click on mount in file manager i get the error dialog "transport endpoint is not connected”

- - if i try to mount an archive that previously was mountable, in the same folder i get a dialogue ‘the folder contents could not be displayed’ with small print "transport endpoint is not connected” 
- and any attempt to access that mounted directory I get "transport endpoint is not connected”. 

Rebooted
mount	Rigel-2022-09-28-151826 FAILS
Rebooted
mount Rigel-2022-09-28-172339 (the one after the failing archive) FAILS
Reboot
mount Rigel-2022-09-28-192351 FAILS (2nd one after failing archive) 
Pattern: it looks like archive Rigel-2022-09-28-151826, won’t mount, and all the archives later than that won’t mount. 

Looking through the log now. lots of flatpack warnings after trying to mount and unmount, but these happen regardless of whether the archive is good or not. 
[vorta-log.txt](https://github.com/borgbase/vorta/files/9678008/vorta-log.txt)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux Mint 21 Cinnamon

### Version of Vorta

Vorta 0.8.7 ...... Borg 1.2.0

### What did you install Vorta with?

Flatpak

### Logs

[vorta-log.txt](https://github.com/borgbase/vorta/files/9678008/vorta-log.txt)

```pytb
not enough room here. please see vorta-log.txt attached
```

**Comment by real-yfprojects** [comment]
This primarily seems to be an issue with `flatpak-spawn`. Please open [a bug report at their repository](https://github.com/flatpak/flatpak/issues/new?assignees=&labels=bug&template=bug_template.yml&title=%5BBug%5D%3A+Unable+to+read+struct+signalfd_siginfo%3A+Bad+file+descriptor) with the title
```
[Bug]: Unable to read struct signalfd_siginfo: Bad file descriptor
```
and the following issue description:
````
This issue occurs with [`com.borgbase.Vorta`](https://github.com/flathub/com.borgbase.Vorta) which is a GUI frontend for the backup tool [borg](https://github.com/borgbackup/borg). Borg allows mounting a backup repository using fuse. For use in the flatpak distribution of Vorta `libfuse` is installed as configured [here](https://github.com/flathub/com.borgbase.Vorta/blob/master/dependencies/libfuse.json) and wrapped with a small script that runs `fusermount` through `flatpak-spawn`. This usually works fine but not on my machine as reported on borgbase/vorta#1424. 

Borg calls backups that are stored in the same repository *archives*. When the vorta application runs `borg mount` a warning is occurs:

```
** (flatpak-spawn:46): WARNING **: 12:49:29.683: Unable to read struct signalfd_siginfo: Bad file descriptor
```

For some archives mounting works nonetheless, for others it doesn't. Since this seems to be an issue of `flatpak-spawn` the vorta devs redirected me to this bug tracker.
````

Thanks.

**Comment by chewywater** [comment]
Thanks. I opened the issue on flatpak https://github.com/flatpak/flatpak/issues/5127 as instructed.

OK. So I'm assuming that my best option for a workaround is to install the non-flatpak version of Vorta?

**Comment by real-yfprojects** [comment]
> OK. So I'm assuming that my best option for a workaround is to install the non-flatpak version of Vorta?

Yes, I would recommend installing through python (*pip3*) for the latest features. This will also allow confirming that this is a flatpak-only issue.

**Comment by chewywater** [comment]
OK. Thanks for the advice. 
I'm not sure I'm technical enough to install through pip3.  
I'll just install vorta (non-flatpak version 0.8.3-1) through mint's software manager for now, and see how it goes.
If you think it's really critical I install from source, let me know.

**Comment by smcv** [comment]
This actually looks like a bug in the script bundled with vorta's Flatpak packaging, which is invoking flatpak-spawn incorrectly. Please edit the script similar to https://github.com/flathub/org.flatpak.Builder/pull/47 (or open an issue on https://github.com/flathub/com.borgbase.Vorta if the Flatpak packaging has a different maintainer).

The flatpak-spawn bug here is that when it's given an invalid `--forward-fd`, the error message is unclear and looks like a problem with flatpak-spawn: https://github.com/flatpak/flatpak-xdg-utils/issues/55

**Comment by real-yfprojects** [comment]
@chewywater You can try the patched version by installing it through the command line:
```
flatpak install --user https://dl.flathub.org/build-repo/111266/com.borgbase.Vorta.flatpakref
```

**Comment by real-yfprojects** [comment]
> When will this patch become part of the public version offered in Mint Software Manager? 

@Hofer-Julian

**Comment by Hofer-Julian** [comment]
It's already published

**Comment by chewywater** [comment]
Awesome, thanks guys!
