### ISSUE TITLE
Discrepancy between repo combobox and db for newly created profiles.

### ISSUE THREAD

**Issue by Lju88** [borgbase/vorta#1428]
### Description

Hello, whenever I switch to another profile and start a backup I receive the "Add a backup repository first." error. I'm able to backup from the profile where I added the repo, but not from the other ones. The only way to backup this way is to remove the repo and add it from the profile I want to use to backup, but this way it won't work anymore from the previous one.

EDIT: checking the settings.db, the repo column of the other profile was "NULL". Trying to select the repo in the UI doesn't change that. I have only one repo and it's actually already selected. Manually setting the correct id in the database fixes the problem.

### Reproduction

- [x] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

MacOS Big Sur, 11.7

### Version of Vorta

0.8.7

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.2

**Comment by real-yfprojects** [comment]
Would you prefer having the single repository selected by default or having no repository selected in the combobox by default? The latter might prevent mistakes where the user forgot to change the default.

**Comment by Lju88** [comment]
Yeah, the second one looks like the behaviour I would expect.
