### ISSUE TITLE
Unable to mount archives in flatpak due to encoding errors

### ISSUE THREAD

**Issue by ironiemix** [borgbase/vorta#1431]
### Description

I am unable to mount archives with special characters (german umlauts) in the flatpak distribution of vorta 0.8.7. The logs are appended on this bugreport.

I managed to find the appropriate section in the borg FAQ (https://borgbackup.readthedocs.io/en/stable/faq.html#if-it-crashes-with-a-unicodeerror-what-can-i-do) The locales on both ends are set to "de_DE.UTF-8".

So I manually installed the debian package from bullseye-backports (also vorta version 0.8.7, https://packages.debian.org/bullseye-backports/vorta), exported the settings from the flatpak install and imported them to the native debian-packaged version. Now I could mount my archives without any problems.

So I suspect a problem with the flatpak version of vorta on ubuntu 20.04 somehow not knowing of the locale setting of the host?

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Zorin OS, based on ubuntu 20.04 focal

### Version of Vorta

0.8.7

### What did you install Vorta with?

Flatpak

### Version of Borg

1.2.0

### Logs

```pytb
2022-10-14 11:18:45,569 - vorta.borg.borg_job - INFO - Running command /app/bin/borg --log-json mount ssh://myuser@myserver:1234/borgbackup/repos/beispielnutzer/data::yoga260-2022-10-14-111751 /home/beispielnutzer/backup
2022-10-14 11:18:48,989 - vorta.borg.borg_job - ERROR - Local Exception
2022-10-14 11:18:48,994 - vorta.borg.borg_job - ERROR - Traceback (most recent call last):
  File "borg/archiver.py", line 5089, in main
  File "borg/archiver.py", line 5020, in run
  File "borg/archiver.py", line 1304, in do_mount
  File "borg/archiver.py", line 183, in wrapper
  File "borg/archiver.py", line 1314, in _do_mount
  File "borg/fuse.py", line 542, in mount
  File "borg/fuse.py", line 275, in _create_filesystem
  File "borg/fuse.py", line 352, in _process_archive
  File "os.py", line 812, in fsencode
UnicodeEncodeError: 'ascii' codec can't encode character '\xd6' in position 20: ordinal not in range(128)

Platform: Linux yoga260 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64
Linux: Unknown Linux  
Borg: 1.2.0  Python: CPython 3.9.10 msgpack: 1.0.3 fuse: llfuse 1.4.1 [pyfuse3,llfuse]
PID: 199  CWD: /home/beispielnutzer
sys.argv: ['/app/bin/borg', '--log-json', 'mount', 'ssh://myuser@myserver:1234/borgbackup/repos/beispielnutzer/data::yoga260-2022-10-14-111751', '/home/beispielnutzer/backup']
SSH_ORIGINAL_COMMAND: None
```

**Comment by real-yfprojects** [comment]
This is unusual since the flatpak docs state:

> Environment variables are generally passed on to the sandboxed application, with certain exceptions. The application metadata can override environment variables, as well as the --env option. Apart from that, Flatpak always unsets or overrides the following variables, since their session values are likely to interfere with the functioning of the sandbox: 

`LANG` isn't included in the list that follows the quote. In fact I cannot reproduce this issue on KDE neon which is based on Ubuntu 20.04 too.

You can test the env var forwarding by running the following in the command line:

```
flatpak run --command=bash com.borgbase.Vorta -c 'echo $LANG'
```

**Comment by ironiemix** [comment]
After reinstalling the flatpak all works fine, I am not able to reproduce the problem now. It occured on two identical Laptops, so I assumed a general bug where obviously only on my installs something went wrong. 

Thanks a lot for looking into this, I think the issue can be closed.
