### ISSUE TITLE
UI: The Mount button is shown twice in the Archives tab.

### ISSUE THREAD

**Issue by Justinzobel** [borgbase/vorta#1436]
Vorta 0.8.7 on Linux
The Mount button is shown twice in the Archives tab.
![image](https://user-images.githubusercontent.com/1370117/196012051-c4c2cae6-4c03-4c24-a897-a22692fa1c09.png)

**Comment by real-yfprojects** [comment]
This is intended. Their tooltips should state how their behaviours differ. One is for mounting a single archive, one for mounting the whole repository.
