### ISSUE TITLE
Manual backups work, but scheduled backups fail

### ISSUE THREAD

**Issue by amorris28** [borgbase/vorta#1439]
### Description

Moved from [this discussion](https://github.com/borgbase/vorta/discussions/1438). 

I setup Vorta with two profiles: one is an ssh repo on borgbase and the other is a local repo on an external hard drive. When I manually run a backup by clicking "Start Backup" both work fine. When I schedule a backup in the Schedule tab, I get a notification that the backup has started, but I don't see any new archives in the Archive tab.

The log says "maximum number of running instances reached (1)" even thought I have no backups running.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Debian 11 Bullseye, GNOME 3.38.5

### Version of Vorta

Vorta version: 0.7.5

### What did you install Vorta with?

Distribution package

### Version of Borg

Borg version: 1.1.16

### Logs

```pytb
2022-10-21 09:57:00,003 - apscheduler.scheduler - WARNING - Execution of job "VortaScheduler.create_backup (trigger: cron[hour='*/1', minute='57'], next run at: 2022-10-21 09:57:00 PDT)" skipped: maximum number of running instances reached (1)
2022-10-21 09:57:51,396 - vorta.scheduler - DEBUG - Job for profile backup-local was rescheduled.
```

**Comment by real-yfprojects** [comment]
Version `0.7.5` is no longer supported. The newest version is `0.8.7`. You can install it [using pip](https://vorta.borgbase.com/install/linux/#install-from-source) or from *bullseye-backports* as described [here](https://backports.debian.org/Instructions/).
