### ISSUE TITLE
i18n: corrupted title for file selector box

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#144]
Debian 9, german locale, working with the code from #134.

The translation of the title of some file/folder selector box into german contains a non-ascii umlaut (äöüß or so).

It does not display the correct character there, just a gap / underscore.

Not sure whether I have a bad font or if there is some unicode issue in Qt / the OS' file selector box.

**Comment by m3nu** [comment]
Just tested on Ubuntu 18.04 and couldn't reproduce it. You have screenshot of the missing ä?

<img width="1215" alt="screenshot 2019-01-20 at 14 43 25" src="https://user-images.githubusercontent.com/3916435/51436124-e5223180-1cc1-11e9-9d21-a85687bc1501.png">

**Comment by ThomasWaldmann** [comment]
To be more precise: it is Debian 9 under Qubes OS.

![vorta-non-ascii-fileselector-title-corrupt](https://user-images.githubusercontent.com/356103/51440367-a9d63180-1cc6-11e9-9d55-082ff8e40cfe.png)

**Comment by m3nu** [comment]
Lucky me. Else I'd be downloading and installing it right now.

**Comment by ThomasWaldmann** [comment]
I solved it like suggested there, works now.
