### ISSUE TITLE
Release v0.8.8

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1443]
Do you have plans for releasing v0.8.8? I would release it now, since borg v2 will need some more time before being released. This also gives us the option to have a bug fix release that is also a feature release when borg v2 is ready.

**Comment by m3nu** [comment]
Sure, we can release it. Will see if anything urgent is left to do.

**Comment by m3nu** [comment]
Master branch works fine here.

I cherry-picked support for 1.2.2. Shall we include it? https://github.com/borgbase/vorta/pull/1456

**Comment by real-yfprojects** [comment]
> Master branch works fine here.

I found some problems.

**Comment by m3nu** [comment]
OK. Just add them to the mile stone.

**Comment by real-yfprojects** [comment]
Next release is good to go when #1462  and #1464 are closed.

**Comment by m3nu** [comment]
Will do some testing tomorrow and then do the release, OK?

**Comment by real-yfprojects** [comment]
Great! :+1:

**Comment by m3nu** [comment]
Done. https://github.com/borgbase/vorta/releases/tag/v0.8.8

Will update Homebrew in 2 days.
