### ISSUE TITLE
Stats for creating backups are confusing

### ISSUE THREAD

**Issue by RubenKelevra** [borgbase/vorta#1448]
### Description

Not sure if that's a Borg issue or Vorta issue, but it's confusing to read that 18.8 GB have been compressed, and it has been deduplicated to 7.2 MB.

![Screenshot from 2022-10-31 10-48-51](https://user-images.githubusercontent.com/614929/198981933-46bbcbdb-c6a8-4fe0-aa62-128809ba752e.png)

I understand that one is 'compressed original data' which Borg has been processed so far, but deduplicated should be renamed.

Reason being is, that if a backup got aborted and continued from the last checkpoint the number deduplication is pretty off: There's no deduplication going on here as only the already uploaded checkpoint data is reused.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

ArchLinux latest

### Version of Vorta

0.8.7

### What did you install Vorta with?

Other

### Version of Borg

1.2.2

**Comment by real-yfprojects** [comment]
> I understand that one is 'compressed original data' which Borg has been processed so far, but deduplicated should be renamed.

What do you propose?

> Reason being is, that if a backup got aborted and continued from the last checkpoint the number deduplication is pretty off: There's no deduplication going on here as only the already uploaded checkpoint data is reused.

Quite frankly, I don't get this. Why isn't there any deduplication after continuing a backup from a checkpoint?

**Comment by RubenKelevra** [comment]
@real-yfprojects I wrote a feature request (#1457) for this with a proposed solution, which follows the principle of least surprise.
