### ISSUE TITLE
zlib selection UI, compression levels, descriptions

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#145]
I just noticed that the UI for it is missing, it just offers all the others.

Also, I am not quite sure about the UI texts for the compression methods, my idea is rather:

- lz4 (modern, super fast low compression)
- zstd (modern, wide range from very fast to very high compression)
- lzma (legacy, slower higher compression)
- zlib (legacy, faster lower compression)

**Comment by ThomasWaldmann** [comment]
hmm, it doesn't let the user select the compression level.

**Comment by m3nu** [comment]
> hmm, it doesn't let the user select the compression level.

Works here, but will try again with the translation PR.

And will adjust the selection of compression levels. I put the current list together at will while developing. I'm sure yours makes more sense.

**Comment by ThomasWaldmann** [comment]
- Zst**d**
- do not advise **(fastest)** for no compression, it is often not true because lz4 saves more time than it needs (overall).
- some well-picked algo+level sounds fine

**Comment by ThomasWaldmann** [comment]
reverse order from fast to slow. that also moves borg's default lz4 compression to top of the list.

**Comment by m3nu** [comment]
OK. Then this wording and order, so users know the algo used.

1. Low compression, very fast (LZ4): `lz4` (selected by default)
2. Medium compression and speed (ZStd): `zstd,3`
3. High compression, slow (ZStd): `auto,zstd,8`
4. Highest compression, very slow (LZMA): `auto,lzma,6`

**Comment by ThomasWaldmann** [comment]
Some users may have started their repo with zlib, so this should be offered also.

Also noting that this is not a 1-dimensional thing, although a list might make it look like that.
speed, compression, algo type/age, ...

**Comment by fischer-felix** [comment]
Is there a way to specify a custom compression level for an algorithm (zstd in my case)? 
I would like to compress more than just level 8, but afaik there is currently no way to set the level.

**Comment by real-yfprojects** [comment]
You can add the[ command line option ](https://borgbackup.readthedocs.io/en/stable/usage/create.html)`-C` of *borg create* in the LineEdit in the ScheduleTab to modify compression.
