### ISSUE TITLE
Unset repository after scheduling backup.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1462]
The scheduler is not update when unsetting the repository for a profile. When the scheduled runs the following error is the result.
Should the user be able to deselect the repository of a profile?

```pytb
Traceback (most recent call last):
  File "/home/theuser/vorta/src/vorta/scheduler.py", line 319, in <lambda>
    timer.timeout.connect(lambda: self.create_backup(profile_id))
  File "/home/theuser/vorta/src/vorta/scheduler.py", line 380, in create_backup
    if self.app.jobs_manager.is_worker_running(site=profile.repo.id):
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by real-yfprojects** [comment]
> Should the user be able to deselect the repository of a profile?

I guess no. What do you think @m3nu?

**Comment by real-yfprojects** [comment]
Also setting the repository again, doesn't trigger the scheduler either.

**Comment by m3nu** [comment]
Yes, would make sense.
