### ISSUE TITLE
FR: More descriptive message when there are no sources.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1463]
When the user didn't configure any sources, the message `borg: error: Need at least one PATH argument`.
Instead vorta should show something a long the lines of `Select sources to backup first`

**Comment by m3nu** [comment]
Sounds like a good pre-run check. Like checking for an available Borg version.

**Comment by Saiesh-Agre** [comment]
I would like to work on this issue, may you guide me about it, so I could get started?
As I'm relatively new to Open Source, any help would be great.

**Comment by m3nu** [comment]
Go ahead! You could add this as pre-run check in `borg/borg_job.py` which already does some checks to e.g. make sure we have a working Borg binary. Best to outline your plan before coding anything.

**Comment by real-yfprojects** [comment]
> You could add this as pre-run check in `borg/borg_job.py`

This check should run for `borg create` only though. So `borg/create.py` would be a better place.

**Comment by diivi** [comment]
How can I reproduce this? I tried backing up without a source 
![image](https://user-images.githubusercontent.com/41837037/221412860-c2e37468-54e0-4477-b7dc-fc9447780207.png)
and without a repository
![image](https://user-images.githubusercontent.com/41837037/221412887-bd13b586-dfcb-40c1-b425-89aebd0ad5b3.png)

**Comment by real-yfprojects** [comment]
Good call, it seems like there are a few more steps to reproduce this. You will have to add a second profile and add sources to it. Then try to make a backup with the profile that doesn't have any sources configured.
