### ISSUE TITLE
Size and Duration Info of Archives get lost when re-adding a Repository

### ISSUE THREAD

**Issue by Tom-H-L** [borgbase/vorta#1469]
### Description

I moved the repository to another directory in the same filesystem (just one folder up) and then re-added the repository to the Vorta profile. Everything worked fine, but the "Size" and "Duration" information for pre-existing archives in the Archives tab got lost in this transition. Only newly created archives after this move of the repo are shown.

Not sure if this is a bug or a missing feature to not have this information displayed after the move of the repo, but it feels buggy to me and if it could be added that the information survives such maneuvers, it would be great.

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Ubuntu 22.04.1 LTS Desktop

### Version of Vorta

0.8.3

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.0

**Comment by m3nu** [comment]
Hello and thanks for taking the time to provide feedback for this project!

This info is recorded by Vorta and not provided by Borg when re-adding a repository, since it's expensive to calculate. So unfortunately it gets lost when removing and re-adding a repository.

**Comment by real-yfprojects** [comment]
You can click on the menu item `Refresh` in the archive actions menu button to fetch this data from the repository. This is not done automatically (for all archives) since that would take a lot of time.

**Comment by Tom-H-L** [comment]
> You can click on the menu item `Refresh` in the archive actions menu button to fetch this data from the repository. This is not done automatically (for all archives) since that would take a lot of time.

I had tried that but it had no result.

Now I updated to 0.8.7 in the wake of upgrading Ubuntu to the latest release and now after opening Vorta for the first time I see all archive size information again!
