### ISSUE TITLE
"Next Backup" info does not get updated correclty

### ISSUE THREAD

**Issue by Tom-H-L** [borgbase/vorta#1470]
### Description

1. I created a new profile with a new repo. at 19:30. While configuring that profile, I set the schedule to backup every 1 hour. The "Next Backup" information set the next backup time to the next full hour: 20:00 
2. Then I manually clicked "Start Backup" so to start with the initial full backup right away, which took way longer than 20:00
3. After finishing the initial full backup at 21:30 the "Next Backup" information was still stuck at 20:00.
4. The only way I could have it update to the right time (22:00) was to change to another profile and change back.

This feels buggy, the correct time should be shown at all times not to confuse or irritate users, leaving many questions open such as "will it ever start backuping now, or did it get stuck in the past for ever, etc".

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Ubuntu 22.04.1 LTS Desktop

### Version of Vorta

0.8.3

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.0

**Comment by m3nu** [comment]
Hello and thanks for taking the time to provide feedback for this project!

I believe this was already changed in a recent version. Can you check if it still happens with the latest released 0.8.8 version? We can't process bug reports of older versions.

**Comment by real-yfprojects** [comment]
This should have been fixed in #1180 which is available since vorta `0.8.4`.
