### ISSUE TITLE
Repository > Original Size grossly wrong

### ISSUE THREAD

**Issue by Tom-H-L** [borgbase/vorta#1472]
### Description

The Original Size indication in the Repository tab is grossly wrong in 2 profiles, showing almost the actual size x2 of repo 1 (1.5 TB instead of actual ca. 780GB) and almost x6 of repo 2 (2.2 TB instead of the actual ca. 400GB)

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Ubuntu 22.04.1 LTS Desktop

### Version of Vorta

0.8.3

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.0

**Comment by m3nu** [comment]
Hello and thanks for taking the time to provide feedback for this project!

Original size is the sum of all files in all archives. Those numbers are provided by Borg, so you would look at their docs for more details.
