### ISSUE TITLE
Symlink follows by default

### ISSUE THREAD

**Issue by lamyergeier** [borgbase/vorta#1477]
### Description

I have added `.nobackup`:

![image](https://user-images.githubusercontent.com/42092626/200177046-03f9aeb8-6d7e-4b4b-a194-9bfa3f040a21.png)

In my Sources there is a folder inside which I have added .nobackup file, and this folder was not in the backup, as expected. At another location in the Sources, I have a symlink to the previous folder which has .nobackup file. The previous folder got added to the backup through the symlinked location!

Please change this  default behavior to not to follow the symlink as it can also lead to circular endless loop!

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Ubuntu 22.04 Gnome 42

### Version of Vorta

0.8.9

### What did you install Vorta with?

Pip

### Version of Borg

1.2.2

### Logs

```pytb
When I paste the LOG I get: There was an error creating your issue: body is too long, body is too long (maximum is 65536 characters).
```

**Comment by m3nu** [comment]
Hi and thanks for taking the time to provide feedback on this project!

Unfortunately the described behavior is implemented in Borg itself and you would need to raise the issue there. Maybe it was already discussed there.

**Comment by real-yfprojects** [comment]
Here is a link to their repository: https://github.com/borgbackup/borg/issues
