### ISSUE TITLE
Vorta in EPEL9 - Update docs

### ISSUE THREAD

**Issue by jonathanspw** [borgbase/vorta#1479]
Hi,

As a followup to https://github.com/borgbase/vorta/issues/1413 I've finished the packaging for EPEL9 now that the deps are done.

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2022-e89aa94d78

This will hit EPEL9 stable in a week (or less if people test it and give it +karma).

**Comment by m3nu** [comment]
Awesome! 👏

**Comment by m3nu** [comment]
Available in EPEL. 🎉

Slightly adjusted the docs to mention this is EPEL and not just Fedora.

Thanks all to making this happen.

```
 # yum search vorta
Last metadata expiration check: 0:47:24 ago on Thu 29 Dec 2022 09:49:26 AM UTC.
======================================================================================= Name Exactly Matched: vorta ========================================================================================
vorta.noarch : A GUI for Borg Backup
```
