### ISSUE TITLE
Repositories in a profile should have separate schedule

### ISSUE THREAD

**Issue by lamyergeier** [borgbase/vorta#1481]
#### Description

A profile that contains several repositories should have separate schedule for each repository. This is sensible as for the same source some backup might be done much more frequently than the others! But in the current design the backup schedule  is same for each repository in the profile! The profile handles the archives separately, it should also handle the schedule separately!

#### Environment

- OS:
- Vorta version: 0.8.9
- Installed from: pip
- Borg version: 1.2.2

#### Logs

```
*paste logs here*
```

**Comment by real-yfprojects** [comment]
A profile defines a backup role including source files, target repository (notice the singular here, in _vorta_ one isn't able to select multiple target repositories yet) and scheduling. If you want to use a different schedule for a specific combination of source files or for a specific repository, simply create another profile.

**Comment by lamyergeier** [comment]
@real-yfprojects  

I am sorry, if I didn't understand, but please look at the following image. We can see that a given profile can have more than 1 target repositories:

![image](https://user-images.githubusercontent.com/42092626/201017152-12d4d38d-85c9-4123-bdd8-8a042c44e079.png)

**Comment by real-yfprojects** [comment]
The combobox allows selecting exactly one repository from the repositories added/connected to vorta. When creating a new profile, you will see that the same repositories are available in the dropdown of the combobox.

**Comment by lamyergeier** [comment]
You are right at a moment we can select any one of the repositories. If we change the schedule for it then the same schedule is used for the another repository also.

**Comment by real-yfprojects** [comment]
> You are right at a moment we can select any one of the repositories. If we change the schedule for it then the same schedule is used for the another repository also.

I think you missed the point. The schedule is only used for the selected repository since each profile can only have one repository associated with it.
