### ISSUE TITLE
FR: Show exact and complete borg command used by vorta to backup

### ISSUE THREAD

**Issue by lamyergeier** [borgbase/vorta#1484]
#### The problem

 [[bit-team/backintime: Back In Time - A simple backup tool for Linux](https://github.com/bit-team/backintime)](https://github.com/bit-team/backintime), another backup software GUI, stores the exact rsync command it uses to backup. This command is also stored in the log for future reference. This is very helpful for troubleshooting. 

Also, may be while backing up the complete command could be shown in the misc tab of the GUI or may be above start backup switch in Repository Tab.

Can you include the exact borg command by Vorta in the log for each archive?

#### Requested Solution

Described above

**Comment by real-yfprojects** [comment]
> Can you include the exact borg command by Vorta in the log for each archive?

We already do.

> Also, may be while backing up the complete command could be shown in the misc tab of the GUI or may be above start backup switch in Repository Tab.

The commands are quite long and, I think, this would clutter the GUI too much.
