### ISSUE TITLE
Error during Vorta operation

### ISSUE THREAD

**Issue by alpinian55** [borgbase/vorta#1485]
#### Description

I have been doing a lot of experimenting trying to find my "perfect" backup and could have easily caused this myself.

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/archive_tab.py", line 479, in delete_result
    deleted_row = self.archiveTable.findItems(self.archive_name, QtCore.Qt.MatchExactly)[0].row()
AttributeError: 'ArchiveTab' object has no attribute 'archive_name'
```

I _was_/_wasn't_ able to reproduce the issue.

#### Environment

- OS:
- Vorta version:
- Installed from:
- Borg version:

#### Logs

```
*paste logs here*
```

**Comment by real-yfprojects** [comment]
I have pasted in our bug report form into your issue. Can fill in the missing details? Thanks.

> I have been doing a lot of experimenting trying to find my "perfect" backup and could have easily caused this myself.

What do you mean by that?
