### ISSUE TITLE
Say where the logs are when telling about warnings in borg execution

### ISSUE THREAD

**Issue by christophehenry** [borgbase/vorta#1486]
#### The problem

Borg execution may complete with warning in which case a message advising to consult the logs a displayed in Vorta. But nowhere it sayd how to find theese logs. 

#### Requested Solution

Provide a link to the log files or the CLI command to execute to consult the logs about the warnings.

**Comment by christophehenry** [comment]
I found this link after searching on internet where to locate Vorta's logs. The fact that I had to search and it was not immediatly obvious is the sign of a UX issue here. If you advise to look at the logs, you should immediatly provide a simple way to consult those logs, that's a good practice.

**Comment by Saiesh-Agre** [comment]
You could provide a button or a link for accessing log in the message itself.
Ex : You can find logs 'here'
or you could point where the logs are.

**Comment by diivi** [comment]
@real-yfprojects This can be closed now :)
