### ISSUE TITLE
Pattern exclusion field doesn't seem to work as documented (always neccessitates absolute paths?)

### ISSUE THREAD

**Issue by christophehenry** [borgbase/vorta#1487]
### Description

My use cas is fairly standard: I want to exclude a bunch of directories and their contents from the backed up directory (my home directory). What I noticed is this directory is not excluded no matter what I write. In the end, the only two things that work are: using the absolute path to the directory or starting the path with `*/` which is very broad.

Now I noticed that [Borg's documentation on patterns](https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns) specifies:

> If you give `/absolute/` as root…

whereas Vorta generates a commands ending by `/home/<my-username>` **without a trainling slash` and I wonder that is why what's documented in Borg documentation doesn't work as expected so far.

For instance, if I want to exclude `/home/user/directory-to-exclude` and Vorta generates `/app/bin/borg create … /home/user`, here is what I tried and didn't exclure the said directory:

```
directory-to-exclude
/directory-to-exclude
pp:directory-to-exclude
pp:/directory-to-exclude
./directory-to-exclude
pp:./directory-to-exclude
sh:./directory-to-exclude
sh:directory-to-exclude
```

The only things that worked:

```
/home/user/directory-to-exclude
*/directory-to-exclude
```

I don't know if that has some influence here but I'm backing up to a Synology with Borg 1.2.1.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Fedora 36 kernel 6.0.5 KDE

### Version of Vorta

0.8.9

### What did you install Vorta with?

Flatpak

### Version of Borg

1.2.0

**Comment by real-yfprojects** [comment]
> Now I noticed that [Borg's documentation on patterns](https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns) specifies:
> 
> > If you give `/absolute/` as root…
> 
> whereas Vorta generates a commands ending by `/home/<my-username>` **without a trainling slash` and I wonder that is why what's documented in Borg documentation doesn't work as expected so far.

I think you missunderstood the borg docs.
When supplying `borg create` with a absolute path as vorta does, the file paths in the backup are relative to the root `/`. Therefore you will have to specify the patterns relative to the root as well. However using absolute paths in the patterns works too.

**Comment by christophehenry** [comment]
So, if I want to exclude `/home/user/directory-to-exclude` and I give `/home/user` to Vorta, what I actually need to indicate is either `home/user/directory-to-exclude` or `/home/user/directory-to-exclude`?

**Comment by real-yfprojects** [comment]
> So, if I want to exclude `/home/user/directory-to-exclude` and I give `/home/user` to Vorta, what I actually need to indicate is either `home/user/directory-to-exclude` or `/home/user/directory-to-exclude`?

Exactly, however I didn't test the first one `home/...`.

**Comment by christophehenry** [comment]
That's very counter intuitive but I suppose that's related tonthe possibly of adding multiple paths to backup. I wonder what happens if you mix relative and absolute paths then…

The doc should probably be updated with a real life example to resolve the ambiguity.

Thank you for the help!

**Comment by real-yfprojects** [comment]
> The doc should probably be updated with a real life example to resolve the ambiguity. 

Yeah, the pattern docs are quite hard to understand. Feel free to open an issue at [borgbackup/borg](https://github.com/borgbackup/borg).

**Comment by christophehenry** [comment]
Done, thank you.
