### ISSUE TITLE
existing repo can't be added

### ISSUE THREAD

**Issue by dynamic4711** [borgbase/vorta#1490]
trying to add an existing repo. Entered the name (with borgbase.con) and the password, but then vorta gives error (unable to add your repository) and in in a pop-up the following:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 6933, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3/dist-packages/peewee.py", line 4306, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/application.py", line 228, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/usr/lib/python3/dist-packages/peewee.py", line 6485, in get
    return sq.get()
  File "/usr/lib/python3/dist-packages/peewee.py", line 6936, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]

**Comment by dynamic4711** [comment]
I should maybe add that this is re vorta 0.8.7 and with borg 1.2.2 on kubuntu jammy (vorta out of jammy backports)

**Comment by real-yfprojects** [comment]
Different issue but same underlying bug as #1449.

**Comment by real-yfprojects** [comment]
> Different issue but same underlying bug as #1449.


Maybe it IS the same. Can you enclose the logs, please?

**Comment by dynamic4711** [comment]
logs. Sure, where do I find those?
BTW: I don't know why, but I tried again to add the repo and it worked for some reason. And yes the other bug looks similar.

**Comment by real-yfprojects** [comment]
> logs. Sure, where do I find those?

*Misc* > *Logs*

**Comment by dynamic4711** [comment]
ok, thank you. the only thing I can find there for the relevant timeframe, however, is what I already posted:

2022-11-12 15:15:32,169 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/peewee.py", line 6933, in get
    return clone.execute(database)[0]
  File "/usr/lib/python3/dist-packages/peewee.py", line 4306, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/application.py", line 228, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/usr/lib/python3/dist-packages/peewee.py", line 6485, in get
    return sq.get()
  File "/usr/lib/python3/dist-packages/peewee.py", line 6936, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]

**Comment by dynamic4711** [comment]
yup is the same as
Peewee error when adding locked repository. #1449
