### ISSUE TITLE
can't install vorta on debian 10

### ISSUE THREAD

**Issue by odufour7** [borgbase/vorta#1496]
### Description

Hi everyone, 

I have problems in installing the software vorta on debian 10. I have just ran on the terminal the following command **pip3 install vorta** , and as you can see, it seems okay: 

Collecting vorta
  Using cached vorta-0.8.9.tar.gz (730 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: secretstorage in ./anaconda3/lib/python3.9/site-packages (from vorta) (3.3.1)
Requirement already satisfied: psutil in ./anaconda3/lib/python3.9/site-packages (from vorta) (5.8.0)
Requirement already satisfied: paramiko in ./anaconda3/lib/python3.9/site-packages (from vorta) (2.12.0)
Requirement already satisfied: peewee in ./anaconda3/lib/python3.9/site-packages (from vorta) (3.15.4)
Requirement already satisfied: appdirs in ./anaconda3/lib/python3.9/site-packages (from vorta) (1.4.4)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.9/site-packages (from vorta) (60.3.1)
Requirement already satisfied: pyqt5 in ./anaconda3/lib/python3.9/site-packages (from vorta) (5.15.7)
Requirement already satisfied: pynacl>=1.0.1 in ./anaconda3/lib/python3.9/site-packages (from paramiko->vorta) (1.5.0)
Requirement already satisfied: cryptography>=2.5 in ./anaconda3/lib/python3.9/site-packages (from paramiko->vorta) (3.4.8)
Requirement already satisfied: six in ./anaconda3/lib/python3.9/site-packages (from paramiko->vorta) (1.16.0)
Requirement already satisfied: bcrypt>=3.1.3 in ./anaconda3/lib/python3.9/site-packages (from paramiko->vorta) (4.0.1)
Requirement already satisfied: PyQt5-Qt5>=5.15.0 in ./anaconda3/lib/python3.9/site-packages (from pyqt5->vorta) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.11 in ./anaconda3/lib/python3.9/site-packages (from pyqt5->vorta) (12.11.0)
Requirement already satisfied: jeepney>=0.6 in ./anaconda3/lib/python3.9/site-packages (from secretstorage->vorta) (0.7.1)
Requirement already satisfied: cffi>=1.12 in ./anaconda3/lib/python3.9/site-packages (from cryptography>=2.5->paramiko->vorta) (1.14.6)
Requirement already satisfied: pycparser in ./anaconda3/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=2.5->paramiko->vorta) (2.20)
Building wheels for collected packages: vorta
  Building wheel for vorta (pyproject.toml) ... done
  Created wheel for vorta: filename=vorta-0.8.9-py3-none-any.whl size=720537 sha256=38dee9d89cc894f381dcb930c6349fb5957e02333391b221ced259e4a053f997
  Stored in directory: /home/odufour/.cache/pip/wheels/bc/fa/2e/f270690814e24183d74c3eda89ad97883f937e675abdd0373c
Successfully built vorta
Installing collected packages: vorta
Successfully installed vorta-0.8.9

But then when I just try to launch vorta with the command   **vorta**, il doesn't work and the following error is triggered:

2022-11-22 14:06:43,900 - root - CRITICAL - Uncaught exception, file a report at https://github.com/borgbase/vorta/issues/new/choose
Traceback (most recent call last):
  File "/home/odufour/anaconda3/bin/vorta", line 8, in <module>
    sys.exit(main())
  File "/home/odufour/anaconda3/lib/python3.9/site-packages/vorta/__main__.py", line 69, in main
    from vorta.application import VortaApp
  File "/home/odufour/anaconda3/lib/python3.9/site-packages/vorta/application.py", line 15, in <module>
    from vorta.qt_single_application import QtSingleApplication
  File "/home/odufour/anaconda3/lib/python3.9/site-packages/vorta/qt_single_application.py", line 2, in <module>
    from PyQt5.QtNetwork import QLocalServer, QLocalSocket
ImportError: /lib/x86_64-linux-gnu/libgssapi_krb5.so.2: symbol krb5_ser_context_init version krb5_3_MIT not defined in file libkrb5.so.3 with link time reference

I am a basic user so maybe it's a very stupid thing. But I am stuck there for the moment. 

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

debian 10

### Version of Vorta

0.8.9

### What did you install Vorta with?

Pip

**Comment by real-yfprojects** [comment]
This is a Qt internal error that probably relates to a faulty installation. It seems like you are using the anaconda python distribution. Usually you shouldn't install packages with pip in anaconda. Instead use the `conda` py package manager.
