### ISSUE TITLE
Vorta should remember the compression type settings again

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1498]
After each restart of Vorta the compression type is reset to LZ4.
No matter what I choose before.

Vorta 0.8.9
Borg 1.2.0
Fedora Flathub Selection

**Comment by real-yfprojects** [comment]
Duplicate of #1495.

**Comment by real-yfprojects** [comment]
This is just a GUI (display) bug that doesn't affect the backups. While the compression set are correctly saved and used, it isn't shown correctly after restart.

**Comment by sudwhiwdh** [comment]
@real-yfprojects Thanks, had searched for it and found no issue.
And also thanks for https://github.com/borgbase/vorta/pull/1499!
