### ISSUE TITLE
FR: Support SSH key agent

### ISSUE THREAD

**Issue by ethrgeist** [borgbase/vorta#1505]
#### The problem
We provision and manage SSH keys for our less technical savvy users via SSH agent, these keys do not show up in Vorta.

#### Requested Solution
Vorta should also query the SSH agent for available keys.

#### Alternatives
-

#### Additional context
-

**Comment by m3nu** [comment]
In that case, just keep it at "Automatic" and SSH should just use it like any other command using `ssh`. The dropdown is only there to use keys with a non-standard name.
