### ISSUE TITLE
Provide light icon set suitable for dark themes

### ISSUE THREAD

**Issue by Gyges88** [borgbase/vorta#151]
The provided icons are barely visible on dark themes (Breeze dark in my case), see screenshots.
Please provide a light icon set for use with dark themes.
OS: Manjaro
DE: plasma 5.14.5
Theme: Breeze dark
![screenshot_20190120_191055](https://user-images.githubusercontent.com/4368901/51443456-5a552d00-1ce9-11e9-9190-6445f3cc1d81.png)
![screenshot_20190120_191121](https://user-images.githubusercontent.com/4368901/51443460-6e992a00-1ce9-11e9-99ec-97084e8c63e2.png)
![screenshot_20190120_192233](https://user-images.githubusercontent.com/4368901/51443477-95576080-1ce9-11e9-859c-ffa4559a9ac3.png)

**Comment by m3nu** [comment]
Good idea. The icons are SVG anyways. So changing the color is simple.

Then it would need to load a different resource-file when our existing `use light icon` option is on or auto-detected.

**Comment by m3nu** [comment]
The icon color now changes together with the "Use light icon". I'm still seeing a few color issues with text on macOS. Will add a PR when done.

<img width="825" alt="screenshot 2019-01-21 at 13 54 42" src="https://user-images.githubusercontent.com/3916435/51455414-6b9f4780-1d84-11e9-93b7-aef71ef18c8b.png">

**Comment by m3nu** [comment]
And here the final result. Used an [external Qt stylesheet](https://github.com/ColinDuquesnoy/QDarkStyleSheet) for the dark theme.

<img width="969" alt="screenshot 2019-01-21 at 14 15 43" src="https://user-images.githubusercontent.com/3916435/51456097-5b3c9c00-1d87-11e9-8b2d-315a261e861d.png">
