### ISSUE TITLE
Help with debugging on macOS - Vorta stucks on startup and does not open

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1510]
### Discussed in https://github.com/borgbase/vorta/discussions/1507

<div type='discussions-op-text'>

<sup>Originally posted by **Vantomas** December  8, 2022</sup>
Hello,
I got new Mac Mini and I copied the home directory from the old one to the new one. After that I have problem with Vorta which does not open anything and stuck only with one process vorta-darwin. If I try to open it in new user profile it works alright so it's something user profile related. 

I tried to use something like strace, but for dtrace I have to disable SIP and Instruments (File Activity/System trace/Time profiles) doesn't show me anything interesting. 

Can you point me in any direction how can I debug this and get why it's stucking somewhere on open, please?
</div>

**Comment by real-yfprojects** [comment]
<div type='discussions-op-text'>

<sup>Originally posted by **Vantomas** December  11, 2022</sup>

Unfortunately it doesn't show anything and it's stuck on something. Even CTRL+C doesn't work and I have to kill the process. I know from another Mac or a clean user profile that Vorta forks into multiple processes and that doesn't happen either.

![Snímek obrazovky 2022-12-11 v 13 33 36](https://user-images.githubusercontent.com/5727555/206903801-ef0cf94a-da5a-4ea9-9cad-6698439317ff.png)
![Snímek obrazovky 2022-12-11 v 13 32 56](https://user-images.githubusercontent.com/5727555/206903766-225dc599-ad0f-48d8-8faf-0cc247fce7b5.png)

</div>

**Comment by real-yfprojects** [comment]
Do the user profiles in your MacOS share the same vorta installation?

What OS version are you running? Which version of vorta do you have installed? How did you install it?

**Comment by Vantomas** [comment]
Yes, Vorta is shared between user profiles. I installed Vorta via Homebrew in /Applications. Currently on version 0.8.9, but I've been having this problem for half a year now, so I've definitely tried some older versions.

Mac mini (2018), Intel Core i7
`$ sw_vers`
`ProductName:	macOS`
`ProductVersion:	12.6`
`BuildVersion:	21G115`

**Comment by Vantomas** [comment]
I tried to clone a repository, download dependencies and then run `python3.10 -v /usr/loca/bin/vorta` and it stucks on `import 'PyQT5'`. 

I wonder if is possible to turn on some debugging output on PyQT5?

[log.txt](https://github.com/borgbase/vorta/files/10219397/log.txt)

![Snímek obrazovky 2022-12-13 v 16 21 08](https://user-images.githubusercontent.com/5727555/207373690-37dbb252-be1f-4a93-a0c6-474902b49bc6.png)

**Comment by real-yfprojects** [comment]
```
python3 -c "import PyQt5"
```
works?

**Comment by Vantomas** [comment]
Yes it works. But I tried debugging the code in VSCode and after about 10 minutes of "Step in" it really stuck somewhere while loading PyQt5.

The first screenshot shows the last "import" call and the second screenshot shows where it gets stuck.

![Snímek obrazovky 2022-12-15 v 13 17 57](https://user-images.githubusercontent.com/5727555/207857899-ac7b678f-7a59-418c-a794-e21571b07203.png)
![Snímek obrazovky 2022-12-15 v 13 18 07](https://user-images.githubusercontent.com/5727555/207857909-32a6ffc5-9044-4fa6-9c9a-4a56f781f4af.png)

**Comment by real-yfprojects** [comment]
So this is not a problem in the vorta code, but with your PyQt5 installation. While `import PyQt5` works probably one of the submodules in pyqt cannot be imported.

**Comment by Vantomas** [comment]
Hi,
just for the reference, I found out what was causing the problem. After few hours of copying and deleting files in ~/Library and many logouts/logins, I found out that the problem was due to the ~/Library/Preferences/.GlobalPreferences_m.plist. I deleted this file, a empty new one was created, but everything works now.
