### ISSUE TITLE
The security option "Try to replace existing permissions when mounting an archive" should be explained somewhere

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1517]
As a user, I have no idea whether I should check the box there or not.

**Comment by sudwhiwdh** [comment]
@real-yfprojects Do you already have an idea of what this could look like?

**Comment by real-yfprojects** [comment]
This could be solved with a tooltip.

**Comment by real-yfprojects** [comment]
@m3nu Is the `try` needed in the label of this setting? Is failure expected when replacing the permissions of the mounted files?

**Comment by m3nu** [comment]
IIRC, overriding permission doesn't always work. Like in cases, where ACLs are used instead of standard Linux permissions. E.g. I've seen Synology NAS have remove all standard permission and then manage everything with ACLs only. When mounting such a backup on macOS, it usually doesn't work.
