### ISSUE TITLE
The font remains grayed out until I click on one of the rows

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1519]
![7](https://user-images.githubusercontent.com/58292468/209375714-737b1d01-0531-4bc1-91db-481b377a3197.png)
![10](https://user-images.githubusercontent.com/58292468/209375713-46b9fd36-5eae-48d1-aa92-ea89d0edc7aa.png)

![8](https://user-images.githubusercontent.com/58292468/209375716-ad909b72-6fa0-41ca-a398-ff4d7e01d659.png)
![9](https://user-images.githubusercontent.com/58292468/209375707-3a1f40eb-310a-4a4e-b212-324d875afec5.png)

![3](https://user-images.githubusercontent.com/58292468/209375722-e8f69925-226a-41a5-9d2d-bd0ad014a82d.png)
![6](https://user-images.githubusercontent.com/58292468/209375718-34f4d96c-58ee-45fb-b191-6fc0cc8bcb22.png)

![4](https://user-images.githubusercontent.com/58292468/209375720-72410721-5a94-470d-9cd3-cd417033570f.png)
![5](https://user-images.githubusercontent.com/58292468/209375719-629584e7-1bfe-46b4-ae1f-d81b5c01cd9a.png)

I expect that the default font setting will not be grayed out. If a row is then explicitly selected, it should then be additionally highlighted in color. The latter is at least the case for me under Fedora 37 workstation.

**Comment by real-yfprojects** [comment]
The same as #1518. Might be linked to the configured Qt style/theme.

**Comment by sudwhiwdh** [comment]
https://github.com/borgbase/vorta/issues/1518#issuecomment-1364699935
