### ISSUE TITLE
Vorta application on linux - SSH key part is gray out

### ISSUE THREAD

**Issue by kellyenfra** [borgbase/vorta#1528]
### Description

I encounter that the SSH key is not being able to click on it 
The box is gray out

I need help is it i didnt install correctly 
can someone help me with this thanks 

my unit is using 
Distributor ID:  Zorin
Description:	Zorin OS 16.2
Release:	16
Codename:	focal

![Screenshot from 2023-01-03 16-10-48](https://user-images.githubusercontent.com/121854511/210320023-030a535c-79cb-47a6-bcb4-13b5ed0a2245.png)

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Description:	Zorin OS 16.2

### Version of Vorta

0.8.9

### What did you install Vorta with?

Flatpak

### Logs

```pytb
non
```

**Comment by real-yfprojects** [comment]
The SSH-Keybox will only be usable with remote repos.

**Comment by kellyenfra** [comment]
I am trying to do a remote backup using vorta to borgbase

**Comment by real-yfprojects** [comment]
Can you enclose a screenshot of the whole window?

**Comment by kellyenfra** [comment]
Hi Borgbase/Vorta

Please see attachment

**Comment by real-yfprojects** [comment]
> Hi Borgbase/Vorta Please see attachment

Sorry, that's not how the email support of github issues works. You will have to embed the image in your email body or use github's web interface.

**Comment by HDInfautre** [comment]
HI
I have the same problem with ubuntu 22.10
I had vorta 0.8.9. I uninstalled it to install 0.8.10 (update not working).
I still have the same version displayed 0.8.9!
Is there a workaround? or should I wait for another version?
Regards

**Comment by real-yfprojects** [comment]
Closed in favour of #1579
