### ISSUE TITLE
Unable to delete profile

### ISSUE THREAD

**Issue by MrDavidMitchell** [borgbase/vorta#1535]
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/vorta/views/main_window.py", line 175, in profile_delete_action
point = QPoint(0, self.profileDeleteButton.size().height() / 2)
TypeError: arguments did not match any overloaded call:
QPoint(): too many arguments
QPoint(int, int): argument 2 has unexpected type 'float'
QPoint(QPoint): argument 1 has unexpected type 'int'

I've attempted to completely purge Vorta to start over.   Vorta worked well for a couple of years and my borg archives had eventually become corrupt.  I deleted the archives through borg, to start a fresh backup.   Now Vorta has started to hang.  To troubleshoot, I set vorta to backup a single ISO file, and it would not complete the backup.  Plenty of disk space.   Using the borg command from the vorta log file works just fine, and the backup of the iso file completes correctly.    Not sure why it's getting hung up.  Not sure where Vorta saves its configuration info.   I uninstalled  (sudo apt remove --purge vorta ) yet after a reinstall vorta picks up my previous configuration profile.  I thought years back I may have installed it through pip or something so I attempted to remove any lingering version with flatpak uninstall and pip uninstall,etc.   It's holding the profile somewhere.   I attempted to delete the profile, it gave the error above.  

Python 3.10.6
Vorta 0.8.3
borgbackup 1.2.0
Linux Mint 21.1   
5.15.0-57-generic #63-Ubuntu SMP Thu Nov 24 13:43:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MrDavidMitchell** [comment]
With the help of another posting I deleted the cache and config files, and things are working again.  

Still not able to delete the profile, but it's not something I plan on doing very often.

**Comment by real-yfprojects** [comment]
You cannot delete the last profile. Though the error you are seeing should not occur.
Vorta stores its settings database in `home/david/.local/share/Vorta/`.
