### ISSUE TITLE
Cannot maximize Vorta user interface window

### ISSUE THREAD

**Issue by cjustin88** [borgbase/vorta#154]
I cannot maximize the user interface window. Dragging one corner of the window diagonally does not change the window size. The text is legible but pages of the configuration that have long lines are scrunched together. Please see the attached screenshot.

1. `pip3 install vorta --user`
2. `vorta`
3. Right click on Gnome appindicator and click on Settings
4. Attempt to maximize window by dragging on one corner, diagonally.

![screenshot from 2019-01-20 20-54-31](https://user-images.githubusercontent.com/5272255/51453746-10bf0f00-1cf6-11e9-9e24-045063fe0f73.png)

 - OS: Fedora 29 (Gnome)

- Linux: `$HOME/.cache/Vorta/log`

```
2019-01-20 20:15:25,734 - apscheduler.scheduler - INFO - Scheduler started
2019-01-20 20:47:52,321 - apscheduler.scheduler - INFO - Scheduler started
```
Thanks.

**Comment by m3nu** [comment]
Not sure why your window is so small. There should be a minimum size.

**Comment by ThomasWaldmann** [comment]
@cjustin88 what is your screen size and resolution? do you have scaling active?

**Comment by brokenpip3** [comment]
@cjustin88 try to change gnome-shell theme with another one (like Arc)

**Comment by m3nu** [comment]
Closing this, since it seems to be an issue with the local setup or window manager.

If anyone else experiences this, feel free to comment here and I'll reopen.
