### ISSUE TITLE
Minor release v8.10

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1543]
Since we have a small but nasty issue that prevents extraction, we should get a new release out soon.

Any blocking issues that should be addressed first? #1521 seems almost ready? @real-yfprojects  There is also milestone https://github.com/borgbase/vorta/milestone/9.

**Comment by real-yfprojects** [comment]
> Any blocking issues that should be addressed first?

Nope.

> #1521 seems almost ready? @real-yfprojects

I won't get it done soon enough. I think there are enough changes (and time) since the last release.

**Comment by m3nu** [comment]
Right. How about merging the Borg v2 branch? I doubt there will be many changes and don't see an issue with making a small tweak later.

**Comment by JSmith-Aura** [comment]
This would be fantastic, I'll just hold off deploying to folk until this is out in the wild. 

Thanks for your guys awesome response its really cool to see a project that actively engages like this!

**Comment by real-yfprojects** [comment]
> Right. How about merging the Borg v2 branch? I doubt there will be many changes and don't see an issue with making a small tweak later.

I don't see a benefit in merging it now but I don't have anything against it either.

**Comment by JSmith-Aura** [comment]
To be a pain, is this a matter of week/s or month/s to get a release up and going? (if its months I'll just push the broken version out to folk so they can at least backup)

**Comment by real-yfprojects** [comment]
> To be a pain, is this a matter of week/s or month/s to get a release up and going?

I would expect it by the end of this week.

**Comment by JSmith-Aura** [comment]
Ah cool! Thanks again for your hard work :D

**Comment by rxgh99** [comment]
> To be a pain, is this a matter of week/s or month/s to get a release up and going? (if its months I'll just push the broken version out to folk so they can at least backup)

Worst-case, extract remains possible from Borg CLI.

**Comment by JSmith-Aura** [comment]
Sure for technical people who are comfortable with the command line. But I prefer to make things as easy as possible on people so this is rather important.

Is this going to be released soon?

**Comment by m3nu** [comment]
Ready to release this, @real-yfprojects ?

This will include some larger changes to support Borg v2, so we may do a bugfix release pretty soon after.

**Comment by real-yfprojects** [comment]
> Ready to release this, @real-yfprojects ?
 
Yes.

> This will include some larger changes to support Borg v2, so we may do a bugfix release pretty soon after.

I expect that too - at the latest when borg v2 comes out of the beta.

**Comment by m3nu** [comment]
Release is out on Github and PyPi. Waiting for Apple to process my membership renewal to do a signed release for macOS.

https://github.com/borgbase/vorta/releases/tag/v0.8.10

**Comment by m3nu** [comment]
macOS release added. Will close this now, but do feel free to share feedback on this release here.

**Comment by JSmith-Aura** [comment]
Thank you guys so much for this! Im just waiting on the brew release then I'll get back to you with feedback :D

**Comment by m3nu** [comment]
Brew release comes a few days after, in case there is an urgent update. Or if someone else adds a PR with them.

Downloading it from here is pretty easy too: https://github.com/borgbase/vorta/releases/tag/v0.8.10

**Comment by JSmith-Aura** [comment]
Just giving some feedback, its working perfectly and folk are very happy with having backups. Thanks again for all your work
