### ISSUE TITLE
Outdated Borg version (1.2.0) included with Vorta Flatpak

### ISSUE THREAD

**Issue by CryptGoat** [borgbase/vorta#1550]
### Description

The Flatpak version of Vorta appears to include an outdated Borg Backup binary. The inlcuded one is Borg 1.2.0, the latest version is 1.2.3. Any chance to get the Flatpak updated? @Hofer-Julian 

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux, Flatpak (FLathub)

### Version of Vorta

0.8.9

### What did you install Vorta with?

Flatpak

### Version of Borg

1.2.0

**Comment by Hofer-Julian** [comment]
@CryptGoat Do you want to open a PR to change this file: https://github.com/flathub/com.borgbase.Vorta/blob/master/dependencies/borgbackup.json?

**Comment by CryptGoat** [comment]
@Hofer-Julian Sure, just have to find a source for valid checksums for the ARM builds.

**Comment by CryptGoat** [comment]
Opened a PR: https://github.com/flathub/com.borgbase.Vorta/pull/96

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian Sure, just have to find a source for valid checksums for the ARM builds.

For the future, one way is to just let it fail.
It will tell you what the correct ones are in the error message.

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian Opened a PR: https://github.com/flathub/com.borgbase.Vorta/pull/96

Thank you
