### ISSUE TITLE
Fatal Error Uncaught exception

### ISSUE THREAD

**Issue by tio-trom** [borgbase/vorta#1551]
### Description

I encounter this bug when I try to extract any archive:

```
Fatal Error
Uncaught exception, please file a report with this text at https://github.com/borgbase/vorta/issues/new Traceback (most recent call last):
File "/usr/lib/python3.10/site-packages/vorta/views/ extract_dialog.py", line 39, in run
parse_json_lines(lines, self.model)
File "/usr/lib/python3.10/site-packages/vorta/views/ extract_dialog.py", line 215, in parse_json_lines model.addItem(
File "/usr/lib/python3.10/site-packages/vorta/views/partials/ treemodel.py", line 369, in additem self._addChild(fsi, path, path[-1], data) IndexError: tuple index out of range
```

The error is brief and Vorta totally crashes. Else it works to mount an archive but if I try to enter any directory in the mounted on, I get a Permission Denied. It used to work for the past years. I did reinstall the OS and brought back all of the config files. Everything else works perfectly fine with Vorta.

Same repository works ok with Pika for example. 

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Arch Linux with XFCE - kernel 6.1

### Version of Vorta

0.8.9

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.2

**Comment by tio-trom** [comment]
> This looks new. Could be weird output by Borg. Would be useful to have the output of the `borg list` command that Vorta runs before the crash.

Can you give me more info about this? I am unsure I understand. I can try to provide you with whatever you need to debug this but I'd need more clear instructions.

**Comment by m3nu** [comment]
I see. Then I'm not sure why Borg adds this one line at the start.

There is no issue with your backup. This is related to parsing the list of files and creating the tree of files. This is very performance-sensitive (as you see from the large input file you gave me.) So we need to be careful about each additional check we add for such errors, as it will affect performance.

**Comment by real-yfprojects** [comment]
> You recall if we had a special case for /?

Nope:
```python console
>>> PurePath('/').parts
('/',)
```

**Comment by m3nu** [comment]
```
In [36]: PurePath('.').parts
Out[36]: ()
```

Then we've found the issue. His file has `.`, not `/` I recall a small Borg change with regard to relative path.

We should handle the case of an empty tuple. Maybe ignore it?

**Comment by real-yfprojects** [comment]
> Maybe ignore it?

Yes, I am already implementing a fix.
