### ISSUE TITLE
Remove Paramiko Dependency

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1559]
This is a heavy depdency and we only use it to verify a file is a SSH key. Would favor removing it and just checking files for starting with `-----BEGIN OPENSSH PRIVATE KEY-----`.

And check for common SSH issues, like wrong ownership or permissions.

Related : #167

**Comment by real-yfprojects** [comment]
Found this: 
https://superuser.com/questions/1515261/how-to-quickly-identify-ssh-private-key-file-formats

**Comment by m3nu** [comment]
Nice. So this confirms the first line. Then I'd just use that to verify the file and not show the key format (doesn't add much value). Most users will just keep it on *Default* anyways. Algo to populate the dropdown would be like this:

1. Grab files in `~/.ssh`
2. Ignore `config` and `known_hosts*`. And `*.pub`
3. For other files read first line.
4. If it matches, show the filename in dropdown.

Right?

**Comment by diivi** [comment]
Hi, I would like to work on this issue, please assign it to me, thanks!

**Comment by real-yfprojects** [comment]
Fixed by #1606
