### ISSUE TITLE
Buttons (Archives Tab) are not deactivated while creating a backup

### ISSUE THREAD

**Issue by RubenKelevra** [borgbase/vorta#1563]
### Description

The Buttons Refresh, Mount, Extract, Rename, Diff and Delete are not greyed out as unavailable when running a backup job. In addition, Compact button is also still active, which is already reported (see #1360).

![Screenshot from 2023-01-21 22-48-11](https://user-images.githubusercontent.com/614929/213888426-bf506937-eab7-4671-94db-c1665a60ffa0.png)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

ArchLinux latest

### Version of Vorta

0.8.9

### What did you install Vorta with?

Other

### Version of Borg

1.2.3

**Comment by m3nu** [comment]
Agree and can reproduce. Maybe we want to add some hooks/events that bundle such changes. Since we get more and more of them.

**Comment by real-yfprojects** [comment]
> I'd like to work on this as my first issue.

Great! If you need a hint where to start, feel free to ask!

**Comment by sunny775** [comment]
Okay, thanks @real-yfprojects!
Currently setting up my local development environment following this guide:  https://vorta.borgbase.com/contributing/#local-development-setup.
I'll ask for help if I encounter any blockers

**Comment by sunny775** [comment]
Hi @real-yfprojects.
I just made a PR for this issue, also resolves #1360.
Kindly review.
