### ISSUE TITLE
Flatpak: Update to 0.8.10?

### ISSUE THREAD

**Issue by CryptGoat** [borgbase/vorta#1569]
### Description

It's me again, is there an ETA for Vorta version 0.8.10 making it to FlatHub?

I will gladly open a pull request if that helps, not sure what to do though. @Hofer-Julian 

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux, Flatpak (Flathub)

### Version of Vorta

0.8.9

### What did you install Vorta with?

Homebrew

### Version of Borg

1.2.3

**Comment by m3nu** [comment]
If it's not automatic, we should add it the normal release process.

**Comment by Hofer-Julian** [comment]
> If it's not automatic, we should add it the normal release process.

Actually, it is to some degree automatic.
I didn't merge it because the automatic PR was bundled with the paramiko library: https://github.com/flathub/com.borgbase.Vorta/pull/97/files
Speaking of, can I update that one now or did we get rid of this dependency?

**Comment by real-yfprojects** [comment]
> Speaking of, can I update that one now or did we get rid of this dependency?

Not yet.

**Comment by Hofer-Julian** [comment]
@real-yfprojects: okay!

Fixed with: https://github.com/flathub/com.borgbase.Vorta/pull/98
