### ISSUE TITLE
'Prune' has a confusing Dutch translation

### ISSUE THREAD

**Issue by unilynx** [borgbase/vorta#1571]
The Prune button has been translated to "Vernietigen..." which translates back to "Destroy". 

I'm not sure what the best translation would be though. "Snoeien.."  would be most literal for Prune but would generally be associated with gardening. "Uitdunnen..." (thin out) has gathered the most votes here and appears to us to be the closest translation in spirit.

**Comment by real-yfprojects** [comment]
> "Uitdunnen..." (thin out) has gathered the most votes here and appears to us to be the closest translation in spirit.

_Uitdunnen_ also matches the German translation _ausdünnen_ vorta uses. Where has this gathered the most votes?

**Comment by unilynx** [comment]
> > "Uitdunnen..." (thin out) has gathered the most votes here and appears to us to be the closest translation in spirit.
> 
> _Uitdunnen_ also matches the German translation _ausdünnen_ vorta uses. Where has this gathered the most votes?

Oh just asked around at our (Dutch) office. Most users have their Mac set to English though.

**Comment by real-yfprojects** [comment]
Have you considered joining the vorta translation team for Dutch? We only have one translator at the moment. Then you can also update the translations discussed -- I don't trust myself to do that correctly. You can find more information on translating in [the docs](https://vorta.borgbase.com/contributing/translations/).
