### ISSUE TITLE
Can't create SSH key without existing remote repo

### ISSUE THREAD

**Issue by HDInfautre** [borgbase/vorta#1579]
Hello

I had confirmed the same problem as other members. But I don't see a resolution?

I confirm that I can't follow the tutorial ~10mn https://www.youtube.com/watch?v=asZX2YbTaNE
If I watch a video ~ 10' I can't select anything
Or https://norangeb.it/en/posts/2022/backup-with-borg-borgbase-and-vorta/
 
On the screenshot, it can select the creation of a new key
I see this also on other tutorials.

**Me, everything is greyed out, not selectable.**

I just started from scratch by installing vorta Flatpak 0.8.10 on ubuntu 22.10.
How do I do this?

![vorta](https://user-images.githubusercontent.com/6817936/216410163-a3aa7dd1-cd3b-4bcc-9f64-517ccdba6a48.png)

**Comment by real-yfprojects** [comment]
> I confirm that I can't follow the tutorial ~10mn https://www.youtube.com/watch?v=asZX2YbTaNE
If I watch a video ~ 10' I can't select anything

Now, you can create a new ssh key by clicking on the plus sign next to the ssh key combobox:
![grafik](https://user-images.githubusercontent.com/62463991/216780364-518e3f5d-00c3-4728-a9d4-5c6f855c9b01.png)

**Comment by HDInfautre** [comment]
Hi

> Now, you can create a new ssh key by clicking on the plus sign next to the ssh key combobox:
No unfortunately, clicking on the "+" has no effect
![Capture d’écran du 2023-02-04 18-45-50](https://user-images.githubusercontent.com/6817936/216781939-6c643d43-0385-4c27-95f1-a753d5ef65e3.png)

**Comment by real-yfprojects** [comment]
Usually another window should open up.

Is the button enabled, that is not grayed out? If it shows an animation it is definitely active.

**Comment by HDInfautre** [comment]
no animation, nothing happens when you click on it, the "+" button !

**Comment by tobast** [comment]
Hi, I can confirm the issue both on 0.8.10 and `master`. It seems to come from [these lines](https://github.com/borgbase/vorta/blob/b072496b3154a07671dae9ca95f835f5e9285c1d/src/vorta/views/repo_tab.py#L148-L150) : if no repository is currently selected, then the whole frame is disabled (grayed out). This means that, when launching Vorta for the first time, it is impossible to first create an SSH key, then create a remote repository.

**Comment by real-yfprojects** [comment]
> It seems to come from [these lines](https://github.com/borgbase/vorta/blob/b072496b3154a07671dae9ca95f835f5e9285c1d/src/vorta/views/repo_tab.py#L148-L150) : if no repository is currently selected, then the whole frame is disabled (grayed out).

That makes sense. Thank you for triaging. Do you want to open a PR?

**Comment by tobast** [comment]
I could, although I'm not certain of what's the best course. I could of course simply enable the whole frame in this case, then disable each element — but that looks hackish and messy. I expect it would be better to also allow creating an SSH key from within the repo creation dialog.

**Comment by m3nu** [comment]
Looks like a good starter issue. A chicken-egg problem.

**Comment by HDInfautre** [comment]
Great if it's possible. If it works, I'll take a borgbase subscription :-)

**Comment by real-yfprojects** [comment]
> I could of course simply enable the whole frame in this case, then disable each element — but that looks hackish and messy.

I wouldn't call it hackish or messy. There are only two widgets you would have to disable -- or you could iterate over the children of the frame.

> I expect it would be better to also allow creating an SSH key from within the repo creation dialog.

This would be a great enhancement of the UX.

**Comment by m3nu** [comment]
Or the *Quick Start Wizard* that was suggested in the past.

**Comment by HDInfautre** [comment]
Hello
 would like to thank the people who helped to solve this problem.
Indeed, to see the problem globally, in terms of the user path, seems important to me.
If I understand correctly, this will be pushed in a future release?
As for the timeframe, do you think it's in the order of weeks or months?
Thanks

**Comment by real-yfprojects** [comment]
> As for the timeframe, do you think it's in the order of weeks or months?

@m3nu will hopefully be able to tell you.

In the meantime you can install the latest version with

```
pip3 install https://github.com/borgbase/vorta/master.zip
```

**Comment by m3nu** [comment]
Usually we do a release when there were enough changes or an urgent bug.

**Comment by HDInfautre** [comment]
hello
Thank you for the reply.
The installation asks me something.
I'll wait a bit for the flatpak package (I prefer this kind of install to snap or appImage)

**Comment by real-yfprojects** [comment]
> The installation asks me something.

Not sure what you mean, but I did give you the wrong link. I updated it above.

**Comment by tobast** [comment]
> Or the _Quick Start Wizard_ that was suggested in the past.

@m3nu, you have mentioned this Quick Start Wizard. Are there any plans somewhere, or is it just something that has been talked about now and then before? I might be interested (though I cannot commit to it yet) in contributing this, if you believe it relevant.

**Comment by real-yfprojects** [comment]
> @m3nu, you have mentioned this Quick Start Wizard. Are there any plans somewhere, or is it just something that has been talked about now and then before? I might be interested (though I cannot commit to it yet) in contributing this, if you believe it relevant.

We'll add it to the GSoC ideas list. Though I didn't have any time for it yet.

**Comment by real-yfprojects** [comment]
Yeah, what do you have in mind? As mentioned earlier, we could add the button for creating a key to the ssh view too.

**Comment by m3nu** [comment]
Yes. Something like that. Maybe re-arrange the *Add Repo* dialog to make it a bit like a wizard. Ask some stuff, explain some background using your new ❓ icon, have a few steps. Creating and copying the SSH key could be one of them. For adding an existing repo it would just skip a step or two.

**Comment by real-yfprojects** [comment]
A startup wizard would be useful still though. You aggree?

**Comment by m3nu** [comment]
It would. So a separate modal window that opens if nothing is set up yet? 75% of it would be in an *Add Repo* wizard. Only missing to add source folders, right?

**Comment by HDInfautre** [comment]
Hello
Thank you for your interest in improving the user process. :-)
I can't help, as I'm not a developer and 'I have trouble explaining myself well in English
I'm following this conversation and as I said I'm still waiting a bit for a flatpak installation

**Comment by real-yfprojects** [comment]
> It would. So a separate modal window that opens if nothing is set up yet? 75% of it would be in an *Add Repo* wizard. Only missing to add source folders, right?

Yes, I guess so.
