### ISSUE TITLE
i18n: Translation Thread (ongoing)

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#159]
This thread is to coordinate the actual translation work. So far working on translations: 

- German: @ThomasWaldmann and @Hofer-Julian 
- Italian: @brokenpip3
- French: @dbrassard and @lapineige
- Dutch: Heimen Stoffels
- Czech: Pavel Borecki
- Polish: Tomasz Kontusz, @ktosiek
- Galician: Miguel Anxo Bouzada, [Transifex profile](https://www.transifex.com/user/profile/mbouzada/)

(let me know your Github and Transifex username to be added her)

Translations are organized on Transifex (TF) and then pulled into the source code, when 90+% complete. More details regarding translations are collected here: https://vorta.borgbase.com/contributing/translations/

Last, we should mention translators somewhere in the credits or the README. There will also be new strings added over time, as we're still adding features. So it's an ongoing commitment.

**Comment by ThomasWaldmann** [comment]
There could be also a more general "CONTRIBUTORS" file, where everybody who contributed *something* (to code, to docs, to i18n, ...) can get added.

**Comment by ThomasWaldmann** [comment]
BTW, i noticed that transifex or the qt tools seem to just kill strings that do not completely match any more (or did I miss something?). So having the `*.ts` files in git is useful to c&p longer translated phrases and then just edit them as needed.

**Comment by m3nu** [comment]
Sometimes these services have a "translation memory". Even if the string was removed, it may suggest the removed translation for a similar string in the future. But yes, good to look it up in Github sometimes.

**Comment by ThomasWaldmann** [comment]
You had an exact match in that case.

What I meant are fuzzy matches - did these work for you also?

**Comment by m3nu** [comment]
Yes. Then it just gives you a e.g. 90% match and ranks it by match.

**Comment by dbrassard** [comment]
For strings with punctuation marks, should the translated text keep those? 
eg. "Repository Path:"

Also, the section "Data Flow to/from Transifex" is unclear to me. 

Finally, is there resources highlighting the proper workflow for Transifex? I can go on the website and translate strings but I need to test them in the final application. I installed the qt5 dev tools but I will still need some pointers (consider that I'm not a software developer).

**Comment by m3nu** [comment]
> For strings with punctuation marks, should the translated text keep those?
> eg. "Repository Path:"

Yes. Please keep all the punctuation marks including `...`, `:` and `.`

**Comment by m3nu** [comment]
> I need to test them in the final application. I installed the qt5 dev tools but I will still need some pointers (consider that I'm not a software developer).

There are a few ways to do this. Easiest is maybe:

1. download .ts file from Transifex
2. put it in `src/vorta/i18n/ts`
3. run `make `make translations-to-qm`
4. run `vorta` command

This assumes you already have Vorta installled as dev setup (editable installation from git). If not and you need further steps, let me know.

**Comment by brokenpip3** [comment]
Italian translation started.. give me a few day

**Comment by m3nu** [comment]
How are translations coming along? I see about half completed on Transifex. Good progress!

I was planning the next release when languages are done. Would be a few bug fixes and languages mostly.

**Comment by brokenpip3** [comment]
> How are translations coming along? I see about half completed on Transifex. Good progress!
> 

I'm near to finish (85%) it but i must review some choice.
I work on this a little time most days. I hope to finish the translations very soon.

**Comment by m3nu** [comment]
Just saw that Italian is now complete. Will we release French at the same time?

**Comment by dbrassard** [comment]
It is getting along. I'll have time to do some more translation today. Some strings just give me a bit of trouble : 
"nyx2.local-2018-11-16T09:49:58 from November 16, 2018". 

I will also need to test out the translation as I just used the Transifex interface until now. 

Do we need to validate/revise each translation in the Transifex interface?

**Comment by m3nu** [comment]
> "nyx2.local-2018-11-16T09:49:58 from November 16, 2018".

Looks like a placeholder. Either copy it or ignore and I'll remove it later.

The way you did it is fine. Just do "Save Changes". We don't use the review feature for now.

**Comment by dbrassard** [comment]
I finished the french translation today but I will need to test it in the application to spot mistakes. 

> This assumes you already have Vorta installled as dev setup (editable installation from git). If not and you need further steps, let me know.

I know how to pull a repository from git and push modifications but that's about it. What are the commands to build and install Vorta in dev mode? Do I need to rebuild the application completely when I switch the language file? It seems as I can modify the language of an already compiled program with the `\. make translations-to-qm`comand. 

P.S. I'm running Ubuntu 16.04

**Comment by ThomasWaldmann** [comment]
@dbrassard have a look in the vorta docs.

**Comment by m3nu** [comment]
This is amazing. I can't judge the actual translation, but it's fascinating that it works as expected. Your translations are already in the master-branch, which should make testing easier. I can also make some screenshots for you if that's quicker. In theory the steps are like this:

1. Checkout latest `master` branch or clone repo. `$ git clone https://github.com/borgbase/vorta`
2. Go to `vorta` root folder and run `$ make translations-to-qm` to compile translations.
3. Install editable version of Vorta: `$ pip install -e .`
4. Run Vorta with `$ vorta`. If you want to use a different language, use `$ LANG=it vorta`

**Comment by m3nu** [comment]
Some screenshots of the first tab and system tray menu:

<img width="1035" alt="screen shot 2019-02-13 at 15 50 34" src="https://user-images.githubusercontent.com/3916435/52695778-55159600-2fa8-11e9-92ca-4f8534567e7f.png">
<img width="1069" alt="screen shot 2019-02-13 at 15 50 04" src="https://user-images.githubusercontent.com/3916435/52695780-55159600-2fa8-11e9-82a2-5e67d3b498c4.png">

**Comment by brokenpip3** [comment]
Yesterday night i tried my translation, i found one error and 2-3 string to replace for better "standard word pick".
Today i replace them asap

**Comment by brokenpip3** [comment]
Ok fixed (i hope). (y)

**Comment by m3nu** [comment]
The new translations are now live as version 0.6.10. Please make sure it all shows correctly.

I'll pull new translations from Transifex before every release from now on, in case something needs changing.

**Comment by m3nu** [comment]
I'll soon add the latest translations for the next release. There are a few new strings that cover the new "Pass extra arguments to Borg" and "Improve compression options" functionality.

I already added translations for German. Maybe you guys can update FR and IT. @brokenpip3 @dbrassard 🙌🙌

**Comment by brokenpip3** [comment]
> I'll soon add the latest translations for the next release. There are a few new strings that cover the new "Pass extra arguments to Borg" and "Improve compression options" functionality.
> 
> I already added translations for German. Maybe you guys can update FR and IT. @brokenpip3 @dbrassard raised_handsraised_hands
> 
> Untranslated strings: https://www.transifex.com/borgbase/vorta/translate/#fr/vorta/165834924?q=translated%3Ano

I'm very sorry, i translated the new string the day after your post this message but forgot to reply here.

**Comment by m3nu** [comment]
No problem. I pulled all available translations for the release. So if they were on Transifex they should be included.

**Comment by m3nu** [comment]
Pinging @lapineige for French translation. Please join the Transifex group first and see here for other details: https://vorta.borgbase.com/contributing/translations/

**Comment by lapineige** [comment]
Request to join sent :)

**Comment by m3nu** [comment]
> Request to join sent :)

Already confirmed. 👍

**Comment by lapineige** [comment]
Already (almost) completely translated :)

**Comment by m3nu** [comment]
Added new Dutch translation and updated French translation.

**Comment by ktosiek** [comment]
Hi! I'd like to start a Polish translation. I am a native speaker. My Transifex login is tomasz.kontusz.

**Comment by ktosiek** [comment]
And a quick question to other translators: are there other translated borg frontends? Borg itself seems to not support translations at the moment, and BorgWeb only has a few words in French.

**Comment by m3nu** [comment]
Thanks for the offer, @ktosiek. I've added Polish on Transifex with you as first translator.

Let me know when done and we'll pull the files into Git, so Qt will load them.

**Comment by m3nu** [comment]
Added you for Finnish, @teemue. 👍

**Comment by m3nu** [comment]
Added Galician. Thanks to [Miguel Anxo Bouzada](https://www.transifex.com/user/profile/mbouzada/)

**Comment by m3nu** [comment]
As suggested in #774 by @Hofer-Julian, we will announce a "string freeze" here about 1-2 weeks before the next release. To give all translators enough time to add new strings on Transifex.
