### ISSUE TITLE
FR: the Size column in the archives list is hard to read due to the mixed units. My proposed change (pull request incoming, need help if possible)

### ISSUE THREAD

**Issue by hariseldon78** [borgbase/vorta#1595]
I find hard to read the sizes of the archives at a glance when they are all mixed units: usually the longer numbers represent smaller sizes, making it difficult to find the biggest archives. So I made a basic algorithm to select a good unit that can adequately represent all sizes, that makes it much easier to read. Also I made the column align to the right, which further improves readability.

This is a screenshot of my proposed change
![image](https://user-images.githubusercontent.com/133625/219548261-26dbe769-e511-4861-8290-52f3f4eac366.png)

**Comment by hariseldon78** [comment]
sorry, the pull request is not ready yet, the tests are failing and I can't pinpoint the cause.. if somebody can help me here's my fork:

**Comment by real-yfprojects** [comment]
Just open a pull request, possibly as a draft. I can have a look then.

**Comment by hariseldon78** [comment]
> Just open a pull request, possibly as a draft. I can have a look then.

ok, here it is: https://github.com/borgbase/vorta/pull/1598
