### ISSUE TITLE
Package for Linux

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#16]
Is this being used?

https://docs.snapcraft.io/python-apps/6741

**Comment by JanSchnacki** [comment]
Snaps are slowly making their way into linux distributions. And also into the tooling for getting updates.

So yes, this would help.

**Comment by ThomasWaldmann** [comment]
one can usually count on linux packagers doing the packaging.

the only thing needed additonally is some pyinstaller-made fat binary for quick ad-hoc installation or if people want to try out newer stuff that their dist has to offer.

**Comment by m3nu** [comment]
There is already a user-provided package for Arch: https://aur.archlinux.org/packages/vorta/

If Linux packaging works well enough through existing channels and distros – even better.

**Comment by ThomasWaldmann** [comment]
Yeah, arch is usually very quick and updates frequently.
For other dists, stability is more important. To make them happy, focus on a core feature set and make that as bug free as possible rather than adding new features.
