### ISSUE TITLE
Code snippet in the contributing guidelines that is supposed to activate the virtual environment is wrong.

### ISSUE THREAD

**Issue by ratchek** [borgbase/vorta#1602]
#### Description
In the [contributing guidelines](https://vorta.borgbase.com/contributing/), the code snippet that activates the virtual environment for bash should be `source ./env/bin/activate` instead of `./env/bin/activate`

#### Environment
Ubuntu 22.04.1

**Comment by real-yfprojects** [comment]
Thanks!
