### ISSUE TITLE
Hangs or suspend on backup webdav network directory

### ISSUE THREAD

**Issue by GFRT-tech** [borgbase/vorta#1605]
The VORTA program does not respond when I add a directory from a network drive under webdav in the sources tab.
.
This directory is accessible and mounted from the Linux Pop!Os file manager.

I must finally kill process 

I have tried several times with the same results 
No trace in the log files

**Comment by m3nu** [comment]
Borg doesn't really support network storage. It will expect either a local repository or a remote one via SSH.
