### ISSUE TITLE
Migrate from `appdirs` to `platformdirs`.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1610]
[Appdirs](https://github.com/platformdirs/platformdirs) is deprecated and no longer maintained. Luckily there is a fork called [platformdirs](https://github.com/platformdirs/platformdirs).

In the process I suggest using the new `*_path` api returning `pathlib.Path` objects instead of str`.

**Comment by ganeshrevadi** [comment]
@real-yfprojects  can you please guide me through on what has to be done.

**Comment by m3nu** [comment]
Jumping in here. You'll want to find all occurrences that use the old library and replace them with the new one. Then make sure they still give the same result everywhere. Else users won't find their settings any more. 😬

Finally, update dependencies.

**Comment by ganeshrevadi** [comment]
Thanks for the help. I will let you know once PR is created

**Comment by ganeshrevadi** [comment]
PR is ready to be reviewed

**Comment by ganeshrevadi** [comment]
Can someone please review the PR!

**Comment by real-yfprojects** [comment]
Don't rush us. We are volunteers too.
