### ISSUE TITLE
FR: Enhance label of exclude pattern box e.g. by using new ToolTipButton

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1615]
The link providing details on the pattern syntax is not very obvious and can easily overlooked (See #1614). It additionally lacks details on vorta's implementation using `--exclude-from`.
![grafik](https://user-images.githubusercontent.com/62463991/221590962-4c12268e-1555-46ec-9196-7f41ca7b36ab.png)

**Comment by m3nu** [comment]
Or multiple lines of examples that cover different use cases.

At least until we can get the exclude GUI up.

**Comment by i1sm3ky** [comment]
Hi @m3nu and @real-yfprojects, I am Kunal, a potential contributor for GSOC 2023.
I've past experiences using pyQt and I feel I could help solving this issue.
It would be a great place for me to start contributing to vorta.
I'd like to work on this as my first issue.
Please assign it to me.

**Comment by real-yfprojects** [comment]
Great! Please sketch out your changes to the GUI before implementing them (literally by drawing it or creating a mockup).

**Comment by real-yfprojects** [comment]
Linked: https://github.com/borgbase/vorta/discussions/1614#discussioncomment-5203510

**Comment by i1sm3ky** [comment]
@real-yfprojects Would something like this work?
<img width="384" alt="IdeaScreenshot" src="https://user-images.githubusercontent.com/114871165/222948142-078b2e77-6c17-490c-865e-89d550f78435.png">

**Comment by real-yfprojects** [comment]
What would the tooltip say?

**Comment by i1sm3ky** [comment]
Maybe something like Borg pattern help

**Comment by real-yfprojects** [comment]
The complete `Borg pattern help` page seems a bit too long for a tooltip.

**Comment by i1sm3ky** [comment]
Then should we just keep it as `Help`?

**Comment by i1sm3ky** [comment]
> Then should we just keep it as `Help`?

@real-yfprojects would it be fine?

**Comment by real-yfprojects** [comment]
A tooltip that only containd the word Help. I don't know how that would help. :laugh:
Can tooltips contain clickable links?

**Comment by i1sm3ky** [comment]
> A tooltip that only containd the word Help. I don't know how that would help. :laugh:
> Can tooltips contain clickable links?

That i is a button so you can click it to open the help page.

**Comment by i1sm3ky** [comment]
> The user wont recognise this though since it is completly flat and doesnt have any animation.
> 

We could create a hover animation for that. The i would turn blue or something.

**Comment by diivi** [comment]
I feel like the link is pretty obvious and visible, the examples however could be improved 😕.

**Comment by real-yfprojects** [comment]
> I feel like the link is pretty obvious and visible, the examples however could be improved confused.

I aggree but the link could have a title attribute describing where it leads too. This issue has the following reason: Vorta lacks details on how it is using the patterns. That includes default pattern style, separation by line feeds, expanding `~` and passing it to borg via `--exclude-from`.

**Comment by real-yfprojects** [comment]
We could also add a new page to the [vorta docs](https://vorta.borgbase.com/usage/) explaining that and link it in the GUI.

**Comment by m3nu** [comment]
Someone is already working on a new exclude GUI. Is this issue still relevant after that?

**Comment by real-yfprojects** [comment]
I guess not. It's aimed at the time until then.

**Comment by diivi** [comment]
If it's a temporary solution, I believe a clickable `?` icon instead of the aforementioned `!` is more suitable.
Maybe with the tooltip - `Borg patterns documentation`

**Comment by i1sm3ky** [comment]
> If it's a temporary solution, I believe a clickable `?` icon instead of the aforementioned `!` is more suitable.
> 
> Maybe with the tooltip - `Borg patterns documentation`

Yeah I could do that, will work and get it done tomorrow.

**Comment by diivi** [comment]
That's great 😀, but I'd recommend you to wait for the maintainers to decide.

**Comment by real-yfprojects** [comment]
I am ok with that. I realised that this issue isn't a big deal since its temporary.

**Comment by real-yfprojects** [comment]
I guess we can also simply close this issue.

**Comment by i1sm3ky** [comment]
Should I work on the temporary fix? I could get it done relatively quickly within a couple of hours.

**Comment by i1sm3ky** [comment]
Should I work on the temporary fix or should I move to another issue?

**Comment by real-yfprojects** [comment]
> Should I work on the temporary fix or should I move to another issue?

I suggest you choose a different issue that is more useful.
