### ISSUE TITLE
Web interface?

### ISSUE THREAD

**Issue by airbillion** [borgbase/vorta#163]
Would it be possible to have a web interface for vorta in the future?

Vorta could then be easily packaged and deployed as a docker... which would make it possible to use on a headless server...

I have been using Borg for a few years now with cli scripts,  but this interface is great!!

**Comment by m3nu** [comment]
No. That's clearly out of scope. There are other people working on something [similar](https://cyborgbackup.readthedocs.io/en/latest/).

**Comment by Bogidon** [comment]
I haven't tried this yet but it should be possible to use something like [xpra](https://xpra.org/) to stream existing vorta app to a web client. It will not be as nice as a true web app, but it may be usable. See this writeup on hackaday: https://hackaday.com/2017/03/31/linux-fu-applications-on-the-web/
