### ISSUE TITLE
FR: Verbose display button (show what's going on)

### ISSUE THREAD

**Issue by Thatoo** [borgbase/vorta#1630]
#### The problem
Information given by vorta about what it is doing is only one line. We don't know about the progress

#### Requested Solution
Having a button to display a kind of terminal showing all what borg is doing (verbose) during a "create" command or a check or whatever.

#### Additional context
I started a repository check and it was saying "INFO: Starting repository check" for ages without more information than that. Impossible to know if borg has made any progress.

**Comment by real-yfprojects** [comment]
Part of this is already covered by #1497 and #1531. 



> showing all what borg is doing (verbose) during a "create" command or a check or whatever.

We already run almost all commands with `--info` which is the same as `--verbose`. And we run _create_, _compact_ and _check_ with `--progress`. So this issue can be closed imo.

**Comment by Thatoo** [comment]
Ok, I'll see all this progress when Debian bookworm will release then :-)
Good to know.
