### ISSUE TITLE
FR: Notifications for consistency check

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1632]
#### Requested Solution

 Vorta displays the notification "Backup successful for [repository]" only after the data consistency check has been completed.
#### Alternatives

As an alternative, I could imagine Vorta sending out different notifications. First for the backup and separate notifications for the consistency check.

**Comment by real-yfprojects** [comment]
> As an alternative, I could imagine Vorta sending out different notifications. First for the backup and separate notifications for the consistency check.

That would makes more sense.

> Can this break something in my backup file?

@ThomasWaldmann will have to tell you.

**Comment by ThomasWaldmann** [comment]
Defined "consistency check" in terms of borg commands.

**Comment by real-yfprojects** [comment]
I think `borg check` is meant.

**Comment by ThomasWaldmann** [comment]
Usually it should be able to roll back ok.

But you never should unplug a disk with a mounted fs - and you can not umount it while it is in use.
So cleanly dealing with this on the operator side avoids mistakes.

**Comment by sudwhiwdh** [comment]
> That would makes more sense.

@real-yfprojects So one notification at the beginning of the backup, one at the end of the backup, one at the beginning of the consistency check, and one after the consistency check is complete?

The smallest interval for the validation of the repository data is currently once a week. At that point it would be four notifications, instead of the usual two for a normal backup without validation.

I wonder if this will be too many notifications and if this change will improve the usability for non-technical users. 

> Usually it should be able to roll back ok.

@ThomasWaldmann What exactly does "roll back" mean in this context?

**Comment by ThomasWaldmann** [comment]
@sudwhiwdh borg usually tries to work transaction based. So if you start from a valid repo state, it starts a transaction. 

Then it works on that and either successfully completes it (finishes transaction) or gets interrupted somehow (crash, power failure, ...).

The next time it works with the repo, it will notice if there is an incomplete transaction and then roll back the repo files to that last valid state (== undo the not completed changes).

**Comment by real-yfprojects** [comment]
> At that point it would be four notifications,

We could reduce it to three notifications by dropping _backup completed_ when there is a consistency check. In case of an additional prune that would make 4 notifications. Or we move the _completed_ notification to the end of all three operations as you suggested.

**Comment by sudwhiwdh** [comment]
> In case of an additional prune that would make 4 notifications.

There is also a notification for pruning?
I have enabled automatic pruning after each backup. I have not received a notification for this yet.

**Comment by real-yfprojects** [comment]
No but we might want to add it because of your FR.

**Comment by diivi** [comment]
I can take this.
@sudwhiwdh what would you prefer out of these two:

>We could reduce it to three notifications by dropping backup completed when there is a consistency check. In case of an additional prune that would make 4 notifications. Or we move the completed notification to the end of all three operations as you suggested.

**Comment by sudwhiwdh** [comment]
@diivi

I can say what would be important to me as a user in relation to my use case.

For me, it would be important to know when the backup starts and from when it is safe to unmount my external USB storage device again because the backup is completely finished. This includes any validations and pruning.

Especially if there are several steps, I think it would be transparent to name them and be able to see them, but this can be looked up in the repository tab at any time.

I would also find it overwhelming to receive a lot of notifications for a backup, because I am informed individually for each step that begins and ends.
