### ISSUE TITLE
Create backup of db before migrations.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1641]
In case of migrations create a backup copy of the database beforehand. This can easily be achieved by copying the file to the same location but a different file name like `settings.db.bak`.

**Comment by DaffyTheDuck** [comment]
Hi! I've achieved this by the `os` command which creates the settings.db.bak on the same location, but is there any specific syntax which is required to make the backup file or the one which I used should work ?

**Comment by real-yfprojects** [comment]
> I've achieved this by the `os` command which creates the settings.db.bak on the same location

Which `os` command?

**Comment by DaffyTheDuck** [comment]
> > I've achieved this by the `os` command which creates the settings.db.bak on the same location
> 
> Which `os` command?

Ah, the `os.system` one, but I guess `shutil` will work great 🤔

**Comment by real-yfprojects** [comment]
Yes, shutil is way better.

**Comment by DaffyTheDuck** [comment]
Hi! @real-yfprojects As mentioned `before migration` here, adding the code for backup in main.py should also work ? since vorta always fetches the db when launched 🤔

**Comment by real-yfprojects** [comment]
This is an interesting use case too. But I would like to have a backup that can be used to downgrade vorta since migrations are irreversible (well not really but vorta cant do it).

**Comment by DaffyTheDuck** [comment]
> This is an interesting use case too. But I would like to have a backup that can be used to downgrade vorta since migrations are irreversible (well not really but vorta cant do it).

Hi! can you force vorta to run migrations? as you mentioned before, that it runs on its own.

**Comment by amit123chauhan** [comment]
Here, I can fix this issue please give me a chance I can fix this problem,

**Comment by real-yfprojects** [comment]
@amit123chauhan Go ahead! And open a PR with your fix afterwards.

**Comment by ambiguousphoton** [comment]
If this issue is still open please assign it to me, i would like to work on it.

**Comment by real-yfprojects** [comment]
> If this issue is still open please assign it to me, i would like to work on it.

Yes, it is. I am looking forward to your PR.

**Comment by AdwaitSalankar** [comment]
Hi @real-yfprojects, can I raise a PR for this? I have tested this using `shutil`.

**Comment by real-yfprojects** [comment]
Yes @AdwaitSalankar that would be great!
