### ISSUE TITLE
Vorta not working (ImportError: Bundle could not be loaded)

### ISSUE THREAD

**Issue by hda42** [borgbase/vorta#1644]
### Description

I use a Macbook Air M1 16GB. 
First I tried the Homebrew-version of Vorta but this version is an Intel version and not an universal build or for Apple Silicon (I had no Issues with that version). Because I use an Apple Silicon Chip I wanted an Arm version so I build this project myself. I used the build-macos.yml and used my machine as a runner(over github action but i also tried to run those commands on my machine not using github action but the result was the same). Because I don't have an Apple Developer Account I skipped the signing step. my build-macos.yml:
![yml](https://user-images.githubusercontent.com/118397088/224574231-cb4378ac-4d18-46a3-88fa-724cf099c030.png)

Thats the only thing I changed because of that signing problem (and the part to use my machine as the arm Runner).
Everything works well. I download the zip. Extract it, open the dmg and execute the Vorta.app.
The first Thing I see is the Question to get full disk acess. behind that I see that pop up:

![vorta](https://user-images.githubusercontent.com/118397088/224573578-2762a98d-8a46-473e-b58b-0cc6f013e0ff.png)

The real app is also there. If I press `ok` or close the pop up window Vorta also closes itself.

Greetings from Germany

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

MacOs Montery 12.6.3

### Version of Vorta

v0.8.10

### What did you install Vorta with?

Binary

### Version of Borg

1.2.3

**Comment by unisimplex** [comment]
i have using vorta version 0.8.10 on my mac mini late(2012) modle with monteray os version 12.6.3 . I used the standard procedure to install , downloaded the dmg file from there website and installed it , also to mention i am using on a intel based chipset 2.5gh intel i5. It is working fine for my system .

**Comment by real-yfprojects** [comment]
Yeah, this probably relates to him building the bundle himself without the signing procedure. @m3nu will hopefully be able to help.

**Comment by m3nu** [comment]
I regularly build bundles without signing. Just `make dist/Vorta.app`
