### ISSUE TITLE
 Prune not working #1645 

### ISSUE THREAD

**Issue by RobDean69** [borgbase/vorta#1646]
I opened this issue and it was closed by @m3nu as "Already resolved in https://github.com/borgbase/vorta/pull/1565"

This might very well be the case but it still doesn't work for me. Has this been merged in 0.8.10? If not, any idea when it will be released? (It seems to break very basic functionality). If it has been merged, it still isn't working.

To my mind, closing issues by linking to another bug report where it's not clear if the fix has been released is pretty poor form.

**Comment by m3nu** [comment]
Me again. 😀

You can already use the fix in the current `master` branch. It will be part of the next release. To find out you could just check the list of commits to find out when the last version was tagged.

**Comment by m3nu** [comment]
You can let us know if the fix in the `master` branch works for you. Then we can get it released faster. 🙌

**Comment by RobDean69** [comment]
Thanks @m3nu. 

I'm just using the latest version on flathub which I saw was updated the other day and I assumed (wrongly as it seems) that this fix was included. 
I don't program so I know very little about github other than how to search and log bug reports. I don't really understand how the branching works nor do I know how to use the master branch.

**Comment by m3nu** [comment]
We have more details on how to use the development branch in the [docs](https://vorta.borgbase.com/contributing/#testing-the-current-development-version). This helps making sure bugs are fixed before making a release.

Next release should be done in 2-3 weeks maybe. When the larger pending PRs are merged.
