### ISSUE TITLE
FR: Sources Tab -> The settings for sorting by Path, Size, File Count should be retained when Vorta is restarted

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#1647]
#### The problem

Currently, I have to set this again after each restart of Vorta.

**Comment by jetchirag** [comment]
@real-yfprojects I'd like to try this. Can you assign it to me?

**Comment by real-yfprojects** [comment]
You can have a look at #1621 for a reference.

**Comment by jetchirag** [comment]
@real-yfprojects Thanks for the reference. I've opened PR #1649 for review.

**Comment by sudwhiwdh** [comment]
Should these settings be part of a profile export?
