### ISSUE TITLE
Negative difference of sizes in archive gives ValueError: math domain error

### ISSUE THREAD

**Issue by jetchirag** [borgbase/vorta#1650]
### Description

Steps to reproduce:
1. I created a source with a single file and started a backup
2. Added a file and created another archive
3. Remove the previous file and started last backup

When I see the diff of first two backups (in which I added a file), it works fine but when I try to view the diff for last two archives, it gives this error:

```
Traceback (most recent call last):
  File "/Users/xxx/Projects/vorta/vorta/src/vorta/views/diff_result.py", line 776, in data
    return pretty_bytes(item.data.changed_size)
  File "/Users/xxx/Projects/vorta/vorta/src/vorta/utils.py", line 290, in pretty_bytes
    n = find_best_unit_for_size(size, metric=metric, precision=precision)
  File "/Users/xxx/Projects/vorta/vorta/src/vorta/utils.py", line 269, in find_best_unit_for_size
    n = math.floor(math.log(size * 10**precision, power))
ValueError: math domain error
```

I traced the error down to https://github.com/borgbase/vorta/blob/6bc532187b1737b5947a59c76a7fe9ed618dff63/src/vorta/views/diff_result.py#L775-L779

value of `item.data.changed_size` and `item.data.size` is in negative because `log` can't take negative value

```
n = math.floor(math.log(size * 10**precision, power))
```

Suggested fix:
```
n = math.floor(math.log(abs(size) * 10**precision, power))
```

It would still calculate the best unit and display +/- as per size. I'm not sure if I'm missing something. If this is a bug, please assign this to me so I can open a PR.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

macOS 12.2.1

### Version of Vorta

0.8.10 / master branch

### What did you install Vorta with?

Pip

### Logs

```pytb
Traceback (most recent call last):
  File "/Users/xxx/Projects/vorta/vorta/src/vorta/views/diff_result.py", line 776, in data
    return pretty_bytes(item.data.changed_size)
  File "/Users/xxx/Projects/vorta/vorta/src/vorta/utils.py", line 290, in pretty_bytes
    n = find_best_unit_for_size(size, metric=metric, precision=precision)
  File "/Users/xxx/Projects/vorta/vorta/src/vorta/utils.py", line 269, in find_best_unit_for_size
    n = math.floor(math.log(size * 10**precision, power))
ValueError: math domain error
```

**Comment by jetchirag** [comment]
@m3nu @real-yfprojects Can you assign it to me if you have verified the bug?

**Comment by jetchirag** [comment]
I've opened a PR with my preferred fix.

**Comment by real-yfprojects** [comment]
Thanks. Btw we get a notification for the PR too.
