### ISSUE TITLE
SSH Key Dropdown not showing all SSH keys

### ISSUE THREAD

**Issue by drohm** [borgbase/vorta#167]
I'm trying to create a new backup and while on the Repository tab, for the SSH Key dropdown, it's only showing 2 of my SSH keys out of the 12 keys in my ~/.ssh folder.  All of the keys are RSA 4096.  I checked the ~/.cache/Vorta/log/vorta.log file for any errors, none were there.

1. Go to the Repository tab.
2. Click on the dropdown menu for SSH Key and only 2 of the 12 SSH keys are displaying.

 - OS: Ubuntu Budgie 18.10

**Comment by drohm** [comment]
Digging into this a bit, I noticed that the private key I created to use is in encrypted format:

`
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,E2D7DD3282325BABCF2CC4BC45F6847B
`

I decrypted it using `openssl rsa -in <encrypted_keyfile> -out <decrypted_keyfile>` and that seemed to do the trick.  This begs the question, does vorta not support keys generated with a passphrase?

**Comment by m3nu** [comment]
Yepp. Encrypted keys aren't supported for now because there are better, os-specific ways to deal with them. Like ssh-agent on Linux and keychain+ssh-agent on macOS.

If you have encrypted keys, just set up this os-specific unlocking mechanism and set Vorta to 'auto mode'.

I don't think we should deal with ssh key passwords in Vorta, but it could show existing unlocked keys for selection.

The main purpose of selecting non-standard keys in Vorta is to avoid including them in `.ssh/config`.

**Comment by drohm** [comment]
It's not a problem, I just wanted to know what was supported or if it was and possibly a bug.  I just went ahead and created a new ssh key without a passphrase.  Thanks.

**Comment by themightyoarfish** [comment]
So what do I do when my ssh key is encrypted? I'm assuming this is the default for most people. I couldn't find anything in the Docs regarding this very common setup.

**Comment by themightyoarfish** [comment]
I think it would be helpful to point to some resources, this must be a common issue.

**Comment by m3nu** [comment]
You unlock it, add it to `ssh-agent` and keep the setting in Vorta on *Default*.

**Comment by themightyoarfish** [comment]
In addition to
```
eval $(ssh-agent -s)
ssh-add <path-to-private-key>
… enter password
[open Vorta, configure repository]
```
I had to also pass `-i ~/.ssh/<key>` to make it use the desired key specifically. I don't know why it didn't work automatically, considering it is the only key on this machine.

**Comment by m3nu** [comment]
Are you using a custom name for the key? That may be an issue. So does it work after adding it?

**Comment by themightyoarfish** [comment]
It's just `id_rsa`. But yes, it does work when I specify the key in the extra options in the SSH command.

**Comment by m3nu** [comment]
The dropdown will soon show encrypted keys too, as we plan to stop verifying them. See #1559.
