### ISSUE TITLE
v0.8.11 Release

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1678]
To discuss this release.

**Comment by real-yfprojects** [comment]
I'd like to see #1625 in this release. And any other PRs I requested your review for depending on the time you have.

**Comment by m3nu** [comment]
I totally missed some open PRs and only found them while reviewing GSoC applicants. Will go over the ones that are ready again tomorrow. Already did 2 today.

**Comment by m3nu** [comment]
Everything that's finished should be merged. Will give it a few days for testing the `master` branch.

**Comment by m3nu** [comment]
https://github.com/borgbase/vorta/releases/tag/v0.8.11
