### ISSUE TITLE
Crash when cancelling "add new profile"

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#168]
**Describe the bug**
The window which opens after "add new profile" is clicked, crashes the whole program when you close it.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click "Add new profile"
2. Close window

**Desktop (please complete the following information):**
 - OS: Fedora 29

**Comment by m3nu** [comment]
Yepp. When you "Cancel" adding the profile. Probably a small issue when processing the result.

Assigning to myself and will fix in the next update.

Thanks for reporting!

**Comment by m3nu** [comment]
PS: If you want to work on this @Hofer-Julian, be my guest. It's likely a very small issue. Let me know here in the next 9 hours. Else, I'll tackle it tomorrow morning.

**Comment by Hofer-Julian** [comment]
Yeah, I'll try it tomorrow. If I can't figure it out, I'll write it here :)

**Comment by m3nu** [comment]
Fixed via #170

(Another pro-tip: If you write "... Fixes #1xx" in your commit message, it will automatically close the issue after merging it.)
