### ISSUE TITLE
platformdirs version requirement

### ISSUE THREAD

**Issue by jonathanspw** [borgbase/vorta#1690]
As a followup to https://github.com/borgbase/vorta/issues/1610 which has broken builds on Fedora 36, 37, and EPEL9 - is 2.6.0+ actually what's required?

I've done builds with 2.3.0 (the version of platformdirs in EPEL9) and things seem fine to me.  Perhaps we can loosen the requirement to 2.3.0+ instead of 2.6.0+ to fix Fedora and EPEL builds.

Currently I am having to change this in the sources before doing the RPM builds.

**Comment by real-yfprojects** [comment]
`2.6.0` introduced a breaking change to `user_log_dir` (see platformdirs/platformdirs#108) which Vorta uses. Since it isn't critical when the log directory changes between updates I don't see a problem with packaging `2.3.0`. However I still think it makes sense to require `2.6.0+` by default. How do you package `borg` for Fedora? They have the same requirements.

**Comment by jonathanspw** [comment]
I don't package borgbackup in Fedora, only Vorta...however I started looking at it to try and answer this question and I'm a bit baffled right now.  `setup.py` from borg very clearly calls for platformdirs 2.6+ yet on f36/f37 borgbackup builds and runs just fine - with no apparent dependency on platformdirs in the packaged product.

What's more odd is that nothing appears to drop said dependency and it should be getting pulled in.

I'm going to keep digging on this.

**Comment by real-yfprojects** [comment]
> which contains no references to platformdirs

I dug into this. Borg uses *platformdirs* from v2 on which is currently in beta.

**Comment by real-yfprojects** [comment]
> Currently I am having to change this in the sources before doing the RPM builds.

I am not familiar with you release process but I wonder whether you are able to add a script to your ci that does that?

**Comment by jonathanspw** [comment]
Yeah from the sounds of things it's better to be dealing with this on the Fedora/EPEL side and keep things as-is in Vorta.

Since this is only a very minor change it's not a big deal to maintain it while needed in Fedora/EPEL.

https://src.fedoraproject.org/rpms/vorta/blob/rawhide/f/vorta.spec#_29

**Comment by real-yfprojects** [comment]
Can we close this then?

**Comment by jonathanspw** [comment]
Yep!
