### ISSUE TITLE
After upgrade to 0.8.12 Vorta archives now show GB sizes as KBs

### ISSUE THREAD

**Issue by Jakethethird** [borgbase/vorta#1692]
#### Description

Just upgraded to 0.8.12 and now the pruning works fine. But I notice the archive size units have now changed - they are now all in KB where as before they were in GB when large. I backup VMs and GBs would normally be the preferred unit.

Edit: I get both MB and KB in different profiles, but not GB. An example is of a large VM-derived archive being 5194624.3 KB whereas previously it was shown as approx 5 GB

#### Environment

- OS: Ubuntu 22.04
- Vorta version: 0.8.12
- Installed from: Flatpak
- Borg version: 1.2.4

#### Logs

```
*paste logs here*
```

**Comment by Jakethethird** [comment]
I read the page you sent - but it does not seem to be selecting the user friendly units. KB are shown, MB are shown, but GB are not - they are converted in to KB. 

See these two screenshots: 

![20230412-14-06-22](https://user-images.githubusercontent.com/28954472/231451979-cb92bcec-fb3d-4c4d-bb76-980a7e4e4871.png)

![20230412-14-05-47](https://user-images.githubusercontent.com/28954472/231452017-1fa7f57d-4422-41d6-9c24-507d958d1b3a.png)

**Comment by real-yfprojects** [comment]
The idea was to make the shown sizes easily comparable while not showing any sizes of zero.

**Comment by Jakethethird** [comment]
OK, thanks for the feedback. Keep up the great work!

**Comment by TimTheSettler** [comment]
I can see the motivation behind this change but something like this should be configurable.  As you can see in the screenshot below, this makes things even worse for me.

![image](https://user-images.githubusercontent.com/132863260/236718443-cbfd10b5-562e-4cf7-8a5c-1455963fcb89.png)

**Comment by real-yfprojects** [comment]
> I can see the motivation behind this change but something like this should be configurable. 

Tracked in #1713
