### ISSUE TITLE
hostname placeholder expansion

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#1696]
Vorta: misc 0.8.x versions and also 0.9.0 (on macOS M1)

In Vorta `{hostname}-...` is configured for creating the archive names and `{hostname}-` as prefix for pruning.

As a borg placeholder, `{hostname}` is documented to expand to the short hostname (not the fqdn).

But I see archive names in the repo with my mac hostname with misc. domains appended (sometimes `.local`, sometimes `.fritz.box`), so it seems to expand to the fqdn.

Especially since this does not always expand to the same fqdn, it creates a bit of a mess, especially considering `prune`.

**Comment by ThomasWaldmann** [comment]
From the vorta console output:
```
2023-04-17 13:22:33,203 - vorta.borg.borg_job - INFO - Running command /opt/homebrew/bin/borg create 
  --list --progress --info --log-json --json --filter=AM -C lz4 --exclude-from /var/folders/... 
  --exclude-if-present .nobackup borg@borgbackup:myrepo::mba2020.local-2023-04-17-132233 /Users/tw
```

Unexpected:
- does Vorta have its own placeholder expansion, using different placeholder definitions than borg?
- why doesn't vorta just give the placeholder "as is" to borg?

**Comment by ThomasWaldmann** [comment]
OK, looks like vorta does its own placeholder expansion, in a different way than borg:

https://github.com/borgbase/vorta/blob/v0.9.0/src/vorta/utils.py#L379

https://docs.python.org/3/library/platform.html#platform.node looks like that function can return short hostname or fqdn.

**Comment by ThomasWaldmann** [comment]
Side note: I am currently pruning some hundreds of archives, because of that hostname expansion and prefix confusion prune didn't really work as it should here.

**Comment by m3nu** [comment]
Yes, we do our own expansion to e.g. preview the archive name in the UI.

I guess best to copy the code Borg uses to keep it consistent.

**Comment by m3nu** [comment]
So would change to this:

```
hostname = socket.gethostname()
hostname = hostname.split(".")[0]
```

From https://github.com/borgbackup/borg/blob/02580c09ea9059dd42eb1a545abba8aa61ca5a73/src/borg/platform/base.py#L288

**Comment by ThomasWaldmann** [comment]
And maybe also the `fqdn` for people wanting to expand to that.

**Comment by m3nu** [comment]
PR @ThomasWaldmann https://github.com/borgbase/vorta/pull/1697

OK to reuse your fqdn code? Else we'll be inconsistent with Borg again.

**Comment by ThomasWaldmann** [comment]
OK, reviewed. Sure ok to reuse it.
