### ISSUE TITLE
Dark mode doesn't activate when installed with pipx

### ISSUE THREAD

**Issue by lamyergeier** [borgbase/vorta#1706]
### Description

Dark mode doesn't activate when installed with pipx

### Reproduction

- [X] I tried to reproduce the issue.
- [x] I was able to reproduce the issue.

### OS

Ubuntu 23.04

### Version of Vorta

0.8.12

### What did you install Vorta with?

			pipx install "borgbackup==2.0.0b4"
			pipx install vorta

### Version of Borg

2.0.0b4

**Comment by m3nu** [comment]
You can install PyQt system packages and then set the env var to inherit them with `--system-site-packages`. (not tested though)

**Comment by zaphod80013** [comment]
I'm seeing the same issue on pop-os (22.04 Gnome 42.5) I installed as root using

`python -m pip install vorta`

it istalled to /usr/local/lib/python3.10/dist-packages so this should be running with system packages, no venv involved.  Does that not refute the assertion made by [real-yfprojects](https://github.com/real-yfprojects) ?

**Comment by real-yfprojects** [comment]
> I installed as root using

Do you have the same issue when installing without root?

**Comment by lamyergeier** [comment]
> pipx install vorta

This installs without root and I am facing the same issue

Refer: [[pypa/pipx: Install and Run Python Applications in Isolated Environments](https://github.com/pypa/pipx)](https://github.com/pypa/pipx)

**Comment by lamyergeier** [comment]
@real-yfprojects  @m3nu 

This issue is closed without even being solved, please disable auto closing of issues.

**Comment by real-yfprojects** [comment]
As I explained in https://github.com/borgbase/vorta/issues/1706#issuecomment-1544502728, I don't think Vorta can fix this.

**Comment by lamyergeier** [comment]
@real-yfprojects I could achieve some success as follows with dark mode with pipx as follows but is not looking proper (text is not readable, certain boxes remain white), please have a look:

```bash
$ pwd
/home/lamy/.local/pipx/venvs/vorta/lib/python3.12/site-packages/PyQt6/Qt6/plugins
```

```bash
$ ln -s /usr/lib64/qt6/plugins/styles .
$ ls -la styles/
total 272K
drwxr-xr-x.  2 root 4.0K Sep  4 02:00 ./
drwxr-xr-x. 38 root 4.0K Oct  2 22:32 ../
-rwxr-xr-x.  1 root 264K Jan 22  2024 adwaita.so*
```

```bash
QT_STYLE_OVERRIDE=Adwaita-Dark vorta
```

![image](https://github.com/user-attachments/assets/8d56e7a4-33ac-48ec-a303-9173a149e3c1)

![image](https://github.com/user-attachments/assets/29f145a2-3ff6-4e02-a866-77ca01fb23f1)

![image](https://github.com/user-attachments/assets/bebe60f7-41ff-425f-a3cd-1f5bb881f447)

**Comment by real-yfprojects** [comment]
@lamyergeier I am afraid I cannot help you as I know to little about the way linking native libraries works in PyQt and Cython in general. Though I do hope you somehow get it to work.

**Comment by m3nu** [comment]
Sometimes this depends on the Qt install method used. Or which packages are installed specifically.

**Comment by lamyergeier** [comment]
@m3nu Is it possible to include the appropriate binary file adwaita.so, with pipx installation so that the dark mode works properly?

I am using Fedora 40 with Gnome 46.

**Comment by m3nu** [comment]
I don't know enough about Linux desktops to make this change or decision, I'm afraid. Generally Qt distro packages will integrate and work better than pip-installed ones.

**Comment by lamyergeier** [comment]
> I don't know enough about Linux desktops to make this change or decision, I'm afraid. Generally Qt distro packages will integrate and work better than pip-installed ones.

May be some who deals with Linux on vorta can reply.

The issue is that flatpak does not support backing up of root user, installation from package manager (e.g. Fedora) are outdated and updated at all in the life time of the version of the operating system, pipx faces issues with dark theme. So there is no single method of installation which solves all these issues on Linux!

**Comment by lamyergeier** [comment]
@m3nu  Please reopen the issue.

**Comment by m3nu** [comment]
What can we change in the context of this project to resolve your issue?

**Comment by lamyergeier** [comment]
> What can we change in the context of this project to resolve your issue?

I meant that the issue is valid as I showed above with screenshot that its possible to have dark mode, and the issue is not resolved, so it should not be closed IMHO.
