### ISSUE TITLE
bad logfile names

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#1707]
Vorta creates log file names like:
- vorta.log
- vorta.log.2023-04-05
- vorta.log.2023-05-06

The "rotated" file names are bad: if you click on "logs" in the vorta UI, it will show you a file selector box and after selecting a log file, it will ask you to choose a program to view that log.

It will ask again and again because it considers `.log` (ok) and `.2023-04-05` (bad) as filename extensions ("file types").

So, the log file names should have the same extension, like e.g.: `vorta.2023-04-05.log`

## Solution

1. Subclass `logging.TimedRotatingFileHandler` inside [log.py](https://github.com/borgbase/vorta/blob/master/src/vorta/log.py)
2. Append `.log` to the suffix in the `__init__` of the created subclass
3. Use the subclass in [init_logger](https://github.com/borgbase/vorta/blob/4d65912d65e18e71462a03e903f6eb71c0edf9bd/src/vorta/log.py#L16)
4. Write unittests for the new subclass in a new test file.

**Comment by bigtedde** [comment]
Hey Thomas, I've got some free time over the next few days and would like to work on this issue. You've outlined the issue and solution really well, and I believe this would give me experience with areas of the code that would be useful for my other GSoC projects. Would you be willing to assign this issue to me?

**Comment by ThomasWaldmann** [comment]
@bigtedde you have it! thanks for working on it.
