### ISSUE TITLE
DEV: Run pre-commit checks in ci.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1709]
#### The problem

We already use pre-commit hooks for QA. However when a contributor doesn't install pre-commit, he can introduce unchecked and unformatted changes that will be require further action for contributors using pre-commit down the line. Currently there is no Github Action enforcing the pre-commit hooks for pull requests. There I would like to add a ci check that runs pre-commit.

#### Possible Solutions

There are multiple options here:

1. Add `pre-commit` command to the `lint` phony in the Makefile
2. Use the *pre-commit.ci* **bot** that can automatically add a commit with the autofixes from the pre-commit hooks and can run `pre-commit autoupdate` regularly.
3. Use the pre-commit.ci lite **action** that can autofix PRs too.

*M3nu* has already said that he dislikes bot commits: https://github.com/borgbase/vorta/pull/1394#issuecomment-1216271383
So option 1 is probably the best. However one could also implement a custom action that commits pre-commit fixes under the name of the previous committer. This should be quite straight-forward iirc.

**Comment by m3nu** [comment]
Yes, 1) is good. Helping humans to push good code and showing them, if they don't. 😀
