### ISSUE TITLE
FR: Add -m flag to open vorta minimized

### ISSUE THREAD

**Issue by vihu** [borgbase/vorta#1717]
#### The problem

It would be nice to add a `-m` flag so that vorta can be opened in a minimized state. For example:

`flatpak run com.borgbase.Vorta -m`

#### Requested Solution

Support `flatpak run com.borgbase.Vorta -m` command such that Vorta can start with its main window minimized.

#### Alternatives

NA

#### Additional context

For reference, syncthing-gtk implements the `-m` flag.

**Comment by real-yfprojects** [comment]
The setting for starting Vorta minimized is not an option for you?

**Comment by vihu** [comment]
> The setting for starting Vorta minimized is not an option for you?

Ah silly me, that works actually! Thanks a lot.
