### ISSUE TITLE
pip3 doesn't install condor

### ISSUE THREAD

**Issue by dragon2611** [borgbase/vorta#172]
**Describe the bug**
On a Linux Mint 19.1 system the pip3 install vorta command doesn't install condor
This causes local repo creation to fail.

Running in the foreground causes this message

> 
> Gtk-Message: 18:30:19.638: GtkDialog mapped without a transient parent. This is discouraged.
> 2019-01-30 18:30:29,716 - vorta.borg.borg_thread - INFO - Running command borg init --info --log-json --encryption=repokey-blake2 /mnt/hdd2/blah/blah/dtopbackup
> 2019-01-30 18:30:29,954 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
> 2019-01-30 18:30:29,955 - vorta.borg.borg_thread - WARNING - File "/usr/bin/borg", line 11, in <module>
> 2019-01-30 18:30:29,955 - vorta.borg.borg_thread - WARNING - load_entry_point('borgbackup==1.1.5', 'console_scripts', 'borg')()
> 2019-01-30 18:30:29,956 - vorta.borg.borg_thread - WARNING - File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
> 2019-01-30 18:30:29,956 - vorta.borg.borg_thread - WARNING - return get_distribution(dist).load_entry_point(group, name)
> 2019-01-30 18:30:29,956 - vorta.borg.borg_thread - WARNING - File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
> 2019-01-30 18:30:29,956 - vorta.borg.borg_thread - WARNING - return ep.load()
> 2019-01-30 18:30:29,957 - vorta.borg.borg_thread - WARNING - File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
> 2019-01-30 18:30:29,957 - vorta.borg.borg_thread - WARNING - return self.resolve()
> 2019-01-30 18:30:29,957 - vorta.borg.borg_thread - WARNING - File "/home/username/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
> 2019-01-30 18:30:29,957 - vorta.borg.borg_thread - WARNING - module = __import__(self.module_name, fromlist=['__name__'], level=0)
> 2019-01-30 18:30:29,957 - vorta.borg.borg_thread - WARNING - File "/home/username/.local/lib/python3.6/site-packages/borg/__init__.py", line 9, in <module>
> 2019-01-30 18:30:29,958 - vorta.borg.borg_thread - WARNING - import condor
> 2019-01-30 18:30:29,958 - vorta.borg.borg_thread - WARNING - ModuleNotFoundError: No module named 'condor'

**Desktop (please complete the following information):**
Xfce on mint 19.1

/Vorta`

**Comment by dragon2611** [comment]
Apologies this looks like an issue with the python setup, I removed the apt installed version of borg and installed borgbackup from pip3 (You have to install libacl1-dev) as the version of borg from pip will fail to build on Mint.

I'll leave the issue here incase someone else runs into it.

**Comment by m3nu** [comment]
No worries. Never heard of "condor" before and was just wondering. :-)

**Comment by dragon2611** [comment]
Think borg was using it for something
