### ISSUE TITLE
Remove GSOC banner from README.

### ISSUE THREAD

**Issue by real-yfprojects** [borgbase/vorta#1738]
This is no longer up-to-date:

```
This project is part of the [Google Summer of Code](https://summerofcode.withgoogle.com/) 2023 program. Apply or learn more [here](https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2023-Ideas)!
```

I suggest either removing it entirely or adding a note somewhere that we currently have GSOC students around.

**Comment by punyamsingh** [comment]
i have made changes to the readme.md.
kindly review.

**Comment by punyamsingh** [comment]
uh, I already made a pull request for this,
please check and tell me if changes are needed,
also please assign me this issue before merging.
