### ISSUE TITLE
Several issues when installing for the first time

### ISSUE THREAD

**Issue by chriscn** [borgbase/vorta#1758]
Hi, I tried to use this program and it took me several times before I was able to succeed. I just wanted to lay out these steps as I think that they should be addressed.

I installed using `brew install --cask votra` and ran into the following issues.

1. `--remote-path=borg1` although this is a [rsync.net](rsync.net) issue it could be worth adding to the docs
2. Permission denied to `.config/borg`; I manually ran `sudo chown -R $USER:staff ...` to edit this as it was created with root
3. Permission denied for `.cache/borg` same as above

The permission denied was weird to figure out.

**Comment by m3nu** [comment]
Vorta won't ever run with root permissions. We even discourage such uses. So the permission issues may come from elsewhere.

**Comment by chriscn** [comment]
I would have thought so, I did give Votra full disk permission but never asked it to install as root and just used the standard brew.

**Comment by real-yfprojects** [comment]
The permission denied error might be caused by you running borg with root earlier, I suppose. To better understand what Vorta could do about that, how did Vorta notify you about the error? (If you still remember)
