### ISSUE TITLE
Error when making a difference between two very different archives

### ISSUE THREAD

**Issue by Rouzic6666** [borgbase/vorta#1759]
Bonjour, Hello
OS linux mint 21.2 cinnamon 5.8.4
version Vorta 0.8.3
Version Borg 1.2.0
CPU Intel© Core™ i7-4790T
RAM 8Go

The error appears when I ask for the difference between 2 archives with a lot of changes on the disk.
No error on archives with fewer changes.

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/archive_tab.py", line 521, in list_diff_result
    window = DiffResult(result['data'], archive_newer, archive_older, result['params']['json_lines'])
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 32, in __init__
    files_with_attributes, nested_file_list = parse_diff_json_lines(lines) \
  File "/usr/lib/python3/dist-packages/vorta/views/diff_result.py", line 113, in parse_diff_json_lines
    assert change_type  # either no changes, or unrecognized change(s)
AssertionError

Regards,
JL

**Comment by m3nu** [comment]
Your Vorta and Borg versoins are both pretty old. Does the error still happen with recent version?

**Comment by Rouzic6666** [comment]
You're right, I've just tested with Vorta 0.8.12 and borg 1.2.4 and it doesn't crash! It takes a while to tell the difference, but it does! )
Thank you very much.
