### ISSUE TITLE
add a setting to start vorta minimized to tray

### ISSUE THREAD

**Issue by sysdbugfactory** [borgbase/vorta#1763]
#### The problem

The way to choose the settings to start vorta minimized to tray is confusing. 

#### Requested Solution

A clear wording such as "start vorta minimized as an icon to tray" would be bettre IMHO

#### Additional context

***

## Steps to solve this issue

1. Open https://github.com/borgbase/vorta/tree/master/src/vorta/store/settings.py
2. Edit the label and the tooltip of the setting as needed: https://github.com/borgbase/vorta/blob/b58ffb6aed0254c565788e912a7cbc13db826275/src/vorta/store/settings.py#L51-L52

**Comment by real-yfprojects** [comment]
This is a good idea!
