### ISSUE TITLE
BORG_PASSPHRASE empty 

### ISSUE THREAD

**Issue by jgkennedy** [borgbase/vorta#1767]
### Description

Vorta does not read BORG_PASSPHRASE. The environment variable is empty when Borg reads it. I stuck a logger here to dump the environment variables, and it's empty. The rest of the environment variables are intact. BORG_PASSCOMMAND works fine. Running Borg works, and the environment variable is filled in. Only in Vorta it's empty. 
https://github.com/borgbackup/borg/blob/1c8da8f98ad118e363d1f90c805e26d5f284d077/src/borg/helpers/passphrase.py#L41

I'm using the latest WSL version Ubuntu 22.04.2 LTS. 

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Ubuntu 22.04.2 LTS

### Version of Vorta

0.8.3

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.0

### Logs

```pytb
vorta.borg.borg_job - WARNING - env environ({'SHELL': '/bin/bash', 'WSL_DISTRO_NAME': 'Ubuntu', 'BORG_PASSPHRASE': '', ...
```

**Comment by real-yfprojects** [comment]
Hi @jgkennedy,
yes, this behaviour is expected. Why do you want to pass the passphrase through the environment variable?
