### ISSUE TITLE
Text color makes links hard to read when using dark mode

### ISSUE THREAD

**Issue by Plastix** [borgbase/vorta#177]
**Describe the bug**
This "bug" is more of an accessibility issue. I have normal vision and it is hard to read the hyperlinks because the blue color blends into background when using Vorta's dark mode.

I would be willing to help fix this if this is indeed something we want to address. Thanks!

**To Reproduce**
1. Enable Vorta's dark mode.
2. Open any tab that has a link, e.g., the "repository" tab.

**Desktop:**
 - OS: MacOS `10.14.3` and Vorta `0.6.7`

**Additional context**
<img width="800" alt="screen shot 2019-02-02 at 6 45 07 pm" src="https://user-images.githubusercontent.com/1526881/52172081-27fdf380-271d-11e9-8c1e-1bac70c8776d.png">

**Comment by m3nu** [comment]
We probably can't fix this, as the link color isn't set in the stylesheet. See the [issue in the upstream project](https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/112) for details.

**Comment by Plastix** [comment]
Hmm that sucks. Thanks for the quick feedback @m3nu.

**Comment by m3nu** [comment]
I ran into the same issue when first integrating the dark theme.

Maybe there is some workaround. Like removing the per-element CSS.

**Comment by m3nu** [comment]
Closing this, as we can't fix it for now. Will keep my eyes open in case something comes up.
