### ISSUE TITLE
Extract View Health column color is always green/healthy

### ISSUE THREAD

**Issue by jetchirag** [borgbase/vorta#1776]
### Description

I was writing tests for a PR and the color wasn't changing even when `healthy` was false.

https://github.com/borgbase/vorta/blob/master/src/vorta/views/extract_dialog.py#L493-L497

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Kali

### Version of Vorta

Branch up to date with Master

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.4

**Comment by real-yfprojects** [comment]
Oh, good catch!
