### ISSUE TITLE
FR: Reduce test workflow for each PR/commit

### ISSUE THREAD

**Issue by bigtedde** [borgbase/vorta#1778]
#### The problem
Our current Github test workflow has 38 checks being ran for each PR/commit. This uses a lot of resources and takes some time to complete. 

#### Requested Solution
Our previous matrix strategy was 4 python versions (3.8 to 3.11) on 2 OS's (linux, mac), with one version of Borg (1.2.4). If we went back to this it would run these 8 checks for unit tests and 8 for integration tests, so 16 total (+ lint). This would reduce the workflow by about 58%. There would remain the option to run all 39 checks manually. 

#### Alternatives
Open to feedback and alternatives 😀
@m3nu @real-yfprojects @jetchirag 

#### Additional context
Addresses [this comment](https://github.com/borgbase/vorta/pull/1716#issuecomment-1676435290).

**Comment by m3nu** [comment]
In favor of reducing default tests and running the rest only when merging into master or manually.

For the latest 2 PRs I've looked at, all had a test time out.

**Comment by real-yfprojects** [comment]
Also we can enable github's merge queue features which helps with merging multiple PRs after another while having to wait for ci each time.

> For the latest 2 PRs I've looked at, all had a test time out.

Will reducing the test matric solve that? I would think some step in the workflow is taking too long if that problem occurs.
