### ISSUE TITLE
FR: Disable "Collapse" button in "Flat" view

### ISSUE THREAD

**Issue by jetchirag** [borgbase/vorta#1784]
The "Collapse" button doesn't do anything when "Flat" view is selected. Could be disabled in such cases
_Originally posted by @m3nu in https://github.com/borgbase/vorta/issues/1749#issuecomment-1682002001_

This is a very minor FR, probably a few lines or so but I wanted to keep it seperate from original PR. I'll submit a PR in a while but please feel free to pick this up if anyone is interested.

***

### Instructions

1. Have a look at https://github.com/borgbase/vorta/blob/567a3546ae09878cf64f9f10c5c6f7bb7254720e/src/vorta/views/diff_result.py#L183
2. Use `setEnabled` to disable `bCollapseAll` in flat mode and enable it in the other modes.
3. Write a test for that behaviour in https://github.com/borgbase/vorta/blob/e85ec38c65f838a1c42dc3d5afdcb3dccb9802f4/tests/unit/test_diff.py

**Comment by SAMAD101** [comment]
```
def change_display_mode(self, selection: int):
        """
        Change the display mode of the tree view

        The `selection` parameter specifies the index of the selected mode in
        `comboBoxDisplayMode`.

        """
        if selection == 0:
            mode = FileTreeModel.DisplayMode.TREE
        elif selection == 1:
            mode = FileTreeModel.DisplayMode.SIMPLIFIED_TREE
        elif selection == 2:
            mode = FileTreeModel.DisplayMode.FLAT
        else:
            raise Exception("Unknown item in comboBoxDisplayMode with index {}".format(selection))

        SettingsModel.update({SettingsModel.str_value: str(selection)}).where(
            SettingsModel.key == 'diff_files_display_mode'
        ).execute()

        self.model.setMode(mode)
```
will changing the `setMode` to `setEnabled` be enough?

**Comment by real-yfprojects** [comment]
No, you will have to modify the code of `change_display_mode` so that it correctly calls `setEnabled`. 
What I forgot to write down is that the same has to be done for 
https://github.com/borgbase/vorta/blob/567a3546ae09878cf64f9f10c5c6f7bb7254720e/src/vorta/views/extract_dialog.py#L178

**Comment by SAMAD101** [comment]
i've made a PR, do suggest any changes/improvements needed.

**Comment by prady0t** [comment]
Is it still open? Can I work on this?

**Comment by real-yfprojects** [comment]
> Is it still open? Can I work on this?

Yes, please.

**Comment by prady0t** [comment]
@real-yfprojects Thanks for assigning me this issue 😄. Can you help me with these questions?
- How to reproduce this issue locally? 
- Where in UI is the `Flat` view?

**Comment by jetchirag** [comment]
@prady0t In Archives Tab, there are two options "Extract" and "Diff" which open a new dialog with [TreeView](https://doc.qt.io/qt-6/qtreeview.html). Here you will find a caret up icon i.e. Collapse button

![image](https://github.com/borgbase/vorta/assets/15169678/f2e5a1d6-ae04-4fa3-ba62-27837fc9039b)


In tree view you can expand an item and reveal its children and this button collapses all items. However In Flat View, there's nothing to expand and collapse. To reproduce, click on View Dropdown and select Flat (defaults to Tree).

![image](https://github.com/borgbase/vorta/assets/15169678/3318ca92-7bde-4775-bf61-f60763d66b35)

**Comment by prady0t** [comment]
Thanks! That was really helpful.

**Comment by prady0t** [comment]
Buttons are greyed out. I tried to add a new repository but I was unable to do that. I got this error message:

<img width="420" alt="Screenshot 2023-09-22 at 11 21 20 AM" src="https://github.com/borgbase/vorta/assets/99216956/87072b1e-a670-42e2-9a85-f89498b02b83">

Should I open a PR regarding this?

**Comment by AdwaitSalankar** [comment]
Hi @real-yfprojects, Can I raise a PR for this?

**Comment by real-yfprojects** [comment]
Yes, of course!
