### ISSUE TITLE
Vorta Icon in the MacOS Menu Bar Does Not Conform to System Appearance

### ISSUE THREAD

**Issue by ksnell88** [borgbase/vorta#1786]
#### Description

The Vorta icon in the MacOS menu bar stands out against all other native and third party apps with it being solid black, etc. This seems like it could be improved from a UI perspective and is a bit distracting.

It would be great if the icon was the same style as all other icons (monochrome?). Giving the end user the option to select the icon (like Amphetamine app does) would be a great alternative if it is not desirable to change to a standardized icon.

See screenshot for example:
![2023-08-23_vorta icon](https://github.com/borgbase/vorta/assets/34407093/244969a8-202f-4cdc-8d91-05d649216992)

#### Environment

- OS: MacOS Ventura 13.4.1
- Vorta version: 0.8.11
- Installed from: Homebrew, as recommended here: [macOS | Vorta for BorgBackup](https://vorta.borgbase.com/install/macos/)
- Borg version: 1.2.4

#### Logs

N/A - see screenshot

**Comment by m3nu** [comment]
There was an open PR to solve this, but I don't know if it ended up working with Qt.

**Comment by m3nu** [comment]
https://github.com/borgbase/vorta/issues/1220

**Comment by real-yfprojects** [comment]
> There was an open PR to solve this, but I don't know if it ended up working with Qt.

It still a work in progress. The problem is that Vorta cannot detect whether the icon should be black or white so we decided to use an icon that works with both kinds of backgrounds.

**Comment by real-yfprojects** [comment]
> And there is no way to hide the icon?

We could implement that.



> I don't know enough to look further but do wonder how the other apps are doing it.

The other apps use the native MacOS API directly which allows providing [a single monochromatic icon](https://developer.apple.com/documentation/appkit/nsimage/1520017-template?language=objc) which will be coloured by the os. In contrary we use Qt which doesn't support this feature afaik.

**Comment by ksnell88** [comment]
Thanks for the info! I guess the problem with hiding the icon is there isn't a real way to know the app is running/to call it since there isn't an icon in the dock. I can see why it is built as is, thanks.

**Comment by real-yfprojects** [comment]
> to call it since there isn't an icon in the dock.

Well you could still open it by trying to start a new Vorta instance.
