### ISSUE TITLE
Add menu or dropdown to change language interface

### ISSUE THREAD

**Issue by drakegalley** [borgbase/vorta#1788]
#### The problem

Hello. I don't see a way to change the language of the program's interface without changing the system language.

For example, my system is in Spanish from Spain and the Vorta translation is incomplete. Therefore, it is confusing to have a mixture of two languages and not be able to do anything to change it.

#### Requested Solution

If it is not possible in the current state of the program to change the language interface, I would like to request that a menu or dropdown be added for this purpose.

Thanks in advance.

**Comment by yiveynod** [comment]
+1 I second this! I'm in Sweden with the same problem and it's also the fact that almost all available documentation is in English making it essentially harder to setup for me even though it tries to give me my native language.

**Comment by m3nu** [comment]
You can already set the language using an env var: https://vorta.borgbase.com/contributing/translations/#using-and-testing-transifex-translations

For adding a dropdown, we could consider such a PR. The *Misc* tab would be the best place for it, I think.

**Comment by yiveynod** [comment]
> You can already set the language using an env var: https://vorta.borgbase.com/contributing/translations/#using-and-testing-transifex-translations
> 
> For adding a dropdown, we could consider such a PR. The _Misc_ tab would be the best place for it, I think.

How do I use an env var on macOS? I’ve used them in various docker containers on Linux based servers but unfamiliar with it on macOS.

**Comment by real-yfprojects** [comment]
And example implementation can be found here: https://github.com/real-yfprojects/ectec/blob/main/python/ectec-gui/src/ectecgui/qobjects.py
The code can be used for Vorta with my permission.
