### ISSUE TITLE
minor bug due to non availability of peewee in requirements.d/dev.txt

### ISSUE THREAD

**Issue by SAMAD101** [borgbase/vorta#1795]
#### Description
When setting up vorta for development in my system, following the steps in contribution guide, I encountered this simple issue:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/sam/Codes/vorta/src/vorta/__main__.py", line 5, in <module>
    from peewee import SqliteDatabase
ModuleNotFoundError: No module named 'peewee'
```
This can simply be solved by adding `peewee` in the requirements.d/dev.txt.

**Comment by real-yfprojects** [comment]
But peewee should be installed when running 

```
pip install -e .
```

It isn't a development dependency and consequently doesn't have to be added to `requirements.d/dev.txt`.
