### ISSUE TITLE
Profile not renamed in icon 'Backup Now' menu until after re-start [Mac OS]

### ISSUE THREAD

**Issue by adamluk** [borgbase/vorta#18]
![screenshot 2018-11-17 at 12 30 06](https://user-images.githubusercontent.com/9057461/48661133-349b7580-ea65-11e8-9dc4-d0895ec7ff31.png)

I have renamed the default profile to BorgBase, however, it still shows as Default in the Backup Now menu.

This corrects itself after Vorta is re-started, so low priority visual bug - perhaps possible to fix?

**Comment by m3nu** [comment]
Fixes. Profile names are now updated whenever menu is opened.
