### ISSUE TITLE
Missing dmg artifact for 0.8.12 release

### ISSUE THREAD

**Issue by chenrui333** [borgbase/vorta#1806]
👋 it looks like the dmg artifact was not included in the 0.8.12 release, raise this issue for some awareness. Thanks!

**Comment by m3nu** [comment]
It's the same as 8.11 and only removes a dependency for pypi.

https://github.com/borgbase/vorta/releases/tag/v0.8.11

I can add the DMG to 8.12 again.

**Comment by chenrui333** [comment]
That would be great, thanks!

**Comment by m3nu** [comment]
Upon thiking more about it: Issue is that the built-in updater may try to grab the file in that case and then wonder why it has a different version.

So best to grab it from 0.8.11 and then we'll do the first release of 0.9 shortly.
