### ISSUE TITLE
Specify number of backups to keep

### ISSUE THREAD

**Issue by drohm** [borgbase/vorta#182]
**Is your feature request related to a problem? Please describe.**
Currently, I don't have a way to define how many backups to keep.  The only scheduling options are manual, x hour interval, or daily.  Also, the only option for pruning is to prune all old archives after each backup.

**Describe the solution you'd like**
Ideally, I'd like to be able to specify how many backups to keep, regardless of backing up manually, x hour interval, or daily.

As an example, here is a screenshot from Timeshift:
![timeshift-numkeep](https://user-images.githubusercontent.com/184959/52468275-39e4f980-2b56-11e9-8594-8541d94eac03.png)

**Describe alternatives you've considered**
I don't have any alternatives with the current implementation.  If I've missed something, apologies in advance.

**Comment by m3nu** [comment]
Have you looked under _Archive > Pruning options_? We have roughly the same there:

<img width="775" alt="screen shot 2019-02-08 at 18 24 10" src="https://user-images.githubusercontent.com/3916435/52472657-c92df380-2bce-11e9-879b-087f8e3d7869.png">

**Comment by adamluk** [comment]
If you Vorta for Borg Backup, click Archives tab, then select Prune Options and Archive Naming

**Comment by drohm** [comment]
Thanks @m3nu.  I had a feeling this functionality was already built-in, I just couldn't find it.
