### ISSUE TITLE
Pruning does not work

### ISSUE THREAD

**Issue by HerroBert** [borgbase/vorta#1821]
### Description

Pruning does not work. Log shows very prompt settlement:

> 2023-09-16 20:21:08,028 - vorta.borg.borg_job - INFO - Running command /usr/bin/borg prune --list --info --log-json --keep-hourly 2 --keep-daily 14 --keep-weekly 0 --keep-monthly 0 --keep-yearly 0 -a sh:amd3700-* --keep-within 10H user@server:/home/remotebackup/backup-vorta
> 2023-09-16 20:21:09,909 - vorta.borg.jobs_manager - DEBUG - Finish job for site: 3

List of backus do not show any difference. Oldest backup is still 2023-7-9.

I tried borg command from above in shell with no other result. Then I tried this command without "-a" (filter) and pruning worked!
Borg version on backup server is 1.1.15.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Ubuntu 23.04

### Version of Vorta

Vorta 0.8.10

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.4

**Comment by m3nu** [comment]
Already fixed, if I recall correctly.

**Comment by HerroBert** [comment]
Was this a borg or vorta bug?
