### ISSUE TITLE
Conection closed by remote Host. is borg working on the server?

### ISSUE THREAD

**Issue by aeollos76** [borgbase/vorta#1832]
Hi,
am facing with an unexpected error which is not letting me complete my back up.
the Error message is : "Connection closed by remote host." 
please help how to work around it.
<img width="801" alt="Screenshot 2023-10-23 at 9 44 00 AM" src="https://github.com/borgbase/vorta/assets/137780357/e480d414-5261-4986-8441-5da0b2307d31">

**Comment by m3nu** [comment]
If it fails right away and goes to BorgBase, this FAQ may be useful. https://docs.borgbase.com/faq/#all-connections-to-a-borgbase-repo-fail-with-an-error-immediately

Or contact support and they will give more guidance.

Your Vorta version is also a bit old.

**Comment by aeollos76** [comment]
thanks so much for the input.
