### ISSUE TITLE
Add Arabic Translation

### ISSUE THREAD

**Issue by ots25** [borgbase/vorta#1834]
Hello. i want to translate Vorta to Arabic language .
My Transifex account is @ots
My best Regards.

**Comment by real-yfprojects** [comment]
Thank you for your interest in translating Vorta. Can you apply to joining the project over at Transifex?

**Comment by ots25** [comment]
Ok, i sent request in Transifex.

**Comment by ThomasWaldmann** [comment]
Related: #1852

**Comment by ThomasWaldmann** [comment]
Not limited to arabic, rather meant as a general comment about translations:

It would be good if translations would get (similar as code changes) some review by another community member capable of doing that.

**Comment by ThomasWaldmann** [comment]
I didn't mean that technically, like the review process on github happening before a PR gets merged.

I just meant that there should be someone looking at that stuff.

Preferably on transifex (more comfortable) or after it gets pull into the repo.

**Comment by ots25** [comment]
Test Arabic Ui 
![Screenshot_20231213_193702](https://github.com/borgbase/vorta/assets/89610703/05a21c86-95de-41a8-84ed-1d5aa724651c)
![Screenshot_20231213_194515](https://github.com/borgbase/vorta/assets/89610703/59641e36-e437-4513-99a4-6dd28ef06676)

**Comment by ots25** [comment]
Testing Arabic UI
![Screenshot_20231213_193702](https://github.com/borgbase/vorta/assets/89610703/d00b96fa-ecff-4519-9922-f89f9b14f330)
![Screenshot_20231213_194515](https://github.com/borgbase/vorta/assets/89610703/e3e2c111-5b55-4745-a5cc-ec6c2d472446)

**Comment by real-yfprojects** [comment]
Since I am little familiar with rtl languages, where exactly lies the problem depicted in your screenshots?

**Comment by ots25** [comment]
In the first picture, notice the word {Borgbase} , which should be at the end of the line on the left.

**Comment by ThomasWaldmann** [comment]
Just a wild guess:

I didn't check in the code, but I could imagine that some text is just assembled in the code (e.g. like using string concatenation and assuming ltr text).

Such places need to be found and changed like `translate("For simple and secure backup hosting, try {borgbase_link}").format(...)` - just a rough example, not sure what kind of string formatting is preferred for vorta src code. 

Then, the rtl translator can move the placeholder via the translated string to the correct place and the formatting (placeholder replacement) happens *after* the translation.

**Comment by ots25** [comment]
Another issue after updating to Vorta 0.9.1, the direction of text and windows in the application has completely flipped from right to left!
![Screenshot_20240113_232520](https://github.com/borgbase/vorta/assets/89610703/0a5fe2be-9315-431e-9914-6075e94a48ef)

**Comment by ots25** [comment]
> Another issue after updating to Vorta 0.9.1, the direction of text and windows in the application has completely flipped from right to left! ![Screenshot_20240113_232520](https://private-user-images.githubusercontent.com/89610703/296518439-0a5fe2be-9315-431e-9914-6075e94a48ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MjM2NzUsIm5iZiI6MTcxMDYyMzM3NSwicGF0aCI6Ii84OTYxMDcwMy8yOTY1MTg0MzktMGE1ZmUyYmUtOTMxNS00MzFlLTk5MTQtNjA3NWU5NGE0OGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDIxMDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MzZlYjUxODUxYjQwNDJmMTc2OGRkNjE0ZmUwN2Y1YzAzODk3NWUzMjUxNzEwNDRmN2U3NWE1YWFiZjk1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3cu7sp2wGCtrmRyCig8P42Xocd-UohX9tz_2RqWq0EM)

**Comment by ots25** [comment]
Hi, after updating Plasma to 6 with wayland and Qt6, Right to left direction problem solved now.
