### ISSUE TITLE
Exclusions not working as expected

### ISSUE THREAD

**Issue by ituri** [borgbase/vorta#1842]
### Description

I have taken an extensive look at the documentation of the exclusion patterns in the [official borg documentation](https://borgbackup.readthedocs.io/en/stable/usage/help.html#borg-help-patterns) and at the ideas/discussion/screenshots [here in the repository](https://github.com/borgbase/vorta/issues/907).

I do however still fail to understand the basics of how exclusions work. I am backing up my home directory in Vorta but I don't want to include `~/Library/Application Support`.
According to the official documentation, this should work as an exclude pattern:
`- '**/Library/Application Support'`
However, it doesn't.
I also looked at the discussion I linked to above. According to some posts there, I could do without the dash at the beginning, i.e.:
`'**/Library/Application Support'`
This doesn't work either; the folder is being backed up. I even tried it without the apostrophe but still this folder and all its subfolders are being backed up. 

Why is that? What am I understanding wrong here?

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Mac OS Sonoma 14.1

### Version of Vorta

0.8.11

### What did you install Vorta with?

Homebrew

### Version of Borg

1.2.4

**Comment by m3nu** [comment]
I have this and it worked since the start:

![Screenshot 2023-11-13 at 15 55 53](https://github.com/borgbase/vorta/assets/3916435/b648f9ba-86de-41ae-8b64-2a2df00fd583)

**Comment by ituri** [comment]
Thank you, that was very helpful! Perhaps the documentation could include some exemplary exclusion patterns? I believe that referencing the Borg documentation and the examples provided there might be somewhat misleading.

**Comment by ituri** [comment]
Thank you, that was very helpful! Perhaps the documentation could include some exemplary exclusion patterns? I believe that referencing the Borg documentation and the examples provided there might be somewhat misleading.
