### ISSUE TITLE
date/time findings

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#185]
search source for `\.(utc)?now` to find:
- added_at / changed_at: sometimes utcnow, sometimes now is used
- three_months_ago != 180 days

**Comment by ThomasWaldmann** [comment]
search for `ISO_FORMAT`:
- defined, but not used. commented code.

**Comment by m3nu** [comment]
Had first look. So the best way forward would be to use `utcnow()` everywhere and then convert to the local timezone as needed with `utc.astimezone(to_zone)`?

**Comment by ThomasWaldmann** [comment]
Didn't look in the specifics here, but yes, usually "utc everywhere + conversion if needed" is a good approach.
