### ISSUE TITLE
log file link should not be in "about" view

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#1862]
#### Description

"Click here to view the logs" was put into the "About" dialogue (in between some web links there).

It should really be in "Schedule" -> "Log", just below the formatted summary - so one can look into the full log if that summary does not offer enough information (which is quite frequently the case).

#### Environment

- Vorta version: 0.9.1.beta3 but also older versions

Note: a good related ticket is #1838, can be solved before or after this one.

**Comment by real-yfprojects** [comment]
I guess, there should be a link at both places.

**Comment by SAMAD101** [comment]
![image](https://github.com/borgbase/vorta/assets/71956678/b9faee17-6035-461b-ab50-2e2b3c3d8842)

Where exactly? There is no good place to put that link.

**Comment by ThomasWaldmann** [comment]
Above that table, there could be:

"If you see a non-zero returncode, please check the log files for more details."

"log files" linking to the folder with the vorta log files.

**Comment by pavankalyan224847** [comment]
is this issue still open can i work on this ?

**Comment by ThomasWaldmann** [comment]
@SAMAD101 are you still working on this?

**Comment by SAMAD101** [comment]
> @SAMAD101 are you still working on this?

No, I'm working on another issue.

**Comment by ThomasWaldmann** [comment]
@pavankalyan224847 you have it!

**Comment by m3nu** [comment]
Yes, makes sense to implement this.

I'll release 0.9 soon with all the changes from GSoC. Let's add this before.

**Comment by pavankalyan224847** [comment]
@ThomasWaldmann logs should be removed from "About" view and the link should be added in the "Log" view but above the table containing Time,category,subcommand,return code right ? and one more thing can you please tell me the folders in which code related to about view and table are written

**Comment by ThomasWaldmann** [comment]
Yes.

You should be able to find the source files by searching for some english text strings you see in the related views on the vorta UI.

**Comment by pavankalyan224847** [comment]
I have made changes in my local repo but i am not able to see changes when in run vorta using that branch ex : i have removed the logs from about view and updated my main branch and then i run vorta using that branch but i can still see logs in the about view can you please tell me how i can check changes that i have made in my main branch

**Comment by ThomasWaldmann** [comment]
@pavankalyan224847 it might be helpful if you open a PR with what you have and ask that there.

**Comment by pavankalyan224847** [comment]
ohk then i'll create a PR

**Comment by shivansh02** [comment]
Can I work on this since author of #1909 is busy at the moment?

**Comment by pavankalyan224847** [comment]
yes sure go ahead you can refer to my commits on the PR which may be helpfull
