### ISSUE TITLE
Command 'uname -p 2> /dev/null' is not in the allowed list

### ISSUE THREAD

**Issue by samwilson** [borgbase/vorta#1865]
### Description

I'm trying to set up Vorta with an existing remote repository (on rsync.net), and it's connecting to it and listing all existing archives correctly, but backing up and other commands are failing. The error message is above (the log I've included is after trying to mount an existing archive, but the backup logs look pretty similar).

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Kubuntu 23.10

### Version of Vorta

0.8.12

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.6

### Logs

```pytb
INFO - Running command /usr/bin/borg --log-json mount xxxxxx@xxxxxx.rsync.net:reponame::archivename /home/user/borg-restore
ERROR - Remote: Borg 0.29.0: exception in RPC call:
WARNING - Remote: Traceback (most recent call last):
WARNING - Remote: File "/usr/home/kibab/borgbackup-0.29.0/borg/remote.py", line 96, in serve
WARNING - Remote: TypeError: open() takes from 2 to 5 positional arguments but 7 were given
WARNING - Remote: Command 'uname -p 2> /dev/null' is not in the allowed list.
ERROR - Remote: Platform: FreeBSD xxxxxx.rsync.net 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 rsync_13_1 amd64
WARNING - Remote: Python: CPython 3.4.3
```

**Comment by real-yfprojects** [comment]
Does this also happen when running borg from the commandline outside of Vorta?

**Comment by samwilson** [comment]
No, everything works find on the command line with `borg mount` and others.

**Comment by real-yfprojects** [comment]
Commandline and Vorta share the same borg version?

**Comment by samwilson** [comment]
Yep, same borg version, and yeah it seems that rsync.net is still running 0.29.0. Is that going to be a problem?

**Comment by m3nu** [comment]
Yes. That's ancient. 1.2.7 is the latest version of Borg. The last security-relevant release was 1.2.6.

**Comment by samwilson** [comment]
I asked them about upgrading, and they said that they have already got the newer version but the binary is `borg1` rather than `borg` and can be used with the `--remote-path=borg1` option.

The version of `borg1` is 1.2.6.

Is it possible to pass `--remote-path=borg1` to all commands issued by Vorta? I know it can be done for `create`, but does that apply to `mount` as well?

**Comment by real-yfprojects** [comment]
> Is it possible to pass `--remote-path=borg1` to all commands issued by Vorta? I know it can be done for `create`, but does that apply to `mount` as well?

Yes, it is. You can supply such arguments when adding the repository to Vorta. They will be stored and used for all other commands afaik.

**Comment by samwilson** [comment]
That works! Thanks. :-)
