### ISSUE TITLE
Local backups without SSH keys

### ISSUE THREAD

**Issue by mYnDstrEAm** [borgbase/vorta#1878]
#### The problem
Why is a SSH key required when just doing local backups?

The SSH key thing was the cause of most problems with Vorta ([see here](https://unix.stackexchange.com/questions/624438/how-to-create-a-new-keyring-default-with-kwalletmanager)). Just allowing users who only do local backups to not set one up would be best. Do I need the SSH key and its passphrase if I tried to restore a backup on another system? I don't think so but maybe I misunderstood something.

#### Requested Solution
For local backups don't require a SSH key and include information that this is needed for remote backups on mouse-over. It would make the software much easier to use, more accessible, and cause less confusion and difficulty in its set-up.

**Comment by m3nu** [comment]
Actually Vorta doesn't need to know about SSH keys, if you just keep it at Automatic. The option to generate one is really just to help newer users.

**Comment by real-yfprojects** [comment]
Isn't the ssh key widget disabled (greyed out) for local repositories? If not that would be the way to go imo.

**Comment by mYnDstrEAm** [comment]
Indeed it's greyed out now in version 0.8.10. Probably still used an earlier version until upgrading to Debian12.
