### ISSUE TITLE
Unable to delete repository?

### ISSUE THREAD

**Issue by Orbixx** [borgbase/vorta#188]
**Describe the bug**
This does not refer to the ability to actually delete remote repo content, but the repo addresses that are contained within the Repository drop-down under the Repository tab for a backup profile. I may be overlooking where to find this, but in that case please accept this a potential UX impovement.

**To Reproduce**
1. Add repo to Vorta
2. Search around for a place to manage existing repos
3. Give up after a few minutes
4. Submit issue on Github

**Desktop (please complete the following information):**
 - OS: MacOS Mojave

Please let me know if you need any further details.

**Comment by m3nu** [comment]
That's already possible using the "Unlink" button next to the dropdown.

Deleting a whole repo for good isn't implemented and probably shouldn't.

**Comment by ThomasWaldmann** [comment]
Deleting a whole repo is dangerous of course.

If you tell it to delete a whole repo, the borg cli will show a list of archives in the repo and require you to confirm with YES that you really want to delete them all.

**Comment by m3nu** [comment]
Correct. For that reason I don't think it should be implemented. Unlinking already solves the problem you describe. It will subsequently be removed from the dropdown.

So I'll close this for now. If I misunderstood the original problem, feel free to comment and reopen.

**Comment by Orbixx** [comment]
Apologies, Unlink was exactly what I was looking for. I just didn't understand the usage. Managing Vorta-wide managed repos from within a single profile's settings confused me.

**Comment by m3nu** [comment]
One profile isn't necessarily bound to one profile. In the future, you will be able to backup to multiple repos from one profile. So it makes sense to have them there. Borgmatic already supports that for example.

**Comment by Orbixx** [comment]
Great, then the current UI makes a lot of sense. Thanks everybody.
