### ISSUE TITLE
Wayland icon on panel/window instead of Vorta icon

### ISSUE THREAD

**Issue by Justinzobel** [borgbase/vorta#1880]
#### Description

On Wayland when the main window is open the panel and window icons are a Wayland icon, not Vorta's.

I am able to reproduce the issue.

1. Open main window when using any wayland composior that has a panel
#### Environment

- OS: Solus (Plasma)
- Vorta version: 0.8.12
- Installed from: Rpo
- Borg version: N/A

![image](https://github.com/borgbase/vorta/assets/1370117/bce34467-1152-4f64-b4e4-dd2d1a2e72e9)

**Comment by real-yfprojects** [comment]
Other users have reported the need to install some extra/qt6-svg package. Does that fix your issue?

**Comment by Justinzobel** [comment]
> Other users have reported the need to install some extra/qt6-svg package. Does that fix your issue?

I have that installed. No change.

**Comment by Justinzobel** [comment]
I responded, waiting on developer action.

**Comment by gzuaps** [comment]
Fix for plasma at URL below
https://discussion.fedoraproject.org/t/whats-with-the-wayland-icons-and-associated-apathy/40180

**Comment by MoralCode** [comment]
Im experiencing this on Kubuntu LTS (same vorta version as OP). would love for the icon to get updated as I have a few apps that have the same default icon in my taskbar and its hard to tell them apart

**Comment by gzuaps** [comment]
If you are using KDE/plasma then you fix the icon using this method

https://discussion.fedoraproject.org/t/whats-with-the-wayland-icons-and-associated-apathy/40180/5

**Comment by MoralCode** [comment]
yeah I saw that. I was ideally hoping to spend my effort in a way that would help fix this for everyone, not just me.
