### ISSUE TITLE
On the M1 Mac, all application icons disappeared after today's brew update.

### ISSUE THREAD

**Issue by Igaryu** [borgbase/vorta#1886]
### Description

IT - 20/01/2024

### Disappearance of icons.

This morning, after my brew daily update that updated Vorta to vorta-0.9.1 version; once launched Vorta.app and clicked on 'start backup' button, I received this message:

```
Icon [several names]svg file missing, please report this issue to https://github.com/borgbase/vorta/issues
```
Checked the open application, all the icons were missing.
  
I verify the reported path: the full directory pointed by the error message was missing: in truth, the full  `/Applications/Vorta.app/Contents/MacOS/assets` directory is missing

`/Applications/Vorta.app/Contents/MacOS` → assets does not exist any more.

I restored my yesterday backup, and it worked again: all directories are at correct place and icons are displayed correctly.

J.C.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Mac Mini M1-   14.2.1 (23C71)

### Version of Vorta

0.9.1

### What did you install Vorta with?

Homebrew

### Version of Borg

borgbackup-fuse 1.2.6

### Logs

```pytb
Traceback (most recent call last):
  File "views/main_window.py", line 269, in backup_cancelled_event
  File "views/archive_tab.py", line 212, in cancel_action
  File "views/archive_tab.py", line 243, in _toggle_all_buttons
  File "views/archive_tab.py", line 377, in on_selection_change
  File "views/archive_tab.py", line 557, in bmountarchive_refresh
  File "views/utils.py", line 9, in get_colored_icon
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/Vorta.app/Contents/MacOS/assets/icons/folder-open.svg'
2024-01-11 07:32:03,690 - vorta.borg.borg_job - DEBUG - Cancel job on site default
2024-01-11 07:32:03,691 - vorta.borg.borg_job - DEBUG - Cancel job on site 4
2024-01-11 07:32:03,691 - vorta.borg.borg_job - DEBUG - Cancel job on site 1
2024-01-11 07:32:03,691 - vorta.borg.jobs_manager - INFO - Finished cancelling all jobs
```

**Comment by m3nu** [comment]
That's odd, since the icons are all there in the app package. The path is `Vorta.app/Contents/Resources/assets/icons`. I also can't reproduce the issue on my Intel mac (and wouldn't know if the arch makes a difference).

Are you running Vorta by double-clicking or via CLI?

**Comment by MartinX3** [comment]
Using Arch Linux with XFCE.
I'm also missing my icons.
The terminal is spammed with `QImage::scaleHeight: Image is a null image`.
![image](https://github.com/borgbase/vorta/assets/4518092/85588cb1-45ac-4795-bada-d1fe748576c2)

**Comment by m3nu** [comment]
One more data point: Icons are there on Alma9 with Gnome, installed via `pip install vorta`.

**Comment by cloudchristoph** [comment]
Is this the same problem, or a different one?
I'm still on Vorta 0.8.11, but an error regarding the icon also popped up today (an continues to do).

![CleanShot 2024-01-11 at 16 20 11@2x](https://github.com/borgbase/vorta/assets/204027/9896397f-bc1d-4b4a-96c4-f0e279474b68)

**Comment by cloudchristoph** [comment]
The icon is placed in 
"/Vorta.app/Contents/MacOS/Resources/assets/icons" not in 
"/Vorta.app/Contents/MacOS/assets/icons"

Does that help?

![CleanShot 2024-01-11 at 16 25 23@2x](https://github.com/borgbase/vorta/assets/204027/19fefa1a-48b9-45f9-a824-b21911a6f709)

**Comment by MartinX3** [comment]
My icons are at `/usr/lib/python3.11/site-packages/vorta/assets/icons/`
```
$ ls -l
insgesamt 340
-rw-r--r-- 1 root root    343 11. Jan 10:51 angle-down-solid.svg
-rw-r--r-- 1 root root    341 11. Jan 10:51 angle-up-solid.svg
-rw-r--r-- 1 root root  11516 11. Jan 10:51 APACHE.txt
-rw-r--r-- 1 root root    379 11. Jan 10:51 broom-solid.svg
-rw-r--r-- 1 root root    475 11. Jan 10:51 check-circle.svg
-rw-r--r-- 1 root root    523 11. Jan 10:51 clock-o.svg
-rw-r--r-- 1 root root    533 11. Jan 10:51 cloud-download.svg
-rw-r--r-- 1 root root    489 11. Jan 10:51 copy.svg
-rw-r--r-- 1 root root   1102 11. Jan 10:51 cut.svg
-rw-r--r-- 1 root root    671 11. Jan 10:51 edit.svg
-rw-r--r-- 1 root root    304 11. Jan 10:51 eject.svg
-rw-r--r-- 1 root root    456 11. Jan 10:51 ellipsis-v.svg
-rw-r--r-- 1 root root   1421 11. Jan 10:51 eye-slash.svg
-rw-r--r-- 1 root root    987 11. Jan 10:51 eye.svg
-rw-r--r-- 1 root root    608 11. Jan 10:51 file-import-solid.svg
-rw-r--r-- 1 root root   1875 11. Jan 10:51 file.svg
-rw-r--r-- 1 root root    402 11. Jan 10:51 folder-on-top.svg
-rw-r--r-- 1 root root    478 11. Jan 10:51 folder-open.svg
-rw-r--r-- 1 root root    369 11. Jan 10:51 folder.svg
-rw-r--r-- 1 root root   3484 11. Jan 10:51 globe.svg
-rw-r--r-- 1 root root 110840 11. Jan 10:51 gpl_logo.svg
-rw-r--r-- 1 root root   6489 11. Jan 10:51 hdd-o-active.png
-rw-r--r-- 1 root root   4552 11. Jan 10:51 hdd-o.png
-rw-r--r-- 1 root root   1741 11. Jan 10:51 help-about.svg
-rw-r--r-- 1 root root    693 11. Jan 10:51 icon.svg
-rw-r--r-- 1 root root  28904 11. Jan 10:51 loading.gif
-rw-r--r-- 1 root root    327 11. Jan 10:51 minus.svg
-rw-r--r-- 1 root root   4536 11. Jan 10:51 OFL.txt
-rw-r--r-- 1 root root    681 11. Jan 10:51 paste.svg
-rw-r--r-- 1 root root    370 11. Jan 10:51 plus.svg
-rw-r--r-- 1 root root   9605 11. Jan 10:51 python_logo.svg
-rw-r--r-- 1 root root    673 11. Jan 10:51 refresh.svg
-rw-r--r-- 1 root root    523 11. Jan 10:51 server.svg
-rw-r--r-- 1 root root    753 11. Jan 10:51 settings_wheel.svg
-rw-r--r-- 1 root root    548 11. Jan 10:51 stream-solid.svg
-rw-r--r-- 1 root root    546 11. Jan 10:51 tasks.svg
-rw-r--r-- 1 root root    403 11. Jan 10:51 terminal.svg
-rw-r--r-- 1 root root    685 11. Jan 10:51 trash.svg
-rw-r--r-- 1 root root   1034 11. Jan 10:51 unlink.svg
-rw-r--r-- 1 root root    365 11. Jan 10:51 user.svg
-rw-r--r-- 1 root root    381 11. Jan 10:51 view-list-details.svg
-rw-r--r-- 1 root root    360 11. Jan 10:51 view-list-tree.svg
-rw-r--r-- 1 root root    809 11. Jan 10:51 wifi.svg
-rw-r--r-- 1 root root    409 11. Jan 10:51 window-restore.svg
```

**Comment by m3nu** [comment]
The function to pull the icon is here: https://github.com/borgbase/vorta/blob/master/src/vorta/utils.py#L296

For distributions packed via PyInstaller, the first case would be used. Maybe there was a change by Apple or PyInstaller? Though the 0.8 app package was done a long time ago and shouldn't just stop working.

**Comment by cloudchristoph** [comment]
> For distributions packed via PyInstaller, the first case would be used. Maybe there was a change by Apple or PyInstaller? Though the 0.8 app package was done a long time ago and shouldn't just stop working.

Sounds odd to me as well.
Do I understand correctly, that the path is based on a ... system constant (no idea about python, sorry), called "_MEIPATH"?

https://github.com/borgbase/vorta/blob/9cc7a98838d2f6bbcf984dd03ac35994b2c62340/src/vorta/utils.py#L299C1-L299C1

Could it be another update - a Python Update, e.g. - that has introduced a change for this constant?
Or does this code never get's called after bundling the packages?

I've Python 3.11.7 on this system

**Comment by m3nu** [comment]
`_MEIPATH` is set by PyInstaller, which packages Vorta for macOS:

https://pyinstaller.org/en/stable/runtime-information.html

**Comment by ThomasWaldmann** [comment]
Interesting. Icons work on macOS here (also M1, Sonoma).

I installed Vorta 0.9.1 via the .dmg offered on github releases page.

**Comment by seija-appears** [comment]
I'm also seeing this:

<img src="https://github.com/seija-appears/Image/blob/main/Screenshot_20240111_210408.png?raw=true">

**OS**
EndeavourOS + KDE Plasma (xOrg)

**Version of Vorta**
1 aur/vorta 0.9.1-1 (+71 4.98) (Installed)
    A GUI for BorgBackup

**What did you install Vorta with?**
using yay to install from Arch aur

**Version of Borg**
1 extra/borg 1.2.7-1 (1.4 MiB 7.0 MiB) (Installed)


```
ls -l 
total 340
-rw-r--r-- 1 root root    343 Jan 10 22:18 angle-down-solid.svg
-rw-r--r-- 1 root root    341 Jan 10 22:18 angle-up-solid.svg
-rw-r--r-- 1 root root  11516 Jan 10 22:18 APACHE.txt
-rw-r--r-- 1 root root    379 Jan 10 22:18 broom-solid.svg
-rw-r--r-- 1 root root    475 Jan 10 22:18 check-circle.svg
-rw-r--r-- 1 root root    523 Jan 10 22:18 clock-o.svg
-rw-r--r-- 1 root root    533 Jan 10 22:18 cloud-download.svg
-rw-r--r-- 1 root root    489 Jan 10 22:18 copy.svg
-rw-r--r-- 1 root root   1102 Jan 10 22:18 cut.svg
-rw-r--r-- 1 root root    671 Jan 10 22:18 edit.svg
-rw-r--r-- 1 root root    304 Jan 10 22:18 eject.svg
-rw-r--r-- 1 root root    456 Jan 10 22:18 ellipsis-v.svg
-rw-r--r-- 1 root root   1421 Jan 10 22:18 eye-slash.svg
-rw-r--r-- 1 root root    987 Jan 10 22:18 eye.svg
-rw-r--r-- 1 root root    608 Jan 10 22:18 file-import-solid.svg
-rw-r--r-- 1 root root   1875 Jan 10 22:18 file.svg
-rw-r--r-- 1 root root    402 Jan 10 22:18 folder-on-top.svg
-rw-r--r-- 1 root root    478 Jan 10 22:18 folder-open.svg
-rw-r--r-- 1 root root    369 Jan 10 22:18 folder.svg
-rw-r--r-- 1 root root   3484 Jan 10 22:18 globe.svg
-rw-r--r-- 1 root root 110840 Jan 10 22:18 gpl_logo.svg
-rw-r--r-- 1 root root   6489 Jan 10 22:18 hdd-o-active.png
-rw-r--r-- 1 root root   4552 Jan 10 22:18 hdd-o.png
-rw-r--r-- 1 root root   1741 Jan 10 22:18 help-about.svg
-rw-r--r-- 1 root root    693 Jan 10 22:18 icon.svg
-rw-r--r-- 1 root root  28904 Jan 10 22:18 loading.gif
-rw-r--r-- 1 root root    327 Jan 10 22:18 minus.svg
-rw-r--r-- 1 root root   4536 Jan 10 22:18 OFL.txt
-rw-r--r-- 1 root root    681 Jan 10 22:18 paste.svg
-rw-r--r-- 1 root root    370 Jan 10 22:18 plus.svg
-rw-r--r-- 1 root root   9605 Jan 10 22:18 python_logo.svg
-rw-r--r-- 1 root root    673 Jan 10 22:18 refresh.svg
-rw-r--r-- 1 root root    523 Jan 10 22:18 server.svg
-rw-r--r-- 1 root root    753 Jan 10 22:18 settings_wheel.svg
-rw-r--r-- 1 root root    548 Jan 10 22:18 stream-solid.svg
-rw-r--r-- 1 root root    546 Jan 10 22:18 tasks.svg
-rw-r--r-- 1 root root    403 Jan 10 22:18 terminal.svg
-rw-r--r-- 1 root root    685 Jan 10 22:18 trash.svg
-rw-r--r-- 1 root root   1034 Jan 10 22:18 unlink.svg
-rw-r--r-- 1 root root    365 Jan 10 22:18 user.svg
-rw-r--r-- 1 root root    381 Jan 10 22:18 view-list-details.svg
-rw-r--r-- 1 root root    360 Jan 10 22:18 view-list-tree.svg
-rw-r--r-- 1 root root    809 Jan 10 22:18 wifi.svg
-rw-r--r-- 1 root root    409 Jan 10 22:18 window-restore.svg
```

**Comment by cloudchristoph** [comment]
> Interesting. Icons work on macOS here (also M1, Sonoma). On that machine, I installed Vorta 0.9.1 via the .dmg offered on the github releases page.
> 
> On another machine (Intel, macOS Ventura), I also upgraded Vorta from 0.8.x to 0.9.1 via brew - also seeing icons there.

Uninstalled my Vorta, rebooted, reinstalled - and now it's working again. I'm seeing the icons again and get no errors. New Vorta 0.9.1.
Really strange.

**Comment by MartinX3** [comment]
It's acting weird here too.
Two laptops with Arch Linux + XFCE (EndeavourOS) and the one has icons, the other hasn't.
The only difference is a computer restart I think.

**Comment by seija-appears** [comment]
installing the extra/qt6-svg package resolved the issue for me in EndeavourOS

**Comment by m3nu** [comment]
Our icons come as SVG, so it makes sense. Glad it was such a simple issue.
