### ISSUE TITLE
Vorta stopped working on recent opensuse Tumbleweed snapshots

### ISSUE THREAD

**Issue by andreaippo** [borgbase/vorta#1887]
Hello,

please refer to:

https://forums.opensuse.org/t/vorta-fails-to-start-in-recent-snapshot/171595

TL;DR Vorta won't start anymore because it depends on platformdirs<4.0.0,>=2.6.0 but my distro now ships 4.1.0.

Is it up to Vorta devs to make this dependency more permissive?

Thanks

**Comment by m3nu** [comment]
This change was already made a few weeks back. See this duplicate issue: #1843 

It's also in the latest stable release 0.9.1. Would you want it backported to 0.8?

**Comment by andreaippo** [comment]
Ciao @m3nu ,

the opensuse maintainer just replied in that thread, saying the opensuse version of the package needs to be updated (indeed I have no updates available, and currently running opensuse's 0.8.12).

It's kind of you to propose backporting, I will let them know and let me advise what could be the fastest way to get back to a usable package on that distro. I guess I can use the flatpak version or just wait it out a few days, maybe it won't take them long to include 0.9.1.

**Comment by andreaippo** [comment]
The maintainers of the package in opensuse are updating it to 0.9.x, so I'll close this issue.

Thanks @m3nu
