### ISSUE TITLE
lrelease: command not found

### ISSUE THREAD

**Issue by tux-wclp** [borgbase/vorta#1890]
### Description

I updated the package from AUR using Yay

It updated all 4 dependencies correctly but it was unable to update the Vorta package from vorta 0.8.12-3 to 0.9.1-1
It blocks at the start of the Build () by restoring this error:

Avvio di build() in corso...
for f in $(ls src/vorta/i18n/ts/vorta.*.ts); do lrelease $ f -qm src/vorta/i18n/qm/$(basename $f .ts).qm; done
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
/bin/sh: riga 1: lrelease: command not found
make: *** [Makefile:57: translations-to-qm] Error 127
==> ERRORE: Si è verificato un errore in build().
L'operazione sta per essere interrotta...
-> errore durante la creazione: vorta-exit status 4
-> Installazione dei seguenti pacchetti non riuscita. È richiesto l'intervento manuale:
vorta - exit status 4

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

EndeavourOS  -  GNOME 45

### Version of Vorta

0.9.1-1

### What did you install Vorta with?

Distribution package

**Comment by m3nu** [comment]
Solution: Install the missing command, which is part of Qt.

```
$ lrelease --version
Usage:
    lrelease [options] -project project-file
    lrelease [options] ts-files [-qm qm-file]

lrelease is part of Qt's Linguist tool chain. It can be used as a
stand-alone tool to convert XML-based translations files in the TS
format into the 'compiled' QM format used by QTranslator objects.
```

**Comment by m3nu** [comment]
See also the section on Required software for translations in our docs:

https://vorta.borgbase.com/contributing/translations/#required-software
