### ISSUE TITLE
There is no un-mount option after mounting an archive

### ISSUE THREAD

**Issue by JackDinn** [borgbase/vorta#1891]
### Description

After using the vorta GUI to select an archive, then hitting the mount button. It mounts fine but there is no un-mount option or button.
I had to umount in manually on shell

vorta version 0.9.1-1
```
System:
  Host: greg-optiplex7050 Kernel: 6.6.8-2-MANJARO arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.27.10 Distro: Manjaro Linux
Machine:
  Type: Desktop System: Dell product: OptiPlex 7050 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 055H3G v: A01 serial: <superuser required> UEFI: Dell
    v: 1.26.0 date: 08/20/2023
CPU:
  Info: quad core Intel Core i5-7500 [MCP] speed (MHz): avg: 850
    min/max: 800/3800
Graphics:
  Device-1: Intel HD Graphics 630 driver: i915 v: kernel
  Display: x11 server: X.Org v: 21.1.10 with: Xwayland v: 23.2.3 driver: X:
    loaded: modesetting dri: iris gpu: i915 resolution: 1920x1080~60Hz
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: intel mesa v: 23.1.9-manjaro1.1
    renderer: Mesa Intel HD Graphics 630 (KBL GT2)
Network:
  Device-1: Intel Ethernet I219-LM driver: e1000e
  Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi
Drives:
  Local Storage: total: 1.84 TiB used: 176.13 GiB (9.3%)
Info:
  Processes: 208 Uptime: 1d 10h 10m Memory: total: 16 GiB available: 15.48 GiB
  used: 4.64 GiB (30.0%) Shell: fish inxi: 3.3.31

```
After successfully mounting, we have no button to un-mount (unless iv just missed it somewhere)
![Screenshot_20240112_175038](https://github.com/borgbase/vorta/assets/5557560/64be7bdc-0b2c-439c-a423-3de3919fc835)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Linux, Manjaro, KDE

### Version of Vorta

0.9.1-1

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.7

**Comment by madeddy** [comment]
> After successfully mounting, we have no button to un-mount (unless iv just missed it somewhere)

Yes, you did. ;)
The Button(s) for mounting have double occupancy. Means if you mount something they switch to "unmount" state. 

IMHO not ideal, **easy to miss** and should be changed. Two buttons, the invalid state greyed out and inactive would be a way i see as OK. If not, at least should this state of doubling etc. somehow made visible.
(Also: There are two mount buttons for different functions and no visible difference to show it! What the *%$§* !)

Greets

**Comment by JackDinn** [comment]
No i didn't, the screenshot above is taken after i have mounted an archive. (you see at the bottom it says "successfully mounted") because i have mounted that archive, but the mount button had not changed to unmount.

However, after the most recent update to 0.9.1-2 the GUI does now show unmount after mounting. So all working now.

I shall close the thread.

**Comment by madeddy** [comment]
> No i didn't, the screenshot above is taken after i have mounted an archive. 

Whoops, missed it obviously. Sry.
They made just some packaging changes regarding translation and qt svg, so i think it was just some slight mistake there. Good for you, greets.

**Comment by real-yfprojects** [comment]
> (Also: There are two mount buttons for different functions and no visible difference to show it! What the _%$§_ !)

So how would you solve that problem? We obviously are aware of this but we didn't know any better. Designing a GUI that isn't overwhelming while still being powerful and giving the user freedom isn't so easy after all. And still we regularly receive feature requests to add even more features further cluttering the UI.

**Comment by JackDinn** [comment]
Personally, now it's working as it should be (the mount button switches to unmount when you have an archive mounted), then that's fine. 

As you say, it's just becoming too much to go any further; it overcomplicates things. 

Well, that's my two cents' worth, anyhow.

**Comment by JackDinn** [comment]
> Also: There are two mount buttons for different functions and no visible difference to show it! What the %$§ 
O my mistake, are you talking about the 2 buttons that say "mount" the one on the side and the one on the bottom. Ahh right, yea i always thought they were the same function, i have never even tried the bottom one. Does it have a different function, if so what? I did wonder why there were 2 buttons that do the same thing?
