### ISSUE TITLE
Error mounting archive when using right-click menu

### ISSUE THREAD

**Issue by eblanshey** [borgbase/vorta#1900]
### Description

1. Right click an archive, select the Mount... option
2. Select an empty folder that you have write permissions for
3. Observe error: `sending file descriptor: Bad file descriptor`

If you click an archive and press the Mount... button below the archive list area, mounting works properly, so this is probably a UI issue. I am using the Flatpak version in Ubuntu 22.04.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Ubuntu 22.04

### Version of Vorta

Vorta 0.9.1

### What did you install Vorta with?

Flatpak

### Version of Borg

Borg 1.2.4

### Logs

```pytb
Cannot figure out how to extract the log
```

**Comment by eblanshey** [comment]
Thank you, I found the logs. Unfortunately there's no useful info there apart from the error I posted, "WARNING - sending file descriptor: Bad file descriptor".

It seems that the first backup created is the one that can't be mounted, whether through the context menu or right-hand side menu. The followup (incremental) backups can be mounted no problem.

I couldn't figure out how to manually run the mount command that was in the logs, as it's running through a flatpak container. For example I tried:

```
 flatpak run --command="/app/bin/borg --log-json mount /REPOINFO::NAME /home/user/Temp/Mnt" com.borgbase.Vorta
```

This gave me a "No such file or directory" error.

**Comment by real-yfprojects** [comment]
> Thank you, I found the logs. Unfortunately there's no useful info there apart from the error I posted, "WARNING - sending file descriptor: Bad file descriptor".

I am imagine there being a lot of useful info like what happened before and after the error, at what step in the process the error occurred, which mount command was run from the context menu and which from the button on the right side, ...
