### ISSUE TITLE
App not launching on macOS Sonoma

### ISSUE THREAD

**Issue by redfirebrooks** [borgbase/vorta#1904]
### Description

The application does not open anymore after the first opening. Fresh install with Homebrew.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

macOS Sonoma 14.2.1 (23C71)

### Version of Vorta

v0.9.1/vorta-0.9.1.dmg

### What did you install Vorta with?

Homebrew

### Version of Borg

borg 1.2.7

### Logs

```pytb
No log available, I can't open the application
```

**Comment by televisi** [comment]
Hi, I noticed this is happening with macOS Monterey (12.7.2), the difference is, it opened for the first time, but after I quit the app and reopen it, it just does not run.

The workaround: 

- Open Activity Monitor
- Find vorta.app
- Double click it and select "Quit"
- Reopen vorta.app

**Comment by m3nu** [comment]
Very old versions may not work with the pre-built bundle. Usually 1 or 2 versions up and down.

Alternative: build it yourself on whatever version you need. Just can't sign it without Apple account.
