### ISSUE TITLE
Show Vorta application icon when user switch between open apps (Command-Tab)

### ISSUE THREAD

**Issue by televisi** [borgbase/vorta#1911]
#### The problem
On Mac, you can use Command-Tab to switch between open apps.
Seems Vorta application icon is not showing during this activity

#### Requested Solution
When Vorta application is running, ideally to have the application icon to show when the user use the Command-Tab shortcut to switch between open apps

#### Alternatives
Use Hot Corners > Mission Control 
And Select Vorta application

Thank you

**Comment by m3nu** [comment]
Vorta is set to run as background app so it doesn't take up space in the Dock. So this is by design.

**Comment by televisi** [comment]
> Vorta is set to run as background app so it doesn't take up space in the Dock. So this is by design.

Ah make sense... so in the scenario I clicked on the green close icon on its window, how do I bring the window/app to show again? 

As when I tried to double click vorta.app, nothing appears?

Thank you

**Comment by real-yfprojects** [comment]
> As when I tried to double click vorta.app, nothing appears?

This should work afaik. Alternatively you click on the system tray icon located in the upper-right corner.

**Comment by televisi** [comment]
> This should work afaik. Alternatively you click on the system tray icon located in the upper-right corner.

Did you mean this icon?
<img width="28" alt="image" src="https://github.com/borgbase/vorta/assets/4546680/060a972c-b360-4279-b292-8738642f9e06">
Because I cannot see Vorta icon here:
<img width="295" alt="image" src="https://github.com/borgbase/vorta/assets/4546680/bd174b72-9694-4c0b-ac6d-5b4b11d82273">

**Comment by real-yfprojects** [comment]
> Did you mean this icon?
> <img alt="image" width="28" src="https://private-user-images.githubusercontent.com/4546680/303749424-060a972c-b360-4279-b292-8738642f9e06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1MDg4ODksIm5iZiI6MTcwNzUwODU4OSwicGF0aCI6Ii80NTQ2NjgwLzMwMzc0OTQyNC0wNjBhOTcyYy1iMzYwLTQyNzktYjI5Mi04NzM4NjQyZjllMDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDlUMTk1NjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVmNDMwZjY2ZjdhZmVlMTg0ODdhMzQ5OTU3NjM4OGI1NDlhZDM4NjBjYWQ4ZTNkZDQ2MjNlM2JjODlmZWI5YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hMaUa1325ppsFzFB95irv7pja_PxUc9gx8_WPjYYkQ8">

No, but next to it there should be a vorta logo you can click on.

**Comment by televisi** [comment]
Hm... I don't see it, unless because I have too many icons on the top bar... let me try to find it again...

**Comment by televisi** [comment]
Oh my! Yes, I can see Vorta icon now! 
It was 'hidden' because I got too many icons on the top bar.
I installed [bartender app](https://www.macbartender.com/) and now I can see it:
<img width="871" alt="image" src="https://github.com/borgbase/vorta/assets/4546680/3c4192b4-ed93-4249-8c26-c466c7287849">

Thank you!
