### ISSUE TITLE
Google Summer of Code 2024 (Mentors)

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#1923]
Hey @witten @Hofer-Julian @real-yfprojects @ThomasWaldmann,

Are we doing GSoC again this year? There was a deadline today. I updated the ideas [page](https://github.com/borgbase/vorta/wiki/Google-Summer-of-Code-2024-Ideas) and [added](https://github.com/python-gsoc/python-gsoc.github.io/pull/155) us to PSF. The process should be simpler than when starting from scratch.

Some features from 2023 aren't fully finished and some need expanding to be useful. And I think the program gave us some momentum. I'd just go for max 1-2 students only, depending what Borgmatic and Borg are planning.

Also, who'd be willing to mentor? If yes, please add some good projects to the ideas page and update 'good first issue' tags.

**Comment by Hofer-Julian** [comment]
Hey @m3nu!
I will not be able to mentor this year. I arguably already did quite little last year as well 🙈

**Comment by m3nu** [comment]
That's not an issue really. Even jumping in now and then is helpful. And as we know, the PSF gets paid by Google according to mentors. So getting some useful PRs for us is a benefit in addition to that.

**Comment by ThomasWaldmann** [comment]
I can offer the same as last year.

**Comment by real-yfprojects** [comment]
Sadly, I can't do as much this time. I could be second contact person but I won't be able to provide full-mentor for a student as I did last year.

**Comment by witten** [comment]
This year I unfortunately won't have time to be a dedicated mentor, but I'd be happy to be on point for borgmatic PRs. Also, some of the borgmatic GSoC ideas are out of date and/or already implemented, so I'll attempt to give those a refresh.

**Comment by m3nu** [comment]
Sounds like we'll go for 1 student this year then. Thanks everyone for cleaning up the ideas page.

Our org is now live on Python's main site: https://python-gsoc.org/ideas.html

**Comment by m3nu** [comment]
Alright, so I would need one more mentor in Google's system to get started. There is no expectation to do much as I can do the calls and usually someone is around to review PRs. I'll also limit it to 1 student only this year.

Steps:
1. Fill the PSF form: https://forms.gle/coJYxhor6FAZcZfU8
2. Accept Google's terms on their platform or wait for an invite:  https://summerofcode.withgoogle.com/ 

Thanks, all! 🙏

**Comment by witten** [comment]
> Alright, so I would need one more mentor in Google's system to get started.

Done!

**Comment by m3nu** [comment]
Thanks a lot for stepping up, @witten! And @diivi!

Glad we can make it happen again. 💪

**Comment by jetchirag** [comment]
I would also be happy to review PRs wherever I can.

**Comment by m3nu** [comment]
Closing since, this is already ongoing.
