### ISSUE TITLE
Ability to increase font size in Vorta

### ISSUE THREAD

**Issue by lamyergeier** [borgbase/vorta#1925]
#### The problem

I have a high resolution screen and as seen in the following image its hard to read the contents, can you please provide a setting to manually set a font size for Vorta, or may be you could let user enter percentage by which all fonts used in vorta gets increased.

![image](https://github.com/borgbase/vorta/assets/42092626/abe7eac5-7f11-4171-bf29-2f5d76b4b91a)

**Comment by m3nu** [comment]
Shouldn't Qt deal with this? Usually there are different style sheets for each OS.

**Comment by lamyergeier** [comment]
Should I install any QT configuration software on Fedora? And could you please tell me what needs to be changed?

**Comment by koutheir** [comment]
@lamyergeier, try setting the environment variable `QT_SCALE_FACTOR` to a value higher than 1. For example:
```shell
$ QT_SCALE_FACTOR=1.15 vorta
```
