### ISSUE TITLE
Vorta is unable to find the installed fuse

### ISSUE THREAD

**Issue by lamyergeier** [borgbase/vorta#1926]
#### Description

I installed borg and vorta as follows: 

```
			sudo dnf install -y python3 python3-devel python3-pip python3-virtualenv \
				libacl-devel libacl \
				openssl-devel \
				lz4-devel libzstd-devel xxhash-devel \
				pkgconf python3-pkgconfig
			sudo dnf install -y gcc gcc-c++ redhat-rpm-config
			sudo dnf install -y fuse-devel fuse   # needed for llfuse
			sudo dnf install -y fuse3-devel fuse3 # needed for pyfuse3
			sudo dnf install -y python3-llfuse
                        
                        pipx install "borgbackup==2.0.0b7"
```
Refer: [Installation — Borg on Fedora](https://borgbackup.readthedocs.io/en/latest/installation.html#fedora)

```
pipx install vorta
```

But I get the following error, clearly vorta is unable to find the FUSE:

![image](https://github.com/borgbase/vorta/assets/42092626/31a72f26-f9dc-41f2-97dd-89f9fc6b4dec)

#### Environment

- OS: Fedora 39
- Vorta version: 0.9.1
- Installed from: pipx
- Borg version: 2.0.0b7

#### Logs

I am unable to see the individual log by double clicking in the following window:

![image](https://github.com/borgbase/vorta/assets/42092626/35b80671-3af9-4d1a-a6aa-d9f74fb13014)

**Comment by real-yfprojects** [comment]
If I am not mistaken this is because you have installed vorta/borg in a virtual pipx environment while the fuse packages is installed in the system python environment by the package manager.
Try

```bash
pipx inject borgbackup llfuse
```
