### ISSUE TITLE
Vorta should motivate the user to backup the repokey

### ISSUE THREAD

**Issue by PinkPlasticBeach** [borgbase/vorta#1928]
#### The problem

Backing up Repokey is no visible and obvious function of Vorta

#### Requested Solution

Vorta should have a button to backup the repokey

and maybe
prompt the user to do so after archive-creation

#### Additional context
As far as I know its  good practice to backup the repokey (/keyfile) of Archives when encrypted (which is default). 
If for some reason this one file is corrupted the whole Archive is lost.

Vorta offers the Option to export Vorta-Profiles and there asks me whether I want to store the "Borg-Passwort"
in the Exported Data. Here I am unsure what that means and does:

---- "export Borg-Password" UNchecked:

Does it Export the repokey at all? Or just Settings/Paths of Vorta? 

---- "export Borg-Password" checked:

Does  it Export the Repokey, but its called "Borg-Password"? (so I need to make sure I have the Passphrase Save somehow else)
OR
Do I export the Repokey PLUS the Passphrase for that key? (such that it will be unsafe to store the Export of the Profile in any place that is not encrypted itself, because its kind of a plaintext key file)

-----------------------

In True-/Veracrypt the User was prompted to Export not only a key-file but a "Header". Im not sure what that "Header" included, but I'm asking me for Borg/Vorta which is the other crucial Metadata that would lead to an inaccessible Archive if damaged.
Is all that Data exported with the "Export" of Vorta-Profiles or not? It would be good to have that information when creating an archive and when using the export-feature of Vorta.

Thanks a lot for this amazing Backup-Solution - Finally - for Linux :D

**Comment by goebbe** [comment]
Related: https://github.com/borgbase/vorta/issues/1918
