### ISSUE TITLE
MacFUSE - vorta 0.9.1-beta2 - and homebrew, too

### ISSUE THREAD

**Issue by mcvons** [borgbase/vorta#1930]
### Description

Am getting this error when attempting to mount an archive

vorta.borg.borg_job - ERROR - borg mount not available: no FUSE support, BORG_FUSE_IMPL=pyfuse3,llfuse.

I have definitely installed macFUSE 4.6.0

have also tried the homebrew

where i get:
/usr/local/Caskroom/osxfuse/3.11.2/Extras/FUSE\ for\ macOS\ 3.11.2.pkg -target /` exited with 1. Here's the output:
installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.

my current osx is 14.3

any guidance much appreciated.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

osx 14.3 

### Version of Vorta

0.9.1-beta2

### What did you install Vorta with?

Binary

### Version of Borg

1.2.7

### Logs

```pytb
vorta.borg.borg_job - ERROR - borg mount not available: no FUSE support, BORG_FUSE_IMPL=pyfuse3,llfuse.

I have definitely installed macFUSE 4.6.0

have also tried the homebrew

where i get:
/usr/local/Caskroom/osxfuse/3.11.2/Extras/FUSE\ for\ macOS\ 3.11.2.pkg -target /` exited with 1. Here's the output:
installer: Error - The FUSE for macOS installation package is not compatible with this version of macOS.
```

**Comment by mcvons** [comment]
So - further poking - and on an attempt to use the command line home brew of the cask install got this new error:

Error: Cannot install borgbackup/tap/borgbackup-fuse because conflicting formulae are installed.
  borgbackup: because borgbackup-fuse is a patched version of borgbackup

Please `brew unlink borgbackup` before continuing.

Did that unlink, tried to install again - that worked 
and now Mounting is working in Vorta

a super duper app for sure - thank you.

**Comment by real-yfprojects** [comment]
I am glad you managed fix the problem. Not sure whether there is a problem with the binary or the brew package.
