### ISSUE TITLE
Add WOL (wakeonlan) Funktion

### ISSUE THREAD

**Issue by Aetzer99** [borgbase/vorta#1949]
Hello,
The problem is that my backup server is waiting in standby. Otherwise the power consumption would be too high.
So it would be great if VORTA could send a WoL command.
Alternatively, it would also be good if Vorta could execute the pre and after commands for every action, then it would be possible for me to solve the problem with a script.

Thank you

**Comment by m3nu** [comment]
We already have pre- and post commands.
