### ISSUE TITLE
Fail to connect to BorgBase repo on new computer

### ISSUE THREAD

**Issue by amorris28** [borgbase/vorta#1961]
I have a BorgBase repo I've been backing up to from a Debian computer.  I am testing how to recover from this repo if my computer were to fail. I installed Vorta on a macOS computer and tried to connect to the repo by doing the following:

- Create SSH key on macOS and add the public key to my BorgBase account.
- Add the macOS SSH key to the Debian repo on BorgBase
- Connect to the Debian BorgBase repo on my macOS Vorta instance by copying the repo url and using the passphrase for that repo

When I try to do the final step, Vorta hangs and I get a popup with the following error message. 

I tried copying the SSH key from my Debian PC over and using that, but that didn't work either. Vorta just hangs with the spinning wheel of death. I have the borgbase encrypted key backup file but I don't know how to use that.

Any idea what's going wrong and how I can get access to this repo from another computer? Thanks!

```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
File "peewee.py", line 7160, in get
File "peewee.py", line 4510, in __getitem__
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "application.py", line 227, in react_to_log
File "peewee.py", line 6712, in get
File "peewee.py", line 7163, in get
vorta.store.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_count", "t1"."schedule_interval_unit", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_make_up_missed", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```

**Comment by amorris28** [comment]
Opening up Vorta now it looks like the Debian repo was successfully added and I am able to download Archives from it onto my Mac. It's unfortunate that the program hangs/crashes and gives an error message even though the repo was successfully added. It looks like others #1943 #1913 have had similar issues. Might be related.

**Comment by m3nu** [comment]
Glad it solved itself. Closing.
