### ISSUE TITLE
Replace flake8 with Ruff for faster linting

### ISSUE THREAD

**Issue by shivansh02** [borgbase/vorta#1969]
#### The problem

Linting speed can be improved by using only Ruff.
#### Requested Solution

I propose replacing flake8 with Ruff, which we are already using in the project. Ruff's linter is much faster and implements every rule in flake8.

#### Alternatives

Other popular python linters, but Ruff seems to be the fastest and its already being used.

**Comment by m3nu** [comment]
Right. Ruff is already used, but we kept flake8 as well. If you want to add a PR that removes flake8, it's fine with me, if we still get the same result.

**Comment by shivansh02** [comment]
Sure, will do.
Also, I wanted to discuss GSoC projects ideas with the mentors. Can you please let me know where I can get in touch?

**Comment by m3nu** [comment]
The Matrix chat mentioned in the wiki will work well. I'll try to be there more often.
