### ISSUE TITLE
GUI crashes with TypeError in translate

### ISSUE THREAD

**Issue by m0n5t3r** [borgbase/vorta#197]
**Describe the bug**
Using version 0.6.8 from pypi, the GUI crashes when trying to add a repository with

```
Traceback (most recent call last):
  File "/opt/vorta/lib/python3.6/site-packages/vorta/views/repo_add_dialog.py", line 135, in run
    self._set_status(translate(params['message']))
  File "/opt/vorta/lib/python3.6/site-packages/vorta/i18n/__init__.py", line 64, in translate
    return application.translate(*args, **kwargs)
TypeError: translate(str, str, disambiguation: str = None, n: int = -1): not enough arguments
```

When trying to initialize a new repository the stack trace is different, but it ends up in the same place.

**To Reproduce**
1. start vorta
2. open the GUI
3. try to add a repository
4. application crashes

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04, virtualenv, python 3.6 from the deadsnakes PPA

I got it working with an ugly hack:

```
    if len(args) == 1:
        return application.translate('messages', *args, **kwargs)
```

... but I guess the correct approach would be to hunt down all calls and change them to `translate('messages', <text>)`

**Comment by m3nu** [comment]
Thanks for reporting. Looks like we're translating too many things here. The messages from Borg shouldn't be translated.

**Comment by m3nu** [comment]
I went with your latter approach. While the original `QTranslator` class supports both calls, our custom debug subclass doesn't support this call. This is why you are seeing this. The custom class is already disabled after version 0.6.8

**Comment by m3nu** [comment]
After consideration, I ended up removing most of those calls.

**Comment by m3nu** [comment]
If you like, you can test the changes from [this branch](https://github.com/m3nu/vorta/tree/issue/197/excess-translations). Else I'll release it as 0.6.9 tomorrow, since this is a serious bug.

**Comment by m0n5t3r** [comment]
the branch explodes on me with `ModuleNotFoundError: No module named 'PyQt5.sip'` (might be my own system or the virtualenv contents), but I replayed the last 3 commits by hand on the code installed from pypi and all seems fine.

**Comment by m3nu** [comment]
Looks like some missing dependencies. How did you install it? It's roughly

```
$ pip uninstall vorta
$ pip install -e .
$ vorta
```

**Comment by m0n5t3r** [comment]
I recreated the virtualenv and it works fine, indeed; it was probably exploding because I ran `setup.py install` first, stopped it and installed vorta with pypi to get dependencies faster, uninstalled and ran `setup.py install` again, so the pyqt install was probably incomplete

**Comment by m3nu** [comment]
Great. So the issue doesn't occur any more?

**Comment by m0n5t3r** [comment]
yup, looks like it works fine
