### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by iamalsonothere** [borgbase/vorta#1973]
Is there a way to provide translations to various languages? I am a polyglot and would like to try translating Vorta into my native language

**Comment by m3nu** [comment]
Check here: https://vorta.borgbase.com/contributing/translations/

Let me know here after signing up with Transifex and I'll confirm you there.

**Comment by m3nu** [comment]
I think you also need to apply to the languages you want to edit in the Vorta project on Transifex. Right now I don't see anything to confirm.

**Comment by iamalsonothere** [comment]
I requested to join again

**Comment by m3nu** [comment]
Got it and confirmed!
