### ISSUE TITLE
Vorta not picking up SSH key assignment from (existing) repo advanced screen when listing archives?

### ISSUE THREAD

**Issue by wokkieman** [borgbase/vorta#1975]
### Description

When adding an existing repo, I specify the ssh key in the advanced window. The repo then shows the size and encryption (no errors). But when trying to list the archives it tells me wrong folder, no access. That indicates to me that a different ssh key is used then specified in the advanced window. When I change the ssh key from the main repo window (the field above compression) to the key used by that repo, the archives list without an issue.

Does listing archives pick up the wrong key (right = key specified in advanced in my understanding)?

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Docker

### Version of Vorta

0.9.1

### What did you install Vorta with?

Other

### Version of Borg

1.2.7

### Logs

```pytb
In Docker I can only find nginx logs. Clicking the misc tab log doesn't do anything.

I was referred here from https://github.com/borgbase/vorta-docker/issues/22 as the issue is potentially related to Vorta and not to the Docker.
```

**Comment by SAMAD101** [comment]
Can you download Vorta in your system (using pip or package manager), and try reproducing the issue? You should be able to see the logs then. That will help to track down what went wrong.
