### ISSUE TITLE
KDE 5.27 Wayland: Vorta UI Broken (transparent), not using system theme settings 

### ISSUE THREAD

**Issue by benjamindaines** [borgbase/vorta#1987]
I noticed this at the same time that the main window layout was changed.  I am running KDE 5.27 with Wayland & the Klassy theme.  However, Vorta does not seem to be respecting the theme configuration of my environment.  Instead, it is either trying to use it's own UI elements and failing or something else is going on.  

Distro is Manjaro and package is from the AUR. 

![image](https://github.com/borgbase/vorta/assets/3039460/5e0a429c-3acc-4dff-a67a-c326fb31eac8)

**Comment by benjamindaines** [comment]
The may be Klassy not having support for qt6. Rebuilding a newer version of the theme now to see if that fixes it.

**Comment by SAMAD101** [comment]
I use KDE 6.0.3 Wayland (Arch Linux) and Vorta runs fine in my system. Plasma 6 is more stable with Wayland, but I'm not really sure what could be the reason in your case.
