### ISSUE TITLE
Tray icon not visible on OS-X Mojave in Dark Mode. 

### ISSUE THREAD

**Issue by 0xErnie** [borgbase/vorta#199]
**Describe the bug**
When I start vorta the first time it seems like it is not working, nothing is happening after the start. The tray icon is not visible, since the icon is black and the background is dark grey on OS-X Mojave in Dark Mode.

The icon is left of the one showing an open box, you may have to adjust brightness or contrast to see it:
![Screenshot](https://user-images.githubusercontent.com/234937/53015094-75cb6900-344a-11e9-9f0e-37c4f66d1214.png)

**To Reproduce**
1. Enable Dark Mode in system settings.
2. Install vorta: `brew cask install vorta`
3. Start vorta
4. Look at the systems tray

**Desktop**
 - OS: OS-X Mojave 10.14.3

To me it first seemed like I just tested another broken oss backup tool with gui for mac, but after some pondering I found the "-f" parameter and then the setting for having a light icon.
Backup went trough just fine.

Might be related to ( #132 ).

**Comment by m3nu** [comment]
You're absolutely correct. We have some code that detects a dark theme, but recently split the icon and theme settings. Seems the icon setting isn't updated in that case. Let's fix that.

**Comment by m3nu** [comment]
Added a small PR to fix this.
