### ISSUE TITLE
Vorta does not accept empty password

### ISSUE THREAD

**Issue by ebeneezer** [borgbase/vorta#1995]
### Description

Neiter Vorta does accept empty password for existing repos now at creating new ones. For internal use i do not want passwords. Vorta is telling be that it validates an existing repo (and does nothing) or it tells me it had created a new repo but never leaves the creation dialog.

This is a show stopper.

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Macos Sonoma

### Version of Vorta

latest

### What did you install Vorta with?

Homebrew

### Version of Borg

latest

**Comment by shivansh02** [comment]
Sorry but for now there seems to be no way to disable encryption in Vorta.

**Comment by shivansh02** [comment]
> What if you choose Advanced > Encryption: None? Will it still need a password?

It does not. So it works as intended, and the passwords fields are now hidden if _None_ is selected to avoid confusion.
