### ISSUE TITLE
Cannot init new repository - ERROR - Connection closed by remote host. Is borg working on the server?

### ISSUE THREAD

**Issue by chodaprog** [borgbase/vorta#1997]
### Description

I’m trying to init a new repo, but keep getting this error « ERROR : Connection closed by remote host ».
I checked your website : https://docs.borgbase.com/faq/#all-connections-to-a-borgbase-repo-fail-with-an-error-immediately

if I use ssh -v [XXXXXX@XXXXXX.repo.borgbase.com](mailto:XXXXXX@XXXXXX.repo.borgbase.com), everything works like a charm, including passing the password prompt.

I’ve tried to regenerate many times the ssh key, or create new repos, without success.
My SSH pub key has been added to the « SSH keys » tab in borgbase, and full access permission granted to this very ssh key.

I’m using vorta v0.91, on a MacOS 13.6.1.

ERRORS

In Vorta
![vorta](https://github.com/borgbase/vorta/assets/19312662/424454d1-a3c9-49ea-aaa0-7c81209919c8)

Steps to reproduce 

1. Clear all SSH keys and existing repositories on borgbase.com
2. Generate new ssh key on my computer id_rsa_borg
3. Add new SSH key to borgbase.com/ssh and paste the content of id_rsa_borg.pub to the field
4. Create a new repo in borgbase.com
5. Grant full access to the newly added SSH keyto this repo
6. Copy the repo's address (format ssh://XXXXXX@XXXXXX.repo.borgbase.com/./repo)
7. In Vorta, click on the "+" to add a new repo, paste the repo's address
8. Paste a new password for the repo and stroke "Add"

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

MacOS 13.6.1

### Version of Vorta

0.91

### What did you install Vorta with?

Distribution package

### Version of Borg

1.2.7

### Logs

```pytb
2024-05-01 13:12:03,172 - vorta.keyring.abc - DEBUG - No module named 'secretstorage'
2024-05-01 13:12:03,172 - vorta.keyring.abc - DEBUG - Using VortaDarwinKeyring
2024-05-01 13:12:03,172 - vorta.borg.borg_job - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2024-05-01 13:12:03,174 - vorta.keyring.darwin - DEBUG - Retrieved password for repo ssh://XXXXXXXX@XXXXXXXX.repo.borgbase.com/./repo
2024-05-01 13:12:03,174 - vorta.borg.borg_job - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
2024-05-01 13:12:03,175 - vorta.borg.jobs_manager - DEBUG - Add job for site default
2024-05-01 13:12:03,176 - vorta.borg.jobs_manager - DEBUG - Start job on site: default
2024-05-01 13:12:03,185 - vorta.borg.borg_job - INFO - Running command /Applications/Vorta.app/Contents/Resources/borg-dir/borg.exe init --info --log-json --encryption=repokey-blake2 ssh://XXXXXXXX@XXXXXXXX.repo.borgbase.com/./repo
2024-05-01 13:12:04,761 - vorta.borg.borg_job - WARNING - Remote: ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory
2024-05-01 13:12:04,764 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
2024-05-01 13:12:04,920 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
2024-05-01 13:12:04,923 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: default

```

**Comment by spiccinini** [comment]
I am having the same issue but with flatpack in linux.
From the logs:
```
2024-05-20 21:20:40,480 - vorta.borg.borg_job - WARNING - Remote: ssh_askpass: exec(/usr/libexec/ssh-askpass): No such file or directory
2024-05-20 21:20:40,486 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?
```

Versions:
```
flatpak list
Name                               Application ID                                 Version           Branch               Installation
Vorta                              com.borgbase.Vorta                             v0.9.1            stable               user
Mesa                               org.freedesktop.Platform.GL.default            24.0.6            23.08                user
Mesa (Extra)                       org.freedesktop.Platform.GL.default            24.0.6            23.08-extra          user
Intel                              org.freedesktop.Platform.VAAPI.Intel                             23.08                user
Breeze GTK theme                   org.gtk.Gtk3theme.Breeze                       6.0.4             3.22                 user
KDE Application Platform           org.kde.Platform                                                 6.6                  user
```


The vorta installed from the archlinux packages (0.9.1-4) is working without errors with the same profile/server so it is an issue from the flatpack version in my case.

**Comment by reinoldus** [comment]
I had the same issue on ubuntu 20.04, booting the flatpak-app from the CMD gave me this:

```
2024-07-07 12:14:26,337 - vorta.borg.borg_job - INFO - Running command /app/bin/borg info --info --json --log-json ssh://xxxxxxxxxxxx/./x/xx
2024-07-07 12:14:26,574 - vorta.borg.borg_job - WARNING - Remote: Bad owner or permissions on /xxx/.ssh/config
2024-07-07 12:14:26,576 - vorta.borg.borg_job - ERROR - Connection closed by remote host. Is borg working on the server?

```

After changing the permissions on my .ssh/config to 600 it worked. It's a bit weird because the config is not really a sensitive file.

**Comment by chodaprog** [comment]
@reinoldus thank you for your answer.
I went further and addressed two issues mentionned in the debug log :

-  First, I installed the missing keyring library : `pip install secretstorage ` (my vorta was installed via pip, but same occured for dmg binary)

- Then, I addressed the ssh-askpass mentionned. Scrolling through internet, I saw someone mentionning there were issues with MacOS updates about ssh-askpass. So, I decided to install it and bind it.

 1. `sudo port install ssh-askpass`
 2. `which ssh-askpass` gave me the location of the freshly installed exec : 
 >/opt/local/bin/ssh-askpass
 3. Some investigation showed me that /usr/X11 was a symlink 
 >/usr/X11R6 -> ../private/var/select/X11 , so I went further and discovered that /private/var/select/ was empty. To bypass this execute `sudo mkdir -p /private/var/select/X11/bin` to create the missing directory
4. Then, create the symlink `sudo ln -s /opt/local/bin/ssh-askpass /usr/X11R6/bin/ssh-askpass`

So far, this solves the errors, and enables the SSH password modal to prompt after adding the repository.

But there still is an issue, now, that I'm investigating.
Vorta still throws "Unable to add your repository" on the UI, but this error is thrown in terminal

> vorta.borg.borg_job - INFO - Running command /opt/local/bin/borg info --info --json --log-json ssh://XXXXXX@XXXXXX.repo.borgbase.com/./repo
> vorta.borg.borg_job - ERROR - Local Exception
> vorta.borg.borg_job - ERROR - Traceback (most recent call last):
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/borg/archiver.py", line 5391, in main
>     exit_code = archiver.run(args)
>                 ^^^^^^^^^^^^^^^^^^
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/borg/archiver.py", line 5309, in run
>     rc = func(args)
>          ^^^^^^^^^^
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/borg/archiver.py", line 178, in wrapper
>     kwargs['manifest'], kwargs['key'] = Manifest.load(repository, compatibility)
>                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/borg/helpers/manifest.py", line 210, in load
>     open(file, 'w').close()
>     ^^^^^^^^^^^^^^^
> PermissionError: [Errno 13] Permission denied: '/Users/USER_NAME/.config/borg/security/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/tam_required'
> 
> Platform: Darw root:xnu-8796.141.3.701.17~4/RELEASE_X86_64 x86_64
> Borg: 1.4.0  Python: CPython 3.12.7 msgpack: 1.0.8 fuse: llfuse 1.5.0 [pyfuse3,llfuse]
> PID: 58234  CWD: /Users/USER_NAME
> sys.argv: ['/opt/local/bin/borg', 'info', '--info', '--json', '--log-json', 'ssh://XXXXXX@XXXXXX.repo.borgbase.com/./repo']
> SSH_ORIGINAL_COMMAND: None

So far, changing permissions on .ssh/config did not help in any way.

**Comment by Dapuva76** [comment]
I'm having the same issue - is chodaprog's post above mine the recommended fix?
