### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by tux-wclp** [borgbase/vorta#1998]
it does not work....
After the last update with Pacman Vorta does not start.

```

[gattino@cryptux ~]$ vorta
Traceback (most recent call last):
  File "/usr/bin/vorta", line 5, in <module>
    from vorta.__main__ import main
ModuleNotFoundError: No module named 'vorta'
[gattino@cryptux ~]$ 
```

**Comment by GamesTrap** [comment]
@tux-wclp I Just had the same error. A rebuild with `yay -S vorta` fixed the error for me.

**Comment by tux-wclp** [comment]
Yes!!!
I have rebuild Vorta and the problem was solved! I also launched rebuild-detector (checkrebuild -v) discovering that many other packages had broken (for example Protonvpn that as Vorta no longer starts): I have rebuild them all and everything has returned to work

**Comment by tux-wclp** [comment]
I close because the problem has been solved !!!
Thanks for your help
