### ISSUE TITLE
Missing features and small bugs

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#2]
Missing features:

Support more `borg` operations:
- [x] Pruning
- [x] Repo checking
- [ ] ~~Snapshot delete~~ Not adding this for now, since pruning does the same thing anyways.

User interface improvements:
- [ ] ~~Clear Log~~. I've reversed the order, so the newest entries are on top. I can't clear it because I need it to know when the last repo check was done. And possibly other things in the future.
- [x] different icon while backup is running
- [x] I wonder if it may be possible to have notifications? Perhaps with the options, such as only notify on error - non zero Returncode?

Bugs:
- [x] when the backup is finished, the cancel button remains enabled
- [x] Disable buttons in repo-add modal when running
- [x] on schedule view : prune checkbox has status "mixed values"/undefined each time I relaunch the app
- [x] Also Exit and then re-launch app is required for Original Size, Deduplicated Size and Compressed Size to populate.
- [x] Can't add repo after unlinking one.
- [x] Giving empty password for encrypted repo triggers password prompt.

(as reported by @mspeder and others.)

**Comment by mspeder** [comment]
Another pick from this morning :

- [ ] In schedule view the "next backup" date is not updated after the first run. Date of next backup is correctly updated in menubar though

**Comment by m3nu** [comment]
Good progress in fixing the bugs and missing features. I may also broke some other things.

Will do some manual testing today and add new automated tests. Then release 0.3. 

Summary of changes:

- move each `borg` command into own class to organize pre-/post-processing and events.
- implement pruning, checking, shapshot refresh.
- run multiple `borg` commands when necessary. (to get all snapshots and size details, to do pruning and checking for background backups)
- move pruning options to snapshot tab.
- tray icon changes color when backup is in progress (design could be improved)

Bugs I noticed and will look into:
- [ ] for developer installs, not all requirements are installed. May be a limitation of specifying them in `setup.cfg`
- [ ] `tox` seems to run on an old version

**Comment by m3nu** [comment]
Next release 0.2.9 is up @mspeder . Lots of rewrites, so there will be new bugs. But hopefully most features are there now. https://github.com/borgbase/vorta/releases

**Comment by adamluk** [comment]
Couple of additional bugs:

1) When Vorta window is maximised it takes up small area of screen with large black border surrounding it. No way to then minimise or exit.

2) Cannot refresh/remove WiFi networks under Schedule > Network, even if these are subsequently removed from Network settings on Mac OS and/or Keychain.

**Comment by m3nu** [comment]
Thanks for reporting, @adamluk . There is no code to remove Wifis for for now. They are only added when missing and sorted by last connection date. So if you remove them from macOS, they will move lower and lower in the list over time. But it could be useful to re-sync the list, I guess. Let's file this under low-prio.

Regarding the maximize-bug, that's quite annoying. Maybe there is a way to disable it altogether. As first step I can change the min/max window sizes a bit.

**Comment by m3nu** [comment]
Notifications implemented. They will trigger:

- when pre-backup check fails. E.g. repo or folder missing.
- when the backup returns a non-0 exit code
- when changing the scheduler (for testing)

**Comment by m3nu** [comment]
All fixed here. Feel free to open a new issue for new bugs.

I'll also add a "feature brainstorming" issue.
