### ISSUE TITLE
"creation date" of a restored file

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#2001]
Vorta 0.8.12
Borg 1.2.4

Linux: In thunar I have the column Creation date. 

When I restore a file with vorta, the "creation date" of the restored file has the date and time when I have executed the restore process. This means the creation date does change.

I would like that the "creation date" does remain unchanged. 

#### Requested Solution
When borg/vorta makes the backup it should save the creation date of each file in a database. When the user restores a file, then borg/vorta can take the creation date from this database and is able also to restore the creation date.

**Comment by shivansh02** [comment]
I don't think creation time can be modified like that.
Pls see [https://unix.stackexchange.com/a/336300](https://unix.stackexchange.com/a/336300)

**Comment by Golddouble** [comment]
Thank you for this comment.

Mabe you are right. But on the same website I have found this statement:
![grafik](https://github.com/user-attachments/assets/5757141e-e05b-490a-ab7e-6f6eb80bce0e)


https://unix.stackexchange.com/questions/336298/how-to-change-files-creation-time-touch-changes-only-modified-time/336300#336300
