### ISSUE TITLE
macOS Sonoma 14.5 (23F79) Vorta started Hangs for few minutes

### ISSUE THREAD

**Issue by wakawakaaa** [borgbase/vorta#2009]
#### Description

From last few weeks after update of macOS to Sonoma 14.5, Vorta started freezing (GUI hanging for few minutes), seems that backup still working, but only GUI hangs. 

Please fix this issue. Thanks.

I _was_/_wasn't_ able to reproduce the issue.

#### Environment

- OS: macOS Sonoma 14.5 (23F79)
- Vorta version: 0.9.1
- Installed from: `brew install borgbackup`
- Borg version: 1.2.8

#### Logs

I have checked logs from last few weeks there is no issue logs, only GUI hangs. 

```
*paste logs here*
```

**Comment by shivansh02** [comment]
Have you noticed any pattern or specific situation that triggers the freezing?

**Comment by wakawakaaa** [comment]
Yes, pattern might be that I have updated M1 Mac to macOS Sonoma 14.5 (23F79). and Other can be update of default updates from brew upgrade. which, updated I think also Python stuff. 

I hope it helps to debug the issue. thanks
