### ISSUE TITLE
Exclude-if-present UI

### ISSUE THREAD

**Issue by shivansh02** [borgbase/vorta#2012]
I'm working on reinstating the much-requested Exclude-if-present functionality.
This is the UI I have drafted as per suggestions from @m3nu. I'd love to hear your inputs on it.

![excludeifpresent-ui1](https://github.com/borgbase/vorta/assets/89853707/08d33077-638f-40a3-82a1-9fae07bb57f5)

**Comment by shivansh02** [comment]
Moved to #1863

**Comment by NovaViper** [comment]
Hey @shivansh02 You linked back to the original issue and not the new PR
