### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by es2337** [borgbase/vorta#2019]
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/vorta/views/schedule_tab.py", line 92, in on_scheduler_change
    self.app.scheduler.set_timer_for_profile(profile.id)
  File "/usr/lib/python3/dist-packages/vorta/scheduler.py", line 111, in set_timer_for_profile
    timer.setInterval(int(timer_ms))
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647

running Ubuntu 22.04.4 LTS and installed vorta via apt.

just created a third profile to backup files already captured by one of the other 2 but to backup in a different location and with more frequency.
when I launch vorta it taken to the new profile and get this error when I try to switch to my other 2 profiles.
when i switch i can see the corresponding screen that i was in my new third profile, and my archives still show, but vorta freezes and ubuntu asks to force quit.

unsure why I am getting this error.

I also changed the backup frequency of the new and one of the 2 older profiles recently.

**Comment by shivansh02** [comment]
The timer integer overflowed. What is your least frequent backup schedule across all 3 profiles?

**Comment by es2337** [comment]
> @es2337 This error was already fixed a long time ago, are you using the latest Vorta version?
 believe I set it to 2 weeks 
other should have been 2 days and 125min.


Just check it, they are all set to 125, but 12min, 125 days, 125 weeks respectively.
I'm positive i didn't set it to that.


running vorta 0.8.3

**Comment by shivansh02** [comment]
> Just check it, they are all set to 125, but 12min, 125 days, 125 weeks respectively.
> I'm positive i didn't set it to that.

That's odd. While I can't think of a reason why this discrepancy would occur, upgrading to a newer release should solve the freezing issue. The fix was released in v0.8.4.

**Comment by es2337** [comment]
Thanks, I'll have a look into why apt is saying i'm on the latest version.

**Comment by es2337** [comment]
I ended up nuking it and installing from flatpack.
could see an easy way to recover my profiles so just rebuilt based off my backups.

lesson learned to keep backups of everything, including profiles XD
