### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rd-sebastian-blaszczok** [borgbase/vorta#2023]
Since we want to use the software in a company, additional features like CLI-based import-export of configurations and one-click backup restoration would be great. Additionally, it would be fantastic if the settings.db could be stored in the system folder (/Library/...), rather than in the user folder.

Settings.db in System directory /Library...
Import/Export with cli
OneDrive integration

**Comment by m3nu** [comment]
You are welcome to make a pull request. Though any new feature should be relevant to a critical mass of users and not just yourself and your staff.
