### ISSUE TITLE
DB error when adding new profile

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#2024]
### Description

We have a bug in the current master branch that's blocking an important feature: When adding a new profile, there is an error related to a DB constraint (see logs).

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

1. Select `+` > *New profile*
2. Then enter any name and confirm
3. Error will appear

### OS

macOS

### Version of Vorta

master branch

### What did you install Vorta with?

Pip

### Logs

```pytb
sqlite3.IntegrityError: NOT NULL constraint failed: backupprofilemodel.allow_new_networks

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/manu/Workspace/vorta/src/vorta/views/profile_add_edit_dialog.py", line 39, in save
    new_profile.save()
```

**Comment by shivansh02** [comment]
@m3nu I couldn't reproduce this, did not get any error. Also, we don't have any column called `allow_new_networks` in BackupProfileModel?

**Comment by m3nu** [comment]
Never mind then. Maybe it's a leftover in my local test DB. I'll go and edit it manually.
