### ISSUE TITLE
Archive Extraction not working

### ISSUE THREAD

**Issue by trinilopez99** [borgbase/vorta#2030]
### Description

I encountered a bug. On MacOS I am unable to extract archives. There is no window prompt to ask me where to save it. It just says "Done getting archive content". Mounting with fuse works fine, but extraction is broken.

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

MacOS Sonoma 14.5

### Version of Vorta

0.9.1

### What did you install Vorta with?

Homebrew

### Version of Borg

1.2.8

### Logs

```pytb
I do not have a "Misc Tab" I only have repositories, sources, schedule, archives. I can't see anywhere to access the logs.
```

**Comment by m3nu** [comment]
The logs are now in *About/Settings*. We'll update the bug template shortly.

For the issue, we'll need more details. Maybe nothing was selected to extract?

**Comment by trinilopez99** [comment]
Definitely selected an archive. I've decided to use another backup system, this interface is not stable for me. Thank you.

**Comment by wakawakaaa** [comment]
@trinilopez99 which other backup system you are using? as I have same issue vorta is very unstable on macos

**Comment by trinilopez99** [comment]
I'm using duplicati for my macs
