### ISSUE TITLE
on MacOS Extract don't work.

### ISSUE THREAD

**Issue by wakawakaaa** [borgbase/vorta#2039]
### Description

on MacOS when click on Extract, Vorta hangs.

I think, on MacOS when click on Extract, Vorta tries to fetch whole borg repo, instead just showing list of file, which leads to Vorta hangs and become unresponsive. after that it can not open a Dialogue to download the needed files. 

Borg is installed without macfuse on MacOS.

by the way this functionality on Linux Mint works fine. 

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

macOS Sonoma 14.5 (23F79)

### Version of Vorta

0.9.1

### What did you install Vorta with?

Homebrew

### Version of Borg

1.2.8

**Comment by m3nu** [comment]
Duplicate of #2094
