### ISSUE TITLE
Only offer repokey-blake2 support to >=1.1.4 borg versions

### ISSUE THREAD

**Issue by varac** [borgbase/vorta#205]
**Describe the bug**

I had borg 1.0.x installed on my laptop. I tried to initialize a repo, and vorta defaults to `repokey-blake2`.
Initialising failed without any meaningful feedback (see #108 and #162). Looking at the console I found that `borg init` complained about `repokey-blake2` as encryption mode.
After upgrading borg to 1.1.x this was fixed.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
- vorta 0.6.10, Python 3.6.7

**Comment by m3nu** [comment]
I agree that the error message should be more meaningful, but keeping tabs of `borg` versions and its features will be a lot of extra code for very little temporary benefit.

For macOS a recent binary is already included. For installs via `pip`, we could set a high enough Borg version as dependency.

**Comment by ThomasWaldmann** [comment]
`borgbackup >= 1.1.4` (earlier 1.1.x had severe issues)

**Comment by ThomasWaldmann** [comment]
related: #120

**Comment by m3nu** [comment]
How about adding it as optional dependency and giving that as default in the docs? E.g. "Install Vorta and Borg Backup together":

`$ pip install vorta[borg]`
 
And then "If you manage your own version of Borg Backup, use just 

`$ pip install vorta`

Extra requirements can be defined in `setup.cfg` like this (untested):

```
[options.extras_require]
borg = borgbackup>=1.1.4
```

**Comment by ThomasWaldmann** [comment]
Sure you wanted to close this?

vorta determines the borg version now, but it does not actually check it.

**Comment by m3nu** [comment]
Determining the version is the first step. Next we can work around different versions. I'm imagining some abstractions for that to avoid checking the version in too many places. Maybe a list of supported features (`repokey-blake2`) based on the version.

Or were you suggesting to blacklist all Borg versions <1.1.4?

**Comment by ThomasWaldmann** [comment]
Not sure how many users still use 1.0.x.

My point was just that the issue this user (see top post) had is not fixed.

**Comment by m3nu** [comment]
Right. When renaming issues, I should keep the original issue. Will add that right away.

**Comment by m3nu** [comment]
Added a helper class for this. Can be used to check for other features in the future or customize Borg commands based on version.

Would love your feedback if this is a good way to implement this @ThomasWaldmann .
