### ISSUE TITLE
settings/about icon not correct color for dark mode

### ISSUE THREAD

**Issue by gzuaps** [borgbase/vorta#2062]
### Description

In interface, settings/about icon (settings_wheel.svg?) is not the correct color for dark mode.

![Screenshot_20240821_130024](https://github.com/user-attachments/assets/dc50ee86-11fc-473e-ace8-7023b27b87e8)

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

fedora 40 plasma 6.1.4 wayland

### Version of Vorta

0.9.1

### What did you install Vorta with?

Other

### Version of Borg

1.2.8

**Comment by m3nu** [comment]
I believe this was already fixed in the master branch.

**Comment by gzuaps** [comment]
Thanks, yes that issue has been fixed in master.
