### ISSUE TITLE
Newly added sources are only visible in mount after restarting Vorta

### ISSUE THREAD

**Issue by echox** [borgbase/vorta#2072]
### Description

Under Macos I've added multiple new source folders to a backup job.
After the backup I've mounted the archive multiple times but wasn't able to see the previously added folders.
Still, the size of the backup increased and I tried mount/unmount multiple times on all archives.

The folders only became visible after restarting Vorta itself. Not sure if this is some caching problem in combination with the fusefs.

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

Macos 14.4.1 (23E224)

### Version of Vorta

0.9.1

### What did you install Vorta with?

Homebrew

### Version of Borg

1.4.0

**Comment by m3nu** [comment]
Doesn't sound like a Vorta issue, since mounting only runs a Borg command.
