### ISSUE TITLE
Vorta 0.10 Feedback

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#2077]
This is to discuss the next release:

https://github.com/borgbase/vorta/releases/tag/v0.10.0-beta1

**Comment by goebbe** [comment]
What would be the best way to install/ test Vorta 0.10 on Linux?  
Is there an easy way to pip install a relase candidate in parallel to the stable release?

**Comment by m3nu** [comment]
Best would be to install the current master branch from Github using pip:

https://vorta.borgbase.com/contributing/#testing-the-current-development-version

**Comment by goebbe** [comment]
Thank you for the pointer! So I would 
- Quit the Vorta (stable) instance, currently running on this computer
- create and _activate_ a venv for the test and install Vorta inside the venv: 
`pip install git+https://github.com/borgbase/vorta#egg=vorta-dev`
- After testing, I would just _deactivate_ this venv and could restart my old stable Vorta. 

Do I have to take extra precautions for the Vorta **config** files, in .local/share/Vorta ? 
Or will this procedure automatically use a separate config folder? (I am worried since I have the stable Version of Vorta running already, and I don't want to damage my current setup.)

@Hofer-Julian: I wish there would be a dev-channel for Vorta on flathub. This would make testing new Vorta versions on Linux easier (and probably saver)

**Comment by sten0** [comment]
I uploaded 0.10-beta1 to Debian experimental on 31 Oct.  Users of unstable/sid and probably testing/trixie can manually install it for testing.

@m3nu In Debian, our Release Team has also reprimanded me (https://bugs.debian.org/1086524) about flaky tests in 0.9.1, and given #2117 I think that Vorta may have one or more races.  Obviously we'll want to use the 0.10 series as a base, so I need to know if users can reasonably expect to rely on beta1 for day to day use.  Will the final release happen before February 2025?  I'd be happy to also start tracking snapshots of the master branch in Debian experimental if that would be useful.  Oh yeah, and Python 3.13 is around the corner...  I'll start testing Vorta with it asap.

**Comment by sten0** [comment]
@goebbe wrote
> Do I have to take extra precautions for the Vorta **config** files, in .local/share/Vorta ? Or will this procedure automatically use a separate config folder? (I am worried since I have the stable Version of Vorta running already, and I don't want to damage my current setup.)

Aha, good thinking!  To the best of my knowledge Vorta only uses a single file for all versions installed: .local/share/Vorta/settings.db.

**Comment by m3nu** [comment]
I haven't seen test failures in Github for a long time. Last change I made was to increase the timeout for their macos tests, since they became very slow for some reason.

0.10 should be ready soon. Currently waiting for some feedback after putting it in our monthly newsletter. Before the end of the year for sure.

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian: I wish there would be a dev-channel for Vorta on flathub. This would make testing new Vorta versions on Linux easier (and probably saver)

@goebbe I missed your message earlier. That is actually possible. All one has to do is to push to the `beta` branch [here](https://github.com/flathub/com.borgbase.Vorta) and it will be built at `flathub-beta`

**Comment by goebbe** [comment]
> @goebbe I missed your message earlier. That is actually possible. All one has to do is to push to the `beta` branch [here](https://github.com/flathub/com.borgbase.Vorta) and it will be built at `flathub-beta`

Would you mind pushing the current dev to flathub-beta? It would certainly be convenient for testing.

**Comment by m3nu** [comment]
I don't know how to do that, but will soon release 0.10, since much of the feedback and pending PR are already taken care of.

**Comment by Hofer-Julian** [comment]
I don't really have time at the moment. I am happy to review PRs though

**Comment by m3nu** [comment]
Thanks for all the feedback. Releasing 0.10 now and saw someone already updated the Flathub dependency.
