### ISSUE TITLE
Ability to schedule a Borg compact

### ISSUE THREAD

**Issue by P-Jay357** [borgbase/vorta#2082]
#### The problem
I would like to compact my backup every month (for example). Currently, I would have to do this manually (for a local repository which is on an external drive).

#### Requested Solution
Have a similar option for scheduling compacting repos like we have with Backup schedule and Validation.

**Comment by goebbe** [comment]
Apparently this has now been implemented and merged. 
https://github.com/borgbase/vorta/pull/1981

**Comment by JourneyOver** [comment]
Is there any idea on when it might possibly be coming to an actual release with this however? :o

**Comment by goebbe** [comment]
This has been merged at the end of June. So I guess this will be part of the next release. 

Please test the current release candidate and provide feedback: https://github.com/borgbase/vorta/issues/2077

**Comment by JourneyOver** [comment]
That seems to just be for MacOS, I'm running linux (ubuntu)

**Comment by goebbe** [comment]
> That seems to just be for MacOS, I'm running linux (ubuntu)
Me too! I guess we have to install the rc manually - however, I am not sure what would be the best way to install Vorta release candidate in parallel to the stable version.   
I just put a question to the referred issue and asked about howto test on Linux.

**Comment by goebbe** [comment]
This is included in the latest release, i.e. Vorta 0.10.  Thanks to the developers! 
Now, by default, "compact" will run every 3 weeks. (this is configurable)

**Comment by m3nu** [comment]
Thanks for the reminder, @goebbe . So time to close this.

Fixed by @shivansh02 in #1981
