### ISSUE TITLE
pkg-resources deprecated for importlib_resources and importlib_metadata

### ISSUE THREAD

**Issue by sten0** [borgbase/vorta#2090]
Hi,

I recently received a report from that

> Use of pkg_resources is deprecated in favor of importlib.resources,
importlib.metadata and their backports (importlib_resources, importlib_metadata).
Some useful APIs are also provided by packaging (e.g. requirements and version
parsing). Users should refrain from new usage of pkg_resources and should work
to port to importlib-based solutions.
>
>Python 3.12 in unstable provides both importlib_resources and
importlib_metadata, so no additional dependencies on those packages are needed.

https://bugs.debian.org/1083985

**Comment by m3nu** [comment]
Added a PR for this.

Looks like we now depend on the [packaging](https://github.com/pypa/packaging) package for the version comparisons.
