### ISSUE TITLE
validation and compaction interval not changeable

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#2101]
### Description

See picture:
- the compaction interval is disabled, so one can not change the value of it. i did not touch anything there, so this is a bug: it should be changeable.
- the validation interval is enabled, so one can change the value of it. this is because i toggled the checkmark to off and to on again to get it into that state. this is a workaround for this bug.

<img width="858" alt="Screenshot 2024-10-18 at 19 45 12" src="https://github.com/user-attachments/assets/36d99ff8-f252-42ce-a417-68d60b7587ca">

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

macOS 15

### Version of Vorta

0.10.0 beta1

### What did you install Vorta with?

Binary

### Version of Borg

1.4.0

**Comment by m3nu** [comment]
Can't reproduce this one either. 😬 Must be some specific condition.

<img width="372" alt="Screenshot 2024-10-18 at 19 20 57" src="https://github.com/user-attachments/assets/7e993be1-20f8-41a2-a0ad-f3cf0c02ed30">

**Comment by ThomasWaldmann** [comment]
I suspect this is because of a yet missing setting in my config. Once you touch/toggle it, the settings gets written/initialized and from that on it is ok.

But it should be also ok when upgrading from an older vorta that did not have that setting yet.

**Comment by m3nu** [comment]
OK. Will check if there is any dependency on default settings.

**Comment by ThomasWaldmann** [comment]
Interesting. I made a backup, maybe also restarted vorta and now I get this again:

<img width="858" alt="Screenshot 2024-10-18 at 21 29 31" src="https://github.com/user-attachments/assets/3de080b1-ea8c-4a0c-bb3d-8e936f2fb3f1">

So the value selection is disabled, again. So guess that does not confirm my theory from previous post.

**Comment by ThomasWaldmann** [comment]
I can also reproduce this for vorta built from master branch: after starting vorta, the values are not enabled.

**Comment by ThomasWaldmann** [comment]
I think in `SchedulePage`, `populate_from_profile` needs to be called **after** the connections are set up.

**Comment by m3nu** [comment]
That's possible. Our GSoC student did some refactoring in this tab to split it into multiple components. Wouldn't be surprised to see a small bug here and there.

**Comment by m3nu** [comment]
Added a PR for this. Does just moving the `populate_from_profile()` fix it?
