### ISSUE TITLE
Development version

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#211]
Maybe it should be included at the beginning of the readme that vorta is currently under heavy development and maybe shouldn't be trusted with important tasks yet?

While vorta runs quite stable (at least for me) the standards for something as important as backups are probably higher.

**Comment by m3nu** [comment]
All the important stuff is done by Borg so I don't worry too much. Most terrible bugs will just crash the interface.

**Comment by Hofer-Julian** [comment]
Well there are the reoccurring tasks right?

**Comment by m3nu** [comment]
If you insist, please add your sentence.

**Comment by Hofer-Julian** [comment]
I do not insist, I only wanted to know how you feel about it. :) 

One counter argument is of course that people might be put off by a disclaimer or think vorta is not usable at all.

**Comment by ThomasWaldmann** [comment]
In general (that is not limited to vorta or borg), people should be advised to positively make sure their backups work. That is at least checking the logs carefully and better repo checking and checking if restores work.

As far as vorta is concerned, the part with checking the logs could be improved, but we already have a ticket for that.

**Comment by Hofer-Julian** [comment]
@ThomasWaldmann like a windows that is opened the first time vorta is started and advises to follow this practise?

**Comment by ThomasWaldmann** [comment]
not sure if it needs to jump at people like this.

**Comment by Hofer-Julian** [comment]
I see
