### ISSUE TITLE
Flatpak: KDE Platform EOL

### ISSUE THREAD

**Issue by fkumro** [borgbase/vorta#2118]
### Description

While updating `vorta` via flatpak, a message is displayed indicating that the runtime used by Vorta is EOL.

```
Info: runtime org.kde.Platform branch 6.6 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   com.borgbase.Vorta
```

### Reproduction

- [X] I tried to reproduce the issue.
- [X] I was able to reproduce the issue.

### OS

Pop!_OS 22.04

### Version of Vorta

0.9.1

### What did you install Vorta with?

Flatpak

### Version of Borg

1.4.0

### Logs

```pytb
Info: runtime org.kde.Platform branch 6.6 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   com.borgbase.Vorta
```

**Comment by m3nu** [comment]
From what I see, this version was already increased here: https://github.com/flathub/com.borgbase.Vorta/blob/master/com.borgbase.Vorta.json
