### ISSUE TITLE
Consider changing Vorta's default tray icon to white/grey on GTK systems

### ISSUE THREAD

**Issue by evertonstz** [borgbase/vorta#212]
[Gnome recently reverted their transparent topbar to the old black bar again](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/376), Vorta's tray icon is already hard to see if the user uses a dark wallpaper, after the reversion the icon will completely blend with the bar making it invisible in all default Gnome systems.

A solution would be adding a white version of the icon as default, at least for GTK systems.

An alternative solution would be to use a grey icon as default to avoid a case of invisible icon on the first launch, preventing user's confusion and also including other DE's that might use a light theme by default.

**Comment by m3nu** [comment]
We already have [a function to detect dark mode](https://github.com/borgbase/vorta/blob/master/src/vorta/utils.py#L212). But just for macOS currently. If you know how to get the theme color in GTK, we can simply add it there.

**Comment by evertonstz** [comment]
> We already have [a function to detect dark mode](https://github.com/borgbase/vorta/blob/master/src/vorta/utils.py#L212). But just for macOS currently. If you know how to get the theme color in GTK, we can simply add it there.

In Gnome the top bar color isn't affected by the dark mode as it's not themed with GTK, it's always black with a little bit of transparency (current release) or solid black (next release). Unofficial themes for the Gnome-Shell can change the top bar's color, but they're hacks since Gnome doesn't have an API for themes.

Other DEs use GTK for theming their bar (xfce do it if my memory isn't failing on me). The problem is that there's no way to detect if a dark or white is being used on those DEs as Gnome doesn't support it. For the system a dark theme is just another theme with custom colors, there's nothing that differentiate it from a theme with light colors appart from the color codes inside the theme.

Anyways, the only solutions I can think are (first one is the perfect solution, second one is the fast one):

- Code an extension for the Gnome Shell that do what the legacy tray icon does, detect if the user is using Gnome Shell and disable the legacy tray icon if True. Change the legacy tray icon to blue, red or make one with dropshadow, etc. PROS: will handle custom themes on gome shell, will work with any distro using gnome shell doesn't matter how customized it is. It'll work on virtually all DEs as they don't use such colors in their bars as the use icon for those will be the new legacy one. CONS: more code to make.

- Default the icon to white on linux. PROS: it should work right for most people (Ubuntu, Fedora and people using any distro with vanilla Gnome 3). CONS: won't handle custom themes automatically on gnome shell, might become invisible on lesser used DEs.

**Comment by Hofer-Julian** [comment]
+1 for the second option (if @evertonstz meant to say default to white on Gnome)

**Comment by m3nu** [comment]
Possible to detect the Gnome version? Would it make sense to make it black above some specific version?

**Comment by Hofer-Julian** [comment]
@m3nu what do you want to make black?

**Comment by m3nu** [comment]
To report a black theme and then use a white icon. Should have been more careful with wording.

**Comment by Hofer-Julian** [comment]
I think checking Gnome-version does not make a lot of sense, because even before the change the default for the topbar was black (it was just a little transparent) :)

**Comment by m3nu** [comment]
Right. So detect if it's GNOME and then report black theme and use white icon?

**Comment by Hofer-Julian** [comment]
Yes!

**Comment by evertonstz** [comment]
> Right. So detect if it's GNOME and then report black theme and use white icon?

Yes (2)

**Comment by LinuxOnTheDesktop** [comment]
I have Vorta 0.6.17 running on Linux Mint 19.1 Cinnamon. I have a dark theme. My Vorta icon looks like this, which is to say, a bit squashed and with insufficient stand-out from the background:

![image](https://user-images.githubusercontent.com/47056543/56350812-889cb880-61c3-11e9-8749-470870e92ebe.png)

So, does the commit mentioned above work only for Gnome?

**Comment by m3nu** [comment]
Have you tried changing the setting to use the light icon under Misc?

There is some auto-detection for dark themes, but it doesn't work for all environments. Feel free to add yours.

**Comment by LinuxOnTheDesktop** [comment]
As I said in my edit: yes, I did, and that solves the colour problem (albeit not automatically) but does not solve the 'squash' problem.
