### ISSUE TITLE
v0.10.0 binary no longer available for intel mac

### ISSUE THREAD

**Issue by silverfoxdoc** [borgbase/vorta#2124]
Vorta updated today but the binary which it has updated to is a pure apple silicon binary, which obviously does not work on intel apple macs.

Please can this be changed back to a universal binary

![Screenshot 2024-11-10 at 14 07 19](https://github.com/user-attachments/assets/6905fa4b-3f2a-4765-b7c8-16df677c33fc)

**Comment by m3nu** [comment]
On it!

**Comment by m3nu** [comment]
Here an Intel build: https://github.com/borgbase/vorta/releases/tag/v0.10.0
