### ISSUE TITLE
appdata regression in 0.10.0

### ISSUE THREAD

**Issue by sten0** [borgbase/vorta#2125]
Hi, 

d5cb1b8fd352 introduced a regression here: 
 https://github.com/borgbase/vorta/commit/d5cb1b8fd352e3554457b1f26ab2e3791a046947#diff-4afe8b66890694ecad66dcb4934cd7a7e5b817cb7149ecf54fc897c759a836d5R47

```
appstreamcli validate-tree ./
com.borgbase.Vorta.appdata.xml
  E: com.borgbase.Vorta:47: description-para-markup-invalid a

✘ Validation failed: errors: 1, pedantic: 5
```

caused by

```xml
<p>See <a href="https://github.com/borgbase/vorta/releases">Github</a>
            for detailed release notes.
        </p>
```
```
description-para-markup-invalid #
Severity: error

This description paragraph contains invalid markup. Currently, only <em/> and <code/> are permitted.
```
(https://freedesktop.org/software/appstream/docs/chap-Validation.html)

**Comment by m3nu** [comment]
Oops. Thanks for the hint. This was well-meaning. Added a validation for this to GH Actions.

**Comment by sten0** [comment]
You're welcome, and thanks for the quick fix
