### ISSUE TITLE
consistent naming of arm & intel binaries to aid with homebrew cask file

### ISSUE THREAD

**Issue by silverfoxdoc** [borgbase/vorta#2128]
thanks for providing intel binary.

Is it possible to make the names consistent between the two different versions?

Had a crack at updating homebrew cask file to download respective version depending on architecture. I am no expert but it seems difficult to stick to their style guidelines with the current names as intel version does not have "v" in it making it difficult to generalise in the way they want.

Could they be named:

Vorta-v0.10.0-intel.dmg
Vorta-v0.10.0-arm.dmg

Thanks

**Comment by m3nu** [comment]
Done. Thanks for the feedback!
