### ISSUE TITLE
After renaming my profile "test" to "mybackup", the "original size" has doubled

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#214]
![grafik](https://user-images.githubusercontent.com/1151915/53687934-baed7600-3d3b-11e9-8b96-429e687c3d2d.png)

* Before renaming, the "Ursprüngliche Größe" was 1,2 TB.
* After renaming, it says "2,4 TB"

**Comment by m3nu** [comment]
I guess a new archive was added in the meanwhile. Once you have a few dozen archives, the first line will be even larger. This is just how Borg calculates the size: it sums up all archives and then gives a deduplicated and compressed files for all the files in the repo.

I was wondering about this as well. As a user I would probably expect the total size of all files of the latest archive, no matter if they already existed. I guess this would skip other important information, like compression and dedupe across multiple archives.

We can probably add a tooltip or note in brackets to make this clearer. I'm not aware of any way to get only the size of the last archive. Could be very expensive computationally.

**Comment by m3nu** [comment]
Closing since the question was answered. Feel free to reopen if there is a way to improve the display with the data we have.
