### ISSUE TITLE
Autoupdate on intel mac downloads arm version

### ISSUE THREAD

**Issue by silverfoxdoc** [borgbase/vorta#2165]
### Description

Just did autoupdate from the notification from within vorta from 10.1 >> 10.2 and it has updated to the apple silicon arm version not the intel version and so won't launch

### Reproduction

- [X] I tried to reproduce the issue.
- [ ] I was able to reproduce the issue.

### OS

MacOS 15.1.1 (Intel)

### Version of Vorta

10.1

### What did you install Vorta with?

Homebrew

### Version of Borg

1.4.0

**Comment by m3nu** [comment]
#2130
