### ISSUE TITLE
[Bug] When "Extract" cannot access a backup archiv, stop and show the error message permanently

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#218]
Previously I reported https://github.com/borgbase/vorta/issues/215 . In my logfile I see
```
2019-03-03 09:11:39,929 - vorta.borg.borg_thread 
- ERROR - Repository /mnt/nas/borgbackup does not exist.
```

however, the Error message is shown only for milliseconds in the Vorta GUI.

I suggest to show error/s **permanently** in the GUI, and in the case of "Extract" do not shown "Done" but "Failed" or "Action failed with error: xxxxx".

**Comment by m3nu** [comment]
Already covered in #108.
