### ISSUE TITLE
Can't open web links within Vorta

### ISSUE THREAD

**Issue by adamluk** [borgbase/vorta#22]
Hopefully an easy one to fix :)

The three web links below are not working when clicked - I can only right click for 'Copy Link Location':

**Sources**
![screenshot 2018-11-20 at 16 08 33](https://user-images.githubusercontent.com/9057461/48786588-12149100-ecdf-11e8-879b-8204fefe6170.png)

**Snapshots**
![screenshot 2018-11-20 at 16 08 45](https://user-images.githubusercontent.com/9057461/48786603-16d94500-ecdf-11e8-8143-443fbc33142b.png)

This web link below is working correctly when clicked and opens in a new tab in Safari:

**Repository**
![screenshot 2018-11-20 at 16 08 02](https://user-images.githubusercontent.com/9057461/48786455-cfeb4f80-ecde-11e8-8d5b-e872d5ebc8b8.png)

**Comment by m3nu** [comment]
I couldn't reproduce this in a fresh guest account. :-(

**Comment by m3nu** [comment]
Correction. Happens to me as well now. Will find out when exactly.

**Comment by m3nu** [comment]
Hope this fixes it. There was a setting to enable external links.

**Comment by adamluk** [comment]
On 0.4.3 now 👍 

The link below is behaving as before and will not open, all others are now fixed :)

![screenshot 2018-11-21 at 10 02 50](https://user-images.githubusercontent.com/9057461/48834117-e17f3680-ed74-11e8-8854-a1b35370afb6.png)

**Comment by m3nu** [comment]
Great. I forgot that one linke. Just changed it.
