### ISSUE TITLE
Issue with displaying directories under root in Extract dialog

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#226]
I made a fresh backup using these rules:

![grafik](https://user-images.githubusercontent.com/1151915/53732258-a913ec00-3e7d-11e9-8861-9421e50b509b.png)

clicking on "Extrahieren" results in a wrong display
with an "empty" top level directory name...
![grafik](https://user-images.githubusercontent.com/1151915/53732346-f6905900-3e7d-11e9-9637-332bd08bfc72.png)

... wherein again subfolders (etc, work) live:
![grafik](https://user-images.githubusercontent.com/1151915/53732370-0740cf00-3e7e-11e9-8ac2-752e043619f5.png)

**Comment by m3nu** [comment]
Thanks for reporting. I can reproduce the issue. Will look into it when time permits. Until then you can also use the Mount-feature to restore backups.

**Comment by frenkel** [comment]
The extract feature works fine, as long as you ignore the item at the root that doesn't have a name.

**Comment by m3nu** [comment]
This should be fixed by #883. Please let us know if the issue still occurs in the current `master` branch on Github.

Here more on testing the current pre-release version: https://github.com/borgbase/vorta/discussions/895
