### ISSUE TITLE
Autostart on Linux Mint not Working

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#227]
My Vorta is configured to automatically start, but this does not work (icon is not in the tray).

![grafik](https://user-images.githubusercontent.com/1151915/53842163-ffc51700-3f9e-11e9-8b17-cf7f9bf47619.png)

* Linuxmint 19.1 appears to be set up for starting Vorta:
![grafik](https://user-images.githubusercontent.com/1151915/53842284-4e72b100-3f9f-11e9-8fcf-023884484961.png)

**Comment by m3nu** [comment]
Autostart on Linux is a rather new feature, which was generously implemented by @Hofer-Julian. Myself I mainly look after the macOS-specific features (like the autostart there).

If you use it and know how to improve it, it would be great to get a Pull Request on it. I guess due to the heterogeneity of the ecosystem autostart on Linux is not easy to get right. But the more people contribute the more we can learn and improve it.

**Comment by Hofer-Julian** [comment]
@Wikinaut which version of vorta do you use?

**Comment by Wikinaut** [comment]
@Hofer-Julian @m3nu removed the version info ```0.6.10``` which I placed into the title
![grafik](https://user-images.githubusercontent.com/1151915/53867257-c074e580-3ff3-11e9-9f52-b3ea9433c150.png)

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian @m3nu removed the version info `0.6.10` which I placed into the title
> ![grafik](https://user-images.githubusercontent.com/1151915/53867257-c074e580-3ff3-11e9-9f52-b3ea9433c150.png)

Okay!

Did you try to turn autostart off and on again (in the settings of vorta)?

**Comment by Wikinaut** [comment]
@Hofer-Julian Yes

**Comment by Hofer-Julian** [comment]
Is vorta in your PATH?
Or to put it in another way: what happens when you open the terminal and execute `$ vorta` ?

**Comment by Wikinaut** [comment]
@Hofer-Julian starting from comandline works.

**Comment by Wikinaut** [comment]
and I have 
![grafik](https://user-images.githubusercontent.com/1151915/54031990-a5030980-41b0-11e9-90b2-c91a27b867df.png)


I will now set a startup delay of some seconds and report here later, whether that works.

**Comment by Wikinaut** [comment]
Sorry. I think the path is simply wrong, must be /home/myuser/.local/bin/vorta . Should work then.

**Comment by Wikinaut** [comment]
@Hofer-Julian I confirm, that that Autostart is working when I manually set up ```/home/myuser/.local/bin/vorta```. As far as I remember, the value which was inserted by your option was ```/usr/local/bin/vorta``` but this is wrong for my local installation.

So - perhaps - your code should detect the correct final location of the binary via ```which vorta``` and then insert the detected value? I don't know.

**Comment by Hofer-Julian** [comment]
I just saw that the newest release doesn't include my last autostart fix.
It should work with the new one, until then I am glad that you found a solution for you :)
