### ISSUE TITLE
Icon vorta

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#229]
Currently vorta has no icon (see fourth entry in the image). Is it possible to change that?
![grafik](https://user-images.githubusercontent.com/30049909/54057320-e5837700-41f2-11e9-98cb-abc3d70abe5f.png)

**Comment by m3nu** [comment]
You're the Linux expert. I discussed this with Thomas some time ago and he mentioned that usually distributions take care of this stuff while packaging an app. See Archlinux for an example where they added the icon. I'm not sure it can be added on the Python side.

**Comment by Hofer-Julian** [comment]
Interesting. I kind of expected that it would be possible on the Python side for macOS and Linux. I will look into the AUR as you suggest.

**Comment by m3nu** [comment]
For macOS I package the app with Pyinstaller and the icon is added [there](https://github.com/borgbase/vorta/blob/master/vorta.spec#L54). But this is unrelated to Linux.

**Comment by Hofer-Julian** [comment]
@m3nu so the fat binary on linux has an icon as well? I can't test it, because it doesn't work on Fedora 29

**Comment by m3nu** [comment]
The way a fat bin is built for Linux is different from macOS. It won't show up there, but needs to use the desktop's or distribution's mechanism. That's why we decided to leave it to the packagers.

**Comment by Hofer-Julian** [comment]
Okay!

**Comment by m3nu** [comment]
It's still a valid issue, but probably a duplicate of either #209 or at least related.

**Comment by m3nu** [comment]
Let's keep it closed for now. Maybe someone finds out how icons are managed on Linux desktops.

**Comment by brokenpip3** [comment]
Hi,
i created the icon and .desktop file for the aur packages, you can find here:

https://gist.github.com/brokenpip3/0ea26e0f5fc7bd5f061df1efe1594291

The icon was grabbed from the mac one converted in png format.

But this is package maintainer issue, imho.

which distribution you use @Hofer-Julian ?

**Comment by Hofer-Julian** [comment]
I use Fedora 29 and installed vorta per pip. I never installed a GUI app per pip before, that's why I didn't know that it's normal that no icon is displayed.

**Comment by MatejKovacic** [comment]
.desktop files in Ubuntu are stored in /usr/share/applications directory.

cat /usr/share/applications/vorta.desktop 
```
[Desktop Entry]
Encoding=UTF-8
Name=vorta
Type=Application
Comment=BorgBackup GUI for macOS and Linux
Exec=vorta
Icon=vorta32.png
Terminal=false
Categories=Application;Utility;Qt;
```
However, I am not sure where to put the icon file. Anyhow, you can always use absolute path to file...

Another option is to copy .desktop file to ~/.local/share/applications and use an absolute path to your icon instead of just the file name:

```
[Desktop Entry]
Encoding=UTF-8
Name=vorta
Type=Application
Comment=BorgBackup GUI for macOS and Linux
Exec=vorta
Icon=~/.local/share/applications/vorta32.png
Terminal=false
Categories=Application;Utility;Qt;

```
