### ISSUE TITLE
Button to access logs

### ISSUE THREAD

**Issue by luckyrat** [borgbase/vorta#230]
As a new user, I set up and ran a borg backup without much hassle (thanks!) but along with the ~60GB of backup data I see a Log entry that indicates a return code of 1 from the create command. From researching borg I think this means that the process generated warnings.

I would like to see those warnings. At the moment I can't trust the result of using this program so I'd like to see more than just "Backup finished." in the UI.

Perhaps a "View output" button on each Log line? Or just include warnings directly in the list of Logs?

**Comment by m3nu** [comment]
We already write most Borg output and other stuff to a log file. Location would be:

- Linux: `$HOME/.cache/Vorta/log`
- macOS: `$HOME/Library/Logs/Vorta`

This is probably not obvious, so we could add a button that opens the default log folder/file? Is this what you suggest?

There is also #121, which is very much related and has some ideas too.

**Comment by luckyrat** [comment]
Thanks. I agree, very related.

I've found my warnings now (as expected, permission denied reading specific files so I'll have to look into how to run Vorta as root... but later, after a reboot to see how it behaves when auto started).

If the ideas in #121 are likely to get implemented then we could close this as a duplicate or a solved question?

If not, maybe a quicker workaround for the specific problem I had would be to include a mention of this more detailed log file in the UI? And/or put a mention of it somewhere in the project documentation (although I couldn't actually find any beyond the installation guide so this might be a bigger task than it sounds!)

**Comment by m3nu** [comment]
> I've found my warnings now (as expected, permission denied reading specific files so I'll have to look into how to run Vorta as root... but later, after a reboot to see how it behaves when auto started).

If you're backing up system files, like `/var/lib` or `/etc` then you probably want to run it as root. If just your home dir, it's better to just find the permission issues.

**Comment by m3nu** [comment]
IMHO it's overkill to display those logs inside Vorta. So just adding a button seems more reasonable to me. Do you think a button opening the log folder would be sufficient, @ThomasWaldmann ?

**Comment by m3nu** [comment]
> Does that work in a platform-independent way? If so, it would be an easy solution (assuming that clicking on a log file then actually shows it without further hassle).

Yes. It's platform-independent. Provided by Qt.

**Comment by m3nu** [comment]
Implemented in #247. There is still another related issue to make the warnings passed through more meaningful.
