### ISSUE TITLE
ModuleNotFoundError: No module named 'vorta.keyring'

### ISSUE THREAD

**Issue by qazip** [borgbase/vorta#232]
**Describe the bug**
Vorta doesn't open. Here are the logs:

```
Traceback (most recent call last):
  File "/usr/bin/vorta", line 11, in <module>
    load_entry_point('vorta==0.6.11', 'gui_scripts', 'vorta')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/vorta/__main__.py", line 6, in <module>
    from vorta.models import init_db
  File "/usr/lib/python3.7/site-packages/vorta/models.py", line 16, in <module>
    from vorta.utils import slugify, uses_dark_mode
  File "/usr/lib/python3.7/site-packages/vorta/utils.py", line 23, in <module>
    from vorta.keyring.abc import VortaKeyring
ModuleNotFoundError: No module named 'vorta.keyring'
```

**Desktop (please complete the following information):**
 - Arch

**Vorta version:**
```
Name            : vorta
Version         : 0.6.11-1
```

**Comment by m3nu** [comment]
Thanks for reporting. This file should be included in the Pypi package. I just validated.

What do you have in `/usr/lib/python3.7/site-packages/vorta/`?

How did you install it? Using the Arch package manager? Can you try installing via PIP?

**Comment by ThomasWaldmann** [comment]
`__init__.py`?

**Comment by qazip** [comment]
These are the contents of of that folder:

```
/usr/lib/python3.7/site-packages/vorta : ls
application.py  autostart.py  config.py  __init__.py  __main__.py  notifications.py  scheduler.py  updater.py  _version.py
assets          borg          i18n       log.py       models.py    __pycache__       tray_menu.py  utils.py    views
```
I installed via AUR: https://aur.archlinux.org/packages/vorta/

Vorta is not in the oficial repositories.

**Comment by m3nu** [comment]
Yes. Package `keyring` is missing `__init__.py`. I just added it as version 0.6.12 to PIP.

**Comment by qazip** [comment]
Can you make a release, so it is updated in the AUR too?

**Comment by m3nu** [comment]
I don't manage the AUR unfortunately. But since you already have the dependencies you can probably install it via PIP (untested):

```
$ pip uninstall vorta
$ pip install -U vorta
```

**Comment by qazip** [comment]
I know you don't manage the AUR, but the AUR gets updated whenever you make a new release. I'd rather not install via PIP.

**Comment by m3nu** [comment]
Sure. Here the release: https://github.com/borgbase/vorta/releases/tag/v0.6.12

**Comment by qazip** [comment]
Thank you, I can confirm it works.
