### ISSUE TITLE
Initialising a new borgup repo hangs: no reaction, no message and no meaningful log entries

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#237]
I use 

* Vorta 0.6.10

since a while for backups.

Now, I added a new profile "Backup-nas10" pointing to a new mounted file system (with 10TB RAID1 OpenMediaVault) on

* /mnt/nas10 

I then navigated to there and added a subdirectory ```backup```

* /mnt/nas10/backup

does now exist.

In Vorta, I used "Repository" > "Neues Repository initialisieren". I expect, that this uses a correct Borgbackup command to both create and initialise a new repo in that path. Pls. correct me, if I am wrong (then, the text should be amended).

The /mnt/nas10 belongs to my default user which also runs Vorta.
However, after entering a password for the new repo, vorta hangs.

There is no message and no relevant entry in ~/.cache/Vorta/log/vorta.log

#### Bug(?): No reaction

After clicking: no reaction.

I am puzzled, because the other profile apparently works.

![grafik](https://user-images.githubusercontent.com/1151915/54882033-38496980-4e56-11e9-9406-bd5faa4e9abc.png)

Pls. assist.

**Comment by ThomasWaldmann** [comment]
Try the same procedure, but do NOT use a network filesystem that time, just a local directory.

The we'll see whether this is a network filesystem or an other issue.

**Comment by Wikinaut** [comment]
@ThomasWaldmann Thomas: same issue on the local filesystem. Very strange.

**Comment by Wikinaut** [comment]
@ThomasWaldmann perhaps my verison is too old? How can I install latest version from git, there are no detailed instructions in the repo.

**Comment by ThomasWaldmann** [comment]
Please use a borg 1.1.x release, preferably 1.1.9.

Do NOT checkout from master, that would result in alpha quality code that likely noone has tested yet with vorta.

**Comment by Wikinaut** [comment]
current borgbackup is 1.1.5
I now updated vorta to 0.6.14 - this begins to work. I will post further information here, close this issue for now.

(I am puzzled, why neither vorta nor borgbackup shows "Update/s are available" messages...)

**Comment by ThomasWaldmann** [comment]
On Linux systems, updates are usually handled by the distribution updater software.

**Comment by Wikinaut** [comment]
@ThomasWaldmann tja, da liegt der Hase im Pfeffer.... (currently  on LinuxMint 19.1 == Ubuntu Derivat...). Perhaps I will file an "AutoUpdate issue for Vorta".

By the way: great work, BTW2: I got to know BorgBackup in your Lightning talk @ 36c3
