### ISSUE TITLE
Adjustments for Borg 1.2.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#238]
Not sure if anyone ever has tested it, but it would be good to do so in case anything in borg or vorta needs changes.

**Do NOT use borg 1.2.0 alpha on your production repos, always use copies or fresh repos.**

https://github.com/borgbackup/borg/releases

**Comment by m3nu** [comment]
Nice changelog. I'll try it out. We use the `--list` option with `borg extract`. This may need attention (find out which Borg version is used).

**Comment by m3nu** [comment]
Did a rough test. Extract command still works, as does the rest. Had to use this to install on macOS:

`$ BORG_OPENSSL_PREFIX=/usr/local/Cellar/openssl/1.0.2q pip install "borgbackup==1.2.0a5"`

- client: `1.2.0a5`
- server: `1.1.8`

**Comment by ThomasWaldmann** [comment]
Yup, this is expected if it can't be discovered by pkg-config.

And on macOS (with brew?) it can't do the latter, if one does not manually adjust PKG_CONFIG_PATH.

If your python was compiled with openssl 1.1, you can also point borg to 1.1.

**Comment by m3nu** [comment]
I only have openssl 1.0.2q. Homebrew offers 1.1. as a kind of special version. I can try that next.

Setting `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` didn't help, so I assume pkg-config doesn't know about it, as you say in https://github.com/borgbackup/borg/issues/4444.

**Comment by ThomasWaldmann** [comment]
did you use ` export PKG_CONFIG_PATH=...`?

**Comment by m3nu** [comment]
Yes. Wasn't enough.

I should add that I recently installed a second/older XCode because I needed it for some old SWIFT code. This may confuse it. I do use `xcode-select` to switch CLI tools between those versions. So maybe I'm not the most representative example.

**Comment by m3nu** [comment]
Alpha6 still working. Used the pre-compiled binary this time. Will test installing from PIP next.

**Comment by ThomasWaldmann** [comment]
Just coming to my mind: does vorta ever call `borg compact` if it detects borg 1.2?

**Comment by m3nu** [comment]
Not currently, but I guess it should. It could run at the same time as the `prune` command. So the option name would change and Vorta would run an additional command if `borg >= 1.2.0`.

Added a checklist item above.

**Comment by ktosiek** [comment]
I see Borg 1.2 tries to save a checkpoint on SIGINT. I'm not sure how much time this could take, especially with slow, or even lost, connection. Does that mean Vorta needs to add a "Cancelling" state after first click on "Cancel", to show that there's still work happening in the background?

**Comment by m3nu** [comment]
Log format seems different. So our status display isn't working any more. Log looks like this:

```
2020-11-06 16:17:28,504 - vorta.borg.borg_thread - WARNING - 14.37 GB O 10.98 GB C 4.77 MB D 22753 N Users/manu/Docume...E2020/T274412531.pdf
2020-11-06 16:17:28,705 - vorta.borg.borg_thread - WARNING - 14.43 GB O 11.01 GB C 4.77 MB D 23272 N Users/manu/Docume... balance_history.csv
2020-11-06 16:17:28,905 - vorta.borg.borg_thread - WARNING - 14.53 GB O 11.09 GB C 4.77 MB D 23786 N Users/manu/Docume...cript of Records.pdf
2020-11-06 16:17:29,105 - vorta.borg.borg_thread - WARNING - 14.72 GB O 11.25 GB C 4.77 MB D 24303 N Users/manu/Docume...tory listing/deb.png
2020-11-06 16:17:29,305 - vorta.borg.borg_thread - WARNING - 14.76 GB O 11.28 GB C 4.77 MB D 24917 N Users/manu/Docume...rry Samui to KUL.pdf
```

![Screen Shot 2020-11-06 at 16 18 41](https://user-images.githubusercontent.com/3916435/98342743-d39f4a80-204b-11eb-879a-7bf4cdd41050.jpg)

**Comment by ThomasWaldmann** [comment]
Maybe vorta should rather use borg's json log format?

**Comment by m3nu** [comment]
We use the json only from what I know/remember. Need to look into this in detail.

**Comment by m3nu** [comment]
Next beta is out. So we should wrap up any new version-adjustments for 0.7.2.

Here a macOS build with the official dir-style release: https://github.com/borgbase/vorta/actions/runs/544192999

**Comment by m3nu** [comment]
Related: #909 to add json-diff support.

**Comment by ThomasWaldmann** [comment]
That might well come also for borg >= 1.1.16.

**Comment by m3nu** [comment]
1.2 release planned for February, all. Any outstanding issues we know of?

**Comment by witten** [comment]
Just discovered this (by actually reading [Borg documentation](https://borgbackup.readthedocs.io/en/master/usage/notes.html#separate-compaction)): Borg compact only works if both client *and server* are > 1.2. So if Vorta is doing Borg version probing for feature compatibility, it'll also need to query the version of each repository's server. I haven't yet found a good way to do that natively with Borg, although `borg info --remote-path 'borg --version' remote:repo` is a total hack that results in an error but yields the version anyway!

**Comment by ThomasWaldmann** [comment]
@witten can you please try if a borg 1.2 client working against a borg 1.1 server does implicit `compact_segments()` at the end of repo-writing commands (like create, delete)? if that is the case, borg compact is not needed separately.

**Comment by witten** [comment]
Does that correspond to the `Cleaned up 0 uncommitted segment files` message? Here's what I'm seeing:

```
[root@flux tmp]# /tmp/borg-1.2.0rc1 --version
borg-1.2.0rc1 1.2.0rc1

[root@flux tmp]# borg info --remote-path 'borg --version' REDACTED@REDACTED.repo.borgbase.com:repo
Got unexpected RPC data format from server:
borg 1.1.17

[root@REDACTED tmp]# /tmp/borg-1.2.0rc1 --debug delete REDACTED@REDACTED.repo.borgbase.com:repo::REDACTED-2020-12-31T00:18:35.053793
using builtin fallback logging configuration
38 self tests completed in 0.07 seconds
SSH command line: ['ssh', 'REDACTED@REDACTED.repo.borgbase.com', 'borg', 'serve', '--debug']
Remote: using builtin fallback logging configuration
Remote: 35 self tests completed in 0.18 seconds
Remote: using builtin fallback logging configuration
Remote: Initialized logging system for JSON-based protocol
Remote: Resolving repository path b'repo'
Remote: Resolved repository path to '/srv/repos/REDACTED/repo'
Remote: Verified integrity of /srv/repos/REDACTED/repo/index.4555
Enter passphrase for key ssh://REDACTED@REDACTED.repo.borgbase.com/./repo:
TAM-verified manifest
Verified integrity of /root/.cache/borg/REDACTED/chunks
security: read previous location 'ssh://REDACTED@REDACTED.repo.borgbase.com/./repo'
security: read manifest timestamp '2022-02-08T08:15:26.772489'
security: determined newest manifest timestamp as 2022-02-08T08:15:26.772489
security: repository checks ok, allowing access
Remote: Cleaned up 0 uncommitted segment files (== everything after segment 4555).
Remote: Verified integrity of /srv/repos/REDACTED/repo/hints.4555
Remote: Storage quota: 5.01 GB out of 357.83 GB used.
Remote: check_free_space: required bytes 587207528, free bytes 8274800566272
Remote: Storage quota: 2.74 GB out of 357.83 GB used.
security: saving state for REDACTED to /root/.config/borg/security/REDACTED
security: current location   ssh://REDACTED@REDACTED.repo.borgbase.com/./repo
security: key type           5
security: manifest timestamp 2022-02-08T20:58:31.145502
RemoteRepository: 1.08 MB bytes sent, 6.27 MB bytes received, 19300 messages sent
```

**Comment by ThomasWaldmann** [comment]
from `compact_segments()` in 1.1 and 1.2:
```
        logger.debug('nothing to do: compact empty')
...
        logger.debug('compaction completed.')
```
So you should see one of these + some more.

**Comment by witten** [comment]
Didn't look like those appeared anywhere in the log above. I'm happy to try some other combinations if that would help.

**Comment by m3nu** [comment]
`borg compact` support merged. So hopefully ready for the big "twoday".

**Comment by Gerben321** [comment]
Great piece of software! I've got it running in Docker on my Unraid server using this container: https://github.com/borgbase/vorta-docker

I was wondering, the version of Borg is 1.2.0 already there, but this issue still seems to be opened. Does it already use borg compact?

Sorry if this is the wrong place to ask. I haven't seen any update and the 1.2.0 update has gone live for Borg itself.

**Comment by m3nu** [comment]
We added the `borg compact` command recently and some new diff types. I'm not aware of major issues, so you're right and this issue can be closed.
