### ISSUE TITLE
Notification for new updates

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#239]
AutoUpdate: inform user when a new Vorta version is available and suggest to install this (show at least the command "pip3 install vorta" or whatsoever).

**Comment by ThomasWaldmann** [comment]
I'ld rather advise against this:
- it would require internet access
- might be a privacy issue, "phone home"
- duplicates already existing code (linux or other distribution package manager / updater)

Also:
- for vorta, if you look once a month or so, there's always a new version.
- for borg a bit less frequent, but as long as you are on 1.1.x the changes are not that big either.

**Comment by Wikinaut** [comment]
okay.

(Gut, dass wir darüber gesprochen haben.)

**Comment by Wikinaut** [comment]
Related questions for which I could not find an answer:

- What is the correct and recommended procedure or command to update a present installation of Vorta?
- Is the full installation ```pip3 install vorta``` command recommended or is there a better way?

Answer should then please be added to https://vorta.borgbase.com/ .

**Comment by Hofer-Julian** [comment]
The recommended installation method are listed here: https://vorta.borgbase.com/download/
You can see from the order in which they are listed which one is the recommended one.

You can update flatpaks with `flatpak update` or your GUI software center, pip packages with `pip install --upgrade vorta`

**Comment by Wikinaut** [comment]
Okay, the correct answer to my question is:

```pip install --upgrade vorta```

May I suggest you add this to your page? Answer should then please be added to https://vorta.borgbase.com/ or a new section https://vorta.borgbase.com/upgrade .

**Comment by m3nu** [comment]
For macOS, we ship the Sparkle framework, which fully handles updates via Github releases.

**Comment by Wikinaut** [comment]
@m3nu nice. But my original post (see above) says "AutoUpdate: inform user when a new Vorta version is available and suggest to install this", this would be a help for every user.

**Comment by m3nu** [comment]
It's probably OK to add upgrade instructions to the different install methods (pip, Flatpak, macOS binary, package manager). The customs will be different for each one. For pip I don't know any package that checks for updates. For most package managers it's also not too common.

Some users are also wary of random network connections. That's mostly why I removed the bug reporting tool I had in the beginning.

**Comment by Hofer-Julian** [comment]
The next (or the one after the next) flatpak version will feature the option for the app to update itself. We can then decide if we want to implement that.

**Comment by ThomasWaldmann** [comment]
Linux systems have a nice package manager and linux distributions dealing with all the usual update needs.

Apps updating themselves (sometimes, if it works) sounds so much like the bad approach seen on windows.

**Comment by Wikinaut** [comment]
@ThomasWaldmann pls. stick to my issue: "informing" is the thing. I wish to have a signalisation when a new version becomes available. This could be a user option ("Inform me when an update becomes available") if you are afraid of "internet access" problems for offline installations.

**Comment by ThomasWaldmann** [comment]
... becomes available from where?

If you mean from vorta developers, this might be not relevant for you if you got your vorta package from a linux distribution (which might only give you security fixes to a stable release and not new releases).
So, in that case, you would neither need this information, nor you could make much use of it (except maybe pushing some package maintainer).

Also the "how to update" you suggested is very system specific, there are docs for that.

**Comment by Hofer-Julian** [comment]
Yep, @ThomasWaldmann brings it to the point. Unfortunately, it sounds simpler than it actually is.

**Comment by Hofer-Julian** [comment]
There are far too many packages which suggest to be updated, even though I have the newest version my distribution provides...

**Comment by m3nu** [comment]
Workaround: subscribe to the Github release [RSS feed](https://github.com/borgbase/vorta/releases.atom).

**Comment by m3nu** [comment]
I agree with Thomas, in that this feature is not common. So closing.
