### ISSUE TITLE
Create a flatpak package for Vorta+BorgBackup

### ISSUE THREAD

**Issue by thecursedfly** [borgbase/vorta#242]
Hi,

It would be great if you could package the Vorta GUI together with BorgBackup in a flatpak package (see https://flatpak.org/ for info/documentation).
That way me and other non techy users would be able to use this data backup solution on their computer without having to build from source or install separate components.
I recommend a flatpak package because it is distribution independent, avoids dependency problems and incompatibilities with older/newer Linux distribution versions, and allows sandboxing for additional security.
(I opened the same issue for a similar tool but there is no flatpak yet, so I'm still looking for a flatpacked Borg GUI solution)

Thanks!

**Comment by m3nu** [comment]
I considered this before for Snapcraft/Snap. In the end we decided to leave packaging to other people. (except for macOS)

We also have an open issue to make fat binaries for Vorta. This is almost done. Just needs building on older systems to be more compatible.

I'll look into it and see how Flatpak compares to a single binary.

**Comment by Hofer-Julian** [comment]
I am also going to look into flatpaks at some point. I am curious, how many problems will come from sandboxing. I already encountered one problem: https://github.com/flatpak/flatpak-builder-tools/issues/26

**Comment by m3nu** [comment]
Good point. A backup tool needs to read at the very minimum your own files.

On macOS this is already an issue and users need to grant "Full Disk Access" in privacy settings before being able to backup folders like Contacts and Calendar.

**Comment by Hofer-Julian** [comment]
Vorta is now packaged as a flatpak and will soon be published at flathub.

**Comment by prefixtry** [comment]
I have ethical concerns that I would like to share and discuss with you. Flathub supports proprietary apps, but I only use Free Software. But even if I only install Free Software with Vorta via Flathub, all proprietary packages of Flathub are suddenly displayed.
Please support Free Software by offering a direct download of your Flatpak version via your website. Could you imagine this from my argumentation, so that a system with only Free Software and Vorta becomes possible?

**Comment by m3nu** [comment]
You can already use `pip` or this repo to get the code directly, if you can't use Flatpak. (I don't use it.)
