### ISSUE TITLE
Install on Ubuntu Bionic failed with error code 1

### ISSUE THREAD

**Issue by MatejKovacic** [borgbase/vorta#244]
I have Ubuntu Bionic and try to install Vorta with:

sudo -H pip3 install vorta
```
Collecting vorta
  Using cached https://files.pythonhosted.org/packages/3b/e0/464d6afde43c335057e765a9b7ec30015d4171d9347cf577d3237314e309/vorta-0.6.15.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/vorta.egg-info
    writing pip-egg-info/vorta.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/vorta.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/vorta.egg-info/entry_points.txt
    writing requirements to pip-egg-info/vorta.egg-info/requires.txt
    writing top-level names to pip-egg-info/vorta.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/vorta.egg-info/SOURCES.txt'
    reading manifest file 'pip-egg-info/vorta.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lqffhb14/vorta/setup.py", line 7, in <module>
        package_data={'vorta.i18n': ['qm/*.qm']}
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/egg_info.py", line 536, in run
        self.read_template()
      File "/usr/lib/python3.6/distutils/command/sdist.py", line 298, in read_template
        line = template.readline()
      File "/usr/lib/python3.6/distutils/text_file.py", line 175, in readline
        line = self.file.readline()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 99: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lqffhb14/vorta/
```

**Comment by ThomasWaldmann** [comment]
Is there something non-ascii in `setup.py`?

**Comment by m3nu** [comment]
I do all my Linux testing on Ubuntu 18.04 and couldn't reproduce this using the same command.

**But** there is a non-ascii em-dash in `Manifest.in` in a comment. This is also the file where it fails in the trace above.

Here a debug package with that [em-dash](https://www.thepunctuationguide.com/em-dash.html) removed. Maybe this one works. You can test it like this (assuming you installed vorta with `sudo`:

```
$ sudo -H pip3 uninstall vorta
$ sudo -H pip3 install https://files.qmax.us/vorta/vorta-0.6.15-debug.tar.gz
```

**Comment by m3nu** [comment]
The difference in outcomes on the same OS could be explained by the default encoding. I get `utf-8` (which installs fine), you probably have `ascii`. (I never changed this setting, so I'm not sure where it's set.)

See [here](https://stackoverflow.com/questions/23917729/switching-to-python-3-causing-unicodedecodeerror): `locale.getpreferredencoding(False)`

**Comment by MatejKovacic** [comment]
`sudo -H pip3 install https://files.qmax.us/vorta/vorta-0.6.15-debug.tar.gz`
This worked just great. Thanks.

No idea why this problem with UTF-8 is... I have fresh and default install of Ubuntu Bionic.

**Comment by m3nu** [comment]
Great. Thanks for testing. Will release the fix soon.

**Comment by MatejKovacic** [comment]
BTW, is there any mechanism to inform user that new version of Vorta is available?

**Comment by m3nu** [comment]
There is in the macOS release. For Linux it's more common to use a package manager.

One could also subscribe to the Github release feed.

**Comment by MatejKovacic** [comment]
Hmm, is there a way to install Vorta through Ubuntu package manager? I did not found any PPA...

**Comment by m3nu** [comment]
There is a user package for Arch and a pending request for adding it to Debian. Ubuntu is missing as of now, I think. You know the process to add it there?

**Comment by ThomasWaldmann** [comment]
@locutusofborg ^^^ do you want to take care of that?

**Comment by LocutusOfBorg** [comment]
Sorry but I have no time for new packages... if anybody wants to package it, feel free to ask for sponsorship!
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922961

**Comment by ThomasWaldmann** [comment]
@LocutusOfBorg OK. Thanks for all the work you already do!

**Comment by m3nu** [comment]
Happy to give it a shot. What's sponsorship? I met some Debian people on conferences and worked for Debian as Google Summer of Code mentor in 2018. But no formal credentials.

**Comment by LocutusOfBorg** [comment]
you have to create a debian package, and then ping me if it builds and works...
https://mentors.debian.net/sponsor/rfs-howto
cc me in the email in case
