### ISSUE TITLE
Unlinking/relinking a repository looses information about the archive size/duration

### ISSUE THREAD

**Issue by Turako** [borgbase/vorta#245]
**Is your feature request related to a problem? Please describe.**
After unlinking/relinking a repository (for whatever reason) Vorta does no longer displays the information about the size and the duration of the individual archives.

**Describe the solution you'd like**
Using borg itself this information is available with the "info" command:

`borg info /media/kadamovsky/admNAS/Backup/borgbackup::Ubuntu1804_Merkur-default_2019-03-31T12:00:00`

This will show the following information:

`Hostname: Merkur`
`Username: kadamovsky`
`Time (start): Sun, 2019-03-31 12:00:00`
`Time (end): Sun, 2019-03-31 12:00:06`
`Duration: 5.75 seconds`
`Number of files: 14486`

and:

`------------------------------------------------------------------------------`
`                       Original size      Compressed size    Deduplicated size`
`This archive:               13.04 GB             11.72 GB             49.87 MB`

I think this is not actually a bug but more or less a feature request. Are there any plans to implement such a feature?

**Comment by m3nu** [comment]
Running the `borg info` command on each *single archive* would take too long (especially for a remote repo with many archives). So we only save this data, when Vorta runs the backup.

When adding a new repo, Vorta just runs the `borg info` command on the whole repo. This gives a list of archives, but not their size or duration. That's the reason this information gets lost when re-linking a repo.

**Comment by Turako** [comment]
I see.
So this information is determined by Vorta during a backup. Where is this information beeing stored? Would it be possible to recall this data for later use w/o getting this data live from the repository?

**Comment by m3nu** [comment]
Yes. We store it in the settings database after each backup run. When you unlink a repo that information is deleted. It's probably not very transparent to keep this information after the user unlinks a repo.
