### ISSUE TITLE
When mounting the whole repo, unmounting is impossible

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#246]
**Describe the bug**
Like stated in the headline, when the whole repo is mounted, there is currently no way to unmount it again with vorta

**To Reproduce**
1. Mount without selecting an archive
2. Try to find a way to unmount it again

**Comment by m3nu** [comment]
I know... Good to have it recorded here.

**Comment by samuel-w** [comment]
Is a possible solution preventing mounting root? If root is needed I could just create a table entry for it.

**Comment by m3nu** [comment]
With the new archive menu, mounting a whole repo isn't possible any more. So closing. We may add full-repo mounting back later.
