### ISSUE TITLE
Bandwith use limiting

### ISSUE THREAD

**Issue by MatejKovacic** [borgbase/vorta#251]
The problem with BorgBackup and Vorta is, that when backuping is run, it eats all my internet connection. While backuping to external location, I am almost unable to use the internet.

Solution would be rate limiting - limiting maximum amount of bandwith, which can be used by backuping.

One solution (on Linux) is to use Trickle. For instance, `trickle -d 500 -u 100 borg`, would run BorgBackup at a maximum of 500KB/s download and 100KB/s upload.

There are discussions if BorgBackup will introduce rate limiting, but this could be in a long time. Meanwhile, you could add some GUI parameters and run borg with (through) trickle.

What do you think?

**Comment by m3nu** [comment]
Main problem is supplying the trickle binary for different platforms. Or would you tell users to install it themselves?

**Comment by MatejKovacic** [comment]
Hmm, better solution would be that this would be a part of BorgBackup...?

Anyway, trickle entirely in userland and is cross platform compatible:
https://github.com/mariusae/trickle

It seems it is available for MacOS also. Anyway, maybe you can take it's code and use it in Vorta directly?

**Comment by m3nu** [comment]
I don't think we want to integrate a whole project written in another language or ship binaries for it. These are simply very different focuses.

The only option I can think of is an optional dependency that gets used when it's there.

**Comment by m3nu** [comment]
Have you tried adding [`--remote-ratelimit`](https://borgbackup.readthedocs.io/en/stable/usage/general.html#common-options) to the new *Add Repository > Advanced > Extra Borg Args*? Since this is appended to all Borg executions it should do what you need.

**Comment by m3nu** [comment]
Closing this for a lack of response and since Borg already has a similar option.

**Comment by ocroquette** [comment]
If you want to limit the bandwidth for an existing repository in Vorta, go to Schedule / Shell Commands and add "--upload-ratelimit <speed>"  in "Add these arguments when creating a backup". The speed is in kiByte/s.
