### ISSUE TITLE
Bug in Version 0.6.17

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#258]
When I install vorta with `pip3 install --user vorta==0.6.16` everything works as expected.
But when I try `pip3 install --user vorta` and start vorta afterwards I get the following error:

`Traceback (most recent call last):
  File "/home/julian/.local/bin/vorta", line 11, in <module>
    sys.exit(main())
  File "/home/julian/.local/lib/python3.6/site-packages/vorta/__main__.py", line 33, in main
    app = VortaApp(sys.argv, single_app=True)
  File "/home/julian/.local/lib/python3.6/site-packages/vorta/application.py", line 63, in __init__
    self.set_borg_details_action()
  File "/home/julian/.local/lib/python3.6/site-packages/vorta/application.py", line 107, in set_borg_details_action
    self._set_status(params['message'])
AttributeError: 'VortaApp' object has no attribute '_set_status'`

I reproduced this behaviour on a freshly installed Ubuntu 18.04 and Fedora 29 virtual machine, but couldn't reproduce it on my workstation with Fedora 29.

**Comment by m3nu** [comment]
You'll see this when there is some error during checking the Borg version on startup. Here a fix (you can probably just apply it manually.

Let me know if it works and I'll release a new version with it. We have a few pending changes anyways.

**Comment by Hofer-Julian** [comment]
I will try it when I am at home

**Comment by m3nu** [comment]
Thanks. Maybe also test the new fat binary from #209 while you're at it.

**Comment by Hofer-Julian** [comment]
Your fix works, now Vorta starts, even when Borg is not installed.
