### ISSUE TITLE
Attempt to create a repository on a remote NTFS volume fails with uninformative message

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [borgbase/vorta#261]
**Describe the bug**
The attempt to create a repository on a remote NTFS volume failed with an uninformative message, viz., `Unable to add your repository.` The user wants to know why and of course ideally wants the new repository to be created without any problem.

**To Reproduce**
1. Have a mount such as 'smb://192.168.1.51/backup/' that works via 'gvfs'.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu] Linux Mint 19.1 x64 Cinnamon

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
[vorta.log](https://github.com/borgbase/vorta/files/3093702/vorta.log)

**Comment by m3nu** [comment]
Any relevant messages in the logs?

**Comment by m3nu** [comment]
Does the equivalent `borg` CLI command work as expected?

**Comment by LinuxOnTheDesktop** [comment]
> Any relevant messages in the logs?
I did include the Vorta log. I see nothing relevant in any other logs, I am afraid.

> Does the equivalent borg CLI command work as expected?

Good question. I had not tried; I installed Vorta to avoid messing with borg directly. But the answer seems to be 'no'. (Assimilation failed!)

```
borg init --encryption=repokey smb://192.168.1.51/backup/Linux/Borg
Local Exception.
Traceback (most recent call last):
  File "borg/archiver.py", line 2184, in main
  File "borg/archiver.py", line 2120, in run
  File "borg/archiver.py", line 99, in wrapper
  File "borg/repository.py", line 82, in __enter__
  File "borg/repository.py", line 103, in create
FileNotFoundError: [Errno 2] No such file or directory: '/home/<username redacted>/smb:/192.168.1.51/backup/Linux/Borg'

Platform: Linux x1 5.0.7-050007-generic #201904052141 SMP Fri Apr 5 21:43:20 UTC 2019 x86_64
Linux: debian buster/sid
Borg: 1.0.13  Python: CPython 3.5.6
PID: 2769  CWD: /home/<username redacted>
sys.argv: ['borg', 'init', '--encryption=repokey', 'smb://192.168.1.51/backup/Linux/Borg']
SSH_ORIGINAL_COMMAND: None

```

Should I file this report against Borg itself, then?

**Comment by LinuxOnTheDesktop** [comment]
I've filed the issue against Borg, [here](https://github.com/borgbackup/borg/issues/1705). Still, it would be good were Vorta to give a more informative error message.

**Comment by m3nu** [comment]
I think you need to mount the SMB share first. Borg doesn't know the protocol and thinks it's a local folder. Just an educated guess from your log.

**Comment by LinuxOnTheDesktop** [comment]
Thanks - but the share is mounted. One can see that from the following in `mtab`:

```
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
/dev/fuse /home<username redacted>/.cache/doc fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
gvfsd-fuse /home/<username redacted>/.gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0
```

Yet perhaps, as the `mtab` stuff seems to suggest, I need to give Borg the path in a  different syntax. (I am unsure though just which of the above lines refers to `smb://192.168.1.51/backup/Linux/Borg`.)

**Comment by m3nu** [comment]
Then better pass the local path instead of `smb://`. That's why you get this error:

`No such file or directory: '/home/<username redacted>/smb:/192.168.1.51/backup/Linux/Borg'`

It thinks you are giving a relative path.

**Comment by LinuxOnTheDesktop** [comment]
Thanks - but I am still having problems:

```
$  borg init --encryption=repokey /run/user/1000/gvfs
Repository /run/user/1000/gvfs already exists.
 ~  $  borg create /run/user/1000/gvfs::Thursday /home/<username redacted>/scripts
Failed to create/acquire the lock /run/user/1000/gvfs/lock.exclusive ([Errno 2] No such file or directory: '/run/user/1000/gvfs/lock.exclusive').
Traceback (most recent call last):
  File "borg/archiver.py", line 2184, in main
  File "borg/archiver.py", line 2120, in run
  File "borg/archiver.py", line 99, in wrapper
  File "borg/repository.py", line 83, in __enter__
  File "borg/repository.py", line 183, in open
  File "borg/locking.py", line 291, in acquire
  File "borg/locking.py", line 304, in _wait_for_readers_finishing
  File "borg/locking.py", line 146, in acquire
borg.locking.LockFailed: Failed to create/acquire the lock /run/user/1000/gvfs/lock.exclusive ([Errno 2] No such file or directory: '/run/user/1000/gvfs/lock.exclusive').

Platform: Linux x1 5.0.7-050007-generic #201904052141 SMP Fri Apr 5 21:43:20 UTC 2019 x86_64
Linux: debian buster/sid 
Borg: 1.0.13  Python: CPython 3.5.6
PID: 12095  CWD: /home/<username redacted>
sys.argv: ['borg', 'create', '/run/user/1000/gvfs::Thursday', '/home/<username redacted>/scripts']
SSH_ORIGINAL_COMMAND: None
```

**Comment by LinuxOnTheDesktop** [comment]
I'm going to close this, in favour of the issues I have open at borg itself.
