### ISSUE TITLE
Execute shell command before checking for repository existence

### ISSUE THREAD

**Issue by rossomah** [borgbase/vorta#262]
**Feature request**
Add option that allows execute shell command before checking for repository existence, it will be helpful for automatically mounting repository directory(for example: via samba) before starting backup.

**Comment by m3nu** [comment]
We already have that. Did you check *Schedule > Shell Commands > Pre/Post Backup Command*?

<img width="780" alt="Screen Shot 2019-04-19 at 07 48 22" src="https://user-images.githubusercontent.com/3916435/56397696-901d9980-6277-11e9-9eaf-56bf9e6c3a35.png">

**Comment by rossomah** [comment]
This is doesn't work, i've got message: Repo folder not mounted or moved. But I've checked my shell command is working from console.

**Comment by m3nu** [comment]
Do you get this error all the time or just when using a post-backup command?

**Comment by rossomah** [comment]
All the time when folder with repository not mounted

**Comment by rossomah** [comment]
I've made simpe patch, it works for me. Perhaps it will be interesting.

[creat.py.patch.zip](https://github.com/borgbase/vorta/files/3099456/creat.py.patch.zip)

**Comment by m3nu** [comment]
I see. You moved the pre-backup command to run before our checks. To avoid getting the "not mounted" error before the mount-command gets a chance to run? Did I get this correctly?

Wanna make a real Pull Request for this?

(here the patch content for future reference)

```
Index: src/vorta/borg/create.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/vorta/borg/create.py	(revision dc9b23f911e74b046f8c25a782608ae991b66bb6)
+++ src/vorta/borg/create.py	(date 1555712019744)
@@ -92,6 +92,12 @@
             if wifi_is_disallowed.count() > 0 and profile.repo.is_remote_repo():
                 ret['message'] = trans_late('messages', 'Current Wifi is not allowed.')
                 return ret
+        ret['profile'] = profile
+        ret['repo'] = profile.repo
+
+        if cls.pre_post_backup_cmd(ret) != 0:
+            ret['message'] = trans_late('messages', 'Pre-backup command returned non-zero exit code.')
+            return ret
 
         if not profile.repo.is_remote_repo() and not os.path.exists(profile.repo.url):
             ret['message'] = trans_late('messages', 'Repo folder not mounted or moved.')
@@ -131,12 +137,6 @@
             cmd.append(f.dir)
 
         # Run user-supplied pre-backup command
-        ret['profile'] = profile
-        ret['repo'] = profile.repo
-        if cls.pre_post_backup_cmd(ret) != 0:
-            ret['message'] = trans_late('messages', 'Pre-backup command returned non-zero exit code.')
-            return ret
-
         ret['message'] = trans_late('messages', 'Starting backup...')
         ret['ok'] = True
         ret['cmd'] = cmd
```

**Comment by rossomah** [comment]
Yes, you are right. Now pre-backup command can mount something before checks. I am first time at github, and don't know how to make pull request. But i can try.

**Comment by m3nu** [comment]
If you're willing to learn it, go ahead. Else I'll just use your code and do it.

**Comment by m3nu** [comment]
This is already implemented and pre-backup commands run before validating the folder.

So closing this now. If this doesn't solve your issue, @rossomah , please let me know here.
