### ISSUE TITLE
Platform Agnostic Packages

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#265]
This issue display the current status of platform agnostic packages for vorta:

- Flatpak
  - Disadvantages
    - Can't bypass sandboxing
  - Advantages
    - Can't bypass sandboxing
    - Tightly integrated into Fedora, Linux Mint, Endless OS and soon Elementary OS
    - Decentralised
    - Easy to install
    - Autoupdate possible (with gnome-software)
  - Experiences
    - Current state of development can be found inside of the repository under /flatpak
    - Hard to package (but maybe not hard to maintain?)
    - ~~Mounting not yet possible (how to compile fuse?)~~
    - Does not display app in language of os yet
    - ~~Are notifications working?~~ They work
  - Next Steps
    - ~~Include icon and .desktop file~~
    - Edit contribution guide
    - Publish vorta flatpak at flathub
- Snap
  - Disadvantages
    - Bypassing sandboxing possible
    - Centralised
  - Advantages
    - Bypassing sandboxing possible
    - Tightly integrated into Ubuntu
    - Official support of proprietary software like VS Code, Skype, Spotify and more (all without sandbox)
    - Autoupdate (forced) 
    - Easy to install

- Appimage
  - Disadvantages
    - No sandboxing
    - ~~No automatic updates~~ (see comment below)
    - ~~No integration in app centers~~ (KDE Discover - see comment below)
  - Advantages
    - One file per app
    - Simple to use

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by wechsler42** [comment]
Just one addition. When we focus on a not that tech experienced user I would suggest to use a package format:
- which does not need to use the command line (change permissions here, add it to PATH, make it executable there, etc) for getting the vorta package to work
- which does not need to force the user to install first this, than that before the user finally could get vorta to work --> just a one stop and positive experience
- which offers desktop integration including notifications out of the box. This is also rather a must to get a positive user experience

**Comment by m3nu** [comment]
Close to being finished by @Hofer-Julian
