### ISSUE TITLE
insecure default permission on Vorta/settings.db

### ISSUE THREAD

**Issue by srgvg** [borgbase/vorta#271]
**Describe the bug**
Vorta/settings.db is created with 0755 permission, allowing all users on the host to read it, (possibly) including encryption passphrases.

**To Reproduce**
1. Install Vorta
2. Configure Vorta
3. Run a backup 
4. ls -l $HOME/.local/share/Vorta/settings.db

**Desktop (please complete the following information):**
 - OS: Debian Linux (testing/buster)

**Possible Fix
- make sure permissions are restricted to the owner/user with 0700 permission bits.

**Comment by m3nu** [comment]
Yeah. That could be fixed. Currently Peewee creates the DB if it doesn't exist.

**Comment by ThomasWaldmann** [comment]
@srgvg Please try this (as the same user as you ran the backup):
```
touch foobar
ls -l foobar
```
Do you see 755 permissions there also?

Then your `umask` is just in general not as you would like it to be.

**Comment by srgvg** [comment]
@ThomasWaldmann yes, files are created by default with a 0222 umask. I disagree that this is the cause of the problem, nor an acceptable solution.

**Comment by ThomasWaldmann** [comment]
I think you mean 0022?

And there is nothing to disagree here, that's just how it works. If you configure the umask for your user to be 0022, it'll just take away write permissions for group and other, but keeps r-x permissions.

If you don't like your files to be read by others and/or group, you should rather default to 0027 or 0077 maybe and just manually change files/dirs if you want to make exceptions from that rule.

**Comment by m3nu** [comment]
Changing the umask in the shell before starting Vorta didn't have any effect, but changing it before the DB gets created did.

Not sure this is necessary, but secure defaults are always good. Here a (small) [PR](https://github.com/borgbase/vorta/pull/300) for it.

**Comment by m3nu** [comment]
Merged #300

**Comment by srgvg** [comment]
Thank you!
