### ISSUE TITLE
Respect `BORG_PASSCOMMAND` environment variable

### ISSUE THREAD

**Issue by rob-as** [borgbase/vorta#272]
I would like to keep the repository password out of my Keyring and instead enter the password everytime it is required for reading/writing the repository.

Would it be possible to keep `ENV['BORG_PASSWORD']` unset if `ENV['BORG_PASSCOMMAND']` is defined (see: https://github.com/borgbase/vorta/blob/master/src/vorta/borg/borg_thread.py#L58-L61)?

This would offer the opportunity to implement a custom method to fetch the repository password.

**Comment by ThomasWaldmann** [comment]
Sounds good. Also there is a FD-based method since a while to pass the passphrase via a file descriptor.

**Comment by m3nu** [comment]
Supporting passcommands would be nice. Like keeping it on a Yubikey? 🤩

I'm just skeptical with regards to env vars, since they are generally not part of a GUI. (We do use them to debug languages.)

How about supporting passcommands in the *Advanced* section of the *Add Repo* dialog?

**Comment by ThomasWaldmann** [comment]
@m3nu guess this is less a case of having to "configure" vorta via env vars (which I agree would be a bit strange), but rather of vorta not getting in the way when the user tries to pass something to borg.

**Comment by rob-as** [comment]
@ThomasWaldmann I would agree with you and keep this configuration out of the Vorta UI.

**Comment by m3nu** [comment]
Then it's decided. Without UI changes it's a rather small change.
