### ISSUE TITLE
Build macOS Binaries on oldstable instead of stable to cover more versions

### ISSUE THREAD

**Issue by Urheberrecht** [borgbase/vorta#273]
**Describe the bug**
Vorta starts with the icon in the upper right corner of the screen. If trying to open from the icon, the icon disappears and the app seems to crash. Starting Vorta again fails.

**To Reproduce**
See above.

**Desktop (please complete the following information):**
 - OS: MacOS 10.13 SERVER (with all security updates) 

**Additional context**
From "vorta.log":
2019-05-02 14:30:45,390 - vorta.i18n - DEBUG - Loading translation failed for ['C'].
2019-05-02 14:30:45,545 - vorta.borg.borg_thread - INFO - Running command /var/folders/q6/j51_d8t162525yvwq1cy41h80000gn/T/_MEIcw9r1j/bin/borg --version

From "system.log":
May  2 14:30:46 Server-intern com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.vorta-darwin.61309): Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 107: Malformed bundle, taint = missing executable

From "vorta-darwin_2019-05-02-143052_Server-intern.crash":
Process:               vorta-darwin [61309]
Path:                  /Applications/Vorta.app/Contents/MacOS/vorta-darwin
Responsible:           vorta-darwin [61309]
       0x100c7f000 -        0x100c85fff +com.borgbase.client.macos (0.6.19 - 0.6.19) <7B85D4FD-A341-348E-8083-7DC82766F257> /Applications/Vorta.app/Contents/MacOS/vorta-darwin
       0x10aa3f000 -        0x10aa8fff7 +org.sparkle-project.Sparkle (1.21.2 12-ga5b23cdbe - 1.21.2) <7C201192-55FC-350C-BA71-8FC0F15B80D5> /Applications/Vorta.app/Contents/Frameworks/Sparkle.framework/Sparkle

**Comment by m3nu** [comment]
What do you see when you run the binary from the Terminal? Like

```
$ ./Vorta.app/Contents/MacOS/vorta-darwin --foreground
```

I'm packaging it on 10.14, but tested on 10.13. The goal is to support the latest and one version before of macOS.

**Comment by sbrosnihan** [comment]
Crashes for me too in sierra and Mojave. I get this when I run from terminal: 
prompt:  /Applications/Vorta.app/Contents/MacOS/vorta-darwin --foreground

[1750] Error loading Python lib '/var/folders/5l/x6nw2g596_dgyrp9jcxgk3_w0000gp/T/_MEIY35QAS/libpython3.6m.dylib': dlopen: dlopen(/var/folders/5l/x6nw2g596_dgyrp9jcxgk3_w0000gp/T/_MEIY35QAS/libpython3.6m.dylib, 10): Symbol not found: _futimens
  Referenced from: /var/folders/5l/x6nw2g596_dgyrp9jcxgk3_w0000gp/T/_MEIY35QAS/libpython3.6m.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/5l/x6nw2g596_dgyrp9jcxgk3_w0000gp/T/_MEIY35QAS/libpython3.6m.dylib

**Comment by m3nu** [comment]
> Crashes for me too in sierra and Mojave. I get this when I run from terminal:

You probably mean Sierra and High Sierra. It's this known issue of building on a specific macOS version. https://github.com/pyinstaller/pyinstaller/issues/3418

I'll build the next one on High Sierra instead of Mojave.

Until then you can always install via PIP as workaround:

```
$ pip install vorta
```

**Comment by Urheberrecht** [comment]
Apologies for not getting back to you earlier. I am in front of this server only once a week...

Running your suggested command from within /Applications gives me this:

MyServer:Applications me$ ./Vorta.app/Contents/MacOS/vorta-darwin --foreground
2019-05-08 19:55:09,332 - vorta.i18n - DEBUG - Loading translation succeeded for ['de', 'de-DE', 'de-Latn-DE'].
2019-05-08 19:55:09,365 - apscheduler.scheduler - INFO - Scheduler started
Traceback (most recent call last):
  File "psutil/_psosx.py", line 362, in catch_zombie
  File "psutil/_psosx.py", line 426, in cmdline
ProcessLookupError: [Errno 3] No such process

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vorta/__main__.py", line 40, in <module>
  File "vorta/__main__.py", line 33, in main
  File "vorta/application.py", line 56, in __init__
  File "vorta/application.py", line 78, in open_main_window_action
  File "vorta/views/main_window.py", line 34, in __init__
  File "vorta/views/archive_tab.py", line 77, in __init__
  File "vorta/views/archive_tab.py", line 93, in populate_from_profile
  File "vorta/utils.py", line 225, in get_mount_points
  File "psutil/__init__.py", line 663, in cmdline
  File "psutil/_psosx.py", line 342, in wrapper
  File "psutil/_psosx.py", line 426, in cmdline
  File "contextlib.py", line 99, in __exit__
  File "psutil/_psosx.py", line 375, in catch_zombie
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=254, name='python-wrapper')
[12629] Failed to execute script __main__


Please bear with me replying with delay.

Many thanks for looking into this.

**Comment by Urheberrecht** [comment]
> Until then you can always install via PIP as workaround:
> 
> ```
> $ pip install vorta
> ```

Although I am doing this "all the time" on my personal Mac, I am bit hesitant to do this on a production server...

But let me know if this would be critical for more testing etc.

**Comment by m3nu** [comment]
macOS doesn't even ship Python3. So you will always install in a virtualenv anyways. Possibly Homebrew. So interfering with the system Python isn't a concern.

It's not critical anyways. From your logs it seems, there is a permission issue while looking at another Python process. I'm guessing it's unrelated to Vorta and should thus be ignored gracefully.

**Comment by m3nu** [comment]
So we have actually 

- [ ] a rare bug (can't get details on Python process found in process list due to permission issue) and 
- [ ] a task (compile release on different macOS version)

**Comment by m3nu** [comment]
Fixed the permission issue when finding mount points. Now on to the Vagrant task.

**Comment by m3nu** [comment]
The first Vorta version, compiled on macOS 10.13 is now ready. The build process is done via Vagrant. (see #290 for details)

Could you see if this version works on your 10.13 installation, @Urheberrecht ?

https://files.qmax.us/vorta/vorta-0.6.20-macos1013.dmg (signed with my Apple dev key)

Some of the backgrounds don't look right. I'll have to look into that in Qt Designer.

**Comment by Urheberrecht** [comment]
I can confirm that this works fine with 10.13!

Many thanks for looking into this issue!

Best regards

**Comment by m3nu** [comment]
Thanks for checking. I already added a pre-release that was compiled under oldstable macOS. In the future we will do all releases via Vagrant on oldstable.

**Comment by Urheberrecht** [comment]
Wonderful, as vorta-0.6.21pre also solves [#289](https://github.com/borgbase/vorta/issues/289) now!
Thank you!
