### ISSUE TITLE
Add custom options to borg create command

### ISSUE THREAD

**Issue by rwaldspur** [borgbase/vorta#274]
I'm looking to add additional arguments to the borg create command from within Vorta, for example, two simple examples:
--exclude-caches
--files-cache=ctime,size

I see there are additional arguments that can be passed while initializing a new repository under the Advanced tab, but my understanding is that there is no current way to add arguments to the "create" command.

This would be (somewhat) similar to issue #96 

I believe this could extend the functionality of Vorta quite a bit in a somewhat general way.

Thanks.

**Comment by m3nu** [comment]
True. Currently there is an option to add arguments to *all* commands. Like global SSH options.

Args for `--create` could go under *Schedule > Shell Commands*. Not sure this is the best place.

**Comment by flip-bs** [comment]
+1 It can be very useful to avoid backing up mounted remote FS with the option `--one-file-system`

**Comment by adatum** [comment]
> Currently there is an option to add arguments to all commands.

@m3nu Is this explained somewhere? 

Options like `--dry-run`, `--one-file-system`, `--exclude-cache` are commonly used and very useful.

**Comment by mahikeulbody** [comment]
and also `--chunker-params` create option.

**Comment by Ramblurr** [comment]
This may be another feature, but I would love to see the ability to add `--dry-run` to test out my backup. Specifically I'm interested in testing my exclusion settings.

**Comment by PitBullCH** [comment]
Looking forward to seeing this one - just had the case myself where I need to add --remote-path=borg1 to the Borg args for Rsync.net, but the only way to do it is delete the profile, unlink the repository, then new profile and re-use existing repository and then can access the Borg args input.
