### ISSUE TITLE
Manjaro Linux: Permission erri during installation via pip3 install vorta

### ISSUE THREAD

**Issue by wechsler42** [borgbase/vorta#278]
Hi there,
here is a minor flaw and a workaround for it.

**Describe the bug**
Installation via pip3 install vorta leads to this error:
`Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/lib/python3.7/site-packages/pyasn1-0.4.5.dist-info'            
Consider using the `--user` option or check the permissions.                 
`

**To Reproduce**
1. pip3 install vorta
2. See error described above.

**Desktop (please complete the following information):**
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
DISTRIB_CODENAME=Illyria
DISTRIB_DESCRIPTION="Manjaro Linux"
Desktop: KDE or Cinnamon

**Additional context**
Workaround:
a) use "pip3 install vorta --user" instead of "pip3 install vorta"
b) use vorta installation via AUR

**Comment by Hofer-Julian** [comment]
I agree that we could give additional information to the installation instructions, but it is not a bug that you can't install vorta system-wide without root privileges, but expected behaviour.

**Comment by wechsler42** [comment]
I fully agree, it it not a bug. But I think for someone who is not that tech-savvy it is an obstacle which could be removed. So I would suggest to adapt the install.md.
