### ISSUE TITLE
Suggestion: Revise install.md with regard to Manjaro/Arch Linux pip installation

### ISSUE THREAD

**Issue by wechsler42** [borgbase/vorta#281]
## Install from Source
The generic way is to install it as Python package using [PIP](https://pip.readthedocs.io/en/stable/installing/). First [install](https://borgbackup.readthedocs.io/en/stable/installation.html) Borg using the package of your distribution or via PyPI. The latter needs some additional [source packages](https://borgbackup.readthedocs.io/en/stable/installation.html#dependencies). Then install Vorta from PyPI. Your local Python version should be >= 3.6. For typical Debian and Ubuntu-based distributions try:
```
$ pip3 install vorta
```
For Manjaro or Arch Linux try:
```
$ pip3 install msgpack==0.5.6 --user
$ pip3 install vorta --user
```

**Comment by ThomasWaldmann** [comment]
I'ld advise against adding borg-related stuff to vorta docs, rather point to borg docs.

**Comment by m3nu** [comment]
Yeah. No point in duplicating docs. Borg already has very comprehensive install instructions.

In addition Pip can be a bit different to use in every environment. Users generally know how to install a package they want the right way. E.g. with/without sudo, in a virtualenv, in the user-folder, etc.

**Comment by wechsler42** [comment]
I agree from perspective of an experienced user. If vorta is targeted towards user which are not that tech-savvy (and I understand vorta that way) then every obstacle received with the combo borg and vorta is something that should be avoided.

**Comment by Hofer-Julian** [comment]
@wechsler42 I see your point. Borgbackup is currently broken on Fedora 30 as well. Can't wait when we can provide a flatpak, snap package and/or appimage so we can escape this dependency hell.

**Comment by wechsler42** [comment]
Yes, indeed, I am looking forward on this, too!
In an ideal world, the chosen package format would be something that is widespread in the Linux-World, meaning that it just works out of the box in actual Linux distros and Desktop Environments without installing further software packages to make the desired package (=Vorta) work. Besides that, the package format should be at home in the common appstores of the distributions so that user just find it there. And yes, the vorta package should work out of the box, so that no further installation borg is necessary, it would be just included.
Ok, so for for my two cents of the ideal world vorta package :-)

**Comment by m3nu** [comment]
Flatpak support is on the way and msgpack is integrated with the latest Borg release. Both should address the issues here. So closing this.
