### ISSUE TITLE
SSH port in repo url is not used when ssh:// is ommitted

### ISSUE THREAD

**Issue by RlndVt** [borgbase/vorta#284]
**Describe the bug**
When trying to connect or initalise a repo over ssh, port 22 is used instead of the one specified in the url.

e.g. user@host:port/path/to/repo

When you add ssh:// the repo is initialised/added.

**Comment by m3nu** [comment]
Have you tried doing the same thing with Borg directly? Will it respect the port? Vorta passes the URL through to Borg. We don't do anything with it.

**Comment by RlndVt** [comment]
You are right, same error. I'll try and report there.
