### ISSUE TITLE
Run vorta backup from commandline

### ISSUE THREAD

**Issue by RlndVt** [borgbase/vorta#293]
**Is your feature request related to a problem? Please describe.**
Cannot create a backup (e.g. based on a profile name) from the command line.

**Describe the solution you'd like**
Allow for Vorta backups to be run from the command line.
Does not need to be all encompassing, but some basic functionality.

I'm thinking of a command like `$vorta run --profile $(profilename)`. Additional flags like `--no-prune` or similar could be added to override settings in a profile.

This allows users to run their own scheduling solution. (e.g. systemd timer, crontab, anacron.)

**Comment by m3nu** [comment]
This use case is already covered by [Borgmatic](https://torsion.org/borgmatic/). Vorta is a GUI tool only.

**Comment by RlndVt** [comment]
Except that you cannot use the configuration/profile created by Vorta in borgmatic. (Or vice versa #107.) One would need to have duplicate profiles for both programs. 

Borgmatic is more all-encompassing allowing for more than just basic functionality, but the command structure is a good inspiration [1].

IMO, being a 'GUI tool only' is a limiting statement. Being a GUI tool that also accepts (basic) commands is more sane.

[1] https://torsion.org/borgmatic/docs/reference/command-line/
