### ISSUE TITLE
cannot mount network drive before backup

### ISSUE THREAD

**Issue by devZer0** [borgbase/vorta#296]
**Describe the bug**
i added 

sudo mkdir /Volumes/share; sudo mount_smbfs //user:pass@server/share /Volumes/share/

as a pre-backup shell command because i want vorta backup to backup to a network share.

i'm getting "Pre-backup command returned non-zero exit code" 

Unfortunately i cannot see what goes wrong

furthermore - i want vorta backup my whole system, but apparently it only runs as non-root user and i cannot switch user context so vorta does backup everything

**To Reproduce**
n/a

**Desktop (please complete the following information):**
 - OSX High Sierra latest

**Comment by Hofer-Julian** [comment]
True, Vorta only runs as a non-root user and that will stay that way as has been mentioned here https://github.com/borgbase/vorta/issues/240#issuecomment-477565025

> sudo mkdir /Volumes/share; sudo mount_smbfs //user:pass@server/share /Volumes/share/

Is there are reason why you have to mount as root?

**Comment by m3nu** [comment]
If you create the mount folder as root user, you need root perms to use it.

Just use a folder that belongs to you as mount point. Instead of `/Volumes/share`.

**Comment by m3nu** [comment]
We recently made some changes to the pre-backup command. It was moved around, so mounting a volume should be possible now.

Vorta won't deal with root permissions, but you can probably prepend `sudo` to your pre-backup command.

If you test it, let us know how it goes.
