### ISSUE TITLE
Problem with QToolbox

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#298]
Today I tried to find the root of the problem with Vorta's Toolbox (no Text is displayed).
QDesigner gave me an idea, but in the end I couldn't fix it.
![Vorta-Adwaita-Problem](https://user-images.githubusercontent.com/30049909/58761098-7773f500-8540-11e9-8438-92a98bc73aaf.gif)

**Comment by m3nu** [comment]
You won't see any content in Qt Designer, as it's only populated programmatically later.

**Comment by Hofer-Julian** [comment]
> You won't see any content in Qt Designer, as it's only populated programmatically later.
> 
> Do you also get an issue when running the Python app?

Yes, please notice the text next to the scissors-symbol and the archive-symbol.
This text is not there when using the flatpak on GNOME (or with pip plus necessary dependencies)

**Comment by m3nu** [comment]
Ah. There. Don't think we can do much about this. Must be in Qt.

**Comment by Hofer-Julian** [comment]
We could force "Fusion"-Style Linux- or Flatpak-wide.

**Comment by m3nu** [comment]
On a positive note, it doesn't happen on macOS. It's aligned left there. Have you tried playing with the design settings in Qt Designer?

<img width="321" alt="Screen Shot 2019-06-12 at 14 48 37" src="https://user-images.githubusercontent.com/3916435/59329345-3ee2d100-8d21-11e9-88ec-6e1a0fc27258.png">

**Comment by Hofer-Julian** [comment]
> On a positive note, it doesn't happen on macOS. It's aligned left there. Have you tried playing with the design settings in Qt Designer?
> 
> <img alt="Screen Shot 2019-06-12 at 14 48 37" width="321" src="https://user-images.githubusercontent.com/3916435/59329345-3ee2d100-8d21-11e9-88ec-6e1a0fc27258.png">

Same with "Fusion"-Style.

And yes, but without success...
