### ISSUE TITLE
pip3 install vorta always shows some "failed building" information due to "invalid command 'bdist_wheel'"

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#299]
**Describe the bug**
```
pip3 install vorta
.....


  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for pycparser
  Running setup.py clean for pycparser
Failed to build vorta peewee psutil tzlocal pycparser
```
Here http://dpaste.com/18T5SJJ.txt is the complete output.

**Desktop (please complete the following information):**
Linux Mint 19.1

**Comment by m3nu** [comment]
Hi and thanks for the report.

Looks like either your `setuptools` is very old or it's missing the `wheel` package. So multiple packages fail installing. Vorta is just one of them.

You can look into this SO thread, which discusses the same issue: https://stackoverflow.com/questions/34819221/why-is-python-setup-py-saying-invalid-command-bdist-wheel-on-travis-ci

**Comment by FabianKnapp** [comment]
You can try

`sudo apt-get install python3-setuptools`

**Comment by Wikinaut** [comment]
@FabianKnapp "python3-setuptools ist schon die neueste Version (39.0.1-2)."

**Comment by m3nu** [comment]
How about `pip3 install wheel`?

**Comment by Wikinaut** [comment]
@m3nu bravo, that  ```pip3 install wheel```fixed it. Should be added elsewhere to the list of dependencies.
