### ISSUE TITLE
macOS Console issues and non-responsive

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#3]
In Activity Monitor.app Vorta shows as (Not Responding) - with an ever increasing 'Recent hangs' count. I've attached screenshots with info.

![screenshot 2018-11-02 at 21 33 08](https://user-images.githubusercontent.com/3916435/47946739-d2ae1c80-df4a-11e8-84f8-e3bbcf058f8b.png)
![screenshot 2018-11-02 at 21 36 41](https://user-images.githubusercontent.com/3916435/47946740-d2ae1c80-df4a-11e8-98c7-c68640c20b25.png)

**Comment by m3nu** [comment]
I looked into upcoming console messages.

1. Error message in console `Unable to load Info.plist exceptions (eGPUOverrides)`
This seems to happen for almost all apps and seems related to Mojave. Not taking any action.

2. App showing "Not responding" in Activity monitor.
Seems to be related to new privacy permissions an app can ask for. I'm not sure this is relevant here. Adding the parameter `NSAppleEventsUsageDescription` fixed the hangs.

3. Error regarding PlugIn-folder in app package. Can be fixed by adding an empty folder. Probably no problem if not.
```
Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/manu/Workspace/vorta/dist/Vorta.app/Contents/, NSFilePath=/Users/manu/Workspace/vorta/dist/Vorta.app/Contents/PlugIns, NSUnderlyingError=0x7f83772dc7e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

4. I couldn't find the others regarding `libdispatch` and `XPC services`. Maybe related to another app.

**Comment by adamluk** [comment]
It's looking good so far - 1.5 hours and no hangs 👍

**Comment by m3nu** [comment]
Great. Then I'll close this for now. I also didn't see a hang after having it on since last night.
