### ISSUE TITLE
long texts truncated (not wrapped)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#30]
some ui elements have quite long texts related to them and they are truncated at the right (not: wrapped to next line).

**Comment by ThomasWaldmann** [comment]
![screenshot from 2018-11-23 15-30-39](https://user-images.githubusercontent.com/356103/48948470-dd9a1280-ef34-11e8-85bf-9f2a72046920.png)

**Comment by ThomasWaldmann** [comment]
still happens, tested on ubuntu linux 18.04.

**Comment by m3nu** [comment]
Oh gosh. I guess the fonts are a bit different on each system. Will wrap everything. Just checked the logging fields for the last commit.

**Comment by m3nu** [comment]
The occurrence in the screenshot is fixed. Still want to set up an Ubuntu to have a second look.

**Comment by ThomasWaldmann** [comment]
Did click through all tabs, guess that was all.
