### ISSUE TITLE
Add profile from file or import profile button

### ISSUE THREAD

**Issue by dtu-compute** [borgbase/vorta#302]
**Is your feature request related to a problem? Please describe.**
When installing Vorta on many workstations it would be very useful if Vorta used the config if such were provided as a file. Here I would have preconfigured everything for the user including repo path, encryption type, password, sources etc.

It could be adding an "Import profile" button or have Vorta look for a specific file, and if it exist, then create that profile.

**Describe the solution you'd like**
A way to provide a profile as a file to many users.

**Describe alternatives you've considered**
One option could be installing it on one workstation, and distribute those generated files to others. That would however not work, as each user should have different repos and passwords. So some sort of config file either json/yaml/xml, so I can auto generate it for each computer in advance.

**Comment by Hofer-Julian** [comment]
Should be doable to dump the necessary data into a json file and import them afterwards.

But it would take effort to maintain it as  Vorta evolves.

**Comment by m3nu** [comment]
Peewee, the ORM wrapper we use may have an export feature.

We shouldn't maintain our own.

**Comment by Hofer-Julian** [comment]
Like this http://docs.peewee-orm.com/en/latest/peewee/playhouse.html?highlight=Export#dataset?

We would still have to write something to retrieve the passwords from keyring before export, and insert them into the keyring after import right?

**Comment by m3nu** [comment]
Saving passwords to plain text formats is a hairy topic. It will depend on the use case if this is acceptable.

I see 2 cases here:

1. UI button to import new profile from json.
2. For enterprise deployments: With an empty config, populate from standardized file XX. So the user has backups without even knowing.

None of those require the password to be exported. For 1, it can ask during import. For 2, the admin can decide if he/she wants to seed the new machine with the password.

**Comment by Hofer-Julian** [comment]
I don't really understand option 2), but 1) and your objection to saving passwords in plain text sounds good.

**Comment by m3nu** [comment]
Elaborating 1: OP plans to "installing Vorta on many workstations". Then he will use some kind of device mgmt or imaging system for setup. Those can generally put a config file in place, populated with some values. If Vorta reads this file, nothing else is needed to set it up for a new user.

Just my model of it. Could be other cases. But that's what I would want when setting it up.

**Comment by Hofer-Julian** [comment]
Did you elaborate 1 or 2?

If it was 2, than it sounds good and 1) would probably not be needed

**Comment by m3nu** [comment]
Closing as duplicate to #462
