### ISSUE TITLE
Translation is not working with flatpak

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#306]
Currently translation is not working when Vorta is run as a flatpak.

I get the following error message for `de_AT`:

`vorta.i18n - DEBUG - Loading translation failed for ['de-AT', 'de-Latn-AT']`

**Comment by Hofer-Julian** [comment]
I just went through with pdb:
qm_path is "/app/lib/python3.7/site-packages/vorta/i18n/qm".
This path exists but it is empty.

**Comment by m3nu** [comment]
Translations in this folder are generated using `make translations-to-qm`.

Is this command run before pushing the files to flatpak? Maybe it supports some kind of pre-install commands? This needs some Qt tools installed as well.

**Comment by Hofer-Julian** [comment]
Flatpak support pre-install commands.

But I don't really see why this isn't necessary when one installs it on the local machine with pip.

**Comment by Hofer-Julian** [comment]
I run 
```pip3 install --prefix=/app --no-deps .

```
to install vorta in the flatpak. Could it be the no-deps flag?

**Comment by Hofer-Julian** [comment]
Running `make translations-to-qm` before installing Vorta worked.
I'd be still interested to understand where's the difference between installing Vorta from PyPi or from local folders, that results in translation only loaded when installed from PyPi

**Comment by Hofer-Julian** [comment]
Also, someone pointed out that these `mkdir` and `cp` [lines](https://github.com/borgbase/vorta/blob/d7ee812cf903f54dabdb3071cff52a1230cfa5f8/flatpak/com.borgbase.vorta.yaml#L73) should be part of the installation process.

Do you think they could or even should be included in the Makefile?

**Comment by m3nu** [comment]
If the translation files are needed for flatpak, then the Flatpak Makefile job can have the `translations-to-qm` as dependency. Same as the PyPi release.

**Comment by Hofer-Julian** [comment]
So we could put all of this:

```
- make translations-to-qm
      - pip3 install --prefix=/app --no-deps .
      - mkdir -p /app/share/metainfo/
      - cp src/vorta/assets/metadata/com.borgbase.Vorta.appdata.xml /app/share/metainfo/
      - mkdir -p /app/share/icons/hicolor/512x512/apps/
      - cp src/vorta/assets/icons/512x512/com.borgbase.Vorta.png /app/share/icons/hicolor/512x512/apps/
      - mkdir -p /app/share/icons/hicolor/256x256/apps/
      - cp src/vorta/assets/icons/256x256/com.borgbase.Vorta.png /app/share/icons/hicolor/256x256/apps/
      - mkdir -p /app/share/icons/hicolor/128x128/apps/
      - cp src/vorta/assets/icons/128x128/com.borgbase.Vorta.png /app/share/icons/hicolor/128x128/apps/
      - mkdir -p /app/share/icons/hicolor/64x64/apps/
      - cp src/vorta/assets/icons/64x64/com.borgbase.Vorta.png /app/share/icons/hicolor/64x64/apps/
      - mkdir -p /app/share/icons/hicolor/48x48/apps/
      - cp src/vorta/assets/icons/48x48/com.borgbase.Vorta.png /app/share/icons/hicolor/48x48/apps/
      - mkdir -p /app/share/icons/hicolor/32x32/apps/
      - cp src/vorta/assets/icons/32x32/com.borgbase.Vorta.png /app/share/icons/hicolor/32x32/apps/
      - mkdir -p /app/share/icons/hicolor/24x24/apps/
      - cp src/vorta/assets/icons/24x24/com.borgbase.Vorta.png /app/share/icons/hicolor/24x24/apps/
      - mkdir -p /app/share/applications/
      - cp src/vorta/assets/metadata/com.borgbase.Vorta.desktop /app/share/applications/

```

in a flatpak Makefile job?
