### ISSUE TITLE
Password - for SSH or repository?

### ISSUE THREAD

**Issue by jans23** [borgbase/vorta#309]
While adding an existing remote repository, I entered the repository URL and below it the SSH password. Later I realized that I had to enter the repository password instead of the SSH password. Perhaps to avoid confusion in the future this could be clarified by renaming "password" to "repository password".

**Comment by m3nu** [comment]
Yeah. Can make sense to rename it.

**Comment by Hofer-Julian** [comment]
I wonder: Is it currently possible to use password-protected SSH Keys in Vorta?

**Comment by m3nu** [comment]
Yes, as long as you add them to ssh-agent first.

**Comment by ThomasWaldmann** [comment]
I'ld recommend using the same terminology as borg uses.

Thus, not "repo password", but "borg passphrase" (see also env var BORG_PASSPHRASE, https://borgbackup.readthedocs.io/en/stable/usage/general.html#environment-variables ).
