### ISSUE TITLE
No notification on Linux

### ISSUE THREAD

**Issue by jans23** [borgbase/vorta#312]
I use Ubuntu Linux 18.04 and in Vorta enabled both notifications (error and success). I never got a notification displayed. Do I need to install a certain package perhaps?

**Comment by Hofer-Julian** [comment]
How did you install Vorta?

**Comment by jans23** [comment]
pip3 install vorta

**Comment by Hofer-Julian** [comment]
Could you please check if you have the same problem with [flatpak](https://flathub.org/apps/details/com.borgbase.Vorta)?

**Comment by jans23** [comment]
I'm trying to... but when opening Flatpak-Vorta it doesn't recognize my configuration stored with pip-Vorta. Could I migrate the configuration somehow?

**Comment by Hofer-Julian** [comment]
Yes, it is stored on different places.

It should work to copy `settings.db` from `~/.local/share/Vorta` to `~/.var/app/com.borgbase.Vorta`/data/Vorta

**Comment by jans23** [comment]
Flatpak-Vorta doesn't prompt me for the SSH password (of remote repository). Another package which should be installed?

**Comment by Hofer-Julian** [comment]
Does that work on pip-Vorta?

**Comment by jans23** [comment]
Yes, ssh-askpass jumps in (after manually installing it).

**Comment by Hofer-Julian** [comment]
Then this is might be a bug of Flatpak-Vorta.
It would be great if you could open an issue for that.

Could you try if you get notifications with Flatpak-Vorta for a remote repository without ssh-password or a local repository?

**Comment by jans23** [comment]
Using Flatpak-Vorta, I setup a test profile and performed a small backup. No notification is displayed at the end while the setting to display notification is enabled.

**Comment by Hofer-Julian** [comment]
You use Ubuntu 18.04 with GNOME, right?

**Comment by jans23** [comment]
right.

**Comment by Hofer-Julian** [comment]
I will try to reproduce your errors on a virtual machine.

**Comment by jans23** [comment]
Thanks. BTW, very cool project!

**Comment by Hofer-Julian** [comment]
I could not reproduce your issue.
How did you test it?
Notifications only appear on scheduled backups not manual ones

**Comment by Hofer-Julian** [comment]
I could not reproduce your issue.
How did you test it?
Notifications only appear on scheduled backups not manual ones

**Comment by jans23** [comment]
The issue was that I expected notifications also for manually started operations. Notifications for scheduled operations do work. Given the fact that most operations take a long time, showing notifications would be good also for manually started operations, IMHO.

**Comment by m3nu** [comment]
For manual operations, we only show error messages. If everything goes smooth, the user doesn't need one more notification after already clicking the button before. Could be done differently of course, but I see no strong reason to change it for now.
