### ISSUE TITLE
Use .nobackup by default, if no other exclusions set

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#314]
**Is your feature request related to a problem? Please describe.**
Without user action, Vorta will show `.nobackup` under the sources tab, suggesting that this is the default. In reality, we don't exclude anything unless the user adds his own settings in that field.

This lead to some confusion, where the functionality was expected:

> My misunderstanding comes from the fact that I believed that .nobackup was automatically used as a filter, but now I think that it’s just a suggestion in the interface (which is why it’s dimmed). I added it explicitely and now it does work!

**Describe the solution you'd like**
1. Actually exclude folders with `.nobackup` file when the user doesn't change the field.
2. Change the text to make it clear that the placeholder has now effect. Maybe like this: `E.g. .nobackup`

**Comment by gtivey** [comment]
Hi all --- Run into this issue today when I tried to backup with a .nobackup file in an early directory in the backup process without success. After finding this post, I was able to tag the directory with an .exclude file and it worked just fine. Thanks for the post!

**Comment by m3nu** [comment]
I've changed the placeholder text a bit. Since the `.nobackup` file isn't really a standard, I'm reluctant to add it as default. But the misunderstanding described above should still be avoided.

![Screen Shot 2020-06-01 at 13 41 38](https://user-images.githubusercontent.com/3916435/83379299-b798dc80-a40d-11ea-9a6a-ac0d7ace8294.jpg)

**Comment by sudwhiwdh** [comment]
> But the misunderstanding described above should still be avoided.

I am actually a little irritated by the (new) placeholders texts as well.
/.DS_Store looks like a macOS-only thing. And under Linux CACHE would probably be ~/.cache. I have never heard of .nobackup by the way. Maybe we can find some cross-system examples that will give the users an idea of what it is all about?

**Comment by m3nu** [comment]
`.nobackup` and `CACHE` (or `CACHEDIR.TAG`) are both examples from [Borg](https://borgbackup.readthedocs.io/en/stable/usage/create.html) or [Borgmatic](https://torsion.org/borgmatic/docs/reference/configuration/). Not making stuff up here.

How about `**/.cache` and `.nobackup` as examples?

**Comment by Hofer-Julian** [comment]
> How about `**/.cache` and `.nobackup` as examples?

Yeah, that would probably be better.

**Comment by sudwhiwdh** [comment]
`.nobackup` is also macOS only, right?
Is `**/.cache` the macOS equivalent of `~/.cache` on my Linux system?

How about if the Vorta shows the appropriate examples depending on my existing system?

**Comment by m3nu** [comment]
macOS uses file attributes and folder lists, not `.nobackup`. It's not a standard from what I know, but I saw it used in Borg issues and in the Borgmatic docs, as already linked [here](https://github.com/borgbase/vorta/issues/314#issuecomment-636785129).

`**/.cache` just means to exclude the folder in all **subfolders**. See the official borg docs for details. The shell expansion `~` is equivalent on Linux and macOS (as are most other things 🤓) 

Hope this clarifies it. If you have better placeholders, please let me know by tomorrow, so I can merge the next PR. Thanks!

**Comment by sudwhiwdh** [comment]
My last comment was probably posted too early. I completed it.

I had noticed your comparisons with the documentaries of Borg and Borgmatic. But I wonder if it doesn't take a lot of technical knowledge to understand these options. And whether it needs examples that are closer to everyday life. Hence my reference to Déjà Dup Backups.

**Comment by m3nu** [comment]
The issue with your Deja Dup comparison is that one can only add folders, not expressions that apply to many files and folders. So the current field may be confusing to some, but offers more power and reflects the functionality provided by Borg. I use it to e.g. exclude all video files across many project folders.

Instead of .nobackup, we could also use .gitignore, which is very familiar. Or both.

**Comment by sudwhiwdh** [comment]
Thanks for the clarity!
Then I think it would be good if there were examples for folders/files as well as for patterns. Then you can see the whole range of Borg. How do you feel about that? Or is it not Borg's idea that at this point folders should also be excluded?

And still open for me: What do you think about making the examples dependent on the system?

Exactly, .gitignore would be understandable, at least in the programming world. It's also a question of Vorta's target group, isn't it?

**Comment by sudwhiwdh** [comment]
Still not clear to me then: Do we need the split screen in Vorta at this point?

**Comment by m3nu** [comment]
The two bottom fields do different things and cant be combined.
