### ISSUE TITLE
Include ssh-askpass in Flatpak build

### ISSUE THREAD

**Issue by jans23** [borgbase/vorta#316]
When using Vorta installed with pip, ssh-askpass prompts for the SSH password. When using Vorta being installed from Flatpak, it doesn't ask for SSH password but instead remote access fails.

System: Ubuntu Linux 18.04, Vorta 0.6.21.

**Comment by Hofer-Julian** [comment]
https://github.com/KDE/ksshaskpass and https://github.com/lxqt/lxqt-openssh-askpass might be alternatives

**Comment by jans23** [comment]
How about https://gnupg.org/related_software/pinentry/ ?

**Comment by prefixtry** [comment]
@Hofer-Julian Is there a solution you favor yet?
OpenSSH has https://man.openbsd.org/ssh-add
How GNOME's Keyring does it https://wiki.gnome.org/Projects/GnomeKeyring/Ssh

**Comment by prefixtry** [comment]
@Hofer-Julian What requirements do you see for solving this issue?

**Comment by Hofer-Julian** [comment]
A program similar to ssh-askpass, but using wayland instead of x11, but in the ideal case is able to use x11 as a fallback.

**Comment by Hofer-Julian** [comment]
But I guess it is not a strict requirement...

**Comment by prefixtry** [comment]
you mean a fallback mode?

**Comment by jans23** [comment]
This issue is still relevant for me. Any idea how to make Vorta ask for SSH passphrase?
