### ISSUE TITLE
Is ~1GB really necessary to install vorta?

### ISSUE THREAD

**Issue by adatum** [borgbase/vorta#322]
Installing the Flatpack requires this  many dependencies? Using Fedora 30.

`flatpak install vorta`

![vorta_install](https://user-images.githubusercontent.com/9773655/60690179-3b131c00-9e93-11e9-8fdf-6106ebd8bb59.png)

Maybe I'm doing something wrong. I'm not familiar with Flatpak.

**Comment by Hofer-Julian** [comment]
Big runtimes are the prize you have to pay for having platform-independent  packages.
However, for further flatpaks the size becomes smaller as they share resources.
