### ISSUE TITLE
Oversized profile selection drop down

### ISSUE THREAD

**Issue by RlndVt** [borgbase/vorta#326]
**Describe the bug**
The ~first~ current entry in the drop down menu in the profile selection is oversized.
See screenshot

![Screenshot_20190711_104726](https://user-images.githubusercontent.com/1658570/61036655-caf02300-a3c9-11e9-9a18-7162f182f368.png)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Vorta: 0.6.21

Vorta installed from AUR.

**Comment by Hofer-Julian** [comment]
Could you please try the [flatpak](https://flathub.org/apps/details/com.borgbase.Vorta) to determine if this is an AUR-specific problem?

You can copy  `settings.db` from `~/.local/share/Vorta` to `~/.var/app/com.borgbase.Vorta/data/Vorta`

**Comment by RlndVt** [comment]
Just tried it. The flatpak version does not have the issue.

Roland

**Comment by Hofer-Julian** [comment]
Okay, then maybe https://aur.archlinux.org/packages/vorta/ is a better place to discuss this problem :)

**Comment by RlndVt** [comment]
On the other hand, the AUR packagebuild only pulls the binary from github [1].

[1] https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vorta

**Comment by Hofer-Julian** [comment]
Well, kinda...

The flatpak solves the issue, so there could be multiple reasons for that:
- problems with Arch/Manjaro that potentially be fixed in the AUR
- it works on a fresh install but not on your installation with updates and additional packages
- problems because of your theme or other modifications on your system

If you want to help, you could install Manjaro with the same desktop environment as you use in a virtual machine and test if the AUR works there 

If it does not, then we would be one step closer to solving your problem :)

**Comment by m3nu** [comment]
I wouldn't know where to fix this in Vorta, since we simply tell Qt to make a dropdown. We don't specify anything.

Since you use the dark theme, have you tried the light theme instead? Could also be a styling issue in the dark theme style we use. @RlndVt

**Comment by RlndVt** [comment]
Disabling dark theme fixes the issue. Dark theme with flatpak does work
though.

I'm spinning up a manjaro VM to test further.

Roland Vet

**Comment by RlndVt** [comment]
In Manjaro VM I added a profile, switched to dark theme, and the menu became oversized again.

**Comment by m3nu** [comment]
Possibly an issue with the dark theme stylesheet (an external project we use). Will see if they have an open issue for it.

Let's still keep this open until then to keep track.

**Comment by Hofer-Julian** [comment]
I'd rather suggest to look into archs python-qdarkstyle package, as it works with the flatpak

**Comment by m3nu** [comment]
Here we go. A rather fresh issue: https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/200

I'm guessing pip pulls a newer version than is packaged in `python-qdarkstyle`

**Comment by Hofer-Julian** [comment]
Or an older one, as the version is hardcoded and manjaro is bleeding edge.

**Comment by RlndVt** [comment]
Tested a kubuntu 19.04 VM and no issue.

Both Manjaro and Kubuntu used qdarkstyle 2.7. However Manjaro uses PyQt5 Qt Version 5.13.0 vs 5.12.2. Could the issue be there? This matches the bug report @m3nu found.

**Comment by Hofer-Julian** [comment]
Flatpak uses 5.11, that could be the problem.

**Comment by philipkozeny** [comment]
Just to weigh in: also happens on macOS (10.15.4), only in dark mode.

**Comment by m3nu** [comment]
Vorta doesn't include any kind of dark style directly. We use an [external project](https://github.com/ColinDuquesnoy/QDarkStyleSheet) for it. You probably want to report your issue there.

**Comment by m3nu** [comment]
Related: https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/200

**Comment by m3nu** [comment]
Applying the fix mentioned in this PR also fixes it. But I'm not sure we should add it. Still did a PR for it: #448 . You can see if this fixes it for you.
