### ISSUE TITLE
Run check on selected archive only (if one is selected)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#33]
hmm, is there no repo (or repo+archives) check, just single archives?

**Comment by m3nu** [comment]
The command used is `['borg', 'check', '--info', '--log-json']` [here](https://github.com/borgbase/vorta/blob/master/src/vorta/borg/check.py#L25). This should use the [defaults](https://borgbackup.readthedocs.io/en/stable/usage/check.html), which ist to first check the repo and then the archive.

**Comment by ThomasWaldmann** [comment]
Ah, ok. If it runs check on the repo url (not an archive url), it checks everything.
I only tested it with a very small repo, so I just saw the last message which was talking about some archive.

**Comment by m3nu** [comment]
For `mount` the behavior is to mount the selected archive if one is selected and the whole repo when none is selected. The same behavior would make sense for `check` as well.
