### ISSUE TITLE
documentation: document data recovery

### ISSUE THREAD

**Issue by goebbe** [borgbase/vorta#330]
**Is your feature request related to a problem? Please describe.**
If your computer breaks or is lost or is hacked, you probably want to recover from your backup. 
To my knowledge there, is currently no documentation about the recovery process, using Vorta, for this type of use case.

**Describe the solution you'd like**
- provide a short documentation of the recovery process, provide links to the basic tools (e.g. borg). 
- Document the conditions for recovery: 
 a) You need a computer with Vorta installed
 b) You need to have the **password** for the repository! (which may only be saved in the keyring of the stolen computer) 
 c) You need to have the info (server password) that is necessary to access your repository on a backup server. :-) 

 - You should probably keep a paper-copy with the info necessary for a) and b) at a save place. 
 - Should Vorta provide a way to easily print the required information?

**Describe alternatives you've considered**

**Comment by m3nu** [comment]
I'm actually looking to add a proper website with landing page (for new users) and some documentation for existing users. Preferably managed as Markdown via Github. This will go in there.

**Comment by m3nu** [comment]
https://vorta.borgbase.com/usage/restore/

Partly covered here now.

**Comment by m3nu** [comment]
Added this to the restore docs: https://vorta.borgbase.com/usage/restore/
