### ISSUE TITLE
Alert on missing Borg binary instead of showing placeholder version number

### ISSUE THREAD

**Issue by goebbe** [borgbase/vorta#333]
I installed Vorta with the pip3 method on GalliumOS (Linux OS, GUI:Xfce) and had the following minor issue:
Since I did **not install borg** before, Vorta complained nicely, when I tried to create a test-repository. 
However, in **Vorta>Misc**   the information about the borg Version was wrong, since it showed: 
**Borg Version: 1.1.10**        
However, borg was not installed at all. 

Expected behaviour: 
If borg is not available Vorta should show this in the Misc tab. Something like: 
**Borg Version: not installed**

**Desktop (please complete the following information):**
- Linux Gallium OS 3.0 
kernel 4.1.18-galliumos    GUI: Xfce

**Comment by m3nu** [comment]
I think you're seeing the default version I put there. No Borg at all is not reported for now, but should.

**Comment by m3nu** [comment]
Added a simple notification for this.

![Screen Shot 2020-06-01 at 12 47 20](https://user-images.githubusercontent.com/3916435/83376774-13f7fe00-a406-11ea-8401-abdcaa04574b.jpg)
