### ISSUE TITLE
selected item extract option

### ISSUE THREAD

**Issue by JackDinn** [borgbase/vorta#336]
I'm not sure if I'm understanding this correctly but am i supposed to be able to extract single/multiple files/folders from the extract option ?

I can only select a single item.
No matter what i select it will extract the whole archive.

I know i can mount the archive and "grab" whatever i need but i was wondering because it mentions about selecting folders at the bottom of the extract GUI.
![Screenshot](https://i.imgur.com/PHw3ymH.png)

vorta 0.6.21-1
Kernel: 5.1.19-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.1.0 Desktop: KDE Plasma 5.16.3 Distro: Manjaro Linux

**Comment by m3nu** [comment]
Generally anything you select is appended to the list of paths to extract. Which command is run (see logs)?

Files below a selection are always extracted, no matter what.

**Comment by JackDinn** [comment]
In the screen shot iv shown i selected just the one file but it extracts the whole archive. It does not matter what i select it extracts everything.
Plus i can only select a single item, holding shift or Ctrl does not allow multi-select.

I shall go and setup a small test archive, select a single file and post the logs.

**Comment by Hofer-Julian** [comment]
Just to be sure: Is it possible that you oversaw the small checkboxes left to the file?

They are hard to see because of your theme

**Comment by JackDinn** [comment]
Ahha , lol. there is a checkbox ^^. Dam my kde theme tinkering has made it invisible to me. Thx

**Comment by m3nu** [comment]
Good diagnosis, @Hofer-Julian . I thought it's just the screenshot.

**Comment by JackDinn** [comment]
is a bit weird as i cant find any other gui's with "invisible" tick-boxes, maybe its just the list-box's or tree-view with ticks (in whatever you are using for the GUI). Now i know its fine though.
Thank you :+1:
