### ISSUE TITLE
Why is vorta using 500MB+ memory when in tray?

### ISSUE THREAD

**Issue by JackDinn** [borgbase/vorta#337]
Yesterday i noticed vorta was using over half a Gig of memory, I just restarted it and continued with my day but this morning i notice that again it was creeping up and was at 300MB+
![](https://i.imgur.com/i9KAwRh.png)

Vorta 0.6.21
System:    Host: greg-pc Kernel: 5.1.19-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.1.0 Desktop: KDE Plasma 5.16.3 

As i write this its now up to 370MB, please advise.

**Comment by m3nu** [comment]
PyQt isn't very efficient with RAM. Usage should be a bit lower when the settings window is closed.

You can also look into the upcoming Go implementation. It's a lot more efficient, but doesn't have all the features of the Python version yet.

https://github.com/borgbase/vorta-go

**Comment by JackDinn** [comment]
> Usage should be a bit lower when the settings window is closed.
This memory usage is with the settings window closed.

I shall take a quick look at the go front-end, thx.

**Comment by m3nu** [comment]
While I'd love to improve memory usage, this is mainly down to Qt. If there are still any specific steps we could do in the context of this project, please share here. Until then I'm closing it.

**Comment by m3nu** [comment]
Also: RAM usage on macOS is just 129 MB with the main window closed. Not great, but not 500 MB either.

![Screen Shot 2020-05-28 at 12 02 58](https://user-images.githubusercontent.com/3916435/83097660-3ffc4200-a0db-11ea-8ee9-84f2bdb7efe6.jpg)

**Comment by justauserid** [comment]
> Also: RAM usage on macOS is just 129 MB with the main window closed. Not great, but not 500 MB either.

<img width="723" height="136" alt="Image" src="https://github.com/user-attachments/assets/86f68d9f-3b22-463a-a41a-3edee240abb9" />

Looks like it has increased now. For main process the real memory us showing ~110MB as shown by you but total memory usage does contribute in causing memory pressure esp. in the age of local LLMs :-)

**Comment by ThomasWaldmann** [comment]
Yay! #2551

**Comment by m3nu** [comment]
Great memory gains, @ThomasWaldmann . Just did a build and it's down to 27 MB of compressed VM 🙌

<img width="702" height="113" alt="Image" src="https://github.com/user-attachments/assets/12743a77-f188-46ea-a128-5dc083473daa" />
