### ISSUE TITLE
After deletion of a backup, I still see cached statistic data of the previous backup

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#338]
After deletion of a backup, I still see cached statistic data of the previous backup even after stopping Vorta and restarting.

The Archive page is empty (as expected).

![grafik](https://user-images.githubusercontent.com/1151915/62084741-4707b900-b25a-11e9-806d-e00ea0d780d0.png)

![grafik](https://user-images.githubusercontent.com/1151915/62084902-9fd75180-b25a-11e9-8754-fc53b6211c6e.png)

* Vorta 0.6.21
* borgbackup 1.1.5

**Comment by m3nu** [comment]
We only get those numbers form `borg create` and `borg info`. That means we need to run 3 commands when you delete a repo. (we already run `borg list` after each delete or prune.)

Worth it to have those numbers right?

**Comment by sudwhiwdh** [comment]
Sounds reasonable!

**Comment by m3nu** [comment]
I suggest to just clear those repo numbers on prune or delete and show `N/A` or something. Then after the next create, the correct numbers will be avail again.

**Comment by sudwhiwdh** [comment]
show `N/A` would be nice, yes!
