### ISSUE TITLE
Profile prune/preview options do not refresh when another profile is chosen

### ISSUE THREAD

**Issue by fantom-x** [borgbase/vorta#339]
**Describe the bug**
I have created two profiles and according to the message the prune settings are supposed to be applied per a profile, but they stay the same and do not refresh when switching profiles.

A second issue on the same page: the Preview values do not refresh either. The Prefix/Name do refresh, but not the previews.

**To Reproduce**
Create two profiles
Set prune options on one
Switch profile
Modify the prune options

**Desktop (please complete the following information):**
MacOS latest

**Comment by m3nu** [comment]
Thanks for reporting. Could be a bug while re-populating the tabs during profile changes. Will check it out.

**Comment by fantom-x** [comment]
Thx; it makes things really confusing if one wants months/years of backups for one profile while only keeping a week's worth of backups for the other one: easy to lose data this way.

**Comment by fantom-x** [comment]
Looks like all the other tabs are refreshing fine; the issue seems to be isolated to the "Archives" tab.

**Comment by fantom-x** [comment]
Back up schedule has a similar issue: change backup frequency for one profile, switch to another, and then back. The value displayed is the old one.

**Comment by m3nu** [comment]
Added a fix for the original issue.

**Comment by fantom-x** [comment]
If I apply this change directly to the installed Vorta.app, will it confuse the auto updated later on?

**Comment by fantom-x** [comment]
Oh, I forgot that Vorta is one single compiled app. I will have to wait until the next release.

**Comment by fantom-x** [comment]
Thank you for the fix: the prune schedule is now refreshing properly. The preview for **Archine Name** & **Prune Prefix** still do not.

**Comment by m3nu** [comment]
I'm having trouble reproducing this issue. Would you mind providing the template string you are using for those settings? Maybe a formatting error?

<img width="584" alt="Screen Shot 2019-10-12 at 22 25 21" src="https://user-images.githubusercontent.com/3916435/66702921-5c5f9000-ed3f-11e9-8efc-799b744989ef.png">

**Comment by fantom-x** [comment]
I have two profiles and each is using the same templates as per below. The **Preview** lines under those template strings do not get refreshed when a different **Active Profile** is selected.

Archive Name: **{profile_slug}-{now:%Y-%m-%dT%H:%M:%S}**
Prune Prefix:   **{profile_slug}-**

**Comment by m3nu** [comment]
Changed the profile a few times. Still no luck reproducing.

Does it work without variables? What's the system and Python version? Anything in the log (Misc > Log) or console?

**Comment by fantom-x** [comment]
```
python --version
Python 2.7.16
```
MacOS 10.14.6 (Mojave). There is nothing in the logs.

No worries; it is just an annoyance: the archives are named correctly, it is just a refresh. Likely not worth the time.

In case this helps: if I modify any template string, its preview immediately refreshes. Then when I switch the profile, the previews remain unchanged: one preview is from one profile and the other is from the other. I change any template and its preview immediately refreshes properly.

**Comment by fantom-x** [comment]
Turned out I have two python installations: one from MacOS and one from brew. The default one (via PATH) is from brew (2.7.16). The one from MacOS is 2.7.10. I am not sure which one is used by Vorta though.

/usr/bin/python
/usr/local/bin/python

**Comment by m3nu** [comment]
Then something is off. Vorta won't work with Python 2 at all. 3.6 or higher only.

Are you using the macOS app bundle from the Release page or did you install it with `pip`?

**Comment by fantom-x** [comment]
I never used **pip** directly on this MacOS.

```
python3 --version
Python 3.7.4
```

**Comment by m3nu** [comment]
Tried again to reproduce without luck. Will close this now.

If the issue still occurs, just reply here with new details. Thanks!
