### ISSUE TITLE
passphrase vs. sentry

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#34]
"During beta, crash reports are sent to [Sentry](https://sentry.io) to quickly find bugs. You can disable this by setting the env variable `NO_SENTRY=1`."

It would be interesting to document whether in case of a crash (and thus data transfer to sentry) the borg passphrase is transmitted or not.

**Comment by ThomasWaldmann** [comment]
hmm, `BORG_PASSPHRASE` is not in their list, so guess it might not get scrubbed?

**Comment by m3nu** [comment]
I added that key as additional "sensitive parameter". But it's a server-side setting unfortunately.

<img width="772" alt="screenshot 2018-11-21 at 23 18 13" src="https://user-images.githubusercontent.com/3916435/48850516-d57e8d80-ede3-11e8-990c-8ba0174ae716.png">

So I added some client-side filtering for those two keys as well in a72f84f.
