### ISSUE TITLE
Crash when re-opening main window during repo setup

### ISSUE THREAD

**Issue by fantom-x** [borgbase/vorta#340]
**Describe the bug**
Crash

**To Reproduce**
Start Vorta in MacOS
Click on the icon and bring up the Vorta interface
Select "Initialize New Backup Repository"
Leave it open, do not enter anything
Here I went to a different window (Files, Safari, etc) but it is not necessary: the next step will crash Vorta
Go back to the icon and bring the Vorta interface again: when it is hidden, using the icon is a convenient way of getting Vorta back in the view
Vorta crashes now

**Desktop (please complete the following information):**
MacOS latest
Vorta latest

**Comment by m3nu** [comment]
I can reproduce this. The precise error is:

```
Traceback (most recent call last):
  File "vorta/views/repo_tab.py", line 159, in repo_select_action
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted
[1]    8147 abort      ./dist/Vorta.app/Contents/MacOS/vorta-darwin
```

**Comment by samuel-w** [comment]
Is this bug still present in 0.7.1?

**Comment by m3nu** [comment]
Still present.

```
Traceback (most recent call last):
  File "/Users/manu/Workspace/vorta/src/vorta/views/repo_tab.py", line 171, in repo_select_action
    self.repoSelector.setCurrentIndex(0)
RuntimeError: wrapped C/C++ object of type QComboBox has been deleted
```

The issue is that we shouldn't redo the main window, but only bring it to the foreground. One line change, but it may be possible to simplify `open_main_window_action()` and `toggle_main_window_visibility()` further.

```
    def open_main_window_action(self):
        if not self._main_window_exists():
            self.main_window = MainWindow(self)
        self.main_window.show()
        self.main_window.raise_()
```

**Comment by m3nu** [comment]
Added the fix suggested above.
