### ISSUE TITLE
Archives tab does not display size/duration after adding an existing repository

### ISSUE THREAD

**Issue by fantom-x** [borgbase/vorta#341]
**Describe the bug**

**To Reproduce**
Create a new repo
Create a few backups
Check that the Archive tab displays size/duration
Unlink the repo
Add it again: the Archive time show the individual backups, but not sizes
Create a new backup: the size/duration of the this backup will be displayed

The screen shot below has three backups: two before unlinking/adding and one after
<img width="214" alt="image" src="https://user-images.githubusercontent.com/5624569/62815420-b5643b00-bae6-11e9-8fd3-5307ff30297b.png">

**Comment by m3nu** [comment]
This is a limitation of the data we get from Borg: It's not available after the actual backup run and we don't get it later from the list command.

If you know a way to get it after the fact, please let me know and it will be implemented.

**Comment by fantom-x** [comment]
Cannot try it right now, but it looks like “borg list” can be used to list files in each archive with “dcsize: deduplicated compressed size”. Is that not feasible?

**Comment by m3nu** [comment]
Currently we use something like:

`$ borg --info --log-json list --json hf70hqb8@hf70hqb8.repo.borgbase.com:repo`

to get a list of existing archives in a repo. This results in output like this:

```
{
    "archives": [
        {
            "archive": "archive-name",
            "barchive": "archive-name",
            "id": "23edc79ff28dfdd4294f22cc885c38f9a239f3b79a4669d16c8f746234172a80",
            "name": "archive-name",
            "start": "2019-08-10T09:52:19.000000",
            "time": "2019-08-10T09:52:19.000000"
        }
    ],
    "encryption": {
        "mode": "none"
    },
    "repository": {
        "id": "feb5431a5e1caab9931a643eb9a121756f2b0a9cc7190c2b6e19399f90e89fbe",
        "last_modified": "2019-08-10T09:52:19.000000",
        "location": "ssh://hf70hqb8@hf70hqb8.repo.borgbase.com/./repo"
    }
}
```

Where could I find `dcsize` without calling another command on each archive?

If we really want this changed and *IF* the data is available to Borg itself, we could add an upstream PR there.

**Comment by fantom-x** [comment]
I think it would be a separate call per each archive to list all files with sizes and then add them all up. I was thinking that that could be done when 1) adding an existing archive and/or 2) testing an archive and/or 3) during a backup.
But I cannot claim I understand borg that well. I will see what I can dig out.

**Comment by m3nu** [comment]
Doing one call per archive will take too long for users with many archives. That's why I decided to only use this data, when the archive was created by Vorta and the details saved at creating time.

But do let me know what you find when looking into it with a fresh set of eyes.

**Comment by fantom-x** [comment]
My last idea is to do a lazy backfill: every backup Vorta picks the latest archive with no size and calculates its size and caches it. The thing about caching is that once archives start being pruned, the cached sizes get wrong. At least the very first one.
If borg does not save this data, then no matter who does the calculations, it will take a while for a lot of archives.

**Comment by fantom-x** [comment]
I have no access to my computer now, but “borg info /path/to/repo —last 99999999999999999” returns archive sizes in one command.

**Comment by fantom-x** [comment]
Yup, "borg info {repo} --last 99999 --json" returns sizes for all archives like below:

            "stats": {
                "compressed_size": 64652667538,
                "deduplicated_size": 34103681,
                "nfiles": 169,
                "original_size": 151332586014
            },

**Comment by m3nu** [comment]
That's great. So we can show a lot more data for old repos.

**Comment by fantom-x** [comment]
But the sizes are not static information: they charge after each prune; a the very least the oldest archive size will change for sure.

**Comment by m3nu** [comment]
Just tested `borg info {repo} --last 99999 --json` and the speed was magnitudes slower. Seconds vs. tens of minutes. Not even a large repo. I think we'll stick with `borg list` for now and have fewer data in exchange for speed.

But thanks for the pointer and the suggestion.
