### ISSUE TITLE
Pyinstaller-packaged assets, like icons get cleaned from temp folder

### ISSUE THREAD

**Issue by Lazza** [borgbase/vorta#344]
**Describe the bug**

After Vorta is open for a while, the tray icon disappears. Here it is(n't):

![Schermata 2019-08-11 alle 19 29 19](https://user-images.githubusercontent.com/8294041/62837316-73660100-bc6e-11e9-9c0a-fd82fd8b54a2.png)

**To Reproduce**
1. Open Vorta
2. Wait...
3. See the icon disappear

**Desktop (please complete the following information):**
- OS: macOS Mojave 10.14.6
- Theme: light
- Hardware: Macbook Pro (Retina, 15-inch, Mid 2014)

**Additional context**

I have a hourly scheduled backup. The issue appears randomly and the icon comes back if I restart Vorta... then it disappears after some time.

**Comment by m3nu** [comment]
Hi and thanks for reporting. You don't have any additional logs or messages when running it attached to a terminal?

This could be an issue with Pyinstaller: on start it unpacks files to a temporary folder. Sometimes the OS will clean those files (including the icon file) after a few days. I've seen it with another Pyinstaller deployment on CentOS.

One solution is to avoid those files from being cleaned at the OS level. I'm not sure if this applies to macOS, but aggressive cleaning could definitely loose you your temp files. So I recommend you check that first. The logs may tell you the temp folder being used. Or `lsof`.

The other solution is to use the Golang [implementation](https://github.com/borgbase/vorta-go) that doesn't rely on temp files the way Pyinstaller does. But it's in an early stage and many functions aren't implemented.

**Comment by Lazza** [comment]
Sorry, I did not think about running it from terminal. 😅 

> Sometimes the OS will clean those files (including the icon file) after a few days

Ah, I see! I have to wait then. Unfortunately I needed a reboot yesterday. But it's true, normally I do not reboot for several days... at most, I suspend the laptop.

Hopefull the problem will manifest again, as it usually does, and I can check the temporary folder.

**Comment by Lazza** [comment]
Today the icon disappeared again. I checked the files with `lsof` and found the temporary path.

The icons are gone:

![Schermata 2019-08-18 alle 17 43 22](https://user-images.githubusercontent.com/8294041/63226842-d102cc00-c1df-11e9-8c04-51f6210a3df7.png)

**Comment by m3nu** [comment]
Then it's probably the pyinstaller issue I suspected. Files get cleaned up after some time.

**Comment by adamluk** [comment]
https://github.com/pyinstaller/pyinstaller/issues/3301

Potential solution?

**Comment by m3nu** [comment]
I made some changes to macOS packaging and the latest version doesn't use a temp folder any more. This should resolve the issues described here. Would be nice if someone could do some testing with this release:

https://files.qmax.us/vorta/Vorta-0.6.24-testing-signed-borg.dmg

**Comment by adamluk** [comment]
Currently using this release - will update here, thanks Manu.
