### ISSUE TITLE
Prevent backup of unusual volume of data

### ISSUE THREAD

**Issue by arthurlogilab** [borgbase/vorta#345]
**Is your feature request related to a problem? Please describe.**
After having defined a clear perimeter for the backup, for example for something that uses 5Go of storage, if for some reason that doubles or increases in a an unexpected fashion, I would love vorta to warn me, before or after actually sending the data to the remote storage. 

**Describe the solution you'd like**

Describe what is expected of the data : for example growth of more that 50% of the size is a problem. 

Before backing up, evaluate the size to be transferred. Pause the backup and alert the user. If additional information about what caused the size increase can be given that would be great. 

For example "Are you sure you want to backup ubuntu-19.04-amd64.iso ?". That way the user can move it to a non backuped up location or add it to the ignored patterns. 

**Describe alternatives you've considered**
When a backup has grown in an unexpected manner, a user has to go though his files, delete or move the data, then create a new backup and delete the snapshot that was "too big".

**Comment by m3nu** [comment]
I understand your use case, but it's not really in Vorta's scope. To do this we would have to know what a user considers "big" and scan all the backup data before running `borg`.

Sometimes I'm not fully sure on what to exclude too. Then I just watch the status logs and cancel if needed. Doesn't need to be a big file that's not wanted. Could also be a cache folder with many small files.
