### ISSUE TITLE
Vorta misses backups

### ISSUE THREAD

**Issue by fantom-x** [borgbase/vorta#347]
I just found several day's worth of missed backups and warnings like this one below. Why does not Vorta wake up the machine to do a backup? Or at the very least it could run the backup the moment the computer wakes up from sleep.

```
apscheduler.executors.default - WARNING - Run time of job "VortaScheduler.create_backup (trigger: cron[hour='*/6', minute='42'], next run at: 2019-08-15 12:42:00)" was missed by 2:58:40.527226
apscheduler.executors.default - WARNING - Run time of job "VortaScheduler.create_backup (trigger: cron[hour='6', minute='42'], next run at: 2019-08-16 06:42:00)" was missed by 2:58:40.528044
```

**Comment by m3nu** [comment]
Correct. There are no backups when the computer is turned off.

**Comment by fantom-x** [comment]
It is not turned off and it have been in use all the time, but it was apparently sleeping during each and every scheduled backup. That lasted for several days with not a single backup.
I know some MacOS apps can wake it up to do their thing. Alternatively, could Vorta display a notification that so many backups were missed? There was no warning at all.

**Comment by m3nu** [comment]
When I say "turned off", it includes hibernation.

There is no warning because it will just do a backup the next time your computer is on. For details see the external scheduler package we use.
