### ISSUE TITLE
Allow sorting Archives by any of the columns

### ISSUE THREAD

**Issue by archont00** [borgbase/vorta#349]
**Is your feature request related to a problem? Please describe.**
I keep a single repository (external HDD) for all computer archives. Hence, each archive name looks like `computer_name-date_stamp`.
Vorta seems to sort Archives only by date. Hence reviewing number of backups by computer name is difficult with a long history of backups.

**Describe the solution you'd like**
It would be nice to allow user to click on a heading of the columns (Date, Size, ..., Name) and have the list sorted up/down.

**Comment by m3nu** [comment]
Merged and will be in the next release.
