### ISSUE TITLE
How to add Google Drive as a remote backup repository?

### ISSUE THREAD

**Issue by VladimirMikulic** [borgbase/vorta#352]
As the title says, I would like to specify a folder on my Google Drive as a repository.

How can I do this?

Thanks.

**Comment by m3nu** [comment]
No. This is not a supported use case.

**Comment by VladimirMikulic** [comment]
@m3nu Do you have some plans for adding this in the future?
It would be nice to have remote storages selection(S3, Dropbox, Google Drive...)

**Comment by m3nu** [comment]
Not something that the underlying library can support.

But you can try other command line tools, called restic or rclone. They work on supporting multiple backends.

**Comment by Hofer-Julian** [comment]
I would like to add that you can create local backups with Vorta and then upload them with rclone

**Comment by VladimirMikulic** [comment]
I thought of using rclone, but I wanted to make sure that I didn't miss any features that Vorta offers.
Rclone works well.

Thanks.
