### ISSUE TITLE
Network Whitelist For Vorta on Linux

### ISSUE THREAD

**Issue by GuardedAirplane** [borgbase/vorta#355]
Currently there is no way to prevent Vorta from backing up automatically on certain networks. On my Mac, I use this feature to prevent backing up on my hotspot and my dad's satellite internet connection. My linux laptop does not have this feature, and I accidentally ate up 75% of my hotspot allowance because of it.

Implementing a Networks tab such as the one found on macOS. Looking at a past issue, it looked like getting previous networks was not supported, so perhaps allowing a manual input of SSIDs or router MAC addresses could work.

An alternative solution, might be a location based solution could be used. As in, if you are at your home address, backup, if not, don't.

**Comment by m3nu** [comment]
Yeah. Would be nice to have this for Linux. Current blocker is that I don’t know of a universal way to get a list of past Wi-Fis and the current Wi-Fi.

With this info the feature could be implemented rather easily.

**Comment by GuardedAirplane** [comment]
Would executing '$ iwgetid' in the background every so often or right before a backup operation work? That gives the current SSID, and you could store any newly observed ones in a log file to be added to the list in the GUI.

**Comment by samuel-w** [comment]
I think this is closed by #547
