### ISSUE TITLE
Vorta UI hangs when hitting Cancel

### ISSUE THREAD

**Issue by markusdd** [borgbase/vorta#357]
**Describe the bug**
After starting a backup I noticed I missed some files in the exclusion list, wo I wanted to cancel the running backup. That worked, but the UI became completely unresponsive, including the close button and tray icon. Only way to end Vorta was doing a kill form the command line.

**To Reproduce**
1) Run Fedora 29 or Fedora 30 (seen on both)
2) Deploy latest Vorta Flatpack
3) Start Vorta as normal user using flatpack run
3) setup remote repo with dedicated SSH key (not default one) and no encryption and LZ4 compression
5) Start manual Backup
6) Try to cancel after a few seconds or a minute

**Desktop (please complete the following information):**
 - OS:Fedora 29 or 30, both observed on KDE and Cinnamon

**Comment by Hofer-Julian** [comment]
Yes, unfortunately.
As already discussed at https://github.com/borgbase/vorta/issues/332
