### ISSUE TITLE
UI opens very small. Overlapping fields.

### ISSUE THREAD

**Issue by vjba** [borgbase/vorta#358]
**Describe the bug**

- Window opens very small, causing overlapping UI fields
- Desktop window does not remember window sizes.

**To Reproduce**
1. Go to tray icon
2. Click on 'Vorta for Borg Backup'
3. See error

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - DE: GNOME Shell 3.28.4

**Additional context**
Screenshots
![Screenshot from 2019-09-05 17-48-29](https://user-images.githubusercontent.com/21375278/64362560-42bf8000-cffe-11e9-9f4d-1460e990aac5.jpg)
![Screenshot from 2019-09-05 17-48-51](https://user-images.githubusercontent.com/21375278/64362468-1d327680-cffe-11e9-9eb8-b880191d4f69.png)

**Comment by Hofer-Julian** [comment]
What is your display resolution?

**Comment by vjba** [comment]
3200 x 1800 (16:9)

**Comment by Hofer-Julian** [comment]
Yeah, that's probably the reason.
Quite possible, that it wasn't tested on HiDPI yet.

**Comment by m3nu** [comment]
Tried resizing the window?

**Comment by vjba** [comment]
> Tried resizing the window?

I can resize the window. the issue is that the app window opens in the above state every time it is launched; not remembering the previous dimensions I resized it to. 

> Quite possible, that it wasn't tested on HiDPI yet.

That makes sense. Can I be of any assistance in future testing for HiDPI hardware?

**Comment by vjba** [comment]
Closing this issue.

After some further investigation I've found this is most likely an issue with flatpak + Wayland.

**Comment by Hofer-Julian** [comment]
I just tried GNOME + flatpak + Wayland.
No problems here, but I don't use a HiDPI screen

**Comment by vjba** [comment]
I've reverted to using the PyPI repository for now. UI functions as expected, but appears as it does in my original post. 

Just gotta make do and wait for some HiDPI patches.
