### ISSUE TITLE
Override permissions for `borg mount`

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#362]
**Problem**
I sometimes restore backups of remote servers. Most files there would belong to other users, like root. Using default mount options, `borg mount` will use the original permissions, thus denying access to normal users.

**Solution**
Since Vorta targets desktops, I suggest to always run `borg mount` with the following options to give the current user read access:

`borg mount -o umask=0277,uid=$UID xxx@xxx.repo.borgbase.com:repo::2019-04-30-1556602978 mnt`

**Describe alternatives you've considered**
Not aware of alternatives. The above solution only partly solves the problem. Backups that use ACL (e.g. from Synology NAS) still need to be mounted as root and won't work as normal user on macOS, even with permissions set as above. It works fine on Linux though.

Any opinion on this or issues you experienced, @Hofer-Julian @ThomasWaldmann

**Comment by ThomasWaldmann** [comment]
Well, guess it depends a bit on your goal, but if we assume it is "restoring other users' files to the state as they were at backup time", `borg mount` is not the right way anyway as it does not deal with all metadata.

Nor could you chown to the correct uid/gid if you are not root.

So, backup and restore for other users' files needs to be done as root, using borg create/extract.

**Comment by m3nu** [comment]
Thanks for weighing in. Usually my main use case with `borg mount` is to grab just a few files from the backup. I wouldn't restore a larger portion with it.

If most people use it like this, always changing the owner and permissions would make sense. So curious to get more feedback.

**Comment by Hofer-Julian** [comment]
I just tried `borg mount` without `-o umask=0277,uid=$UID` and while it did retain the original permissions, the owner of all files and directories was my current user `julian:julian`, while the user owning the files/directories on the server is `www-data:www-data`.

**Comment by m3nu** [comment]
On macOS it will retain the original user as well.

**Comment by Hofer-Julian** [comment]
> On macOS it will retain the original user as well. There seem to be small differences between OSs.

Or Fedora specific? I tried it inside and outside of a Flatpak and got the same result?

But back to the original question, I am all for adding `-o umask=0277,uid=$UID`.
I personally never had this problem, but it seems like a problem the average user might despair when confronted with it.

**Comment by m3nu** [comment]
Thanks for weighing in everyone. Did a (very simple) PR and tested with a client NAS that often loses some data. Works all well.
