### ISSUE TITLE
Run commands from the CLI (single app)

### ISSUE THREAD

**Issue by asitemade4u** [borgbase/vorta#364]
As a data scientist, I get a lot of intermediate result files, generally CSVs. I would like to save these results from the code, besides the regular schedule of backups in the Vorta backup.

It would be practical (ifit does not already exist!) to be able to launch a backup defined in Vorta as a script from the Command Line (in my case Ubuntu/bash)

Launching from the Ubuntu Vorta menu is OK, but I often forget to do so whereas with a script called from the code I am working on, I would _never_ forget...

**Comment by asitemade4u** [comment]
Another solution (but still unsatisfactory to me) would be to be able backup schedules with shorter span of time.

**Comment by Hofer-Julian** [comment]
Someone already opened an issue for that, which was closed quite immediately (https://github.com/borgbase/vorta/issues/293).

I see potential use cases for this feature as well, but at the same time it would make Vorta harder to maintain. I am unsure if the trade-off is worth it.

The only GUI I know which offers an extensive CLI is inkscape (https://github.com/borgbase/vorta/issues/293).

**Comment by Hofer-Julian** [comment]
> As a data scientist, I get a lot of intermediate result files, generally CSVs. I would like to save these results from the code, besides the regular schedule of backups in the Vorta backup.
> 
> It would be practical (ifit does not already exist!) to be able to launch a backup defined in Vorta as a script from the Command Line (in my case Ubuntu/bash)
> 
> Launching from the Ubuntu Vorta menu is OK, but I often forget to do so whereas with a script called from the code I am working on, I would _never_ forget...

What is the reason you don't use borg(matic)?

**Comment by asitemade4u** [comment]
I understand your point. However, would it be possible to add this feature:

- one defines a backup script in Vorta as usual
- a button allows to **extract** the substance of the backup script, as an interpreter would do, to a CLI script on disk
- that way, the script on disk could be executed at will while being close to the Vorta backup script -- until it is next modified, of course.

Thanks again for Vorta, which is amazing when used locally as well as with a remote server

**Comment by Hofer-Julian** [comment]
> I understand your point. However, would it be possible to add this feature:
> 
>     * one defines a backup script in Vorta as usual
> 
>     * a button allows to **extract** the substance of the backup script, as an interpreter would do, to a CLI script on disk
> 
>     * that way, the script on disk could be executed at will while being close to the Vorta backup script -- until it is next modified, of course.
> 
> 
> Thanks again for Vorta, which is amazing when used locally as well as with a remote server

That feature is discussed here https://github.com/borgbase/vorta/issues/364#issuecomment-539671003
You are welcome to give the arguments a thumb up you agree to

**Comment by samuel-w** [comment]
Do we only need to implement backup creation? If so we can do something along the lines of `vorta create --profile-name=Default` and just call create_backup_action. 
Anything else can be done by the GUI.
