### ISSUE TITLE
prune prunes too much?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#38]
I didn't practically try it, but the code looks like prune is not used with `--prefix` option.
In this case, prune specification applies to **all** archives in the repository.

If one backs up multiple clients (or in general: multiple data sets) into one rep, it will likely delete archives that should not get deleted.

So, if archive names are like `hostname-datasetname-timestamp`, we should use `--prefix hostname-datasetname-` and the prune options should be set per hostname-datasetname combination.

**Comment by m3nu** [comment]
I didn't consider this use case. To avoid unexpected prunes, I added `platform.node()` as prefix. The `create` subcommand uses it as prefix as well.
