### ISSUE TITLE
cannot select hidden folders

### ISSUE THREAD

**Issue by smily01** [borgbase/vorta#382]
I use Manjaro 18.1.0 with a Cinnamon DE. I'd like to use Vorta , but when I want to add a hidden folder in sources this isn't possible. Perhaps this is a bug?

**Comment by Hofer-Julian** [comment]
What do you mean with not possible?

Do you get an error?

**Comment by smily01** [comment]
What I mean, is that I can't see the hidden folders.

**Comment by Hofer-Julian** [comment]
Try pressing ctrl+h while the file chooser is open.

**Comment by smily01** [comment]
I already tried it, but it doesn't work.

**Comment by Hofer-Julian** [comment]
Do you get Vorta from flathub, AUR or PyPI?

**Comment by smily01** [comment]
from aur

**Comment by Hofer-Julian** [comment]
Please try the flatpak

**Comment by smily01** [comment]
I will, thank you!

**Comment by smily01** [comment]
It worked, thank you!
