### ISSUE TITLE
What permissions does the Vorta Flatpak need?

### ISSUE THREAD

**Issue by prefixtry** [borgbase/vorta#384]
And would it make sense to add them to the documentation?
https://vorta.borgbase.com/

**Comment by Hofer-Julian** [comment]
No, I don't think it makes sense to add it to the documentation.

Gnome Software is already able to display the permissions, the same goes for the CLI.

I am sure other software centers and flathub will follow.

But you can also see the permissions [in the finish-args of the manifest](https://github.com/borgbase/vorta/blob/master/flatpak/com.borgbase.Vorta.json)

**Comment by sudwhiwdh** [comment]
Does Gnome Software show permissions before or after installation?

**Comment by Hofer-Julian** [comment]
Before
