### ISSUE TITLE
Offer an alternative Flatpak download for non-technical FOSS users

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#388]
Hi, just found this Flatpak Issue. https://github.com/borgbase/vorta/issues/242
Since the repo seems to be blocked, I would like to share my comments on this topic in a new issue. Previously, I had already contacted Manuel by mail, he encouraged me to bring this to GitHub. He also told me to mention @Hofer-Julian so he can hopefully help with Flatpak.

The problem with your alternative idea https://github.com/borgbase/vorta/issues/242#issuecomment-554733473 seems to me to be that, in addition to Flathub, there is probably a need for an offer for non-technical and security-conscious users. Users who don't have the confidence to bypass the standard package management of their system (because pip does exactly that), who don't have any competence in dealing with terminals and who still want 100% free software sources. Therefore it would be perhaps really an idea to make your Flatpak available in addition to Flathub also directly under https://vorta.borgbase.com/download/linux/ At least until Flathub also offers a pure FLOSS solution.

all the best and thank you for supporting FLOSS!
sudwhiwdh

**Comment by Hofer-Julian** [comment]
I don't think that a Flatpak download option is reasonable. This would combine the disadvantages of flatpak and appimage.

I personally don't see the problem with a store which offers proprietary software. But you are free to convince alternative flatpak repositories which do not offer proprietary software to include Vorta. Like e.g. the one of Fedora.

**Comment by sudwhiwdh** [comment]
What do you mean with combination of flatpak appimage disadvantages here?

Okay, I understand your personal preferences. Could you imagine a solution for those users who depend on a different perspective?

**Comment by Hofer-Julian** [comment]
> What do you mean with combination of flatpak appimage disadvantages here?

Flatpaks tend to be bigger than appimages. Without a repository we lose the auto update.

> Okay, I understand your personal preferences. Could you imagine a solution for those users who depend on a different perspective?

Like I said convince someone (or do it yourself) to include Vorta in the Fedora flatpak store.
But I can't see the point of users who demand that. Do they delete their browser, because you can use it to install proprietary software? With flathub the licence of every software is at least obvious.

I will close this issue now, but if you want help to include Vorta in another Flathub store or a distro's repository you are very welcome to do so.

**Comment by sudwhiwdh** [comment]
I would help if you see the possibility to provide a version as .flatpakref directly from your website at https://vorta.borgbase.com/download/linux/. Just like you already offer it for macOS.

See how to at https://docs.flatpak.org/en/latest/using-flatpak.html#install-applications. 

Then there is no need for external maintainers who hopefully update your Vorta package regularly and reliably in some external distro repos or software platforms. 

You can make sure that there is always a FLOSS version available.
And the users who appreciate it, do already exist. Even if you have a different or more relaxed approach to it yourself.

Kind regards!

**Comment by Hofer-Julian** [comment]
There is no external maintainer, packages on flathub are (in the ideal case) updated by the developers themselves. In the case of Vorta that would be me.

However, if in the future someone creates a FLOSS-only alternative to flathub we might consider to include it there as well.
