### ISSUE TITLE
How to add extra command line parameters to EXISTING backup

### ISSUE THREAD

**Issue by jbrepogmailcom** [borgbase/vorta#391]
**Describe the bug**
There is no possibility to add command line parameters to borg backup when the repository is already created. I want to limit backup to one filesystem (exclude mount points) by -x, but it is nowhere to add.

When trying to add the command to newly linked repository, there is error in log:
borg: error: unrecognized arguments: -x

**To Reproduce**
1. Create a new backup repository
2. Try to add command line parameter -x
3. Check log: borg: error: unrecognized arguments: -x

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by jbrepogmailcom** [comment]
When I think about the issue it can actually be quite important. Imagine you have encrypted volume, and you mount it decrypted only when user is present. But if no -x parameter is present, that decrypted volume is backed up. Then when the intruder gets access to Vorta GUI, it can mount decrypted backup, because the password for borg decryption key is stored in Vorta settings. I see this as security problem. I recommend that for automated backup the password is used automatically, but for restore, extract and mounting, the password would always have to be entered manually. Plus that optional -x parameter of course. Until that happens, I have to unistall Vorta and use command line.

**Comment by samuel-w** [comment]
-x is used for create only, so this would be more like https://github.com/borgbase/vorta/issues/274.
