### ISSUE TITLE
on GNOME "add folder" dialog does not work

### ISSUE THREAD

**Issue by rubonabo** [borgbase/vorta#392]
**Describe the bug**
"Add folder" dialog behaves like a file-selection dialog, not a folder-selection dialog.

**To Reproduce**
**Steps to reproduce the behavior:**
Go to 'Sources'
Click on 'Add Folder'
Select a folder
Click on "Open"
Selection dialog stays open and shows folder contents.
****Desktop** (please complete the following information):**
 Pop-OS 19.10 (based on Ubuntu 19.10)
GNOME with wayland
vorta v0.6.23, installed via flatpak
**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by Hofer-Julian** [comment]
Thanks!
I will close this issue and reopen https://github.com/borgbase/vorta/issues/392 instead.
