### ISSUE TITLE
Option to zoom the UI

### ISSUE THREAD

**Issue by jeroenpraat** [borgbase/vorta#393]
**Is your feature request related to a problem? Please describe.**
The text and other elements are just to small for my eyes.

**Describe the solution you'd like**
Make it possible to increase (and decrease) the zoom level of the UI. Or any other option that will make the fonts and such larger.

I'm using Gnome BTW, if that matters.

**Comment by ThomasWaldmann** [comment]
Do you have a high dpi display? Screen size / pixel resolution?

**Comment by jeroenpraat** [comment]
A resolution of 1920x1080, I don't know about the dpi. Running Ubuntu 19.10.

**Comment by ThomasWaldmann** [comment]
You forgot to give your physical screen size (diagonal, inches or cm).

**Comment by m3nu** [comment]
Shouldn't the OS or Qt take care of that? On Android and macOS you choose the text size for the whole desktop. It's not a setting for a single app.

If we can change some Qt settings to support this better, we should add them.

**Comment by Hofer-Julian** [comment]
I'd be interested in a screenshot of the whole desktop with Vorta open. That should make it easier to argue about

**Comment by jeroenpraat** [comment]
Physical screen size: 

Diagonal: ~60 cm
Width: ~53 cm
Height: ~30 cm

Screenshot desktop:

![Schermafdruk van 2019-12-22 21-55-03](https://user-images.githubusercontent.com/41594439/71327219-1a548680-2506-11ea-905f-17239e1dfa8d.png)

**Comment by ThomasWaldmann** [comment]
24" 1920x1080 a quite low dpi and quite standard display nowadays.

**Comment by Hofer-Julian** [comment]
Vorta's font size is not lower than your system's font size.
You might be interested in GNOME accessibility tools to increase it globally,

**Comment by jeroenpraat** [comment]
You are right. It must be the color scheme, why it looks smaller. Sorry for the inconvenience.

**Comment by Hofer-Julian** [comment]
No problem, glad to help!
