### ISSUE TITLE
fuse: failed to open /dev/fuse: Permission denied

### ISSUE THREAD

**Issue by BenWestcott** [borgbase/vorta#395]
The error in the title is thrown when trying to mount an archive. /dev/fuse is owned by user root, group root. Root user can read and write, group and other have no permissions.

1. Go to 'archives'
2. Click on an archive
3. Click 'Mount' and pick a user-writable folder
4. Error appears below the button and in the terminal/log

 - OS: Artix Linux (Arch without systemd)

**Comment by ThomasWaldmann** [comment]
Some Linux dists handle this by membership in a specific `fuse` group (and thus have group permissions for `fuse` group on `/dev/fuse`).

This seems to be not the case for the linux dist you use, so find out how you have to deal with fuse there.
