### ISSUE TITLE
Skip scheduled backup if nothing is changed

### ISSUE THREAD

**Issue by tomasxvavra** [borgbase/vorta#400]
Hello, it would be nice to have feature to skip scheduled backups if nothing is changed on the file system.

I am running hourly backups and there is a lot of them but many contains no changes. If those could be skipped, it would be great.

I know that borg does not supports this and I have no idea how to implement it. Just an idea..

**Comment by m3nu** [comment]
We can't implement this due to how Borg works. It runs one-off and doesn't monitor for changes all the time.
