### ISSUE TITLE
Can't browse a mounted archive

### ISSUE THREAD

**Issue by cbgregoire99** [borgbase/vorta#402]
**Describe the bug**
When I mount an archive in Vorta v.1.110 when I try to view it in my desktop file browser I get the following message i.e. see attached image. I am using Linux Mint 19.2's file browser.
![Screenshot from 2020-02-12 20-43-01](https://user-images.githubusercontent.com/50671083/74393865-450ddd80-4dd9-11ea-8a48-cbbb25a5f5ef.png)

I also cannot unmount the archive. When I try to do that I get the following message i.e. see attached image.
![image](https://user-images.githubusercontent.com/50671083/74394058-c1082580-4dd9-11ea-99af-f568ab9744fd.png)

**To Reproduce**
1. Go to 'Archives' tab in Vorta
2. Click on an archive then click on Mount
3. Select a folder to mount it in.
4. See the error.

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.2 this is a derivative of Ubuntu

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by ThomasWaldmann** [comment]
"Transport endpoint not connected" likely means the borg mount process has died.
