### ISSUE TITLE
Please document at least one copyright holder so that the terms of the license will be valid

### ISSUE THREAD

**Issue by sten0** [borgbase/vorta#403]
Hi!

Thank you for this software.  As a longtime user of Borg, I'm confident that Vorta is exactly what people need/want :-) so I've begun packaging Vorta for Debian (and thus derivatives such as Ubuntu, Mint, Pop! OS, Elementary, et al), and this issue will block inclusion into the Debian Archive.

**Describe the bug**
A user does not possess the rights conferred by a license unless a copyright holder is named.  Briefly, a license is a contract between the creator of a work (the copyright holder) and the recipient or user of that software, and without a named copyright holder this contract does not occur, thus the license is invalid.  This occurs because copyright occurs automatically with "all rights reserved" (eg: no rights to redistribute) in countries that have adopted the Berne Convention.  As a result of this, users of Vorta technically don't have a GPL-3 license to use and/or redistribute the software.  This applies Pypi and Flathub too, by the way.

**Solution**
The easiest thing to do would be to attribute everything to @m3nu.  The next easiest solution is to assign copyright for each file to whoever added the file to the git repo.  The next easiest solution is to use git to get statistical breakdowns per-file, and to document the copyright of everyone who contributed more than 10 lines.  Most projects do not maintain a separate CONTRIBUTORS.translations file, and the translation become the property of the named copyright holders.  That said, I'd like to second @ThomasWaldmann 's proposal (https://github.com/borgbase/vorta/issues/159#issuecomment-456253325) to provide such a CONTRIBUTORS[.translations] file because I prefer to attribute the work people did to the people who did it.

See §"How to Apply These Terms to Your New Programs" of the GPL-3 for more info.  I will of course be happy to help do the work of git spelunking, if necessary, and I'm required to do a full copyright review and analysis before uploading my package to the Debian Archive.  An alternative method to adding a copyright header to each file is to maintain a CONTRIBUTORS file.

Here is another link that may be helpful: https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html

Oh, and if there is more than 10 lines of BorgBackup code in Vorta then https://github.com/borgbackup/borg/blob/master/LICENSE and their AUTHORS file will need to be included for compliance with their license, probably in the `src/vorta/borg` subdir.

Best,
Nicholas

**Comment by m3nu** [comment]
Thanks for bringing this up, @sten0. Looks like just adding the license file isn't enough.

I added a pull request to add a contributors file and copyright note. I loosely used the Borg project and some other Python projects as inspiration for the setup.

There is no code from Borg in Vorta, since we generally only *run* Borg commands and wouldn't re-implement any aspects of it.

Hope this solves the license issue. If anything can be improved, I'm open to adjustments.

**Comment by sten0** [comment]
Thank you, much appreciated!  The only other thing is date of fixation.  eg © 2019-2020 John Doe.  This makes a difference for people who live in countries where copyright expires and the work moves into the public domain after x number of years.  It's also as easy-reference in case of disputes relating to prior art.

I can do the git spelunking work to get the beginning and end date ranges if you'd prefer to work on something more interesting ;-)

**Comment by m3nu** [comment]
What's the change needed? Currently it says `© 2018-2020` in the Readme and license. I first worked on it in 2018. Already looked it up in the commit history.

**Comment by sten0** [comment]
Oh! "© 2018-2020 Manuel Riel and Vorta contributors" at the bottom of README.md.  Yes, that looks good to me :-)  Sorry for the noise, it was totally my fault for not noticing the addition of this new line...

Thanks again, and take care!
Nicholas

P.S. I'm hoping to complete the package within the week because two family members have switched to Pop!OS and need easy long-term hassle-free backups asap, and ftpmasters willing, in Debian within a month.  Other than life stuff, the primary reason for the delay was/is qdarkstyle; it's a weird piece of software to package system-wide!
