### ISSUE TITLE
Tests only work when system-language is set to English

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#414]
My tests fail unless I remove https://github.com/borgbase/vorta/blob/3efecd71f3b0fc69261284efcd8d628bb2b89d59/src/vorta/i18n/__init__.py#L62

**Comment by m3nu** [comment]
Yes, the test check for some strings, which are in English.

We could explicitely add English as locale for tests.

**Comment by m3nu** [comment]
Add test fixture to always use English. Let me know if this works for your tests on a German system, @Hofer-Julian
