### ISSUE TITLE
Scheduling problem and backup bar

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#417]
(reported by email)

I am using...
Vorta Version 0.6.24
Borg Version 1.1.11.dev128+gae78914c

The computer is...
iMac (late 2013)
OSX 10.15.3

First problem:
On the "Schedule" tab I select "Backup daily at [time]" but the next day I see that (1) no archive was made at the time selected (2) the selection is no longer on "Backup daily at [time]" but instead is on "Backup manually."

I would like to backup daily at a specified time.  This was something I was able to achieve in the past on a different computer.  For now, I am making manual backups.

Second problem:
The manual backup progress bar does not stop until I press "cancel."  It appears to send the files to the backup then never send a 'done' command after the last file.  I would like it to stop the backup once the backup is completed.

Many thanks.
- Trevor

**Comment by m3nu** [comment]
For the scheduler problem: Is it possible your computer is turned off at the set backup time?

For the progress bar: The bar will move, while Borg is doing something in the background. It's probably not complete yet.

**Comment by dgancedo** [comment]
I have the same problem when I change the schedule to any other option and close and open Vorta again the option it's back in manually

**Comment by m3nu** [comment]
Are you pressing the *Apply* button after making the change? Since this reloads the scheduler, it's a button, rather than a background change.

**Comment by m3nu** [comment]
Also see #343
