### ISSUE TITLE
Add advanced options for repositories (and archives)

### ISSUE THREAD

**Issue by goebbe** [borgbase/vorta#421]
**Is your feature request related to a problem? Please describe.**
Sometimes a borg updates or fixes require the application of advanced borg commands or options. Example:  Update from borg 1.10 to 1.11 requires action in order prevent potential index corruption / data loss issue:
https://github.com/borgbackup/borg/blob/1.1.11/docs/changes.rst#version-1111-2020-03-08
> Advised procedure to fix any related issue in your indexes/caches: - install fixed borg code (on client AND server) - for all of your clients and repos remove the cache by:
> `borg delete --cache-only YOURREPO` (later, the cache will be re-built automatically)
> 
> for all your repos, rebuild the repo index by: `borg check --repair YOURREPO` This will also check all archives and detect if there is any data-loss issue.

This requires the following commands: 
borg --version      <- Check local borg version is at least 1.11
borg --version ssh://YORREPO    <- Check remote borg version is at least 1.11
If both conditions apply: 
borg delete --cache-only ssh://YOURREPO
borg check --repair ssh://YOURREPO

To my knowledge, Vorta currently does not warn about issues and does not provide an easy way to apply the necessary commands. 

**Describe the solution you'd like**
Provide an "advanced commands"-section that allows to apply the necessary commands conveniently. 
Perhaps Vorta could also warn the user, that action is required and point to the new buttons?

**Describe alternatives you've considered**
Perhaps point to the borg-release notes and to the required action - and do nothing else. Leave it to the user to apply the necessary commands from the terminal.

**Comment by m3nu** [comment]
Suggest to run one-off commands from the command line. We're not looking to implement 100% of Borg commands, just the ones used most frequently.
