### ISSUE TITLE
starting with root rights: Vorta freezes

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#422]
I have just installed the Flatpak- Version of Vorta.
And I have also installed the original Borg files via Linux distribution "Package Manager".

I want to backup to an external HD. This HD has root rights. I can not choose it as Repository as user-Account.

So I just went into the Desktop-Starter and changed
`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=vorta com.borgbase.Vorta`
into
`mx-pkexec /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=vorta com.borgbase.Vorta`

But now, when I try to choose a new repository, Vorta freezes.
Is there a way to solve this?

**Comment by Hofer-Julian** [comment]
No, this is unfortunately not possible.

**Comment by Golddouble** [comment]
Thank you for your answer.

What is not possible?
1. Starting Vorta as root? or
2. Making a backup to a HD partition, that needs Admin rights?

Thank you.

**Comment by Hofer-Julian** [comment]
Both

**Comment by Golddouble** [comment]
Thank you.
Does this also mean, I can not backup system-files, but only my personal data from home?

**Comment by Hofer-Julian** [comment]
Exactly :)

**Comment by m3nu** [comment]
Right. Vorta is mostly designed for desktops. Not common to have root there. To back up servers with mixed permissions, Borgmatic will be a better choice.

For Flatpaks you will also have some sandbox (no expert there). So becoming root is not possible (I think).
