### ISSUE TITLE
Not able to update vorta to 0.6.24 on Ubuntu 18.04

### ISSUE THREAD

**Issue by Turako** [borgbase/vorta#423]
Maybe not a real vorta problem itself, but I am not able to update to version 0.6.24 on my Ubuntu 18.04 using

`pip3 install -U vorta`

I do get the following error:

<pre>Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
      File &quot;/usr/lib/python3.6/tokenize.py&quot;, line 452, in open
        buffer = _builtin_open(filename, &apos;rb&apos;)
    FileNotFoundError: [Errno 2] No such file or directory: &apos;/tmp/pip-build-dsji6qxi/pyqt5/setup.py&apos;
    
    ----------------------------------------
<font color="#CC0000">Command &quot;python setup.py egg_info&quot; failed with error code 1 in /tmp/pip-build-dsji6qxi/pyqt5/</font>
</pre>

Do I have a wrong/old version of pip? Is this a known issue?

Thank you!

**Comment by Hofer-Julian** [comment]
I'd rather says that something is broken with your pqt5 installation.
If you are not interested in a long error hunt or reinstalling the OS I'd suggest to use the flatpak instead.

Settings can be transferred by copying ~/.local/share/Vorta/settings.db to ~/.var/app/com.borgbase.Vorta/data/Vorta/.
