### ISSUE TITLE
making Vorta fresh (reset)

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#424]
I use Vorta as Flatpack.
How can I delete all data from Vorta, so that it is, as if I have never used it and just fresh installed? (Deleting all keys, passphrases, SSH-keys, profiles and so on.)

I use it with MX Linux (Debian).
Thank you.

**Comment by Hofer-Julian** [comment]
Vorta-Settings:
- Flatpak: delete ~/.var/app/com.borgbase.Vorta/data/Vorta
- pip: delete ~/.local/share/Vorta

SSH-Keys: depends on where you stored them, but ~/.ssh might be a good guess
