### ISSUE TITLE
just a simple backup

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#426]
I am not a professional user. I just want to backup my home folder to an external hard drive.

I don't want to use keys, encryption and passwords and Pins.

I have installed the flatpack version. I have deleted the following folders to start new and try again:

```
 ~/.var/app/com.borgbase.Vorta/data/Vorta
~/.local/share/Vorta
~/.ssh

```
So I started the program new. I just leave all as it is, but choose "Add new repository." Then I choose my target folder. I click the "add" button. Now it asks for a passphrase. I do not want to put any passphrase in, to make things easier. But it seems that I have no choice. I have to put in a passphrase. So I type in "123456789". Then I click the "add-button". Now I'm asked for some kind of password. 
https://www.bilder-upload.eu/bild-668787-1585560122.png.html

German:
Anmeldeschlüssel entsperren:
Geben Sie das Passwort zum Entsperren des Schlüsselbundes ein:
Ihr Anmeldeschlüsselbund wurde nicht automatisch entsperrt, als Sie sich n diesem Rechner angemeldet haben.

Enhlish:
Unlock logon key:
Enter the password to unlock the keyring:
Your logon keychain was not automatically unlocked when you logged on to this machine.

I have no idea what kind of password I have to enter here now. 

Can you help me? Thank you.

**Comment by m3nu** [comment]
The screenshot shows a window by Gnome's password manager, Vorta just uses it to store passwords.

You can choose "None" as encryption when creating a repo and it won't ask for a PW.

**Comment by Golddouble** [comment]
Thank you.
I found the "None" Entry and I found out, that the password window from Gnome's password manager asked for the users Login-password of my linux distribution. So I am a step forward now.
