### ISSUE TITLE
Backup source using relative path

### ISSUE THREAD

**Issue by devurandom** [borgbase/vorta#427]
**Is your feature request related to a problem? Please describe.**

I would like to not have the absolute path to the directory to backup in the paths saved by Borg.

`borg help create` says:
> Paths are added to the archive as they are given, that means if relative paths are desired, the command has to be run from the correct directory.

However, I cannot figure out how to make Vorta `cd` into the given source directory before creating the backup.

**Describe the solution you'd like**

A config flag that allows me to specify for a backup profile whether to `cd` into the source directory and backup `.` or whether to use absolute paths would be nice.

**Describe alternatives you've considered**

I do not see alternatives right now.

**Comment by m3nu** [comment]
Don't see how Vorta could support this, since it's a GUI app. There is no CWD.

**Comment by devurandom** [comment]
In my scripts I am doing it like this:
```c
chdir("/directory/to/backup")
system("borg create /path/to/archive .")
```

Note the `.` as the backup path argument to `borg`.

**Comment by m3nu** [comment]
We support adding multiple paths. So this won't work or will make it messy.

**Comment by eric-j-ason** [comment]
What about paths relative to the home directory, using `~`? That does work in the exclusion list.

What I'm trying to do is pre-generate a bootstrap configuration (`.vorta-init.json`) without knowing what the username or home directory is called on the machine that's going to be backed up.

**Comment by m3nu** [comment]
Interesting use case. The path picker wouldn't work with relative URLs, but we could make this work during the import with minimal changes. It just needs to expand `~` while importing `.vorta-init.json`. Could be a 1-line change.
