### ISSUE TITLE
incremental, diferencial, validate

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#428]
1)
Once we have made a full backup: Can we only make incremental backups then. Or is it possible to make also differential backups. Or are all differential?
https://www.bilder-upload.eu/bild-df36b3-1585642869.png.html

2)
When I mark the line from 2020-03-30 13:52 and press the "Prüfen" button (see picture above) does Vorta then only validate the backup part created at 2020-03-30 13:52 or does Vorta then validate the backups from 2020-03-30 13:52 and 2020-03-30 12:07?
If the anwer is "all": Is there a way only to validate the backup from 2020-03-30 13:52?
It looks not useful to validate always all backups, when simply a little backup of a few MB has added and there is a list with 50 backups.

3)
Makes the button "Pfüfen" (see the picture above) exactliy the same thing like the checkbox "Repository validieren" (see picture below):
https://www.bilder-upload.eu/bild-ae58d5-1585643303.png.html

Thank you.

**Comment by ThomasWaldmann** [comment]
borg always does full backups, but in an efficient way (so it "feels" incremental).

**Comment by Golddouble** [comment]
Thank you.
I assume, that "prüfen" (see the first link to the picture) means, Vorta ensures that the backup is error-free and can be restored correctly.

What is with question 2?
So does "Prüfen"  (see the first link to the picture) only validate the new backup part of 3.2 GB or does it always validate the 3.2 GB and 70.1 GB part?
Thank you.

**Comment by Hofer-Julian** [comment]
@Golddouble questions related to borg are probably more suitable for borg's IRC channel https://www.borgbackup.org/support/free.html
