### ISSUE TITLE
unmount a snapshot

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#432]
I did mount a "Snapshot" in my archiv to 
/media/Konto/Seagate 2TB-2/Vorta Mount/

It works. I can go  to /media/D-Konto/Seagate 2TB-2/Vorta Mount/  in thunar and browse through my Snapshot.

Then, in the archive Tab, I mark the mounted "Snapshot" and press the "unmount" button.
My expectation is, that now it will unmount my snapshot.
But there is a message: No active Borg mounts found.

I close Vorta.
I go with thunar into /media/Konto/Seagate 2TB-2/Vorta Mount/.
I can still browse through the snapshot.

I change with thunar to /home/Konto/ -Folder.
I try now to unmount 
/media/Konto/Seagate 2TB-2 
in my system (my systems unmount function, not the one in Vorta, because Vorta is closed). 
Message from my system: "Unable to unmount, Device is in Use".

Question: How can I unmount a mounted snapshot?

I use Flatpak v0.6.23 Linux (Debian based)

-----
Edit:
-----

In the meantime I found out how I can solve this:

    Start thunar with sudo.
    Right click under device on the mounted folder. -> unmount

But why does the unmount-Button in the Vorta Gui not work?
What can I do, to bring the unmount button into work?

I have installed:
Flatpack: com.Borgbase.Vorta v0.6.23
Borgbackup 1.1.9-2
Borgbackup-doc 1.1.9-2

Thank you.

**Comment by Golddouble** [comment]
In the meantime I found out how I can solve this:
1. Start thunar with sudo.
2. Right click under device on the mounted folder. -> unmount

But why does the unmount-Button in the Vorta Gui not work?
What can I do, to bring the unmount button into work?

I have installed:
Flatpack: com.Borgbase.Vorta v0.6.23
Borgbackup 1.1.9-2
Borgbackup-doc 1.1.9-2

Thank you.

**Comment by Golddouble** [comment]
I have tried the same now in the terminal:
```
user@mx:~
$ borg umount /media/user/Seagate 2TB-2/Mount4
usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug]
            [--debug-topic TOPIC] [-p] [--log-json] [--lock-wait SECONDS]
            [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
            [--remote-ratelimit RATE] [--consider-part-files]
            [--debug-profile FILE] [--rsh RSH]
            <command> ...
borg: error: unrecognized arguments: 2TB-2/Mount4
user@mx:~
```
Does not work.

**Comment by Hofer-Julian** [comment]
I've noticed similar problems with borg mounts. For example when I try to unmount a borg mount, while I still have it open in my file manager, it of course fails, but from then on it refuses to let me unmount even if I don't have it open anymore.

My guess would be that neither Vorta nor borg can do much about that, but maybe @ThomasWaldmann can say more about that.

**Comment by Golddouble** [comment]
> similar problems with borg mounts. For example when I try to unmount a borg mount, while I still have it open in my file manager,

Thank you for this comment. I have tried now this:

1. mount a "Snapshot" in my archiv to /media/Konto/Seagate 2TB-2/Vorta Mount/
2. browse through the mounted archiv
3. close all open thunars
4. go back to Vorta GUI und press the "unmount"- Button
`
Result: No active Borg mounts found`

5. Open Thunar again. -> It's still mounted.

**Comment by m3nu** [comment]
> I have tried the same now in the terminal:
> 
> ```
> user@mx:~
> $ borg umount /media/user/Seagate 2TB-2/Mount4
> usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug]
>             [--debug-topic TOPIC] [-p] [--log-json] [--lock-wait SECONDS]
>             [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
>             [--remote-ratelimit RATE] [--consider-part-files]
>             [--debug-profile FILE] [--rsh RSH]
>             <command> ...
> borg: error: unrecognized arguments: 2TB-2/Mount4
> user@mx:~
> ```
> 
> Does not work.

Doesn't work because the arguments are wrong.

**Comment by Hofer-Julian** [comment]
> > I have tried the same now in the terminal:
> > ```
> > user@mx:~
> > $ borg umount /media/user/Seagate 2TB-2/Mount4
> > usage: borg [-V] [-h] [--critical] [--error] [--warning] [--info] [--debug]
> >             [--debug-topic TOPIC] [-p] [--log-json] [--lock-wait SECONDS]
> >             [--show-version] [--show-rc] [--umask M] [--remote-path PATH]
> >             [--remote-ratelimit RATE] [--consider-part-files]
> >             [--debug-profile FILE] [--rsh RSH]
> >             <command> ...
> > borg: error: unrecognized arguments: 2TB-2/Mount4
> > user@mx:~
> > ```
> > 
> > 
> > Does not work.
> 
> Doesn't work because the arguments are wrong.

Ah yes, you are missing quotes, it should be
borg umount "/media/user/Seagate 2TB-2/Mount4"

**Comment by Golddouble** [comment]
> Doesn't work because the arguments are wrong.

Thank you. So I made a further try:
```
$ borg umount /media/user/Seagate\ 2TB-2/Mount77
fusermount: entry for /media/user/Seagate 2TB-2/Mount77 not found in /etc/mtab
user@mx:~
$ 

```
The content of my  /etc/mtab is:
```
sysfs /sys sysfs rw,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
udev /dev devtmpfs rw,nosuid,relatime,size=4007876k,nr_inodes=1001969,mode=755 0 0
devpts /dev/pts devpts rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=807984k,mode=755 0 0
/dev/sda4 / ext4 rw,noatime 0 0
tmpfs /run/lock tmpfs rw,nosuid,nodev,noexec,relatime,size=5120k 0 0
pstore /sys/fs/pstore pstore rw,relatime 0 0
tmpfs /dev/shm tmpfs rw,nosuid,nodev,noexec,relatime,size=5810260k 0 0
/dev/sda6 /home ext4 rw,noatime 0 0
rpc_pipefs /run/rpc_pipefs rpc_pipefs rw,relatime 0 0
cgroup /sys/fs/cgroup tmpfs rw,relatime,size=12k,mode=755 0 0
systemd /sys/fs/cgroup/systemd cgroup rw,nosuid,nodev,noexec,relatime,release_agent=/run/cgmanager/agents/cgm-release-agent.systemd,name=systemd 0 0
tmpfs /run/user/1000 tmpfs rw,nosuid,nodev,relatime,size=807980k,mode=700,uid=1000,gid=1000 0 0
gvfsd-fuse /run/user/1000/gvfs fuse.gvfsd-fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
/dev/fuse /run/user/1000/doc fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1000 0 0
/dev/sdc3 /media/user/Seagate\0402TB-2 ext4 rw,nosuid,nodev,relatime,stripe=8191 0 0
borgfs /media/user/Seagate\0402TB-2/mount77 fuse ro,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions 0 0
```

**Comment by m3nu** [comment]
`borgfs /media/user/Seagate\0402TB-2/mount77 fuse ro,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions 0 0`

Your mount is there, but the weird filename is causing you issues.

**Comment by Golddouble** [comment]
Thank you.

Further ties:
When I make this, it unmounts. This works:
`borg umount /home/user/Mount`

But when I make all the same, but use the "unmount" button in Vorta it does not work.

**Comment by Golddouble** [comment]
I use  Vorta Flatpacks v0.6.23.
My System MX Linux 19.

Here are the screenshots:
1. https://www.bilder-upload.eu/bild-85eb57-1586539134.png.html
2. https://www.bilder-upload.eu/bild-0a3cdc-1586539150.png.html
3. https://www.bilder-upload.eu/bild-906c96-1586539167.png.html
4. https://www.bilder-upload.eu/bild-74b0d4-1586539177.png.html
5. https://www.bilder-upload.eu/bild-bb7956-1586539187.png.html
6. https://www.bilder-upload.eu/bild-7ecd5a-1586539762.png.html
7. https://www.bilder-upload.eu/bild-5cbc80-1586539211.png.html
8. https://www.bilder-upload.eu/bild-229a3a-1586539227.png.html

Shut down the computer and start new. After:
9. https://www.bilder-upload.eu/bild-7e1378-1586539239.png.html

**Comment by Golddouble** [comment]
Maybe this is because Vorta asks for each step for my user password?
But not when I try to unmount. But it should?
![Passwort-Vorta](https://user-images.githubusercontent.com/13977359/80527599-e518e300-8994-11ea-8afc-cc7847b2efad.png)

(?)

I do not know why it alway asks for my user password. I have a repository without Encryption. 
(?)

**Comment by m3nu** [comment]
I'm closing this since it's probably an issue with the folder name.

**Comment by Golddouble** [comment]
I guess, this is not an issue with the folder name.
Please read the post from 5 Apr:

> Thank you.
> I have changed now my mount folder from the weird filename(see above) to ~/Mount.

So I guess this issue should be reopened. (?)

**Comment by kntasks** [comment]
I'm experiencing the same behaviour as described by the OP. 

![borg-snapshot-unmount-not-successful-scrot 2021 11 29_09 54 58](https://user-images.githubusercontent.com/24494120/143805937-f7018aa5-79b2-4bff-b92e-eb9fbbdd60d7.jpg)

The workaround is to open Thunar then unmount snapshot within Thunar. 

However, when I go back to the Vorta, I can still see the snapshot as mounted. If I click 'refresh' then I can see 'refreshing archives' on the bottom of the screen and only then the mount point disappears. 

As a test, I also tried the following. Mount the snapshot 2021-11-29 09:51, use my usual file manager Dolphin to navigate through the snapshot, go back to home directory, so the snapshot directory is not in use. Unmount snapshot through Vorta. Then try to mount snapshot 2021-11-29 00:51 to the same mount point /home/k/vorta-backup. Error message is displayed:

`fusermountpoint: failed to access mountpoint /home/k/vorta-backup: permission is denied. `

So, the mount point is definitely in use.

Then I tried this (to check if VOrta still displaying the snapshot as mounted when it was unmounted via THunar is just a VOrta display issue): 

1) mount snapshot 2021-11-29 09:51.
2) use dolphin to navigate the snapshot.
3) Back to home directory (so snapshot is 'not in use')
4) unmount snapshot through Thunar (check VOrta - yes, it's still showing as mounted)
5) try to mount 2021-11-29 00:51 to /home/k/vorta-backup (even though Vorta is still showing 2021-11-29 09:51 as mounted to /home/k/vorta-backup)
6) message appears 'mounting archive' then it says 'mounted successfully'.
7) Within vorta now I can see two snapshots (both 2021-11-29 09:51 and 2021-11-29 00:51) mounted to /home/k/vorta-backup

![borg-snapshot-unmount-two-snapshots-mounted-on-same-mountpoint-scrot 2021 11 29_10 45 24--](https://user-images.githubusercontent.com/24494120/143806325-a3923589-953e-4f92-be79-5ff4054f0023.jpg)

8) I navigate to /home/k/vorta-backup and check for the newest file on terminal using: 

find . -printf '%T+ %p\n' | sort -r 

9) the snapshot 2021-11-29 00:51 is the one that is now mounted on /home/k/vorta-backup (which is expected), even though the Vorta interface is saying both snapshots are mounted.
