### ISSUE TITLE
Add a step by step guide for local use of Vorta

### ISSUE THREAD

**Issue by sudwhiwdh** [borgbase/vorta#434]
Screenshots would be nice.
And also, what consequences the individual choices have for the usage.
The documentation should be written so that no prior knowledge is needed to understand it.

**Comment by sudwhiwdh** [comment]
This could be added here https://vorta.borgbase.com/usage/local/

**Comment by sudwhiwdh** [comment]
"Note: Vorta is currently in beta-testing and shouldn’t be your only backup solution."
https://vorta.borgbase.com/usage/
Is Vorta really still in beta status?

**Comment by m3nu** [comment]
> Is Vorta really still in beta status?

Not really. Docs should be changed. You're interested in that @meowmix3?

**Comment by Golddouble** [comment]
"a step by step guide for local use of Vorta":
Good point.

**Comment by meowmix3** [comment]
> > Is Vorta really still in beta status?
> 
> Not really. Docs should be changed. You're interested in that @meowmix3?

Very much so.  Give me a couple days and I'll create a PR.

Would you rather me use a macOS or Linux machine for the screenshots?  It shouldn't matter too much, but if the bigger demographic is macOS it might make sense to make the users feel more "at-home" while following the guide.

**Comment by m3nu** [comment]
Doesn't matter, but macOS looks nicer, I think. You can also make nice screenshots with `Cmd + Shift + 5` and then select a single window. E.g.:

![Screen Shot 2020-04-07 at 22 37 49](https://user-images.githubusercontent.com/3916435/78682352-74941e80-7920-11ea-8bef-9f135ff18e06.jpg)

**Comment by meowmix3** [comment]
> Doesn't matter, but macOS looks nicer, I think. You can also make nice screenshots with `Cmd + Shift + 5` and then select a single window. E.g.:

Got it, after looking over the docs I'll probably just stick to Linux since my macOS machine isn't always available, and I'll likely write up remaining documents.  GNOME has pretty drop shadow screenshots too though 😃

![Screenshot from 2020-04-07 11-37-37](https://user-images.githubusercontent.com/63012818/78689333-39640200-78c4-11ea-8309-a089c5995ea9.png)

**Comment by Golddouble** [comment]
**@meowmix3**
When you create a doc for local use of Vorta:
Perhaps you could then also integrate a few words relating to this question here:
https://github.com/borgbase/vorta/issues/435

Thank you.

**Comment by meowmix3** [comment]
> **@meowmix3**
> When you create a doc for local use of Vorta:
> Perhaps you could then also integrate a few words relating to this question here:
> #435
> 
> Thank you.

Sure, I replied to your issue in the Vorta thread as well.  My guess is that it's just a permissions issue, and I'll make sure and touch on that in the "Restore" section.

**Comment by Golddouble** [comment]
Your step for step guide is quite good.

Maybe you can add an explanation for the differences function of Vorta, that also answers all this questions:
https://github.com/borgbase/vorta/issues/444

Thank you.

**Comment by m3nu** [comment]
Thanks to @meowmix3 for implementing this. The other requests are off-topic and I'm closing this issue now.
