### ISSUE TITLE
If a restore is done by mounting and copying, the restored files lose their original rights.

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#435]
When I mount a snapshot, then all files have an icon with a lock.
When I then place some of this files from the mounted folder to a target folder (retrive a file through copy), then I would expect, that this file loses the lock of the icon. Then before I made a backup of this file (in the source) it also did not have a lock symbol on the icon. But the lock symbol on the icon remains.

So, when I have a file in the source (without a lock symbol on the icon) I call it "MyFile.txt", then I make a back up with Vorta, then mount the snapshot and copy it to a target, (I have now MyFile.txt in a new target), then I ask me, if is now this file in the new target, that has still a lock symbol in the icon a little bit different from the original "MyFile.txt"?

Or why should this now have a lock symbol on the icon?

Locksymbol on the icon. An example:
https://www.bilder-upload.eu/bild-96b837-1586266848.png.html

**Comment by meowmix3** [comment]
I'm a little confused here, would you be able to post some screenshots as well as your system information (OS version, Desktop environment (if using Linx), Vorta version, etc) to elaborate on the issue?

I don't have Vorta in front of me right now, but if I had to guess its because the mounted snapshot is "Read Only", meaning the file in the snapshot cannot be directly modified.  The lock symbol may just mean your system is letting you know that you cannot modify the file on the mounted snapshot, and when you copy it over the lock is no longer there because it is a copy of the file.  There should be no difference in the files, just the permissions on it (while using the snapshot).

Does that help at all?

**Comment by Golddouble** [comment]
Does not help. 

> ... and when you copy it over the lock is no longer there because it is a copy of the file.
This is what I would expect. But it is not so.

I will make some Screenshots.

**Comment by Golddouble** [comment]
I use  Vorta Flatpacks v0.6.23.
My System MX Linux 19.

Here are the screenshots:
1. https://www.bilder-upload.eu/bild-85eb57-1586539134.png.html
2. https://www.bilder-upload.eu/bild-0a3cdc-1586539150.png.html
3. https://www.bilder-upload.eu/bild-906c96-1586539167.png.html
4. https://www.bilder-upload.eu/bild-74b0d4-1586539177.png.html
5. https://www.bilder-upload.eu/bild-bb7956-1586539187.png.html
6. https://www.bilder-upload.eu/bild-7ecd5a-1586539762.png.html
7. https://www.bilder-upload.eu/bild-5cbc80-1586539211.png.html
8. https://www.bilder-upload.eu/bild-229a3a-1586539227.png.html

Shut down the computer and start new. After:
9. https://www.bilder-upload.eu/bild-7e1378-1586539239.png.html

**Comment by meowmix3** [comment]
Got it, can you try 

> I use Vorta Flatpacks v0.6.23.
> My System MX Linux 19.
> 
> Here are the screenshots:
> 
> 1. https://www.bilder-upload.eu/bild-85eb57-1586539134.png.html
> 2. https://www.bilder-upload.eu/bild-0a3cdc-1586539150.png.html
> 3. https://www.bilder-upload.eu/bild-906c96-1586539167.png.html
> 4. https://www.bilder-upload.eu/bild-74b0d4-1586539177.png.html
> 5. https://www.bilder-upload.eu/bild-bb7956-1586539187.png.html
> 6. https://www.bilder-upload.eu/bild-7ecd5a-1586539762.png.html
> 7. https://www.bilder-upload.eu/bild-5cbc80-1586539211.png.html
> 8. https://www.bilder-upload.eu/bild-229a3a-1586539227.png.html
> 
> Shut down the computer and start new. After:
> 9. https://www.bilder-upload.eu/bild-7e1378-1586539239.png.html

Got it, can you try copying the files with a different file manager to see it still happens with that?  It could just be your file manager.  I tried replicating the issue on my computer with the Nautilus and it seems to copy fine, with the new file being read/writable.

But to answer your question
> then I ask me, if is now this file in the new target, that has still a lock symbol in the icon a little bit different from the original "MyFile.txt"?
The file is the same, it should just be a permissions issue.

**Comment by Golddouble** [comment]
You are right. I have only "read" right on this file:
![VortaTerminal](https://user-images.githubusercontent.com/13977359/79037394-cd89de00-7bd0-11ea-8b7d-fe0ef5dae123.png)

> ... can you try copying the files with a different file manager to see it still happens with that?

I have tried with XnViewMP. But it's the same issue.

**Comment by m3nu** [comment]
If you need to preserve all metadata, use `borg extract`. Restoring via mount loses metadata. This is unrelated to Vorta.
