### ISSUE TITLE
Run Backup after login

### ISSUE THREAD

**Issue by Justinzobel** [borgbase/vorta#438]
Two alternatives.

**Describe the solution you'd like**
I'd like to be able to backup shortly after login, whether that be an option inside Vorta that is a tickbox and field, Backup at login, Wait x seconds/minutes after login.
Or it could be a terminal command I can run, `vorta --backupnow --profile "Myprofilename" after sleeping for x seconds/minutes

**Comment by meowmix3** [comment]
What desktop environment do you use?

This can probably be achieved outside of Vorta, using [a .desktop file](https://specifications.freedesktop.org/autostart-spec/0.5/ar01s02.html]) and a command line borg wrapper such as [Borgmatic](https://torsion.org/borgmatic/).  

Shouldn't be too crazy to write.  Or if your DE allows it, just writing a simple shell script with:
```
#!/bin/bash
borgmatic -C -v0 -p
```
& and have your desktop start it while logging in.  There's a few guides on configuring borgmatic out there.

**Comment by ThomasWaldmann** [comment]
Another idea is to (optionally?) show a clearly visible countdown before starting the backup.

Some people have to first search and plug in their usb disks before the backup can succeed.

**Comment by Justinzobel** [comment]
Thanks Alexandar, I'm going to give this a go.

TW I have a pre-exec command in my Vorta backup to ensure the server is
there before starting.

**Comment by m3nu** [comment]
Thanks to @samuel-w , you can now do `vorta --create nyx2@borgbase` and it will start a backup for that profile on an existing Vorta instance.

Hope this kinda solves the issue. We probably can't do further integration, since this is different for every OS.
