### ISSUE TITLE
How to run Vorta on Ubuntu

### ISSUE THREAD

**Issue by smartm0use** [borgbase/vorta#439]
I have installed Vorta with `pip3 install vorta` and I can't find it in the applications menu of Ubuntu.
So I open it running `vorta` from a terminal window, but when I close the app I have the process still running in the terminal and I have to type ctrl+c or close the window. Is it normal?

```
~$ vorta
2020-04-08 10:22:17,778 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2020-04-08 10:22:17,897 - apscheduler.scheduler - INFO - Scheduler started
2020-04-08 10:22:19,196 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg --version
```

I'm on Ubuntu 18.04.4 LTS.

**Comment by meowmix3** [comment]
By default, Vorta will close if you 'Ctrl+c' out of it or close the terminal window.

There's a few solutions to this, one would be running `vorta --daemonize` with the latest Vorta, which starts it in the background, and you can run `vorta` whenever you want to bring the window up.

If you want a little more integrated experience with Ubuntu, perhaps give the [flatpak on flathub](https://www.flathub.org/apps/details/com.borgbase.Vorta) a shot.  It will create an icon you can select through your default application launcher.  It's one version behind at the moment, but it should work fine.

**Comment by Hofer-Julian** [comment]
That's expected when installing with pip.

As @meowmix3 suggested, please use the flatpak if you expect integration with your desktop environment

**Comment by smartm0use** [comment]
Have I to uninstall it via pip before installing it via flatpak?

**Comment by Hofer-Julian** [comment]
If you want to keep your setttings, follow the instructions at https://vorta.borgbase.com/download/linux/

Then
pip3 uninstall vorta

**Comment by smartm0use** [comment]
Ehm... running `flatpak install flathub com.borgbase.Vorta` I get this error:

**error: Remote "flathub" not found**

**Comment by Hofer-Julian** [comment]
You have to follow https://flatpak.org/setup/ first

**Comment by smartm0use** [comment]
It worked thank you.
