### ISSUE TITLE
Offer beta releases

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#443]
We had some situations in the past where we noticed issues after a release, which probably would have been easily found if more people would have tested them.

I don't know how much effort it is for you @m3nu to make a (pre-)release on github, but at least on flathub, beta releases are easy.

**Comment by m3nu** [comment]
I tried pre-releases in the past and nobody used them. So now there are only normal releases and everyone helps find bugs 😁

**Comment by Hofer-Julian** [comment]
Okay, then let's keep it that way :)
