### ISSUE TITLE
differences between snapshots: rights

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#444]
I have today made an updated of my backup (added a snapshot).
Then I have opened the Diff-window to see the differences between the old and this new backup.

It looks like this:
![VortaDiff](https://user-images.githubusercontent.com/13977359/79064970-73127f80-7cad-11ea-894e-32556438bc7c.png)

I do not understand, what that means:

> [-rw-r--r-- into -rw-------] home

Does this mean, the rights of my /home/ has changed from 
-rw-r--r-- into -rw------- ?

1. Question: Why do I have 
"/home/user/" 
twice? In the upper part and in the down part?

2. Question: When this are the rights of my home why doesn't it show this with a "d" before, because /home/ is a folder?:
drw-r--r--  ->  drw-------

3. Question: Did only the rights of "/home/" change or all subfolders also?

4. Question: In the upper part I have "Home/.thunderbird" and also in the down section I have "Home/.thunderbird". Does this mean all rights of all this files and folders have changed their rights from -rw-r--r--  ->  -rw------- ?

5. Question: So I went to my terminal to find out, what my actual rights for home are. The result is:
```user@mx:/home
$ ls -all
drwxr-xr-x   4 root root  4096 Mär 29 15:17 home
```
My expectation was, that it would be either -rw-r--r-- or  -rw-------  (?)

Very confusing.

**Comment by Hofer-Julian** [comment]
@Golddouble, thanks for opening this issue.
This should be fixed by https://github.com/borgbase/vorta/pull/373.
Unfortunately, this PR is not included in the newest flathub build.
I could release the snapshot from master, but I'd rather follow Vorta's release cycle.

@m3nu could you make a new release or should I publish a flatpak build from current master?

**Comment by Golddouble** [comment]
Thank you.
So what is the error?
Is the error only in the "difference-feature"? Or is something wrong with my backup now?
What is the error? How should it be?

**Comment by Hofer-Julian** [comment]
The error is only in the GUI.
The borg cli output should still be valid.
I wouldn't be too worried now, and check again when the next release is out

**Comment by m3nu** [comment]
Fixed via #373 and references and outdated version.
