### ISSUE TITLE
Add a guide with some examples how to use "Thinning"-function

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#446]
### Would appreciate to have 5-10 examples how to use this function in the guide:
![Vorta Ausdünnung](https://user-images.githubusercontent.com/13977359/79447977-f64f1080-7fe0-11ea-9712-700acf2ab66c.png)
![Vorta Ausdünnung-1](https://user-images.githubusercontent.com/13977359/79447983-f8b16a80-7fe0-11ea-8958-fd9e68983c7e.png)

### What will exactly happen with which chose?

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
(Furthermore:
Is it okay to have 500 snapshots? Or should we use this function before? I am aware, that this function makes space available. But what about the reliability of the backup with 500 snapshots? (I mean faulty backups, not recoverability of the data). 

How reliable is the "Thinning"-function? Isn't there a risk of destroying the backup by using this function? 

I know that we can check backups, if we want to be sure that they are in good condition. But if I now have 40 backups and delete 30 of them with the "Thinning" function and then use the Validate function and find that the backups are no longer in good condition, then validating is probably of no use to me. Then I have lost all backups.

Thank you.)

**Comment by m3nu** [comment]
I feel that this is a question about Borg's inner workings and you should look it up there.

This is the relevant docs page: https://borgbackup.readthedocs.io/en/stable/usage/prune.html

If something isn't answered there, open an issue with them to update the docs. Vorta doesn't try to copy Borg, only provide a UI.

So I'll close it here.

**Comment by Golddouble** [comment]
Thank you for the link
