### ISSUE TITLE
Automatically switch UI between light / dark versions

### ISSUE THREAD

**Issue by philipkozeny** [borgbase/vorta#447]
**Is your feature request related to a problem? Please describe.**
With macOS Catalina there is an automatic mode to switch the UI between the light appearance and dark mode. Vorta being able to switch UI modes on the fly, based on the current system setting would be great.

**Describe the solution you'd like**
Since there are options to choose between a light/dark UI and icon I would expect / find it great to have also a version that automatically detects dark mode and switches the UI and icon based on the system setting.

**Comment by m3nu** [comment]
This would be a welcome addition. If you can already share a pull request, I'll be happy to review it.

**Comment by m3nu** [comment]
This is now working @philipkozeny . Merged it a few days ago. See also this short video: https://twitter.com/borg_base/status/1266253145904037893
