### ISSUE TITLE
Unable to add existing unencrypted repo

### ISSUE THREAD

**Issue by skerit** [borgbase/vorta#450]
**Describe the bug**
I have an existing, unencrypted repo up on borgbase. I used it to backup my `home` folder before reinstalling my computer, so I need to add it again on a totally new install.

But doing this in Vorta always fails, I believe it is because at some point Borg asks `Warning: Attempting to access a previously unknown unencrypted repository!
Do you want to continue?`, and Vorta doesn't handle this?

There is a workaround though: I can start Vorta with the `BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK` environment variable set to `yes`. Then it does work.

Maybe adding a checkbox to mark it as unencrypted could, which would set the environment variable would help?
And maybe adding a text input to set extra environment variables, like you can already add `Extra Borg Arguments` on the advanced tab?

Also: it would be nice if the complete borg output could be seen when adding the repository (without having to dig up the log file)

**To Reproduce**
1. In the `Repository` tab, click on the `Add existing repository` option in the `Repository` dropdown
2. Enter the `Repository URL`, in my case it's on Borgbase
3. Click `Add`

**Desktop (please complete the following information):**
 - OS: Manjaro (Linux 5.6.6)

**Additional context**

```
2020-04-24 11:24:36,792 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg info --info --json --log-json xxx@xxx.repo.borgbase.com:repo
2020-04-24 11:24:37,247 - vorta.borg.borg_thread - WARNING - Remote: Warning: Permanently added 'xxx.repo.borgbase.com,116.202.166.181' (ECDSA) to the list of known hosts.
2020-04-24 11:24:37,691 - vorta.borg.borg_thread - WARNING - Remote: X11 forwarding request failed on channel 1
2020-04-24 11:24:38,192 - vorta.borg.borg_thread - ERROR - Cache initialization aborted
```

**Comment by Hofer-Julian** [comment]
@skerit If you want to work on this, I'd be happy to review it.

**Comment by geckolinux** [comment]
Subscribing, this bug has bitten me twice now and I always forget the name of the environment variable and I can't easily find this bug report.

**Comment by Hofer-Julian** [comment]
@m3nu, as you mentioned [here](https://github.com/borgbase/vorta/pull/508#issuecomment-647348093) I think we should pass `BORG_UNKNOWN_UNENCRYPTED_REPO_ACCESS_IS_OK` all the time.

People tend to have an intuitive feeling that switching from the encrypted default to the unencrypted option is less safe.
But maybe @ThomasWaldmann has a different opinion here?

**Comment by Hofer-Julian** [comment]
Also we only need it for already existing repos, so the "damage" is already done
