### ISSUE TITLE
Add warning in case a backup repo is modified outside Vorta (which could lead to a sync/display problem inside Vorta)

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#454]
Hello @m3nu,

you apparently closed the 

#430 [Suggestion] Add the repo total size as an extra line in the archive list

in a way, so that I unfortunately cannot answer **there**.

Yes, you may be right:

*As far as I remember*, I even created the borg archive outside Vorta - is there any information that this should not be done?? - and then pruned it with some borg commands outside, and some actions inside Vorta, including refreshing.

In my view, this is a clear hint (pls. correct me, if I am wrong) that something inside Vorta - you are indicating that - is not fully reflecting and following the real status of a repo when the repo was modified by borg's native commands.

**Comment by m3nu** [comment]
> As far as I remember, I even created the borg archive outside Vorta - is there any information that this should not be done?? - and then pruned it with some borg commands outside, and some actions inside Vorta, including refreshing.

It's usually not an issue. You will only miss some archives. Running a *Refresh* from the repo tab will fix it.

If you know a good way to find out and warn about it, just do a pull request for Vorta.

If you think the docs can be improved and it's important enough to add, please open the PR there.
