### ISSUE TITLE
Window size on opening

### ISSUE THREAD

**Issue by SamuelBenard** [borgbase/vorta#457]
**Describe the bug**
When vorta starts, window is definitely too small on my screen

**To Reproduce**
Start vorta
Window is too small

**Desktop (please complete the following information):**
System:    Kernel: 5.3.0-51-generic x86_64 bits: 64 compiler: gcc 
           v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 

**Additional context**
I have a hidpi screen (3200 x 1800) and I setup my scale factor to 2. Input fields look more or less ok but maybe window size doesn't consider scale factor on init.

Screenshot : https://imgur.com/a/2FimyMb

**Comment by m3nu** [comment]
I'm not on a Linux desktop, but maybe @Hofer-Julian can give a tip.

**Comment by Hofer-Julian** [comment]
@SamuelBenard, does it look fine when you resize the window?

**Comment by SamuelBenard** [comment]
Yes, once resized, aspect is good. Text fields, combo box, everything looks good. It's just the window size

**Comment by m3nu** [comment]
Window size is set in the Qt template. I'm not sure how the actual size is set. If a fix is needed for Linux and someone figures out how to do it exactly, we can add it to the project.

**Comment by Hofer-Julian** [comment]
Scaling the window with the font size might work https://stackoverflow.com/a/25145800/11038610

Btw, are we sure that this is a linux-only problem? Has anyone tested Vorta on a hidpi screen on macOS yet?

**Comment by SamuelBenard** [comment]
I was having a look at this : https://doc.qt.io/qt-5/highdpi.html as qt is hidpi compliant sing qt 5.4. Do you know where main window size is set ? so I can do some tests ? (I don't know nothing about python but with documentation, I can try some things)

**Comment by Hofer-Julian** [comment]
> 
> 
> I was having a look at this : https://doc.qt.io/qt-5/highdpi.html as qt is hidpi compliant sing qt 5.4. Do you know where main window size is set ? so I can do some tests ? (I don't know nothing about python but with documentation, I can try some things)

https://github.com/borgbase/vorta/blob/a4436d8f248f9ba0541409b607295057ba6f3806/src/vorta/assets/UI/mainwindow.ui#L9

**Comment by SamuelBenard** [comment]
that's the template but foud it.

in lib/python3.6/site-packages/vorta/utils.py

replaced

```
from PyQt5 import QtCore
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication, QFileDialog, QSystemTrayIcon

from vorta.borg._compatibility import BorgCompatibility
from vorta.keyring.abc import VortaKeyring
from vorta.log import logger

keyring = VortaKeyring.get_keyring()
logger.info('Using %s Keyring implementation.', keyring.__class__.__name__)
```

with

```
from PyQt5 import QtCore
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QApplication, QFileDialog, QSystemTrayIcon

from vorta.borg._compatibility import BorgCompatibility
from vorta.keyring.abc import VortaKeyring
from vorta.log import logger

QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True) #enable highdpi scaling
QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True) #use highdpi icons

keyring = VortaKeyring.get_keyring()
logger.info('Using %s Keyring implementation.', keyring.__class__.__name__)
```
found info here : https://leomoon.com/journal/python/high-dpi-scaling-in-pyqt5/
Now mainwindow looks right. Do you want me to do a PR ?

**Comment by m3nu** [comment]
I can't test it on Linux, but if it works for you, awesome.

PR would be highly appreciated to have your contribution on official record. Else I can also add it with the next release.

**Comment by m3nu** [comment]
Already merged and in the latest release.
