### ISSUE TITLE
Subfolders restored instead of chosen file

### ISSUE THREAD

**Issue by SamuelBenard** [borgbase/vorta#458]
**Describe` the bug**
If you choose a file that is at root of backup, the whole backup is restored, not only the file. If the file to restore is in subdirectory, then only the choosen file is restored as expected

**To Reproduce**
backup a directory that contains files and dirs. ex :
```
dir_to_backup
  file_1
  file_2
  subdir_1
    file_3
  subdir_2
    file_4

```
If you try to restore file_3 or file_4, works as expected
if you try to restore file_1 or file_2, then all backup files and dirs are restored (file_1, file_2, subdir_1, file_3, subdir_2, file_4)

**Desktop (please complete the following information):**
System:    Kernel: 5.3.0-51-generic x86_64 bits: 64 compiler: gcc 
           v: 7.5.0 Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 

**Additional context**
I didn't spend too much time on this but I can do some more tests if needed

**Comment by m3nu** [comment]
It's known that you can't unselect child files, once a parent is selected. Maybe you mean that.

If you mean that some other random folders are also restored, you should look at the actual Borg command we run (written into the log).

Generally we build a list of files in the backup and append everything you select to the list that Borg will restore. Not great if you want to exclude subfolders, but fairly simple.

**Comment by SamuelBenard** [comment]
Tried again but can't reproduce. I close the issue, I'll reopen it if I can reproduce and trace logs
