### ISSUE TITLE
Cannot open window, backups run normally

### ISSUE THREAD

**Issue by 0fbcb238c0** [borgbase/vorta#459]
**Describe the bug**
Vorta starts and backups normally, but I cannot open the Vorta window to change settings or use any other GUI feature.
I'm using Vorta 0.6.24 with python 3.8 on Manjaro right now, but had this problem on Ubuntu in the past, which persisted up until replacing it with Manjaro. 
I already tried reinstalling, to no avail.

**To Reproduce**
1. When I click the Vorta icon in the taskbar it crashes.
2. The following error mesage is created in the terminal:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/vorta/tray_menu.py", line 28, in on_activation
    self.app.toggle_main_window_visibility()
  File "/usr/lib/python3.8/site-packages/vorta/application.py", line 92, in toggle_main_window_visibility
    self.open_main_window_action()
  File "/usr/lib/python3.8/site-packages/vorta/application.py", line 81, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/usr/lib/python3.8/site-packages/vorta/views/main_window.py", line 35, in __init__
    self.repoTab = RepoTab(self.repoTabSlot)
  File "/usr/lib/python3.8/site-packages/vorta/views/repo_tab.py", line 59, in __init__
    self.init_repo_stats()
  File "/usr/lib/python3.8/site-packages/vorta/views/repo_tab.py", line 78, in init_repo_stats
    self.sizeOriginal.setText(pretty_bytes(repo.total_size))
  File "/usr/lib/python3.8/site-packages/vorta/utils.py", line 105, in pretty_bytes
    return f'{round(size, 1)} {Dic_powerN[n]}B'
KeyError: 5

I would append the Vorta log, but an error message does not appear there.

**Comment by m3nu** [comment]
Looks like you threw a value at the byte-formatting function it didn't like. The actual value doesn't show here, but I'll see if it can be crashed like that.

Thanks for writing in.

**Comment by 0fbcb238c0** [comment]
I would have suspected that it was a problem with the repository, but I can open it normally on a Vorta instance running on my server, where the repo is located.

The reason for my suspicion was that Vorta opens normally as long as that repo (I only have on repo) is not configured but, as mentioned, it works normally on another PC.
After the repo is set as the target location Vorta will crash the next time I try to open the Vorta window.
This also happens only in Vorta, I can backup to the repo using Borg, other Borg functions work also as expected.

Sorry for not mentioning it above, I was quite tired there.

**Comment by m3nu** [comment]
This was fixed via #433. Maybe you have an old version?

**Comment by 0fbcb238c0** [comment]
At the time of the first comment I used Vorta 0.6.24, but after upgrading to the now available 0.6.26 it now works. Thanks
