### ISSUE TITLE
dataset identifier needed

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#46]
when using multiple datasets (== multiple sets of source dirs == multiple profiles) and backing up into a single repo, the archive names are currently missing a dataset identifier in their name (could be the profile name).

this is required for humans (manually dealing with archives) as well as for `borg prune --prefix=...` because prune options can be given for each profile and thus must be limited to the dataset specified in that profile.

could be: `hostname-datasetname-timestamp`

also, the archives list shown to the user should only show archives made by the current profile / the current dataset identifier.

**Comment by m3nu** [comment]
The profile-ID can be used as dataset name. Then one repo can be used for multiple backup profiles.

So the Archive-view should only show archives belonging to a) the current profile AND b) the current repo?

**Comment by ThomasWaldmann** [comment]
Yes.

**Comment by ThomasWaldmann** [comment]
i created a new archive and there is only `-1` added to the name in contrary to the profile name being `testing`, so the expectation would be `-testing`.

**Comment by m3nu** [comment]
The thing is that it's very easy to rename a profile. The profile ID is more permanent.

If the profile name slug is used for pruning or filtering, that could be an issue.

**Comment by ThomasWaldmann** [comment]
i still would prefer having archive names that make obvious sense (even if not using vorta).
so maybe the profiles should not be editable.

**Comment by m3nu** [comment]
Then why not:

`{hostname}-{profile_id}-{profile_name_slug}-{timestamp}`

and only use the first two for pruning/filtering. It's only 2 chars longer and gives the best of both worlds.

**Comment by ThomasWaldmann** [comment]
it still would be strange outside of vorta.

**Comment by m3nu** [comment]
Alright. Then let's save the slug on profile creation and not change it when renaming it.
