### ISSUE TITLE
Allow pasting a list of sources

### ISSUE THREAD

**Issue by patogit** [borgbase/vorta#466]
When adding source folders via the GUI, I have to add them one by one, but I can add exclude patterns all at once. If I have a list of exclude patterns in a text editor, I can just copy and paste the list, and I'd like to be able to do the same for includes, instead of navigating through the file explorer to each of the fifteen sources. Maybe this is related to https://github.com/borgbase/vorta/issues/378

**Comment by m3nu** [comment]
Currently this is a *list* and not a _text field_ for consistency. If a user pastes random text, we would need to validate every directory first and give some error if one has an issue.

For patterns this is not as critical (they simply won't work).

It would probably be possible to make it a text field, while keeping the _Add Folder_ buttons and just append the path and validate it when the text field changes.
