### ISSUE TITLE
Mac app does not show up on dock; not on option+tab options

### ISSUE THREAD

**Issue by jcrben** [borgbase/vorta#470]
**Describe the bug**
Having trouble using this for mac. When I shift focus away from Vorta - for example to copy something - Vorta cannot be accessed again. Option+tab does not list it and the Dock doesn't list. When I click it on the top taskbar it does not open. 

I end up having to reopen it w/ Spotlight. 

Running macOS Mojave 10.14.6

**To Reproduce**
1. Open Vorta w/ Spotlight
2. Press option+tab to shift focus
3. Press option+tab to shift focus back -> not available
4. Click vorta icon in taskbar -> vorta does not open
5. Look for vorta in dock > not there

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6

**Additional context**
~~If appropriate include logs. Can be found in Main Window > Misc Tab > Log.~~
Can provide if needed and instructed.

Notice lack of Vorta in Dock. Hard to take a screenshot of apps showing when hitting option+tab.
![image](https://user-images.githubusercontent.com/5614134/82850343-ddbff900-9eb0-11ea-908e-8704d718e7df.png)

**Comment by jcrben** [comment]
Note: if I click "Add a repository", then option+tab to notes (to copy and paste)
![image](https://user-images.githubusercontent.com/5614134/82850595-dea55a80-9eb1-11ea-80b7-ec78fa00373c.png), then hit this button: 
![image](https://user-images.githubusercontent.com/5614134/82850618-f2e95780-9eb1-11ea-81c8-820a996397e0.png)

The app crashes.

**Comment by m3nu** [comment]
Being a background app, Vorta doesn't show a Dock icon. This is by design.

**Comment by jcrben** [comment]
The app is also crashing, as I noted in my second post. In any case, a poor experience. It should show up in the dock as active when I'm actively using it, like, say, Docker or syncthing.

The brusque handling of this report also helps me decide to avoid borgbase

**Comment by m3nu** [comment]
I don't know what option option-tab would do. It's not implemented.

**Comment by m3nu** [comment]
The thing is that we get many issue reports recently, but almost nobody bothers to make even a simple pull request. Often the bug is on some exotic Linux distribution.

So very sorry if supporting a keyboard shortcut I never heard of offended you. If you need it, feel free to add a PR and it will be added.

**Comment by m3nu** [comment]
I think you mean Cmd-Tab, not Option-Tab?

Vorta runs as background app and doesn't show up there. See also: [LSUIElement](https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement)

**Comment by jcrben** [comment]
Ah, yeah. I mean Cmd+tab. Are you familiar with https://github.com/sieren/QSyncthingTray? It does this better. When the app is open, it shows up in the Dock. But when I close the UI, it keeps running in background.

**Comment by m3nu** [comment]
I would love to have it in the Dock, when the main window is open, but don't know how and don't have the time to dig into this in the near future.

If you know the settings required, then just open a PR and I'll add it.
