### ISSUE TITLE
UI Crash when adding same repo twice

### ISSUE THREAD

**Issue by vapaavetehinen** [borgbase/vorta#473]
**The bug**
Re-adding the same repo and then deleting it creates an inconsistency between the app and the database which crashes the UI.

**To Reproduce**
1. Have one existing repository connection
2. Click on Add Existing Repository
3. Put in the same path for the existing connection. This seems to update the UI, but point to the same database entry. If you close the UI and reopen it it will just show the one repo, but in the existing UI session it remains as a second entry.
4. Delete the new entry.
5.  Select the other remaining entry. The UI will crash and cannot be recovered without fixing or recreating the database file.

**More Info**
Version: v0.6.23
The error is as follows when you try to open the UI window after deleting the bug:
```
Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/peewee.py", line 6665, in get
    return clone.execute(database)[0]
  File "/app/lib/python3.7/site-packages/peewee.py", line 4121, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/application.py", line 80, in open_main_window_action
    self.main_window = MainWindow(self)
  File "/app/lib/python3.7/site-packages/vorta/views/main_window.py", line 37, in __init__
    self.repoTab = RepoTab(self.repoTabSlot)
  File "/app/lib/python3.7/site-packages/vorta/views/repo_tab.py", line 59, in __init__
    self.init_repo_stats()
  File "/app/lib/python3.7/site-packages/vorta/views/repo_tab.py", line 74, in init_repo_stats
    repo = self.profile().repo
  File "/app/lib/python3.7/site-packages/peewee.py", line 4269, in __get__
    return self.get_rel_instance(instance)
  File "/app/lib/python3.7/site-packages/peewee.py", line 4260, in get_rel_instance
    obj = self.rel_model.get(self.field.rel_field == value)
  File "/app/lib/python3.7/site-packages/peewee.py", line 6242, in get
    return sq.get()
  File "/app/lib/python3.7/site-packages/peewee.py", line 6670, in get
    (clone.model, sql, params))
vorta.models.RepoModelDoesNotExist: <Model: RepoModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."url", "t1"."added_at", "t1"."encryption", "t1"."unique_size", "t1"."unique_csize", "t1"."total_size", "t1"."total_unique_chunks", "t1"."extra_borg_arguments" FROM "repomodel" AS "t1" WHERE ("t1"."id" = ?) LIMIT ? OFFSET ?
Params: [1, 1, 0]
```

**Comment by vapaavetehinen** [comment]
I forked the project and added a commit in a new branch with a couple different approaches to fixing this issue. Could I get a maintainer (probably m3nu) to take a look and weigh in on the fix before I open a pull request? Maybe there's a third approach that could be suggested if the ones I have written seem unfitting for some reason.

**Comment by m3nu** [comment]
On it.

**Comment by m3nu** [comment]
Good change. Do you think the one in [`repo_add_dialogue.py`](https://github.com/vapaavetehinen/vorta/commit/f0baa93da19afa855d5af8b58d2e2e3c8ba15bc4#diff-0b8e171e9469f4181d6533a96548aeeeR116) is sufficient? One could argue that the same repo should never be added twice.

The second change to `repo_tab.py` solves a different problem to keep the list in sync.

Shall we just add both?

**Comment by m3nu** [comment]
I agree that the same repo should only be added one time. Else the same archive would be saved multiple times and archives would be missing until refresh.

Let's definitely add the first change. For the second change I'll have a look. If I was too sloppy with keeping repos in sync, it's probably a good idea to add it too.

Have you enabled "Allow Contributors to push to this branch", so I can make changes?

**Comment by vapaavetehinen** [comment]
Just added you as a collaborator. Not sure if there's a better way to do that.

**Comment by m3nu** [comment]
No worries. Already did the pull request. Both is fine.
