### ISSUE TITLE
Password confirmation on repo init

### ISSUE THREAD

**Issue by vapaavetehinen** [borgbase/vorta#479]
The initialize new repository window should have a second field to retype the password as confirmation to help prevent people from typing it incorrectly by mistake.
Alternately the password field could be clear text or have a toggle/checkbox to be clear text.

**Comment by m3nu** [comment]
I'll move this to #385, which already has more details on the same topic. Particularly the requirements summarized in this [comment](https://github.com/borgbase/vorta/issues/385#issuecomment-635060484).
