### ISSUE TITLE
"Backup now" tray list is not updated for new profiles

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#48]
I have 2 profiles, but the tray menu only offers me "backup now" for the first profile.

**Comment by ThomasWaldmann** [comment]
restarting vorta helps, now it shows both profiles.

can it update the menu dynamically?

**Comment by m3nu** [comment]
It's [already](https://github.com/borgbase/vorta/blob/master/src/vorta/tray_menu.py#L55) re-generated before opening to account for renamed profiles. Not sure why it only showed one profile. Will try to reproduce.

**Comment by ThomasWaldmann** [comment]
http://doc.qt.io/qt-5/qsystemtrayicon.html#ActivationReason-enum

this is a bug of the desktop environment, in my case: ubuntu 18.04 with standard gnome.

**Comment by ThomasWaldmann** [comment]
https://stackoverflow.com/questions/43657890/pyqt5-qsystemtrayicon-activated-signal-not-working

works for me. @m3nu does it work on macOS also?

**Comment by m3nu** [comment]
Yes. System tray was always working on macos.

**Comment by ThomasWaldmann** [comment]
I rather meant the new code in the PR.
