### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by Hofer-Julian** [borgbase/vorta#482]
https://github.com/borgbase/vorta/blob/09b697e39599a3d519d7bffe0abd1a44ca4e2948/src/vorta/models.py#L212 is not translated in the most recent release of Vorta.
However https://www.transifex.com/borgbase/vorta/ displays 100% translation for German.

Is it possible that Transifex isn't aware of the newest strings?

**Comment by m3nu** [comment]
Yes. Needs to be updated sometimes. `Makefile` has the commands. I'll do it some time.

**Comment by m3nu** [comment]
Just pushed new strings and made you a translation maintainer @Hofer-Julian 🤝

Commands to upload new strings to Transifex are:

```
$ make translations-from-source
$ make translations-push
```

Needs the Transifex client installed and setup first.

```
$ pip install -U -r requirements.d/dev.txt
```
