### ISSUE TITLE
Zstandard "auto" compression?

### ISSUE THREAD

**Issue by geckolinux** [borgbase/vorta#485]
Hi there,

Does the Zstandard compression algorithm by default automatically detect which files are compressible? If not, would it be possible to include an "auto" option for the Zstandard menu choices?

![Screenshot_20200601_203911](https://user-images.githubusercontent.com/2692138/83470515-06636800-a448-11ea-9d6e-e855fe712737.png)

Thanks a lot for your great work on Vorta, I've been using Borg for years, but Vorta is what motivates me to actually keep regular backups.

**Comment by m3nu** [comment]
Thomas, the main Borg maintainer recommended to use "auto" only for older/slower compression algos. We preserved the thinking behind it in the comments and there is probably an issue for it too: https://github.com/borgbase/vorta/blob/master/src/vorta/views/repo_tab.py#L32

I'm assuming modern algos detect and skip mp4 files or jpegs. Didn't do a benchmark though.

Good to hear the project made you do backups. That's the real goal in the end. 👍

**Comment by phiresky** [comment]
Testing with an (incompressible) `mkv` file I can say that zstd definitely doesn't completely skip incompressible data:

`zstd -15 *.mkv  1:28,82 total`

`zstd -8 *.mkv  20,115 total`

`zstd -3 *.mkv  3,832 total`
