### ISSUE TITLE
Scalable icon (application/Desktop icon) has poor visibility in dark menus

### ISSUE THREAD

**Issue by sten0** [borgbase/vorta#489]
Scalable icon (application/Desktop icon) has poor visibility in dark menus.  Screencap attached.

[output.zip](https://github.com/borgbase/vorta/files/4727402/output.zip)

(p.s. this screencap also demonstrates the keyword added in #488)

**Desktop (please complete the following information):**
 - OS: Debian sid, KDE/Plasma

A quick query found these:
https://forum.kde.org/viewtopic.php?f=285&t=123468
https://forum.kde.org/viewtopic.php?f=285&t=123132

Most people seem to just choose/create an icon that looks good on both dark and light themes.  One alternative I've considered is depending on the Breeze iconset, which provides both light and dark variants, and using either their coloured or their symbolic svg icon according to the configured icon-set.  If you'd like I can look into this some more and see if there's a better way.

**Comment by m3nu** [comment]
I think we'll just recolor it to have one icon only. It's simple enough with a SVG. I already changed the dark blue hyperlinks in the UI to work on both backgrounds. Will look for some color ideas.

Cool stuff with the keyword.

**Comment by m3nu** [comment]
Related: https://hig.kde.org/style/color/index.html

**Comment by m3nu** [comment]
Change the grey color to have >3 [contrast ratio](https://snook.ca/technical/colour_contrast/colour.html#fg=888888,bg=EFF0F1) on both KDE backgrounds

KDE:
![Screen Shot 2020-06-12 at 11 59 12](https://user-images.githubusercontent.com/3916435/84463412-488c7500-aca4-11ea-8343-2d86d149b02f.jpg)
![Screen Shot 2020-06-12 at 11 59 28](https://user-images.githubusercontent.com/3916435/84463424-54783700-aca4-11ea-857e-3d1edc91e200.jpg)

macOS:
![Screen Shot 2020-06-12 at 12 19 45](https://user-images.githubusercontent.com/3916435/84464466-26482680-aca7-11ea-8fd9-07468841ad5a.jpg)
![Screen Shot 2020-06-12 at 12 20 16](https://user-images.githubusercontent.com/3916435/84464472-28aa8080-aca7-11ea-988c-ac5a51e22e58.jpg)

**Comment by sten0** [comment]
Hi Manu,

Sorry I thought I had replied to this issue.  Thank you for sharing the
screenshots, I appreciate it :-)

It looks to me like the objective was to make the icons look the same
relative value (relative to the background).  Anyways, if that was your
objective, It's been achieved.  It might also be worth checking to see
how it looks with a white window underneath the semi transparent menu.

With the transparency, and a white window behind, the contrast for the
Breeze (light variant) will probably be enhanced, and I suspect it will
diminished for the Breeze-Dark variant.  I'm guessing you tested this
case, and you chose the best match?  I'm thinking 5% to 10% darker will
make it visually stand out better with a white window underneath,
because the Breeze-Dark variant matches the "Backup Software" text,
and that text's colour looks like will be invisible with a white under
window.

**Comment by m3nu** [comment]
I always tested with the pure background color (as specified [here](https://hig.kde.org/style/color/index.html)), not the transparent version with some window behind it. The current shade of grey gave roughly the best contrast in both directions. Personally I prefer a slightly darker tone too, but that gave lower contrast values.

**Comment by sten0** [comment]
Hi Manu,

Manu <notifications@github.com> writes:

> I always tested with the pure background color (as specified [here](https://hig.kde.org/style/color/index.html)), not the transparent version with some window behind it. The current shade of grey gave roughly the best contrast in both directions. Personally I prefer a slightly darker tone too, but that gave lower contrast values.
>

Is the icon the same shade with both variants?  The MacOS example makes
them look like different shades...maybe it's one of those "relative
contrast" psycho-visual tricks where the same shade looks different on
different backgrounds?  At any rate thank you for investigating and
making this change, it's a definite improvement!

Update on the Debian package: I've uploaded it, and we're now waiting
for Debian project procedures...these have been slow recently, so it
could be September by the time it becomes available to users, and I'm
not sure if that's early enough to make it into Ubuntu 20.10.  Updates
are much faster an easier after the initial acceptance, btw :-)

**Comment by m3nu** [comment]
Probably a psycho-visual effect related to the background. I'll probably end up making it slightly darker before the next release anyways.

Also good stuff with the Debian package. I'll follow the progress. 👍
