### ISSUE TITLE
question/Feature request: Key management

### ISSUE THREAD

**Issue by jchhenderson** [borgbase/vorta#490]
I am using Vorta as I am not comfortable with Borg's CLI - so far, so good :-)

I am currently backing to my local NAS and am about to trial Borgbase.

It has occurred to me that Vorta holds my SSH keys I have no clue where they are to copy them for safety etc.

It would therefore be great of there was a way to export/import the public key or private/public key combo.

Meanwhile I have 2 questions:
1] If I create a new repo and stick with auto-choose SSH key, will it use the same one from my previous repo or select a new one for the new repo?

2] If I move to a new machine and want to restore my files to that new machine, how do I get my SSH keys in order to setup Vorta on that new machine?  or more precisely, are my keys stored in ~/.local/share/Vorta/settings.db?

thanks,
James.

[edit: added location of settings.db to question]

**Comment by jchhenderson** [comment]
perhaps this should be closed against #462?

**Comment by jchhenderson** [comment]
Thanks!

I know I am about to ask an uneducated question, buuuut....

If the SSH keys are not critical and it is OK to lose them. ....why have them in the first place and/or why not hide them entirely from the UI?  What are they doing?

...are they generated from the encryption password?

**Comment by m3nu** [comment]
They are still needed for access and the authentication part.

Not generated from the Borg passphrase, just randomly.

**Comment by jchhenderson** [comment]
sorry to be dumb here, but if I need it for access and it is generated randomly, surely I need it (as I will lose access it otherwise).

**Comment by Hofer-Julian** [comment]
@jchhenderson, these concept are not that easy to understand, so please don't feel bad :)
You need your SSH-key only when you try to access remote places, like e.g. your repository on borgbase.
These kind of services allow you to add the public part of your SSH-key-pair as **additional** access method.
But you'll still have username+password to log in and add another public key, if you'd ever lose the original one.

**Comment by jchhenderson** [comment]
agh, so it is not important because new keys can be generated.

So, the keys are required to access the repo and are generated by the repo (not Borg).  Vorta's special relationship with BorgBase means it also handles the creation of Borgbase's keys internally?
