### ISSUE TITLE
Question: Can I backup the same spruces to multiple destinations in the same profile?

### ISSUE THREAD

**Issue by jchhenderson** [borgbase/vorta#491]
Hi,

I have setup a backup to my local NAS (ironically called Borg - has been for years).

I now want to backup the exact same sources offsite (to Borgbase).

Do I need to create a new profile and manually select the same sources or can I just create a new destination and have Borg backup to both destinations using the same sources in the same profile?

I ask because making a new profile would mean having to manually keep the sources is sync (if I make changes on the future).

**Comment by m3nu** [comment]
Currently Vorta only supports one destination per profile (can be changed easily with the dropdown).

Eventually we'd like to support multiple destinations, like Borgmatic already does. I imagine making the repo dropdown a list with checkboxes, so multiple items can be selected.

We already have an issue for this, so I'll close this one. For details see https://github.com/borgbase/vorta/issues/103.
