### ISSUE TITLE
is this warning a concern?

### ISSUE THREAD

**Issue by jchhenderson** [borgbase/vorta#493]
**Describe the bug**
My logs always show this warning when backing up:
`- vorta.borg.borg_thread - WARNING - /Users/jameshenderson/Pictures/Photos Library.photoslibrary: scandir: [Errno 1] Operation not permitted: '/Users/jameshenderson/Pictures/Photos Library.photoslibrary'`

**To Reproduce**
Every scheduled backup (I am trialling 3 destinations and it is on all of them)

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.5
**Additional context**
[vorta.log](https://github.com/borgbase/vorta/files/4764216/vorta.log)

**Comment by m3nu** [comment]
Probably due to macOS sandboxing. You'd have to enable full disk access to allow it to read all the files. Else a few folders like contacts or calendar files will be skipped.

![Screen Shot 2020-06-11 at 19 14 29](https://user-images.githubusercontent.com/3916435/84379066-d0786d80-ac17-11ea-9d54-c5cc258ec461.jpg)

**Comment by jchhenderson** [comment]
cheers.

**Comment by lamixer** [comment]
Hello! 

On MacOS 10.15.7 there is no longer a way to manually add a program in the full disk access preferences -- Apple took away the + button. Setting up Vorta (via Homebrew) 0.7.3 I added several folders from my home folder. Documents and others work fine, and the Pictures folder works, but the actual "Photos Library.photoslibrary" cannot be read (I assume, as it is 0 bytes when I mount and browse the backup and the size is clearly missing my large photo library.

Any tips?

Thank you!

**Comment by m3nu** [comment]
> Apple took away the + button.

No. Still there in latest stable.

![Screen Shot 2021-02-25 at 09 00 50](https://user-images.githubusercontent.com/3916435/109087416-602f5f00-7748-11eb-8132-653da087c831.jpg)

**Comment by lamixer** [comment]
Argh! Sorry. I confused myself (the hour here was too late to be piling on bug reports). I was able to grant Vorta full disk access and that solved the problem. My confusion (no excuse) was that I also was poking around the 'Photos' privacy setting which unfortunately does  not have the add button, forcing us to use the full disk access option.

That is of course a MacOS issue, not Vorta. Thank you! Vorta is lovely.

![MacOS-Photos-Privacy](https://user-images.githubusercontent.com/4958776/109134787-527cd800-774e-11eb-8f28-72ff76ab4e3b.png)
