### ISSUE TITLE
flatpak on flathub has outdated borg

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#494]
on a fresh ubuntu mate 20.04 install, I added flatpak / flathub and installed `com.borgbase.Vorta`.

it says, it has borg `1.1.10` (/app/bin/borg), which is a few patch releases behind.

i'ld like to recommend that this is updated to `1.1.13` asap, because there were major bug and performance fixes (specifically: FUSE performance, extract/diff/... memory leak fix).

**Comment by ThomasWaldmann** [comment]
There is also that potential index corruption issue that was fixed in 1.1.11+, but is still present in 1.1.10:

https://raw.githubusercontent.com/borgbackup/borg/1.1.11/docs/changes.rst

**Comment by m3nu** [comment]
Can Flatpak always use the latest version, @Hofer-Julian ?

**Comment by Hofer-Julian** [comment]
Thanks for the reminder @ThomasWaldmann, the next time you update you should have the newest borg version. I'll try to keep up with the point releases from now, I assume it is enough to follow borgbackup's twitter feed to be up to date?

@m3nu a quick search tells me that there is one who does it with a custom script plus github actions. I think until something similar becomes more streamlined, I'll do it manually.

**Comment by m3nu** [comment]
I can also update it before releases, if you tell me the file to change. (assuming it's in this repo)

**Comment by Hofer-Julian** [comment]
It is not in the repo.
[This](https://github.com/borgbase/vorta/tree/master/flatpak) is only used for local builds.
You'd have to do something like [this](https://github.com/flathub/com.borgbase.Vorta/pull/24/files). If you don't already have access to this repo, it would be easy to give it to you.

**Comment by Hofer-Julian** [comment]
[Here](https://github.com/flatpak/flatpak-builder-tools/tree/master/pip) is the official tool to make updating/creating of modules easier.

**Comment by ThomasWaldmann** [comment]
Solved by #500, thanks!
