### ISSUE TITLE
unclear: "(als Systemverwalter)"

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#495]
Installed vorta from flathub on ubuntu 20.04.

Window title says "Vorta for Borg Backup (als Systemverwalter)" (english: "as System Administrator").

It is unclear to me what that means practically.

Is vorta running as `root`?

Will vorta run `borg` as `root`? (using `sudo`?)

When deciding what to back up (on the "Sources" tab), this is important to know.

If it runs as `root`, one can add arbitrary stuff there.

If not, one better stays within the current user's home directory or will see permission issues while doing a backup.

**Comment by m3nu** [comment]
Seen this before, @Hofer-Julian ?

**Comment by Hofer-Julian** [comment]
@ThomasWaldmann Neither borg nor vorta are run as root.
It seems to be a known problem of Mate/Flatpak though, that it reports falsely that flatpaks are run as root https://www.linuxquestions.org/questions/linux-software-2/why-do-flatpak-programs-have-as-superuser-in-the-title-bar-4175645382/

**Comment by ThomasWaldmann** [comment]
Ah, thanks for explaining!
