### ISSUE TITLE
Strange icon in system tray after installing from Flatpak

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#496]
ubuntu mate 20.04, vorta from flatpak.

the icon shown at the top right looks like a light rectangular frame with a red round "forbidden" traffic sign inside.

**Comment by ThomasWaldmann** [comment]
maybe related to #318?

**Comment by m3nu** [comment]
Only testing on Debian testing/KDE these days. Maybe a screenshot would be helpful.

@Hofer-Julian

**Comment by Hofer-Julian** [comment]
@ThomasWaldmann, would be nice if you could test, if it also appears when installed via pip

**Comment by ThomasWaldmann** [comment]
customer system i had for some maintenance, do not have access easily.

**Comment by Hofer-Julian** [comment]
Okay, then let's close it for now :)
