### ISSUE TITLE
Use double inputs for repository password

### ISSUE THREAD

**Issue by ktosiek** [borgbase/vorta#499]
**Is your feature request related to a problem? Please describe.**
A typo when creating a repository might make the backups unusable.

**Describe the solution you'd like**
Using a second masked input, or an unmasked one, would let the user make sure the password that was typed in was the correct one.

**Describe alternatives you've considered**
Writing the password in an external editor and copying it into Vorta helps, but the UI should be safer by default.

**Comment by m3nu** [comment]
We already have an issue for that, so I'll close this one.

**Comment by ktosiek** [comment]
Just as a note: it seems this is tracked in #385.

**Comment by m3nu** [comment]
Yes. Thanks for linking. I renamed the other issue to emphasize it got more broad.
