### ISSUE TITLE
Don't know how to add an existing repository (via Port 23)

### ISSUE THREAD

**Issue by ralfzosel** [borgbase/vorta#505]
I have an existing repository on a so called [storage box](https://community.hetzner.com/tutorials/install-and-configure-borgbackup) which I can access via ssh from my server e. g. like that: 

`borg list ssh://u123456@123456.your-storagebox.de:23/./backups`

When I try to add that as an existing repository to Vorta, I don't know how to enter the Repository URL. I tried the following:

- `u123456@u123456.your-storagebox.de:23/./backups` → Unable to add your repository
- `u123456@u123456.your-storagebox.de:23` → Unable to add your repository
- `u123456@u123456.your-storagebox.de:backups` → Unable to add your repository
- `u123456@u123456.your-storagebox.de` → Please enter a valid repo URL or select a local path

I could not find much information, how to enter the Repository URL properly except the placeholder `csvis8xq@csvis8xq.repo.borbase....`  and the example `izral6we@izral6we.rep.borgbase.com:repo` [in the docu](https://vorta.borgbase.com/usage/remote/).

Perhaps, the access via Port 23 is the problem? Does that work with Vorta (and how)? It would be great if this case would be mentioned in the documentation – or did I simply miss it?

**Comment by ThomasWaldmann** [comment]
Did you try using `ssh://u123456@123456.your-storagebox.de:23/./backups` with vorta?

For a special port, you need the `ssh://` syntax, because the `user@host:` syntax used the colon for other purposes.

**Comment by ThomasWaldmann** [comment]
The placeholder of course should suggest the syntax that works for everybody.

**Comment by ralfzosel** [comment]
Sorry, I forgot to mention that I also tried this with `ssh` (as you suggested now) – with the same result: →Unable to add your repository.

But, after I changed the key on the second tab, it finally started "Fetching and building archive indes …" which is great. Thank you for your help!

With the message on the first tab, I did not expect a misconfiguration on the second tab. So that also could be improved on the UI.

**Comment by m3nu** [comment]
> With the message on the first tab, I did not expect a misconfiguration on the second tab. So that also could be improved on the UI.

You mean the AddRepo window? There are two tabs, but only one error message for the window. You should see the same error on both tabs, since the error is for the window, not one tab. We don't have errors specific to one tab. They are simply used to structure the input.

So we are probably good here and I'm closing this issue.

![Screen Shot 2020-06-15 at 20 03 35](https://user-images.githubusercontent.com/3916435/84655393-76dbb000-af43-11ea-84eb-e491604c2417.jpg)
