### ISSUE TITLE
Vorta should use the XDG Base Directory Specification

### ISSUE THREAD

**Issue by x80486** [borgbase/vorta#513]
## Describe the bug

I started using Vorta for backups. I use the Flatpak version and I noticed that somehow, a subdirectory `${USER}/.local/state/Vorta/` is created — with just one file: `socket`.

> I'm assuming this path is hard-coded because all the other files are going correctly into their corresponding subdirectories under `${USER}/.var/app/com.borgbase.Vorta/`.

## To Reproduce

1. Install Vorta Flatpak
2. Initialize a new repository with `Repokey-Blake2` (I can't see that subdirectory created with `Keyfile-Blake2`, but I might have missed it in the many tries testing `Vorta`)
3. `cd` into `${USER}/.local/state/Vorta/` :wink: 

## Desktop (please complete the following information):

- OS: Arch Linux `Linux uplink 5.4.46-1-lts #1 SMP Wed, 10 Jun 2020 20:36:34 +0000 x86_64 GNU/Linux`.

**Comment by x80486** [comment]
Looks like `STATE_DIR` in `config.py`:

```python
import appdirs

APP_NAME = 'Vorta'
APP_AUTHOR = 'BorgBase'
dirs = appdirs.AppDirs(APP_NAME, APP_AUTHOR)
STATE_DIR = dirs.user_state_dir
```

...is resolving to `${HOME}/.local/state/${APP_NAME}/`; probably because `XDG_STATE_HOME` is not defined in the Flatpak environment :roll_eyes:

**Comment by Hofer-Julian** [comment]
Thanks fo opening the issue.
You are right, the Vorta flatpak shouldn't create files outside .var and conform to standards instead.

@samuel-w do you want to have a look, or should I look into it?

**Comment by samuel-w** [comment]
You look into it, currently working on issue 487
