### ISSUE TITLE
Installation on Linux - FileNotFoundError

### ISSUE THREAD

**Issue by khalsajing** [borgbase/vorta#514]
**Describe the bug**
Installation fails on Debian Buster using pip3: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-b16s_xhj/pyqt5/setup.py'. Similar bug reported, now closed, a few years ago: "Installation on Linux #9"

**To Reproduce**
1. sudo apt install borgbackup. borg 1.1.9 installed.
2. sudo apt-get install python3 python3-dev python3-pip python-virtualenv libssl-dev openssl libacl1-dev libacl1 build-essential
3. sudo apt-get install libfuse-dev fuse pkg-config
4. pip3 install vorta and pip3 install --user vorta: Both yield the same result. Including trying as root user.
5. Installation quits with: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-b16s_xhj/pyqt5/setup.py'

**Desktop (please complete the following information):**
 - Running on VirtualBox for testing before moving to production (flatpak works, but is not permitted in production).
 - OS: Linux xyz 5.5.0-0.bpo.2-amd64 #1 SMP Debian 5.5.17-1~bpo10+1 (2020-04-23) x86_64 GNU/Linux
  - python3 -V: Python 3.7.3
  - pip3 --version: pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7)

**Additional context**
[vorta.log](https://github.com/borgbase/vorta/files/4789601/vorta.log)

**Comment by m3nu** [comment]
This was reported before for PyQt. I think the solution was to upgrade `pip`. It's not a Vorta issue.

**Comment by khalsajing** [comment]
For anyone trying to install the vorta client on debian 10.4 (buster), the default apt installs version: pip3 --version: pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7). m3nu's suggestion works. After installing pip3, run: pip3 install -U pip. This upgrades pip3 to: pip 20.1.1 from /home/sistum/.local/lib/python3.7/site-packages/pip (python 3.7). Not intuitively obvious: but now you can install vorta via pip3.
