### ISSUE TITLE
Display Borg Warning When Initializing New Repository

### ISSUE THREAD

**Issue by hutson** [borgbase/vorta#526]
**Describe the bug**

I encountered difficulties while attempting to initialize a new BorgBackup repository in Vorta (Using the Flatpak version).

After providing a _Repository URL_, a _Borg passphrase_, and pressing Add, there was a momentary flash where Vorta displayed a Borg error before displaying _Unable to add your repository_.

![Screenshot_20200625_232314](https://user-images.githubusercontent.com/6701030/85820384-bd978a00-b73b-11ea-84fa-cdd46bc7f1c7.png)

I ran Vorta directly using Flatpak (`flatpak run com.borgbase.Vorta`), and noticed the following output:

```bash
2020-06-25 23:19:31,929 - vorta.borg.borg_thread - WARNING - Remote: Bad owner or permissions on /home/[USERNAME]/.ssh/config
2020-06-25 23:19:31,935 - vorta.borg.borg_thread - ERROR - Connection closed by remote host. Is borg working on the server?
```

The `ERROR` was the flash in the Vorta dialog. However, it was the `WARNING` that was the ultimate culprit. Turns out I needed to set the permissions on the `config` file to `600` (`chmod 600 ~/.ssh/config`). 

After that change I was able to successfully initialize a new repository.

**To Reproduce**
1. Set permission of `~/.ssh/config` to `660`.
1. Run Vorta directly using `flatpak`.
1. Navigate to the _Initialize New Repository_ dialog.
1. Provide _Repository URL_ (From BorgBackup).
1. Enter random string into _Borg passphrase_.
1. See `WARNING` in console, but no hint in the Vorta dialog.

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04

**Expected Behavior**

Please display Borg warnings to provide the user with actionable information that may help them address issues during the initialization process.

**Comment by m3nu** [comment]
Already covered under #375, so closing here.
