### ISSUE TITLE
Unable to initialize a new repository

### ISSUE THREAD

**Issue by kabaga** [borgbase/vorta#529]
**Describe the bug**
I could not initialize a new repository in Xubuntu 18.04. I created a directory /mnt/tower_borgbackup on my Xubuntu and mounted my NFS share from my NAS. The df -h shows the NFS directory has been mounted through /mnt/tower_borgbackup.  When I navigate through the Vorta > Initialize New Repository > Browse the folder structure until I find the /mnt/tower_borgbackup, the Open Folder button is greyed out. I could not select any directory. I tried to create a new directory in Documents to test and I could not select it as the destination repo.

**To Reproduce**
1. Click on Initialize New Repository
2. Select any directory or NFS share
3. Click the Open Folder button
4. No error the button is greyed out

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Flatpak installed

**Additional context**
See screenshot https://imgur.com/a/MfcsFqP

**Comment by Hofer-Julian** [comment]
Do you have this problem only for nfs mounts?

**Comment by kabaga** [comment]
> Do you have this problem only for nfs mounts?

I could copy a file from Documents and pasted it to the nfs mount and it showed up at my NAS. In Vorta, I simply could navigate /browse around and open any folder, but the final folder is unselectable as shown in my screenshot. I could not select any folder due to the Open button is greyed out.

**Comment by Hofer-Julian** [comment]
I do remember that we had similar problems with people using a old flatpak version. Please make sure you use the one from the official PPA
