### ISSUE TITLE
Repository Space Warning

### ISSUE THREAD

**Issue by hutson** [borgbase/vorta#532]
**Is your feature request related to a problem? Please describe.**

I recently added a new directory to the _Sources_ list that would exceed the 10GB limit available in the free plan on BorgBase to test the behavior of Borg+Vorta+BorgBase.

During the upload process Vorta displayed the following error:

![Screenshot_20200628_192022](https://user-images.githubusercontent.com/6701030/85965913-e90cb580-b983-11ea-9db2-d4f480ce153e.png)

First, there was no indication that adding the new directory would exceed the available storage space. Had this not been intentional I may have been in a situation where I added a directory to be backed up only to find out hours/days later that it had not been successfully uploaded. 

Second, when I looked at the _Archives_ page there was no backup available for today. I would have expected to see a list of files that _were_ successfully uploaded up to the point when space ran out. Unfortunately it appears as if nothing was backed up. Had this been a 401GB directory on a 100GB plan, I _think_ the backup would have failed at 400GB leaving nothing to show for the time and effort to upload.

![Screenshot_20200628_192120](https://user-images.githubusercontent.com/6701030/85966403-48b79080-b985-11ea-8aff-30e3dc569831.png)

**Describe the solution you'd like**

There are several ways activity may create more data than can be accommodated by the remote server. For this particular case, is it possible for Borg to pre-calculate the space that will be consumed by the backup and then check with the remote repository to verify space is available before beginning the backup?

In another backup tool I use, this is the default behavior, and disabling that behavior is an application preference:

![Screenshot_20200628_204939](https://user-images.githubusercontent.com/6701030/85967162-700f5d00-b987-11ea-85ce-6bd7e07e96f7.png)

I believe Borg maintains a lock on the remote repository so that it's not possible for another backup process to consume the space before the backup is complete. However, this may not matter in the case where the remote repository is sharing a single account with multiple repositories that count against the same disk space quota.

**Comment by samuel-w** [comment]
I don't think there is a way for Borg to pre-calculate the space, as deduplication and compression reduce storage usage by a lot (For me, 200GB turns into 30GB). There is a way to disable space calculations, but its a bit hacky IMO https://github.com/borgbackup/borg/commit/43acbb92dabf08b7cae9e7a264c06c92194a484c.

**Comment by ThomasWaldmann** [comment]
borg does checkpoints now and then, default interval is (iirc) every 1800s.

have a look using `borg list --consider-checkpoints REPO`.

if you see .checkpoint archives with that, these are valid, but incomplete archives.

you usually do not need to manually deal with them because they will be pruned if there is a newer complete archive.

but if you want to save some backup time, do not delete the checkpoints until you have created a complete backup - this will safe time due to deduplication.

**Comment by hutson** [comment]
> borg does checkpoints now and then, default interval is (iirc) every 1800s

I did not get a chance to run `borg list`, but I did notice checkpoints after I pressed the _Refresh_ button on the _Archives_ page.

![Screenshot_20200630_214956](https://user-images.githubusercontent.com/6701030/86199283-4b4ded80-bb1f-11ea-89eb-affdf976d880.png)

> and yes, as @samuel-w said, it is not easy/quick to compute space usage in advance, so the easiest solution is to not be too tight on backup space

Thank you to both you and @samuel-w for helping me to understand why it may not be advantageous to have Borg+Vorta per-calculate disk space consumption.

**Comment by samuel-w** [comment]
We might be able to do this by averaging the last N backup sizes and giving a message like "This backup might exceed your free storage space", but it would be inaccurate if you don't do frequent backups.

**Comment by hutson** [comment]
Resolving.

As noted above, pre-calculating space usage is virtually impossible.

I believe #375 and #366 will improve the user experience around this particular failure case.
