### ISSUE TITLE
Can't Diff or Mount Archives While Backup Running

### ISSUE THREAD

**Issue by hutson** [borgbase/vorta#533]
**Describe the bug**

I wanted to demonstrate how to run a diff between two archives, but after pressing the _Diff_ button on the diff dialog, nothing happened (The dialog vanished but no diff was shown).

I suspect this is because I am currently running a backup job.

**To Reproduce**
1. Press _Start Backup_.
2. Click on the `Diff` button on the _Archives_ tab.
3. Chose two archives to diff.
4. Press `Diff` and observe that the dialog disappears and no diff is shown.

**Desktop (please complete the following information):**
 - OS: Kubuntu
- Installation method: Flatpak

**Comment by Hofer-Julian** [comment]
Yeah, the borg repository is locked while you access it.
A second access attempt will fail
