### ISSUE TITLE
expect different borg rc codes for signals

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#536]
just an early "incoming change" warning for borg:

https://github.com/borgbackup/borg/issues/5161 - this will be fixed in master and 1.1-maint soon and get into next releases.

not sure if vorta has specific expectations about borg signal rc being 2 (bug since long), but if it has, it has to cope with a change to 128+N (as documented).

especially: SIGTERM, SIGHUP, SIGINT (Ctrl-C), see the PRs.

**Comment by m3nu** [comment]
Thanks for the note. We do use it to check the status of Borg commands to run. But only 0 and 1 mainly. Will still review it.
