### ISSUE TITLE
Ensure all archive action buttons are disabled if a backup is in progress

### ISSUE THREAD

**Issue by hutson** [borgbase/vorta#538]
**Is your feature request related to a problem? Please describe.**

Based on my feedback in https://github.com/borgbase/vorta/issues/533, it was not apparent to me that the _Backup is already in progress_ text seen underneath the _Extract_ button was in response to my attempt to run a Diff.

**Describe the solution you'd like**

It would help if the feedback was more closely tied to the action.

For example, while a backup is running, disable the _Diff_ button and add a hover over tooltip that says "Can not diff archives while running a backup".

**Describe alternatives you've considered**

Allow the _Diff_ button to be clicked, but display a dialog with the same text as above.

**Comment by ThomasWaldmann** [comment]
Guess this issue is more generic.

If the borg repo is locked (due to some active borg action), you can not do much (not just "not diff", but rather "not anything").

**Comment by m3nu** [comment]
We used to disable all the action buttons when a backup was already running. Looks like this feature got lost on the way. I'll make sure it works again.

**Comment by m3nu** [comment]
Should be like this, but the buttons currently don't disable when starting a backup from the main window, only when doing an action from the archive tab. This needs changing. Buttons should disable every time.

![Screen Shot 2020-07-02 at 07 27 06](https://user-images.githubusercontent.com/3916435/86300492-91957080-bc35-11ea-8ed9-1482984fc67a.jpg)
