### ISSUE TITLE
MacOS: Vorta window not accessible via CMD-TAB

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#541]
**Describe the bug**
On macOS (10.15.5), I can not switch to the Vorta window (when opened) via CMD-TAB. However, it is available in Mission Control. 

**To Reproduce**
1. In task menu, open Vorta
2. Switch to other window
3. Try to go to Vorta using CMD-TAB

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by m3nu** [comment]
Please see [here](https://developer.apple.com/documentation/bundleresources/information_property_list/lsuielement) and #470.
