### ISSUE TITLE
MacOs: Exclusion pattern is ignored

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#542]
**Describe the bug**
As seen in this picture, my exclusion path (Library/Application Support/MobileSync/Backup) is ignored. I am however not sure if this is a bug or my mistake. However, after reading https://borgbackup.readthedocs.io/en/stable/usage/help.html, this relative path should work
<img width="756" alt="Exclude Pattern ignored" src="https://user-images.githubusercontent.com/41552467/86512515-3c0ebe80-be03-11ea-8fa8-18393ab245c8.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by ThomasWaldmann** [comment]
Where **exactly** did you read that they "should work"?

**Comment by m3nu** [comment]
Your source path and all of Vorta's paths are absolute, thus you need absolute exclude patterns, as explained in the docs you linked:

> When you give /absolute/ as root, they will look like /absolute/…/file.ext. 

The patterns in this text field use Borg's `--exclude-from`, thus [fnmatch](https://docs.python.org/3/library/fnmatch.html) is used. So you probably want:

```
*/*.owncloudsync.log
*/*._sync_*.db
~/Documents/_old
```

We do want to improve exclusion handlings and make them easier to understand. See #399 for further discussions.

**Comment by deermo** [comment]
Thank you for your answer. 
> The path/filenames used as input for the pattern matching start from the currently active recursion root. 
This is what made me think that while recursively parsing the folders, it will match. But I understand now that this is not how it works. Anyway, I think it's good to make them easier to understand.
