### ISSUE TITLE
v0.6.26 not working in high sierra

### ISSUE THREAD

**Issue by dantebarba** [borgbase/vorta#543]
**Describe the bug**

Looks like v0.6.26 is not compatible with High Sierra.

**To Reproduce**

Install in High Sierra 10.13.6 (17G65)

**Desktop (please complete the following information):**
 - OS: 10.13.6 (17G65)

**Comment by m3nu** [comment]
You can probably just use the Python version via `pip`. The pre-built binary is probably not compatible.

**Comment by moefuerst** [comment]
@m3nu Is there a specific reason you don't target High Sierra for the pre-built binary? It's quite an annoyance to get it working: 
(cc @dantebarba)

1.) Install with homebrew: `brew cask install borgbackup` then `pip3 install vorta`. 

2.) You could launch vorta from terminal simply with `vorta`, but this means a constantly open terminal window printing vorta's output, plus the python app launcher open in the dock at all times 

3.) Unsatisfying solution: 
- create a new AppleScript App with the Script Editor with this: `do shell script "export LC_ALL=en_US.UTF-8; export LANG=en_US.UTF-8; /usr/local/bin/vorta &> /dev/null &"`. Export as App
- Navigate to your Python launcher app `open /usr/local/opt/python/Frameworks/Python.framework/Versions`, then click on your Version, then Resources
-  Right-click on the Python App > Show Package contents > Contents. 
- Edit the Info.plist, add `<key>LSUIElement</key><string>1</string>`
- Do this every time you upgrade Python, plus the Python app launcher will now never show for anything in the dock

**Comment by m3nu** [comment]
High Sierra is near end of life and I would need to build it in a virtual machine. This wouldn't allow notarization, which is mandatory for newer macOS versions and needs a current version of xcode.

You can just use the `Makefile` to build it yourself. Everything is included in the repo. You just need PyInstaller and Borg. Rough steps:

```
$ make borg  # git clone borg first
$ make dist/Vorta.app  # needs pyinstaller and you may need to remove the notarization script first
```

**Comment by moefuerst** [comment]
Thanks!

I think `$ make dist/Vorta.app` should work, because the notarization part only happens when you `make` the .dmg if I read the `Makefile` correctly no?

— I tried, Borg built fine but I couldn't get Vorta to build (with PyInstaller via homebrew), some weird `$PATH` issues, `package/vorta.spec` couldn't import `src/vorta/_config.py` and `src/vorta/_version.py`, etc. To bad!

**Comment by m3nu** [comment]
> but I couldn't get Vorta to build (with PyInstaller via homebrew), some weird `$PATH` issues, `package/vorta.spec` couldn't import `src/vorta/_config.py` and `src/vorta/_version.py`, etc. To bad!

Try installing it first. Else the import won't work. E.g. `pip install -e .` from the repo root.

**Comment by moefuerst** [comment]
Thanks! Managed now. I didn't want to install from the repo since I already had a pip install of the latest release. Worked by manually setting the `APP_NAME` etc.

**Comment by moefuerst** [comment]
Thanks, updated above

**Comment by ww7** [comment]
Thanks for sharing the building steps.

How suppress auto-update dialog? 
The setting for "no check update" ignored.
What also shows an error about self-signed certificate.
