### ISSUE TITLE
Not backing up the other flatpak configs

### ISSUE THREAD

**Issue by kabaga** [borgbase/vorta#544]
**Describe the bug**
When Vorta runs, it is not backing up the other flatpak configs located in /home/$USER/.var/app/.

**To Reproduce**
1. Start the Vorta backup
2. Once backup is done, check the Archive
3. The only visible is the ~/.var/app/com.borgbase.Vorta/

**Desktop (please complete the following information):**
 - OS: Xubuntu 18.04 and Fedora 32

**Additional context**
n/a

**Comment by Hofer-Julian** [comment]
Yeah, flatpaks cannot access data of other flatpaks...

**Comment by kabaga** [comment]
Is that a normal behavior?
Is there a workaround?

**Comment by Hofer-Julian** [comment]
Yeah, for security reasons.

Still annoying for our use case.

I don't know of any workaround.

But if you want to ask in flatpak's IRC, be my guest 😊
