### ISSUE TITLE
refactor names

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#55]
as seen in #54, some names are too specific - it's not always a `directory or folder`, can be any `fs item`.

e.g.:
- sourceDirectoriesWidget
- sourceDirModel
- choose_folder_dialog
- dir = ...
- ... (?)

**Comment by m3nu** [comment]
> All directories are files, but not all files are directories --[source](https://english.stackexchange.com/questions/150806/what-is-the-noun-for-either-a-file-or-folder)

So calling them all `files` would be correct?

**Comment by m3nu** [comment]
Refactored most objects around the files and folders to be backed up. Including the ORM model. Will do the rest whenever I notice them.
