### ISSUE TITLE
post-backup-command

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#554]
As I want to have a sound, as soon as Vorta has finished its backup, I have added this as post-back-command:
`speaker-test -t wave -W /usr/share/sounds/furVorta -w pluck.wav -r 11025 -l 1`

This works great in a terminal, but not in Vorta. What do I miss?

Thank you.

**Comment by samuel-w** [comment]
Are you running it in flatpak? If so, then Vorta does not have access to /usr/share/sounds, and so cannot access the sound file. A solution would be to move the sound file to your user directory where it is accessible.

**Comment by Golddouble** [comment]
Thank you. Yes I use Flatpak.  
Unfortunately 
`speaker-test -t wave -W /home/user/.SoundsEreignis -w pluck.wav -r 11025 -l 1`
does also not work, but works in a terminal.

**Comment by samuel-w** [comment]
Try running `flatpak override --socket=pulseaudio com.borgbase.Vorta` and restarting Vorta. This should allow access to pulseaudio.

**Comment by Golddouble** [comment]
Thank you.

But it is also not working after this:
```
Golddouble@mx:~
$ sudo flatpak override --socket=pulseaudio com.borgbase.Vorta
[sudo] Passwort für VM-Konto: 
Golddouble@mx:~
```

I have also tried this:
`xfce4-terminal -e speaker-test -t wave -W /home/user/.SoundsEreignis -w pluck.wav -r 11025 -l 1`

It's not working.

**Comment by samuel-w** [comment]
Replace the command with `paplay SOUNDFILE`

**Comment by Golddouble** [comment]
Thank you.
Unfortunately this command also works great in terminal, but not in Vorta Flatpack:
![Vorta no sound](https://user-images.githubusercontent.com/13977359/88284360-8e018080-cced-11ea-89a7-30623a24ccb4.png)

**Comment by samuel-w** [comment]
I really don't know at this point, since flatpak messes up standard permissions so much. 
Try using the pip version of Vorta instead, but you do have to copy the Vorta folder from `$HOME/.var/app/com.borgbase.Vorta/data/` to `$HOME/.local/share/`

**Comment by Golddouble** [comment]
OK. Does this mean the feature post backup command is not usable in flatpack version. That's a pity.

**Comment by samuel-w** [comment]
Basically its useless if you do anything that isn't part of the basic Unix commands, due to the restrictiveness of the sandbox. 
It's annoying because it fails silently, and doesn't seem to leave anything in the logs.

**Comment by Golddouble** [comment]
So are you trying to say "post backup command" would work together with "basic Unix commands" in flatpack version?

I would like to check this.
What would a "basic Unix command" be, I could take to test? Can you give me an example?
Thank you.

**Comment by samuel-w** [comment]
In most cases umount requres root, and playing a sound in flatpak seems to be very hard to do.

**Comment by ktosiek** [comment]
It seems we can run applications in the host environment by using (flatpak-spawn)[https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn]. I've got a sound by using: `flatpak-spawn --host paplay /usr/share/sounds/gnome/default/alerts/drip.ogg`.
Maybe we should wrap commands with `flatpak-spawn --host` when running inside flatpak?

**Comment by Golddouble** [comment]
Thank you. Looks like an impressive discovery!

But how to install flatpak-spawn in a debian based distribution? I have not found it in my package manager.

**Comment by ktosiek** [comment]
It's available inside the flatpak sandbox, but not on the host. You'd have to try using it from Vorta installed with flatpak.

**Comment by Golddouble** [comment]
Wow, that's really amazing!
paplay works this way.

**Comment by Golddouble** [comment]
When I have some time I also will try out 
<umount sdd>

**Comment by Golddouble** [comment]
OK. Here is the result:
`flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/f4e0668f-b6f4-4f51-8dec-067f0ca780f8`

This is working. It unmounts f4e0668f-b6f4-4f51-8dec-067f0ca780f8 .

But this is not working:
`udisksctl unmount -b /dev/disk/by-uuid/f4e0668f-b6f4-4f51-8dec-067f0ca780f8 | udisksctl unmount -b /dev/disk/by-uuid/0ED42CE5D42CD2AE`

This command only unmounts 4e0668f-b6f4-4f51-8dec-067f0ca780f8, but not 0ED42CE5D42CD2AE .

I would like to have all this commands in the "post-backup-command" line:
1. flatpak-spawn --host paplay /usr/share/sounds/gnome/default/alerts/drip.ogg
2. flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/f4e0668f-b6f4-4f51-8dec-067f0ca780f8
3. flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/0ED42CE5D42CD2AE
4. flatpak-spawn --host udisksctl power-off -b /dev/drive

Is this somehow possible?

**Comment by Golddouble** [comment]
Here is the result:
umount works.

For example this command works:
`flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/f9e0668f-b6f9-9f51-8dec-067f0ca780f7 && flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/0CD92CE5D92CD2AE`

It unmounts my external HDD. But I also want to power off my external HDD.

This works fine in a terminal:
`udisksctl unmount -b /dev/disk/by-uuid/f9e0668f-b6f9-9f51-8dec-067f0ca780f7 && udisksctl unmount -b /dev/disk/by-uuid/0CD92CE5D92CD2AE && udisksctl power-off --block-device $(readlink  -e /dev/disk/by-uuid/f9e0668f-b6f9-9f51-8dec-067f0ca780f7| sed 's/[0-9]*$//' )`

So I tried to convert it for using in Vorta. So this was the command I have used in Vorta:
`flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/f9e0668f-b6f9-9f51-8dec-067f0ca780f7 && flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/0CD92CE5D92CD2AE && flatpak-spawn --host udisksctl power-off --block-device $(flatpak-spawn --host readlink  -e /dev/disk/by-uuid/f9e0668f-b6f9-9f51-8dec-067f0ca780f7| flatpak-spawn --host sed 's/[0-9]*$//' )`

Or for better reading:

> flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/f9e0668f-b6f9-9f51-8dec-067f0ca780f7 &&
> flatpak-spawn --host udisksctl unmount -b /dev/disk/by-uuid/0CD92CE5D92CD2AE &&
> flatpak-spawn --host udisksctl power-off --block-device $(
> flatpak-spawn --host readlink  -e /dev/disk/by-uuid/f9e0668f-b6f9-9f51-8dec-067f0ca780f7| 
> flatpak-spawn --host sed 's/[0-9]*$//' )

My expectation was, that this way I also can power off my HDD like it did in terminal. And yes, for a short time it turns the power od the HDD off, but after a few seconds the power is on again and the blue led of my HDD is blinking.

**Comment by ktosiek** [comment]
Can you test your flatpak-spawn command in `flatpak enter com.borgbase.Vorta sh`? It looks like something that should work.
