### ISSUE TITLE
Libraries out of date

### ISSUE THREAD

**Issue by samuel-w** [borgbase/vorta#557]
Basically the title. Out of date libraries lead to bugs in Vorta. In my case, an out of date `python3-paramiko` leads to fewer ssh keys displayed when installed from flatpak vs pip.

I noticed the flatpak install pulls a static version of the libraries. Is there a way for it to always pull the latest version to avoid this in the future?

I believe out of date libraries is also the cause of #555

**Comment by Hofer-Julian** [comment]
> Basically the title. Out of date libraries lead to bugs in Vorta. In my case, an out of date `python3-paramiko` leads to fewer ssh keys displayed when installed from flatpak vs pip.
> 
> I noticed the flatpak install pulls a static version of the libraries. Is there a way for it to always pull the latest version to avoid this in the future?
> 
> I believe out of date libraries is also the cause of #555

I will update paramiko.

There are currently scripts in the working which should make it easier to automate that in the future.
