### ISSUE TITLE
profile settings

### ISSUE THREAD

**Issue by lawmanuk** [borgbase/vorta#558]
When I change profiles the source/exclusions don't change with the profile.

This makes a profile almost pointless?

Can the source/exclusions change when we change profiles please?

thanks

**Comment by lawmanuk** [comment]
don't understand what you mean by not-reproducible?    When you change profiles, do your sources/exclusions update too?

**Comment by samuel-w** [comment]
Yes. Sources and exclusions are stored per profile. Can you post your OS, how you installed Vorta, and Vorta version please?

**Comment by lawmanuk** [comment]
Hi

I was using it wrong.

That's working now.

Still can't use vorta for system backups as root.

Or even to open repositories made by Borg commandline as root.

Thanks
