### ISSUE TITLE
system backup

### ISSUE THREAD

**Issue by lawmanuk** [borgbase/vorta#559]
when I try to create a system backup of root /, vorta gives errors as its not running borg as sudo root.

I've tried running sudo vorta, but that doesn't help either.

In the end I have to run sudo borg and not use vorta at all.

Can you please allow vorta to run borg in sudo root mode when required, so we can do system backup/restore.

many thanks

**Comment by Hofer-Julian** [comment]
Thanks for opening this issue.

The topic was already discussed in multiple issues, e.g. https://github.com/borgbase/vorta/issues/422

**Comment by lawmanuk** [comment]
Hi Hofer,

I can see you've rejected the request on grounds that vorta is not a server
app, and built for desktops.

The problem is that desktop users would like to be able to backup their own
system in case of failure, just like timeshift does.

Vorta with root would assist, so unsure why this is not allowed when likely
a relatively simple permission update.

Thanks

**Comment by m3nu** [comment]
He closed it because your request is duplicate. Please use the search function to find similar requests first and don't open duplicates. For this case see #240
