### ISSUE TITLE
Workaround for macOS Big Sur Public Beta 1

### ISSUE THREAD

**Issue by nboelter** [borgbase/vorta#574]
This is not a bug report since macOS Big Sur is in beta and this is probably not a bug in Vorta.

The release version of Vorta from vorta-0.6.26.dmg does not work for me on macOS Big Sur Public Beta 1, it sits at 100% CPU permanently without showing a window. Sampling shows that most of the time is spent in Core Animation. 

The workaound i am using is to use the setup.py to install vorta to /usr/local/bin/vorta, which works fine.

```
brew install python@3.8 qt
brew cask install borgbackup
pip3 install PyQt5 PyQt5-sip
python3.8 setup.py build
python3.8 setup.py install
/usr/local/bin/vorta
```

PS:
I also tried to build my own Vorta.app, which also sits at 100% without doing anything. The steps involved were:
- Add /usr/local/opt/qt/bin to PATH
- Copy Vorta.app/Contents/Resources/borg-dir from the release version to ../borg/dist/
- Replace “excludes=[]” with “excludes=['tkinter']” in package/vorta.spec because pyinstaller cannot find the Tcl framework on Big Sur
-  Create an empty /usr/local/lib/python3.8/site-packages/PyQt5-5.15.0-py3.8-macosx-10.15-x86_64.egg/EGG-INFO/top_level.txt because pyinstaller expects a top_level.txt
- Copy a build of Sparkle.framework to bin/darwin
- Run make dist/Vorta.app
- cp /usr/local/lib/python3.8/site-packages/PyQt5_sip-12.8.0-py3.8-macosx-10.15-x86_64.egg/PyQt5/sip.cpython-38-darwin.so dist/Vorta.app/Contents/MacOS/PyQt5/ because of “WARNING: Hidden import "PyQt5.sip" not found”

**Comment by m3nu** [comment]
Thanks for the report. Maybe Qt will need an update too. I'll make sure there is a working release, once I've installed Big Sur.

**Comment by kremalicious** [comment]
No workaround needed anymore, Vorta v0.7.1 runs just fine on Big Sur beta 6

**Comment by m3nu** [comment]
Happy to hear that. Thanks a lot for testing and providing feedback! 👌
