### ISSUE TITLE
palette change not detected in PyInstaller build

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#575]
**Describe the bug**
When macOS is used in "Dark Mode", the icon is barely visible as it stays black. Other icons turn white when "Dark Mode" activates.

<img width="189" alt="grafik" src="https://user-images.githubusercontent.com/41552467/90055322-74949880-dcdd-11ea-9ff3-8ee12c558430.png">

<img width="189" alt="grafik" src="https://user-images.githubusercontent.com/41552467/90055238-56c73380-dcdd-11ea-9967-ac98e2943c39.png">

**To Reproduce**
1. Turn macOS into dark mode
2. Start Vorta (from BIN or python build)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6

**Additional context**

**Comment by m3nu** [comment]
I can't reproduce your issue when running from Python directly, but from the binary. The theme change event from Qt doesn't fire and dark mode isn't detected at all.

**Comment by m3nu** [comment]
I was able to fix this issue by following some steps outlined [here](https://github.com/gridsync/gridsync/issues/267#issuecomment-609980411). The fix requires adding a macOS plist setting and recompiling the PyInstaller bootloader and (possibly) Python interpreter. I'm documenting the steps here. Not sure whether they should be added to the docs.

1. Compile Python (and virtualenv): `export MACOSX_DEPLOYMENT_TARGET=10.13 PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install 3.8.5`
2. Install Vorta in edit mode as usual `pip install -e .`
3. Install Pyinstaller
```
git clone https://github.com/pyinstaller/pyinstaller.git build/pyinstaller
cd build/pyinstaller/bootloader
git checkout develop
export MACOSX_DEPLOYMENT_TARGET=10.13
export CFLAGS=-mmacosx-version-min=10.13
export CPPFLAGS=-mmacosx-version-min=10.13
export LDFLAGS=-mmacosx-version-min=10.13
export LINKFLAGS=-mmacosx-version-min=10.13
python ./waf all
cd ..
pip install .
```
4. Set `NSRequiresAquaSystemAppearance` to `False` for macOS app bundle.

**Comment by m3nu** [comment]
Test build for you, @deermo . NOT signed or notarized. https://files.qmax.us/vorta/Vorta-575.zip

**Comment by deermo** [comment]
Wow, incredible fast bug fix, @m3nu! The issue is resolved in the build you provided. Thank you!
