### ISSUE TITLE
dev/sdb mount not possible

### ISSUE THREAD

**Issue by JPEckmann** [borgbase/vorta#576]
flatpak version of vorta on ubuntu (mate) 20.04
I have a backup archive which is on an external disk /dev/sdb1 and which contains the backup of my hard disk (parts of) 

I start vorta 
click  "select backup destination"
  "add existing repository"

a) The "folder symbol" in the "connect to existing repository" is inactive (and clicking it blocks vorta
b) if I type /media/eckmann/borgbackup19
(which is the correct f
filename, since borg alone works well)
I get the answer 
"please enter a valid repo URL or select a valid local path"

if, instead I do file://...
vorta.borg.borg_thread - ERROR - Connection closed by remote host. Is borg working on the server?

but /dev/sdb1 is just a passive hard disk

Did I miss instructions?

it cannot mount since

**Comment by Hofer-Julian** [comment]
/dev is blacklisted by flatpak https://docs.flatpak.org/en/latest/sandbox-permissions.html

Please mount your harddrive to something different e. g. /mnt or /run/media

**Comment by JPEckmann** [comment]
But it is mounted as /media/eckmann

is this wrong?

what is the logical difference between /mnt and /media ?
(both are directories under /) 

????




On Wed, 12 Aug 2020, Hofer Julian wrote:

->/dev is blacklisted by flatpak https://docs.flatpak.org/en/latest/sandbox-permissions.html
->
->Please mount your harddrive to something different e. g. /mnt or /run/media
->
->-- 
->You are receiving this because you authored the thread.
->Reply to this email directly or view it on GitHub:
->https://github.com/borgbase/vorta/issues/576#issuecomment-673083129
->

**Comment by Hofer-Julian** [comment]
I've edited my answer, but you only see it if you go to the web interface.

Is this the only repo that makes problems?

When you say clicking on the button "stops" vorta. Do you mean it freezes? Crashes?

**Comment by JPEckmann** [comment]
It freezes



On Wed, 12 Aug 2020, Hofer Julian wrote:

->I've edited my answer, but you only see it if you go to the web interface.
->
->Is this the only repo that makes problems?
->
->When you say clicking on the button "stops" vorta. Do you mean it freezes? Crashes? 
->
->-- 
->You are receiving this because you authored the thread.
->Reply to this email directly or view it on GitHub:
->https://github.com/borgbase/vorta/issues/576#issuecomment-673085968
->

**Comment by JPEckmann** [comment]
On Wed, 12 Aug 2020, Hofer Julian wrote:

->I've edited my answer, but you only see it if you go to the web interface.
Ilooked at it ???

I dont understand what I am supposed to do 

flatpak run com.borgbase.Vorta  --filesystem=host    ?

**Comment by Hofer-Julian** [comment]
Did you try other existing repositories as well?

**Comment by JPEckmann** [comment]
they are all on the same external drive

On Wed, 12 Aug 2020, Hofer Julian 
wrote:

->Did you try other existing repositories as well? 
->
->-- 
->You are receiving this because you authored the thread.
->Reply to this email directly or view it on GitHub:
->https://github.com/borgbase/vorta/issues/576#issuecomment-673096922
->

**Comment by JPEckmann** [comment]
manually mounted the external disk on /mmm

no better

**Comment by Hofer-Julian** [comment]
Please create a new repo on your homedrive and test if it works there

**Comment by JPEckmann** [comment]
Not really, please advise

flatpak --filesystem=host run com.borgbase.Vorta

and I triy to create a new archive as /home/eckmann/vortatest

no success, clicking the "folder symbol" still freezes vorta




On Wed, 12 Aug 2020, Hofer Julian wrote:

->Please create a new repo on your homedrive and test if it works there
->
->-- 
->You are receiving this because you authored the thread.
->Reply to this email directly or view it on GitHub:
->https://github.com/borgbase/vorta/issues/576#issuecomment-673104956
->

**Comment by Hofer-Julian** [comment]
I see.

Have you tried to install Vorta with pip?

**Comment by JPEckmann** [comment]
Yes, that didnt work well. 

it starts and when it wants to find my repositories, it does nothing

BTW: On ubuntu 18.04 vorta worked (pip version)

ppip: NOW

2020-08-12 23:02:19,064 - apscheduler.scheduler - INFO - Scheduler started
2020-08-12 23:02:19,089 - vorta.borg.borg_thread - INFO - Running command 
/usr/bin/borg --version

then stuck

I'm going to bed. If you are in Europe, we can continue tomorrow . let me 
know.

Wir koennen auch direkt kommunizieren, ich kann Sie anrufen wenn Sie Zeit 
haben

Prof. Jean-Pierre Eckmann, 
Departement de Physique Theorique
and
Section de Mathematiques
32, Bld D'Yvoy, Universite de Geneve
1211 Geneva 4 Switzerland
Phone (41)(22)3796360
http://fiteoweb.unige.ch/~eckmannj/





On Wed, 12 Aug 2020, Hofer Julian wrote:

->I see.
->
->Have you tried to install Vorta with pip? 
->
->-- 
->You are receiving this because you authored the thread.
->Reply to this email directly or view it on GitHub:
->https://github.com/borgbase/vorta/issues/576#issuecomment-673107841
->

**Comment by Hofer-Julian** [comment]
Good idea.

Closing this issue for now.

**Comment by JPEckmann** [comment]
JP

**Comment by JPEckmann** [comment]
die perl version laeuft nun (weiss nicht warum)

mein archives habe KEIN passwort .
koennen Sie eine option einrichten damit ich sie trotzdem anschauen kann?

Danke

**Comment by Hofer-Julian** [comment]
Ich weiß nicht welche perl version sie meinen.
Aber besprechen wir das besser über email.
Sie sollten eine von mir empfangem haben

**Comment by JPEckmann** [comment]
Koennen Sie mir noch einmal Ihre email senden, die ich zwischen uns zwei 
benuetzen soll?

JPE

PS: Die oython version habe ich zum laufen gebracht





On Sat, 15 Aug 2020, Hofer Julian wrote:

->Ich weiß nicht welche perl version sie meinen.
->
->Aber besprechen wir das besser über email.
->
->Sie sollten eine von mir empfangem haben
->
->
->
->-- 
->
->You are receiving this because you authored the thread.
->
->Reply to this email directly or view it on GitHub:
->
->https://github.com/borgbase/vorta/issues/576#issuecomment-674406115

**Comment by Hofer-Julian** [comment]
Ok

-------- Original-Nachricht --------
