### ISSUE TITLE
Implement a "copy repository URL to clipboard" button

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#579]
**Is your feature request related to a problem? Please describe.**
Some tasks cannot be performed in Vorta, or Vorta currently crashes when doing so (i.e. #386). So these tasks have to be performed using borg CLI.

**Describe the solution you'd like**
Borg CLI requires the repository URL. Although I have these in my password manager, the workflow could be very easy when there'd be a possibility so quickly copy the respository URL to the clipboard using the Vorta GUI. I.e., a button next to the "Unlink repository" could be used for this. 

**Edit:**
I just saw this button in the bin @m3nu provided in #575... So it was implemented in #517. Sorry, did not check the closed issues / pull requests.

**Comment by m3nu** [comment]
Should be implemented already. I have the button in latest master.

The test build I gave you before should have it too.

**Comment by deermo** [comment]
Jup, sorry, see my edit. Felt a little unreal ;) Just saw this a few minutes after opening this issue when playing around with the different versions.
