### ISSUE TITLE
Reorder GUI to seperate "per profile settings/tasks" and "global settings/tasks"

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#580]
**Is your feature request related to a problem? Please describe.**
Currently, the GUI mixes elements of per profile settings (i.e. the tabs "Repository", "Sources", ...) and global settings / tasks (i.e. "Misc" tab and the "Start backup" / progress bar area). 

**Describe the solution you'd like**
Rearranging the GUI so that there are two horizontally seperated areas. The upper one could include to profile switch  and the 4 tabs ("Repository", "Sources", ...). The lower one could also have two tabs, with the first beeing "Current task" (maybe indicating which profile is running, #578), and the second beeing the current "Misc" tab (i.e. namend "Global options")? 

**Describe alternatives you've considered**
Renaming "Misc" to "Global options" could also help.

**Comment by samuel-w** [comment]
Changing "Misc" to "Global Settings" would be a more accurate name for it.
