### ISSUE TITLE
Support borg's "auto" compression mode

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#587]
**Is your feature request related to a problem? Please describe.**
Borg supports an additional [auto mode for compression](https://manpages.debian.org/testing/borgbackup/borg-compression.1.en.html), which means adding an "auto," before the compression mode in the CLI. I like this mode as I backup i.e. videos and photos, too, which will likely not be compressed when using the auto mode (although I never checked this behaviour). Currently, in Vorta, the compression mode has to be chosen and the auto mode is not available. 

**Describe the solution you'd like**
Add a check box to support the auto mode. When  checked, add "auto," to the -C argument.
Unchecked: `-C zstd,8`
Checked: `-C auto,zstd,8`

**Describe alternatives you've considered**
Not supporting auto mode. 
Or, supporting an override for command line options, which might be even more work?

**Comment by m3nu** [comment]
Already have. Including an explanation on why those options were chosen.

https://github.com/borgbase/vorta/blob/master/src/vorta/views/repo_tab.py#L33
