### ISSUE TITLE
"Backup running" indicators in the tray icon (red dots) lost when switching between light/dark mode

### ISSUE THREAD

**Issue by deermo** [borgbase/vorta#588]
**Describe the bug**
During a running backup, the tray icon has red dots signalling that a backup is ongoing. When my mac switches between dark/light mode, these red dots are lost and the Vorta symbol is displayed without them.

**To Reproduce**
1. Start backup
2. Manually switch between light/dark mode

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6

**Comment by m3nu** [comment]
I've seen it. Let's call this low priority.

**Comment by samuel-w** [comment]
Since we do not have different icons for light/dark mode as of https://github.com/borgbase/vorta/commit/4eafad547240920aee3e0e8d9ce72b06b014b81e, should this be closed?

**Comment by m3nu** [comment]
Good idea. Resolved itself. 😀
