### ISSUE TITLE
Vorta diff functionality returns UnboundLocalError

### ISSUE THREAD

**Issue by nicopace** [borgbase/vorta#589]
**Describe the bug**

The diff screen never appears.

**To Reproduce**
1. Go to 'Archives'
2. Click on 'Diff'
3. Select two archives
4. Nothing happens. If you check the output on the command-line, this appears:
```
2020-08-17 16:22:33,273 - vorta.borg.borg_thread - INFO - Running command /usr/bin/borg diff --debug --info --log-json xxx@mybackup.host:~/backup::default-2020-08-15T20:35:25 default-2020-08-16T16:39:23
Traceback (most recent call last):
  File "./.local/lib/python3.8/site-packages/vorta/views/archive_tab.py", line 460, in list_diff_result
    window = DiffResult(result['data'], archive_newer, archive_older)
  File "./.local/lib/python3.8/site-packages/vorta/views/diff_result.py", line 72, in __init__
    files_with_attributes.append(parse_line(line))
  File "./.local/lib/python3.8/site-packages/vorta/views/diff_result.py", line 60, in parse_line
    full_path = line[full_path_index:]
UnboundLocalError: local variable 'full_path_index' referenced before assignment
```

**Desktop (please complete the following information):**
 - OS: Linux Mint

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

Vorta Version: 0.6.26
Local Borg Version: 1.1.11

**Comment by Hofer-Julian** [comment]
This should be fixed.
Unfortunately it is been a while since the latest release.

Could you please try the dev version?

**Comment by nicopace** [comment]
> This should be fixed.
> Unfortunately it is been a while since the latest release.
> 
> Could you please try the dev version?

I can, how can I do it?

**Comment by Hofer-Julian** [comment]
https://vorta.borgbase.com/contributing/

**Comment by m3nu** [comment]
> Unfortunately it is been a while since the latest release.

I'm working on macOS packaging for Borg currently. We also have a few larger open PRs. Once that's all merged, we'll have a new release. Thanks for the patience. 🙏

**Comment by Hofer-Julian** [comment]
Great 😊

**Comment by nicopace** [comment]
> This should be fixed.
> Unfortunately it is been a while since the latest release.
> 
> Could you please try the dev version?

I tried.
It is fixed.

thanks,
