### ISSUE TITLE
Website: Use another AUR helper under Installation/Linux - yaourt is deprecated

### ISSUE THREAD

**Issue by daPhipz** [borgbase/vorta#591]
The [installation instructions for Vorta on Linux](https://vorta.borgbase.com/download/linux/) suggest to use `yaourt` as AUR helper.
However, this program is not maintained anymore and therefore not recommended to use.
I suggest to change the website as follows:

`$ yay -S vorta`

**Comment by m3nu** [comment]
Thanks. Added to the docs repo.

**Comment by m3nu** [comment]
https://github.com/borgbase/vorta.borgbase.com/commit/44ad2b01e5b6e82f52e4f5f78f2eeefff423b268
