### ISSUE TITLE
Improve Backup source management

### ISSUE THREAD

**Issue by XXXBold** [borgbase/vorta#593]
**Is your feature request related to a problem? Please describe.**
Implementing this will improve usability when modifying the backup source files/directories.

**Describe the solution you'd like**
I've got some ideas, which will improve the handling of the backup source list. If you want these issues splitted, let me know.

- [x] **1. Allow selection of multiple files/folders on the file browser.**
For now, when multiple files/folders within the same folder are desired for backup, they have to be added each one-by-one, which is very inefficient and annoying for multiple items, because you have to browse to this folder again and again, for each item.

Implementation suggestion:
I think there's a flag for the file browser function to allow multiple item selection. Add an entry for each selected.

- [x] **2. Allow selection of multiple items withon the sources list**
This is easier if one wants to delete multiple entries at once.

Implementation suggestion:
Shouldn't be difficult to implement I think.

- [x] **3. Add an option to sort the entries within the sources list**
Since each new entry is added to the end of the list, it can become confusing. I'd suggest that there should be at least an option to sort the entries in alphabetical order if desired.
In general, I'd appreciate if there'd be some kind of separation between files and folders.

Implementation suggestion:
Add an additional button to sort the entries. Maybe buttons for moving an entry up/down within the list will also be useful?

- [x] **4. Show occupied space of entries + size of all files**
It would be nice if the size on disk of each entry would be shown aswell. Additional, the size of all entries could be shown somewhere aswell.
This would be very convenient to the enduser, because for now one can only guess how big the backup will be (excluding compression), without running it.

Implementation suggestion:
Replace listcontrol with e.g. tablecontrol (Maybe there's a better control in QT, IDK).
Create two columns (This could also be useful for filtering I guess):
[Path][Size]
When doing this way, it's easy to add other columns aswell if required.

The sum of all entries' size could be shown below the list.

**Describe alternatives you've considered**
1.: There's no alternative to do this faster afaik.
2.: Delete one by one
3.: Not possible right now
4.: N/A

**Comment by samuel-w** [comment]
For number 4, it wouldn't be that useful after the first backup because of de-duplication.

**Comment by m3nu** [comment]
> Edit: For 3, it would be better to automatically sort the entries, to reduce the number of buttons.

Yes, can be sorted automatically. No button for this.

![wgetgui](https://user-images.githubusercontent.com/3916435/91652406-aa9d8f00-eac9-11ea-82e0-19e731bf3a06.png)

Merged #600 by @samuel-w to address item 1. Item 2 is already resolved. Was merged a week ago or so. (not released yet.)

**Comment by m3nu** [comment]
1 to 3 are now merged. Thanks to @samuel-w and @XXXBold for implementing.

For 4 you are suggesting to calculate the size of each source folder? Possible, but a headache, since it a) may take quite long for network drives or many files, b) will change over time.

**Comment by XXXBold** [comment]
Some thoughts on my side, about number 4, and some in general.

**General**
- First, I'd suggest to change the QListWidget used for the source paths to a QTableWidget, as it is used for the archives list.
This has the following advantages:
- Multiple information shown to each entry in different columns, not just a plain path. For example:
  - Size of the file/folder (as suggested nr 4)
  - Type: Directory or single file (Maybe additional N/A type if the path is (no longer) available?)
 - User can desire how to sort the entries much better (By pathname, by size, by type...) by clicking the column.
 - If there's more information required, just add a new column to the table.

**According to number 4:**
1) Calculate the size of each file/folder when it's added to the list. Maybe use a different thread to not block the UI, and show a "caluclating..." label or similar as long as in progress. Use the class QFileInfo size member, so the calculation itself is easy: https://doc.qt.io/qt-5/qfileinfo.html.
2) Calculate the size of each entry when vorta starts, also use a different (or multiple?) threads to not block the UI.

For the changes over time: Add a button to manually update the list, so it's up to the user. I won't do this on interval, this will cause problems, e.g. prevent disks from sleep etc. More advanced, maybe there are hooks available to observe a path and on the fly make individual updates on change, but this is probably too complicated for now, at least I'm not familiar with this.

I'm already working on parts of that, most important question is: Are you okay with changing the sourceFilesWidget to a QTableWidget? This is imo the first step to be done.

**Comment by samuel-w** [comment]
For number 4, it wouldn't be that useful outside of the first backup, since only the diff would be stored.

**Comment by XXXBold** [comment]
> For number 4, it wouldn't be that useful outside of the first backup, since only the diff would be stored. Would lead to confusion on subsequent backups.


I disagree with that: It's always a useful information to see the current datasize of the source, regardless if there are already backups present.
It's also possible the user adds new sources, while there are already backups made.

I can't see why this is confusing, it won't display the size of the files in the backup, just it's actual size on the source path.

**Comment by m3nu** [comment]
Final PR merged. So closing this issue. Thanks to everyone who contributed!
