### ISSUE TITLE
Unable to add your repository

### ISSUE THREAD

**Issue by reeloop** [borgbase/vorta#598]
Hi,

I´m on Arch-Linux and I´m not able to add a remote repository in Vorta. 

I´ll use a ssh connection to an Alpine-Linux. 
SSH is configured and borg is working fine with console, I can use:
`borg init -e repokey-blake2 user@192.xxx.xxxxxx:/mnt/data/user/borg  `       
`borg create user@192.xxx.xxx.xxx:/mnt/data/user/Borg_backup::test ~/Downloads`
`borg list user@192.xxx.xxx.xxx:/mnt/data/user/borg`
and
`borg extract user@192.xxx.xxx.xxx:/mnt/data/user/borg::test`

So everything works. But if I try to use the repository or add a new one with Vorta I get the error:
'Unable to add your repository'

**This is my Vorta.log:**
`vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
 asyncio - DEBUG - Using selector: EpollSelector
root - DEBUG - Found 0 passwords matching repo URL.
vorta.borg.borg_thread - DEBUG - Password not found in primary keyring. Falling back to VortaDBKeyring.
vorta.borg.borg_thread - INFO - Running command /usr/bin/borg init --info --log-json --encryption=repokey-blake2 user@192.xxx.xxx.xxx:/mnt/data/user/borg
vorta.borg.borg_thread - WARNING - Remote: ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
vorta.borg.borg_thread - WARNING - Remote: ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
vorta.borg.borg_thread - WARNING - Remote: Permission denied, please try again.
vorta.borg.borg_thread - WARNING - Remote: ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
vorta.borg.borg_thread - WARNING - Remote: Permission denied, please try again.
vorta.borg.borg_thread - WARNING - Remote: ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory
vorta.borg.borg_thread - WARNING - Remote: user@192.xxx.xxx.xxx: Permission denied (publickey,password,keyboard-interactive).
vorta.borg.borg_thread - ERROR - Connection closed by remote host. Is borg working on the server?`

Vorta Version: 0.6.26
Borg Version: 1.1.13

**Comment by m3nu** [comment]
Probably the `askpass` stuff in your logs? That seems unusual.

**Comment by reeloop** [comment]
Hi,

yes, that´s maybe a problem, but I don´t know what to do with askpass...

I just realized, I also get a warning when I init the repository:
`Remote: Using a pure-python msgpack! This will result in lower performance.`

Maybe that´s the problem?

**Comment by ThomasWaldmann** [comment]
Yes, the pure python msgpack warning points to a problem with the compiled msgpack (either it was not compiled at all or the resulting binary does not work - the latter can happen if you use the fat binary on linux that has an incompatible glibc).

**Comment by reeloop** [comment]
Hi,

okay, I´ve installed a fresh debian with borgbackup. I am able to to init a new repository without the pure-python warning.

I´ve turned off my firewall, and create a new user + ssh-keys + directory for backup-repository, I´am able to connect, init, backup, restore with the borg-commands without any problems or warnings.

But if I try to add this directory to Vorta (or init a new one with Vorta) I get the sameError:
`Remote: ssh_askpass: exec(/usr/lib/ssh/ssh-askpass): No such file or directory`

**Comment by samuel-w** [comment]
Install the `ssh-askpass` pacakge

**Comment by reeloop** [comment]
Hi, thanks. After a complete new ssh-key and reinstallation of vorat it worked. So, that´s not a problem anymore.
