### ISSUE TITLE
Support --keep-within prune option

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#6]
- [x] Clear log. Either manually or after some time.
- [x] Cannot refresh/remove WiFi networks under Schedule > Network, even if these are subsequently removed from Network settings on Mac OS and/or Keychain.
- [x] Update wifi last-connected times.

**Comment by ThomasWaldmann** [comment]
@m3nu keep-within could be just 1 more text line below the already present one, like:

```
Keep 5 hourly, 4 daily, 3 weekly, 2 monthly, 1 annual archives. (How?)
No matter what, keep all archives within the last [ 3h ].
```

**Comment by JanSchnacki** [comment]
That actually sounds very good.
