### ISSUE TITLE
missing vspace / separation

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#60]
![screenshot from 2018-11-26 09-44-36](https://user-images.githubusercontent.com/356103/49002531-241f8500-f160-11e8-91d1-06e7f0ef3327.png)

there should be a bit more space separating the table, the prune options and the buttons.

**Comment by m3nu** [comment]
Added some space to separate buttons. Prune options are related to the table in some way, so they can stay near it I'd say.

<img width="788" alt="screenshot 2018-11-27 at 10 36 46" src="https://user-images.githubusercontent.com/3916435/49054805-7334eb00-f230-11e8-88af-3b120b31a024.png">

**Comment by m3nu** [comment]
Changes were merged in #61
