### ISSUE TITLE
extract does not work as expected

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#608]
I have about 60 "incremental" backups of my home.
In this home also 
`/home/D-Konto/.local/share/wineprefixes/My_own_wine_folder/`
is included.

So today I wanted to restore the folder
`/home/D-Konto/.local/share/wineprefixes/My_own_wine_folder/`
only.

How did I do this:
I rename my old folder "/home/D-Konto/.local/share/wineprefixes/My_own_wine_folder/" into "/home/D-Konto/.local/share/wineprefixes/My_own_wine_folder.defect/"
In archive tab I marked the snapshot from 2020-08-31.
I pressed extract.
I searched an selected
`/home/D-Konto/.local/share/wineprefixes/My_own_wine_folder/`
I do not unselect anything inside this folder.
I press extract.
I choose "root" (German "Rechner" (calculator)).
I press open.

My expectation was, that I will now have a new folder 
`/home/D-Konto/.local/share/wineprefixes/My_own_wine_folder/`
and that this folder has also the folder 
`/home/D-Konto/.local/share/wineprefixes/My_own_wine_folder/drive_c/Program Files/`

But the folder 
`/home/D-Konto/.local/share/wineprefixes/My_own_wine_folder/drive_c/Program Files/`
is not included. It is missing. And some other folders too, although they exist, when I browse through the archiv in "extract-mode".

????????

Thank you.

Edit:
I did it a second time. Now it worked as expected.

**Comment by m3nu** [comment]
> I did it a second time. Now it worked as expected.

Good to hear it worked. Keep in mind that Borg extracts the full folder prefix by default. Maybe this bit you? Can be tricky with hidden files.

Hidden files will be included in the backup unless explicitly excluded with patterns.

**Comment by Golddouble** [comment]
Meybe I had this issue, because I have started Fsearch at the same time as Vorta was running?
Fsearch is for searching files and folders. When we start Fsearch it makes the file-name-index new (update index database).

Maybe that's what sparked it. So that Vorta was not working reliably?

**Comment by m3nu** [comment]
I doubt reading some files would interfere with extracting. But who knows..
