### ISSUE TITLE
Vorta 0.7.0 is using German although device is set to English

### ISSUE THREAD

**Issue by philipkozeny** [borgbase/vorta#623]
**Describe the bug**
I have updated Vorta to the latest 0.7 release. My Mac is set to English as the primary language (see menu bar). German is setup as a secondary language. Vorta shows everything in German though, this did not happen with the release before 0.7.

**To Reproduce**

![Screenshot 2020-09-07 at 13 12 24](https://user-images.githubusercontent.com/16721635/92381803-cfb68100-f10b-11ea-88cb-54d83ad9141e.png)

**Desktop (please complete the following information):**
- OS: macOS 10.15.6
- Vorta version: 0.7.0
- Borg version: 1.1.13

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by m3nu** [comment]
Can't reproduce this. Which locales are loaded as per your logs? (*Misc > Log*)

`2020-09-07 20:22:05,681 - vorta.i18n - DEBUG - Loading translation succeeded for ['en-US', 'de-US'].`

![Screen Shot 2020-09-07 at 20 22 24](https://user-images.githubusercontent.com/3916435/92387538-4e311400-f148-11ea-9e53-2f6e9f37c889.jpg)

**Comment by philipkozeny** [comment]
`2020-09-06 15:40:44,610 - vorta.i18n - DEBUG - Loading translation succeeded for ['en-AT', 'de-AT'].`

![Screenshot 2020-09-07 at 15 33 22](https://user-images.githubusercontent.com/16721635/92393092-9b4cc000-f11f-11ea-847c-7fd9f11e759a.png)

**Comment by m3nu** [comment]
I see. You are using "Austrian Englisch", while our source language is US English. So it falls back to German in weird ways. See [here](https://doc.qt.io/qt-5/qtranslator.html#load-1).

I've renamed our source language to just `en` from `en-US`. For me this fixes the issue, even with `en-AT`.

**Comment by Hofer-Julian** [comment]
TIL that Austrian English is a thing

**Comment by philipkozeny** [comment]
Ah ok - thanks! I guess it's "Austrian English" because of the region setting 😅

**Comment by notDavid** [comment]
Does this fix other languages also? My macOS keyboard/Input source is Dutch, and my system language is English. Vorta 0.7.1 gives me a German UI...

**Comment by m3nu** [comment]
Logs please. German isn't hardcoded anywhere. Might be somewhere in your locales.
