### ISSUE TITLE
installation without internet (ubuntu 18.04)

### ISSUE THREAD

**Issue by masterbalby2** [borgbase/vorta#630]
Hello to all,
I want to use vorta on an ubuntu 18.04 to manage my different BORG backup servers.
Unfortunately I'm on a closed network that doesn't have access to the internet.
I've been trying for several days to find a solution to install vorta (deb...) or to compile it from source but I can't manage it.
Is there a method or is there someone who can help me?
Thank you in advance for your help

**Comment by m3nu** [comment]
Vorta doesn't need internet to install, if you e.g. clone the repo or get the source archive from PyPi.

You still need to install all dependencies though. That should be possible with the same approach (downloading dependencies from PyPi). It's not a Vorta-specific problem though. See here for example https://stackoverflow.com/questions/11091623/how-to-install-packages-offline

**Comment by masterbalby2** [comment]
thank you very much.
I'm trying now
