### ISSUE TITLE
Panel icon is dark on Vorta ver. 0.7.0

### ISSUE THREAD

**Issue by Maula-Jatt** [borgbase/vorta#637]
**Describe the bug**
After upgraded (flatpak) to latest version 0.7.0 the tray icon turned dark. I am on Manjaro XFCE stable.

**To Reproduce**
1. Upgrade to version 0.7.0 on flatpak
2. Reboot computer
3. Try icon is dark in colour which is diffucult to identifty on an already dark theme on Xfce.

**Desktop (please complete the following information):**
- OS: Manjaro Xfce (stable)
- Vorta version: 0.7.0
- Borg version: 1.1.13

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by samuel-w** [comment]
This is fixed by #622, they look like this now:
![darj](https://user-images.githubusercontent.com/67625312/92353421-e75b1e80-f0a5-11ea-964b-2d59ee5f6ee7.png)
![darj2](https://user-images.githubusercontent.com/67625312/92353422-e7f3b500-f0a5-11ea-9423-213091eb1bf8.png)

**Comment by Maula-Jatt** [comment]
Faced "Crash on opening GUI #629"
Waiting for permanent fix for flatpak.

**Comment by samuel-w** [comment]
For now, downgrade with
`flatpak update --commit=f25a21a8edab50f84797949bfd0bb9d87e21cb3fcc74536cb83e50469bceb0fa com.borgbase.Vorta`

**Comment by Maula-Jatt** [comment]
I am now back on previous version. Do I close this issue?
