### ISSUE TITLE
Language based on keyboard layout, not display language

### ISSUE THREAD

**Issue by mischaelschill** [borgbase/vorta#639]
**Describe the bug**
Vorta uses the keyboard layout to determine the language to show, not the display language.

**To Reproduce**
1. Select Swiss-German keyboard layout
2. Open Vorta -> Language is German
3. Select US-English keyboard layout
4. Open Vorta -> Language is English

**Desktop (please complete the following information):**
- OS: MacOS Catalina
- Vorta version: 0.7.0
- Borg version: 1.1.13

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
Was not an issue in 0.6.x

**Comment by mischaelschill** [comment]
I was able to reproduce the bug once, now Vorta is stuck in the wrong language no matter what I do.

**Comment by m3nu** [comment]
Probably duplicate of #623. Please try RC3 from https://github.com/borgbase/vorta/issues/629#issuecomment-689230173
