### ISSUE TITLE
Installing pip package version wrong

### ISSUE THREAD

**Issue by samuel-w** [borgbase/vorta#643]
**Describe the bug**
When installing 0.7.1, the package version listed is wrong. Aesthetic bug only, since 0.7.1 appears on the misc tab.

**To Reproduce**
1. Uninstall Vorta
2. Install Vorta 0.7.1
`pip install vorta==0.7.1`

**Desktop (please complete the following information):**
- OS: Ubuntu 20.04
- Vorta version: 0.7.1
- Borg version: 1.1.13

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
Console output:
```
Installing collected packages: vorta
Successfully installed vorta-0.7.0
```

**Comment by m3nu** [comment]
Doesn't happen for me in a fresh venv.

```
$ pyenv virtualenv 3.8.5 vorta-tmp
$ pip install -U vorta
...
Successfully installed PyQt5-sip-12.8.1 apscheduler-3.6.3 peewee-3.13.3 psutil-5.7.2 pyobjc-core-6.2.2 pyobjc-framework-Cocoa-6.2.2 pyobjc-framework-CoreServices-6.2.2 pyobjc-framework-FSEvents-6.2.2 pyobjc-framework-LaunchServices-6.2.2 pyqt5-5.15.0 tzlocal-2.1 vorta-0.7.1
```

**Comment by samuel-w** [comment]
Happens to me in a fresh venv. Might be a Linux thing, but it doesnt happen with older versions.
(venv) [user@PC-PC tmp]$ pip install vorta

> Processing /home/user/.cache/pip/wheels/02/cb/bf/b7651efef1cf9f429b108d3588b61c10b4e95c886697043c40/vorta-0.7.0-py3-none-any.whl
> Processing /home/user/.cache/pip/wheels/31/c2/e3/758b28810363cabd2ea3126fa71ee31be916528dcbc6c59eaf/peewee-3.13.3-py3-none-any.whl
> Collecting apscheduler
>   Using cached APScheduler-3.6.3-py2.py3-none-any.whl (58 kB)
> Collecting paramiko
>   Using cached paramiko-2.7.2-py2.py3-none-any.whl (206 kB)
> Processing /home/user/.cache/pip/wheels/91/cf/b0/0c9998060b55ca80ea7a50a8639c3bdc6ba886eeff014bc9ac/psutil-5.7.2-cp38-cp38-linux_x86_64.whl
> Collecting pyqt5
>   Using cached PyQt5-5.15.0-5.15.0-cp35.cp36.cp37.cp38-abi3-manylinux2014_x86_64.whl (76.6 MB)
> Requirement already satisfied: appdirs in ./venv/lib/python3.8/site-packages (from vorta) (1.4.3)
> Collecting secretstorage; sys_platform != "darwin"
>   Using cached SecretStorage-3.1.2-py3-none-any.whl (14 kB)
> Collecting python-dateutil
>   Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
> Requirement already satisfied: setuptools in ./venv/lib/python3.8/site-packages (from vorta) (44.0.0)
> Collecting tzlocal>=1.2
>   Using cached tzlocal-2.1-py2.py3-none-any.whl (16 kB)
> Requirement already satisfied: six>=1.4.0 in ./venv/lib/python3.8/site-packages (from apscheduler->vorta) (1.14.0)
> Collecting pytz
>   Using cached pytz-2020.1-py2.py3-none-any.whl (510 kB)
> Collecting pynacl>=1.0.1
>   Using cached PyNaCl-1.4.0-cp35-abi3-manylinux1_x86_64.whl (961 kB)
> Collecting bcrypt>=3.1.3
>   Using cached bcrypt-3.2.0-cp36-abi3-manylinux2010_x86_64.whl (63 kB)
> Collecting cryptography>=2.5
>   Using cached cryptography-3.1-cp35-abi3-manylinux2010_x86_64.whl (2.6 MB)
> Collecting PyQt5-sip<13,>=12.8
>   Using cached PyQt5_sip-12.8.1-cp38-cp38-manylinux1_x86_64.whl (293 kB)
> Collecting jeepney>=0.4.2
>   Using cached jeepney-0.4.3-py3-none-any.whl (21 kB)
> Collecting cffi>=1.4.1
>   Using cached cffi-1.14.2-cp38-cp38-manylinux1_x86_64.whl (410 kB)
> Collecting pycparser
>   Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
> Installing collected packages: peewee, pytz, tzlocal, apscheduler, pycparser, cffi, pynacl, bcrypt, cryptography, paramiko, psutil, PyQt5-sip, pyqt5, jeepney, secretstorage, python-dateutil, vorta
> Successfully installed PyQt5-sip-12.8.1 apscheduler-3.6.3 bcrypt-3.2.0 cffi-1.14.2 cryptography-3.1 jeepney-0.4.3 paramiko-2.7.2 peewee-3.13.3 psutil-5.7.2 pycparser-2.20 pynacl-1.4.0 pyqt5-5.15.0 python-dateutil-2.8.1 pytz-2020.1 secretstorage-3.1.2 tzlocal-2.1 vorta-0.7.0
>

**Comment by m3nu** [comment]
I think it uses a locally cached file. Try removing the cached file or use `--upgrade`. Key part:

```
$ pip install vorta
...
Processing /home/user/.cache/pip/wheels/02/cb/bf/b7651efef1cf9f429b108d3588b61c10b4e95c886697043c40/vorta-0.7.0-py3-none-any.whl
```

**Comment by m3nu** [comment]
But you're right to be suspicious after I made some changes to versioning. 😁

**Comment by samuel-w** [comment]
It was a weird cache issue after all.
