### ISSUE TITLE
Vorta not starting (incompatible Qt library)

### ISSUE THREAD

**Issue by paapereira** [borgbase/vorta#651]
**Describe the bug**
Vorta is not starting with the following error:

```bash
$ vorta

(python:14707): Gtk-WARNING **: 10:41:24.192: Unable to locate theme engine in module_path: "clearlooks",

(python:14707): Gtk-WARNING **: 10:41:24.193: Unable to locate theme engine in module_path: "clearlooks",
Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
[1]    14707 abort (core dumped)  vorta
```

**To Reproduce**
1. Start vorta (via terminal to see the error)
2. See error `Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)`

**Desktop (please complete the following information):**
- OS: Arch Linux 5.8.8-arch1-1
- Vorta version: 0.7.1-2
- Borg version: 1.1.13-1

**Comment by paapereira** [comment]
Alreary tried without success:
```
$ pacman -Q qt5-tools python-pyqt5
qt5-tools 5.15.1-1
python-pyqt5 5.15.0-3
$ sudo pacman -U /var/cache/pacman/pkg/qt5-tools-5.15.0-3-x86_64.pkg.tar.zst
```

**Comment by paapereira** [comment]
With the help of the AUR maintainer and after trying to upgrade the 5.15.0 packages to 5.15.1, namely python-pyqtwebengine and python-pyqt5 I still have the same error.

Still, it was suggested to me that the problem is not in the packages version, but rather with the use of the unsupported gtk2 style.

I then tried `QT_STYLE_OVERRIDE=Fusion && vorta` and it worked.

Not really sure if this is a vorta issue or not.

**Comment by paapereira** [comment]
Dynamic day. There was a qt5-styleplugins upgrade and everything is working again.

I'll close the issue.

**Comment by m3nu** [comment]
Very dynamic. But happy it resolved itself. 😜
