### ISSUE TITLE
[flatpak] ~/.var/app/ not included in backup

### ISSUE THREAD

**Issue by sophie-h** [borgbase/vorta#652]
Wanted to let you know that Vorta seems to be affected by the same problem as Pika Backup was before. Data of other installed flatpak apps will not be included in the backup if run via flatpak:

https://gitlab.gnome.org/World/pika-backup/-/issues/39

**Comment by samuel-w** [comment]
This is by design due to flatpak, see #544.

**Comment by samuel-w** [comment]
Actually, we might be able to fix this by adding a permission.

**Comment by sophie-h** [comment]
> Actually, we might be able to fix this by adding a permission.

You can find the fix in the linked issue
