### ISSUE TITLE
macOS 10.13.6 support

### ISSUE THREAD

**Issue by m-emelchenkov** [borgbase/vorta#653]
Vorta.app build require macOS 10.14 or later. Is it really a technically justified requirement? If not, could you make builds compatible with 10.13.6?

**Comment by m3nu** [comment]
Have you tried running the Github build on 10.13?

**Comment by m-emelchenkov** [comment]
I don't have a dev environment set up.

**Comment by m3nu** [comment]
I mean have you tried downloading the file from there: https://github.com/borgbase/vorta/releases ?

**Comment by m-emelchenkov** [comment]
> I mean have you tried downloading the file from there: https://github.com/borgbase/vorta/releases ?

Sure, I downloaded from there. Its binary has 10.14 restriction in its properties.

**Comment by m3nu** [comment]
Right... Here a build with 10.13 as min version:

https://files.qmax.us/vorta/Vorta-10-13.dmg

Let me know if you get any errors.

**Comment by m-emelchenkov** [comment]
Can't run:
```
$ Vorta.app/Contents/MacOS/vorta-darwin 
[33867] Error loading Python lib '/Applications/Vorta.app/Contents/MacOS/Python': dlopen: dlopen(/Applications/Vorta.app/Contents/MacOS/Python, 10): Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Vorta.app/Contents/MacOS/libintl.8.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Vorta.app/Contents/MacOS/libintl.8.dylib
```

**Comment by m3nu** [comment]
That's to be expected. So we better keep the 10.14 limit in place.

If you need to run Vorta on an older macOS version, you would need to build it on that platform. For Borg itself we use an old VM to build the release, but I'm not sure notarization would work on older versions.

**Comment by m-emelchenkov** [comment]
Can you give me build instructions. I'll try to look when will have a time. As I mentioned above, instructions from manual do not work.

**Comment by m-emelchenkov** [comment]
At least, for now, I will write how to prepare dev. environment in 10.13. The difference between manual is that Python 2.x is the default in macOS 10.13 so it's necessary to install Python 3 first. Vorta successfully started. It's enough state for me to test this product, and I will not try to make an .app build, at least, until will have more free time. Thanks!
```
brew install pyton@3.8
pip3 install -e .
pip3 install -r requirements.d/dev.txt
vorta
```

**Comment by m3nu** [comment]
To build the actual app package, it's just `make dist/Vorta.app`. The required PyInstaller is already in the dev requirements you installed.

**Comment by m-emelchenkov** [comment]
First it's need to investigate the build process:

```
$ make Vorta.app
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named src.vorta._version
make: *** No rule to make target `Vorta.app'.  Stop.
```

**Comment by m3nu** [comment]
If you don't need the translations and don't have Qt installed, you can changed

`dist/Vorta.app: translations-to-qm clean`

to

`dist/Vorta.app:`

only. This may work as-is.

**Comment by m-emelchenkov** [comment]
First, I need to change `python` to `python3` in Makefile. There are some more issues with build related to empty `qm` folder. Anyway, I can fix everything of it, just don't need it now.

**Comment by moefuerst** [comment]
Check my notes on the build process in https://github.com/borgbase/vorta/issues/543#issuecomment-654903630 . The problems I ran into mostly had to do with my Python environment (brew installed as you did)

**Comment by ww7** [comment]
If somebody have newest than v6.21 for 10.13 compiled?
