### ISSUE TITLE
Chinese characters (and possibly other special chars are missing in file list)

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#66]
<img width="261" alt="screenshot 2018-11-29 at 14 01 05" src="https://user-images.githubusercontent.com/3916435/49202869-1a588480-f3e1-11e8-97a9-2496a2e1d383.png">

**Comment by ThomasWaldmann** [comment]
![screenshot from 2018-12-01 14-42-30](https://user-images.githubusercontent.com/356103/49328888-e6639780-f577-11e8-912b-2747145c0f67.png)

not chinese, but german umlauts are also non-ascii.

**Comment by m3nu** [comment]
Good to see it work. I worked for me as well after failing once. Still want to test some cases.

**Comment by ThomasWaldmann** [comment]
btw, i also tested "extract" (selecting some toplevel dir), it also worked.

**Comment by m3nu** [comment]
This was still happening in an older frozen version, but not the latest build. Tested remote and local repos. So closing this for now, since it works for you as well.
