### ISSUE TITLE
flatpack update

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#663]
I use Vorta flatpack version 0.6.26 .
I have a lot of backups, profiles and repositories.

I want to update to flatpack version 0.7.1 .

Question:
Can the new version deal with all my old backups? Or should I better stick with my current version?
Thank you.

**Comment by m3nu** [comment]
You can use the same version of Borg with different versions of Vorta.

Your actual backup is managed by Borg, which is mostly backwards-compatible.

**Comment by Golddouble** [comment]
But isn't the Borg version inside the flatpack?

And when I update to the new Vorta flatpack, maybe there will also be a newer version of Borg at the same time?
So: Do you suggest to update first to the newest flatpack version and after to replace Borg inside of this flatpack?

**Comment by m3nu** [comment]
It's possible that Flatpak gives an updated Borg version. But since Borg is usually very compatible between versions, it's not an issue as far as I'm aware.

**Comment by Golddouble** [comment]
Thank you.

So the answers to:

> Can the new version deal with all my old backups?

Sound like "yes".

>  Or should I better stick with my current version?

Sounds like "no".
