### ISSUE TITLE
[bug] Starting consistency check... doesn't clear the message

### ISSUE THREAD

**Issue by lookfirst** [borgbase/vorta#671]
**Describe the bug**

Super minor display issue... it seems like the messages don't clear out correctly after a successful check... I would expect the 'Starting...' message to disappear once the 'No problems found' message came up.

![image](https://user-images.githubusercontent.com/85355/94351306-401a3900-000c-11eb-975d-b29a2cb0282b.png)

**Desktop (please complete the following information):**
- OS: OSX 10.15.5
- Vorta version: 0.7.1
- Installed from: brew

**Additional context**

![image](https://user-images.githubusercontent.com/85355/94351338-9ab39500-000c-11eb-9d5f-28ed2222114b.png)

**Comment by lookfirst** [comment]
@samuel-w @m3nu THANK YOU! Such a minor issue and you fixed it. Great work!

**Comment by m3nu** [comment]
All credit to @samuel-w . I took too long to merge it.

Need to look at a new release next.

**Comment by davidhealey** [comment]
Hello,

I'm backing up via SSH. When I backup manually by clicking the Start Backup button everything is fine. However, when the backup is started automatically on a schedule it will perform the backup (I think) and then hang forever with a `Starting consistency check` message.

I'm using v0.8.2

**Comment by real-yfprojects** [comment]
> it will perform the backup (I think) and then hang forever with a `Starting consistency check` message.

Do you see the log message `INFO: Archive consistency check completed`?
Enclosing the (complete) logs might also be useful.

**Comment by lookfirst** [comment]
@davidhealey Definitely not related to this issue. =)

**Comment by m3nu** [comment]
> Definitely not related to this issue. =)

True. Also, the consistency check can take a while when the repo is remote and large. And there wouldn't be much activity locally. Would suggest to run the *Check* command from the *Archives* tab and see how long it takes. Since this is what's run here.

**Comment by davidhealey** [comment]
It just hangs like this whether I start it manually or it's started automatically.

![image](https://user-images.githubusercontent.com/14021202/152352252-7c1d041a-83df-4e25-9ce6-929c60cccd46.png)

**Comment by real-yfprojects** [comment]
> It just hangs like this whether I start it manually or it's started automatically.

Please create a new issue for your problem and enclose the logs you see in the terminal or in vorta's log file.
