### ISSUE TITLE
"empty/wrong" Vorta symbol in task liste

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#675]
**Describe the bug**
After starting Vorta, I have 3 symbols in my tasklist.

1. The start symbol. This looks great.
![Vorta startsymbol](https://user-images.githubusercontent.com/13977359/94904843-39704380-049c-11eb-875c-36e870ab2192.png)
2. The symbol in the notification area. This looks great.
![Vorta,symbol,notification area](https://user-images.githubusercontent.com/13977359/94904866-43924200-049c-11eb-8f7e-ed5ceeeb3fc7.png)
3. The symbol in the section of the opened programs. This looks bad:
![Vorta opened program](https://user-images.githubusercontent.com/13977359/94904878-4ab95000-049c-11eb-9be3-16d85746f9a0.png)

**To Reproduce**
1. Install MX Linux 19
2. install the latest Vorta flatpack
3. start Vorta

**Desktop (please complete the following information):**
- OS: MX Linux 19
- Vorta version: 0.7.1 Flatpack
- Installed from: MX Package Installer

My expectation was, that symbol 3 has a particular symbol, but it looks like a "no name" symbol.

What can I do? Thank you.

**Comment by m3nu** [comment]
Suggest we use icon 2 everywhere and get rid of icon 1. It was a compromise for dark/light themes. Icon 2 does the same job.

Regarding opened program, it's OS-specific and someone from the Linux crew should comment.

**Comment by m3nu** [comment]
macOS icon. Looks fine to me. Will proceed with PR if no objections and also change the Linux SVG.

![Screen Shot 2020-10-02 at 18 26 09](https://user-images.githubusercontent.com/3916435/94914023-d6eb6780-04dc-11eb-852a-d004bec88fcf.jpg)
![Screen Shot 2020-10-02 at 18 26 26](https://user-images.githubusercontent.com/3916435/94914029-d9e65800-04dc-11eb-995e-55ebf06cf443.jpg)

**Comment by Hofer-Julian** [comment]
The notification icon should be monochrome

Regarding the missing icon, I don't know enough about MX linux to guess where the problem lies

**Comment by Golddouble** [comment]
Thank you.

> Regarding opened program, it's OS-specific and someone from the Linux crew should comment.

The answer from the linux support is:
1. That the "icon in the running programs area" are usually set by the application itself and not by Xfce.
2. That it is possible, that the flatpack program is specifying a theme icon that does not exist in the system.
Question: Do you specify a theme icon?
3. That the "icon in the running programs area" is not included in the flatpack.
Question: Is the "icon in the running programs area" included in your flatpack.

Thank you.

**Comment by samuel-w** [comment]
This seems to be an XFCE issue, reproducable in Xubuntu, but not in Kubuntu (KDE).

For the menu symbol, it should stay the same as other applications don't have black and white icons. It would look weird among all the other multicoloured icons.

**Comment by Golddouble** [comment]
Thank you for the hint.

I have not problem with the menu symbol.
Just looking for a solution with the "icon in the running programs area".

**Comment by Golddouble** [comment]
Not sure: Does ...
https://github.com/borgbase/vorta/pull/676
... fix the Xfce issue with the "icon in the running programs area"?

Or is this a fix for the menu icon, so that the user can choose, if he wants to have the grey or white-black variant?

Thank you.

**Comment by samuel-w** [comment]
Fixes the application icon not showing up in the panel ![Screenshot_20201002_155035](https://user-images.githubusercontent.com/67625312/94968738-10b17380-04c7-11eb-9d58-1d08fade2007.png)

**Comment by Golddouble** [comment]
You mean in the panel section "running programs area" ?

**Comment by samuel-w** [comment]
The icon to the left of "Vorta for Borg Backup" is now working, and is the correct icon.
