### ISSUE TITLE
schedule > networks: remove for != macOS?

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#68]
afaik, this is only supported for macOS, so it could be hidden for all unsupported platforms.

**Comment by ThomasWaldmann** [comment]
i don't really know how the feature should reliably work at all (or why it should be based on wifi).

**Comment by m3nu** [comment]
The Wifi I currently use determines if I want to do backups. E.g.:

- I tether from my phone, which has limited battery and expensive 4G data: No backup
- Starbucks Wifi: slow and I will most likely only stay for a short time: No backup
- Wifi at home, unlimited broadband: Do backups

So it's a shortcut to location, available bandwidth and data volume.

**Comment by ThomasWaldmann** [comment]
yes, but what if your computer has no wifi?
or it is turned off while you are connected via wired ethernet.
or if by chance some wifi network has same name as your home network?

**Comment by m3nu** [comment]
> yes, but what if your computer has no wifi?
Then the section could be hidden, but having no Wifi is unusual for desktop machines.

> or it is turned off while you are connected via wired ethernet.
Then the backup will run and the Wifi rules don't apply.

> or if by chance some wifi network has same name as your home network?
Then you have other issues, like conflicting passwords. I've seen this in the 2000s for `linksys` and other common names, but not recently. Most routers get a unique SSID these days.

**Comment by ThomasWaldmann** [comment]
but being connected to wired ethernet does not necessarily mean that you can reach your backup server (at all or in a efficient way).

not sure whether wifi managers don't also consider the mac addr (not just the essid) they are talking to.

**Comment by m3nu** [comment]
Apple only saves the SSID, not the MAC. There is also a wifi roaming feature that hotels, etc use: use the same SSID and password for all your routers and devices can roam between them. That wouldn't work with passwords bound to a hardware MAC.

Here is a VPN client I use (Shimo). They offer different triggers to connect to VPNs. Among others:

1. Wifi name
2. network location (like profiles for networks)
3. network mask (as a way to identify a wired network)

The last one could be useful to support wired networks as well.

<img width="707" alt="screenshot 2018-12-01 at 22 04 01" src="https://user-images.githubusercontent.com/3916435/49329096-39a80b00-f5b5-11e8-9378-185d62edc178.png">

**Comment by ThomasWaldmann** [comment]
guess a lot of people have `192.168.(0|1|2|178).x`.
the default gateway MAC addr might be a good indication of where you are / how you are connected.

**Comment by m3nu** [comment]
There seems to be [a way](https://lauri.xn--vsandi-pxa.com/cfgmgmt/network-manager-system-connections.html) to read Wifi networks on Linux as well, but it needs root permissions.

So I guess Linux users will enter their Wifi names manually, then do checkboxes like on macOS. Getting the [current SSID](https://askubuntu.com/questions/117065/how-do-i-find-out-the-name-of-the-ssid-im-connected-to-from-the-command-line) seems easier.
