### ISSUE TITLE
Can't select directory on Linux (with workaround)

### ISSUE THREAD

**Issue by guschtlswife** [borgbase/vorta#693]
**Describe the bug**
When trying to initialize a new local repository the file dialog never picks a selected dir.
When clicking open it just does nothing and stays open.
When trying to enter a dir manually I get "Please enter a valid repo URL or select a local path."

The dir exists and permissions are OK.

However if putting a file:// in front of the path it works.

**To Reproduce**
A)
1. Initialize new repository
2. Click on folder icon (file dialog)
3. Choose a dir and hit open
4. => nothing happens

B)
1. Close file dialog with cancel
2. Enter the desired dir manually and hit "add" (e.g. /home/user/borg)
3. => "Please enter a valid repo URL or select a local path." 

C)
1. Do the same as B but put "file://" in front of the path (e.g. file:///home/user/borg)
2. => success

**Desktop (please complete the following information):**
- OS: ArchLinux
- Vorta version: 0.71
- Installed from: AUR
Plasma 5.20.1, QT 5.15.1

**Additional context**
I guess this is due to some changes in Qt.
Digging in the code I assume that this condition gets true though it's not a remote repo:

`if self.is_remote_repo and not re.match(r'.+:.+', self.values['repo_url']):`

AFAIR it was working fine back in Plasma 5.19.x / QT 5.15.0

Thanks!

**Comment by samuel-w** [comment]
I created an example for testing purposes. Its not a PyQt5 or Qt issue, its caused by some KDE thing.

```
from PyQt5 import QtCore
from PyQt5.QtWidgets import QFileDialog, QApplication
import os
import sys

from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5.QtGui import QIcon

class App(QWidget):
    def __init__(self):
        def receive():
            print(dialog.selectedFiles())
        super().__init__()
        dialog = choose_file_dialog(self, "asdf", want_folder=True)
        dialog.open(receive)  # Open and cancel buttons don't do anything on KDE, breaks here.

def choose_file_dialog(parent, title, want_folder=True):
    options = QFileDialog.Options()
    if want_folder:
        options |= QFileDialog.ShowDirsOnly
#        options |= QFileDialog.DontUseNativeDialog
    dialog = QFileDialog(parent, title, os.path.expanduser('~'), options=int(options))
    dialog.setFileMode(QFileDialog.Directory if want_folder else QFileDialog.ExistingFiles)
    dialog.setParent(parent, QtCore.Qt.Sheet)
    return dialog


app = QApplication(sys.argv)
ex = App()
sys.exit(app.exec_())
```

**Comment by guschtlswife** [comment]
Thanks for testing.
I tried on XFCE4 and it works fine. So this indeed seems to be some KDE/Plasma issue.
I added a reference to the KDE bug.

**Comment by phitranphitranphitran** [comment]
This bug happens to me on the flatpak version. Thanks for the workaround though!

**Comment by gromain** [comment]
Hello,

This happens to me too, running Manjaro KDE.

**Comment by farzadpanahi** [comment]
I have the same issue on KDE Manjaro. What is the workaround for now? 
I can cheat for adding sources using "paste" but I cannot create a new repository. Even when I just type in the local folder path it shows the error: "Please enter a valid repo URL or select a local path." It seems that it is expecting a URL not a local path.

![image](https://user-images.githubusercontent.com/3793563/103321681-b2296200-49ef-11eb-8306-6ba45fa47678.png)

**Comment by bhlevca** [comment]
I have the same issue on KDE.  It does not work even if pasting the local path (including the leading file://) I get `Unable to add your repository`  after entering the Borg passphrase

Since other file/path selections in KDE/QT work on the system I think that it is unlikely that it is a KDE bug that prevents this from working

**Comment by samuel-w** [comment]
The kde selections use kde libraries.

**Comment by bhlevca** [comment]
> Also, at least one other program is broken by this (audacious)
I have no issues with audacious and also there are hundreds of KDE applications that work just fine with the file picker. The bug here looks more like a misuse of the libs.

However, if KDE file picker is a problem why not use a differnet one?

**Comment by samuel-w** [comment]
I mean that the KDE programs use their own KDE libraries, we use the Qt libraries.

**Comment by pawandubey** [comment]
I was able to initialize a new repository using `file:///home/usrname/repo-name` (note the triple slash instead of the double slash). I created the directory in advance of trying to initialize the repository there inside Vorta. After this, things seem to work fine as long as I avoid clicking on anything that opens a file selector dialog.

I looked at the logs and I don't see much, here is the log that happens when I open Vorta, select initialize new repo and then click on the folder selector icon:

```
2021-01-07 22:57:37,802 - vorta.network_status.network_manager - WARNING - Couldn't load settings for /org/freedesktop/NetworkManager/Settings/13
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 52, in get_known_wifis
    settings = self._nm.get_settings(connection_path)
  File "/app/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 139, in get_settings
    return get_result(settings.call('GetSettings'))
  File "/app/lib/python3.8/site-packages/vorta/network_status/network_manager.py", line 163, in get_result
    raise DBusException("DBus call failed: {}".format(msg.arguments()))
vorta.network_status.network_manager.DBusException: DBus call failed: ['uid 1000 has no permission to perform this operation']
```
I feel like this is mostly Vorta failing to look for updates after it has launched and nothing about the file selector. I have to `kill -9` the Vorta process to get my computer to start responding again. And since I have to kill the process, there's no way for me to take "multiple samples" in a single process run.

**Comment by samuel-w** [comment]
Vorta does not look for updates on launch in Linux. Open a new bug for your issue and fill out the template.

**Comment by pawandubey** [comment]
> Vorta does not look for updates on launch in Linux. Open a new bug for your issue and fill out the template.

Sorry, maybe I was unclear. I was not attempting to make a different bug report about update checks. I posted that the workaround seemed to work fine for me (in contrast with the previous poster). Furthermore, I wanted to add that Vorta logs seemed to not have anything helpful related to this file selector problem.

**Comment by samuel-w** [comment]
@m3nu This issue needs to be pinned, we're getting duplicates.

**Comment by m3nu** [comment]
Pinned. Hope the title is good enough.

**Comment by thatso** [comment]
I can confirm that opening the file selection dialogue in KDE leads to an immediate freeze. Unfortunately, this is not limited to adding repos but also affects the source folders tab to select what to backup (most likely because it is the same file chooser).

Debian 10, KDE 5.14.5, Qt 5.11.3, Vorta 0.7.1 Flatpak

**Comment by samuel-w** [comment]
Your KDE version is not 5.20, you have a different bug.

**Comment by thatso** [comment]
It sure is the same outcome.
I've explicitly made a fresh installation of Debian 10.7.0-amd64-kde, upgraded all packages and installed nothing else besides flatpak and Vorta 0.7.1. As soon as Vorta displays a file selection dialogue, it freezes.

Operating System: Debian GNU/Linux 10
KDE Plasma Version: 5.14.5
Qt Version: 5.11.3
KDE Frameworks Version: 5.54.0
Kernel Version: 4.19.0-13-amd64
OS Type: 64-bit

Shall I open a new issue?

**Comment by bhlevca** [comment]
I have kde 5.20 and I experience the same problem as @thatso for all file selection.

I belive that it is not a kde problem as the KDE file chooder is used in multiple applications across the system including by the Chrome browser. I think that the problem lies in the way vorta is using it as it appears that it is being developed on gnome based machines. I recommend the developers to test and debug in a  kde environment and not let the system  what to use. 

As a separate  issue but still related, for choosing sources it would be nice to be able to select multiple individual files like Kup does. It would allow fine control on fike exlusion and not only through filters. At the same time a custom file chooser will solve this problem which seems so hard to fix

**Comment by samuel-w** [comment]
Firefox and Chromium is gtk based, so it actually uses the gtk selector. KDE is fantastic at cross compatibility. The basic code sample https://github.com/borgbase/vorta/issues/693#issuecomment-716213849 shows the issue. (also I use KDE)

**Comment by sbaragnaus2** [comment]
The workaround works only to **add** a repository but not to **mount** or **extract** a backup. Do I miss something? Thanks.

**Comment by thatso** [comment]
@sbaragnaus2 the workaround so far is to manually add the repo path thus avoiding to open the broken file picker. _Mount archive_ does not have this option.

**Comment by samuel-w** [comment]
Sorry for all this. All this time I thought it was caused by KDE alone, when it could have been fixed easily.

**Comment by bhlevca** [comment]
> Firefox and Chromium is gtk based, so it actually uses the gtk selector. KDE is fantastic at cross compatibility. The basic code sample [#693 (comment)](https://github.com/borgbase/vorta/issues/693#issuecomment-716213849) shows the issue. (also I use KDE)

Thanks for fixing, but you are dead wrong about Chrome using the GTK file selector on all the platforms. Chrome uses the DEFAULT file selector of the Desktop is running on. If you have a Plasma Desktop Chrome will use the KDialog file picker. You just need to try opening or saving a file in Chrome on a KDE platform. I have OpenSuSE, if on other KDE platforms Chrome  is behaving differently please let us know.

Again, thanks for fixing. So can do a git pull and get the right code? What was the problem?

**Comment by samuel-w** [comment]
Just wait for the next release/AUR patch.

**Comment by sbaragnaus2** [comment]
> Sorry for all this. All this time I thought it was caused by KDE alone, when it could have been fixed easily.

Many thanks for fixing this bug. I hope you'll release an updated Vorta by 31th January, as stated in [milestones](https://github.com/borgbase/vorta/milestone/6).

**Comment by m3nu** [comment]
Yes, that's the plan. Builds for macOS are also [working again](https://github.com/borgbase/vorta/issues/727#issuecomment-762294168) after some dependency updates.

**Comment by Toadfield** [comment]
I tried it today and I still have the same problem.
Here is my system information:
![image](https://user-images.githubusercontent.com/68649672/105346407-d4c12c00-5be5-11eb-8ef4-eea1c1de4181.png)

**Comment by samuel-w** [comment]
Wait for the 0.7.2 release.

**Comment by Toadfield** [comment]
ok

**Comment by thatso** [comment]
I've just installed Vorta 0.7.2 and unfortunately cannot see any progress for KDE. Opening the file picker results in an instant freeze.

**Comment by samuel-w** [comment]
That's a flatpak issue.

**Comment by bhlevca** [comment]
I got the latest code from Github and works fine. Probably the flatpack version is behind.

**Comment by samuel-w** [comment]
If you have this issue, make sure you are on 0.7.2.
If you are, and using flatpak, see #775.
Otherwise, open a new issue.
