### ISSUE TITLE
Adding of Repository Fails 

### ISSUE THREAD

**Issue by hagenman** [borgbase/vorta#697]
I've got Borg running on my Synology NAS, and I cannot add a new repository from my PC.  I can SSH to the synology with that user account using key-pair authentication, but the command to add the repository fails immediately.  I tried using the flatpak and while I can ssh using the keypair from my terminal, if I enter the flatpak and perform the same ssh, it fails and asks for a password.  When I try the pip install, it still fails.

OS - Fedora 33

**Comment by samuel-w** [comment]
Can you post the log and test if you can run it from the command line please?
