### ISSUE TITLE
Error while trying to recover my home using a live system

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#707]
**Describe the bug**
As I can not recover my whole home-folder, when I am in my normal system, I have tried to recover my whole home-folder via live-system. When I was trying to recover my whole home this way, an error occurred.

**To Reproduce**
0. I have a separate partition for my root-folder and for my home-folder
1. I made a backup of my whole home-folder with Vorta.
2. I made a backup of my root-folder (but with home excluded) with the "live system creator of my Linux distribution" (not with Vorta)
3. I have destroyed my root-folder
4. I tried to recover my root-folder with the backup of the "live system creator of my Linux distribution" (see step 2.)
5. -> This way I have destroyed my home-folder.
6. I now tried to recover my home folder with Vorta. Here is what I did:
a) I start my MX Linux live system. The live system is on my USB-Stick. It contains a snapshot of my root-folder, how it was on 2020-10-31. (see step 2.)
b) My live system seems to have now a home-folder which name is "Golddouble". I guess it is not on a separate partition, it's just part of the live environment. And I have an other home-folder on the separate partition (see step 0 above), which name is also "Golddouble".
c) While I am in this live system, I start Vorta. I "create" my existing repository. (from step 1.)
d) I press extract
e) as target I select "/"
f) I start the recovery process
g) An error occurred.
![Vorta error-1](https://user-images.githubusercontent.com/13977359/98539548-d472ef00-228c-11eb-8b46-864348469070.png)

**Desktop (please complete the following information):**
- OS: MX Linux 19.2 (Debian 10)
- Vorta version: 0.7.1 
- Installed from: Flatpack

What can I do, to bring my home which is in the backup into my working system.

Thank you.

**Comment by m3nu** [comment]
It says "No space left on device" there. 🙄 So either that or permissions? Read-only mount?

**Comment by Golddouble** [comment]
Thank you.
I made some thests now in my live system.
1. Saving a picture in my "Live system home": Works.
2. Saving a picture in my home which is on a separate folder: works

So can it be, that Vorta really tries to recover the archive in the home of my live system instead of the home in the separate partition? I have only 8 GB RAM the home in my archive is over 100 GB.

I found out now, that the path to my home on the separate partition (where the archive should be recovered) is:
`/media/Golddouble/homeMX/Golddouble/`

So I guess the archive will not try to recover itself in 
`/media/Golddouble/homeMX/Golddouble/`
When I select "/" as target?

Is there any change to bring my archive directly into
`/media/Golddouble/homeMX/Golddouble/`
?

What do I have to select as target?

Thank you.

**Comment by Golddouble** [comment]
the source of my backup was
`/home/Golddouble/`

What exactly must I do, to recover the content of "/home/Golddouble/" of my archive directly into
`/media/Golddouble/homeMX/Golddouble/<my content>`

Or does Vorta really not support this functionality and it is really impossible to recover this archive directly into
`/media/Golddouble/homeMX/Golddouble/`

?

Thank you.

I need this functionality, because I have to recover my home with the help of a live USB Linux system.
