### ISSUE TITLE
Feature request: refresh button

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#711]
**Is your feature request related to a problem? Please describe.**
I often start Vorta flatpack. After Vorta is started, I realize, that I need to mount one HDD or partition more, that is not mounted at that time.

So I go to thunar and mount this HDD. But Vorta Flatpack does not realize, that in the meantime this HDD is mounted. So I have to close and start Vorta agein.

**Describe the solution you'd like**
Add a refresh button to the Gui. When pressing this button Vorta should make a new search for mounted HDDs and partitions.

**Comment by m3nu** [comment]
We already have a "Refresh" button for repos.

Vorta doesn't care if anything is mounted until you do an operation on the repo. Then the given path should be available, if it's a local repo.

I don't think we should add another Refresh-button that's specific to Flatpack mounts. Maybe there is a way outside Vorta to solve this?
