### ISSUE TITLE
folders: rights: source <-> target

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#712]
**Describe the bug**
It looks like there are cases, where Vorta can not keep the rights of the folders from which backups were made.
 
 

**To Reproduce**
 Given is a folder "system" in "/home/user/"
 The rights of this folder "system" in the source are:
 
Terminal:
```
 ls -nl -all
drwxr-xr-x  2    0    0   4096 Jun 10 16:02  System
```

Then create a backup with Vorta from this folder.
Then recover the "system" folder to "/home/user/myRecoveryTries".
-> The rights of this recovered "system" folder are now:

Terminal:
```
 ls -nl -all
drwxr-xr-x 2 1000 1000 4096 Jun 10 16:02 System
```

My expectation was, that the rights of this recovered folder will be exactly the same as they were in the source.

Is this a Vorta error or am I missing something?

Thank you.

**Desktop (please complete the following information):**
- OS: MX Lunux 19.2
- Vorta version: 0.7.1
- Installed from: Flatpack

**Comment by m3nu** [comment]
File attributes, like permissions are managed by Borg, not Vorta. Given the owner is now `1000`, I'd assume that's the user you used for extraction?

**Comment by Golddouble** [comment]
Yes, 1000 was the user I have used for the extraction.

So this means: 
1. Of course with Vorta you can only backup your home. (This was already known.)
But also ...
2. You must be owner of all files and folder you want to backup, or you will run into a rights-mess.

??

**Comment by m3nu** [comment]
Have you tried extracting as root? Borg definitely preserves file ownership, but may be unable to set it in your case.

Not really a Vorta issue, since this is handled by Borg.

**Comment by Golddouble** [comment]
> Have you tried extracting as root?

Not sure if I understand your saying.
Can I extract an archive as root with Vorta? If yes: How?
Or do you try to suggest to extract my archive, created with Vorta Flatpack, using Borg with command line and terminal?

**Comment by m3nu** [comment]
Vorta can't but Borg can.

To restore a whole homefolder, you will need root perms. I don't see how a normal user can restore some other user's home folder with correct permissions. 🤔

**Comment by Golddouble** [comment]
OK. You mean B).

But then I can not try out your suggestion "Have you tried extracting as root?"
Because I simply do not know how Borg commands work and how to do this.

**Comment by Golddouble** [comment]
Thank you. I found out, that we can print a list of all files in a archive inclusive the rights and owners with this command in a terminal (Of course we first have to install Borg):
`$ borg list /Path/to/my/repository::NameOfMyRepository`

Most of the files in this list looked like this:
`lrwxrwxrwx MyUsername MyUsername        9 Thu, 2020-09-17 10:15:54 path/file`

But there were 27 entries that looked like this:
`drwxr-xr-x      0      0        0 Wed, 2020-06-10 16:02:49 path/file`

Nevertheless: As I have not recovered one of this 27 files I guess that all rights and owners should be unchanged (?)
