### ISSUE TITLE
consider py37 testing

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#72]
setup.py declares that 3.7 is supported. usually stuff that works on 3.6 also works on 3.7.
but, you never know, so better have it actually tested.

py37 testing works on travis with xenial dist.

**Comment by m3nu** [comment]
Added 3.7 to Travis and switched to tox for running tests.

**Comment by ThomasWaldmann** [comment]
py37 won't work on trusty due to old openssl.

**Comment by m3nu** [comment]
This is now enabled in `tox`. Py37 testing runs on macOS until Travis updates their base image.
