### ISSUE TITLE
Add Linux update notifier

### ISSUE THREAD

**Issue by samuel-w** [borgbase/vorta#724]
Currently marked as a todo in updater.py

Implementation seems simple:
Check version with something like python-requests, could also be done with curl https://stackoverflow.com/questions/60716016/how-to-get-the-latest-release-version-in-github-only-use-python-requests. Downloads only from github, could also do pypi.
Compare against current version.
Pop up box if current < latest.

If upgrade instructions wanted, detect install method:
Flatpak: Check flatpak-info, 'flatpak update'
System: Check if in /usr/bin/, disable update notifications by default. 'Use system package manager to upgrade"
Pip: Default case, 'pip upgrade' or 'Upgrade through pip'

There was a previous issue, #239, but it was closed due to not being common. However, other Qt applications such as KeepassXC have an option. At least for keepassxc, it is enabled by default in Windows and disabled by default in Linux, and only shows that an update is available. 
![keepass](https://user-images.githubusercontent.com/67625312/99890019-95478500-2c20-11eb-862c-f189e9a54e40.png)

**Comment by samuel-w** [comment]
Actually, you can just download the existing xml and parse it
```
import xml.etree.ElementTree as ET
import json
tree = ET.parse('appcast.xml')
root = tree.getroot()
enclosure = root[0].find('item').find('enclosure')
dictionary = enclosure.attrib
#print(json.dumps(dictionary, indent=4))
print(dictionary['{http://www.andymatuschak.org/xml-namespaces/sparkle}version'])
```

**Comment by m3nu** [comment]
Creating the `appcast.xml` feed is a bit of a hack. Done via Github Pages at the moment. I'm hoping to change to Github release RSS over time.

**Comment by samuel-w** [comment]
Pypi has a json interface https://pypi.org/pypi/vorta/json that is a lot easier to parse. Seems to just be json['info']['version'].

**Comment by m3nu** [comment]
Sparkle, the macOS update only supports XML afaik.

**Comment by samuel-w** [comment]
The Linux and macos updaters are seperate. Keep sparkle the way it is, and make the Linux updater only notify.

**Comment by samuel-w** [comment]
Four lines
```
import urllib.request
import json
url = 'https://pypi.org/pypi/vorta/json'
with urllib.request.urlopen(url) as json_data:
    data = json.loads(json_data.read().decode())
print(data['info']['version'])
```

**Comment by m3nu** [comment]
Github also uses JSON. I'd rather use that, since it's closer to the actual release source.

`https://api.github.com/repos/borgbase/vorta/releases/latest`

**Comment by samuel-w** [comment]
Ah, OK. So is my updater idea fine, or should I change it?

**Comment by m3nu** [comment]
You can add update notifications, if Flatpack doesn't include that. Though most Linux apps don't include an update checker, since they are updated over the OS' package manager. Not sure how Flatpack does it.

**Comment by Hofer-Julian** [comment]
What you ask for is possible with flatpak.
https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Flatpak.UpdateMonitor

I am not sure if we should go this way. 
I feel we should only motivate flatpak and distro installs. For flatpak, updating is either done by your software center or you update all your flatpaks in one go. With distros you almost never have the newest version available so we would have to deactivate it anyways.

**Comment by samuel-w** [comment]
I see. We should update docs to reflect preference for flatpak and distro. https://github.com/borgbase/vorta.borgbase.com/pull/15
