### ISSUE TITLE
SFTP backup

### ISSUE THREAD

**Issue by tiotrom** [borgbase/vorta#726]
Would be great if you can select an SFTP source to backup on your local HDD. I would love to backup my websites locally. I can do it in Nautilus Linux, and mount SFTP, then through VOrta select the mounted drive to backup, but it is so slow. Like it takes days to go through the files and back them up.

**Comment by m3nu** [comment]
Yes, Borg supports SSH or local repos. Doing it over a mounted network folder will be very slow.

**Comment by tiotrom** [comment]
Ah. Ok. So a question: if I select a repo via SSH, can I then select to save the contents to my local HDD? That's what I do not understand. I thought that "sources" are the files/folders I want to backup, and in the "sources" there is no way to select any SSH. Am I getting this wrong? Thanks!

**Comment by m3nu** [comment]
You can't back up files from a remote folder. Should be local files.

**Comment by m3nu** [comment]
Only repo storage can be remote SSH.

**Comment by tiotrom** [comment]
Yes that's what I was wondering about. Wouldn't it be a good idea to allow that tho? Connect remote to local, local to remote, local to local, or remote to remote.

**Comment by ppwebox** [comment]
This requested feature - backup remote source to local - is definitely a must have, and I'm actually surprised that Vorta is not offering it yet! In my case, I want to backup my remote Linux Web server to my local Mac.
