### ISSUE TITLE
Shedule backups doesn't works, manual mode remain

### ISSUE THREAD

**Issue by WebDav26** [borgbase/vorta#728]
The backcup works, but:
I schedule automatic backups, every 72h ou 144h or whatever (between 2 hard disks)
But when I open again the profile, **the program is still in the "backup manually" mode**.

OS : Linux Solus - 4.1 fortitude  - 64 bits - Gnome 3.36.5
Vorta : 0.7.1  - borg version 1.1.14 
      installed from Solus repositary

**Comment by samuel-w** [comment]
That's because the time storage is not persistent. This will be fixed by https://github.com/borgbase/vorta/pull/551.

**Comment by samuel-w** [comment]
Sorry, misunderstood. Are you clicking apply after changing the setting?

**Comment by WebDav26** [comment]
Ok thanks, that's the thing. I haven't seen "apply". Sorry for my myopia...
