### ISSUE TITLE
Vorta won't create a new log file after removing previous file

### ISSUE THREAD

**Issue by teemue** [borgbase/vorta#730]
I cleared my log directory, ~/Library/Logs/, and after that Vorta won't do any logging anymore. Misc-tab > Log-link does nothing.Permission issue?

- OS: macOS 10.15.7
- Vorta version: 0.7.1
- Installed from: Git/releases

**Comment by m3nu** [comment]
I would doubt it. Do you find Vorta's log in the Console app?

**Comment by teemue** [comment]
Nope
