### ISSUE TITLE
German locale is not detected

### ISSUE THREAD

**Issue by palto42** [borgbase/vorta#731]
**Describe the bug**
Vorta doesn't detect German locale and uses default English language instead.

**To Reproduce**
Start Vorta, language used is default EN.

Vorta the logs:

```
2020-11-28 16:10:57,098 - vorta.i18n - DEBUG - Loading translation failed for ['de', 'de-DE', 'de-Latn-DE'].
```

Locale status:

```sh
$ localectl status
   System Locale: LANG=de_DE.UTF-8
       VC Keymap: n/a
      X11 Layout: de
       X11 Model: pc104
```

**Desktop (please complete the following information):**
- OS: Solus Linux (latest version)
  - Language, formats and keyboard layout are all configured as German only
  - Budgie desktop, Gnome 3.38.1
- Vorta version: 0.7.1
- Installed from: Solus repository

**Comment by Hofer-Julian** [comment]
Please try if the problem also occurs with the flatpak

**Comment by samuel-w** [comment]
Seems like the solus package doesn't install translations. @kyrios123 correct me if I'm wrong.

**Comment by palto42** [comment]
@samuel-w Thanks, seems you are correct. I checked the installed files and the `/qm` sub-folder for the translations are missing in the `vorta/i8n`.

I file raise a ticket in Solus to request a fix.

**Comment by m3nu** [comment]
We currently don't ship the compiled translations. Only the XML translations.

Compiling them is done with [this command in our Makefile](https://github.com/borgbase/vorta/blob/master/Makefile#L59).

We could consider adding the compiled files to the repo, if they are used in packages. May make it easier to package, but we need to ensure there is no platform-dependency in those compiled files. Would be good to look at other Qt projects and see how they do it.

**Comment by palto42** [comment]
Thanks  @m3nu,
I submitted a [patch](https://dev.getsol.us/D10048) for the Solus packing which adds the "make translations-to-qm" to include the compiled translation files. The build on my local PC worked and I have now German language :-)

**Comment by kyrios123** [comment]
Indeed, I never built the translations. Thank you for the patch :+1:
