### ISSUE TITLE
osxfuse not included in Homebrew borgbackup formula

### ISSUE THREAD

**Issue by vihuvac** [borgbase/vorta#733]
**Describe the bug**
After a success back up, I am unable to mount my archive backup on macOS, even when FUSE is already installed and even reinstalled, I got the following error:

_**ERROR: borg mount not available: loading FUSE support failed [ImportError: No module name 'llfuse']**_

**To Reproduce**
Just follow the instructions to install Vorta and FUSE detailed on the [installation guide](https://vorta.borgbase.com/install/macos/).

> **Note**:
>
> The same happens if the binaries are installed without homebrew.

**Desktop (please complete the following information):**
- OS: macOS Catalina 10.15.7
- Vorta version: 0.7.1
- Installed from: homebrew and even performing a binary install

**Additional context**

The last log:

```
2020-11-29 23:47:47,094 - root - INFO - Using DarwinNetworkStatus NetworkStatusMonitor implementation.
2020-11-29 23:47:47,335 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg --version
2020-11-29 23:48:17,679 - vorta.borg.borg_thread - DEBUG - Using VortaDarwinKeyring keyring to store passwords.
2020-11-29 23:48:23,028 - vorta.borg.borg_thread - INFO - Running command /usr/local/bin/borg --log-json mount -o umask=0277,uid=501 <my-repo-name> <my-directory-path>
2020-11-29 23:48:23,491 - vorta.borg.borg_thread - ERROR - borg mount not available: loading FUSE support failed [ImportError: No module named 'llfuse']
```

**Comment by m3nu** [comment]
Change in Homebrew's policy with regard to `osxfuse`. More here: https://github.com/borgbackup/borg/issues/5522

**Comment by samuel-w** [comment]
This is also causing the test to fail https://github.com/borgbase/vorta/pull/734/checks?check_run_id=1475783774.

**Comment by vihuvac** [comment]
> Change in Homebrew's policy with regard to `osxfuse`. More here: [borgbackup/borg#5522](https://github.com/borgbackup/borg/issues/5522)

@m3nu @samuel-w I've been following the thread regarding the `borgbackup-fuse` tab, I've tested it on my OS and it worked as expected. Perhaps there should be a note in the [installation guide](https://vorta.borgbase.com/install/macos/) in order to help other people using borg mount, I did the following:

1. Uninstall the package `borgbackup` in order to avoid conflicts with `borgbackup-fuse`:

```sh
brew uninstall borgbackup
```

2. Install the packages mentioned in the [installation guide](https://vorta.borgbase.com/install/macos/) (vorta and osxfuse).
3. Install the new package `borgbackup-fuse`.

Thanks a lot for you support. 😊 💪

**Comment by m3nu** [comment]
Agreed. A documenation update is needed for both Borg and Vorta.

Vorta also doesn't depend on a particular Homebrew Borg any more. The user needs to decide which version to choose.

**Comment by m3nu** [comment]
[Docs for Vorta](https://vorta.borgbase.com/install/macos/) are already update. So closing this issue.

**Comment by vihuvac** [comment]
Great! Thanks a lot guys!
