### ISSUE TITLE
Add definitions to labels

### ISSUE THREAD

**Issue by samuel-w** [borgbase/vorta#736]
Currently all the labels have no descriptions. This make it confusing what they mean. For example, what is the difference between "low", "medium" and "high" priorities?

**Comment by m3nu** [comment]
Labels where?

**Comment by Golddouble** [comment]
the labels of guithub

**Comment by m3nu** [comment]
Ah. True. I can add that.

**Comment by samuel-w** [comment]
Primarily my issue is what each priority means, because all the issues seem to be tagged low priority.

**Comment by m3nu** [comment]
I see 17 out of 111 issues tagged low prio. It's not defined really, but you can make a suggestions and we add it as description.

My definition of "low prio" would be that it's not important to the majority of users or the applications functionality.

**Comment by samuel-w** [comment]
I view it like this:
High: Security issue or something that will typically to block workflow such as program not starting or crashing in common usage, such as crashing on backup start.
Medium: Something that is common or likely to block workflow but has a workaround.
Low: Something that is inconvenient/cosmetic that has an easy workaround, or an issue that is not likely to happen.

Found some useful links:
http://blog.lookfar.com/blog/2017/02/09/priority-and-severity-how-to-classify-and-approach-product-issues/
https://confluence.atlassian.com/adminjiraserver/defining-priority-field-values-938847101.html
https://www.drupal.org/docs/develop/issues/fields-and-other-parts-of-an-issue/issue-priority-field

**Comment by m3nu** [comment]
Yeah, sounds sensible.

**Comment by samuel-w** [comment]
I think we can take these definitions: https://github.com/google/tie/wiki/Issue-Priority-Definitions and convert it into:

- low: Nice to have feature
- medium: Non-critical improvement to functionality or usability
- high: Critical to security, functionality or usability (Cannot function or hard to use without)

**Comment by m3nu** [comment]
[Added](https://github.com/borgbase/vorta/labels) the descriptions.

> Whats the different between idea and planning?

I see it as project management cycle:

1. have an idea and discuss if it's useful
2. plan the implementation, UI, etc
3. code/implement it
4. ready to merge, review
5. merge

**Comment by samuel-w** [comment]
Also, we need to add package:ppa and package:native labels.

**Comment by m3nu** [comment]
Labels are mostly updated.
