### ISSUE TITLE
Feature request: add user friendly support for system restoring (not only personal data)

### ISSUE THREAD

**Issue by Golddouble** [borgbase/vorta#739]
**Is your feature request related to a problem? Please describe.**
I can not use Vorta, when I want to restore my system (and not only my personal data), because of problems with rights and because we can not restore a running system. 

So for this the only alternative that I know, is to use timeshift. What is so good in timeshift?
When you want to restore an older state of your system you just can mark the snapshot of question. Then press the restore-button. -> **Now timeshift shuts down the system and restores the backup. After the system starts up again. The restored system boots and you are in your restored system again. All is easy and user friendly. No need for using a live system or doing anything very complex.** 

So when I like timeshift, why do I not use timeshift together with Vorta?

I always make my backups manually, because I use an external HDD for this. I can not create them automatically, because I always have to connect the external HDD first.
1. With Timeshift AND Vorta I would have to start always two backups in different programs each day. I prefer to start one backup in one program each day.
2. Timeshift takes much more place for an incremental backup on the HDD than Borg.
3. I also would have to backup the hidden folders in my home with timeshift, because we can not restore hidden folders with Vorta in a running system without destroying anything. But timeshift does not restore exactly the state of the backup. If new files are added to the "hidden file"s in "home" after the snapshot, they are simply retained too. That's not what I want.

**Describe the solution you'd like**
I think it is already possible to backup files from "/" with Vorta. But restore "/" is not supported through Vorta until now.
So please add the functionality of timeshift I have described above: _Now timeshift shuts down the system and restores the backup. After the system starts up again. The restored system boots and you are in your restored system again._

(Of course before Vorta starts the restoring process, there should be a possibility to check and uncheck folders that should be/not be restored. So that we can for example restore only "/" and some hidden folders of "home" and leave the other personal data untouched. (This is a feature, that I also miss in timeshift.))

I think, when you would add this feature, there will probably be no program far and wide that Vorta is not superior to.

**Comment by samuel-w** [comment]
This doesn't fall into the project scope. Vorta is more meant for backing up user data, and not the entire system. That is more suited to something like [borgmatic](https://github.com/witten/borgmatic) or command-line borg backup.

**Comment by Golddouble** [comment]
But Borgmtic is with command line without GUI. So nothing for me.

**Comment by m3nu** [comment]
Sadly this is difficult to do correctly with a GUI and often not necessary (no need to backup system files). So we focus on personal files mainly, as explained above.
