### ISSUE TITLE
system tray icon

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#74]
on ubuntu 18.04, the tray background is dark brown, so there is little contrast with the black vorta icon:

![screenshot from 2018-12-01 15-47-20](https://user-images.githubusercontent.com/356103/49329514-7279bd00-f580-11e8-96eb-1643847c3d1c.png)

of course, everybody uses different themes / colours, so no idea how to solve this in a general way without looking ugly.

note: as github seems to enlarge small images, the screenshot does not look as bad as the real tray.

**Comment by m3nu** [comment]
<img width="720" alt="screenshot 2018-12-02 at 14 47 39" src="https://user-images.githubusercontent.com/3916435/49336669-e334de00-f641-11e8-8f0c-158d8357cb60.png">

Added light icon for dark themes. Can be selected in **Settings** tab.
