### ISSUE TITLE
'Contributing' documentation error

### ISSUE THREAD

**Issue by aromanelli** [borgbase/vorta#743]
**Describe the bug**
The 'Working on the GUI' section of the '[Contributing](https://vorta.borgbase.com/contributing/)' documentation web page has instructions that does not work.
Specifically, the "brew cask install qt-creator" instruction does not work, and returns a "Cask 'qt-creator' is unavailable: No Cask with this name exists." error.

**To Reproduce**
1. Open a terminal window.
2. Run '**brew cask install qt-creator**' (without quotes) at the command prompt.
3. Observe warning and error returned ...
```
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
Error: Cask 'qt-creator' is unavailable: No Cask with this name exists.
```

**Desktop (please complete the following information):**
- OS: Fedora 33 Workstation
-

**Comment by samuel-w** [comment]
You're on Fedora, which has an rpm package for it https://src.fedoraproject.org/rpms/qt-creator. 
If you want to use cask run `brew install --cask qt-creator`

We should update the docs so it uses repology https://repology.org/project/qtcreator/versions rather than cask.

**Comment by aromanelli** [comment]
@samuel-w I tried your suggestion for using brew, and got the same not available error ...

[adrian@xxx ~]$ **brew install --cask qt-creator**
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
aida-header                muffet                     trec_eval
==> Updated Formulae
Updated 65 formulae.

**Error: Cask 'qt-creator' is unavailable: No Cask with this name exists.**
[adrian@xxx ~]$

**Comment by samuel-w** [comment]
`sudo dnf install qt5-devel`
