### ISSUE TITLE
Icon style mismatch on MacOS Big Sur

### ISSUE THREAD

**Issue by LukeWheeldon** [borgbase/vorta#746]
The Vorta top tray icon is looking rather obnoxious (see screenshot).

An icon that follow the Apple design would be great, ideal if it works both in day and night mode.

Happy to attempt to find some help through Gitcoin if @m3nu wishes me to.

Screenshot:
<img width="461" alt="Screenshot 2020-12-23 at 13 21 38" src="https://user-images.githubusercontent.com/61089799/103000223-8820fd00-4522-11eb-8d60-cf47ff4b1c6f.png">

**Comment by m3nu** [comment]
We use **one** icon that works for dark/light themes and multiple desktop envs.

**Comment by LukeWheeldon** [comment]
Thanks for clarifying. If you change your mind I'm happy to fund the work on a neat MacOS icon.

It might not seem like much but it makes the app look more legit. It evidently is already legit for those who are looking for other, more important aspects. But for less initiated people, it makes a difference. And I believe Vorta/Borg should be used by a lot more people, so anything that can help adoption, I see it as good.
