### ISSUE TITLE
Unable to add an existing repository if the passphrase is empty

### ISSUE THREAD

**Issue by sandrotosi** [borgbase/vorta#747]
Hello,
using vorta/0.7.1 i am unable to add an existing repository that was created with an empty passphrase. the initialization command is:

```
$ borgmatic init -e repokey
/backup/borg is not a valid repository. Check repo config.
Enter new passphrase: 
Enter same passphrase again: 
Do you want your passphrase to be displayed for verification? [yN]:
```

(i used `borgmatic` but that doesnt really matter here) and when asked for a passphrase i left that empty.

when i try to add that repo in vorta, by using the Current profile > Repository > Repository > Add existing repository, i add the correct location in Repository URL and leave empty Borg passphrase, but i get an `unable to add your repository" message in the popup window, and in the main window i can read "ERROR: passphrase supplied in BORG_PASSPHRASE, by BORG_PASSCOMMAND or via BORG_PASSPHRASE_FD is incorrect."

I selected this as a bug report instead of a feature request because I believe vorta is not currently supporting a valid configuration.

Thanks,
Sandro

**Comment by sandrotosi** [comment]
@m3nu i see you added the status not-reproducible tag: is there anything you want me to check on my system on why this does happen here?

**Comment by samuel-w** [comment]
You didn't fill out the template:

**Desktop (please complete the following information):**
- OS:
- Vorta version:
- Installed from:

**Comment by sandrotosi** [comment]
OS: Debian unstable
Vorta version: 0.7.1
Installed from: Debian package

**Comment by samuel-w** [comment]
Managed to reproduce it
`borg init test-repo -e repokey`
Try to add repo, fails because there is the filler password 999999
https://github.com/borgbase/vorta/blob/3112a111f7a63ac814c7ec5f36e0796a3edece02/src/vorta/borg/info.py#L44

**Comment by sandrotosi** [comment]
thanks @samuel-w i can confirm with your change i can add the existing archive with empty passphrase to vorta.

What i see now, or actually dont see, are some information about the backup: in details, Size and Duration columns in the Archive tab are empty

**Comment by samuel-w** [comment]
The values are only calculated and saved when making a backup in Vorta, if you make a backup in borg command line Vorta doesn't track that. Also, the size and duration values are deleted when removing a repository. This is by design, see https://github.com/borgbase/vorta/issues/245.
