### ISSUE TITLE
add vorta version somewhere

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#75]
e.g. some "About..." entry in the tray menu or in the settings window title, like "Vorta 0.5.1".

an "About" menu entry could also link to the docs on the web.

**Comment by m3nu** [comment]
Added to the new settings tab.

**Comment by m3nu** [comment]
The documentation is already linked in some places. Users are probably more likely to click it, if they need info on that precise setting in that moment.

Some extra text could be added in the settings tab as well. Not sure what makes sense yet.
