### ISSUE TITLE
Released Vorta RPM package on Fedora Copr

### ISSUE THREAD

**Issue by luminoso** [borgbase/vorta#750]
Hi!

I've worked on vorta **rpm** packaging for Fedora, EPEL (and friends), OpenSuse, Mageia and CentOS >= 7
Also for multiple arches: i586, aarch64, x86-64 and s390x.

The build system is supported by Fedora Copr.

I've also created a brief project summary for the copr project based on the vorta's README.md 

Project page: https://copr.fedorainfracloud.org/coprs/luminoso/vorta/

Can anyone please clarify if these next steps are possible?

1. Enable Github release web hook so that a new release triggers automatically a new build
2. Update documentation

Potentially closes #331

**Comment by m3nu** [comment]
Good job! No problem with 1 and 2. What do you need in detail?

**Comment by luminoso** [comment]
To activate a github webhook, that triggers a new build when there's a new github release.

The webhook as a secret API key, can we communicate privately?
Or else anyone can trigger a new build :)

I'm at Matrix vorta channel: @luminoso:kde.org

**Comment by luminoso** [comment]
@m3nu can we move this forward? Are you a member of Vorta's Matrix channel?

**Comment by m3nu** [comment]
Definitely! Assigned myself and will do the testing and docs update.

Not on Matrix for now, but will check it out.

**Comment by m3nu** [comment]
Thanks for adding this! Looks good. Will try to set up a Fedora VM for testing.

In the meanwhile, I added the new repo to the docs: https://vorta.borgbase.com/install/linux/#rpm-based-packages

For updates, just add a PR against the [docs repo](https://github.com/borgbase/vorta.borgbase.com).

**Comment by luminoso** [comment]
We're missing the webhook that triggers a new rpm package automatically when a new version is released on github

How can I contact you privately? 

If makes sense, I'm on Matrix Vorta's channel and this is my handle: https://matrix.to/#/@luminoso:kde.org

**Comment by m3nu** [comment]
I don't have Matrix set up yet, but should.

Until then, just drop me an email to hello at borgbase.com. Thanks!

**Comment by jonathanunderwood** [comment]
@luminoso any plans to submit this to Fedora proper? It would be fantastic to have this in the official repository.

**Comment by luminoso** [comment]
Is there any special limitation on using Copr?

I didn't even thought on that possibility. I guess that the support/requirements for it to be tight. I'll check it out.

**Comment by topazus** [comment]
grateful for your work

**Comment by verchalent** [comment]
This package is still linked on the Vota page, but seems to no longer exist.

**Comment by luminoso** [comment]
That is right. That's because there's now an official Fedora package for vorta

**Comment by verchalent** [comment]
Sorry, I was not clear in my comment. The package no longer existing makes sense. My issue is that the install instructions still point to the deprecated package.

**Comment by m3nu** [comment]
Which part of the install instructions is wrong? The EPEL package is link there, no?

https://vorta.borgbase.com/install/linux/#enterprise-linux-and-derivatives-rpm

**Comment by m3nu** [comment]
The COPR package should be removed?

**Comment by verchalent** [comment]
Yes. For Fedora it should be "dnf install vorta"
