### ISSUE TITLE
I can't add a folder

### ISSUE THREAD

**Issue by Toadfield** [borgbase/vorta#754]
**Describe the bug**
If I go to "Sources>Add Folder" or "Repository>Initialize new Repository and add a folder" then if I click on a folder and select "open" nothing happens

**Desktop (please complete the following information):**
- OS:Manjaro
- Vorta version:0.7.1-5
- Installed from:Github

**Additional context**
[vorta.log](https://github.com/borgbase/vorta/files/5791834/vorta.log)

**Comment by aardbol** [comment]
I can confirm. Happens on multiple machines. Desktop environment: KDE Plasma.

**Comment by samuel-w** [comment]
Is it version 5.20.x?

**Comment by plaidmanthorny** [comment]
I'm having this problem as well. KDE Neon with Plasma 5.20.5.

**Comment by samuel-w** [comment]
This is a duplicate of https://github.com/borgbase/vorta/issues/693. Closing.
