### ISSUE TITLE
Being able to set a max size for backups on a profile

### ISSUE THREAD

**Issue by Toadfield** [borgbase/vorta#755]
What I want is being able to set the max size the backups folder can reach until they are full.
And that you can set,that after the folder reached max,that the oldest backups get deleted
That would be handy,so that the folders don't get too big.

**Comment by m3nu** [comment]
Already implemented in Borg (as param `--storage-quota`) and also [BorgBase.com](https://www.borgbase.com) (as per-repo quotas) in the dashboard.

**Comment by Toadfield** [comment]
So does it not work with the gui,but only with the cli?

**Comment by samuel-w** [comment]
If its set in the CLI it will be followed, but there is no way to set it in the GUI.

**Comment by m3nu** [comment]
We could add it as setting in the repo creation dialog.

But it won't be followed for most remote repos (e.g. BorgBase) and may cause more confusion than clarity.

**Comment by samuel-w** [comment]
Its a `borg config` setting, and I think its so rare that its not worth adding in the UI.

**Comment by Toadfield** [comment]
But it would be very handy to have that feature in the gui

**Comment by m3nu** [comment]
It's easy to wish for a feature, but someone needs to maintain the code in the future, do updates, fix tests, etc. So we can only accommodate features that are beneficial for a large enough number of users. Else the team will be spread to thin over time. Thanks for understanding.

**Comment by Toadfield** [comment]
ok
