### ISSUE TITLE
Can't select multiple folders

### ISSUE THREAD

**Issue by sbaragnaus2** [borgbase/vorta#758]
**Describe the bug**
I can't add multiple sources directories at once (CTRL+left mouse button). I don't know what's wrong, because I can add multiple files add once. 
_If you had a drive with 100 folders and you have to add 70 folders it's a time consuming task._ 

**To Reproduce**
1. Go to 'sources' tab
2. Click on 'add folder'
4. See error: I can't select multiple folders

**Desktop (please complete the following information):**
- OS: Fedora 33 Kde spin (Plasma 5.20.5, Frameworks 5.78, Qt 5.15.2)
- Vorta version: 0.7.1
- Installed from: Flathub

This also happens on Solus Plasma with Vorta installed from Solus repository

**Additional context**
n/a

**Comment by samuel-w** [comment]
Unfortunately there is no way to do this, Qt supports selecting only one folder at a time. As an alternative, I'll modify the paste files/folders button so that you can copy many folders and press paste to input all of them.
