### ISSUE TITLE
fat binary for linux

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#76]
not sure what is contained in the macOS pyinstaller-made binary (does it include borg also?), but there could be a fat binary for linux also.

it might not be needed for all linux users (as some dists already package vorta), but neither all dists have it nor all dists are quickly taking new vorta releases.

**Comment by m3nu** [comment]
macOS also ships your fat `borg` binary, but it will prioritize an existing local binary if there is one.

Regarding Linux I looked into using [Snaps](https://snapcraft.io/) in #16. I'm not sure a fat binary is appropriate for a GUI application. It will also need an icon, application menu entry, etc. For macOS this can be added via pyinstaller. For Linux I'm not fully sure.

**Comment by ThomasWaldmann** [comment]
Well, as we already have a fat-binary building mechanism used for macOS, doing same (and not adding a totally different mechanism) for linux isn't that far fetched.

If the addtl. stuff for UI integration isn't supported for linux, users can deal with it manually.
