### ISSUE TITLE
difference between 0.7.1 ppa and flatpak

### ISSUE THREAD

**Issue by bastiencyr** [borgbase/vorta#760]
**Describe the bug**
Hello, first, thanks for this project. I was already using borgbackup and it is an awesome tool. A graphic interface is welcome (in particular for mounting/unmounting archive). 
I noticed some strange differences between 0.7.1 ppa and flatpak vorta. 

**To Reproduce**
First bug on ppa but not on flatpak :
1. Go on archive tab
2. Click on refresh 
3. All date are set to current date
This is a picture : 
ppa : 
![Capture d’écran du 2021-01-16 00-27-36](https://user-images.githubusercontent.com/63359575/104788238-14c18280-5792-11eb-8011-c2d154c22008.png)
flat : 
![Capture d’écran du 2021-01-16 00-31-14](https://user-images.githubusercontent.com/63359575/104788263-2efb6080-5792-11eb-9016-cb68a114336f.png)

Second "bug", it's not really a bug : 
1. Go to repository tab
2. Click on add a repository (from existing one or not)
3. Open File manager to select a folder repository 
4. The file manager is different between flat and ppa. The problem is that the file manager from ppa doesnt show device like HDD... For Linux beginners, it can be confusing to find your device in /media. 
(Dark theme works on ppa but not on flat)

**Desktop (please complete the following information):**
- OS: Linux Mint 20 LTS
- Vorta version: 0.7.1 
- Installed from: Flat and ppa

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

Bastien

**Comment by samuel-w** [comment]
Flatpak and native packages store their data in different locations,  flatpak is `~/.var/app/com.borgbase.Vorta/data/Vorta/`, native is '~/.local/share/Vorta/`. The reason flatpak and ppa look different is because flatpak cannot access your theme data, while the native one can.

**Comment by bastiencyr** [comment]
I dont think so. qt docs says that "By default, a platform-native file dialog will be used if the platform has one.". The file dialog opened with ppa version is not the file dialog system but the built in qt file dialog. (it is the file dialog from flat which is the native file dialog system...)

**Comment by samuel-w** [comment]
I'm using the PPA version, and the file selector works fine for me. Must be a configuration issue.

**Comment by samuel-w** [comment]
Actually, it seems to only happen in Cnnamon DE.

**Comment by samuel-w** [comment]
Cinnamon is GTK3 based, so its Qt support is not good. https://forum.qt.io/topic/78023/qt-applications-don-t-look-natie-linux-mint-18-1-cinnamon/7. The date issue should not happen, try clearing your settings.

**Comment by bastiencyr** [comment]
Hello @samuel-w , I changed my config in qt5 settings and chose gtk2 as standard dialog. Its working now ! I have the right dialog file manager and when I refresh archives, dates are the right dates. Thank you very much !

**Comment by samuel-w** [comment]
I'll update the docs to list your solution. Nice that your figured it out.
