### ISSUE TITLE
No matching distribution found for vorta

### ISSUE THREAD

**Issue by deuzene** [borgbase/vorta#77]
`pip install vorta` returns:

`Collecting vorta
  Could not find a version that satisfies the requirement vorta (from versions: )
No matching distribution found for vorta`

**Comment by m3nu** [comment]
Which OS is this? Currently it supports any Posix and macOS, as specified [here](https://github.com/borgbase/vorta/blob/master/setup.cfg#L12).

Borg (the tool that Vorta uses to do the work) doesn't support Windows, so we can't support it either.

An alternative on Windows 10 would be to install on the Linux subsystem, which is an Ubuntu. I didn't test it, but it could work.

The GUI would also work on Windows without issues. I've seen screenshots of it.

**Comment by deuzene** [comment]
Oh sorry! I tried on Fedora 28, where `borgbackup` went from Fedora repo.

**Comment by m3nu** [comment]
Just tried this on a Fedora 28 VPS. No issues. Command:

`pip3 install --user vorta`

**Comment by deuzene** [comment]
Ok it's works with `pip3`.
Thank you.

**Comment by m3nu** [comment]
I'll mention Python 3 in the README, since it wasn't clear enough. The pip error message isn't helpful either.

Thanks for testing and reporting. If you notice any other issue, just open a new issue here.

**Comment by MatejKovacic** [comment]
I am trying to install Vorta on Ubuntu 16.04 (yes, it is quite old):
`sudo -H pip3 install vorta`

and got this error:

```
Collecting vorta
  Could not find a version that satisfies the requirement vorta (from versions: )
No matching distribution found for vorta
```

**Comment by ThomasWaldmann** [comment]
@MatejKovacic do you have python 3.6? vorta does not work with older versions.

**Comment by m3nu** [comment]
Reminds me to provide some pre-built binaries for Ubuntu and others. #76

**Comment by MatejKovacic** [comment]
That would be great.

Meanwhile, I installed Python 3.6, linked it as default Python3, installed newer version of pip3... and installation did not work. So I decided to completely replace Python 3.5 with 3.6... and the whole system just went down... :-)

Now I am doing dist-upgrade. If successfull, vorta installing problems will vanish too. :)

**Comment by ThomasWaldmann** [comment]
@MatejKovacic just as a note for "next time":

if you install some python additionally to the system python, put it into /usr/local/bin and do not name it python, python2 or python3, but keep it as python3.6 only. alternatively, use pyenv.

That way, you won't have interference with system python.

**Comment by MatejKovacic** [comment]
Okeeey, after upgrade there is another problem:

`sudo -H pip3 install vorta`

```
Collecting vorta
Installing collected packages: vorta
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 179, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 393, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 57, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 913, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 445, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/wheel.py", line 428, in move_wheel_files
    assert info_dir, "%s .dist-info directory not found" % req
AssertionError: vorta .dist-info directory not found
```

**Comment by MatejKovacic** [comment]
pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

python3 -V
Python 3.6.7

cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

**Comment by ThomasWaldmann** [comment]
Try:
- clearing pip cache
- pip3 install --no-use-wheel vorta


On April 6, 2019 8:13:09 AM GMT+02:00, Matej Kovacic <notifications@github.com> wrote:
>Okeeey, after upgrade there is another problem:
>
>`sudo -H pip3 install vorta`
>
>```
>Collecting vorta
>Installing collected packages: vorta
>Exception:
>Traceback (most recent call last):
>File
>"/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py",
>line 179, in main
>    status = self.run(options, args)
>File
>"/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py",
>line 393, in run
>    use_user_site=options.use_user_site,
>File
>"/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py",
>line 57, in install_given_reqs
>    **kwargs
>File
>"/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py",
>line 913, in install
>    use_user_site=use_user_site, pycompile=pycompile,
>File
>"/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py",
>line 445, in move_wheel_files
>    warn_script_location=warn_script_location,
>File "/usr/local/lib/python3.6/dist-packages/pip/_internal/wheel.py",
>line 428, in move_wheel_files
>    assert info_dir, "%s .dist-info directory not found" % req
>AssertionError: vorta .dist-info directory not found
>```
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/borgbase/vorta/issues/77#issuecomment-480477917

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MatejKovacic** [comment]
```
rm -r ~/.cache/pip
sudo -H pip3 install vorta --no-binary :all:
```

```
...
Collecting pyqt5 (from vorta)
  Could not find a version that satisfies the requirement pyqt5 (from vorta) (from versions: )
No matching distribution found for pyqt5 (from vorta)
```

**Comment by m3nu** [comment]
Is this an ARM or i386 system by any chance? PyQT may not have a pre-compiled package for that arch.

**Comment by MatejKovacic** [comment]
I tried `sudo apt install python3-pyqt5`, but with no success. However, I found out that PyQt5 is available only with pre-built binaries (wheels); there are no sources available. So I run: `sudo -H pip3 install pyqt5`.

After that:
`
Command "/usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-0bauw_v8/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel "cffi>=1.1; python_implementation != 'PyPy'"" failed with error code 1 in None`

**Comment by m3nu** [comment]
From what I remember, you'll need a rather old PyQt version on an old Ubuntu due to some dependency. I had an issue like this with Travis a while back. That's why you can't install it.

If you're on an exotic architecture there may not be a binary package at all. So the only option will be to compile it yourself. (both, Qt and PyQt)

**Comment by ThomasWaldmann** [comment]
@m3nu he said he upgraded to 18.04, that is relatively new and latest available version with long-term support (next one will be 20.04 next year).

**Comment by ThomasWaldmann** [comment]
@MatejKovacic latest python3 in 18.04 is 3.6.5, why do you have 3.6.7 (maybe there is still interference of the python you installed manually)?

https://packages.ubuntu.com/bionic/python3

**Comment by m3nu** [comment]
Right. I over-read the update part. I think he did a dist-upgrade and the old stuff (problems) are still there. What I'd look into next:

- Why did `$ apt install python3-pyqt5` fail?
- Are the usual dev-packages installed (build-essential libssl-dev libffi-dev python-dev). This may make `pip3 install pyqt5` fail. Checking their docs may help.

**Comment by ThomasWaldmann** [comment]
https://packages.ubuntu.com/bionic-updates/python3 < 3.6.7 from there, so it seems ok, ignore my last comment.

**Comment by mitchd123** [comment]
Sorry I didn't originally see the requirement on minimum version of python.  For newbies such as myself,  here's a nice guide to upgrading python.  https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/
