### ISSUE TITLE
macOS 0.7.2 Release Candidate - Testers wanted

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#770]
This is the first release built via [Github Actions](https://github.com/borgbase/vorta/actions/runs/495513152) and based on [Borg Backup's new dir-style release](https://github.com/borgbackup/borg/releases) (thanks to @ThomasWaldmann). So it should be somewhat reproducible and consistent.

The only change I make locally is to sign and notarize it. Details are [here](https://vorta.borgbase.com/contributing/packaging/#macos-application-bundle). You can also make your own macOS build from some other branch you are currently testing.

Download link: https://files.qmax.us/vorta/Vorta-0.7.2-RC2-notarized.dmg

This was tested on macOS Mojave and Big Sur. It's also [reported](https://github.com/borgbase/vorta/issues/727) to work on M1 silicon.

If you need `mount` support, please see [here](https://vorta.borgbase.com/install/macos/) on how to use Borg's new Homebrew Tap provided by @sunknudsen.

Also a shoutout to @samuel-w for contributing most of the features and fixes for this release.

**Comment by LukeWheeldon** [comment]
Working on 11.1 M1, thank you @m3nu.

**Comment by m3nu** [comment]
New version is now out. Thanks to everyone who contributed and tested.

https://github.com/borgbase/vorta/releases/tag/v0.7.2
