### ISSUE TITLE
Wrong size reported on folder

### ISSUE THREAD

**Issue by bhlevca** [borgbase/vorta#773]
**Describe the bug**
When attaching one folder the calculation of the size is wrong
It is possible that the errow show is dues to a very large number of  files.
However `du -h .` gives the right size

![Vorta_Screenshot](https://user-images.githubusercontent.com/182494/105531217-f9390900-5cb6-11eb-842d-7847b9b914cd.png)

**To Reproduce**
Select a directory that sits on a partition (in my case /home/bogdan )
Vorta shows `32 TB` while `du -shc -- {.[!.],..?,}*` gives `827G    total`
Need to mention that the entire disk has 6 TB and the partition is only 4 TB

**Desktop (please complete the following information):**
- OS: Linux OpenSuse Tumbleweed
- Vorta version: latest from  git although in the Misc tab is shown 0.71 
- Installed from: git and compiled
- Borg version 1.1.14  form the opensuse repo

Vorta and Borg versions can be found in Main Window > Misc Tab

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
[vorta.log](https://github.com/borgbase/vorta/files/5857942/vorta.log)

I am curios if taking  snapshot would be possible in such conditions and what causes this wrong reporting.
It may be a borg related issue

**Comment by m3nu** [comment]
Hi, thanks for reporting this. We use Python, rather than `du` to get the folder size. It's slower but has better portability.

I'm seeing some permission errors in your log. Maybe some of the folders you mentioned aren't accessible to the user running Vorta?

Apart from that we could log such errors. We may silently ignore them right now.

**Comment by bhlevca** [comment]
I found the problem. There was a cache file created by the search tool `recoll`.  Although its size was of only 6 GB it was reporting 32  TB!  including `ls -hl `, but not the `du `  Very strange. Obviously,  only `du ` gave the right size as  the entire HD is only  6 TB 
Very strange thing that `recoll` does. It uses the `xapian` libraries.  I will report that problem to them. Sorry for the false alarm, although you may want to rely on `du` reporting from `Python` as well.
