### ISSUE TITLE
Vorta freezes

### ISSUE THREAD

**Issue by carobinario** [borgbase/vorta#775]
**Describe the bug**
I upgraded from Vorta 0.7.1 to Vorta 0.7.2 (Flatpak). If I click on "add repository", "add folder" or "add files" the app freezes and **I had to kill it manually.** Don't know what happened: Vorta 0.7.1 had serious bug with file picker that was fixed (as stated in https://github.com/borgbase/vorta/issues/693). Don't know it's fixed or not: this new version is unusable.

Please let me know how can help you testing this useful software (maybe a Flatpak beta version?) but please, don't publish extremely buggy software. Thanks.

**To Reproduce**
_Please read above._

**Desktop (please complete the following information):**
- OS: Operating System: Fedora 33, KDE Plasma Version: 5.20.5, KDE Frameworks Version: 5.78.0, Qt Version: 5.15.2, Kernel Version: 5.10.10-200.fc33.x86_64, OS Type: 64-bit, Processors: 4 × Intel® Core™ i5-6600 CPU @ 3.30GHz, Memory: 15.3 GiB of RAM Graphics Processor: Mesa Intel® HD Graphics 530
- Vorta version: 0.7.2
- Installed from: Flathub

**Additional context**
Log: 
2021-01-31 18:51:50,616 - apscheduler.scheduler - INFO - Scheduler started
2021-01-31 18:51:50,802 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-01-31 18:51:50,861 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version

**Comment by samuel-w** [comment]
Testing on KDE Neon:
pip: No error
flatpak: Error

**Comment by thatso** [comment]
As already said in #693: I've upgraded to Vorta 0.7.2 Flatpack and still have the file picker freeze in KDE.

**Comment by samuel-w** [comment]
Yes, this is a different bug. As stated above, this is confined to only flatpak, whereas the previous one affected all packages.

**Comment by carobinario** [comment]
Hi, thanks you for fixing this bug. Can we expect a Vorta 0.7.2.1 version with this patch applied or we have to wait for Vorta 0.7.3 planned for April 30th?

**Comment by samuel-w** [comment]
Found a workaround: Disable the "Get statistics of file/folder when added" in the Misc tab.

**Comment by thatso** [comment]
I did `flatpak update` followed by `flatpak uninstall --unused` resulting in:

```
flatpak list

Description                                                                Application                                Version       Branch       Arch         Origin        Installation
Vorta - Backup client                                                      com.borgbase.Vorta                         v0.7.2        stable       x86_64       flathub       system
default                                                                    org.freedesktop.Platform.GL.default                      20.08        x86_64       flathub       system
Intel                                                                      org.freedesktop.Platform.VAAPI.Intel                     20.08        x86_64       flathub       system
openh264 - OpenH264 Video Codec provided by Cisco Systems, Inc.            org.freedesktop.Platform.openh264          2.1.0         2.0          x86_64       flathub       system
Breeze Gtk theme - Breeze Gtk theme matching the KDE Breeze theme          org.gtk.Gtk3theme.Breeze-Dark                            3.22         x86_64       flathub       system
KDE Application Platform - Shared libraries used by KDE applications       org.kde.Platform                                         5.15         x86_64       flathub       system
```
However, the file picker still freezes.
