### ISSUE TITLE
backup scheduling stops working after sleep on macOS

### ISSUE THREAD

**Issue by chriswep** [borgbase/vorta#777]
When i put macOS to sleep (every night for me), after wakeup no backups are run anymore by the scheduler. I have to close and re-open Vorta for the scheduler to work again.

**Desktop:**
- OS: macOS 10.15.7
- Vorta version: 0.7.1, Borg 1.1.13

**Additional context**
There is nothing in the logs, indicating that the scheduler is triggering nothing.

**Comment by m3nu** [comment]
I can confirm this issue on macOS 11. Seems to happen after a longer hibernation.

Since we are using an external package for scheduling, I'll need to check with them first.

**Comment by m3nu** [comment]
Since the code isn't very complex and the library we use, apscheduler, may drop Qt support in their latest version, we should just directly use Qt here.

https://doc.qt.io/qt-5/qtimer.html#interval-prop

**Comment by m3nu** [comment]
App Nap is also interfering with scheduled backups. Been testing this the whole day and it just missed some backups until I opened (wake up) the app.

https://stackoverflow.com/questions/22773570/disable-app-nap-for-ruby-on-mavericks

**Comment by m3nu** [comment]
I believe this is solved by disabling App Nap mainly and adding a timer to restore jobs periodically. The latter may only be needed for extreme cases.

<img src="https://user-images.githubusercontent.com/3916435/106682925-7e4ce800-65fe-11eb-8b7a-46fcec8b675f.jpg" width=200 />

Here a test build for you, @chriswep : https://github.com/m3nu/vorta/actions/runs/530771289 (Not signed, so do *right-click > Open*)

I'll merge it once you verified it solves your issue.

**Comment by chriswep** [comment]
thanks @m3nu i can tell you tomorrow if it works.

with this build i get a dialog "Auto-update not configured - For security reasons, Vorta needs to be code-signed or its updates need to be signed with an EdDSA key. See https://sparkle-project.org/documentation/ for more information." on every start. i guess this is due to the missing signing.

**Comment by m3nu** [comment]
Yeah. That's just the missing signing/notarization.

Looking forward to your feedback after testing.

**Comment by chriswep** [comment]
@m3nu the schedule was successfully triggered today after a good nights sleep!

i'm getting regular (hourly?) desktop notifications now from vorta, something like the schedule having been updated. i guess this is for debugging purposes, so it should be disabled for the release.

while we are at it (don't want to bother you with a new issue, just want to put it out there, maybe it's an easy thing to add while you are looking into scheduler code anyway): it would be great if a schedule could also be set in multiple days, not only hours. i would expect this to be a common use-case. E.g. the option "Backup daily at ..." could be changed to "Backup every ... days at ..." with 1 being the default (which wouldn't change the current default behaviour).

Thanks!

**Comment by m3nu** [comment]
Right. We can remove this notification, since we refresh the scheduler more often now.

Regarding the different time options, we already have an open PR for this, which is scheduled for the next release. #551
