### ISSUE TITLE
Uncaught exception while deleting an archive

### ISSUE THREAD

**Issue by rblenis** [borgbase/vorta#781]
the following error popped up while deleting an archive. The only things that sticks out to me is that I had the archive list sorted by name when this happened.

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/vorta/views/archive_tab.py", line 442, in delete_result
    deleted_row = self.archiveTable.findItems(self.archive_name, QtCore.Qt.MatchExactly)[0].row()
IndexError: list index out of range

**Comment by m3nu** [comment]
I can reproduce this, but only *after* sorting by name *and* deleting some other repo first.

I assume the list gets out of sync somehow.

**Comment by rblenis** [comment]
If the cause is from the sorting, then perhaps the correct fix is the one I submitted a PR for correctly sorting (#784).

**Comment by m3nu** [comment]
Yeah.  I think your PR fixes both issues. Will wait for Samuel to review the PR as well before merging.

**Comment by m3nu** [comment]
Merged #784 . Can't trigger the issue any more.
