### ISSUE TITLE
Sorted archive list gets corrupted on refresh

### ISSUE THREAD

**Issue by rblenis** [borgbase/vorta#783]
**Describe the bug**
Sorting the archive list will result in corrupted list after it is refreshed.

**To Reproduce**
1. Sort the archive list by clicking on one of the columns, such as 'Name'.
2.  Then refresh the list by clicking delete, prune or refresh buttons.
3. The updated list will be corrupt.
4. 
![Screenshot from 2021-02-06 11-29-06](https://user-images.githubusercontent.com/10763518/107123964-a93d7300-686e-11eb-8dbc-d74d8160d4ba.png)

**Desktop (please complete the following information):**
- OS: linux (Ubuntu 20.10)
- Vorta version: 0.7.2 (borg 1.1.15)

- Installed from: Ubuntu "Software" app (flatpak)

**Comment by m3nu** [comment]
Seems to be the same as #781, which also edits the table. At least your PR fixes that as well. 👍

**Comment by m3nu** [comment]
Closing this, since #784 seems to fix it too.
