### ISSUE TITLE
Invalid repos get saved

### ISSUE THREAD

**Issue by schwma** [borgbase/vorta#87]
Is it possible to specify the ssh port of the remote borg host in Vorta? I tried to specify the following URI format: `ssh://user@host:port/path/to/repo` as described in the [borg backup docs ](https://borgbackup.readthedocs.io/en/stable/man_intro.html?highlight=port#repository-urls), but nothing seems to happen after "Validating existing repo..." in the "Connect to existing Repository" dialog.

**Comment by schwma** [comment]
Apparently the `ssh://user@host:port/path/to/repo` entries are added to the Repository drop down list and backing up to those entries works. The "Connect to existing Repository" dialog just isn't closed after pressing "Add".

But unfortunately invalid repositories also appear in the dropdown after restarting Vorta.

Steps to reproduce:
1. Open Vorta settings and select "Add Existing Repository"
2. Enter "invalidrepo" as the Repository URL
3. Press "Add"
4. Press "Cancel"
5. Exit and reopen Vorta
6. "invalidrepo" now appears in the Repository dropdown menu

**Comment by m3nu** [comment]
Thanks for the good report. They should only be added after successful validation.

**Comment by ThomasWaldmann** [comment]
the repo url is a beast. maybe just take it and let borg validate it?

**Comment by m3nu** [comment]
That's how it works already. I don't do anything with the URL except saving it and passing it on.

Not sure why it's saved before validation. Should be a small issue somewhere.

**Comment by m3nu** [comment]
Fixed and improved the whole dialog a bit.
