### ISSUE TITLE
Update Homebrew formula to v0.7.3

### ISSUE THREAD

**Issue by s2d3** [borgbase/vorta#870]
Homebrew formula still installs v0.7.2: https://formulae.brew.sh/api/cask/vorta.json

v0.7.3 is now available.

**Comment by m3nu** [comment]
Hi, this is a different repo. You can open a PR against Homebrew Cask or wait for them to update it.

Repo: https://github.com/Homebrew/homebrew-cask

**Comment by m3nu** [comment]
PR to update: https://github.com/Homebrew/homebrew-cask/pull/100075

**Comment by m3nu** [comment]
0.7.3 is now available via Homebrew Cask.
