### ISSUE TITLE
Extract does not handle filename/paths with CR/LF characters in them.

### ISSUE THREAD

**Issue by rblenis** [borgbase/vorta#883]
If you backup files with a CR or LF in the name or path, then performing a diff or extract will not correctly show a directory tree of the files.  The CR/LF can cause the later portion of the filename to be interpreted as another file, etc.  The problem needs to be addressed in borg first, since it does not support json output mode for the related commands, so it's probably impossible to properly parse all legal filenames until json mode is supported in these commands.

- OS: linux (Ubuntu 20.10
- Vorta version: 0.7.2
- Installed from: 1.1.15

**Comment by m3nu** [comment]
Closely related to #226

**Comment by rblenis** [comment]
Should this issue be split in 2, since at least the archive list/extract portion can be/is fixed with support of the --json-lines option? borg will need a similar option for diff command.

**Comment by m3nu** [comment]
Yes, let's do list/extract first.

**Comment by rblenis** [comment]
I've submitted a PR for borg to add json-lines output for diff, so I'll start a PR here for supporting that feature once it's accepted

**Comment by rblenis** [comment]
I split off the 'diff' portion of this issue. The new issue is #901.

**Comment by m3nu** [comment]
Thanks! Will test this, after taking care of the KWallet issue that still comes up.

**Comment by m3nu** [comment]
Merged #885
