### ISSUE TITLE
Unhandled Exception on Create Remote Repository Failure [macOS Mojave]

### ISSUE THREAD

**Issue by TwistedBlizzard** [borgbase/vorta#886]
**Describe the bug**
Vorta encounters an unhandled exception and opens a dialogue box with the traceback when it fails to create a remote repository for any reason when running on macOS Mojave. I've tested both the version from Homebrew and the binary provided on GitHub.

**To Reproduce**
1. Try to create a new repository without having the repository directory available, for example. (This also happens if the server does not have the correct SSH key)
2. The repository is not created and the dialogue box appears.

**Expected Behavior**
Error is displayed in the main window, possibly with a helpful pointer about what may be done to resolve the information.

**Environment (please complete the following information):**
- OS: macOS Mojave
- Vorta version: 0.7.3
- Borg version: 1.1.15
- Installed from: Homebrew

**Traceback**
`Traceback (most recent call last):
  File "views/repo_add_dialog.py", line 114, in run
  File "borg/init.py", line 19, in prepare
  File "borg/borg_thread.py", line 131, in prepare
AttributeError: 'Repo' object has no attribute 'is_remote_repo'`

**Comment by m3nu** [comment]
Hi and thanks for reporting this. I wasn't able to reproduce this. Neither using "Init New Repo" or "Add Existing Repo" cause an error when entering an address without valid SSH key.

Do you have any more details?

**Comment by c-93** [comment]
Environment (please complete the following information):

    OS: Current Manjaro KDE
    Vorta version: 0.7.3
    Borg version: 1.1.14
    Installed from: yay and pacman

Same error here: After having an incompatibility/ issue with the password manager, vorta suggested to unlink and re-add the backup-repository. I did the above steps to re-add the existing repo.

`Uncaught exception [...] Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/vorta/views/repo_add_dialog.py", line 211, in run
    params = BorgInfoThread.prepare(self.values)
  File "/usr/lib/python3.9/site-packages/vorta/borg/info.py", line 24, in prepare
    ret = super().prepare(profile)
  File "/usr/lib/python3.9/site-packages/vorta/borg/borg_thread.py", line 131, in prepare
    if profile.ssh_key is not None and profile.repo.is_remote_repo() and \
AttributeError: 'Repo' object has no attribute 'is_remote_repo'`

**Comment by m3nu** [comment]
Thanks for the reports, @c-93 and @TwistedBlizzard . I see that a new (unimportant) verification is causing this error. The solution is to just remove a few lines here https://github.com/borgbase/vorta/pull/887/files

Please confirm this fixes the issue and I'll merge it right away. To test via Pip:

`$ pip install --force-reinstall git+https://github.com/m3nu/vorta.git@issue/886/repo-attr-error`

**Comment by c-93** [comment]
Thanks for your solution! This works for me. :)
