### ISSUE TITLE
Borg 0.7.3 kdewallet error

### ISSUE THREAD

**Issue by cooch007** [borgbase/vorta#888]
**Describe the bug**
upgrading to v 0.7.3 produces error on launch "error when attempting to decrypt the wallet kdewallet using gpg.  If you are using a smartcard, please ensure its inserted & try again.  GPG error was no secret key"
"please unlock your password manager"

previous version of vorta runs correctly with no issue.  

I do not / have not ever used kdewallet

**To Reproduce**
1. launch vorta
2. start a backup that you have saved in your profile

**Environment (please complete the following information):**
- OS: ubuntu 18.04.5
- Vorta version:.0.7.3
- Installed from:flathub

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.
previous version of logs shows this  vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
this version shows vorta.borg.borg_thread - DEBUG - Using VortaKWallet5Keyring keyring to store passwords.

**Comment by m3nu** [comment]
If you have both, KWallet and SS installed, it will use KWallet first. There were some changes in selecting this recently, which may not be optimal. https://github.com/borgbase/vorta/blame/master/src/vorta/keyring/abc.py

If you don't use KWallet, why not uninstall it?

Also see the existing discussion in #859, so closing this one until we have a concrete solution to implement.
