### ISSUE TITLE
Certain password characters appear to break things

### ISSUE THREAD

**Issue by strmd** [borgbase/vorta#89]
Using Vorta 0.60 on macOS, I both initialized and added an existing local repo with some non-ASCII characters in the passphrase, specifically å, ä and ö.

After the configuration is complete, every subsequent Vorta operation fails with an `ERROR - passphrase supplied in BORG_PASSPHRASE or by BORG_PASSCOMMAND is incorrect` when it decidedly is not. Relinking doesn't work, when pressing the Add button nothing happens, as long as the troublesome character is in the password. With an all-ASCII password, behavior is as expected.

**Comment by ThomasWaldmann** [comment]
either a encoding or unicode normalization issue.
this is why borg outputs a hex dump of the passphrase bytes if it is not ascii.

**Comment by m3nu** [comment]
Fixed. A classic unicode-issue. Encoded strings are longer than decoded ones. Also added a test for it.
