### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#892]
Hi,
I have Swedish translation ready to go, if you want.
Please let me know where to upload, Transifex or Github is ok both, for me.

While testing I also found some missing/not working translation strings, seen in these dumps.

![screen_20210225-073513](https://user-images.githubusercontent.com/2996154/109116574-12fbbf00-7741-11eb-84e7-9e99c11c9f12.png)
![screen_20210225-074112](https://user-images.githubusercontent.com/2996154/109116601-1a22cd00-7741-11eb-9ecc-79cd2e98ed77.png)
![screen_20210225-074955](https://user-images.githubusercontent.com/2996154/109116614-1ee78100-7741-11eb-9de3-dd4b9f1f8af3.png)

_Originally posted by @eson57 in https://github.com/borgbase/vorta/discussions/891_

**Comment by eson57** [comment]
I found one more during today's backup...
![screen_20210226-072846](https://user-images.githubusercontent.com/2996154/109263965-7f8bc200-7804-11eb-8cc1-719c41e41a7c.png)

**Comment by samuel-w** [comment]
The default profile name is set before qt starts, so that can't be translated.

**Comment by m3nu** [comment]
Fixed by @samuel-w. Thanks for reporting, @eson57 . The new strings are already on Transifex.
