### ISSUE TITLE
Vorta 0.7.3 unbrauchbar geworden: nach dem Upgrade Vorta von 0.7.1 auf 0.7.3 crasht Vorta beim "unlock your keymanager"

### ISSUE THREAD

**Issue by Wikinaut** [borgbase/vorta#893]
![grafik](https://user-images.githubusercontent.com/1151915/109153592-65eb6b80-776d-11eb-81d3-e8075eea9b4e.png)

ich wähle ersten Punkt.

Dann crasht Vorta mit

![grafik](https://user-images.githubusercontent.com/1151915/109153676-7f8cb300-776d-11eb-8864-51607c2b9f0f.png)

Mein Keymanager ist der systemweite von Linux Mint, der heißt wohl seahorse. Dort sind Schlüssel unter anderem von meinem Nextcloud-Programm.

Erbitte Hilfe.

System:
* Linux Mint 20.1, fully upgraded.
* Borgbackup 1.1.15

**Comment by Wikinaut** [comment]
Als Workaround habe ich erstmal gedowngraded per

```pip install -U --no-cache-dir vorta==0.7.1```

**Comment by m3nu** [comment]
Please join the existing discussion regarding this issue at #859.

And try the current `master` branch with a possible fix, as mentioned here: https://github.com/borgbase/vorta/discussions/859#discussioncomment-401271

**Comment by Wikinaut** [comment]
@m3nu thanks so far. Will wait until new release.
