### ISSUE TITLE
Uncaught exception related to the selection of a key for Vorta in kdewallet

### ISSUE THREAD

**Issue by remym19** [borgbase/vorta#897]
**Describe the bug**
When I started a backup for the first time since I last updated Vorta, I got a window prompt from the key manager asking me to select a key in kdewallet for Vorta usage.
With that window still opened and untouched, I unmounted the local disk where the repository of the backup was located.
This raised an uncaught exception which is detailed below.

**To Reproduce**
1. Select a local backup to an external disk.
2. Mount the partition of the backup's repository.
3. Click on start the backup, in my case that made the key manager ask to select a key for Vorta.
4. Don't touch the key manager window and unmount the external partition, in my case this triggered an uncaught exception.

**Environment:**
- OS: Linux Mint 20 Cinnamon (Cinnamon 4.6.7, Linux Kernel 5.4.0-66-generic)
- Vorta version: 0.7.3-0ubuntuppa2 (Borg 1.1.15)
- Installed from: apt-get or mintinstall
- Pyhton version: 3.8.2-0ubuntu2

**Additional context**
> Uncaught exception, please file a report with this text at
> https://github.com/borgbase/vorta/issues/new
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/vorta/application.py", line 109, in create_backup_action
>     msg = BorgCreateThread.prepare(profile)
>   File "/usr/lib/python3/dist-packages/vorta/borg/create.py", line 71, in prepare
>     ret = super().prepare(profile)
>   File "/usr/lib/python3/dist-packages/vorta/borg/borg_thread.py", line 144, in prepare
>     ret['password'] = cls.keyring.get_password('vorta-repo', profile.repo.url)
>   File "/usr/lib/python3/dist-packages/vorta/keyring/kwallet.py", line 30, in get_password
>     if not (self.is_unlocked and self.get_result("hasEntry",
>   File "/usr/lib/python3/dist-packages/vorta/keyring/kwallet.py", line 45, in is_unlocked
>     return self.handle > 0
> AttributeError: 'VortaKWallet5Keyring' object has no attribute 'handle'

[vorta.log](https://github.com/borgbase/vorta/files/6051420/vorta.log)

**Comment by m3nu** [comment]
KWallet still broken, @samuel-w . `self.handle` is never set if an error happens in `try_unlock()`, so this is expected:

https://github.com/borgbase/vorta/blame/master/src/vorta/keyring/kwallet.py

**Comment by m3nu** [comment]
Due to the many bugs with this and the fact that some Linux users simply don't want to use a provided keychain, I'm making this an optional setting:

https://github.com/borgbase/vorta/pull/898

**Comment by m3nu** [comment]
Added a fix for this in #899. So you have 2 options @remym19 :

1. Use #898 to just not use KWallet
2. Use #899 and you will keep getting the "Keychain locked" error without exception.

**Comment by samuel-w** [comment]
Just going to remove kwallet at this point.

**Comment by remym19** [comment]
Ok, thanks for the fix and for the option in the misc tab.
