### ISSUE TITLE
Installation on Linux

### ISSUE THREAD

**Issue by andsvb2** [borgbase/vorta#9]
Hi.
I couldn't get Vorta installed through the pip method.
My system is a Manjaro Linux, kernel 4.19.1-1, and I have Borg and its dependencies installed.
I attached a file with the output of command `$ pip install vorta`. The message of error is `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9f2cc75a/pyobjc-framework-Cocoa/`.
[vorta.log](https://github.com/borgbase/vorta/files/2564401/vorta.log)

**Comment by m3nu** [comment]
Simple. I need to make the Objective-C imports conditional, as they only apply on macOS.

Sorry about that. Will push a fix in 0.3.1

**Comment by m3nu** [comment]
Updated and tested on Ubuntu 18. Seems to work now. :-) Just missing the system tray. (maybe missing a distro package)

<img width="1277" alt="screenshot 2018-11-09 at 14 05 59" src="https://user-images.githubusercontent.com/3916435/48246009-9ede6580-e428-11e8-850e-372c1688ebb9.png">

Let me know if it works for you. Leaving it open for now.

**Comment by andsvb2** [comment]
After the update I had encountered errors related to python packages missing on my system. I've installed them in the same order that the messages appeared.

The packages were installed in this order:

* Repo
1. python-ply
1. python-pycparser
1. python-cffi
1. python-asn1crypto
1. python-bcrypt
1. python-cryptography
1. python-pyasn1
1. python-pynacl
1. python-paramiko
1. python-peewee
1. python-jeepney
1. python-entrypoints
1. python-secretstorage
1. python-keyring
1. python-pytz
1. python-tzlocal
* AUR
1. python-apscheduler
 * REPO
1. python-certifi
1. python-raven
* AUR
1. python-sentry_sdk

Now I'm faced with another error. The log of the command `$ pip install vorta` is attached.

The error message displayed is `Command "/usr/bin/python -u -c "import setuptools, 
[vorta.log](https://github.com/borgbase/vorta/files/2566542/vorta.log)
tokenize;__file__='/tmp/pip-install-pzszort3/vorta/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-iybtm3ht/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-pzszort3/vorta/`.

Is it necessary to install with the `-- user` option?

**Comment by andsvb2** [comment]
I've successfully installed with the command `$ pip install --user vorta`.

**Comment by JanSchnacki** [comment]
I could now install version 0.3.2 on Kubuntu 18.10, too. Thanks!

**Comment by m3nu** [comment]
Yeah. All the dependencies are added. I installed on a fresh Ubuntu earlier this afternoon. Do either:

- `pip install vorta` – to install from Pypi
- `pip install -e .` – to install from the cloned git repo. Pip will first pull any dependencies.

The `--user` option is good when using the system Python without a virtualenv. If you plan on doing development, a virtualenv is recommended.

**Comment by m3nu** [comment]
There are just too many ways to install Python packages. When one installs with the user-option he may need to updates his `PATH` as well. Better keep it general, like most projects.

**Comment by m3nu** [comment]
In the medium-run I want to package Vorta+Borg together so it  can be used together. But I'm not sure what's the best way to do that yet. Suggestions welcome.
