### ISSUE TITLE
'VortaKWallet5Keyring' object has no attribute 'handle'

### ISSUE THREAD

**Issue by IJRepin** [borgbase/vorta#903]
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/vorta/application.py", line 115, in create_backup_action
    msg = BorgCreateThread.prepare(profile)
  File "/app/lib/python3.8/site-packages/vorta/borg/create.py", line 71, in prepare
    ret = super().prepare(profile)
  File "/app/lib/python3.8/site-packages/vorta/borg/borg_thread.py", line 138, in prepare
    ret['password'] = cls.keyring.get_password('vorta-repo', profile.repo.url)
  File "/app/lib/python3.8/site-packages/vorta/keyring/kwallet.py", line 30, in get_password
    if not (self.is_unlocked and self.get_result("hasEntry",
  File "/app/lib/python3.8/site-packages/vorta/keyring/kwallet.py", line 45, in is_unlocked
    return self.handle > 0
AttributeError: 'VortaKWallet5Keyring' object has no attribute 'handle'

**Comment by IJRepin** [comment]
Vorta seems to automatically select the kwallet keyring after the last update, but I want to select gnome's keyring (Seahorse) instead. Is there a way to switch that?

**Comment by m3nu** [comment]
> Vorta seems to automatically select the kwallet keyring after the last update, but I want to select gnome's keyring (Seahorse) instead. Is there a way to switch that?

There is a PR to disable the system keychain completely. You can help us test it here: https://github.com/borgbase/vorta/pull/898

> `AttributeError: 'VortaKWallet5Keyring' object has no attribute 'handle'`

Thanks for taking the time to report this. This issue is already resolved via #899 and was originally reported in #897. Please help us by testing the current Github version as described [here](https://github.com/borgbase/vorta/discussions/895) to ensure a bug-free release.

**Comment by IJRepin** [comment]
> > Vorta seems to automatically select the kwallet keyring after the last update, but I want to select gnome's keyring (Seahorse) instead. Is there a way to switch that?
> 
> There is a PR to disable the system keychain completely. You can help us test it here: #898
> 
> > `AttributeError: 'VortaKWallet5Keyring' object has no attribute 'handle'`
> 
> Thanks for taking the time to report this. This issue is already resolved via #899 and was originally reported in #897. Please help us by testing the current Github version as described [here](https://github.com/borgbase/vorta/discussions/895) to ensure a bug-free release.

Thx!
