### ISSUE TITLE
empty files don't show size in extract dialog, and are sorted incorectly.

### ISSUE THREAD

**Issue by rblenis** [borgbase/vorta#915]
1. create an archive with some empty files (size==0)
2. select archive and click 'extract'
3. expand tree view to see files
4. notice that empty files are sorted at the top (with directories), and size field is blank

- OS: Ubuntu 20.10
- Vorta version: 0.7.5
- Installed from: snap

**Comment by m3nu** [comment]
Interesting. Will try to reproduce this.

**Comment by m3nu** [comment]
Was able to reproduce this as well. Empty files end up on top of folders.

I believe they should show up with 0B together with other files.

![Screen Shot 2021-04-09 at 11 38 53 PM](https://user-images.githubusercontent.com/3916435/114205410-dac8dc80-998c-11eb-9b5c-965f8db6c33c.jpg)
