### ISSUE TITLE
pip installation fails if qtpy is missing

### ISSUE THREAD

**Issue by SkaveRat** [borgbase/vorta#917]
Currenty using a completely fresh install of xubuntu 20.04.

After installing vorta via `pip`, I get the following error message:

```
$ .local/bin/vorta 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

I fixed it by installing `python3-qtpy`. Is it possible to add this as a dependency to the installation process, or at least a note?

**Comment by m3nu** [comment]
PyQt5's packaging changed slightly in February. They ship compiled binaries in a separate package (`PyQt5-Qt` on PyPi) now. Maybe that's what you are seeing?

The mentioned `python3-qtpy` shouldn't be needed, but it may install soemthing else. I'd try `python3-pyqt5` first.

You can also review the deps of the official Debian package: https://packages.debian.org/sid/vorta

**Comment by SkaveRat** [comment]
Okay, I've uninstalled qtpy and re-installed pyqt5 afterwards, and vorta still works. Just installing pyqt5 as a dependency seems to work

**Comment by m3nu** [comment]
Closing this since it seems solved.
