### ISSUE TITLE
Show error when trying to delete the last profile

### ISSUE THREAD

**Issue by rugk** [borgbase/vorta#918]
**Describe the bug**

**To Reproduce**
1. Create a new profile at the top, the only/first one.
2. Click on the delete button.

What happens: Nothing.
What should happen: Either show an error or just delete the profile.

**Environment (please complete the following information):**
- OS: Fedora 33
- Vorta version: v0.7.5
- Installed from: Flathub

**Additional context**
nothing speical logged

**Comment by m3nu** [comment]
The last profile is never deleted, but there is no error message currently. We could probably add that.

**Comment by jzacsh** [comment]
> What should happen: Either show an error or just delete the profile.

Same. Specifically I was expecting this to just get me back to the starting state of the first time I used the app (a clean slate).
