### ISSUE TITLE
Vorta language is German although my Mac is set up to run in English

### ISSUE THREAD

**Issue by maxhgerlach** [borgbase/vorta#919]
**Describe the bug**

The system language is set to English primarily, although the region is set to Germany. Vorta displays all UI text in German instead of English and there is no obvious way to change that. Please see the screenshots below.

The logfile (also attached) contains this related line:
```
2021-03-10 17:33:36,666 - vorta.i18n - DEBUG - Loading translation succeeded for ['en-US', 'en-DE', 'de-DE', 'de'].
```

**Environment (please complete the following information):**
- OS: macOS 10.15.7
- Vorta version: 0.7.5
- Installed from: `brew install --cask vorta`

**Additional context**

[vorta.log](https://github.com/borgbase/vorta/files/6117600/vorta.log)

![Screen Shot 2021-03-10 at 17 57 21](https://user-images.githubusercontent.com/1778667/110667015-1fb0f600-81ca-11eb-9edc-767f4414b54a.png)

![Screen Shot 2021-03-10 at 17 58 18](https://user-images.githubusercontent.com/1778667/110667133-3f481e80-81ca-11eb-9a51-4e5fd6e13f6c.png)

**Comment by m3nu** [comment]
Couldn't reproduce this, but we had some issues with Qt language selection [before](https://github.com/borgbase/vorta/issues/623). Maybe remove the second redundant English language setting?

![Screenshot 2021-03-11 at 09 00 14](https://user-images.githubusercontent.com/3916435/110720141-0d29d180-8249-11eb-8f29-2c9975524f94.jpg)

**Comment by maxhgerlach** [comment]
> Maybe remove the second redundant English language setting?

That did the trick! Thanks for the tip. Quite a weird bug.
