### ISSUE TITLE
vorta screencast

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#92]
I am preparing a lightning talk for 35c3 (and I hope I get a slot assigned).

If that works out, I intend to show some slides and the borg and vorta screencasts (as time permits, only have 5 minutes max. for all).

So, if you could have the screencast up-to-date at 2018-12-29, that would be super cool. :)

Also, maybe slow it down a little bit. Currently it is going a bit too fast if one has never seen vorta before, IMHO.

Note: currently frontpage shows "build failing".

**Comment by m3nu** [comment]
Sounds good. Glad to help with that. I'll make a slower video and export it as proper video file.

Travis sometimes fails tests due to timeouts. The default of 1 second is not enough. Probably some VM-neighbors running high-CPU tests at the same time. I don't want to add a higher timeout to all tests and still look for a way to change the default.

**Comment by m3nu** [comment]
Here a slightly slower screencast lasting 1:38 min. If you keep talking while playing it, the timing should be doable.

https://files.qmax.us/vorta/screencast-7.mp4

**Comment by rugk** [comment]
AFAIK you can anyway only use PDFs as slides at 35C3 lightning talks. As such, as much as I'd like to see it, I guess it is hardly possible to embed a screencast in a PDF… :stuck_out_tongue_winking_eye:

**Comment by ThomasWaldmann** [comment]
@m3nu thanks for the slower screencast. not sure if time will permit for that length, but I'll see / try.
Can I rely on that URL being available until 31.12.2018?

@rugk yes, they say so, but a browser is also possible according to them.

**Comment by m3nu** [comment]
Yes. The URL will stay up.

The resolution of the video is high enough to pull out some screenshots, if needed. VLC does that nicely.
