### ISSUE TITLE
Backup stops working when deleting server from .ssh/known_hosts

### ISSUE THREAD

**Issue by rb2k** [borgbase/vorta#921]
**Describe the bug**
I cleared out my known_hosts file and noticed that vorta will error out for backups afterwards.
If you manually ssh to the host again, accept the host key ("yes") the backups work again.

I guess that makes sense, but it would be nice if vorta either asked (best option) or at least told me that that's the issue rather than a generic "is borg running over there?" message.

**To Reproduce**
1. remove entry for backup server from ~/.ssh/known_hosts
2. start backup
3. See it fail

**Environment (please complete the following information):**
- OS: macOS 10.15.7
- Vorta version: 0.7.5
- Installed from: the website (+ auto updates after)

**Comment by m3nu** [comment]
Already a planned feature we track under #714
