### ISSUE TITLE
Use ‘auto’ compression mode for zstd

### ISSUE THREAD

**Issue by erAck** [borgbase/vorta#924]
The UI limits the available compression settings to 6 picks, of which none offers the auto feature. Seen that the option is stored as argument string in settings.db I experimentally tried to change that to `auto,zstd` but that makes Vorta bail out on start with

```
Traceback (most recent call last):                                                                      
  File "/usr/lib/python3/dist-packages/peewee.py", line 2653, in execute_sql                            
    cursor.execute(sql, params or ())
sqlite3.IntegrityError: NOT NULL constraint failed: backupprofilemodel.compression                      

During handling of the above exception, another exception occurred:                                     

Traceback (most recent call last):                                                                      
  File "/usr/lib/python3/dist-packages/vorta/views/repo_tab.py", line 155, in compression_select_action 
    profile.save()                                                                                      
  File "/usr/lib/python3/dist-packages/peewee.py", line 5617, in save                                   
    rows = self.update(**field_dict).where(self._pk_expr()).execute()                                   
  File "/usr/lib/python3/dist-packages/peewee.py", line 1587, in inner                                  
    return method(self, database, *args, **kwargs)                                                      
  File "/usr/lib/python3/dist-packages/peewee.py", line 1658, in execute                                
    return self._execute(database)                                                                      
  File "/usr/lib/python3/dist-packages/peewee.py", line 2076, in _execute                               
    cursor = database.execute(self)                                                                     
  File "/usr/lib/python3/dist-packages/peewee.py", line 2666, in execute                                
    return self.execute_sql(sql, params, commit=commit)                                                 
  File "/usr/lib/python3/dist-packages/peewee.py", line 2660, in execute_sql                            
    self.commit()                                                                                       
  File "/usr/lib/python3/dist-packages/peewee.py", line 2451, in __exit__                               
    reraise(new_type, new_type(*exc_args), traceback)                                                   
  File "/usr/lib/python3/dist-packages/peewee.py", line 178, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/peewee.py", line 2653, in execute_sql
    cursor.execute(sql, params or ())
peewee.IntegrityError: NOT NULL constraint failed: backupprofilemodel.compression
```

**To Reproduce**
1. In Vorta create a profile with default settings.
2. Close Vorta.
3. Edit settings.db using sqlitebrowser.
4. Change table `backupprofile` column `compression` value from `lz4` to `auto,zstd`
5. Save change.
6. Close sqlitebrowser.
7. Start Vorta => failure.
(the error message "NOT NULL constraint failed: backupprofilemodel.compression" is a tad misleading..).
8. Change value back to `lz4` or `zstd,3` and all good.

**Environment**
- OS: Debian 10.8 (buster)
- Vorta version: 0.7.1
- Installed from: Debian package buster-backports vorta-0.7.1-4~bpo10+1
- The same happens for version 0.7.5 flatpak

**Expectation**
I'd expect that Vorta accepts the changed argument, making the list box entry simply display the argument value if no predefined UI string is available for the selection. At least not crash..

**Comment by m3nu** [comment]
Looks like you deleted the value instead of changing it? Hence the `NOT NULL constraint failed`.

The compression algos were selected by the current Borg maintainer. They include `auto` settings for older algos, where they make sense. You can view the source code and extensive comments here: https://github.com/borgbase/vorta/blob/master/src/vorta/views/repo_tab.py#L36

**Comment by m3nu** [comment]
Also: Even after correctly changing the value in the DB, the UI may fail, since it can't find the long version of those settings. So I wouldn't recommend such edits.

**Comment by erAck** [comment]
> Looks like you deleted the value instead of changing it? Hence the `NOT NULL constraint failed`.

No, there definitely was the `auto,zstd` value in the compression field (which is why I called the exception message misleading), and still there when invoking sqlitebrowser a second time after the Vorta crash, and changing it back to `lz4` (or another predefined value) made Vorta work again.

However, I do understand that fiddling with the database that way is unexpected by Vorta. I just liked to use auto,zstd because of lots of already compressed media files (jpeg,mp4) and using the modern zstd algorithm for files that are not. Guess I'll fall back to using zstd,3 then.

**Comment by m3nu** [comment]
According to Thomas, the `auto` option is only needed for older algos. Did you run a test to see if it has an impact? If yes, we could add it.

**Comment by erAck** [comment]
I did a test using Borg 1.1.15 with a small subset of ~1500 files, mostly jpeg, 6.65GB original size, a few exclude patterns for a realistic scenario, from hard disk to SSD to keep disk write overhead low, 3 runs each:

auto,zstd
compressed 6.64GB  deduplicated 6.10GB
2m45s average

zstd
compressed 6.63GB  deduplicated 6.09GB
2m59s average

So auto,zstd was slightly (8%) faster and zstd only compresses a few bits more. YMMV.. No idea how that scales with 1TB of data.

**Comment by m3nu** [comment]
Interesting. Pretty similar, as expected.

Do you still have the numbers for each run? Just to know the rough standard deviations and confidence intervals. If Stds are high, then the difference may be non-significant.

**Comment by erAck** [comment]
No individual numbers anymore, but I can do a few runs over the weekend.

**Comment by erAck** [comment]
Same scenario as above, apparently from LVM hotspot cache, 6 runs each:

auto,zstd:
Duration: 2 minutes 35.99 seconds
Duration: 2 minutes 32.94 seconds
Duration: 2 minutes 30.99 seconds
Duration: 2 minutes 32.10 seconds
Duration: 2 minutes 29.32 seconds
Duration: 2 minutes 30.29 seconds

zstd:
Duration: 2 minutes 46.76 seconds
Duration: 2 minutes 48.37 seconds
Duration: 2 minutes 49.56 seconds
Duration: 2 minutes 45.77 seconds
Duration: 2 minutes 48.71 seconds
Duration: 2 minutes 46.85 seconds

**Comment by m3nu** [comment]
Thanks for testing! Looks like there isn't much variability here and `auto` is indeed a few seconds faster consistently.

Next question is if the difference is large enough to change to `auto,zstd`. Any other downside when using `auto` for `zstd`, @ThomasWaldmann ?

**Comment by ThomasWaldmann** [comment]
Maybe do the same test also with some other data sets. The outcome might be depend on the kind of data.

In general, one can of course use `auto,zstd`. There was just the general assumption (or I read it somewhere, don't remember), that zstd copes better with precompressed data than older algorithms, so `auto` might not be that useful.

**Comment by m3nu** [comment]
Agreed. A dataset with mixed data will probably show no difference.

And if the user has a repo full of images or videos, *no compression* should be used.

Migrating those settings would be non-backwards compatible as well and lead to the same crashes OP has seen, when an older Vorta version is used. So I'd rather avoid that unless the benefit is really large.
