### ISSUE TITLE
elevator pitch vs. trying to say it all

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#93]
some note about the project's front page (README as shown on github):

i'ld suggest considering this as your elevator pitch: you have 1 minute to convince someone vorta is what they want. putting a lot of stuff into it might have some tl;dr effect and thus i think it should be avoided.

so:
- README == elevator pitch  "what is it, why you really want it."
- doc chapters ==

  - intro (include ../README)
  - installation, usage, development, ...
  - license (include ../LICENSE)
  - authors (include ../AUTHORS).

**Comment by m3nu** [comment]
Fully agree that the README got too bloated. I simplified it a bit and moved the development stuff to its own file. Hope this improves things. Not sure about install instructions.

New version is here: https://github.com/m3nu/vorta/tree/v0.6.2

For now the volume of information is small enough to keep it in 2-3 files. Later I was planning on adding a simple landing page with download links and install instructions for users who are not used to browsing on Github.

**Comment by ThomasWaldmann** [comment]
Still too long IMHO, see my idea above. For docs, https://readthedocs.org is an option.

**Comment by m3nu** [comment]
Thought so. Moved *Installation* out as well and merged some items.

https://github.com/m3nu/vorta/tree/v0.6.2

Having proper docs is surely important for a complex CLI tool (Borg) or a library package, but GUI applications (and websites) are generally expected to explain themselves. So this should be the end goal if possible.

Currently I'm putting all articles on docs.borgbase.com, which may not be the best place to collect content on so many different projects. Once I have a better idea of what documentation is needed, I'll split it up. It's all written in Markdown anyways, so it will be quick to move.

Next steps should be a landing page for users who don't use Github and something like a quickstart guide, _if_ the UI fails to explain itself. Landing page could be like https://www.arqbackup.com/ with some subpages for install- and usage instructions.
