### ISSUE TITLE
error during add existing repository

### ISSUE THREAD

**Issue by FreeInMind** [borgbase/vorta#931]
Traceback (most recent call last):
  File "/home/xy/.local/lib/python3.8/site-packages/peewee.py", line 6884, in get
    return clone.execute(database)[0]
  File "/home/xy/.local/lib/python3.8/site-packages/peewee.py", line 4275, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xy/.local/lib/python3.8/site-packages/vorta/application.py", line 191, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/home/xy/.local/lib/python3.8/site-packages/peewee.py", line 6438, in get
    return sq.get()
  File "/home/xy/.local/lib/python3.8/site-packages/peewee.py", line 6887, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]

**Describe the bug**
Running a borg backup (without Vorta) and then trying to add this repository in Vorta (at the same time) produce the error above.

**Environment (please complete the following information):**
- OS: Linux Mint 20.1 Ulyssa
- Vorta version: 0.7.5 Borg Version: 1.1.15
- Installed from: flatpak

**Comment by m3nu** [comment]
Thanks for reporting, @FreeInMind. Would you mind using the bug report template, so we have all the details for your report here? Thanks!

**Comment by StuartMacKay** [comment]
You will get this error is there is an existing lock on the repository. Ignore the exception trace on the popup dialog, the actual error will be displayed at the bottom of the main window. In my case there was an existing lock on the repository. Removing it manually (no idea if this is safe or not) solved the problem.
```
cd .cache/borg/cdb17e5a46881f09b93614.../lock.exclusive/
rm host@1841384365247419.1224431-0 
```

**Comment by m3nu** [comment]
Ah. So the use case here is to add a repo to Vorta that is currently in use somewhere else?

We already support breaking the lock for existing repos in some cases, but breaking it for new repos is probably a bit risky. The better way is to make sure the repo isn't locked *before* adding it to Vorta.

**Comment by StuartMacKay** [comment]
This was an existing repo that only contains a backup of my laptop. Not sure how the lock got left lying around. I have scripts that run one per day but their scheduled time was nowhere close to the time when I encountered the lock.

**Comment by m3nu** [comment]
In recent versions, Borg usually breaks stale locks without user interaction. So it’s possible there was an active process around when you added the repo.
