### ISSUE TITLE
Infrequently used buttons in Source tab as icons instead of buttons

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#933]
Especially the paste and refresh sizes buttons aren't used very frequently. So suggest to use smaller buttons with icon for them. Same with "Remove".

![Screen Shot 2021-04-02 at 10 05 07 AM](https://user-images.githubusercontent.com/3916435/113372380-27178980-939b-11eb-8d62-576185554ed6.jpg)

Bonus: Use only one button for adding files/folders. Currently there are some Qt limitations that prevent this, but there could be a workaround.

**Comment by real-yfprojects** [comment]
May I simply add a *fontawesome* icon to the repo? I will need a icon for a minus sign.

**Comment by m3nu** [comment]
Yes, 3 icons: remove, paste, refresh

**Comment by real-yfprojects** [comment]
> Yes, 3 icons: remove, paste, refresh
 A clipboard icon for the paste action is a good idea.
