### ISSUE TITLE
Error when trying to enable start at login

### ISSUE THREAD

**Issue by Justinzobel** [borgbase/vorta#941]
**Describe the bug**
Error when trying to enable start at login in Misc tab

**To Reproduce**
1. Go to 'Misc tab'
2. Click on 'Automatically start at login'
3. See error

**Environment (please complete the following information):**
- OS: Solus 4.2
- Vorta version: 0.7.5
- Installed from: Solus Repository

**Error:**
```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/vorta/views/misc_tab.py", line 31, in <lambda>
    b.stateChanged.connect(lambda v, key=setting.key: self.save_setting(key, v))
  File "/usr/lib/python3.7/site-packages/vorta/views/misc_tab.py", line 40, in save_setting
    open_app_at_startup(new_value)
  File "/usr/lib/python3.7/site-packages/vorta/autostart.py", line 39, in open_app_at_startup
    with open(Path(__file__).parent / "assets/metadata/com.borgbase.Vorta.desktop") as desktop_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.7/site-packages/vorta/assets/metadata/com.borgbase.Vorta.desktop'
```

**Comment by Justinzobel** [comment]
After opening my eyes a bit more, I figured I'd dig, `/usr/lib/python3.7/site-packages/vorta/assets/` doesn't have a metadata folder in it.

**Comment by m3nu** [comment]
Maybe the Solus packaged didnt include those files. The linked maintainer will know.

**Comment by m3nu** [comment]
Closing this, since it's not related to this repo, but third party packaging. If anything can be improved with the autostart templates we ship with Vorta, feel free to comment again here.
