### ISSUE TITLE
Feature Request: Add a View Command Menu.

### ISSUE THREAD

**Issue by xLogiiCx** [borgbase/vorta#946]
Hello, it would be really nice to add a "View Command Menu" where the user can check what Borg command is running when using the GUI. 

It would be really helpful for Debugging and improving purposes.

**Comment by m3nu** [comment]
All commands are already printed in the logs. You find those linked in the *Misc* tab.

**Comment by m3nu** [comment]
I'll close this, since it's already implemented by logging each command to the log file. Some operations run multiple Borg commands, so there is no 1:1 mapping. If you're interested, just find them in the logs. I also use this for debugging.
