### ISSUE TITLE
Unable to read struct signalfd_siginfo: Bad file descriptor

### ISSUE THREAD

**Issue by smartm0use** [borgbase/vorta#948]
I'm getting the following error when mouting backups:

`Unable to read struct signalfd_siginfo: Bad file descriptor`

Anyway the backups is mounted successfully. But what does it mean that error? Is something bad?

- OS: Ubuntu 20.04
- Vorta version: 0.7.5
- Installed from: Flatpak

**Comment by m3nu** [comment]
Doesn't look like a Python exception.

**Comment by Hofer-Julian** [comment]
Indeed.
Something went wrong deeper in the stack when attempting to mount the repo
