### ISSUE TITLE
Error: Traceback - Archive failure.

### ISSUE THREAD

**Issue by sconnary32** [borgbase/vorta#949]
I was syncing a large directory and after a day I found it had ended with this error.
![image (1)](https://user-images.githubusercontent.com/28371598/114929140-445f4580-9de8-11eb-9daf-596fa9dc1804.png)

I restarted the sync and once it worked through the cache it failed again with the same output.
I moved onto a different backup set without issue so far.

**Comment by m3nu** [comment]
Please fill the full bug report template including steps to reproduce the issue and Vorta logs.

**Comment by sconnary32** [comment]
This is a Borg issue not Vorta.  I reinstalled Borg and so far have made it well past the current point where the blockage happened.
