### ISSUE TITLE
0.6.1 regression not going in background on start

### ISSUE THREAD

**Issue by mygithubthrowaway** [borgbase/vorta#95]
**Describe the bug**
Hi, the version 0.6.1 not start in background

**To Reproduce**
1. Start
2. No forking in background

**Desktop (please complete the following information):**
 - OS: Archlinux

**Additional context**
No log, error or warning

Another things: before the 0.6.1 version i set vorta in autostart(1,2) at system login and i don't see the gui, just the tray icon. With the 0.6.1 version i see the gui appears after login (gnome)

A option "start in tray icon" would be great!

sorry for my bad english

[1](https://specifications.freedesktop.org/autostart-spec/0.5/ar01s02.html)
[2](https://wiki.archlinux.org/index.php/XDG_Autostart)

**Comment by adamluk** [comment]
Thanks for reporting this. It has already been resolved, please see #91. It will be included in version 0.6.2 when it is released.

**Comment by m3nu** [comment]
Thanks for taking care, @adamluk . The fix is up for [review](https://github.com/borgbase/vorta/pull/97) at the moment. It's mostly changes to the README, so not urgent.

**Comment by m3nu** [comment]
Mini release: https://github.com/borgbase/vorta/releases

**Comment by m3nu** [comment]
Hope you also like the new README.
