### ISSUE TITLE
disk usage option

### ISSUE THREAD

**Issue by paulharris** [borgbase/vorta#950]
Suggestion: add an "actual disk usage" option in borg

When using borgbase.com , you can't run "ssh whatever@whatever du" (like you can with rsync.net - borgbase runs borgserver)
and the "borg info" command appears to only compute the archive size of the existing archives.

In append-only mode, the prune command leaves orphaned chunks behind, and these don't seem to be included in any of the numbers provided by "borg info"

So for example, I have a long-running backup on borgbase, using append-only and pruning to only about 10 recent backups.

If I run:
borg info
borg check --repair
borg info

The "borg info" outputs are identical,
but the disk usage on the web interface of borgbase.com show that the actual disk usage got dramatically smaller.

Would be great if there were "actual disk usage" and even "orphaned chunks disk usage" in the borg-info outputs, or perhaps in their own unique command.

Would be nice :)

**Comment by m3nu** [comment]
That's right. In append-only mode, Borg doesn't know about previous "transactions" until you adjust the transactions file to do a rollback.

For me a better way to deal with append-only would be to outright reject delete/prune commands. Unfortunately this will break existing tooling around Borg, so it's just an idea for now. https://feedback.borgbase.com/posts/28/reject-delete-and-prune-commands-for-append-only-repos

I also don't think the upstream Borg project is keen on adding this, since there are already other ways to look at the space usage. And for BorgBase you get it reported in the web UI or you could rsync the raw repo data and then size it, if you don't trust the UI. 😬

**Comment by paulharris** [comment]
I don't want to change the way borg does delete and prune, I think it works fine for now.
Perhaps it could warn that it doesn't reclaim space, that would help yourself.

But not-reclaiming-space is pretty standard in other situations, eg std::vector doesn't reclaim memory when you erase or resize - it is for efficiency in that case.

And append-only, well seems pretty obvious that it can't reclaim space.  How would that even be possible.

Instead, it would become clear that space isn't being reclaimed if it warned (but not so helpful) or was able to tell you how much space COULD have been reclaimed.

And one more note, I would assume it would actually be more efficient to avoid reclaiming after a prune.  eg if a large file was added to a backup, removed, and then reappeared later on, wouldn't that be an opportunity to reuse a previously-orphaned chunk?  So if you have a case of data reappearing, then a lot of work and uploading is skipped.   I see this happen with my dropbox, they obviously don't reclaim immediately, I am able to re-add large folders back into my dropbox a week or two later, and the upload time is near-zero.

**Comment by paulharris** [comment]
I should also mention that git also doesn't clear space (orphans) until you do a "git gc" (or the wasted space passes a threshold).

This is really good in git's situation, as accidental branch deletes can be recovered by a git-reflog or similar.  I've done that more than once.

It would perhaps be good for borg to add a specific command, like "borg show hidden transactions" or similar.  It would perhaps be able to list old transactions in old logs (that must still be written somewhere - append-mode), and then the user can specifically try and mount or check or recover that old transaction - then it would depend if its chunks did still exist, or had been cleared away.   Might still be useful for the user (in disaster-recover situations) to be able to load up a part transaction, even if it were to see the file metadata ie how files were laid out, to identify when super_important.txt was deleted.

**Comment by m3nu** [comment]
What you are asking for is more a Borg- than Vorta feature. Have you looked at upcoming features in Borg 1.2? There were some changes to compaction and such. Didn't look at the details, but may be what you mean.

**Comment by paulharris** [comment]
Ah bugger, yeah sorry the URL bar autocorrected to this borg repo and I didn't doublecheck.   I'll close this and move it to borg.
