### ISSUE TITLE
file dialog freezes

### ISSUE THREAD

**Issue by mutable-dan** [borgbase/vorta#958]
This seems to be an extension of:
https://github.com/borgbase/vorta/issues/221#issue-416751542

```
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.8.0-50-generic
OS Type: 64-bit
---------------
I am experiencing the same issues described above with the flatpack
I get around  adding the repo by entering file:///path
but if i try to add sources or mount a repo.  it freezes and i need to kill -15 it

thank you

```

**Comment by m3nu** [comment]
Please fill the full bug template to ensure we can quickly find a solution to the reported issue.

For this specific case: Does it also happen when running from `pip install vorta` or with the current `master` branch? (see [here](https://vorta.borgbase.com/contributing/#testing-the-current-development-version) on how to test the current `master` branch via `pip`.

**Comment by mutable-dan** [comment]
**Describe the bug**
Any file open dialogs freeze the app

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 
 repository, add exisitng repo
 archives, select one, mount


**Environment (please complete the following information):**
- OS:
- Vorta version:
- Installed from: flatpack

Vorta and Borg versions can be found in Main Window > Misc Tab.
vorta:0.7.5, borg: 1.1.15

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

regarding  pip: i do not use pip

**Comment by m3nu** [comment]
Possible duplicate of #962 ?

Could this be a flatpak sandboxing issue, @Hofer-Julian ?

**Comment by Hofer-Julian** [comment]
Hard to know, without checking pip.

**Comment by Hofer-Julian** [comment]
Ah, seems like someone else has a similar problem with qt, flatpak and kubuntu 20.04

https://github.com/flatpak/flatpak/issues/4186

**Comment by mutable-dan** [comment]
fixed in 0.7.7  
thank you

**Comment by mutable-dan** [comment]
hello
This bug is back.

flatpak but with  vorta ver  0.8.7

if I open a dialog, it locks the desktop and i think pings the cpu (because i hear the fan rev up)
The dialog I opened was the mount one in the  archives tab

thanks

**Comment by Hofer-Julian** [comment]
If you use Kubuntu 20.04, please upgrade to 22.04

**Comment by mutable-dan** [comment]
ok, thx
