### ISSUE TITLE
Customize base borg command to add additional options

### ISSUE THREAD

**Issue by soakes** [borgbase/vorta#96]
Hi,

I have been trying to setup Vorta with rsync.net, however it does work but its using the old 0.x server with a lot of errors in the log and I just hate errors :)

```
2018-12-17 20:25:38,670 - WARNING - Remote:
2018-12-17 20:25:38,670 - WARNING - Please note:
2018-12-17 20:25:38,670 - WARNING - If you see a TypeError complaining about the number of positional arguments
2018-12-17 20:25:38,670 - WARNING - given to open(), you can ignore it if it comes from a borg version < 1.0.7.
2018-12-17 20:25:38,670 - WARNING - This TypeError is a cosmetic side effect of the compatibility code borg
2018-12-17 20:25:38,671 - WARNING - clients >= 1.0.7 have to support older borg servers.
2018-12-17 20:25:38,671 - WARNING - This problem will go away as soon as the server has been upgraded to 1.0.7+.
```
In the welcome email, they state that the following:

> If you need to use borg 1.x we recommend running your command as follows:
> 
> borg COMMAND --remote-path=borg1 ...
> 
> No special options are required to run borg 0.x

I have been trying to figure away on how to do this with Vorta.  From what I can see there is no option in the client and so would you consider in adding this in the future? meanwhile I can get away with a scripted solution but would be nice to have a UI.

Kind Regards,

Simon

**Comment by ThomasWaldmann** [comment]
guess the whole (local) borg base command should be configurable and default to just `borg`.

**Comment by soakes** [comment]
That would be perfect.

**Comment by m3nu** [comment]
This would be done [here](https://github.com/borgbase/vorta/blob/master/src/vorta/borg/borg_thread.py#L119). Currently it looks for a global `borg` bin, then an embedded one (pyinstaller) and then fails.

**Comment by soakes** [comment]
This is awesome thank you.  Will give it a whirl.

**Comment by adamluk** [comment]
Would it be possible to have an explanation of how to utilise #109 with --remote-path=borg1 please?

**Comment by m3nu** [comment]
#109 is unrelated to this. If you want to specify additional CLI options (like `--remote-path`) it would be covered in this issue. Hoping to implement it soon. Of course PRs are also welcome by others.

**Comment by soakes** [comment]
Thank you guys.

**Comment by m3nu** [comment]
Hey @soakes, @adamluk , this feature was now implemented by @ethernet-zero in #193 . Please have a look if it works well for you. Then we can merge it.

**Comment by soakes** [comment]
Thanks everyone, seems to be working and great job once again.

**Comment by m3nu** [comment]
Great. Merged.
