### ISSUE TITLE
Select SSH key when adding a new repo

### ISSUE THREAD

**Issue by m3nu** [borgbase/vorta#960]
When adding a new repo that needs a custom SSH key, that's not possible yet. Not sure if the key selected in the same profile is used. Still not fully intuitive.

**Comment by camlafit** [comment]
Hello

I think my use case is related to this issue. If I'm wrong no problem to open a new issue :)
When we add an existing remote repository we can't specify ssh key to use, choice is limited to created a new key or use default key. I presume default use case is ~/.ssh/id_rsa path

But it could be wrong. When we manage many keys, we can have : 
* ~/.ssh/serverX[.pub]
* ~/.ssh/serverX/id_rsa[.pub]
* ~/serverX/.ssh/id_rsa[.pub]
* ...

We can have too many use case, should be better to propose only two options : 
* create a new ssh key and ask where to store
* provide an explorer and select specific key path to use

**Comment by m3nu** [comment]
Yes, it's a bit of a chicken-egg problem. Maybe we should move the SSH selection above the repo selection. I'm not looking to duplicate this inside the repo dialog.

**Comment by camlafit** [comment]
Hello

Ssh key selection could be related to each repository. In my part it looks normal to have to select ssh key when we define repository connection.

**Comment by real-yfprojects** [comment]
Is this still an issue? @m3nu

**Comment by m3nu** [comment]
Should be solved, since we added a key selection dropdown to the *Add Repo* dialog some time ago.

The "Quick Start Wizard" task could expand the *Add Repo* dialog to also generate the key, copy it and do some explaining.
