### ISSUE TITLE
Cannot add folders under /var/www

### ISSUE THREAD

**Issue by cspeare** [borgbase/vorta#962]
**Describe the bug**
Add Folder does not show www under /var, attempting to paste the path shows "Some of your sources are invalid: /var/www/myproject"

**To Reproduce**
1. Go to Source
2. Click on Past Folder/Files (after copying path to clipboard)
3. See error

**Environment (please complete the following information):**
- OS: Ubuntu 20.04 Desktop
- Vorta version: 0.7.5
- Installed from: Flakpak

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by m3nu** [comment]
Maybe a permission issue?

**Comment by cspeare** [comment]
Potentially however if I choose Add Folder I can navigate to / (which wouldn't be owned by my user), then navigate to /var which shows

```
  cache
  config
  data
  db
  run
  tmp
```

Interestingly if I do ls -ltr /var I get the following:

```
drwxrwsr-x  2 root staff    4096 Apr 15  2020 local
drwxr-xr-x  2 root root     4096 Feb  9 18:47 opt
drwxrwsr-x  2 root mail     4096 Feb  9 18:47 mail
drwxr-xr-x  7 root root     4096 Feb  9 18:50 spool
drwxrwsrwt  2 root whoopsie 4096 Feb  9 18:52 metrics
lrwxrwxrwx  1 root root        4 Apr 21 16:49 run -> /run
lrwxrwxrwx  1 root root        9 Apr 21 16:49 lock -> /run/lock
drwxr-xr-x 20 root root     4096 Apr 22 10:03 cache
drwxr-xr-x 10 root root     4096 Apr 22 10:59 snap
drwxrwsrwt  2 root whoopsie 4096 Apr 22 13:25 crash
drwxr-xr-x  2 root root     4096 Apr 25 10:53 backups
drwxrwxr-x 15 root syslog   4096 Apr 26 08:54 log
drwxr-xr-x  4 root root     4096 Apr 26 10:41 www
drwxr-xr-x 79 root root     4096 Apr 26 14:02 lib
drwxrwxrwt 15 root root     4096 Apr 26 14:39 tmp

```

So it seems to be able to select _some_ folders but not all of them - taking cache and www they seem to have the same permissions, but only cache is visible

**Comment by m3nu** [comment]
Same issue happens when installing via pip?

**Comment by cspeare** [comment]
Pip installation works fine - I just went for the flatpak as it was first (and some dislike of python as a language).  Thanks

**Comment by Hofer-Julian** [comment]
Yep, these directories are blacklisted for flatpaks:
"/lib, /lib32, /lib64, /bin, /sbin, /usr, /boot, /root, /tmp, /etc, /app, /run, /proc, /sys, /dev, /var"

If you have to access them with Vorta, you have to use another type of installation

**Comment by m3nu** [comment]
> Yep, these directories are blacklisted for flatpaks:
> "/lib, /lib32, /lib64, /bin, /sbin, /usr, /boot, /root, /tmp, /etc, /app, /run, /proc, /sys, /dev, /var"

Good to know. Might be worth adding to the docs, since we list Flatpak first.

**Comment by Hofer-Julian** [comment]
Good point

**Comment by m3nu** [comment]
I've linked to the Flatpak docs mentioning the restricted folders and sorted our install options from most generic to most specific. Pip is most widely available, then Flatpak, then distribution packages.

**Comment by Hofer-Julian** [comment]
@m3nu please don't put pip on the top again.
It might be the most general, but it is definitely the one which breaks the easiest and the one that integrates the worst with the DE. I feel that far too often if people ask for help on Matrix, pip is the reason.

**Comment by m3nu** [comment]
Haha. Alright. Then just adding the note on locked folders.

**Comment by Hofer-Julian** [comment]
Thank you! ☺️
