### ISSUE TITLE
Fatal Error: application.py

### ISSUE THREAD

**Issue by sconnary32** [borgbase/vorta#964]
Describe the bug
Get fatal error and vorta goes into "starting consistency check"  I have to restart Vorta to get past it.

Fatal Error: 
Traceback (most recent call last):
  File "/home/adminroot/.local/lib/python3.8/site-packages/vorta/application.py", line 202, in <lambda>
    msg.accepted.connect(lambda: self.break_lock(profile))
  File "/home/adminroot/.local/lib/python3.8/site-packages/vorta/application.py", line 218, in break_lock
    self.set_progress(params['message'])
AttributeError: 'VortaApp' object has no attribute 'set_progress'

To Reproduce

Start a sync and it might run into this.

OS: Ubuntu 20.04 Desktop
Vorta version: 0.7.5
Installed from: pip3
Borg: 1.1.16
Vorta and Borg versions can be found in Main Window > Misc Tab.

Additional context
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by m3nu** [comment]
Thanks for sharing. There was an obvious bug when setting the error message when breaking a lock. Would be very rare.

Basically your repo is locked (possibly used by another process) and then breaking that lock fails with some error. And after that informing you about this other error fails. 😄
