### ISSUE TITLE
Fatal Error when trying to add Existing Repository 

### ISSUE THREAD

**Issue by xLogiiCx** [borgbase/vorta#979]
**Describe the bug**
I am receiving an Fatal Error when trying to add my first Borg Repo to the Default Profile. 

**To Reproduce**
1. Go to Repository Site
2. Click on Add Existing Repository
3. Add Repo URL and Borg Pass
4. Click Add and wait
5. See error

**Environment (please complete the following information):**
- OS: Ubuntu 20.04.2 LTS x86_64
- Vorta version: 0.7.5
- Installed from: pip3
- Borg Version 1.1.15

Vorta and Borg versions can be found in Main Window > Misc Tab.

**Additional context**
Repository looks like this
`
ssh://user-xx@user.your-domain.com:23/./backup.borg
`

The Fatal Error:
```
Uncaught exception, please file a report with this text at
https://github.com/borgbase/vorta/issues/new
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/peewee.py", line 6884, in get
    return clone.execute(database)[0]
  File "/home/user/.local/lib/python3.8/site-packages/peewee.py", line 4275, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/vorta/application.py", line 191, in react_to_log
    profile = BackupProfileModel.get(name=context['profile_name'])
  File "/home/user/.local/lib/python3.8/site-packages/peewee.py", line 6438, in get
    return sq.get()
  File "/home/user/.local/lib/python3.8/site-packages/peewee.py", line 6887, in get
    raise self.model.DoesNotExist('%s instance matching query does '
vorta.models.BackupProfileModelDoesNotExist: <Model: BackupProfileModel> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."name", "t1"."added_at", "t1"."repo_id", "t1"."ssh_key", "t1"."compression", "t1"."exclude_patterns", "t1"."exclude_if_present", "t1"."schedule_mode", "t1"."schedule_interval_hours", "t1"."schedule_interval_minutes", "t1"."schedule_fixed_hour", "t1"."schedule_fixed_minute", "t1"."validation_on", "t1"."validation_weeks", "t1"."prune_on", "t1"."prune_hour", "t1"."prune_day", "t1"."prune_week", "t1"."prune_month", "t1"."prune_year", "t1"."prune_keep_within", "t1"."new_archive_name", "t1"."prune_prefix", "t1"."pre_backup_cmd", "t1"."post_backup_cmd", "t1"."dont_run_on_metered_networks" FROM "backupprofilemodel" AS "t1" WHERE ("t1"."name" = ?) LIMIT ? OFFSET ?
Params: ['New Repo', 1, 0]
```
If appropriate include logs. Can be found in Main Window > Misc Tab > Log.

**Comment by m3nu** [comment]
There was a bug when renaming a profile doesn't remove it from the dropdown list. In that case the wrong profile could be selected.

Does the issue still exist in the current `master` branch? Here is how to use the current master branch/development version: https://vorta.borgbase.com/contributing/#testing-the-current-development-version

**Comment by xLogiiCx** [comment]
Seems to be fixed in the current branch.

**Comment by real-yfprojects** [comment]
> Seems to be fixed in the current branch.

Now quite some time has past and it seems like the error didn't occur again. If this issue is resolved, please close it.
