### ISSUE TITLE
Vorta and system keychain

### ISSUE THREAD

**Issue by GitStorageOne** [borgbase/vorta#989]
Hi!

When vorta configured to run with schedule rules, each time when vorta trying to perform backup it requests access to wallet.  
Wallet designed to be locked most of the time, in order to secure data.  
It's impossible to enter password every hour.  
Once vorta accessed to keychain it should cache password for repository in process memory  
(probably encrypted with random session password).  

For example, when user open some SMB in Dolphin, it require access to wallet as well, after that, Dolphin does not ask password again until log off. Same with wifi password.

**Comment by m3nu** [comment]
You can avoid using the system keychain by disabling *Store password in system keychain if available* in the *Misc* tab.

It's also possible that the interface to your system keychain could be improved. If yes, PRs are always welcome. 🙏
