### ISSUE TITLE
i18n: translation, localisation (overview)

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbase/vorta#99]
recently showed borg at the local linux user group, it was well received, some people prefer gui to cli tools, so vorta is just what they waited for.

but, first question of one of the guys: "gibt's das auch auf Deutsch?" ("is this also available in German?") and i had to tell "no, not yet".

so, while i18n for borg is rather optional, because UNIX admins hacking stuff on the cli usually also speak English rather well, it's a different story for the target audience of vorta - we need i18n for them.

so, what needs to be done:
- (this ticket) code needs to prepared for i18n, qt style:

  - `vorta.i18n` package with some i18n infrastructure code
  - `self.tr('english phrase')` (scope comes from instance class name)
  - `app.translate('scope', 'english phrase')`
- #135 packaging
- #136 check original texts
- #137 infrastructure for translators, integration
- #138 i18n policy, see also #140
- #139 layout short vs. long texts / rtl languages
- #141 localisation
- UI needs to be as self-explaining as possible (because I guess we do not want to translate the docs also).
- I'ld advise to only add 1 language at first, get everything implemented / tested for that and only after that add more languages.

**Comment by m3nu** [comment]
Feared this would come up eventually. I know the process from large-scale website translations, I've organized in the past. Was always good fun.

I'll see if there are any blockers, like the Qt UI-files. Then start marking and extracting strings for translation.

**Comment by brokenpip3** [comment]
Sign me for Italian translation :+1:

**Comment by genma** [comment]
Count me in for French translation :+1:

**Comment by m3nu** [comment]
Thanks, already noted. Hehe.

**Comment by ThomasWaldmann** [comment]
I'll try doing some work on this. No experience yet with any qt-specific stuff related to this (if any).

**Comment by ThomasWaldmann** [comment]
First slight issue I've found is that py36+ f-strings are not really compatible with using a translation function.

**Comment by ThomasWaldmann** [comment]
https://doc.qt.io/qt-5/internationalization.html

**Comment by m3nu** [comment]
The QT C++ docs don't always fully apply to PyQt. For translations, the workflow seems roughly like this:

1. Extract translatable strings into `.ts` files using the `lupdate` command. Then compile them to `.qm` files using the `lrelease` command.[[1](http://doc.qt.io/qt-5/linguist-manager.html#using-lupdate)]
2. Then use the [`QTranslator` class](http://pyqt.sourceforge.net/Docs/PyQt5/api/qtranslator.html) to [load](https://doc.qt.io/qt-5/qtranslator.html#load) `.qm` files from for a specific language from a path: `translator.load("qt_ru", PATH)`
3. Add the `QTranslator` instance to the app: `app.installTranslator(translator)`

I didn't test this yet, but found some examples on SO.[[2](https://stackoverflow.com/questions/13032774/pyqt-english-to-finnish-translation), [3](https://stackoverflow.com/questions/19032805/pyqt-multiple-languages-qt-designer-auto-generated-ui)]

This takes care of the Qt UI files. for strings in ordinary Python files, the workflow will be slightly different. Hope we can still use a common format to have all translations in one place. Regarding f-strings, they may be complementary. I.e. first pull the translated string. Then fill the data by evaluating the translated string as f-string. There could also be a helper-function that does both – takes an English string, translates it if needed and fills in some data.

**Comment by ThomasWaldmann** [comment]
AFAIK, f-string expansion by the py36+ interpreter is only done on literal f-strings and only when they are first evaluated. While researching f-strings, i found https://pypi.org/project/fstring - not sure whether it's worth adding this as requirement or we rather should just transform the f-strings and use % expansion - you decide.

About having the translatable strings at 2 places (qt-style and gettext-style): that's a bit embarrassing, but I think this problem maybe has been solved already in another pyqt project that is translated.

**Comment by m3nu** [comment]
> About having the translatable strings at 2 places (qt-style and gettext-style): that's a bit embarrassing, but I think this problem maybe has been solved already in another pyqt project that is translated.

Gettext isn't needed. The said `QTranslator` class can also translate ordinary strings.

`tr("Host {0} found").format(hostName)` - from [here](https://stackoverflow.com/questions/18361182/whats-the-correct-way-to-translate-a-dynamic-string-in-pyqt) and also mentioned [here](https://kuanyui.github.io/2014/09/03/pyqt-i18n/).

An official: [example](https://github.com/baoboa/pyqt5/blob/master/examples/tools/i18n/i18n.py#L186). Note the `self.tr('some string')`

Here is also [someone](https://github.com/aarddict/desktop) who mixed gettext and QTranslator. But the above way is probably better.

**Comment by ThomasWaldmann** [comment]
Quick update:
- Have extraction from .ui and .py working (lupdate, pylupdate5, lrelease).
- QTranslator still rejecting to load the .qm file (no error msg, just returns False), need to investigate that still.

PR coming ASAP.

**Comment by ThomasWaldmann** [comment]
i'm splitting this ticket into multiple ones...

**Comment by m3nu** [comment]
It may be better to use the non-country translation tag for simplicity? E.g. just 'de' instead of 'de_DE'? I doubt there will be a 'de_CH', etc.

**Comment by ThomasWaldmann** [comment]
yes, for `de` that is rather unlikely.

but for `cn`, there is a difference between taiwan and mainland china.

**Comment by m3nu** [comment]
Yepp. Would do it like that.

**Comment by ThomasWaldmann** [comment]
Just noticed that we need to specify whether the original strings should be `en_US` or `en_GB`.

**Comment by m3nu** [comment]
`en_US` is more common, I guess. But I don't see any specific existing strings. Like color, organization, etc.

**Comment by lapineige** [comment]
> Count me in for French translation 👍

I'm also interested 😃

**Comment by m3nu** [comment]
Thanks for the interest, @lapineige . I added you to the official translation thread. See the details there.

**Comment by jose1711** [comment]
Hi, please add me to the thread. I'd like to work on translation to Slovak. Thanks!

**Comment by m3nu** [comment]
My pleasure, @jose1711. I've added a new discussion for Slovak here. Please see my response and next steps there: https://github.com/borgbase/vorta/discussions/978
