### ISSUE TITLE
libgtk3-nocsd.so.0 Error when running Vorta flatpak under Kubuntu 20.04

### ISSUE THREAD

**Issue by aaylnx** [borgbase/vorta#995]
I get the following error when I run the Vorta flatpak under Kubuntu 20.04

`ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.`

With this problem Vorta will not let me select any directories for repositories.

Any thoughts? This a bug?

**Comment by m3nu** [comment]
Please fill the whole bug template when reporting an issue.

Do you get the same error when installing via Pip?

**Comment by aaylnx** [comment]
Sorry about missing the template. Ok, here goes another try.

**Describe the bug**
On a fresh install of Vorta using the flatpak package I am unable to select any folder locations. This includes backup destinations for a new repository as well as folders as sources to be backed up.


**To Reproduce**
Steps to reproduce the behavior:
1. Open Vorta flatpak and go to the repository tab
2. Select "Initialize New Repository"
3. Click the folder icon to choose a local path as a repository and navigate to the desired directory location.
4. Select the directory for the repository and click "Open"
5. Nothing Happens

Also, if I try to manually type in the path, I get the following error message "Please enter a valid repo URL or select local path"

I do not get this problem when installing with Pip.

When starting the flatpak from the terminal I get the following output:

> ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
2021-05-28 11:42:24,272 - vorta.i18n - DEBUG - Loading translation succeeded for ['en', 'en-US', 'en-Latn-US'].
2021-05-28 11:42:24,303 - apscheduler.scheduler - INFO - Scheduler started
2021-05-28 11:42:24,496 - root - INFO - Using NetworkManagerMonitor NetworkStatusMonitor implementation.
2021-05-28 11:42:24,595 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version
2021-05-28 11:42:24,605 - vorta.borg.borg_thread - WARNING - ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Environment (please complete the following information):**
- OS: Kubuntu 20.04 - KDE Plasma Version: 5.18.5
- - Vorta version: 0.7.5 flatpak
- Installed from: Flathub

**Comment by m3nu** [comment]
> I do not get this problem when installing with Pip.

Good to know. And thanks for the details. Maybe some Flatpak sandboxing or dependency issue. @Hofer-Julian will know more.

**Comment by Hofer-Julian** [comment]
Mmmh, people definitely tested it already under Kubuntu 20.04. I would expect, that somehow the flatpak installation itself is broken. It would be interesting though to test a fresh Kubuntu 20.04 to be sure.

**Comment by aaylnx** [comment]
> Mmmh, people definitely tested it already under Kubuntu 20.04. I would expect, that somehow the flatpak installation itself is broken. It would be interesting though to test a fresh Kubuntu 20.04 to be sure.

When I have the time, I will test it out in a fresh VM of Kubuntu and report back.

**Comment by aaylnx** [comment]
Alright, I've had an opportunity to set up some VM's and test out the Vorta flatpak.

I installed on three different VMs.

1. Kubuntu 20.04
KDE Plasma Version: 5.21.4
KDE Frameworks Version: 5.80.0
Qt Version: 5.15.2

2. KDE neon 5.21 (The newest Neon based on Ubuntu 20.04)
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2

3. Ubuntu 20.04

On the Kubuntu and KDE Neon installs both the bug description and the steps needed to reproduce it are identical to the bug report I provided above.

On the Ubuntu install I had no problems whatsoever. Everything worked fine.

Seems like this is a bug related to KDE and the Vorta flatpak.

I did not get any additional output from the terminal except for on the Neon install. In the case of that install I got the following error in the terminal when I would tried to select a folder

> kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.ServiceUnknown" 
"org.freedesktop.DBus.Error.ServiceUnknown"

Does anyone else have any experience with the Vorta flatpak on a KDE based desktop?

Let me put it this way, has anyone had success running the flatpak on a KDE based desktop?

Is there anything else I can do to provide more feedback for this? I'm not a programmer, and I'm not even used to doing many bug reports, but I am happy to try and provide further feedback if that would prove helpful in trying to isolate and fix what's going on.

**Comment by aaylnx** [comment]
By the way, I should add that I did not get the error messages related to libgtk3-nocsd.so.0 which I mentioned at first in this bug report, however the experience of not being able to select folders as destinations for repos (either through the file manager or by typing in the path) was exactly the same on the two VM installs I did.

**Comment by Hofer-Julian** [comment]
Thanks alot @aaylnx for investigating.
At the moment indeed none of the core contributors uses KDE. A former one used it under Fedora, I have to check if that makes a difference. It might take a bit to find the root of this problem, so maybe we should add a disclaimer regarding flatpak + kde + ubuntu combo.

**Comment by aaylnx** [comment]
Well, I decided to try installing the Flatpak under Fedora, so I spun up a VM of Fedora 34 KDE spin and I get the same exact problems I had with KDE on Kubuntu and Neon. I am unable to select the repository folder either through the file manager or through typing it in manually.  Seems that the flatpak works fine in a Gnome environment, but there's a problem in Plasma for sure.

**Comment by Hofer-Julian** [comment]
I could reproduce it on my virtual machine.
I downgraded the runtime, which solved the problem for now.
This is not a long time solution, so I hope that we are fine by just skipping one version of the runtime and not staying with the current one for too long.

Running flatpak update should be enough.

**Comment by aaylnx** [comment]
Thanks!

**Comment by francois072** [comment]
I'm currently having the exact same issue.

> I downgraded the runtime, which solved the problem for now.

What command should I run? @Hofer-Julian

**Comment by Hofer-Julian** [comment]
flatpak update com.borgbase.Vorta

**Comment by francois072** [comment]
> flatpak update com.borgbase.Vorta

Thanks but I already updated Vorta. I though that I should downgrade the KDE runtime or something.

**Comment by aaylnx** [comment]
To me it looks like the problem was related to a problem in KDE Frameworks which now appears to be fixed. This will take a little while to roll out to distros though. Check out this link.

http://www.tuxmachines.org/node/152236

**Comment by francois072** [comment]
Luckily I run Manjaro so it shouldn't take too long. :smiley:
